### PR TITLE
Using ECS to deploy a docker app to AWS

### LINKED ISSUE #2231: Using Elastic Container Service to Deploy a Docker App to AWS
### Proposed title of article
Using Elastic Container Service to Deploy a Docker App to AWS

### Introduction paragraph (2-3 paragraphs):
Elastic Container Service (ECS) is a cloud computing services provided by Amazon Web Services to manage containers and allow developers to run applications in the Cloud without having to configure an environment for the code to run. 

ECS was developed by Amazon in response to the rise of containerization. ESC enable developers to easily use Docker containers for a wide range of activities from hosting to running complex micro services that require thousands of containers.

 In this article I will explain a step-by-step procedure of deploying a Docker based application to Amazon web pages using elastic container service.

### Key takeaways: 
Setting up AWS Command Line Interface
Building a Docker based app using flask
Deploying a Docker container to AWS

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by victorelvice**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2231

### CODE REVIEW

**Comment by victorelvice** [comment]
Hi @srishilesh.  This is the duplicate PR fixing the #2231 issue and #2278 PR merge conflict. Check it out.

Thank you!

cc @hectorkambow

**Comment by srishilesh** [comment]
Hey @ahmadmardeni1 / @louisefindlay23,

This PR is duplicate of https://github.com/section-engineering-education/engineering-education/pull/2278

Could you please give this duplicate PR a final review? The author has been waiting too long to get his article published

@victorelvice Sorry to keep you waiting.

cc. @hectorkambow

**Review by srishilesh — APPROVED** [review]

**Comment by ahmadmardeni1** [comment]
Sure @srishilesh I will do the final review ASAP

**Comment by ahmadmardeni1** [comment]
This article needs a plagiarism check @srishilesh 
cc @hectorkambow

**Comment by hectorkambow** [comment]
Plagiarism check done @ahmadmardeni1 

The 1st sentence needs a source. 👀 

https://searchaws.techtarget.com/definition/Amazon-EC2-Container-Service

**Comment by ahmadmardeni1** [comment]
@srishilesh victorelvice is a first-time contributor.
@victorelvice Please upload your info+picture in the correct structure.

**Comment by srishilesh** [comment]
> @victorelvice Please upload your info+picture in the correct structure.
> @srishilesh victorelvice is a first-time contributor. Ping me when he uploads it👀

@ahmadmardeni1 
Oops. Did not notice that.

He did upload his info in the previous PR.

Will ping you after adding it here. Thanks for letting me know.

**Comment by srishilesh** [comment]
@ahmadmardeni1 

It's ready for final review.

I've added the author info. Please let me know if I have missed out anything.

cc. @victorelvice

**Comment by ahmadmardeni1** [comment]
Don't worry about it! I will do the final review Asap @srishilesh

**Pull request merged**
