### PR TITLE
Java Exception Handling

### LINKED ISSUE #2923: Java Exception Handling
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Java Exception Handling

### Introduction paragraph (2-3 paragraphs):
Errors can occur at any time in programs but what matters is the way we handle them and rectify them to maintain the normal flow of our application. Java being the most prominent object-oriented programming language provides a powerful mechanism to handle these errors and exceptions that occur. `Exception handling` in Java is one of the most powerful tools for dealing with run-time errors like `ClassNotFoundException`, `IOException`, `SQLException`, and `RemoteException`, among others. Effective exception handling makes your program more robust and easier to debug. This article will go through the fundamentals and various methods of java exception handling.

### Key takeaways: 
1. What is Exception Handling
2. Comparison between errors and exceptions
3. Exception hierarchy
4. Types of Exceptions
5. How to implement Exception handling

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Dawe-7**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2923

### CODE REVIEW

**Comment by Dawe-7** [comment]
@BrianaNzivu, any progress?

**Comment by BrianaNzivu** [comment]
Hey @Dawe-7 👋🏾.

Working on it.
 
Due to unavoidable personal circumstances, I have not been able to work on your article this last week. 
I'd like to apologize for the delay.

Expect updates by the end of the day. 

Regards.🚀

**Comment by hectorkambow** [comment]
@Dawe-7 

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Java Exception Handling #2985.pdf](https://github.com/section-engineering-education/engineering-education/files/6919957/Java.Exception.Handling.2985.pdf)

**Comment by Dawe-7** [comment]
@hectorkambow, I've fixed the plagiarism. Could you kindly run another plagiarism check.

cc: @BrianaNzivu

**Comment by hectorkambow** [comment]
@Dawe-7 
The % is still pretty high - we typically like to go for 10% or less. 

not sure if its boilerplate or what causing this 🤔 
[Java Exception Handling #2985 2nd.pdf](https://github.com/section-engineering-education/engineering-education/files/6955808/Java.Exception.Handling.2985.2nd.pdf)

**Comment by Dawe-7** [comment]
> @Dawe-7
> The % is still pretty high - we typically like to go for 10% or less.
> 
> not sure if its boilerplate or what causing this 
> [Java Exception Handling #2985 2nd.pdf](https://github.com/section-engineering-education/engineering-education/files/6955808/Java.Exception.Handling.2985.2nd.pdf)

@hectorkambow 
Some of the plagiarism occurring from the code are required boilerplate but I've worked on the plagiarism and managed to fix it. Could we kindly run another plagiarism check.

cc: @BrianaNzivu

**Comment by hectorkambow** [comment]
plagiairism check done 👍 @BrianaNzivu

**Review by BrianaNzivu — APPROVED** [review]
Hey @Dawe-7 👋 .
The article is a very interesting read. Good job!
Just a few things I'd like to point out:
1.  It is always advisable to submit an article that is well polished. By this, I mean having an article that does not have too many grammatical corrections and functional code. I suggest that you check out our [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) page which has links to various resourceful tools for writing. 
2. When it comes to plagiarism, always try and run your article on [Quetext](https://www.quetext.com/) to avoid any extra revision round.  You can also use [Quilbot](https://quillbot.com/) to paraphrase some statements.
3.Lastly please go through all the corrections I have made so that you can not repeat the same mistakes.

That's it! :smile: 

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

**Review by kayere — APPROVED** [review]
Great article @Dawe-7, very informative. Please go over my changes to help improve the flow and format of your future articles.

cc @BrianaNzivu

**Pull request merged**
