### PR TITLE
Managing Docker Containers using Command Line Interface

### LINKED ISSUE #2891: Managing Docker Containers using Command Line Interface(CLI)
### Proposed title of article
Managing Docker Containers using Command Line Interface

### Introduction paragraph (2-3 paragraphs):
If you are managing numerous Docker Containers simultaneously, you might have noticed that this is indeed a very hefty task. In this article, we will learn some top ways that can be very handy for you to manage Docker Containers straight from the Command Line Interface. We will see practical examples of the most commonly used yet very effective and efficient Docker Commands that would surely make your Docker experience seamless.

### Key takeaways: 
By the end of this article the reader will be able to manage docker containers by:
1. Running a Docker Container in Interactive Shell.
2. Remove all the Dangling Volumes
3. Removing Docker Containers and Images
4. Using Aliases.
5. Inspecting Docker Containers .

### References: 
N/A

### PR DESCRIPTION
**Pull request by Wanyoike-shift**
Managing Docker Containers using Command Line Interface

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
 This fixes #2891

### CODE REVIEW

**Comment by Bayler** [comment]
Hi @Wanyoike-shift Welcome to our Engineering Program! I will be reviewing your article.

On first glance, I noticed that your hero image is blurred with black shadows on the edges. Please re-upload a clearer hero image, preferably a high resolution image (600px by 400px) without the black shadows at the edges. Do that first then I can continue with the review.

**Comment by Wanyoike-shift** [comment]
Hello @Bayler I am sorry I deleted the branch that contains this article.
Am I supposed to create another PR or what am I supposed to do  so that I can be able to edit the article.

**Comment by smkinyan** [comment]
@Wanyoike-shift You'll have to re-submit this PR. I've realized I can't edit the PR. I think it's because you deleted the branch. Created a new PR then close this one. Make sure you create a new branch while creating a new PR

**Comment by Bayler** [comment]
@Wanyoike-shift You'll have to re-submit this PR. I've realized I can't edit the PR. I think it's because you deleted the branch. Created a new PR then close this one. Make sure you create a new branch while creating a new PR

**Comment by Bayler** [comment]
This is the new PR #3127

**Pull request closed without merging**
