### PR TITLE
Understanding the downsides of load balancing

### LINKED ISSUE #5029: Understanding the downsides of load balancing
#### Proposed title of article
Understanding the downsides of load balancing

#### Proposed article introduction
A single server cannot handle all the workload of a given application. It is likely to experience issues with performance, availability, and economics.
In order to handle increased traffic, increasing the capability if processing requests is required and can be achieved either by scaling up or scaling out.
However, the machine fails at times and the cost of using high specification machine may be huge to even afford. Spreading the workload over multiple machines may be a better approach, hence use of load balancing is recommended. But this approach may experience several challenges. In this article, we will cover some of the challenges and possible solutions.

#### Key takeaways 
At the end of this article the leaner will understand:
- the concept of load balancing and several approaches to achieve it
- the advanced challenges of load balancing
- the possible solutions that can be implemented to curb the challenges

#### Article quality
The article will concentrate more on the advanced challenges and their possible workarounds experienced with load balancing

#### References
N/A

### PR DESCRIPTION
**Pull request by martha-ngugi**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #5029

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Kayere** [comment]
Plagiarism check done.

**Review by collins-a — CHANGES_REQUESTED** [review]
Hey @martha-ngugi, good article on load balancing. However, please review your paragraphing. I advise you to have at least three sentences per paragraph to avoid making segments of the article look like an unpunctuated list.

Ping me when done, then we'll be ready for the final review.

**Comment by martha-ngugi** [comment]
> Hey @martha-ngugi, good article on load balancing. However, please review your paragraphing. I advise you to have at least three sentences per paragraph to avoid making segments of the article look like an unpunctuated list.
> 
> Ping me when done, then we'll be ready for the final review.

Hi @collins-a, the changes requested has been made and taken a note on them. You can proceed with the review process.
Thank you.

**Review by collins-a — APPROVED** [review]

**Comment by hectorkambow** [comment]
Just saw you had this PR assigned @WanjaMIKE

**Comment by WanjaMIKE** [comment]
Finishing up @hectorkambow

**Comment by WanjaMIKE** [comment]
Merged #5288 into master

**Pull request merged**
