### PR TITLE
How To Deploy A Streamlit App With Docker

### PR DESCRIPTION
**Pull request by Bravinsimiyu**
-  Added a folder called how-to-deploy-a-streamlit-app-using-docker
-  Added an index.md, data.png, female-prediction.png, hero.png, index.png, male-prediction.png files.
This article gives a detailed description on how to deploy a simple streamlit app withdocker.
We first build a simple machine learning model, then we add its user interface using streamlit, then we finally deploy it using docker.

### CODE REVIEW

**Review by kayere — CHANGES_REQUESTED** [review]
Hello @Bravinsimiyu - Welcome to section's engineering program. Thank you for submitting your first article. I am just done with the preliminary review and I have made some suggestions. Overall, you have chosen good topic to explore, the only issue is your grammar. I'd suggest you work on your grammar so as to make the review process easier and faster. Also, make sure you review your article before submitting it so as to catch any typos made. Lastly, try as much as possible to use descriptive headings. 

Please go over my suggestions and ping me when you are done or have any enquiry.

**Comment by kayere** [comment]
Also, link the issue to this PR.

**Comment by Bravinsimiyu** [comment]
Hello, once I have made all the changes should I open another PR or how do
I submit the changes I have made?

**Comment by kayere** [comment]
Pushing your commits should be enough. Your changes have been applied. I'll
get to the review ASAP.

**Comment by kayere** [comment]
Hello @Bravinsimiyu - Have noticed that you have not added my suggestions. Please do so by committing the suggestions you see fit before we proceed to tech review. Use the `Commit suggestion` button to add commits.

**Comment by Bravinsimiyu** [comment]
This fixes #2454

**Comment by Bravinsimiyu** [comment]
Hello, @kayere I have made the requested changes, please review.

**Review by kayere — APPROVED** [review]
Good work making the changes @Bravinsimiyu - Your article is now ready for final review.

**Comment by hectorkambow** [comment]
@Bravinsimiyu 

The .csv file can not be included in the PR - it can not be published to the site. 

What is this file for?? Can it be included some other way - as a link - as a seperate file or repo that links out.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by Bravinsimiyu** [comment]
Hello @hectorkambow the .csv is the dataset used, but I have removed it from the PR and added an external link

**Comment by hectorkambow** [comment]
great work gents @Bravinsimiyu 

cc @kayere  

Please be sure to go through my final edits to better improve future articles and reviews. 🚀

**Comment by Bravinsimiyu** [comment]
Yeah I will, So what next?

**Comment by Bravinsimiyu** [comment]
Yeah, I will,  @hectorkambow  so what next?

**Comment by hectorkambow** [comment]
> Yeah, I will, @hectorkambow so what next?

Payouts tend to go out once a week - usually on Friday or over the weekend. 

Now you can continue to explore more topics - but submitting a topic form for approval 🚀

**Comment by Bravinsimiyu** [comment]
Hello @hectorkambow I'm having issues joining sectionio-community on Slack, could you send me the invitation link

**Comment by Bravinsimiyu** [comment]
Hello @hectorkambow my payment in paypal is on hold, can you can you confirm receipt on your end so that the money can be released.

**Pull request merged**
