### PR TITLE
Introduction To PHP Graphic Techniques

### LINKED ISSUE #4768: Introduction to PHP graphic techniques
####Proposed title of article
[Languages] Introduction to PHP graphic techniques 

####Proposed title introduction
PHP has the Inherent ability to create and manipulate graphics independently. The scope and capabilities of PHP graphics handling is indeed deep and powerful. It does this with the aid of the GD library which currently supports image formats in JPEG, png, gif and wbmp. 
    This tutorial aims at giving a solid foundation to intended readers on the first steps to take in this graphics journey. It is an intended intro to follow up graphics tutorials that I intend to publish here. 

Key takeaways
i.	Readers will learn how to create a canvas, ink and paint brush.
ii.	Readers will learn how to draw geometric shapes such as rectangles, polygons e.t.c
iii.	Readers will learn how to write words on the canvas.

### PR DESCRIPTION
**Pull request by SarahAsuquo**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4768

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Review by jumamiller — APPROVED** [review]
Hi, @SarahAsuquo I honestly loved every single tech review process on this article. Looking forward to more!

To proceed to the final review, kindly update your author details, we usually prefer the folder name to be in small letters i.e `sarah-asuquo` and not `Sarah-Asaquo`. Kindly update.

> If you have any questions, kindly reach out

**Comment by SarahAsuquo** [comment]
Authors details has been updated as requested.
@jumamiller

**Review by jumamiller — APPROVED** [review]
Approved!

**Comment by srishilesh** [comment]
@jumamiller 

Make sure to assign yourself to the PRs that you are reviewing.

**Comment by ahmadmardeni1** [comment]
Why do you a duplicate of every picture? @SarahAsuquo 
cc @jumamiller

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
