### PR TITLE
Deploy flask to gce

### LINKED ISSUE #3269: Deploying a Flask application to Google Compute Engine
### Proposed title of article
Deploying your application to Google Virtual Machine

### Introduction paragraph (2-3 paragraphs):
Google provides a deployment virtual machine that relieve users from the acquisition of complex and expensive infrastructure required to run some application. Through their Infrastructure as a Service (IaaS) platform, Google provides an underlying infrastructure with easy setup for deployment of most applications.

This tutorial is a guideline on how to deploy an application on Google Compute Engine. I am a JavaScript fanatic so in my explanation, I will use Python to build a Flask web application application as a starting point. I will take the reader through the process of building the application to final deployment where we access the application from a unique IP address.

### Key takeaways: 
1. Working with Google Cloud Platform(shell & editor)
2. Building application on Google Cloud Platform
3. Creating virtual machine on Google Cloud Shell
4. Deploying applications to Google Virtual Machines.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by ryanjonnes**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3269

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Comment by ahmadmardeni1** [comment]
I think this article is light on substance. What do you think? @mercymeave

**Comment by mercymeave** [comment]
> I think this article is light on substance. What do you think? @mercymeave

I followed with the article. I think @ryanjonnes should provide screenshots of deployment and explicitly explain the procedures of deployment.

**Comment by ryanjonnes** [comment]
Sure Mercy. Working on that just now!

**Comment by hectorkambow** [comment]
cc @section-engineering-education/content-moderator-team

**Comment by ahmadmardeni1** [comment]
The cloud-shell image does not exist. Can you upload it please? @ryanjonnes

**Comment by ahmadmardeni1** [comment]
Welcome to Section EngEd @ryanjonnes And congrats on your first article 🎉

The "cloud-shell" and "Deployed" images do not exist. Please upload them and I will publish your article.

**Comment by mercymeave** [comment]
Hello @ryanjonnes 

KIndly work on the changes requested by @ahmadmardeni1 then ping me to open the pr.

Its not much. Just upload the images.

**Comment by ryanjonnes** [comment]
Sorry @mercymeave  and @ahmadmardeni1 

I must have missed the two.

**Comment by mercymeave** [comment]
Hello @ryanjonnes 

Thanks for making the changes.

@ahmadmardeni1  would you please give the PR  final review?

**Comment by mercymeave** [comment]
Hello @ryanjonnes 

Thank you for fixing the changes. @ahmadmardeni1  please give it a final review.

**Comment by ahmadmardeni1** [comment]
Congrats on your first article 🎉 @ryanjonnes 

Thank you for the review @mercymeave

**Pull request merged**
