### PR TITLE
Getting Started With .NET MAUI To Build Cross-Platform Apps In Visual Studio

### LINKED ISSUE #5150: Getting Started With .NET MAUI To Build Cross-Platform Apps In Visual Studio
### Topic Suggestion
Getting Started With .NET MAUI To Build Cross-Platform Apps In Visual Studio

### Writing sample(s): 
https://www.section.io/engineering-education/different-techniques-of-encoding-data-for-transmission/

#### Proposed title of the article
Getting Started With .NET MAUI To Build Cross-Platform Apps In Visual Studio

#### Proposed article introduction
.NET MAUI is a cross-platform framework that is used to create native desktop and mobile applications. It is the most productive way to create, performant Android, iOS, macOS, and Windows Apps, all from a single code base. It is an evolution of Xamarin.Forms and extended from desktop scenarios with UI controls.

In this tutorial, I will be taking the reader through the concept of .NET MAUI in visual studio. I will implement this by use of a demo project that will take the reader through the procedure of building a .NET MAUI Application.

#### Key takeaways 
From this tutorial, the reader will understand;
- the concept of the .NET MAUI framework.
- how to build cross-platform applications using the .NET MAUI framework
- the importance of the .NET MAUI framework to the .NET developers

#### Article quality
This tutorial targets developers who want to write cross-platform apps in XAML and C#, from a single shared code-base in Visual Studio, and share UI layout and design across platforms. I will be getting information from different sites to ensure that I cover each and every part and provide the knowledge needed to the reader.

#### References
N/A.

### PR DESCRIPTION
**Pull request by Geo-free**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [X] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #5150 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your article for publishing. 
With the recent increase in article volume out team has been working diligently to review every article. Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by Kayere** [comment]
Plagiarism check done.

**Comment by Kayere** [comment]
Great article @Geo-free.

@LinusMuema - Please give this PR a final review.

**Comment by LinusMuema** [comment]
Hi @Geo-free 

Great job on the article.

cc: @Kayere

**Pull request merged**
