### PR TITLE
How to Create a Carousel Using React Class Components and Tailwind CSS

### LINKED ISSUE #3864: How to Build a Responsive Image Carousel in React
### How to Build a Responsive Carousel in React 
An image carousel is a slideshow of images that helps improve the user's experience of a website. The slideshow can be automated(where the transition from one image to another is controlled by timers), controlled by a click of buttons, or a combination of both.

In this article, we will cover how we can create the image carousel in React and style it with CSS to make our website more interactive improve the user experience.

### Prerequisites: 
To follow along in this tutorial, you need to have:
- Basic CSS knowledge
- Basic React Knowledge

### PR DESCRIPTION
**Pull request by kimanikevin254**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3864

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by louisefindlay23** [comment]
@kimanikevin254, please follow the Topic Suggestion This Closes instructions because adding this closes in a further comment does not work.

**Comment by WanjaMIKE** [comment]
Kindly, let another reviewer to take up this PR. You have more PRs on your plate and they are not ready for final reviews.

**Comment by hectorkambow** [comment]
Pinged reviewer via Slack as well.

**Comment by kimanikevin254** [comment]
@hectorkambow

I have done everything and my code is working so I'm just waiting for the reviewer's reply.

**Comment by kimanikevin254** [comment]
@zolomohan, any feedback?

**Comment by hectorkambow** [comment]
@section-engineering-education/content-moderator-team 

Team can we please take a look at this (it just need a tech review) & final review. 

I've pinged the peer reviewer on 10/22 - with no major response. 

Thank you 👀

**Comment by Kayere** [comment]
On it ✔️

**Review by Kayere — APPROVED** [review]

**Comment by Kayere** [comment]
@WanjaMIKE and @ahmadmardeni1 - could you please give this article a final review.

**Comment by ahmadmardeni1** [comment]
Great work gentlemen @Kayere @kimanikevin254

**Comment by hectorkambow** [comment]
> @WanjaMIKE and @ahmadmardeni1 - could you please give this article a final review.

@Kayere  

Thank you Gents 🚀 💪

**Pull request merged**
