### PR TITLE
[Duplicate of #5899] - How to use Symbolic Math toolbox in Matlab to analyze Fourier series

### LINKED ISSUE #5639: How to use symbolic math's toolbox in Matlab to analyze the Fourier series.
### Topic suggestion
How to use symbolic math's toolbox in Matlab to analyze the Fourier series.

#### Introduction
Symbolic Math Toolbox provides functions for solving, plotting, and manipulating symbolic math equations. You can create, run, and share symbolic math code. The toolbox provides functions in common mathematical areas such as calculus, linear algebra, algebraic and differential equations, equation simplification, and equation manipulation. We want to see how this toolbox can be used to solve fourier series.
In this tutorial, the Fourier series is implemented and simulated using Symbolic Math's Toolbox of MATLAB. Both the forms of the Fourier series i.e. Trigonometric and Exponential are implemented. The proposed programs are versatile and have the capability to receive any function of t. The program gives plots of harmonics, original function and approximated function, Magnitude spectrum and Phase spectrum.

#### Key takeaways 
- Trigonometric Fourier Series.
- Exponential Fourier Series.
- MATLAB Code to implement Trigonometric Fourier Series.
- MATLAB Code to implement Exponential Fourier Series.

#### Article quality
Using this toolbox maybe so tricky for a student and this article is to explain clearly and make it easy for the student to solve their problems using this toolbox.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by linetachieng**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5639 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by linetachieng** [comment]
This is a duplicate of #5899 
@hectorkambow 
cc @WanjaMIKE

**Comment by linetachieng** [comment]
@hectorkambow This is a duplicate of #5899
cc @WanjaMIKE , @srishilesh, @munubi254

**Comment by munubi254** [comment]
OK. I hope you did check the readability issues as raised by @WanjaMIKE

**Comment by srishilesh** [comment]
Assigning this PR to @munubi254 , since it was previously test-reviewed by @munubi254 . Duplicate of #5899 

@linetachieng 

Do we have any updates?

**Comment by linetachieng** [comment]
@munubi254 I had made all the requested changes.
cc @srishilesh

**Comment by munubi254** [comment]
@linetachieng, check slack ASAP.

**Comment by srishilesh** [comment]
Hey @munubi254 ,

Where are we with this review? If it needs any more revisions, please consider closing this PR.

**Comment by munubi254** [comment]
@srishilesh, you can label it as ready for final review.

**Comment by lalith1403** [comment]
Jumping on this one team 🚀

**Comment by lalith1403** [comment]
Well done @linetachieng and @munubi254. A very detailed and informative article.

**Pull request merged**
