### PR TITLE
Getting Started with Singular Value Decomposition(SVD) in Python

### LINKED ISSUE #5290: Getting Started with Singular Value Decomposition(SVD) Algorithm in Machine Learning
#### Proposed article introduction
Singular Value Decomposition(SVD) is a powerful technique that is widely used to solve a wide variety of problems in dimensionality reduction tasks. This algorithm works with a data matrix of the form m x n, where m is the number of rows and n is the number of columns. Thus the general idea for the SVD is that a rectangular matrix can be broken down into a product of three other matrices as shown in the following formula;
$A=U. \Sigma. V^T$

Where;
- A is our m x n matrix that we are interested in decomposing. This rectangular matrix can be for real numbers or for complex numbers.

- U is an orthogonal matrix
- $\Sigma$ is an m x n diagonal matrix, and 
- $V^T$ is the  transpose of an orthogonal matrix

For instance, if we have a rectangular matrix A of size m x n, then there exists an orthogonal matrix U of size m x m, an m x n diagonal matrix $\Sigma$ of size m x n, and an orthogonal matrix V^T of size n x n.

These three matrices have the following features;
First, the columns of U and V are made of the eigenvectors of A.

- Columns of U are orthonormal of eigenvectors of $AA^T$
  These columns are called the left singular vectors of A.

- Columns of V are orthonormal eigenvectors of $A^TA$
    These columns are called the right singular vectors of A.

- $\Sigma$ is an m x n diagonal matrix containing the square root from the eigenvalues from U or V in descending order.
 This diagonal entry of $\Sigma$ is called the singular value of matrix A.

All the calculations involved in obtaining these three matrices will be outlined in the article using a real matrix A. Since we shall be using a huge matrix in the real application, i.e., an image matrix, we shall also show how we can automate this computation in python.

#### Key takeaways 
By the end of this study, learner will have known;
- What is Singular Value Decomposition, and the kind of a matrix can be decomposed using this algorithm.
-  All steps and mathematical computations associated with each step of the SVD algorithm. They will understand this by having real matrix computation that we shall outline in the article. 
- Real-world applications of SVD, i.e., at Google in PageRank algorithm, previously at Facebook in image recognition, etc.
- How to perform SVD in python using a matrix sample.

#### Article quality
Since this algorithm has a wide range of applications in real world, the learner should be prepared with a deep understanding of the concept, and therefore this article will focus on offering all needed to get started with SVD such that an absolute beginner has an undoubt understanding of the concept. If that is not enough, the learner will know what function they need to run in order to decompose a matrix using SVD and how they can reconstruct the decomposed matrix in python.

#### References
N/A

### PR DESCRIPTION
**Pull request by Faith034**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5290

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. :rocket:
Thank you.

**Comment by raboba2re** [comment]
@hectorkambow @ahmadmardeni1 I will like to review this article

**Comment by lalith1403** [comment]
plagiarism check done ✔️

**Review by mercymeave — CHANGES_REQUESTED** [review]
Hello @Faith034 

You have a great article here. However, just one little issue. Your mathematical formulas are not showing correctly.  Would you please check that then get back via slack or here? 

Great article! :rocket:

**Review by mercymeave — APPROVED** [review]
Hello, @Faith034 

I think the problem is with Github's markdown compiler. The formulas work well on vscode. This was an amazing piece. Great work!

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
