### PR TITLE
Understanding daemons in Linux using Node.js

### LINKED ISSUE #6979: UNDERSTANDING DAEMONS IN LINUX USING NODE.JS
## Proposed article introduction
- A daemon process simply put is a program that runs in the background smoothly.
“Smoothly” in that even if a session in the foreground is stopped or an input mechanism is interacted with, the daemon process will continue. This is the main difference between Background tasks and daemon processes.
 - The first and obvious method we’ll showcase is using the “&”, showing vividly how it’s affected by SIGHUP and the huponexit parameter.
 We’ll then showcase the disown command including all the functionalities and how It’s affected by standard I/O.
 We’ll then showcase the nohup command with all its functionalities and how it will relate to the ampersand.
We’ll then showcase how to use the screen and Tmux command to implement a daemon process that doesn’t stop when the terminal windows are closed.
Finally, we’ll showcase forever, nodeman and pm2 which are node tools for running node applications as daemon processes.

## Key takeaways 
- Understanding the difference between background and daemon processes.	
- Understanding the effects of SIGHUP signal and huponexit on the ampersand.
- Understanding the disown command in running daemon processes.
- Understanding the nohup command in running daemon processes.
- Understanding the different node tools when running node applications as daemons.
- How to use Tmux to implement daemon processes.
- Understanding how to run a simple node.js server on the terminal as a daemon process.

## Article quality
These are all the different functionalities of how daemon processes work with nodejs servers collected into one article. It’ll be more in-depth as I’ll open up every process with its advantages and disadvantages displaying lines of understandable code as we move along.

### PR DESCRIPTION
**Pull request by osepoo**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
`This closes #6979

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Plagiarism check complete

**Review by adrianmurage — APPROVED** [review]
Hey @osepoo  👋 .

Very good job on the article. It is a very interesting read. Barely any changes to be made 👏 .

A final review will be done now by a content moderator.
Otherwise, congratulations on publishing your article🍾.

In case of any questions or clarification (currently or in the future), do not hesitate to reach out.
I am ALWAYS here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

**Comment by hectorkambow** [comment]
@adrianmurage 
Please reach to via a Slack DM 👍

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
