### PR TITLE
  SendRedirect in Servlet Collaboration

### LINKED ISSUE #4655: SendRedirect in Servlet Collaboration.
#### Proposed title of article
SendRedirect in Servlet Collaboration.

#### Proposed article introduction
Page redirection is commonly used when a document or any files are moved to a different location and we need to send the client there, or to balance the server load generated by more visitors accessing the page.
The HttpServletResponse interface's SendRedirect() method can be used to redirect a response to another resource, such as a servlet, jsp, or html file.

I'll go over the SendRedirect() in depth in this article.
#### Key takeaways 
1. Introduction
2. SendRedirect () and its significance.
3. Difference between SendRedirect() and RequestDispatcher.
4. An example of how to use SendRedirect()

#### Article quality
This article is very similar to Evans Lodoctor's Servlet Request and Servlet Collaboration article. The main difference is that Lodoctor tags in ServletDispatcha in the servlet collaboration section, whereas I'm going to use servlet collaboration in a different way. The SendRedirect()method will be used in this case. I'll also explain the differences between the two methods to help readers understand them better.

I'll make sure that this article is unique and useful to both new and experienced Java programmers. Thank you very much!

#### References
N/A

### PR DESCRIPTION
**Pull request by Chaun864**
This closes #4655

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Plagiarism check done. Please take a moment to correct the highlighted issues. Thanks

**Comment by WanjaMIKE** [comment]
[New Scan 5_18 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7506780/New.Scan.5_18.PM.Copyleaks.Report.pdf)

**Comment by Chaun864** [comment]
> Plagiarism check done. Please take a moment to correct the highlighted issues. Thanks


Hello @WanjaMIKE? Java's imported packages and predefined methods account for the majority of the plag. The code will not run if I try to rewrite it. Thank you.

**Comment by Chaun864** [comment]
> The explanation is highlighted.

Done.

**Comment by paulodhiambo** [comment]
@Chaun864 please add a link to complete source code.

**Pull request merged**
