### PR TITLE
Best URL Structure To Improve Search Engine Optimization

### LINKED ISSUE #6307: Best URL Structure To Improve SEO
### Topic Suggestion
Best URL Structure To Improve SEO

### Writing sample(s): 
N/A
#### Proposed title of article
Best URL Structure To Improve SEO

#### Proposed article introduction
Performance is a standard consideration when developing a website. Developers take into account numerous undertakings to ensure their creation perform in an optimized manner. Good SEO practices can increase the popularity of a  website let alone its monetization ability. Additionally, better SEO tactics ensure that a site ranks on the top list of the popular search engines such as Google and Bing. Among the methods of conforming to most practiced SEO techniques is through URL structure optimization.

#### Key takeaways 
In this article you will learn about:
- What is URL structuring. 
- Importance of improving your URL struture.
- Tips on optimizing your next URL.
#### Article quality
The article will feature a deeper dive into the art of URL structuring. Other articles on the web feature a shallow coverage of the topic while this article seeks to hold the reader into the different way they can optimize their next URLs.

#### References
N/A

### PR DESCRIPTION
**Pull request by selina-maina**
#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [X] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #6307

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Plagiarism check complete

**Comment by selina-maina** [comment]
hello @collins-a just to bring your attention to this article.

**Review by selina-maina — COMMENTED** [review]
Hello @collins-a  I have made the needed corrections and thank you for the kind remarks.

**Review by collins-a — APPROVED** [review]

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
@selina-maina  

After a short (final) review it stuck us that the article topic is widely covered on other sites - and the material was not that extensive. 
 
 
 Found myself making some changes for flow along the way as well. 
 
 We will be closing this topic - thank you very much we look forward to another topic submission.

**Pull request closed without merging**
