### PR TITLE
speech to text app with Javascript using web speech API

### PR DESCRIPTION
**Pull request by prince-joel**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by zolomohan** [comment]
Hey @prince-joel. Seems like your article is very similar to this article which has been published already. 
https://www.section.io/engineering-education/speech-recognition-in-javascript/

cc @hectorkambow.

**Comment by hectorkambow** [comment]
> Hey @prince-joel. Seems like your article is very similar to this article which has been published already. Please check articles that have been published already before submitting your idea or the article to avoid overlap.
> 
> https://www.section.io/engineering-education/speech-recognition-in-javascript/
> 
> cc @hectorkambow.

Great catch @zolomohan  

Thank you for pointing this out 🚀 

@prince-joel Please be sure to go through the items. 

We always want to ensure our topics don't overlap but instead build off each other.

**Comment by hectorkambow** [comment]
@prince-joel Please place the Topic form this PR is tied to 👍

**Comment by hectorkambow** [comment]
https://github.com/section-engineering-education/engineering-education/issues/2204

**Comment by hectorkambow** [comment]
@prince-joel Any update on this PR - is it ready to be reviewed and published?? 

Based on the comment about it overlapping?

**Comment by prince-joel** [comment]
@hectorkambow  there is an overlap, I will have to close the issue. Or can I write it in another language like python?

**Comment by hectorkambow** [comment]
Writing it in another Language (that has not been covered) should be a good option 👍 - please double check that we dont have that in our library. 

🚀

**Comment by hectorkambow** [comment]
@prince-joel 

Just wanted to follow up on this PR - you are welcome to continue with a new language as mentioned before. 
We can either re-open this PR - or it may be better to just open a fresh Pull Request with the new article when ever you are ready. 

Mention this PR and the old topic form in the new one 👍 

Thank you - just closing it to clear up the queue- can be reopened at any time if needed

**Pull request closed without merging**
