### PR TITLE
Model explanation with Dalex

### LINKED ISSUE #6788: [Machine Learning] Model explanation with Dalex
#### Proposed title of article
[Machine Learning] Model explanation with Dalex

#### Proposed article introduction
Model explanation allows human users to comprehend and trust the results and output created by machine learning algorithms. Dalex is used to describe an AI model, its expected impact and potential biases. It helps characterize model accuracy, fairness, transparency and outcomes in AI-powered decision making. It is crucial for an organization in building trust and confidence when putting AI models into production. Model explainability also helps an organization adopt a responsible approach to AI development.

Dalex has a set of tools and frameworks to help you understand and interpret predictions made by your machine learning models. Understanding how an AI-enabled system has led to a specific output.  Explainability help developers ensure that the system is working as expected, it might be necessary to meet regulatory standards.

Dalex contrasts with the concept of the  black box in machine learning where even its designers cannot explain why an AI arrived at a specific decision. Model explanation will determine the logical reasoning of the model when making a prediction and explains the decisions made by the model.

#### Key takeaways 
1. Black box vs transparent/glass box models.
2. Benefits of model explanation.
3.  Dalex installation and Dalex `explain ()` function.
4.  Building a customer churn model  using Logistic Regression.
5. Explaining the customer churn model using Dalex.

#### Article quality
This article is unique because it will enable us to build a full transparent model. It is crucial for an organization to have a full understanding of the AI decision-making processes with model monitoring and accountability of AI. It also enable stake holders not to trust them blindly. Using the Dalex functions and methods, users will be able to understand and explain machine learning (ML) algorithms, deep learning and neural networks. This tutorial will use step-by-step guide of how to explain a customer churn model.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by simonkamau497**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6788

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Review by jerimkaura — CHANGES_REQUESTED** [review]
Hey @simonkamau497 

This is a wonderful piece for your first article. However, before you get to the data exploration stage, why don't you help out readers set up their development environment. You jumped straight into coding but I do feel some might get confused.

Second, I got the error below while trying to run the code in vs code. Would you please fix the issue so that readers don't run into such errors?
Screenshot 2022-03-12 at 21 43 35

Otherwise, you have a great article.

Thanks.

Otherw

**Comment by LinusMuema** [comment]
plagiarism check done ✅

**Comment by simonkamau497** [comment]
Hello @jerimkaura, I have made the changes. Also, consider using Google Colab notebook to run the code so that you can get the same results.

Thanks.

**Comment by hectorkambow** [comment]
Fantastic 👍

Please be sure to proofread the entire article as Peer Reviewers do not provide revisions services (and may not point out all pending issues).

If any other major edits are required @jerimkaura  we can close the PR to allow the student the proper time to make the edits.

**Comment by jerimkaura** [comment]
Great work @simonkamau497 

The code runs perfectly on colab.

@hectorkambow

**Comment by jerimkaura** [comment]
Hello @simonkamau497 

I cant find the image `metrics-score.png`. Kindly confirm if you didn't upload it then we wind up.

**Comment by simonkamau497** [comment]
Hello @jerimkaura, I have changed the `metrics-score.png`  to `performance-scores.png`. This is the image I had uploaded. I just forgot to match the names.

Thanks.

**Review by jerimkaura — APPROVED** [review]
Great article @simonkamau497 

Check on the changes made to improve your future articles.

Great work overall 🎉

**Comment by hectorkambow** [comment]
👀  

Will be closing this PR if more edits are required by the author (to be taken out of the queue). 

@simonkamau497 

cc @simonkamau497

**Pull request closed without merging**
