### PR TITLE
Implementation of CI/CD in C/C++ Application(Linux) Using Shell and Docker Executor on GitLab

### LINKED ISSUE #2621: Implementation of CI/CD in C/C++ Application(Linux) Using Shell and Docker Executor on GitLab
### Proposed title of article
Implementation of CI/CD in C/C++ Application(Linux) Using Shell and Docker Executor on GitLab

### Introduction paragraph (2-3 paragraphs):
Many executors with GitLab Runner are available for implementing CI/CD. Nevertheless, Shell and Docker are more popular with them and with these runners we can easily create a repository. These runners can be chosen based on the requirements and availability of the resources. 
This article focuses mainly on the C/C++ Linux application's Shell and Docker executor and code in the Bash script is written. A bash script can be used to build and test the application.

### Key takeaways: 
In this article, the reader will understand:
1. what docker and shell executors are.
2. implementation of C/C++ on Shell Executor.
3. implementation of C/C++ on Docker Executor

### References: 
N/A

### PR DESCRIPTION
**Pull request by carteblanchemunene**
…ocker Executor on GitLab

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2621

### CODE REVIEW

**Comment by hectorkambow** [comment]
@carteblanchemunene 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀

Thank you.

**Comment by hectorkambow** [comment]
@carteblanchemunene 

👋 Good afternoon - and welcome to the EngEd program.
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Implementation of CICD in CC++ Application(Linux) Using Shell and Docker Executor on GitLab #2822.pdf](https://github.com/section-engineering-education/engineering-education/files/6803452/Implementation.of.CICD.in.CC%2B%2B.Application.Linux.Using.Shell.and.Docker.Executor.on.GitLab.2822.pdf)

**Comment by carteblanchemunene** [comment]
hello @hectorkambow 
plagiarism error corrected, please check.
 thank you

**Comment by carteblanchemunene** [comment]
Hello @paulodhiambo
Hope you are doing great.
Wish to inquire the progress of this article.

**Comment by paulodhiambo** [comment]
@carteblanchemunene I am reviewing it now.

**Comment by carteblanchemunene** [comment]
Hello @paulodhiambo whats the progress of my article?

**Comment by paulodhiambo** [comment]
@carteblanchemunene amazing tutorial. @hectorkambow you can give it a final review.

**Comment by ninjaginja** [comment]
@carteblanchemunene I'm jumping in here while @hectorkambow is out of the office (this week). As has been noted in earlier comments, your article seems to replicate the article [here](https://www.geeksforgeeks.org/implementation-of-ci-cd-in-c-c-applicationlinux-using-shell-and-docker-executor-on-gitlab/). Unfortunately, we cannot publish content that infringes on another author's intellectual property. This article requires substantial re-working in order to meet our requirements as original content. I would advise either revisiting the approach that you take with this topic (such as applying the concept within a unique project), or exploring a different topic area.

**Pull request closed without merging**
