### PR TITLE
[Duplicate of #4236]: How to create a responsive React navigation bar using PrimeReact

### LINKED ISSUE #3847: How to create a responsive React navigation bar using PrimeReact
**Proposed title of article**

   How to create a responsive React navigation bar using PrimeReact.

**Introduction paragraph:**

  React.js is one of the most common JavaScript library used for building client-side rendering websites. This allows developers to make their website entirely rendered in the browser with JavaScript. 

   In this article, we will create a responsive React navigation bar using PrimeReact, which is a UI component library for React.js.

**Key takeaways:**
 
1.  What is PrimeReact.
2.  How to add PrimeReact library to react.js project.
3.  How to import and use PrimeReact components.
4.  How to make our navigation bar responsive using PrimeReact.

**References:**
N/A

### PR DESCRIPTION
**Pull request by Geraldoeze**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #3847

### CODE REVIEW

**Comment by Geraldoeze** [comment]
@WanjaMIKE I've created a new PR and added more contents to my article.

**Comment by hectorkambow** [comment]
@srishilesh 
can we get a status on this PR ? 

If any more major revisions are needed - we will be closing this PR asap. 👀

**Comment by srishilesh** [comment]
> @srishilesh 
> can we get a status on this PR ? 
> 
> If any more major revisions are needed - we will be closing this PR asap. 👀 

@hectorkambow 

This is a duplicate of #4236, and it was previously reviewed by @zolomohan . So, I had this PR assigned to him.

If @zolomohan is unavailable to take up this, I can take it up and review this?

**Comment by zolomohan** [comment]
@hectorkambow @srishilesh Somehow didn't notice this PR was assigned to me. Getting right on it.

**Comment by srishilesh** [comment]
@zolomohan 

As you had requested in Slack, I'll take this up for review.

**Comment by srishilesh** [comment]
Jumping in for the tech review.

**Review by srishilesh — APPROVED** [review]
@Geraldoeze 

Good job.

I've made some major changes to the flow and formatting.

Make sure to go through my changes, as well the changes made by the previous reviewer, before you get started with your next article.

Moving for the final review.

Thanks.

**Comment by hectorkambow** [comment]
Please be sure to go over any edits made by your peer reviewer to improve future articles and reviews and prevent any PR closure.

**Comment by Geraldoeze** [comment]
@hectorkambow
Thank you.
I will go over the edits and changes made.

**Pull request merged**
