### PR TITLE
price tracker

### LINKED ISSUE #5394: How to Build a Price Tracker with Python, Selenium and Twilio
### Writing sample(s): 
https://adamtheautomator.com/docker-save-image/https://adamtheautomator.com/github-actions-environment-variables/
https://okteto.com/blog/develop-and-deploy-a-flask-and-reactjs-app-in-okteto/index.html
https://www.section.io/engineering-education/dockerized-django-application-with-github-actions/

#### Proposed title of article
How to Build a Price Tracker with Python, Selenium and Twilio 

#### Proposed article introduction
This tutorial will teach you how to use Python and Selenium to scrape prices of product on Amazon build a price tracker with the data. The idea is this, you are going to input the product you are looking for and the price you will like the product to go below. 
Selenium and BeautifulSoup to get the prices of a particular searched product and then it will be compared with the price you expect the product to fall below. If any of the price(s) are in your expected range an SMS will be sent to you on your phone saying they are products in your price range, the number of products in your price range will also be shown too. 
I will also set up scheduled jobs which will be used to run the Python code once every day without the user's intervention.

#### Key takeaways 
- How to use Beautifulsoup with Selenium for web scraping.
- Converting different data types in Python
- How to use twilio with Python to send automated SMS.
- How to set up scheduled jobs to run Python code.
- Write Python logic for price tracking.

#### Article quality
It can't be found anywhere on the internet.

### PR DESCRIPTION
**Pull request by khabdrick**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #5394

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Plagiarism check done

**Comment by WanjaMIKE** [comment]
@khabdrick Kindly, do not make changes that will overwrite this review. Thanks

**Comment by hectorkambow** [comment]
> @khabdrick Kindly, do not make changes that will overwrite this review. Thanks

Do a git pull first to apply the edits made here - then make your changes after the git pull 👍

**Comment by khabdrick** [comment]
> > @khabdrick Kindly, do not make changes that will overwrite this review. Thanks
> 
> Do a git pull first to apply the edits made here - then make your changes after the git pull 👍 

I don't have any edits to make.

**Comment by khabdrick** [comment]
Hello @hectorkambow this article has been in the pipeline for a while, but not final review.
Is it that the article is no good enough for the blog or is there something wrong with it?

**Comment by hectorkambow** [comment]
> Hello @hectorkambow this article has been in the pipeline for a while, but not final review. Is it that the article is no good enough for the blog or is there something wrong with it?

Not sure - the team has been going through our queue - we had a big backlog at the time. 

@section-engineering-education/content-moderator-team

**Comment by hectorkambow** [comment]
Jumping on this one now

**Comment by hectorkambow** [comment]
Overall very nice job gents. This was easy to follow along 🚀

**Pull request merged**
