### PR TITLE
Security Threats for NFTS and Possible Solutions

### LINKED ISSUE #7235: [Security] Step by step to security threats of NFTS and possible solutions| hardware wallet
**### Proposal Submission**

### **Proposed title of the article**

[Security] Step by step to security threats of NFTS and possible solutions| hardware wallet

### **Proposed article introduction**

Whether online or offline, security is one of the major issues that we do have to tackle on our day to day bases.
Both companies and individuals are struggling to protect their individual properties and NFTs. As the metaverse keeps on a flight, the NFT
and digital avatars can be represented by NFTs and moved from one virtual world to another.
Allow me to demystify NFTS.
An NFT (the abbreviation for the non-fungible token ) stands for cryptographically unique tokens that are linked to digital 
and sometimes physical contents, by providing proof of ownership.

Fungible means that the token is interchangeable. For example a dollar, you can swap a dollar with another one dollar and still own one dollar.
Non-fungible means they are unique. They cannot be swapped as no two NFTs are alike. A lot of content has seen turned to NFTs, including
digital arts, movies, and music. In 2021 NFTs has exploded to mainstream leading to the creation of DEFI (Decentralised Finance)
and DAO  ( decentralized autonomous organizations). In the future, the NFT could be used to provide deeds to companies,
sell tickets, and provide marriage certificates,

In this article, the reader will learn about the step-to-step threats on NFTs and implement proper possible solutions to protect their NFTs.

**### Key takeaways**

- Understanding NFTs.
- Understanding NFT's possible threats.
- Possible NFTs security solutions.
- What does the future holds for NFT.

### **Article quality**

This in-depth tutorial will add so much value to the reader because along with learning about block chain, security threats of NFTs and possible
solutions, they will also learn about the future of NFTs.

### **References**

N/A

### PR DESCRIPTION
**Pull request by Sreign254**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #7235

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Review by BrianaNzivu — CHANGES_REQUESTED** [review]
Hey @Sreign254 👋 

Welcome to Section - EngEd.
We are happy to have you here 🚀

Very good job on the article. It is a very interesting read 👏 .

Although, your article has quite a lot of grammatical mistakes. I want you to read through and correct it using [Grammarly](https://app.grammarly.com/).

Ping me when done 🚀

**Comment by Sreign254** [comment]
Hello @BrianaNzivu , It seems you have deleted some of the contents in the index.md with your commit.

Kindly check it out, so that I can work on the revision thanks.

**Comment by Sreign254** [comment]
Hello @BrianaNzivu, I have used Grammarly to correct grammatical mistakes 🚀 . Kindly review.

Thanks.

**Review by BrianaNzivu — APPROVED** [review]
Hey @Sreign254    👋 .

Excellent job on the article. It is an exciting read 👏 .
Just a few comments:
- It is always advisable to submit an article that is well polished. I mean having an article that does not have too many grammatical corrections and functional code. I suggest you check out our [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) page, which has links to various resourceful tools for writing. 
- Please go through ALL the corrections I have made so that you can not repeat the same mistakes.

That's it! :smile: 

A final review will be done now by a content moderator.
Otherwise, congratulations on publishing your article🍾.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

**Comment by hectorkambow** [comment]
Jumping on this one

**Comment by hectorkambow** [comment]
@Sreign254 
Can you please reach out via a DM asap 👍

Thank you

**Comment by Sreign254** [comment]
Hello sir..

**Comment by hectorkambow** [comment]
Hello @Sreign254 

Are you in the [EngEd community Slack](https://join.slack.com/t/sectionio-community/shared_invite/zt-1ay0qlrc6-pSv~5iCXtETeDqcX606w1A)?

**Comment by hectorkambow** [comment]
@Sreign254 

Need some help finding your account in the database

**Pull request merged**
