### PR TITLE
[Android] Building native apps on android using JavaScript, HTML and CSS -Angular ionic

### LINKED ISSUE #4439: [Android] Building native apps on android using JavaScript, HTML and CSS -Angular ionic
#### Proposed title of article
[Android] Build native apps on android using JavaScript, HTML and Cascading Style Sheets

#### Proposed article introduction
Use of applications increases efficiency through service delivery, feedback and faster product access on phones. The main operating systems on phones are android and IOS. There is an increasing demand of customized apps and websites developed to suit businesses, individuals or even rendering a particular service. 
Having a basic knowledge of coding through of Hyper Text Mark-up Language (HTML), JavaScript and Cascading Style Sheets (CSS) are beneficial in building your applications. There is an increasing presence of an online community of developers, resource tools and free software can be accessed to build applications.
This article will focus on understanding what native applications are and how different they are when compared to hybrid and web applications. It will also focus on how JavaScript, HTML and CSS are used in developing native applications on android. Testing and troubleshooting of bugs in native applications will be covered as well.

#### Key takeaways 

•	General introduction on understanding native applications
•	How JavaScript, html and Cascading Style Sheets (CSS) works in native applications 
•	Building native apps using JavaScript , html and Cascading Style Sheets
•	Testing of built native applications 
•	Troubleshooting of bugs in built apps
•	Advantages and disadvantages of native apps built using JavaScript, html and CSS

#### References
n/a

### PR DESCRIPTION
**Pull request by Rmwamboi**
this fixes #4439

### CODE REVIEW

**Comment by LinusMuema** [comment]
plagiarism check done :heavy_check_mark:

**Comment by Rmwamboi** [comment]
Hey @BrianaNzivu,
Just pinging you to find out whether there are any recommendations you would like be addressed.

**Comment by hectorkambow** [comment]
Author pinged via Slack as well. @BrianaNzivu

**Review by BrianaNzivu — CHANGES_REQUESTED** [review]
Hey @Rmwamboi  👋.
First of all, apologies for the delayed review.
Just a few changes:
1. Your hero image should be  600 x 400  px. Also, I think, there is a typo in the name of the hero image. Kindly correct that. 
2. Kindly link your author bio so that I can add your info in the front matter.

**Comment by hectorkambow** [comment]
@BrianaNzivu I will be closing this article.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. Not a problem but it seems that this PR is still quite a bit aways from being completed. 
 
In an effort to be fair to our larger EngEd community as a rule of thumb - we can only accept content (pull requests) that are complete and fully polished articles/tutorial - meaning they are ready to be published. 
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) - this allow all revisions to be done on your forked personal repo. 
 
We will be closing this PR and please re-submit it when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 
 
>NOTE: A duplicate PR will go back into the queue and will not receive any further major revisions. A duplicate PR should be 100% ready to be published, otherwise it will be closed immediately. We encourage our new contributors to go over our [resources page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) and [new contributor folder](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors) to be better familiar with the level of quality and style we are looking to publish.
 
Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.
 
👍

**Comment by BrianaNzivu** [comment]
Hey @Rmwamboi 👋 
Just checking up on you. Did you manage to open a new PR?
Do you need help?

**Pull request closed without merging**
