### PR TITLE
Getting Started with Eigendecomposition in Python

### LINKED ISSUE #5896: Getting Started with the Eigendecomposiion in Python
### Proposal Submission

Getting Started with the Eigendecomposiion in Python

#### Proposed article introduction
Eigendecomposition is a Linear Algebra technique used in machine learning to factorize square data matrices into three matrices that are easy to work with under intense matrix transformations. For a matrix to be decomposed using the Eigendecomposition, it must be a square matrix. An Eigendecomposition of a square matrix A is given as A = VSV^-1, where;
V is a matrix of eigenvectors of matrix A,  S is a diagonal matrix of eigenvalues corresponding to eigenvector in the matrix V, and V^-1 is an inverse of V.

The general idea in Eigendecomposition is to represent a matrix by its eigenvalues and eigenvectors that is computationally less expensive than the original matrix. Moreover, this technique does not lose the matrix's information as we can retrieve the original matrix from these three components by multiplying them together.

 The benefit of Eigendecomposition can not be realized when working under small transformations, but when we are transforming a data matrix many times, say 1000 times, we can appreciate its contribution in easing the computational power needed if we were to multiply the borigin\al matrix 1000 times. For, Eigendecomposition we only need to multiply the diagonal matrix 1000 times. This is much easy with a diagonal matrix; we only take each value of the diagonal matrix and raise it to the power value given and obtain a scaled diagonal matrix. This makes the computation very easy and time-saving.

In this article we will look at the following:
- First, we shall clearly explain what Eigendecomposition is and how it is used in machine learning.
- Secondly, by hand, we will perform Eigedecomposition on a synthetic data matrix. Before we can do this first, we shall look at properties that a matrix must satisfy to be decomposed using Eigendecomposition.
- Also, we shall look at the importance of Eigendecomposition over transforming the original matrix. Here we shall compare the computation carried on a matrix with Eigendecomposition and without.
- Lastly, we will implement Eigendecomposition in python.

#### Key takeaways 
By the end of this article, a serious learner will know:
- What's Eigendecomposition
- What are properties a matrix must satisfy to be decomposed using Eigendecomposition
- How to perform Eigendecomposition by hand on a data matrix
- What are the benefits of performing Eigendecomposition on a data matrix
- How Eigendecomposition is implemented in python

#### Article quality
Many articles are already in place trying to handle Eigendecomposition at their best. However, most of them focus on computing this algorithm by hand and leave learners to implement it by themselves. Also, most of them don't let learners know the importance of applying this technique to a data matrix. This article will address these limitations. First, we will show the learner how to compute the Eigendecomposition by hand and implement it using software python, as it's the most used language in machine learning. Then, again, we will show how the Eigendecomposition eases matrix transformation computations by comparing a computation with and without this algorithm. This is what will make this article uniques from the rest already in place.

#### References
N/A

### PR DESCRIPTION
**Pull request by jacksonjate1**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5896

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by srishilesh** [comment]
@jacksonjate1 

The markdown format of these mathematical equations looks incorrect:
image

Can you verify them please?

**Comment by jerimkaura** [comment]
> @jacksonjate1
> 
> The markdown format of these mathematical equations looks incorrect: image
> 
> Can you verify them, please?

Hello @srishilesh 

I think the problem is with the Github markdown compiler. Otherwise, this is how it looks when I open the file on VS code.

Screenshot from 2022-01-13 12-58-48

**Comment by srishilesh** [comment]
> > @jacksonjate1
> > 
> > The markdown format of these mathematical equations looks incorrect: image
> > 
> > Can you verify them, please?
> 
> Hello @srishilesh 
> 
> I think the problem is with the Github markdown compiler. Otherwise, this is how it looks when I open the file on VS code. Same to [this  PR](https://github.com/section-engineering-education/engineering-education/pull/5968/)
> 
> Screenshot from 2022-01-13 12-58-48
> 
> 
> 

@jerimkaura 

Thanks for letting me know. I didn't know that these wouldn't work with GitHub markdown compiler.

**Comment by jerimkaura** [comment]
> @section-engineering-education/peer-reviewers
> 
> Is anyone available to pick up this PR? It's been pending for a while.
> 
> @jacksonjate1 Please wait until one of our peer-reviewers starts their review process.

I cam review it.

@srishilesh

**Comment by srishilesh** [comment]
> > @section-engineering-education/peer-reviewers
> > 
> > Is anyone available to pick up this PR? It's been pending for a while.
> > 
> > @jacksonjate1 Please wait until one of our peer-reviewers starts their review process.
> 
> I can review it.
> 
> @srishilesh 

@jerimkaura 

Thank you.

**Comment by srishilesh** [comment]
@jerimkaura 

I believe the author has been waiting for a while for the review. Just checking if you could review this. If not, we can re-assign this PR to someone else.

**Comment by jerimkaura** [comment]
> @jerimkaura
> 
> I believe the author has been waiting for a while for the review. Just checking if you could review this. If not, we can re-assign this PR to someone else.

Hello @srishilesh 

Please assign this PR to someone else. I have enough to work on at the moment.

@section-engineering-education/peer-reviewers

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Comment by WanjaMIKE** [comment]
This PR fails to render. Could you check that everything is okay then create a duplicate PR. Thanks

**Comment by jacksonjate1** [comment]
@WanjaMIKE 
Have just checked. To my surprise, there is nothing to change. On VS code, everything seems okay.
Kindly, would you consult with @srishilesh?
I think his recommendation was right. I used the same format with this PR #4443. It failed to render on Git markdown but upon publication, everything was okay.

**Comment by WanjaMIKE** [comment]
@jacksonjate1 could you recreate a new duplicate PR. Thanks

**Pull request closed without merging**
