### PR TITLE
How to Deploy an NFT with Remix IDE and Opensea

### LINKED ISSUE #7445: How to Deploy an ERC-721 NFT Smart Contract with Remix IDE
### Topic Suggestion
How to Deploy an ERC-721 NFT Smart Contract

### Writing sample(s): 
- https://www.section.io/engineering-education/an-introduction-to-blockchain-architecture/
- https://www.section.io/engineering-education/an-introduction-to-defi/

#### Proposed title of the article
How to Deploy an ERC-721 NFT Smart Contract

#### Proposed article introduction
[Blockchain] This article will provide a step by step guide to deploying an NFT with Remix IDE and Interplanetary File System

#### Key takeaways 
- How to deploy an ERC-721 token
- Writing the Smart Contract with Remix to deploy the token
- Utilizing IPFS as a decentralized cloud in storing your digital artwork
- Utilising Metamask test networks
- Deploying and Compiling an ERC-721 token

#### Article quality
This article will be succinct towards ensuring beginners in the blockchain space can easily understand how to deploy an NFT token, because it seems to have been made complex and strange to new entrants in this tech space.

#### References
N/A

### PR DESCRIPTION
**Pull request by corpsgeek**
> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #7445

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by mohamedgh16** [comment]
You should rename the images that you're using to something helpful instead of numbering them.

**Comment by corpsgeek** [comment]
Alright i will look into it

**Comment by corpsgeek** [comment]
@mohamedgh16 all updated

**Comment by louisefindlay23** [comment]
Plagiarism check complete

**Comment by hectorkambow** [comment]
🚀  

Thank you v much @louisefindlay23  

Can we work on publishing some of the "ready for final" PRs - the plagiarism checks can wait for now. 

Thank you

**Comment by corpsgeek** [comment]
I should be asking the reviewer @hectorkambow

**Comment by corpsgeek** [comment]
He added the revisions needed label, didn’t see any comment as to what need to be revised, perhaps @mohamedgh16 is still reviewing.

**Comment by corpsgeek** [comment]
@mohamedgh16 is this still being reviewed by you, haven’t received any comments yet. 

Cc: @hectorkambow

**Comment by corpsgeek** [comment]
@mohamedgh16 this is a bit frustrating, I have checked the files committed, as opposed to the screenshot you sent, I can't see any of that on my end here. Could you drag them into the conversation thread please.

cc: @hectorkambow

**Review by ghost — COMMENTED** [review]
Check now.

**Comment by corpsgeek** [comment]
@mohamedgh16 all issues have been resolved

**Comment by corpsgeek** [comment]
@mohamedgh16 how is the review going??

**Comment by corpsgeek** [comment]
Is my reviewer still active? @hectorkambow

**Comment by hectorkambow** [comment]
@corpsgeek 

👀

**Comment by mohamedgh16** [comment]
@hectorkambow @corpsgeek Sorry for being late. Allow me to work on this now.

**Comment by mohamedgh16** [comment]
@corpsgeek Great tutorial 👍.
Take a look at the edits to minimize revision next time.

**Comment by corpsgeek** [comment]
Aye aye captain.

**Comment by corpsgeek** [comment]
@hectorkambow what does the “white label” mean?

**Comment by corpsgeek** [comment]
@mohamedgh16 can you explain what the white label means?

**Comment by hectorkambow** [comment]
@corpsgeek 
The label corresponds with the date the topic was approved.

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
@corpsgeek 
Well done - please review some of the edits I made during my final review. 


You'll be able to see your live published article on the site (in about 30 mins).

To give your article a boost in page engagement - share it across your social site (LinkedIn/Twitter) and tag the EngEd program so we can also share it and give it some traction as well!
(we will try and do the same once we feature it).

If you have not done so already - consider adding a skill section to your author page. This will go a long way for potential future employers.

**Pull request merged**
