### PR TITLE
Design a sign up and login gui using javafx

### LINKED ISSUE #3463: Design a Sign-up and Login GUI using JavaFX
### Proposed title of the article

Design a Sign-up and Login GUI using JavaFX

### Introduction paragraph (2-3 paragraphs)

JavaFX is an open-source Java framework that is used to create, develop, and deliver highly portable hardware-accelerated user interfaces.
It is used to create GUI's for Rich Internet Applications (RIA), Web, desktop, and embedded and mobile applications.
Login and Sign-up forms have a unique design which makes the site presentable and of a unique design.

In this article, you will learn how to build a JavaFX Login and Sign-up User Interface(UI).

### Key takeaways

At the end of this article, you will have gained the following knowledge:

- What is JavaFX
- JavaFX libraries
- Setting up a JavaFX project
- Designing the Login and Sign-up form
- Running the application

### Pre-requisites

The basics of the article include the following:

- Java language knowledge and use
- A Java IDE is set up in your machine.
- A stable internet connection.

### References

N/A

### Templates to use as guides

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by blacklihgt**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #3463

### CODE REVIEW

**Comment by blacklihgt** [comment]
@john-amiscaray 

I have done the changes as asked

I'll be waiting from you

**Comment by john-amiscaray** [comment]
@blacklihgt Good work, I only needed some minor changes in my last commit. We will move on to the technical review where I will check for technical accuracy and if your code/steps work.

**Comment by john-amiscaray** [comment]
@blacklihgt In the section on setting up the JavaFX project, I tried following the same steps as you but my installation of IntelliJ Ultimate doesn't provide the same options to set the dependencies, group + artifact ids and etc. I was wondering then if you are using some kind of plugin to have these options available to you? If this is the case, please add information on that in that section of the article.

**Comment by john-amiscaray** [comment]
> 
> 
> @blacklihgt In the section on setting up the JavaFX project, I tried following the same steps as you but my installation of IntelliJ Ultimate doesn't provide the same options to set the dependencies, group + artifact ids and etc. I was wondering then if you are using some kind of plugin to have these options available to you? If this is the case, please add information on that in that section of the article.

By the way, my IntelliJ version is 2020.3.1

**Comment by blacklihgt** [comment]
Ohh, the `New JavaFX project Layout` used is in the IntelliJ ultimate `2021.2.2` and in the community version `2021.2.2`.
These are the latest versions. The community version is free of course...

**Comment by john-amiscaray** [comment]
> 
> 
> Ohh, the `New JavaFX project Layout` used is in the IntelliJ ultimate `2021.2.2` and in the community version `2021.2.2`.
> These are the latest versions. The community version is free of course...

Got it, I'll update my IntelliJ and try again.

**Comment by john-amiscaray** [comment]
> 
> 
> > Ohh, the `New JavaFX project Layout` used is in the IntelliJ ultimate `2021.2.2` and in the community version `2021.2.2`.
> > These are the latest versions. The community version is free of course...
> 
> Got it, I'll update my IntelliJ and try again.

Seems to work now thanks

**Comment by john-amiscaray** [comment]
@blacklihgt Good news, I finished the technical review quicker than expected and I don't require any changes from you at this point. There was a small thing where some elements were given ids in the code in your article but not when you actually went to follow the steps. However, I think it's not something we should worry too hard about. You can go ahead make it so that there is consistency there but I don't think it matters all that much so that's up to you.

**Comment by john-amiscaray** [comment]
@blacklihgt I must add as well that I enjoyed going through your article step by step and creating that UI. I might consider learning JavaFX myself cause it seems like it could be useful and fun. Nice UI as well I must say. Great job!

**Comment by john-amiscaray** [comment]
@blacklihgt PS: please look through my commits just in case and let me know if I made any mistakes.

**Comment by blacklihgt** [comment]
> @blacklihgt PS: please look through my commits just in case and let me know if I made any mistakes.

Let me check...

**Comment by blacklihgt** [comment]
All seems well @john-amiscaray  ... :rocket: :+1:

**Comment by Kayere** [comment]
Great article @blacklihgt.
Thank you for the review @john-amiscaray.

**Pull request merged**
