### PR TITLE
How to collect update and organize python logs

### LINKED ISSUE #4635: [Python] How to collect, update, and organize Python logs
#### Proposed title of the article
[Python]How to collect, update, and organize Python logs
#### Proposed article introduction
 The built-in logging module in Python is intended to provide vital visibility into your applications with little configuration. This article describes how to configure Python's logging module to log all the data needed, route it to desired destinations, and consolidate logs to gain deeper insights into Python applications.
 An external configuration file can also be used to configure the Python logging subsystem. The Python standard library contains the specifications for the logging configuration format.
 The logging library follows a modular design and is divided into four categories: loggers, handlers, filters, and formats.
#### Key takeaways 
1. Customize your logs' priority level and destination.
2. Create a customized setup with various loggers and destinations.
3. Include tracebacks and exception handling in your logs.
4. To facilitate troubleshooting, format your logs in JSON and consolidate them.
#### Article quality
The article thoroughly explains how Python logs work, providing students with a solid foundation in logging. It will enhance their skills since every detail is put in place.
#### References
N/A

### PR DESCRIPTION
**Pull request by kymomolly**
fixes #4635

### CODE REVIEW

**Comment by kymomolly** [comment]
fixes #4635

**Comment by WanjaMIKE** [comment]
Please work on the plagiarism highlighted in the attached file. Thanks

[How to collect update and organize python logs #4823 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7512876/How.to.collect.update.and.organize.python.logs.4823.Copyleaks.Report.pdf)

**Comment by WanjaMIKE** [comment]
@paulodhiambo could you check if this article is similar to https://realpython.com/python-logging/

**Comment by paulodhiambo** [comment]
> @paulodhiambo could you check if this article is similar to https://realpython.com/python-logging/

Hello @kymomolly your article is similar to the pointed out article. I suggest you explain how to collect logs in a Flask or Django application.

**Comment by kymomolly** [comment]
Hello @paulodhiambo, working on it soonest.

**Comment by kymomolly** [comment]
Hello @paulodhiambo, requested enhancement committed

**Comment by kymomolly** [comment]
@paulodhiambo, how is the progress?

**Comment by hectorkambow** [comment]
@section-engineering-education/content-moderator-team can we get this PR a plagirism check.  

Lets glance through the content 1st - if it looks polished lets run it through a check. 👍

**Comment by ahmadmardeni1** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. @kymomolly 
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

There appear to be many sentences in this article that are taken verbatim from third-party sources. Like [datadoghq](https://www.datadoghq.com/blog/python-logging-best-practices/) and [realpython](https://realpython.com/python-logging/).
[How to collect update and organize python logs#4823](https://github.com/section-engineering-education/engineering-education/files/7547006/New.Scan.2_09.PM.Copyleaks.Report.pdf)

**Comment by kymomolly** [comment]
@ahmadmardeni1, you did not attach the pdf as indicated above

**Comment by kymomolly** [comment]
@paulodhiambo, necessary updates are done.

**Comment by ahmadmardeni1** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

Please take your time and revisit your article. @kymomolly 
[How to collect update and organize python logs#4823](https://github.com/section-engineering-education/engineering-education/files/7561545/New.Scan.9_07.AM.Copyleaks.Report.pdf)

**Pull request closed without merging**
