### PR TITLE
Continuous Integration with Jenkins

### LINKED ISSUE #2759: Continuous Integration with Jenkins
### Proposed title of article
Continuous Integration with Jenkins

### Introduction paragraph (2-3 paragraphs):

In the spirit of collaboration and agile methodology, several developers build codes and combine these different codes into one code base. This process would involve version control system (VCS) where different developers can get code from other developers using pull requests, send their changes to other developers using push requests and combine different code bases from different contributors using merge requests. This process can be automated using continuous integration.

There are various tools that can be used for continuous integration. Jenkins is one such tool. This article will focus on Jenkins as a tool for continuous integration. It is a popular open source tool that can be used to automate different build process. These processes are predefined and can be triggered by different processes such as on predefined time intervals or predefined user actions.

### Key takeaways: 

•	Understanding Jenkins and its role in continuous integration
•	Basic setup of Jenkins
•	What are pipelines and how are they used with Jenkins
•	Benefits of using Jenkins compared to other Continuous integration tools
•	Shortcomings of using Jenkins as a continuous integration tool

### References: 
n/a

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Rmwamboi**
this fixes #2759

### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Have you used our preferred heading structure? - H3 (###) and up? ---- You have not. Please revise the article. Thanks

**Comment by Rmwamboi** [comment]
Edited the headings @WanjaMIKE

**Comment by Rmwamboi** [comment]
I have fixed that. @WanjaMIKE

**Comment by WanjaMIKE** [comment]
@Rmwamboi Kindly, add an author's page.

**Comment by Rmwamboi** [comment]
@WanjaMIKE this has been added. thanks for the insightful amendments made, I will strive improve on quality of my articles going forward.

**Comment by hectorkambow** [comment]
Overall nice job @Rmwamboi - easy to follow along 👍 

cc @WanjaMIKE

**Comment by hectorkambow** [comment]
@Rmwamboi Please contact me via Slack.

**Pull request merged**
