### PR TITLE
How to Automate Tests for Dockerized Django Applications with GitHub Actions

### PR DESCRIPTION
**Pull request by khabdrick**
It’s always a good idea to use GitHub Actions for your project because it makes it easy to automate processes through which include; testing and deploying your project. Docker helps make sure your app works the same way on all platforms. Adding these functionalities to your application can make it easy for CI/CD and collaboration.

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Plagiarism check is done. Kindly, correct the highlighted areas in the attached pdf. Thanks
[New Scan 5_33 PM Copyleaks Report (1).pdf](https://github.com/section-engineering-education/engineering-education/files/7506859/New.Scan.5_33.PM.Copyleaks.Report.1.pdf)

**Comment by khabdrick** [comment]
@WanjaMIKE  do I need to change the paraphrased part too?

**Comment by khabdrick** [comment]
Hello @WanjaMIKE I have made the changes required

**Review by jerimkaura — CHANGES_REQUESTED** [review]
Hello @khabdrick 

Would you please go over some of the published articles to master sentence formatting and structuring? You seem to be having a lot of incomplete/hanging sentences.

Structure your ideas into followable sentences organized into sentences that can be followed.  You should refrain from making your entire article a set of instructions. 

Tell the reader what you want to do, why you are doing it, and how it will help the application. From there you can provide them with the instructions of doing it.

**Comment by khabdrick** [comment]
Hello @jerimkaura ,I have made the corrections you requested!

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Review by jerimkaura — APPROVED** [review]
Thank you submitting such a great article. :rocket: . Take note of the following:

- File names and folder names are enclosed within a `backticks` not  * asterisk *
- All the changes made to improve your future articles.

Let us wait for one of the final reviewers to finish on this.

**Comment by khabdrick** [comment]
That was a mistake, hope I didn't mess up any thing

**Comment by hectorkambow** [comment]
👍 overall nice work - very detailed and straight forward tutorial 
 
Please review and suggestions/changes made by your peer reviewer and/or myself during a final review.

**Comment by khabdrick** [comment]
Hello @hectorkambow what about payment?

**Pull request merged**
