### PR TITLE
Build a Hash Generator Application using React.js

### LINKED ISSUE #4631: [Languages]Build a Hash Generator Application using React.js
#### Proposed title of the article

Build a Hash Generator Application using React.js

#### Proposed article introduction

Hashing is the process of converting an input of any length into a fixed-sized string of text using a mathematical function. This means that any text can be converted into an array of numbers and letters through an algorithm, no matter how long it is. The text being converted/hashed is referred to as an input. The algorithm used to covert this string is called a hash function. The generated value is called a Hash value. This guide will teach the reader about the Hash functions and illustrates how to build a Hash generator application using React.js. We will create a simple app that calculates hashes from strings of text.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

- What are Hash functions?
- What are Hash functions used for
-  Characteristic of a Good Hash function
- Create a Hash Generator using React.js

#### Article quality

This article explains the different Hash functions and why you need them. Then build a React app that takes a string of text and converts them to a  Hash function.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### PR DESCRIPTION
**Pull request by mosesreigns**
Build a Hash Generator Application using React.js

This closes #4631

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Plagiarism check done. Please take a moment and correct the highlighted issues. Thanks

[New Scan 5_17 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7506764/New.Scan.5_17.PM.Copyleaks.Report.pdf)

**Review by mercymeave — COMMENTED** [review]
Hello @mosesreigns 

Thank you for submitting such a clean article. We encourage such :rocket:

I am proceeding to tech review.

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
👍 overall nice work - very detailed and straight forward tutorial 
 
Please review and suggestions/changes made by your peer reviewer and/or myself during a final review.

**Pull request merged**
