### PR TITLE
Author RSS Feeds

### PR DESCRIPTION
**Pull request by louisefindlay23**
### Inspiration

Be able to create RSS feeds for indivdual authors so they can have a dynamic list of articles they've published which can be consumed in places like personal portfolio websites and GitHub Profiles.

### Features

Adds an author parameter to the main EngEd RSS Feed which can be filtered using programming language of choice.

### Improvements

Using the author parameter create a unique .xml file for each author. This currently works by adding a .xml template file in an individual author folder but haven't yet got it working so it will generate a new file based on URL (e.g. `/author/louise-findlay/index.xml`)

### Workaround

Haven't managed to get the above desired improvement working with Hugo but it's easier to do so by just consuming the original RSS feed and then iterating over it so can make an small Node application to do so.

[Repo Link](https://github.com/louisefindlay23/section-author-rss-feed)

### CODE REVIEW

**Comment by louisefindlay23** [comment]
The small Node.js application is working well and obtains the Section RSS Feed and can isolate the posts section and parse for specific tags. Added a form so users can enter their name and then replaces to lowercase and hyphen per author name format.

Will add functionality of generating specific author feeds once PR has been merged so I can filter for the author tag.

**Comment by hectorkambow** [comment]
@louisefindlay23 

👀  

Can you please elaborate a bit more - I'm not sure I'm following what this would do. (or how it would work). 

Where would the RSS feed show up? 

Is it just a link that students can plug into their linkedin and other social sites? 

I guess I'm wondering where that link would be located on the EngEd site?? 

Would it auto update every time a new article is posted?  

Will it go on there Github profiles?

**Comment by louisefindlay23** [comment]
Sure, Hector.

The current Section RSS feed (for all articles) is located here: https://www.section.io/engineering-education/index.xml. Users can use that to display all Section articles in places where RSS feeds are supported such as GitHub Readmes (using [Blog Post Workflow](https://github.com/gautamkrishnar/blog-post-workflow) GitHub Action) and websites. This feed is created by Hugo by default and auto updates when new posts are created.

This PR adds a author parameter to articles which will allow us to filter specific posts based on article author.

To make this super easy and separate from the main Section Repo, I wrote a small Node app that will take the main Section EngEd feed and will be able to filter the feed (using the author parameter) once it's been added. This processes the existing RSS feed into JSON and is available via URL. 

I then made a GitHub Action to simplify the process of adding to a GitHub readme.

**Comment by hectorkambow** [comment]
@ninjaginja 
Wanted to ask if we could review this RSS (for individual authors) whenever you have a moment.

Thank you v much.

**Pull request merged**
