### PR TITLE
[Duplicate #7138]How to employ brotli compression method

### PR DESCRIPTION
**Pull request by Newton-cyber**
#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? 
- [X] Is your article properly formatted in Markdown? 
- [X] Have you used our preferred heading structure? 
- [X] Does your article follow any of the suggested structure formats?
- [X] Is your article over 750 words? [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? 
- [X] Can your article be understood by beginners?
- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. 
- [X] Have you checked your article for readability? [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
`This closes #7138 `

### CODE REVIEW

**Comment by Newton-cyber** [comment]
@srishilesh made  all the requested changes from previous PR

**Comment by hectorkambow** [comment]
@Newton-cyber 

Please be sure you have proofread the entire article as peer reviewers do not (and can not) point out every issue. 

If this PR has any other errors - we will be closing it immediately

👍

**Comment by hectorkambow** [comment]
@srishilesh as a matter of fact this PR has been closed multiple time - we should not be working on it. 

image

cc @Newton-cyber

**Comment by hectorkambow** [comment]
cc @srishilesh Happy to recosider if you think otherwise

**Pull request closed without merging**
