### PR TITLE
Flutter Authentication Using Flask API

### LINKED ISSUE #4869: [API]Flutter Authentication Using Flask API
#### Introduction
Softwares or applications are mostly made to solve problems for a particular set of people. 
Most times software or applications hold data that is not supposed to be accessible to everyone. 
this has made Authentication a core aspect of software or application development.

Flutter is a UI toolkit created by google, it is used to build cross-platform mobile applications for Android and IOS, and desktop applications for Windows, Mac, and Linux. UIs built with Flutter always depend on backend technologies for functionalities like authentication, one of these backend technologies is Flask.
Flask is a micro web framework written in python.

Authentication is the process of proving if a user trying to access a system has the permission to do so. It verifies users by comparing credentials provided to those on a file in a database of the 
authorized user’s information on a local operating system or within an authentication server.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

#### Key takeaways 
After reading this article the reader will;
- Learn to build a login and register form
- how to make a post and a get request using flutter
- Understand how authentication works.

#### Article quality
The article will explain in-depth how API works with frontends applications, and how developers can communicate or make a request to backend applications.

### PR DESCRIPTION
**Pull request by wobin1**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4869

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by LinusMuema** [comment]
plagiarism check done :heavy_check_mark:
Just the code snippets raising red flags but imports can't be changed

**Review by jerimkaura — CHANGES_REQUESTED** [review]
Hello @wobin1 

Thank you for being patient on this. Your article is great but you need to remember that all sentences end in a period, not a comma, and begin in a capital letter.

Go over the article and enclose all variables, filenames, functions, classes, widgets, and other special words in back-ticks.

**Comment by wobin1** [comment]
@jerimkaura changes affected

**Review by jerimkaura — COMMENTED** [review]
Made a few corrections. Take note of them. Proceeding to tech review.

**Review by jerimkaura — APPROVED** [review]
Hello @wobin1 

Thanks for such a great article. Would please consider using explanatory headings? Something like 'STyling the Login Page' INstead of just saying login. Finish up on that then ensure all image are reflecting before the final review.

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
👍 overall nice work - very detailed and straight forward tutorial 
 @wobin1 Please review and suggestions/changes made by your peer reviewer and/or myself during a final review. 
 
cc @jerimkaura Please do the same 👍

**Pull request merged**
