### PR TITLE
Will Serverless Computing replace Docker Containers?

### PR DESCRIPTION
**Pull request by verah-tech**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by verah-tech** [comment]
This solves issue #2400

**Comment by hectorkambow** [comment]
https://github.com/section-engineering-education/engineering-education/pull/2449/files

@verah-tech 

Just noticing this article overlaps with the article above. 

Please review the topics and see where your article could draw more value or a different perspective than the other one in the works 🚀 

There is more than enough to explore the concept in more depth. 

Please speak with the author of the other article (or review the article in the works) to be sure to build upon and/or explore further concepts beyond what is being offered in the other article 👍 

cc @ahmadmardeni1

**Comment by verah-tech** [comment]
@hectorkambow The issue is from me,,it doesn't overlap as I am the one who wrote it

**Comment by ahmadmardeni1** [comment]
@verah-tech  Maybe you can talk about [EaaS (Section’s Edge as a Service)](https://www.section.io/about/)?

Being container-based (Docker/Kubernetes), our platform includes the ability to build and bring your own edge module or select from our library of highly available and highly performant edge compute modules.

You can compare it with the other services and when the user should use ours. Cons and Pros for each one, etc ...

There are a lot of resources on [our website](https://www.section.io/) that can help you understand our products.

This is just a thought, and you are not forced to talk about it. Also, you can talk to the other author on Slack as Hector suggested.
cc @hectorkambow

**Comment by ahmadmardeni1** [comment]
@verah-tech 
He put the wrong link.
Here it is:
https://github.com/section-engineering-education/engineering-education/pull/2399

**Comment by hectorkambow** [comment]
> @verah-tech Maybe you can talk about [EaaS (Section’s Edge as a Service)](https://www.section.io/about/)?
> 
> Being container-based (Docker/Kubernetes), our platform includes the ability to build and bring your own edge module or select from our library of highly available and highly performant edge compute modules.
> 
> You can compare it with the other services and when the user should use ours. Cons and Pros for each one, etc ...
> 
> There are a lot of resources on [our website](https://www.section.io/) that can help you understand our products.
> 
> This is just a thought, and you are not forced to talk about it. Also, you can talk to the other author on Slack as Hector suggested.
> cc @hectorkambow

Whatever you think is best to help differentiate your article from the other one 👍 the topic is a very interesting and huge topic - should be plenty to reference and speak about.

@verah-tech 
Thank you 🚀

**Comment by verah-tech** [comment]
@ahmadmardeni1 The article is from me, I just did the wrong upload kindly advise the way forward.
Thank you
cc @hectorkambow

**Comment by ahmadmardeni1** [comment]
@verah-tech I'm lost a little, how it is from you?
The author of [this article](https://github.com/section-engineering-education/engineering-education/pull/2399) is Jaykip.

**Comment by ahmadmardeni1** [comment]
@verah-tech Both are talking about the same concepts and we can't publish both of them.
Sure, close it till you draw more value or a different perspective.

**Comment by verah-tech** [comment]
@ahmadmardeni1 Thank you

**Pull request closed without merging**
