### PR TITLE
Getting Started with YouTube Android Player API to Play YouTube Videos

### LINKED ISSUE #6912: [Android] Getting Started with YouTube Android Player API to Play YouTube Videos
#### Proposed article introduction
The YouTube Android Player API enables you to incorporate video playback functionality into your Android applications. The API defines methods for loading and playing YouTube videos (and playlists) and for customizing and controlling the video playback experience.

Using the API, you can load or cue videos into a player view embedded in your application's UI. You can then control playback programmatically. For example, you can play, pause, or seek to a specific point in the currently loaded video.

You can also register event listeners to get callbacks for certain events, such as the player loading a video or the player state changing. Finally, the API has helper functionality to support orientation changes as well as transitions to fullscreen playback.

#### Key takeaways 
- What is YouTube's Android Player API?
- How does it work?
- Obtain your KEY.
- Integrating it into an Android project.

#### Article quality
This is something that I have been learning and using it in a Movies app that I am developing, so I thought I should share a clear tutorial so that other developers don't have to go through the whole web looking for a solution. 

#### References
-N/A

### PR DESCRIPTION
**Pull request by mosestakai**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6912

### CODE REVIEW

**Review by jerimkaura — CHANGES_REQUESTED** [review]
Hello @mosestakai 

Welcome to Section Engineering Education. You have an amazing article. I have made a few corrections in my first round of reviews. 

However. Why don't you make the application such that one can post a video name then the API searched for that video and returns it to the user instead of playing just a single video? Won't that be more beneficial to our readers?

Thanks.

**Comment by mosestakai** [comment]
> Hello @mosestakai
> 
> Welcome to Section Engineering Education. You have an amazing article. I have made a few corrections in my first round of reviews.
> 
> However. Why don't you make the application such that one can post a video name then the API searched for that video and returns it to the user instead of playing just a single video? Won't that be more beneficial to our readers?
> 
> Thanks.

Sure @jerimkaura let me add that functionality to the app, but I made the tutorial simple as from the title - "Getting Started..."

**Comment by mosestakai** [comment]
@jerimkaura I have made the revisions

**Comment by louisefindlay23** [comment]
Plagiarism check complete.

**Comment by jerimkaura** [comment]
> @jerimkaura I have made the revisions

Great, let me take a look. Looks promising 🎉

**Review by jerimkaura — COMMENTED** [review]
Hello @mosestakai 

This is a great work done here 🎉 

You have a clean and easy ton read piece.

Proceeding to tech review. I actually loved the idea of playing YouTube videos in an android app.

Good work gentleman!

**Review by jerimkaura — APPROVED** [review]
Great article.

Let us wait for the final review.

**Comment by hectorkambow** [comment]
Jumping on this one 
@section-engineering-education/content-moderator-team

**Comment by hectorkambow** [comment]
👏  Great work. 

Thank you for you patience as our team was working through the back log of articles .

Looking forward to reviewing more of your great tutorials like this one. 

I'd recommend that your also consider adding some skills (programming languages) to your EngEd Author profile (if you haven't already done so). !

**Comment by hectorkambow** [comment]
@mosestakai

**Pull request merged**
