### PR TITLE
Choosing between Managed WordPress vs Shared WordPress Hosting

### LINKED ISSUE #1196: Choosing between Managed WordPress vs Shared WordPress Hosting
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

There are different hosting services available in the market, including shared, managed WordPress hosting, and even dedicated hosting service. But which one is suitable for your needs? This article aims to compare shared and managed WordPress hosting.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. What is Shared WordPress hosting
2. What is Managed WordPress hosting
3. Benefits and drawbacks of both Managed WordPress and Shared WordPress Hosting

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

### PR DESCRIPTION
**Pull request by EKahuha**
this fixes #1196

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by Dawe-7** [comment]
@hectorkambow I'll review this article.

**Comment by hectorkambow** [comment]
@Dawe-7  Will be going through this article as a Review 🚀

**Comment by hectorkambow** [comment]
plagiarism check done

**Review by Dawe-7 — COMMENTED** [review]
Hello @EKahuha, I've left a few suggestions. Consider making the changes and we can move on to the final review. Overall, it's a good article.

**Comment by EKahuha** [comment]
@Dawe-7, I have updated this article.

**Review by Dawe-7 — APPROVED** [review]

**Comment by Dawe-7** [comment]
@hectorkambow, this article is ready for a final review.

**Comment by hectorkambow** [comment]
@EKahuha 👍  
great overall topic (I did think it would benefit from a bit more substance) - please go over the changes I made to include into future articles 🚀  

Its always a good idea to include more sources within the article for the audience to have an external resource to continue exploring. (see example in the article - use the sources you use to write the article). 

There were some changes I made in place I thought the article was a bit difficult to read - please keep this in mind to work on for future articles as it may lead to more revisions or PR closure. 

cc @Dawe-7  please go over the changes made as well to better our reviews in the future as well 👍  

Overall, great work gentlemen 🚀

**Comment by Dawe-7** [comment]
Well noted @hectorkambow

**Pull request merged**
