### PR TITLE
Approximating the Speed of an Object and its Distance using OpenCV in Python

### LINKED ISSUE #6316: Approximating the Speed of an Object and its Distance using OpenCV in Python
#### Proposed title of article
Approximating the Speed of an Object and its Distance using OpenCV in Python

#### Proposed article introduction
Computers are essential in today's technological age. They can make our lives easier by making other integratable tasks easier to perform such as speed and distance approximation.
We are going to see how to calculate the distance with a webcam using OpenCV in Python. Measure the distance from the object(face) to the camera, capture a Reference image and note down the measured distance using the Distance finder function. 
Likewise, finding the velocity of the object, since speed is the relation of distance with respect to the given time, using coherent functions.
In this tutorial, We will require python packages such as numpy, cv2, mediapipe, math, ctypes, time, and among others to work with and well-explained details on their usage. 

#### Key takeaways 

1. Using OpenCV to find the distance of an object.
2. Finding the velocity or speed of the object.
3. Integration of the distance with respect to speed for simultaneous output.

#### Article quality
Unlike other articles, the code will be well explained and not just copy-pasted. But designed in an eccentric way for easier understanding and consumption. Deeply emphasizing the importance and use of packages.

#### References
N/A

### PR DESCRIPTION
**Pull request by GeekEdmund**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6316

### CODE REVIEW

**Comment by GeekEdmund** [comment]
@Dawe-7 
Submitted a PR.

**Comment by Kayere** [comment]
Hello @GeekEdmund,

 Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Approximating the Speed of an Object and its Distance using OpenCV in Python #6630 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/8078035/Approximating.the.Speed.of.an.Object.and.its.Distance.using.OpenCV.in.Python.6630.Copyleaks.Report.pdf)

**Comment by GeekEdmund** [comment]
@lalith1403 fixed the requested changes

**Comment by lalith1403** [comment]
The article needs a lot of work. There are several grammatical, and formatting issues. Please go through the contribution guidelines, and make the necessary changes. I will be closing this PR for now to make room for other PRs.

**Comment by GeekEdmund** [comment]
@lalith1403 Done with the changes as requested.

**Comment by hectorkambow** [comment]
@lalith1403 

@section-engineering-education/content-moderator-team  

Is anyone available to do a review on this? 

If any other edits are required we can go ahead any close it to allow the proper time to proofread it.

**Comment by WanjaMIKE** [comment]
There still appears to be several grammar errors and unreadable sentences. Please correct them @GeekEdmund . Thanks

**Comment by lalith1403** [comment]
Feel free to work on these idling and let us now once done. Thank you.

**Comment by GeekEdmund** [comment]
@Lalith I'm done with the changes, so I was requesting for reopening of the PR  to push the final changes so that we can complete the final review.

**Comment by GeekEdmund** [comment]
@WanjaMIKE Completed the requested changes, you may now proceed with your final review.

**Comment by WanjaMIKE** [comment]
I am unable to view this PR on my computer. I seem to have an issue on my end.

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
> The article needs a lot of work. There are several grammatical, and formatting issues. Please go through the contribution guidelines, and make the necessary changes. I will be closing this PR for now to make room for other PRs.

At this point (your first closure), the article should have been re-submitted as a new PR for a duplicate label. 

It seems it was closed and re-opened a few times. (and edits were made by both reviewers) 


The % was pretty also high, which is a cause for concern that this topic may not be completely original. 

This seems like a potential candidate for permanent closure.

**Comment by hectorkambow** [comment]
@lalith1403 

@WanjaMIKE 

@GeekEdmund 

This article was still not ready to be published. Any article of this caliber should be closed asap.

**Pull request merged**
