### PR TITLE
 Creating an audiobook with Pyttxs3, PyPDF3 and Tkinter

### LINKED ISSUE #2499: Creating an Audiobook with PyPDF3 and Pyttsx3
### Proposed title of the article
Creating an Audiobook with PyPDF3 and Pyttsx3 (Python libraries)

### Introduction paragraph (2-3 paragraphs):
There's has never been a time in the history of humankind with so much knowledge to consume. This has caused a distracted world where what you read is what makes you. This, in turn, caused time deficiency among readers which has led to the creation of audiobooks. Whether working, driving or eating, you can consume a book.

But as a developer, you need not buy one when you can actually create one for free.

In this tutorial, we shall look at PyPDF3 and Pyttsx3 (Python libraries) and how to use them to create your own audiobook.

### Key takeaways:
* What isPyPDF3?
* What is Pyttsx3?
* Using both PyPDF3 and Pyttsx3 to create, use and save an audiobook in a .mp3 format.

### References:
* [Pyttsx3](https://pypi.org/project/pyttsx3/)
* [PyPDF3](https://pypi.org/project/PyPDF3/)

### PR DESCRIPTION
**Pull request by FREDERICO23**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2499

### CODE REVIEW

**Comment by FREDERICO23** [comment]
Hello @Bayler I created a new one kindly ping @ahmadmardeni1 to continue with the review

**Comment by Bayler** [comment]
> Hello @Bayler I created a new one kindly ping @ahmadmardeni1 to continue with the review

@FREDERICO23  Let me have a final look at it make sure everything is okay before he takes over.

**Comment by Bayler** [comment]
@ahmadmardeni1 This article is now ready for final review. It is a duplicate of the closed PR #2792 which had some issues. 

@FREDERICO23 I'm done with your review. I love the hero image you've used. I've learnt a lot too. Good job!
To avoid making the same mistakes in your future articles, make sure you always create a new branch when submitting a new article.

**Comment by FREDERICO23** [comment]
@Bayler Thanks for the positive reviews. It has been a great learning experience and a great contributors interaction. Looking forward to working together with you on my next article.

**Comment by ahmadmardeni1** [comment]
Great work gentlemen @FREDERICO23 @Bayler 🚀

**Pull request merged**
