### PR TITLE
Stir Framework In Action In a Spring Web App

### LINKED ISSUE #7804: Stir Framework in Action in a Spring Web App
#### Proposed title of the article
Stir Framework in Action in a Spring Web App

#### Proposed article introduction
January 26th, 2023 saw the release of Stir version 1.0.0 to Maven central, an open-source Java framework I’ve developed over the past two months. Stir is a feature-rich server-side rendering framework that allows you to generate HTML on the fly. With its developer-friendly API and extensive documentation, you can get started with it right away and use it as the templating solution for your next backend project.

In this tutorial, I’ll show Stir in action by creating a simple to-do application with Spring. In the process, we’ll see the major features of Stir, the advantages of using it, and proper usage of it for your next project. By the end of this guide, you will have everything you need to know to use Stir for server-side development.

#### Key takeaways
- The advantages of Stir as a server-side rendering solution
- HTML Document Templating
- Building a custom AbstractUIElement class
- Working with element descriptors
- How to use Stir in a production application

#### Article quality
This guide will provide the reader with examples of the practical applications of Stir by going step-by-step through a to-do app powered by it.

#### References
https://github.com/john-amiscaray/Stir

### PR DESCRIPTION
**Pull request by john-amiscaray**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #7804

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Merged #7807 into master

**Comment by WanjaMIKE** [comment]
Published @john-amiscaray

**Comment by john-amiscaray** [comment]
@WanjaMIKE I found a few errors just now (i.e., broken images and links). Can I go ahead and create a new PR to fix it?

**Comment by WanjaMIKE** [comment]
I updated the images @john-amiscaray Thanks

**Pull request merged**
