### PR TITLE
data abstraction in c#

### LINKED ISSUE #2648: Data  abstraction in C#
### Proposed title of article
Data  abstraction in C#

### Introduction paragraph (2-3 paragraphs):
The property of data abstraction is that just the most important details are displayed to the user. The user is not shown the units that are trivial or non-essential. The practice of identifying only the required attributes of an object while discarding the irrelevant information is known as data abstraction. An object's properties and actions distinguish it from other objects.

In this article, the reader will understand data abstraction with the aid of the abstract classes 

### Key takeaways: 
By the end of this article the reader will understand:
1. what is data abstraction.
2. types of abstraction
3. abstract classes.
4. use of abstract classes and abstract methods.
5. encapsulation vs data abstraction.
6. advantage of abstraction.

### References: 
N/A

### PR DESCRIPTION
**Pull request by Dick7603**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2648

### CODE REVIEW

**Comment by hectorkambow** [comment]
@Dick7603 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀

Thank you.

**Comment by Dick7603** [comment]
hello @kayere I wish to enquire about the progress of my article.

**Review by kayere — COMMENTED** [review]
Hello @Dick7603, welcome to section's engineering education program. Sorry for the delayed review. This is a great article. I have made some changes for flow and format. Please go through them so that you can apply them in your future articles. 

Lastly, please edit you conclusion. It does not seem appealing at the moment. You can write a summary of what the article covers and how that can help the reader in a real-life scenario. Ping me when you are done so that we can proceed to final review.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by Dick7603** [comment]
Noted

**Comment by Dick7603** [comment]
hello @kayere I have done the requested changes. 
Please check my last commit. Thank you

**Review by kayere — APPROVED** [review]
Congratulations @Dick7603. Your article is now ready for final review and should be published as soon as a Content Moderator gets to it.

Keep up the good work.

**Comment by ahmadmardeni1** [comment]
Congrats on your first article and welcome to Section EngEd🎉 @Dick7603 

Thank you for the review @kayere

**Pull request merged**
