### PR TITLE
How to Perform Threading Timer in Python

### LINKED ISSUE #4561: [Languages]How to Perform Threading Timer in Python
#### Proposed title of article
How to Perform Threading Timer in Python

#### Proposed article introduction

The threading module in Python is a built-in module called threading that can be imported directly. Threading is an object in Python because practically everything is represented as an object in Python. A thread can do a lot of things:  Data storage, Data structures such as dictionaries, lists, and sets are used to store information.
It's possible to provide it to a function as a parameter. A process can also be used to execute a thread. In Python, a thread can be in multiple states such as wait, blocked, and so on.
The timer is a subsidiary class present in the python library named “threading”, which is generally utilized to run a code after a specified time period. 
Python’s threading.Timer() begins after the delay specified as an argument within the threading.

#### Key takeaways 

1. Understanding threads in Python.
2. Python timer functions.
3. Creating and using a timer class.
4. Working with Python decorator and context manager.

#### Article quality

The article is intended to be precise and clear to the point, illustrated by codes making it more practical and interesting, to increase time spent on the page.

#### References

N/A

### PR DESCRIPTION
**Pull request by GeekEdmund**
This fixes #4561

### CODE REVIEW

**Comment by GeekEdmund** [comment]
@adrianmurage  Submitted a PR

**Comment by paulodhiambo** [comment]
@GeekEdmund please link an issue to this PR.

**Comment by GeekEdmund** [comment]
@paulodhiambo, how do I link the issue to PR

**Comment by WanjaMIKE** [comment]
Please correct the highlighted issues in the plagiarism report. Thanks
[New Scan 10_59 AM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7527062/New.Scan.10_59.AM.Copyleaks.Report.pdf)

**Comment by GeekEdmund** [comment]
@paulodhiambo Completed the task you asked

**Comment by hectorkambow** [comment]
👍 overall nice work - very detailed and straight forward tutorial 
 
Please review and suggestions/changes made by your peer reviewer and/or myself during a final review.

**Pull request merged**
