### PR TITLE
How to create a Machine Learning App using the FastAPI and deploying it to the Kubernetes cluster

### LINKED ISSUE #2799: How to create Machine Learning App using the FastAPI and deploying it to kubernates cluster
### Proposed title of the article
How to create Machine Learning App using FastAPI and deploying it to Kubernetes cluster

### Introduction paragraph (2-3 paragraphs):
FastAPI is a modern, fast (high-performance), web framework for building APIs with Python 3.6+.
Here we will build our machine learning model, after creating the model we will create an application using the FastApi which has different routes that can be used to make predictions.
After serving our machine learning model as an API, we will create a docker container for the application.
Finally, we will be able to deploy the FastAPI docker container to the Kubernetes cluster.
### Key takeaways: 
1. How to create a simple machine learning model.
2. How to install the FastAPI.
3. Serving the ML model as an API using the FastAPI.
4. How to create Docker Container.
5. Deploying the FastAPI docker container to Kubernetes cluster.
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Bravinsimiyu**
This fixes #2799 

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by lalith1403** [comment]
It's very important to spell check the article, Especially the title. Kindly use services such as Grammarly to check the spellings and grammar and let us know.

**Comment by Bravinsimiyu** [comment]
Hello @lalith1403, I have spell-checked the article using Grammarly and edited the article title. Kindly review.

**Comment by ninjaginja** [comment]
plagiarism check completed - all good
[2120420-b652d660c633e6cec594-1626819122012.pdf](https://github.com/section-engineering-education/engineering-education/files/6851516/2120420-b652d660c633e6cec594-1626819122012.pdf)

**Comment by lalith1403** [comment]
There are two index.md files in the current PR. Can you remove the redundant one and let me know. Thank you.

**Comment by Bravinsimiyu** [comment]
Hello, @lalith1403 I have removed the other index.md file

**Comment by lalith1403** [comment]
I feel the changes made are deleting a published article. Can you check with the files changed and let me know. I will immediately get to reviewing this article thereafter.

**Comment by Bravinsimiyu** [comment]
Hello @lalith1403 i had to create another PR

**Comment by Bravinsimiyu** [comment]
@lalith1403 i have issues with the file changed.

**Pull request closed without merging**
