### PR TITLE
MySQL Connection Graphical User Interface design Using JavaFX and Scene builder

### LINKED ISSUE #4384: MySQL Connection Graphical User Interface design Using JavaFX and Scene builder
#### Proposed title of the article
  MySQL Connection Graphical User Interface design Using JavaFX and Scene builder

#### Proposed article introduction
JavaFX is suitable for desktop application development and other applications. Desktop applications should provide an interface where the user can enter data. Through interaction with the desktop application user interface, the data can be saved in a database (MySQL) for processing or any other manipulation .i.e. future retrieval.   
In this article, we will get to learn how JavaFX through scene builder can be used to design a desktop application that can connect to the MySQL database. 
I will demonstrate how to create and design a simple graphical user interface using scene builder and JavaFX where the user can input database connection string, save the connection string in an XML file, retrieve them from the file and connect to the database

#### Key takeaways 
1.	Getting started with JavaFX using Netbeans
2.	 Getting started with scene builder
3.	Intergrading scene builder with Netbeans

#### Article quality
In this article I will be able to demonstrate using a code (FXML and JavaFX) snippet how JavaFX through scene builder can be user to design a user interface which connects to the MySQL database directly. In most of the articles in the internet, concept of connecting Java to MySQL has  no provision  for doing this through graphical user interface. I will therefore bridge this gap through using scene build to design a GUI, bind the resulting FXML file to the application  which from the GUI will provide a means of connecting to the database in any application without going deep to changing the code i.e.  the connection is controlled at the UI level.

#### Reference
https://www.oracle.com/java/technologies/javase/javafxscenebuilder-info.html

### PR DESCRIPTION
**Pull request by JosephAyoma**
…ne builder

### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #4384

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Kayere** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[MySQL Connection Graphical User Interface design Using JavaFX and Scene builder #4608 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7452619/MySQL.Connection.Graphical.User.Interface.design.Using.JavaFX.and.Scene.builder.4608.Copyleaks.Report.pdf)

**Comment by JosephAyoma** [comment]
@Kayere revision done as per the document

**Comment by Dawe-7** [comment]
@Kayere, could we kindly have another plagiarism check.

**Comment by Kayere** [comment]
Plagiarism check done ✔️

**Comment by Kayere** [comment]
Plagiarism check done ✔️

**Review by Dawe-7 — CHANGES_REQUESTED** [review]
Great article @JosephAyoma, I've left you a few suggestions. Kindly implement them so that we can move on to tech review.

**Comment by JosephAyoma** [comment]
@Dawe-7 I have effected the changes

**Review by Dawe-7 — APPROVED** [review]
Awesome article @JosephAyoma. Please go through the changes made throughout the review process so you can improve on the flow and format of your future articles. Looking forward to your contributions. 
Cheers!

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
@JosephAyoma 

Please be sure to review any suggestions/changes made by your peer reviewer and/or myself during a final review.

**Pull request merged**
