### PR TITLE
Dynamic Programming In Javascript Using Tabulation

### LINKED ISSUE #7232: Dynamic Programming in Javascript using Tabulation
#### Proposed article introduction
Dynamic Programming in Javascript using Tabulation

#### Proposed article introduction
Tabulation is a technique used to solve dynamic programming problems. You first fill up a table and then compute the solution to the problem based on the result on the table. It is a Bottom-Up method. We start solving the problems from the base cases (bottom) and gathering answers to the top. Tabulation implementation is iterative in nature.

The advantage of using tabulation is that It‘s fast as we directly access previous states from the table. If all sub-problems must be solved once tabulation is better because all the entries must be filled one by one.

#### Key  takeaways
- What is tabulation?
- What is iteration?
- How to implement tabulation.
- How to use tabulation to solve dynamic programming problems.
- Tabulation time complexity

#### Article quality
This article will cover tabulation algorithms in dynamic programming in depth. The reader will learn how to implement tabulation algorithms, how to work with tabulation to solve dynamic programming problems, and how to calculate tabulation time complexity. This will help the reader to fully understand the topic.

### PR DESCRIPTION
**Pull request by gatwirival**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #7232

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Some plagiarism was identified/highlighted in the attached report.

[New Scan 6_52 AM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/8925240/New.Scan.6_52.AM.Copyleaks.Report.pdf)

**Comment by hectorkambow** [comment]
Our team has been working diligently to clear the backlog and we should be getting this pull request ready to be published next week 🚀

**Comment by hectorkambow** [comment]
Jumping on this one

**Comment by hectorkambow** [comment]
@gatwirival 
👏 Nicely done. Please be sure to review any edits made during the review.

You'll be able to see your live published article on the site (in about 30 mins).

To give your article a boost in page engagement - share it across your social site (LinkedIn/Twitter) and tag the EngEd program so we can also share it and give it some traction as well!
(we will try and do the same once we feature it).

If you have not done so already - consider adding a skill section to your author page. This will go a long way for potential future employers.

**Pull request merged**
