### PR TITLE
Turing Test in AI

### LINKED ISSUE #4976: [Artificial Intelligence]Turing Test in AI
#### Proposed title of article
[Artificial Intelligence]Turing Test in AI

#### Proposed article introduction
This article will provide an overview of the Turing Test in AI, which was introduced in 1950 by renowned mathematician Alan Turing. The purpose of the test was to determine whether a machine can exhibit Human-like Intelligence in its work or thought process. The test was dubbed 'The Imitation Game' in Alan Turing's research paper. He considered a computer/machine to be intelligent only if it could mimic human-like responses. If the interrogator (Judge) cannot determine whether the response is from a machine or a human, the machine passes the test.
#### Key takeaways 
How turing test is performed
Requirements for passing turing test in AI
Feartures of Turing Test in AI
Limitations of Turing test.

#### Article quality
The Modern Day Turing test. Machine is tested using respondents to determine if it is  human or a computer. This article uses simple grammar and it is user friendly.
 
#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by LeemaH2**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4976

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by LeemaH2** [comment]
hello @mbaabuones this is an update of PR#5367

**Comment by mbaabuones** [comment]
> hello @mbaabuones this is an update of PR#5367

@LeemaH2 Thank you for submitting this PR. Although the quality of the article has significantly improved, you have not followed all the instructions. In normal cases, a duplicate PR should be closed immediately if there are further changes needed. However, I will exempt you from this because you are a first-time contributor. Subsequently, ensure you have followed all the suggestions made by reviewers. Please go through the comments in the closed PR and work on ALL the suggested changes.  Ping me when you are done.

**Comment by LeemaH2** [comment]
hello @mbaabuones  the requested updates are in place

**Comment by mbaabuones** [comment]
> hello @mbaabuones the requested updates are in place

All sections should have at least two paragraphs. Add content in the section 'Modern Day Turin Test' and update the table of contents to reflect the section 'features of turin test'.

**Comment by LeemaH2** [comment]
Hi @mbaabuones I've updated the requested changes

**Comment by mbaabuones** [comment]
> Hi @mbaabuones I've updated the requested changes

@LeemaH2 My apologies for taking long to respond to your changes. I was about to move your article to the tech review, but there are still several grammatical errors in your article. In the initial comments, I had requested you to use Grammarly.com to fix these errors. It seems you have not done so. Please fix all grammatical errors in the article. In addition, you did not fix the issue of hero image. Please work on the ALL the changes that were requested. If there will be further changes needed from here, I will be forced to close this PR.

**Comment by LeemaH2** [comment]
Hello @mbaabuones ....Thanks for reaching out to my article....the requested changes are in place

**Review by mbaabuones — APPROVED** [review]

**Comment by mbaabuones** [comment]
> Hello @mbaabuones ....Thanks for reaching out to my article....the requested changes are in place

@LeemaH2 Note the changes I have made.

**Comment by WanjaMIKE** [comment]
Merged #5550 into master

**Pull request merged**
