### PR TITLE
Genie slide in jelly and scale pop up notification effects

### LINKED ISSUE #3247: Genie, Slide-in, Jelly, and scale Pop-up Notification effects
### Proposed title of the article

Genie, Slide-in, Jelly, and scale Pop-up Notification effects

### Introduction paragraph (2-3 paragraphs)

Websites need notifications to display burning events or additional information. Pop-ups, used to pass notifications, are sweet if used effectively and at the right time. Notification effects depending on the main website theme bring a website's unique taste and signature look.

In this article, you will learn how to apply some of these notification effects. These are the Genie, Slide-in, Jelly, and scale Pop-up notification effects. You will see how eye-catching these effects are dependent on the type of information being displayed.

### Key takeaways

By the end of this article, you will learn how to apply some of these notification effects to a webpage. These are the:

- Slide-in effect
- Genie effect
- Scale growth effect
- Jelly pop-up effect

You will also get to know some of the notification effects which we can use on your webpage and when to use them.

### Pre-requisites

For you to flow easily with this article, you need to have some of these basics:

- Basics of HTML.
- Basics of CSS.
- JavaScript interactions.
- Web development IDE. I definitely recommend Visual Studio Code IDE. You can download it from [here](https://code.visualstudio.com/)

### References

N/A

### Templates to use as guides

- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by prograte**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #3247

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Your code is copy-pasted from third-party sources.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Genie slide in jelly and scale pop up notification effects - PART-1](https://github.com/section-engineering-education/engineering-education/files/7189752/New.Scan.10_28.AM.Copyleaks.Report.pdf)
[Genie slide in jelly and scale pop up notification effects - PART-2](https://github.com/section-engineering-education/engineering-education/files/7189753/New.Scan.10_33.AM.Copyleaks.Report.pdf)

**Comment by prograte** [comment]
> Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Your code is copy-pasted from third-party sources.
> 
> Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
> Be sure to see our resources page to see more info on plagiarism and what is considered as such.
> 
> [Genie slide in jelly and scale pop up notification effects - PART-1](https://github.com/section-engineering-education/engineering-education/files/7189752/New.Scan.10_28.AM.Copyleaks.Report.pdf)
> [Genie slide in jelly and scale pop up notification effects - PART-2](https://github.com/section-engineering-education/engineering-education/files/7189753/New.Scan.10_33.AM.Copyleaks.Report.pdf)

I'm working on it...

**Review by mercymeave — CHANGES_REQUESTED** [review]
Hello @prograte,

Thank you for submitting your first article for review. I am so glad to have you on board.

You have a nice article but please consider summarizing your concepts to avoid having an unnecesarily long article. 

Why don't you host your CSS files somewhere and just provide a link to them, They made the article so long.

Ping me once you get done.

**Comment by prograte** [comment]
@mercymeave, it's done...

**Comment by LinusMuema** [comment]
Hi @prograte 

It appears that there are many code snippets in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).
We're really looking for unique/original content.

[Genie slide in jelly and scale pop up notification effects #3860 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7268747/Genie.slide.in.jelly.and.scale.pop.up.notification.effects.3860.Copyleaks.Report.pdf)

**Pull request closed without merging**
