### PR TITLE
Abstraction in Java

### LINKED ISSUE #3240: Abstraction in Java
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Abstraction in Java

### Introduction paragraph (2-3 paragraphs):
Abstraction refers to the process of displaying the important details of a program while hiding the background details from the user. Only the essential details are displayed to the user while the non-essential or trivial are hidden because the user is not required to know them. The practice of identifying only the required attributes of an object while discarding the irrelevant information is known as data abstraction. 
The features and behaviors of an object assist to distinguish it from other things of the same sort, as well as classify and group them. Using a simple example, we can think of abstraction like driving a vehicle. We only deal and know what is required of us but don’t know the mechanism behind the movement. Interfaces and abstract classes are used to achieve abstraction in Java. This article will go through how we can accomplish complete data abstraction using interfaces and Java abstract class and methods.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.
1. What is abstraction
2. Ways to achieve data abstraction
3. Java abstract class and methods.
4. Complete abstraction using interfaces
5. Encapsulation vs Data Abstraction
6. Advantages of Abstraction

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by watosole**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #3240 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by hectorkambow** [comment]
@watosole 👋  Good afternoon

[Abstraction in Java #3402.pdf](https://github.com/section-engineering-education/engineering-education/files/7027843/Abstraction.in.Java.3402.pdf)

👋 Good afternoon - and welcome to the EngEd program.
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.


There appear to be a few (lines of codes) sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. 

There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/.)

**Comment by hectorkambow** [comment]
@watosole 
Also upon a quick glance over it seems this topic may have been well covered in other blogs or official documentation. 

Lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.

cc @Dawe-7

**Comment by Dawe-7** [comment]
@watosole, could you check on the plagiarism and add sources for quotes or images that aren't yours.  Also, your code snippets should be original.  [Here](https://www.scribbr.com/plagiarism/how-to-avoid-plagiarism/l) is more on plagiarism.

**Comment by watosole** [comment]
@hectorkambow , @Dawe-7 
I have resolved the plagiarism errors as advised, is it okay now?.

**Comment by Dawe-7** [comment]
> @hectorkambow , @Dawe-7
> I have resolved the plagiarism errors as advised, is it okay now?.

@watosole, I noticed that you didn't pull the changes i made to the article. In your future articles, make sure to pull any and all changes made to your article by the reviewer.

@WanjaMIKE, could you kindly run another plagiarism check.

**Comment by watosole** [comment]
> > @hectorkambow , @Dawe-7
> > I have resolved the plagiarism errors as advised, is it okay now?.
> 
> @watosole, I noticed that you didn't pull the changes i made to the article. In your future articles, make sure to pull any and all changes made to your article by the reviewer.
> 
> @WanjaMIKE, could you kindly run another plagiarism check.

@Dawe-7, Okay, I will check on that.

**Comment by Dawe-7** [comment]
@watosole, Awesome article, Kindly go through the changes I've made to improve on your future articles.

@hectorkambow, Could we kindly run another plagiarism check. This article is ready for final review.

cc: @Kayere

**Review by Dawe-7 — APPROVED** [review]

**Comment by hectorkambow** [comment]
The % is 40%. 

[Abstraction in Java #3402 2nd scan.pdf](https://github.com/section-engineering-education/engineering-education/files/7080140/Abstraction.in.Java.3402.2nd.scan.pdf)


Will be closing this article until it is reworked. We can't publish any content that is not original or properly cited/referenced.

👍 
Thank you

**Pull request closed without merging**
