### PR TITLE
An Introduction to PyTorch Lightning

### LINKED ISSUE #4642: [Machine Learning] An Introduction to PyTorch Lightning
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

An Introduction to PyTorch Lightning

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Pytorch lightning is a framework built on top of Pytorch. As we know, Pytorch is already great. Pytorch lighning is in a lot of ways even greater. PyTorch Lightining can be compared to the Keras API model which is built on top of TensorFlow. It is a lightweight PyTorch wrapper for high-performance primarily built for use by researchers and computer science PhD students.
This tutorial will give a gentle introduction to PyTorch lighting and implement an example to demonstrate how the framework can be used in code.  

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to understand:
1. What is PyTorch
2. What is PyTorch Lightning
3. The advantages of PyTorch Lightning over unstructured PyTorch
4. Who is PyTorch Lightning for?
5. Implement an example to demonstrate how PyTorch Lightning is used 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [PyTorch Lightning](https://www.pytorchlightning.ai/)
- [PyTorch Lightning GitHub Repo](https://github.com/PyTorchLightning/pytorch-lightning)

### PR DESCRIPTION
**Pull request by Bayler**
This closes #4642

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Review by collins-a — COMMENTED** [review]
@Bayler good job introducing PyTorch Lightning. I'm satisfied with the tutorial as is.

**Comment by Bayler** [comment]
> @Bayler good job introducing PyTorch Lightning. I'm satisfied with the tutorial as is.

@collins-a Thank you for your review.

**Comment by WanjaMIKE** [comment]
@Bayler the gif seems longs. Could you upload it to YouTube and then embed it in the article.

**Comment by Bayler** [comment]
> @Bayler the gif seems longs. Could you upload it to YouTube and then embed it in the article.

@WanjaMIKE  No worries. I'll do that then ping you when done

**Comment by Bayler** [comment]
> > @Bayler the gif seems longs. Could you upload it to YouTube and then embed it in the article.
> 
> @WanjaMIKE No worries. I'll do that then ping you when done

@WanjaMIKE done. I hope I've embedded it correctly.

cc: @collins-a

**Comment by hectorkambow** [comment]
@Bayler Please refrain from creating a pull request to close it. 

We close PR based on how long they have been opened - so this PR was going to be closed (if I had not read the comments).

**Comment by Bayler** [comment]
> @Bayler Please refrain from creating a pull request to close it. 
> 
> We close PR based on how long they have been opened - so this PR was going to be closed (if I had not read the comments).

Noted.

**Comment by WanjaMIKE** [comment]
Nice tutorial @Bayler I like your style

**Comment by WanjaMIKE** [comment]
Merged #4816 into master

**Pull request merged**
