### PR TITLE
Creating a shopping cart API with Java

### PR DESCRIPTION
**Pull request by kingsleynwafor54**
Committing to a new branch as instructed by @ srishilesh  and @john-amiscaray

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
What issue does this PR fix?

**Comment by john-amiscaray** [comment]
@kingsleynwafor54 It doesn't seem you've properly addressed the concerns we've had regarding the version control here. @srishilesh was saying that you were using the same branch you used for your last article on lambdas. To fix this you want to checkout to a new branch on your command line before committing your new article. I think you should try something like:

```bash
git checkout master
git fetch section
git pull --rebase section master
git checkout -b [new-branch]
```
Then add your files and do the following:

```bash
git add .
git commit -m"added article"
git push origin
```

What do you think @srishilesh ?

**Comment by john-amiscaray** [comment]
> What issue does this PR fix?

It's for issue #5585. @kingsleynwafor54 Be sure to add the sentence: *This closes #5585.* in your pull request.

**Comment by srishilesh** [comment]
> @kingsleynwafor54 It doesn't seem you've properly addressed the concerns we've had regarding the version control here. @srishilesh was saying that you were using the same branch you used for your last article on lambdas. To fix this you want to checkout to a new branch on your command line before committing your new article to a new pull request. I think you should try something like:
> 
> ```bash
> git checkout master
> git fetch section
> git pull --rebase section master
> git checkout -b [new-branch]
> ```
> Then add your files and do the following:
> 
> ```bash
> git add .
> git commit -m"added article"
> git push origin
> ```
> 
> What do you think @srishilesh ?

@john-amiscaray 

This should work.

**Pull request closed without merging**
