### PR TITLE
How to Set up and Configure Redis Caching for WordPress

### LINKED ISSUE #2671: How to Set up and Configure  Redis Caching for WordPress
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

Redis an open-source in-memory data structure store that can be used as a caching system. It is a memory caching software that runs on the service.

Redis object cache can be used to optimize the backend performance of WordPress website database usage. This will caching database queries objects, and it stores them in memory. As a result, the strategy will enhance the server response time as well as the website speed.

Whenever a user accesses a  WordPress website, a request is sent to the MySQL server, and then the request is served back to the user from the same server. This operation can be expensive/time, and resource-consuming if you have a large backend WordPress panel.

Redis object can be used to store the cache of this request outputs of the particular query sent to the MySQL server. So when another makes the same request that requires the same query transaction, instead of hitting the MySQL server again, the Redis object will serve the request from the object cache.

This guide will teach you how to set up and configure Redis object cache for your WordPress website or blog.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

What is Redis object cache?
How Redis object works
Setting up and configuring Redis object for WordPress

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Catemacharia**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
Fixes #2671

### CODE REVIEW

**Comment by hectorkambow** [comment]
@Catemacharia 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀

Thank you.

**Comment by hectorkambow** [comment]
@Dawe-7 👍 will be reviewing this article

**Comment by Catemacharia** [comment]
@Dawe-7, Am waiting for your reviews.

**Comment by Dawe-7** [comment]
> @Dawe-7, Am waiting for your reviews.

@Catemacharia, Review in progress. I"ll ping you incase of any changes

**Comment by ninjaginja** [comment]
plagiarism check completed - all good
[2120420-630c97ebfec7885ef03b-1626801991306.pdf](https://github.com/section-engineering-education/engineering-education/files/6850167/2120420-630c97ebfec7885ef03b-1626801991306.pdf)

**Comment by Catemacharia** [comment]
> > @Dawe-7, Am waiting for your reviews.
> 
> @Catemacharia, Review in progress. I"ll ping you incase of any changes

Any progress? @Dawe-7

**Comment by ahmadmardeni1** [comment]
Any progress on this PR? @Dawe-7 👋

**Review by Dawe-7 — CHANGES_REQUESTED** [review]
Great article @Catemacharia, I've left you some suggestions that I think will be helpful to readers. The empty suggestions are unnecessary spacing so you should remove the spaces.

**Comment by Dawe-7** [comment]
@hectorkambow, Kindly add the `revisions needed` and `needs hero image` labels

cc @ahmadmardeni1

**Comment by Catemacharia** [comment]
> Great article @Catemacharia, I've left you some suggestions that I think will be helpful to readers. The empty suggestions are unnecessary spacing so you should remove the spaces. Also, I noticed that you don't have a hero image, consider adding one.
@Dawe-7 Thank you, I have implemented the suggestions and added a hero img.

**Review by Dawe-7 — CHANGES_REQUESTED** [review]
@Catemacharia, Everything looks good. Just one minor change and the article will be ready for final review.

**Comment by Catemacharia** [comment]
> @Catemacharia, Everything looks good. Just one minor change and the article will be ready for final review.

Updated @Dawe-7

**Comment by Dawe-7** [comment]
> > @Catemacharia, Everything looks good. Just one minor change and the article will be ready for final review.
> 
> Updated @Dawe-7

@Catemacharia, Thanks, everything's looking good

**Comment by Dawe-7** [comment]
@hectorkambow, This article is ready for final review.

cc @ahmadmardeni1

**Comment by Catemacharia** [comment]
> @hectorkambow, This article is ready for final review.
> 
> cc @ahmadmardeni1

cc @louisefindlay23

**Review by Dawe-7 — APPROVED** [review]

**Review by louisefindlay23 — APPROVED** [review]
Great tutorial, @Catemacharia. Very easy to understand what Redis is and you've really gone into lots of detail about why Redis is useful in optimising WordPress sites. 

Be sure to check out my minor final review edits to inform future articles.

Thanks, @Dawe-7 for peer reviewing.

**Pull request merged**
