### PR TITLE
How to Create an Automatic Slider in Android Studio

### LINKED ISSUE #1753: How to Create an Automatic Slider in Android Studio
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of the article
How to Create an Automatic Slider in Android Studio

### Introduction paragraph (2-3 paragraphs):
Sliders are commonly used on cross platforms, i.e., websites, Desktop applications, and mobile applications. They are widely implemented on the home pages or application main screens to showcase major and key features.

Let's take the case of an eCommerce application. You would like to show the new items you have in your shop without interfering with the user app interaction. Slides would be a perfect way to showcase some of these major new items to your users.

This guide will walk you through how to create an automatic slider page using android studio.

### What we shall look at
We will create a slider based on the following concepts.
- Populate an array list of slides into a `ViewPager` using `PagerAdapter`.
- Set a list of slides in a tabbed layout and a toolbar.
- Set timmer that will automatically slide to the next slider after a set of milliseconds.

### Prerequisites
This guide uses java in android studio. Prior knowledge of android [ViewPager](https://developer.android.com/training/animation/screen-slide), [PagerAdapters](https://developer.android.com/reference/kotlin/androidx/viewpager/widget/PagerAdapter), and [TabLayout](https://developer.android.com/reference/com/google/android/material/tabs/TabLayout) would be helpful.

### Setting Up
Start a new android studio project. I have changed the default parent theme. To do that on your android studio, go to `res` folder → `values` → `style.xml` and change the app theme, as shown below.

```xml
<resources 
<style name="Theme.AnAutomaticAndroidSlider" parent="Theme.AppCompat.Light.DarkActionBar"></style>
</resources>
```

### Laying out the slider components
Create an XML layout name it `slider_items_layout.xml`. The slides are comprised of two major views.

- A text view for the slide title.
- An image view for the slide hero image.

### Key takeaways: 

- Setting up the android studio project
- Laying out the slider UI components
- Setting a ViewPager and TabLayout
- Setting up PagerAdapte and a model class
- Preparing the slider adapter
- Setting up the timer
- Testing the application

### References: 
https://developer.android.com/reference/kotlin/androidx/viewpager/widget/PagerAdapter
https://developer.android.com/reference/com/google/android/material/tabs/TabLayout

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)

### PR DESCRIPTION
**Pull request by kimkimani**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
fixes #1753

### CODE REVIEW

**Review by WanjaMIKE — APPROVED** [review]
@kimkimani Nice article. I have learned a lot about sliders in Android Studio.

**Comment by hectorkambow** [comment]
@kimkimani  Please see attached PDF - this article has also raised a few flags. 
the % was higher than we typically accept as you are aware. 


[How to Create an Automatic Slider in Android Studio #1782.pdf](https://github.com/section-engineering-education/engineering-education/files/6207183/How.to.Create.an.Automatic.Slider.in.Android.Studio.1782.pdf)

**Comment by kimkimani** [comment]
@WanjaMIKE Check the new updates to confirm if they are okay

**Comment by WanjaMIKE** [comment]
Checking ...

**Comment by WanjaMIKE** [comment]
@hectorkambow could you give this article a final review. Thanks

**Comment by hectorkambow** [comment]
seem to have run into a commit issue / merging issue was not able to commit my changes. 
Will try again in a moment

**Pull request merged**
