### PR TITLE
How to Create a Collapsible Bottom Navigation Android Jetpack Compose Navigation

### LINKED ISSUE #4595: [Android/Kotlin] How to Create a Collapsible Bottom Navigation Android Jetpack Compose Navigation
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

How to Create a Collapsed Bottom Navigation Android Jetpack Compose Navigation

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

Jetpack Compose is our modern native UI toolkit for android. Jetpack Compose is a new way of designing native android apps using Kotlin without XML. The then XML code is now replaced with Kotlin to design our android apps. The design logic is implemented in Kotlin. It is intuitive and built from scratch to accelerate development, letting you write UI with much less code. This means you just focus on building features and spend less time creating UI you want to showcase in your android application. This guide will use Jetpack Compose to create android navigation. In this guide, we will create collapsed bottom navigation using Jetpack Compose Navigation.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

- What is Jetpack Compose
- Getting started with Jetpack Compose
- Getting started with Jetpack Compose Navigation
- Build a collapsed bottom navigation using Jetpack Compose Navigation

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

Jetpack Compose is a new technology for building native android apps using Kotlin. Several articles describe how to create bottom navigations but using XML codes. This guide will focus on using Jetpack Compose to create a bottom navigation bar. We will also make the navigation collapsed by listening to different screen interactions.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Antony-Prince**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4595

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Kayere** [comment]
Plagiarism check done ✔️

**Comment by Ericgacoki** [comment]
Very informative tutorial! Keep it up 🚀

**Review by Ericgacoki — APPROVED** [review]

**Comment by hectorkambow** [comment]
Thank you for your patience as our team has been working diligently to work through the recent increased volume of articles coming in. 

We are going through are ready articles in the order they were received and working on improving our review time as well. 

🚀

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
@Antony-Prince  

@Ericgacoki 

Im confused regarding the images in this article???

There are two articles in this PR? 

@Ericgacoki  please keep a closer eye on this type of issue. 


@Antony-Prince can you please fix this?

**Comment by Ericgacoki** [comment]
Let me take a look 😶

**Comment by Ericgacoki** [comment]
There seems to be some files from already published articles that weren't there during the review process. This could be a result of [this repo update](https://github.com/section-engineering-education/engineering-education/pull/4749/commits/85fac9898d7ea31584b93428e5fbeba4a48c3046).

There are two possible ways to fix this:
1. Delete the unwanted files.
2. Close this PR and open a clean one.

**Comment by Ericgacoki** [comment]
@Antony-Prince, your new PR should only contain the files pictured below. Remember to use the latest version of `index.md`. We apologize for the confusion.

new pr

Final review will continue in your next PR.

cc: @hectorkambow

**Comment by hectorkambow** [comment]
Lets be sure to tie the duplicate PR to this one 👍  - to keep track

Thank you

**Pull request closed without merging**
