### PR TITLE
How to build a Snake Game in JavaScript

### LINKED ISSUE #6037: [Languages] How to Build a Snake Game In JavaScript
#### Proposed title of article

How to Build a Snake Game In JavaScript

#### Proposed article introduction
Hands-on projects are the best way to learn any programming language. The Snake Game is a simple game that can be created using the fundamentals of JavaScript and HTML.
Snake is an old-school video game from the late 1970s. The basic goal is to navigate a snake while eating as many apples as possible while avoiding contact with the walls or the snake's body.
In this article, I’ll show you step-by-step how to create this Snake Game using JavaScript and HTML

#### Key takeaways 
1. Display the board and a still snake
2. Make the snake move automatically
3. Use arrow keys to change the snake’s direction
4. Incorporate food and score

#### Article quality
This article will provide learners with a deep understanding of javaScript. Many articles on the internet rely on official documentation, and their examples are hard for beginners to understand. This article will be perfect for novices, as the code snippets will be well demonstrated and straight to the point.

#### References
N/A

### PR DESCRIPTION
**Pull request by Kamau-ke**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6037

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
The following sentences seem to show some plagiarism. Please correct them. Thanks

Screenshot (1)

**Comment by Kamau-ke** [comment]
@WanjaMIKE  I have incorporated the changes
cc @jumamiller

**Comment by jumamiller** [comment]
Hi, kindly run this submission on a grammar checker. Unfortunately, it has a couple of mistakes.

**Comment by jumamiller** [comment]
Hello @Kamau-ke kindly fix the article!

**Comment by Kamau-ke** [comment]
@jumamiller  I have made the changes. Please have a look.

**Review by jumamiller — CHANGES_REQUESTED** [review]
I have made a couple of grammatical edits. Kindly head over to the commits and check them to help you improve the quality.

Any further revision from this step may lead to the article closure. Submit a ready to publish article!
FYI: You didn't run this article on Grammar checkers. It's one of the requirements.

**Comment by jumamiller** [comment]
Also, <br/> this tag is everywhere, kindly check on the markdown syntax!

**Review by del-ui — APPROVED** [review]

**Comment by jumamiller** [comment]
We'll close this for now. Submit a new PR when ready to be published! Thank you.

**Pull request closed without merging**
