### PR TITLE
Tailwindwithflask

### PR DESCRIPTION
**Pull request by Curiouspaul1**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by Curiouspaul1** [comment]
@hectorkambow i just made the new PR as you requested

**Comment by Curiouspaul1** [comment]
@katungi can you tag @hectorkambow So he knows that I've made a new PR

**Comment by katungi** [comment]
Hey @Curiouspaul1 , Hector will look into it soon enough.

**Comment by hectorkambow** [comment]
Upon 1st glance - it seems that the merge conflict is gone - but my VScode has been a bit glitchy last few days.

**Comment by katungi** [comment]
What do you mean glitchy??

**Comment by Curiouspaul1** [comment]
Hello @katungi @hectorkambow hope you're both doing well, I wanted to know what the update on the PR was and why its taking this long.

**Comment by hectorkambow** [comment]
> Hello @katungi @hectorkambow hope you're both doing well, I wanted to know what the update on the PR was and why its taking this long.

👋  Good afternoon @Curiouspaul1  - all articles go through our queue - so they go through a funnel to get published - this article has a few others before it - I do understand it was a duplicate - so we will try to push it forward. 
👍

**Comment by Curiouspaul1** [comment]
> > Hello @katungi @hectorkambow hope you're both doing well, I wanted to know what the update on the PR was and why its taking this long.
> 
> 👋 Good afternoon @Curiouspaul1 - all articles go through our queue - so they go through a funnel to get published - this article has a few others before it - I do understand it was a duplicate - so we will try to push it forward.
> 👍

Good morning (its 1AM here lol).. i understand thanks for updating me, I appreciate it. Hope to hear from you soon

**Comment by hectorkambow** [comment]
@Curiouspaul1 
> first time contributor, be sure to include a short Author Biography and Headshot image. Please include the files in the authors folder within the GitHub repo. We want to credit you for your hard work.

Please see the author folder for the structure.

We can not publish the article without an author page.

Also please go over the edits I've made during my final review - many run on sentences that made a few paragraphs drag on. 

Overall good work 👍 


cc:
@katungi

**Comment by Curiouspaul1** [comment]
> @Curiouspaul1
> 
> > first time contributor, be sure to include a short Author Biography and Headshot image. Please include the files in the authors folder within the GitHub repo. We want to credit you for your hard work.
> 
> Please see the author folder for the structure.
> 
> We can not publish the article without an author page.
> 
> Also please go over the edits I've made during my final review - many run on sentences that made a few paragraphs drag on.
> 
> Overall good work 👍
> 
> cc:
> @katungi

Thanks for the review, I'll go over it and make the necessary changes

**Comment by Curiouspaul1** [comment]
Hi @hectorkambow I just pushed the updates as on account of the review.

**Comment by hectorkambow** [comment]
@Curiouspaul1 Just noticing that this PR has 198~ files I believe there was an error when doing a Git pull/push via the text editor. (see image.) 

Your PR should only include your files needs for your article. 

Please see our FAQ in our repo to how to solve a merge conflict. 

cc @katungi  Please try to take note for these type of issues in future articles 👍 

image

**Comment by hectorkambow** [comment]
Will be closing to clear up queue. 

Please link this PR to the new clear PR without the merge conflict. If you are new to using GitHub and Git we can refer some resources as well to help along 🚀

**Pull request closed without merging**
