### PR TITLE
creating a responsive html registration form

### LINKED ISSUE #3081: Creating a responsive HTML registration from
### Introduction
In this tutorial we will learn how to create a Responsive HTML Registration Form. The registration form has multiple input fields with varied input details where the user must enter in his or her information in order to submit for a certain web page. There are many different sorts of registration forms, but the main goal of these form is to collect information or facts from the user.

### Key takeaways: 

- Creating basic Html template for registration form
- Adding CSS design 
- Creating responsive registration form

### References: 
N/A

### PR DESCRIPTION
**Pull request by harshitab13**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3081

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by M0nicah** [comment]
Hello @harshitab13 , I have gone through your PR and I have noticed some grammatical errors.
You have also used both first and second person, they are all mixed up. Could you please go through the article once more? Try to use third person like "we" instead of "I".

Check on spelling mistakes too.
Thanks.

**Comment by harshitab13** [comment]
@M0nicah I have done the changes.

**Comment by M0nicah** [comment]
Hi @harshitab13 , please add a hero image for your article. It should be 600x400 pixels. You may get them from Unsplash.

It can be an image of a login, sign up form or anything related to HTML and CSS. These are the final changes before we move to the next step.
Thanks.

**Comment by harshitab13** [comment]
@M0nicah  added hero image

**Comment by hectorkambow** [comment]
[creating a responsive html registration form #3442.pdf](https://github.com/section-engineering-education/engineering-education/files/7080162/creating.a.responsive.html.registration.form.3442.pdf)

👋 Good afternoon - and welcome to the EngEd program.
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % way was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

We will be closing this PR - while the content is re-worked. 

Make the changes on your forked repo and create a new PR with a duplicate label when the articles is polished and ready to publish.

**Pull request closed without merging**
