### PR TITLE
Introduction to Dynamic Host Configuration Protocol (DHCP)

### LINKED ISSUE #1613: Introduction to Dynamic Host Configuration Protocol (DHCP)
### Proposed title of article
 Introduction to Dynamic Host Configuration Protocol (DHCP)

### Introduction 
The vast majority of the host on the internet are user-end devices. These devices require a unique identifier on the internet known as an Internet Protocol (IP) address.
This address can be configured as static by a network administrator or dynamically using Dynamic Host Configuration Protocol (DHCP).
This article will look at DHCP version 4 (DHCPv4) and DHCP version 6 (DHCPv6).

### Key takeaways: 
At the end of this article, the reader should have learned:
- What DHCP is
- the need for DHCP
- The various versions of DHCP in used

### References: 
https://www.efficientip.com/what-is-dhcp-and-why-is-it-important/

### PR DESCRIPTION
**Pull request by raboba2re**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

This fixes #1613

### CODE REVIEW

**Comment by raboba2re** [comment]
@srishilesh  please I will like you to review this article.  I will like to know if I followed your recommendations from my last PR

**Comment by hectorkambow** [comment]
plagiarism check done

**Review by srishilesh — APPROVED** [review]
Hey @raboba2re,

Thanks for the PR.

Great article. You have improved a lot since your last review. Keep up the great work!

There were minor flow and formatting changes. You can refer the commits to know them. Also, you had missed to add a `!` for images. Apart from these changes, everything else looks great.

Moving this article for the final review.

Thank you.

**Comment by raboba2re** [comment]
@srishilesh thank you so much for your guidance and patience, I have learned a lot from you sir. 
And for the "!", it was an oversight, sorry for that.

**Comment by hectorkambow** [comment]
Great work gentlemen 

@raboba2re  
cc @srishilesh

**Pull request merged**
