### PR TITLE
Generating Machine Learning Pipelines with TPOT in Python

### LINKED ISSUE #3150: Generating Machine Learning Pipelines with TPOT in Python.
### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
A machine learning pipeline is a way to codify and automate the workflow it takes to produce a machine learning model. Machine learning pipelines consist of multiple sequential steps that do everything from data extraction and preprocessing to model training and deployment.
Here we shall use TPOT for the machine learning pipeline, TPOT is a python library that uses genetic programming behind the scenes to generate an optimized ML pipeline. It uses the concept of natural selection, survival of the fittest, and mutation to find the best machine learning model and the required parameters to produce the best result.
TPOT will enable us to automate some of the stages of the ML life cycle such as feature engineering, model building.
TPOT utilizes these 3 concepts
1. Selection: selecting the best
2. Crossover: crossbreed the selected best over and over to get the best of the best
3. Mutation: mutate the best to become even better.

### Key takeaways: 
1. Data Preparation.
2. Installing TPOT.
3. Using three concepts of TPOT in building our model, Selection, crossover, and mutation.
4. Implementing machine learning pipelines to automate feature engineering and model building.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by kelvinkimani501**
This fixes #3150 
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by lalith1403** [comment]
@kelvinkimani501 Welcome to EngEd Program. Thank you for submitting the article. Upon first glance, it looks exciting. However, there are several readability issues (grammatical errors, tough to comprehend paragraphs). Can you rectify the same so that we can move on to the review stage? You may refer to the [contribution guidelines](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors). 

Ping me once done.

**Comment by Bravinsimiyu** [comment]
Hello, @lalith1403 I have made the requested changes.
Thanks.

**Comment by kelvinkimani501** [comment]
I have made the requested changes.
Thanks.
@lalith1403

**Comment by hectorkambow** [comment]
@kelvinkimani501 

[Generating Machine Learning Pipelines with TPOT in Python #3343.pdf](https://github.com/section-engineering-education/engineering-education/files/6995921/Generating.Machine.Learning.Pipelines.with.TPOT.in.Python.3343.pdf)

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

Also want to make sure there is no overlap with this article:

https://blog.jcharistech.com/2020/05/29/generating-machine-learning-pipelines-using-tpot-and-genetic-programming-in-python/

cc @lalith1403

**Comment by lalith1403** [comment]
There is a lot of overlap with the website mentioned by @hectorkambow. The code examples are the same. The topics covered are the same as well.

**Comment by kelvinkimani501** [comment]
@lalith1403, I will have to close this PR and work on another topic.

**Pull request closed without merging**
