### PR TITLE
Understanding and Implementing Passwordless SSH

### LINKED ISSUE #6276: [Networking]Understanding Passwordless SSH
### Topic Suggestion
Understanding Passwordless SSH

### Writing sample(s): 
[How to Add Pure CSS Waves to Your Website](https://www.section.io/engineering-education/pure-css-wave-animations-website/)

#### Proposed title of the article
Understanding Passwordless SSH

#### Proposed article introduction
Online privacy and security are vital considerations in technology. In the current era, information is comparable to gold. Because of the value that information holds, there has been a rise in better security practices and strategies meant to ensure information remains secure on the internet. The secure shell host protocol (SSH) is among the vital security implementations technology experts use to secure information on transit in an unsecured network. As time passes the cryptographic based protocol has seen a revamp into a passwordless alternative meant to increase its robustness as one of the best security protocols in use. 

#### Key takeaways 
- what is passwordless SSH
- Reasons for preferring passwordless SSH over normal SSH 
- Advantages and disadvantages of passwordless SSH
- Use cases of passwordless SSH
- How to set up passwordless SSH

#### Article quality
Articles on the web only focus on how one can set up passwordless SSH. This article takes a broad but deeper approach to include the advantages and disadvantages of the technology combined with an explanation of the what, why and how of passwordless SSH.
#### References
N/A

### PR DESCRIPTION
**Pull request by lin-chez**
#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [X] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #6276

### CODE REVIEW

**Comment by Bayler** [comment]
@lin-chez Please remove the authors index.md file. I'm not sure why you included it

**Comment by lin-chez** [comment]
Hello @Bayler! The authors index.md file was automatically included in my commits since I had a merge conflict.

**Comment by Bayler** [comment]
> Hello @Bayler! The authors index.md file was automatically included in my commits since I had a merge conflict. 

You need to remove it.

**Comment by lin-chez** [comment]
@Bayler I have removed the file.

**Comment by wilkistermumbi** [comment]
> @Bayler I have removed the file.

It seems like that file is still causing conflicts. If you can't resolve that conflict, it'll cause merging issues in the future. If you can't solve it, create a new PR in a new branch and make sure to only upload the required files.

**Comment by Bayler** [comment]
@lin-chez It seems like that file is still causing conflicts. If you can't resolve that conflict, it'll cause merging issues in the future. If you can't solve it, create a new PR in a new branch and make sure to only upload the required files.

**Pull request closed without merging**
