### PR TITLE
How to build a GlassBox Model using InterpretML Python

### LINKED ISSUE #5052: [Machine Learning] How to build a GlassBox Model using InterpretML Python
#### Proposed title of article
[Machine Learning] How to build a GlassBox Model using InterpretML Python

#### Proposed article introduction
Glass box models are models that are transparent to the user. In a glass box model, all the features and parameters are known to the user and they know the criteria used by the model to reach its prediction results and conclusion. This gives full transparency and one can know how the model works and functions behind the scene.

Over the years, many machine learning engineers have been building black-box models. Black-box models, the users do not know the internal workings and the functionality of the model. Users cannot understand these models and they end up accepting the model blindly.  Developers hide the actual risk of using these models, Glassbox model is the better alternative that gives you exposure to the model.

In this tutorial, we will use InterpretML to build a glass box model. It will build a model that will be able to explain itself and give a more transparent view to the users. This will improve quality products, machine learning processes, and research. Examples of glass box models are decision tree models and linear models.

#### Key takeaways
1. Black box models vs Glass box models.
2. Example of the Glass box model.
3. How to work with InterpretML Python
4. Building a transparent.
5. Analysing the model results.

#### Article quality
This tutorial will compare two concepts of building machine learning models: Black box models and Glass box models. It will look into the traditional black-box models and some of their limitations that led to the introduction of glass box models. We will dive into a glass box model and build a custom transparent model from scratch.
Finally, we will analyze the prediction results made by the model so that we can have a better understanding of the model.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by charlesndirutu33**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5052

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Plagarism check complete

**Review by mercymeave — COMMENTED** [review]
Hello @charlesndirutu33 

You have a great article here. I am marveled at your level of fluency and flow for your first article. You have done great. However, minimize the use of `this` and `let us`. Making it redundant makes the writing dull and lacks professionalism.

I am proceeding to tech review.

**Review by mercymeave — APPROVED** [review]
Hello Charles,

Thank you for your great article. Let us wait for a final review.

**Comment by LinusMuema** [comment]
Hi @charlesndirutu33 
Awesome job on the article.

cc: @mercymeave

**Pull request merged**
