### PR TITLE
How to create a Machine Learning App using the FastAPI and deploying it to the Kubernetes cluster

### LINKED ISSUE #2799: How to create Machine Learning App using the FastAPI and deploying it to kubernates cluster
### Proposed title of the article
How to create Machine Learning App using FastAPI and deploying it to Kubernetes cluster

### Introduction paragraph (2-3 paragraphs):
FastAPI is a modern, fast (high-performance), web framework for building APIs with Python 3.6+.
Here we will build our machine learning model, after creating the model we will create an application using the FastApi which has different routes that can be used to make predictions.
After serving our machine learning model as an API, we will create a docker container for the application.
Finally, we will be able to deploy the FastAPI docker container to the Kubernetes cluster.
### Key takeaways: 
1. How to create a simple machine learning model.
2. How to install the FastAPI.
3. Serving the ML model as an API using the FastAPI.
4. How to create Docker Container.
5. Deploying the FastAPI docker container to Kubernetes cluster.
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Bravinsimiyu**
This fixes #2799
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by Bravinsimiyu** [comment]
@lalith1403 I had to open another PR

**Comment by lalith1403** [comment]
I will get to it immediately. Thank you for your patience.

**Comment by lalith1403** [comment]
@Bravinsimiyu there are still files from the previous PR. Let me know if you are facing any difficulty. 

Thank you

**Comment by Bravinsimiyu** [comment]
Hello @lalith1403 it seems I have some difficulties

**Comment by Bravinsimiyu** [comment]
From my end there is only one index.md, I would like your help @lalith1403

**Comment by lalith1403** [comment]
image

The article titled, How to Deploy Streamlit App with Docker, is your earlier published article. You have to rebase your repository and update the contents of the master branch. Then, create a new branch and insert this article in a new folder. Let me know if you need more help with this.

**Comment by Bravinsimiyu** [comment]
Hello, @lalith1403 am unable to rebase my repo.
But I have now seen the duplicate file

**Comment by Bravinsimiyu** [comment]
I have managed to create a new branch called "new" and added the article
But I'm unable to update the master branch with my original article

**Comment by lalith1403** [comment]
@hectorkambow any guide that you can refer the author to for more info on GitHub?

**Comment by Bravinsimiyu** [comment]
hello @lalith1403, I was using the UPLOAD_INSTRUCTIONS.md but still, it does not restore everything.
I used this commands
git fetch section

git pull --rebase section master

git push origin

**Comment by lalith1403** [comment]
Can you list out the steps you carried out from the beginning. That way we can debug the error.

**Comment by Bravinsimiyu** [comment]
1. I ran this command git remote add section http://github.com/section-io/engineering-education
2. git fetch section

fetch

**Comment by Bravinsimiyu** [comment]
3. git pull --rebase section master
rebase

**Comment by Bravinsimiyu** [comment]
rebase1

**Comment by Bravinsimiyu** [comment]
it only restores a duplicate file of my current article but not my previous article
rebase1_LI

**Comment by lalith1403** [comment]
Interesting. Let's try this. 
Delete the repository that you have cloned. Re-clone the repository and issue the following commands. Avoid using the master branch to submit new PRs. Once cloned, use the following commands:
1. git remote add section http://github.com/section-io/engineering-education
2. git fetch section
3. git pull --rebase section master


Add the folder containing your article after pulling all the changes. Let's create a new branch and then try the new commands:
1. git checkout -b new-branch-name
2. git add .
3. git commit -m "message description here"
4. git push

**Comment by Bravinsimiyu** [comment]
hello @lalith1403, it still does not restore everything.
instead, it has a lot of conflicts with other authors articles

**Comment by Bravinsimiyu** [comment]
can I use my other GitHub account to make create the same topic suggestion and make the PR for the same using a different GitHub account?

**Comment by Bravinsimiyu** [comment]
but you can still review it as the same article but just on a different GitHub account to reduce the conflicts
@lalith1403

**Comment by lalith1403** [comment]
@hectorkambow Need your help with this particular issue.

**Comment by hectorkambow** [comment]
@Bravinsimiyu Have you tried deleting the entire forked repo - recloning it via VScode (or your text editor) - and then adding your files in. 

The reason for the conflicts (most probably) is due to the fact your repo is not up to date with the main EngEd repo. 

Every article should be its own seperate branch - on your forked repo. 


cc @lalith1403

**Pull request closed without merging**
