### PR TITLE
Recovering Deleted Files with foremost

### LINKED ISSUE #3183: Recovering Deleted Files Using Foremost
### Proposed title of article

Recover Deleted Files With Foremost

### Introduction paragraph (2-3 paragraphs):
Foremost is a forensic program used to recover lost files based on their headers, footers, and internal data structures. It implements a technique known as data carving. It is free and comes with most Linux platforms. This makes it ideal to use in recovering deleted data in hard disk drives and pen drives.

In this tutorial, we will be showing stepwise how to use foremost to recover deleted files from a pen drive. We will then show how to use foremost to recover deleted files from a whole hard disk drive or a specific partition of the hard drive.

### Key takeaways: 

1. Installing foremost in a Linux platform.
2. Tools included in the foremost package.
3. Use foremost to recover deleted files of all types.
4. Use foremost to recover a specific file type.

### References: 

N/A

### PR DESCRIPTION
**Pull request by FINCH285**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3183 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Bayler** [comment]
@FINCH285 @FREDERICO23 ???

**Comment by FINCH285** [comment]
@FINCH285

**Comment by FINCH285** [comment]
@Bayler I used @FREDERICO23 computer to commit my article. I think I might have left out something

**Comment by Bayler** [comment]
> @Bayler I used @FREDERICO23 computer to commit my article. I think I might have left out something

Noted. Have you left out anything?

**Comment by hectorkambow** [comment]
@FINCH285 

The XML file needs to be included as a code snippet if its needed for the article - but that file can not be published. 

it can also be a link if needed 

cc @Bayler

**Comment by hectorkambow** [comment]
@FINCH285 

[Recovering Deleted Files with foremost #3376.pdf](https://github.com/section-engineering-education/engineering-education/files/6996014/Recovering.Deleted.Files.with.foremost.3376.pdf)

There appear to be many sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/.)

cc @Bayler

**Pull request closed without merging**
