### PR TITLE
HOW TO DEPLOY DJANGO PROJECT WITH DATABASE USING HEROKUAPP HOISTING SERVICES. 

### LINKED ISSUE #2637: HOW TO DEPLOY DJANGO PROJECT WITH DATABASE USING HEROKUAPP HOISTING SERVICES.
### Introduction

Deploying Django project with database can be done using different hoisting platforms. There are some dependencies required for the project to be hoisted as described by chosen platform. Heroku has been one of the great and sweet hoisting platform for Django project and in this article I will walk you through how to do just that using one of  my deployed site on Heroku which uses their database, https://microstoryapp.herokuapp.com . Lets get to real gist later!!

### Key Takeaways
At the end of this tutorial, readers will get proper understanding of how they can hoist their project on the chosen platform using the following concepts:

How to setup Django project with requirement dependencies,
How to setup account and login with Heroku,
How to push up project to git so that Heroku account created can access it,
Finally, How to hoist your project and get domain name with extension of herokuapp.com.

### Reference Sites
Heroku Official Website

### PR DESCRIPTION
**Pull request by Horlawhumy-dev**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

this fixes #2637

### CODE REVIEW

**Comment by Horlawhumy-dev** [comment]
What about this sir @hectorkambow @marienjus

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. :rocket:
Link your topic-suggestion, please.
Thank you. @Horlawhumy-dev

**Comment by Horlawhumy-dev** [comment]
Oh! My bad. Thanks @ahmadmardeni1

**Comment by Horlawhumy-dev** [comment]
Hope I am not missing any info on the review. @ahmadmardeni1 @zolomohan

**Comment by hectorkambow** [comment]
@Horlawhumy-dev This PR has MULTIPLE index files. 

Multiple articles on it. It should only have the articles to be published. One a time - each articles should be its own branch.

**Comment by hectorkambow** [comment]
@Horlawhumy-dev 

I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[HOW TO DEPLOY DJANGO PROJECT WITH DATABASE USING HEROKUAPP HOISTING SERVICES. #3225.pdf](https://github.com/section-engineering-education/engineering-education/files/6963598/HOW.TO.DEPLOY.DJANGO.PROJECT.WITH.DATABASE.USING.HEROKUAPP.HOISTING.SERVICES.3225.pdf)

**Comment by Horlawhumy-dev** [comment]
Sorry about that sir. I have done the corrections.

**Comment by zolomohan** [comment]
Thank you @Horlawhumy-dev @hectorkambow. I'll start the preliminary revisions soon.

**Pull request closed without merging**
