### PR TITLE
Getting Started With Datastore In Kotlin

### LINKED ISSUE #1404: Getting started with Preference DataStore in Kotlin
### Brief Summary: 
A lot of developers have used SharedPreferences at one point of their development process to store key-value pairs. But there was just something about it. Such as manually needing to switch to a background thread, not being safe from runtime exception and signal errors  like IOException.  Jetpack DataStore works pretty much the same but offers more capabilities. 

### Key Takeaways: 
- Understanding what is DataStore and why you should use it.
- A brief description of the different types of DataStore and how they work.
- Working with Preference DataStore.

### References: 
N/A

### PR DESCRIPTION
**Pull request by carolinemusyoka**
### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [X] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [X] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [X] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1404

### CODE REVIEW

**Comment by carolinemusyoka** [comment]
This fixes issue #1404

**Review by paulodhiambo — CHANGES_REQUESTED** [review]
@carolinemusyoka amazing article on Datastore. I have made a few suggestions, review and ping me when done. Add your author profile in the authors' directory, I have seen its missing.

**Comment by carolinemusyoka** [comment]
Hey @paulodhiambo , thank you for reviewing my PR. I`m done correcting the suggested edits.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by paulodhiambo** [comment]
@carolinemusyoka an amazing article on Datastore with Kotlin.

**Comment by hectorkambow** [comment]
@carolinemusyoka  Great tutorial - seems like a very useful tutorial for the community. 

Please review the edits made during the revision process to implement into future articles 👍  


cc @paulodhiambo  please do the same to improve format during revisions. 💯

**Pull request merged**
