### PR TITLE
Getting started with Jetpack Compose in Android

### LINKED ISSUE #2538: Getting started with Jetpack Compose in Android
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

### Proposed title of article

Getting started with Jetpack Compose in Android

### Introduction paragraph (2-3 paragraphs):

Android’s current UI toolkit is over 11 years old now. Over this time, a lot of issues have been raised concerning the overall performance of the imperative paradigm used. Every Android developer would love to see all the pain points of the old view system and XML layouts go away.

Jetpack Compose is a modern toolkit designed to simplify UI development in Android. It combines a reactive programming model with the conciseness and ease of use of the Kotlin programming language. It is fully declarative, meaning you describe your UI by calling a series of composable functions that transform data into a UI hierarchy.

 This article will walk you through the fundamental concepts that you need to get started with this new paradigm.
  
### Key takeaways: 

In this article, the reader will learn:

1. Why we need Jetpack Compose.
2. How to build UIs with Compose.
3. How to manage states in composable functions.
4. Data flow principles in Compose.
5. What to expect in Jetpack Compose version 1.0.0

### References: 

N/A

### PR DESCRIPTION
**Pull request by MaurineM**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This Fixes #2538

### CODE REVIEW

**Comment by MaurineM** [comment]
Closing to add author details

**Comment by MaurineM** [comment]
Reopening for review

**Comment by hectorkambow** [comment]
plagiarism check done

**Review by kayere — APPROVED** [review]
Great article @MaurineM, very informative and easy to follow through. Please go over the changes I have made to help improve the quality of your future articles.

**Review by louisefindlay23 — APPROVED** [review]
Great article, @MaurineM. Final review complete.

Thanks for reviewing, @kayere.

**Pull request merged**
