### PR TITLE
Predicting Covid-19 Cases using NeuralProphet

### LINKED ISSUE #6167: [Machine Learning] Forecasting Covid-19 Caseload and Mortality using NeuralProphet
### Topic Suggestion
Forecasting Covid-19 Caseload and Mortality using NeuralProphet

### Writing sample(s): 
[Writing Style](https://www.section.io/engineering-education/save-and-load-stacked-ensembles-in-onnx/)

#### Proposed title of article
Forecasting Covid-19 Cases and Deaths using NeuralProphet

#### Proposed article introduction
Performing predictions on datasets where a time series is the independent variable can prove challenging using traditional machine learning methods. Facebook (now Meta) in 2017 came up with a library which extracts non-linear patterns which may have daily, weekly or other seasonality. This library is called Prophet (previously known as FbProphet).
One limitation of the library is that it does not generalize well to complext trends thus tends to under-fit.  The Data Science Core Team at the company thus came up with NeuralProphet, a library based on AR-Net, a simple auto-regressive Neural Network for time-series and Pytorch.

We shall use the global cases dataset from Johns Hopkins University Center for Systems Science and Engineering (JHU CSSE) Global Covid-19 Data repository to perform forecasting. This is a very useful dataset as it has a lot of seasonality and complex patterns.

#### Key takeaways 
This tutorial will help the reader with;
- Understanding Time-Series Forecasting
- Installation of NeuralProphet
- Formating the data for forecasting
- Performing Forecasts on a single series
- Forecasting on multiple series

#### Article quality
NeuralProphet is not widely written on as it is fairly new (released in 2021).
Covid-19 data provides a quality pattern set for performing forecasting on using a neural-network based method.

#### References
[NeuralProphet Release Notes](https://ai.facebook.com/blog/neuralprophet-the-neural-evolution-of-facebooks-prophet/)
[COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University](https://github.com/CSSEGISandData/COVID-19)
[Prophet on GitHub](https://github.com/facebook/prophet)

### PR DESCRIPTION
**Pull request by iannjari**
Created: content/articles/predicting-covid-using-neuralprophet/index.md
This article gives a tutorial on how to Forecast Covid-19 Cases using NeuralProphet

Image: content/articles/predicting-covid-using-neuralprophet/hero.png

This closes #6167

### CODE REVIEW

**Comment by lalith1403** [comment]
plagiarism check done ✔️

**Comment by wilkistermumbi** [comment]
@iannjari I find your article too shallow. I'd like you to go through this [tutorial](https://github.com/section-engineering-education/engineering-education/pull/5874/files) to see the standard of writing and formatting we want for publishing. That tutorial will give you an idea of how you can improve your tutorial.

**Comment by hectorkambow** [comment]
@wilkistermumbi 

Any update on this - if any other edits are needed - we will be closing the PR 👍

**Comment by wilkistermumbi** [comment]
For reproducibility purposes, I'd like you to reproduce the results from this experiment using Google Colab then add the link in this tutorial.

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
