### PR TITLE
Introduction to recursion in ruby

### PR DESCRIPTION
**Pull request by ianmaish**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by ianmaish** [comment]
This fixes #1770

**Comment by WanjaMIKE** [comment]
@ianmaish where is your commit for the article. I am not seeing it.

**Comment by ianmaish** [comment]
@WanjaMIKE done changes

**Comment by WanjaMIKE** [comment]
Nice article @ianmaish Please remember to always add a conclusion.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by hectorkambow** [comment]
@ianmaish 
This PR has another index file in it. 

Can you please delete those unneeded files - and or submit a new PR with only the needed files

cc @WanjaMIKE

**Comment by hectorkambow** [comment]
image

**Comment by ianmaish** [comment]
Done changes 
@hectorkambow

**Comment by hectorkambow** [comment]
@ianmaish  
🤔  

My apologies that didn't seem to work - the file was deleted but the PR still shows it - my concern is that once merging this PR - it will in fact delete that index file from our main repo. 

(also seeing this weird file as well) see image

image


The best way to fix and avoid all this is to create a new PR - but make sure that you create a new Branch from your forked repo 
on that branch only add the necessary files on that PR. 

That way there will be no extra index file or shortcut file. 

Our apologies for the back and forth - sometimes new contributors have some issues with GItHub - but after a successful try it get much smoother.

**Pull request closed without merging**
