### PR TITLE
Applying AI and ML to predict consumer behavior

### LINKED ISSUE #1663: Applying AI and Machine Learning to predict customer behavior
Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposed title of article
**Role of AI in Futuristic Digital Marketing**

### Introduction paragraph(s):
Artificial Intelligence is changing the face of digital landscape in the recent past. AI can analyze data to easily predict the buying behaviors and decisions of target customers and also improve user experience to provide the audience what they actually need.

In this article, we will learn about how AI has helped in understanding customers better. We will also learn about various tools and technologies which helps in Data analysis for providing better insights on consumer behavior.

### Key takeaways: 
- Reader will understand the importance of AI and its deployment in understanding targeted customers better for their buying behaviors and decisions
- Reader will also understand how AI helps to improve user experience
- Reader will learn about various data analysis tools and technologies

### References: 
- https://www.nihtdigitalmarketing.com
- https://www.smartinsights.com

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by skay-ai**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #1663

### CODE REVIEW

**Review by srishilesh — APPROVED** [review]
Hey @skay-ai,

Welcome to EngEd community!

Amazing article. It's very beginner friendly.

Moving for the final review.

Thanks.

**Comment by louisefindlay23** [comment]
@hectorkambow, can you please run a plagiarism check on this article?

**Comment by hectorkambow** [comment]
plagiarism check done

**Review by louisefindlay23 — APPROVED** [review]
Great article, @skay-ai. Final review complete.

Thanks, @srishilesh for peer reviewing.

**Comment by skay-ai** [comment]
Hey @srishilesh / @louisefindlay23 ,

Thanks for reviewing and publishing my article. I'm really excited for publishing my very first article at Section.

Just to clarify, I was paid only 150 USD for a tech tutorial. (I believe it's 250 USD for tutorials, as mentioned [here](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/FAQ.md))

I believe this blog is a tech tutorial. As mentioned in the guidelines for a tech tutorial, I've explained step by step on how to predict consumer behaviour, using codes in Python. The reader will learn to do that from scratch.

I'm not sure if my blog was misclassified as an article. Moreover, there wasn't any revisions needed from my side.

Please help me understand.

**Comment by louisefindlay23** [comment]
Thanks for informing us, @skay-ai. Will forward to one of the program managers, who can take this further. 

cc -  @ninjaginja.

**Comment by ahmadmardeni1** [comment]
Hey 👋🏻 @skay-ai
Sorry for the confusion, we have modified it to $150 per tutorial months ago. 

We told the technical writers about it via Slack, but I'm not sure why we didn't edit our docs. Again, we are sorry for any misunderstanding.

**Comment by ninjaginja** [comment]
Thank you for reaching out @skay-ai. It looks as if the FAQ doc did not get updated when we rolled out the new payout structure, as documented [here](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md). The current payout for tutorials is $150. I have just updated the FAQs to reflect the correct amounts. Apologies for the confusion.

**Pull request merged**
