### PR TITLE
Submitting Data to a Google Form in Android

### LINKED ISSUE #6952: [Android] Submitting Data to a Google Form in Android
### Submitting Data to a Google Form in Android

Google Forms is a survey administration software included as part of the free, web-based Google Docs Editors suite offered by Google. The app allows users to create and edit surveys online while collaborating with other users in real-time.

Google Form provides a quick, flexible and easy to use platform for the academic unit to deploy in form in any shapes and sizes. The Google form allows administrators to quickly create forms that's suitable for most academic needs, including event registration, major/minor declaration, student information submission, alumni info update, etc.

With Google Forms, you can collect all answers in one place. You can even embed the form directly into your email.

The problem is that Google Forms is only available as a web application which makes integrating it to an Android harder. In this tutorial, we will create a simple android app that needs to submit some survey data to a a web based google form with Retrofit.

### Key takeaways
- What are Google forms?
-  How to create a Google form.
- Google form being a web based software, understand how to send data to a google form from an Android app.
- Validating the form before sending the data.

### Article quality
This article will be up-to-date and very informative:
- I have gone through the web, most developers are struggling with integrating Google forms in Android, there are some answers in Stackoverflow but not that helpful.
-  This [article](https://www.androidmads.info/2016/10/google-form-to-android-application.html) is almost similar to the issue that I am raising but it is old and uses older technologies and libraries.

References
- N/A

### PR DESCRIPTION
**Pull request by calvinombati**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6952

### CODE REVIEW

**Comment by lalith1403** [comment]
PFA the plagiarism report. It is higher than what we accept. Please make the changes accordingly. Thank you.

**Comment by calvinombati** [comment]
Hello @jerimkaura, I have fixed those small instances that were raising plagiarism.

**Review by jerimkaura — APPROVED** [review]
@calvinombati 

Great article. Moving this forward to the final review.

Take note of the changes made to sharpen your future articles

**Comment by ahmadmardeni1** [comment]
Great work team @calvinombati @jerimkaura

**Pull request merged**
