### PR TITLE
[duplicate] end-to-end speech recognition

### PR DESCRIPTION
**Pull request by extravaganza77**

### CODE REVIEW

**Comment by extravaganza77** [comment]
@hectorkambow @lalith1403  This is an article update.

**Comment by lalith1403** [comment]
The article folder needs to go inside the articles folder. The author folder needs to go inside the authors' folder. Can you change that? The earlier issue was the same thing.

**Comment by extravaganza77** [comment]
@lalith1403 
changes are in place

**Comment by extravaganza77** [comment]
@lalith1403 
what's the update on my article?

**Comment by lalith1403** [comment]
The article will go through the queue again and will ping you once your article is up for review. Thank you.

**Comment by lalith1403** [comment]
This PR has merge conflcts. Can you check once?

**Comment by lalith1403** [comment]
Closing PR due to inactivity.

**Pull request closed without merging**
