### PR TITLE
Building web application with kotlin and typescript

### LINKED ISSUE #4920: Building web application with Kotlin and Typescript
### Topic Suggestion
Building web application with Kotlin and Typescript

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Building web application with Kotlin and Typescript

#### Proposed article introduction
The integration occurs in the context of а web application (bасkend) that runs on а JVM and а browser application (frоntend) that еmрlоys а TypeScriрt-bаsed frаmewоrk like ngulаr оr Reасt (with the TypеScriрtiоn). On the JVM side, Kоtlin integration is simple, and with the right build tool (i.e., Grаdle and the Kоtlin Multiрlаtfоrm Plugin), Kоtlin code is built into a simple jаr mоdule. This JVM JAR can be used just like any other JVM JAR. The JаvаSсriрt side of things is a little more difficult. The build tool will compile the Kotlin code and generate a jаr containing the UMD JаvаSсriрt mоdule (by default). The interesting part is incorporating this into the node. JS-based integrated browser application programming interface

#### Key takeaways 
- The Build Scripts
- The information module
- The client module
- Unpacking the Kotlin modules
- Using Kotlin generated modules in TypeScript code
- TypeScript types for Kotlin code
- TypeScript declarations for third party libraries

#### Article quality
This article describes the problems encountered whilst integrating Kotlin generated modules with a TypeScript browser application and how to overcome them.

#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by 07BLAIZER**
#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
`This closes #4920`

### CODE REVIEW

**Comment by 07BLAIZER** [comment]
@paulodhiambo I have done the changes

**Comment by 07BLAIZER** [comment]
@paulodhiambo  any progress on the article? Its about a week and i don't see any progress.

**Review by paulodhiambo — APPROVED** [review]

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
https://github.com/section-engineering-education/engineering-education/files/7721361/Building.web.application.with.Kotlin.and.Typescript.5466.pdf

**Comment by hectorkambow** [comment]
@07BLAIZER 

image

**Comment by hectorkambow** [comment]
formatting is really off - not entirely sure as to why. 

Typically this is seen when an author copies and pastes the text.

**Comment by hectorkambow** [comment]
Will be closing this - as we can not publish as is due to the formatting.

**Comment by paulodhiambo** [comment]
Hello @hectorkambow seems it was a problem with the encoding scheme, I have fixed it.

**Comment by hectorkambow** [comment]
image


The same issues persist - I was referring to all the letters that are a different font (see image). 

That is why we closed it.

**Pull request closed without merging**
