### PR TITLE
Getting started with python plug-ins for GIMP

### LINKED ISSUE #4843: [python]Getting started with python plug-ins for GIMP
#### Proposed title of the article
Getting started with python plug-ins for GIMP
#### Proposed article introduction
GIMP is an open-source picture control program that many individuals use as a feasible option in contrast to a portion of the business contributions. GIMP handles convoluted components like layers and ways. GIMP upholds various diverse picture organizations and accompanies generally complex channels. GIMP has solid local area backing and inclusion, so it is generally simple to track down data concerning how to utilize or expand GIMP.
This article will turn out how to utilize GIMP-Python, which is an assortment of Python modules that permit you to program in Python to computerize errands in the GNU Image Manipulation Program (GIMP). These Python modules are basically coverings for the libgimp library. GIMP-Python isn't as old as Script-Fu expansions. To run scripts in Script-Fu, a module is utilized. The Python script becomes the dominant focal point in GIMP-Python and behaviors the work. You might run the GIMP-Python scripts straightforwardly from GIMP, or you can utilize GIMP's clump mode to begin it from the order line. 

#### Key takeaways 
- Enrolling your content
- Scripting the resize
- Running the resize module script
- Prearranging the picture change
- Running the refreshed module script
- Running both on a folder
#### Article quality
In this article, you will figure out how to foster Python code to computerize two unique cycles in GIMP: picture resizing and document saving. It will likewise help the student on the best way to use GIMP-python.
#### References
N/A

### PR DESCRIPTION
**Pull request by kmwangi-ken**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This fixes #4843

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Please always use the template provided by us.
I edited your initial comment and added the template. Check what matches your article.

**Comment by srishilesh** [comment]
@kmwangi-ken 

Looks like there are merge conflicts in `content/authors/kennedy-mwangi/index.md`. Could you please resolve it before the review? And, looks like you tried removing this authors info - `content/authors/kennedy-mwangi/index.md`.

**Comment by srishilesh** [comment]
@kmwangi-ken Looks like the merge conflict has not been resolved yet.

If needed, you can create a new PR.

**Comment by taves-hub** [comment]
@srishilesh I'm working on it but the conflict is not yet resolved. Let me create a new PR and ping you.

**Pull request closed without merging**
