### PR TITLE
Hapi validation bcrypt hashing and jwt

### LINKED ISSUE #2999: Hapi validation,Bcrypt Hashing and JWT in action
### Proposed title of article
Hapi validation,Bcryp Hashing and JWT in action

### Introduction paragraph (2-3 paragraphs):
Form validation is necessary before submitting form values to a server. You need to have a strict method that ensure you dont dump unnecessary values into your server. Hapi validation is a javascript module that provides just that with much ease.

Still on form validations, values like passwords need to not to be submitted as plain texts. Passwords should be hashed before they even pass the frontend on the application. This practice is solely meant to enhance the security of an application. Bcrypt is a module tha is used to hash & compare passwords in a server.

This article aims at illustrating the working logic of these two modules by building a basic authentication system with JWT and implemeting Hapi validation to validate the form inputs, bcrypt to hash and compare passwords and JWT to provide auth tokens for signing in and out of the application.

### Key takeaways: 
1. Hapi validation working login.
2. Encrypting passwords in the server side
3. Creating database Models with MongoDB  & Hapi

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### PR DESCRIPTION
**Pull request by phinaomondi**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #2999

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
There are few issues flagged in the plagiarism check. Please fix them. Thanks
[Hapi validation bcrypt hashing and jwt #3533.pdf](https://github.com/section-engineering-education/engineering-education/files/7072144/Hapi.validation.bcrypt.hashing.and.jwt.3533.pdf)

**Comment by phinaomondi** [comment]
Done.

**Review by mercymeave — APPROVED** [review]
Hello @phinaomondi 

Thank you for submitting such a resourceful article. Looking forward to more from you.

**Comment by WanjaMIKE** [comment]
@phinaomondi could you explain your code snippets. This will help the reader understand better the contents. Thanks

**Comment by phinaomondi** [comment]
> @phinaomondi could you explain your code snippets. This will help the reader understand better the contents. Thanks

Sure, let me add comments and in-depth explanations

**Comment by phinaomondi** [comment]
Hey Mike,

I have explained the code. The snippets are easy to read and besides, I have added a link to the application's code.

cc: @mercymeave

**Comment by mercymeave** [comment]
@phinaomondi,

Thank you for the corrections.

@WanjaMIKE, would you please give this PR  a final review?

**Comment by Kayere** [comment]
@ahmadmardeni1 - Could you please do a plagiarism check on this article. Thanks.

**Comment by hectorkambow** [comment]
> @ahmadmardeni1 - Could you please do a plagiarism check on this article. Thanks.

On it

**Comment by hectorkambow** [comment]
plagiarism check done. 

It would be wise to review the code snippets highlighted here 
[New Scan 10_36 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7165501/New.Scan.10_36.PM.Copyleaks.Report.pdf)

**Comment by phinaomondi** [comment]
On it

**Comment by phinaomondi** [comment]
Done @Kayere , @mercymeave , @hectorkambow

**Comment by Kayere** [comment]
Great article @phinaomondi. Please be sure to go over the changes made by your peer reviewer and I to help improve the quality of your future articles.

cc @mercymeave - Please go over the changes as well.

Overall, great work 🚀.

**Pull request merged**
