### PR TITLE
Python static typing merge conflict resolution

### LINKED ISSUE #1316: Python static typing
### Brief Summary: 
Python is a dynamically typed language. The interpreter handled types implicitly. This article demonstrates how several annotation tools can be used to specify constraint data types of objects. Typing makes the code cleaner and maintainable.

### Key Takeaways: 
1. Static typing in python
2. Function Annotations
3. Variable Annotations
4. Basics of mypy type checker

### References: 
N/A

### PR DESCRIPTION
**Pull request by jerimkaura**
### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes  #1316

### CODE REVIEW

**Comment by jerimkaura** [comment]
Fixed merge conflict on PR #1364

**Comment by hectorkambow** [comment]
Not sure what is causing a merge conflict, but please take the changes from the 1st PR - add those changes to this file and create a new PR @jerimkaura  
Thank you 👍

**Comment by jerimkaura** [comment]
Made the changes from the first PR into this.

**Comment by hectorkambow** [comment]
I do not know why this PR cannot make more commits to it. 

I know this a new PR - but I can not make any edits. 

With a new PR(pull request) - make sure it is a fresh PR - not using the old one. It seems like you deleted the old .md file and added more to it. 


@jerimkaura  

Thank you 👍

**Pull request closed without merging**
