### PR TITLE
Voice Identification using Classification Algorithms

### LINKED ISSUE #4077: voice identification using classification algorithms
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed title of article
[Machine learning] voice identification using classification algorithms 

#### Proposed article introduction
Many high-tech goods gradually invaded our daily lives during the information age, drastically altering our lifestyles. Information technologies, on the other hand, are continuing to progress towards a more human-centered approach. Biometric identification technology has gradually superseded several of the previous authentication methods that need to be investigated before people can properly manage them. Biometric identification results include face recognition technologies used in public areas, law enforcement agencies, and Siri voice mobile assistant on iPhone and Bixby Voice on Galaxy.

#### Key takeaways 

1.  Classification
2.  Feature extraction and configuration parameters
3. The proposed speech identification system

#### Article quality
The classification techniques for the problem of personality recognition by voice using machine learning approaches are discussed in this article. In the speech preprocessing procedure, we used the MFCC method. A comparative examination of five classification methods was performed to answer the problem.
#### References
machine learning

### Conclusion
In this article, a number of classification algorithms and speech preprocessing issues will be considered.
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by JOEOBY**
#### Formatting and structure checks
- [X] Have you used the correct folder and file structure?
- [X] Is your article properly formatted in Markdown? 
- [X] Have you used our preferred heading structure?
- [X] Does your article follow any of the suggested structure formats?
- [X] Is your article over 750 words? 
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic?
- [X] Can your article be understood by beginners?
- [X] Have you included a hero image that is 600x400 pixels and have the copyright to use it?

#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article?
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit.
- [X] Have you checked your article for readability?
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4077

### CODE REVIEW

**Comment by JOEOBY** [comment]
@Bayler  I have updated the changes you requested.

**Comment by Bayler** [comment]
@JOEOBY Welcome to our Eng-Ed Engineering Program. Please take note of all the commits I made in this article so that you don't repeat the same mistakes in your next article.

**Comment by hectorkambow** [comment]
@JOEOBY 
Thank you for your patience as our team has been working diligently to work through the recent increased volume of articles coming in. 

We are going through are ready articles in the order they were received and working on improving our review time as well. 

🚀

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
@JOEOBY 

Not sure if there has some files that have not been pushed? 

I tried to check it out and it showed 8 files to push and 9 to pull via my vscode. ?? 

Not sure how or why? 

I tried to check out another PR and had not such issue. 

cc @Bayler any idea?

**Comment by Bayler** [comment]
> @JOEOBY
> 
> Not sure if there has some files that have not been pushed?
> 
> I tried to check it out and it showed 8 files to push and 9 to pull via my vscode. ??
> 
> Not sure how or why?
> 
> I tried to check out another PR and had not such issue.
> 
> cc @Bayler any idea?

@hectorkambow everything seems okay from my end. Please check to confirm whether you've pushed all files @JOEOBY

**Comment by JOEOBY** [comment]
@hectorkambow  i have rechecked and all files are in line from my side.
Thank you.
cc @Bayler

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
@section-engineering-education/content-moderator-team Can someone try to preview this when the they have a chance? 

I could not get it to render?

**Comment by hectorkambow** [comment]
@Bayler 

I didn't see a plagiarism check on this PR - please lets be sure we are always performing a plagiarism check. I did the whole final review fixed more thing before I realized. Not a good use of our time to be doing reviews on PR that will be closed.

@JOEOBY 

On that note - many sentences and paragraphs seem to be paraphrased from other sources. 

We only accept unique and original content to be published.

[Voice Identification using Classification Algorithms #4629.pdf](https://github.com/section-engineering-education/engineering-education/files/7577319/Voice.Identification.using.Classification.Algorithms.4629.pdf)

**Pull request closed without merging**
