### PR TITLE
[Duplicate of #4989] - Using logistic regression in pytorch to identify handwritten digits

### LINKED ISSUE #4591: [Languages] Using Logistic Regression in PyTorch to Identify Handwritten Digits
#### Proposed title of article
Using Logistic Regression in PyTorch to identify handwritten digits
#### Proposed article introduction
When there are several explanatory variables, logistic regression is used to calculate the odds ratio. With the exception that the response variable is binomial, the approach is quite similar to multiple linear regression. The impact of each variable on the odds ratio of the observed event of interest is the end outcome.
The statistical method of logistic regression allows us to predict a binary outcome given a set of independent factors. Now we'll look at how to do this in PyTorch, as well as how to use Logistic Regression in PyTorch to identify handwritten digits from the MNIST dataset.
#### Key takeaways 
- Knowing The Dataset
- Build The Neural Network
-  Adjusting Weights
- Core Training Process
#### References
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by masese911**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4591

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by masese911** [comment]
Duplicate of #4989

**Comment by masese911** [comment]
@lalith1403

**Comment by srishilesh** [comment]
@section-engineering-education/peer-reviewers 

Is anyone available to review this PR?

**Comment by srishilesh** [comment]
Hey @lalith1403 ,

Looks like we have the review pending for a while. If you're occupied with some other work, shall I take this one?

**Comment by lalith1403** [comment]
Hello @srishilesh,

I will be completing it by tomorrow EOD. Thank you.

**Review by lalith1403 — APPROVED** [review]

**Comment by masese911** [comment]
This is duplicate of 4989. Can someone please give it a final review
@Kayere @louisefindlay23 @LinusMuema @ahmadmardeni1

**Comment by masese911** [comment]
This is duplicate of 4989. Can someone please give it a final review
@Kayere @louisefindlay23 @LinusMuema @ahmadmardeni1 @hectorkambow

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
