### PR TITLE
How to perform containerized static application security testing(SAST) using MobSF within a Docker container

### LINKED ISSUE #6058: [Security] How to perform containerized static application security testing(SAST) using MobSF within a Docker container
#### Proposed title of article
Static application security testing(SAST) using MobSF in a Docker container

#### Proposed article introduction
This article will introduce a reader to application vulnerability testing, outlining the various ways of performing the same. This article will try to make a brief comparison between the static testing method and dynamic method and any other methods in existence.

The article will further focus on the static secutity testing method outlining step by step process of how it works and analyze the results obtained from SAST together with its advantages. This article will use MobSF framework from within a docker container to perform the step by step process of SAST. 

#### Key takeaways 
The reader should master:
1. What is SAST
2. Differences between SAST and DAST
3. Tools used in application security testing
4. Step by Step process of how SAST works
5. Advantages and Disadvantages SAST

#### Article quality
This article will not only cover a detailed process of application security testing but also give the various tools used apart from the tool of focus, and also explain what security testing entails in theory.

#### References
N/A

### PR DESCRIPTION
**Pull request by RuthAMare**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6058

### CODE REVIEW

**Comment by lalith1403** [comment]
PFA the plagiarism report. It is higher than what we accept. Please make the changes accordingly. Thank you.
[How to perform containerized static application security testing(SAST) using MobSF within a Docker container #6266.pdf](https://github.com/section-engineering-education/engineering-education/files/7963683/How.to.perform.containerized.static.application.security.testing.SAST.using.MobSF.within.a.Docker.container.6266.pdf)

**Review by mercymeave — COMMENTED** [review]
@RuthAMare 

Hey, I am glad to be reviewing your article? Congratulations on such a great article.

Would you please address the changes highlighted and shorten the folder URL. It is too long.

**Comment by RuthAMare** [comment]
@mercymeave, changes have been taken note of and committed appropriately.

**Comment by RuthAMare** [comment]
Renaming the folder would delete the entire branch and its content, meaning we have to open a new PR.

**Review by mercymeave — COMMENTED** [review]
@RuthAMare 

Hello Please shorten the URL. It is too long.

**Comment by mercymeave** [comment]
Now you will have to upload the images into the folder `security-testing-using-mobsf-in-docker` then delete the previous folder.

Ping me if you have any difficulties.

**Comment by RuthAMare** [comment]
@mercymeave all appropriate changes made.

**Review by mercymeave — COMMENTED** [review]
Hello @RuthAMare 

I seem to find a lot of similarities and verbatim between your article and [this one](https://www.synopsys.com/glossary/what-is-sast.html). 

Please consider working on your piece to ensure originality and legibility.

**Comment by mercymeave** [comment]
In order to keep our backlog to a minimum, we will be closing this PR, as all edits should be completed on author's forked repo not in the queue.

**Pull request closed without merging**
