### PR TITLE
Leveraging BodyPix for Body Segmentation using Python

### LINKED ISSUE #6669: [Machine Learning] Leveraging BodyPix for Body Segmentation using Python and OpenCV
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Leveraging BodyPix for Body Segmentation using Python and OpenCV

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

BodyPix is a body segmentation model that is built on TensorFlow. The model leverages a pre-trained neural network to segment human bodies from frames. Beside segmenting your body, this tutorial will leverage this model to change your background using your webcam and OpenCV. 

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader should be able to:
- Learn about the BodyPix model.
- Learn how to install the model onto our notebook.
- Learn how you can segment your body.
- Learn how to remove and change the background. 

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

Not only will I show the readers how to perform the segmentation using one person but also how one can use it on multiple people in an input image or video.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

- [BodyPix](https://github.com/tensorflow/tfjs-models/tree/master/body-pix)

### PR DESCRIPTION
**Pull request by splashtonia**
This closes #6669

## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Comment by WanjaMIKE** [comment]
This PR fails to render. This may arise if the repo was not forked correctly. Please ensure that its correctly configured. @splashtonia

**Comment by splashtonia** [comment]
> This PR fails to render. This may arise if the repo was not forked correctly. Please ensure that its correctly configured. @splashtonia

@WanjaMIKE Could there be another reason why that is happening? I've published a couple of PRs before with the same repo

**Comment by hectorkambow** [comment]
@splashtonia have you done a git pull since those last articles were published (on your forked repo)? 

We have updated the repo a few times in the recent weeks.

**Comment by splashtonia** [comment]
> @splashtonia have you done a git pull since those last articles were published (on your forked repo)?
> 
> We have updated the repo a few times in the recent weeks.

@WanjaMIKE Can you try now? I just did a git pull

cc: @hectorkambow

**Comment by hectorkambow** [comment]
@splashtonia I believe the git pull should be done before the PR is submitted (this PR would still have the older repo info). 🤔 

(I think)

cc @WanjaMIKE

**Pull request closed without merging**
