### PR TITLE
Getting started with Python plug-ins for GIMP

### LINKED ISSUE #4843: [python]Getting started with python plug-ins for GIMP
#### Proposed title of the article
Getting started with python plug-ins for GIMP
#### Proposed article introduction
GIMP is an open-source picture control program that many individuals use as a feasible option in contrast to a portion of the business contributions. GIMP handles convoluted components like layers and ways. GIMP upholds various diverse picture organizations and accompanies generally complex channels. GIMP has solid local area backing and inclusion, so it is generally simple to track down data concerning how to utilize or expand GIMP.
This article will turn out how to utilize GIMP-Python, which is an assortment of Python modules that permit you to program in Python to computerize errands in the GNU Image Manipulation Program (GIMP). These Python modules are basically coverings for the libgimp library. GIMP-Python isn't as old as Script-Fu expansions. To run scripts in Script-Fu, a module is utilized. The Python script becomes the dominant focal point in GIMP-Python and behaviors the work. You might run the GIMP-Python scripts straightforwardly from GIMP, or you can utilize GIMP's clump mode to begin it from the order line. 

#### Key takeaways 
- Enrolling your content
- Scripting the resize
- Running the resize module script
- Prearranging the picture change
- Running the refreshed module script
- Running both on a folder
#### Article quality
In this article, you will figure out how to foster Python code to computerize two unique cycles in GIMP: picture resizing and document saving. It will likewise help the student on the best way to use GIMP-python.
#### References
N/A

### PR DESCRIPTION
**Pull request by kmwangi-ken**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #4843`

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your article for publishing.
With the recent increase in article volume out team has been working diligently to review every article. Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by kmwangi-ken** [comment]
@mercymeave Hello I have done as you requested. You may have a look at it and give guidance where needed. Thank you

**Comment by srishilesh** [comment]
@kmwangi-ken 

I remember getting started with the preliminary revision on your very first PR (#5083) of this article. Somehow, it got transferred to another peer-reviewer. :laughing:

Not a problem now. From the next time, make sure to ping the first reviewer who reviewed your article. This is just to avoid duplicate suggestions, and reduce delay in publishing. Moreover, tracking suggestions becomes easier if one peer-reviewer reviews them through the end.

Since @mercymeave got started with some major suggestions, let her continue. Assigning this PR to her.

Thanks.

**Review by mercymeave — CHANGES_REQUESTED** [review]
Hello @kmwangi-ken 

Your article still have a lot of readability issues and code mistakes.This is the fourth time this PR is being worked on. If you need more to time to work on it then let us know.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. Not a problem but it seems that this PR is still quite a bit aways from being completed. 
 
In an effort to be fair to our larger EngEd community as a rule of thumb - we can only accept content (pull requests) that are complete and fully polished articles/tutorial - meaning they are ready to be published. 
 
All revisions and edits **should be completed on your own forked repo** (as to not take up room in the queue) - this allows all revisions to be done on your forked personal repo. 
 
We will be closing this PR.
 
Our Peer Reviewer and Content Moderator teams do NOT provide any revisions services. All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

**Pull request closed without merging**
