### PR TITLE
A Look at RAID and Erasure Coding 

### LINKED ISSUE #7227: [Security] Data Recovery: RAID and Erasure Coding
### Topic Suggestion
Security 

### Writing sample(s): 
[How to add pure CSS waves to your website](https://www.section.io/engineering-education/pure-css-wave-animations-website/)
#### Proposed title of article
Data Recovery: RAID and Reed Solomon Erasure Coding

#### Proposed article introduction
Organization require large amounts of storage alternatives to store their data and information. When the storage needs in your organization start soaring up the roof, alternatives such as moving information to the cloud or fitting dedicated storage servers become viable options. Large storage alternatives like dedicated storage server use a range of data recovery alternatives to ensure that all data stored in their systems can be recovered in case of failures. Alternatives such as RAID implementation, and its competitor Erasure Coding are just but a few of the popular methods used to recover data. 
#### Key takeaways 
This article seeks to educate the reader on:
- A look at the different types of raid methods and finding out which will suite your data recovery needs.
- A discussion on the different erasure coding schemes and finding out which is best in various cases.
- Determining which method suits your hardware type(SSD and HDD), architecture(cloud and hyper converged distributed storage.), performance needs and available storage. 

#### Article quality
This article takes an in-depth approach to discussing the topic of data recovery. The article only focuses on data recovery and how one can use the information compiled in the article to select the best approach between erasure coding and RAID. The article cover additional topics such as identifying the types of technologies beneath RAID and Erasure coding. This is different from other blog articles that mostly focus on defining the two methods and listing out a few differences between the two methods.

#### References
N.A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by lin-chez**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #7227

### CODE REVIEW

**Comment by lin-chez** [comment]
@ahmadmardeni1 and @hectorkambow @LinusMuema @louisefindlay23 .This pr has not received a reviewer yet its peers have. kindly assign a reviewer for this.

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Comment by lin-chez** [comment]
@lalith1403 kindly  are there any issues that are impeding your progress with the review?

**Comment by lalith1403** [comment]
Hey @lin-chez, can you add you author folder name in place of the author placeholder?

**Comment by lin-chez** [comment]
Hello, @lalith1403 kindly state if there are any issues with my PR that are hindering your review process.

**Comment by hectorkambow** [comment]
@lalith1403 is this PR ready for a final review?

**Comment by WanjaMIKE** [comment]
Hey @lin-chez @lalith1403 was held up for a little while. Will be continuing with the review. Thanks

**Comment by lin-chez** [comment]
@WanjaMIKE 
Thank you for the wonderful communication. Looking forward to working with you.

**Pull request merged**
