### PR TITLE
How to Create a Web Component with Vanilla JavaScript

### LINKED ISSUE #3140: How to Create a Web Component with Vanilla JS
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to Create a Web Component with Vanilla JavaScript

### Introduction paragraph (2-3 paragraphs):
Web components are reusable and encapsulated HTML elements created using JavaScript. They let us create functionality that can be reused on other applications that we built with different technologies.

Web Components work in any web standard environment that supports basic HTML, CSS, and JavaScript. This article is a step-by-step guide on how to create a Web Component using Vanilla JavaScript.

### Key takeaways: 
1. What is a web component?
2. How do web components work?
3. Building a web component

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by LeahKui**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #3140.

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Hi, @LeahKui. Congratulations on submitting your first article. 

In the future, please remember to link your topic suggestion to your PR by following the instructions in **Topic Suggestion This Closes** so we can easily payout your article.

**Comment by hectorkambow** [comment]
[How to Create a Web Component with Vanilla JavaScript #3592.pdf](https://github.com/section-engineering-education/engineering-education/files/7080301/How.to.Create.a.Web.Component.with.Vanilla.JavaScript.3592.pdf)


👋 Good afternoon - and welcome to the EngEd program.
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

@LeahKui

**Comment by LeahKui** [comment]
Update on the index.md

**Review by mercymeave — APPROVED** [review]
Proceeding to tech review

**Review by mercymeave — APPROVED** [review]
@hectorkambow, @ahmadmardeni1 @WanjaMIKE  would you please run a final plagiarism check on this PR before the final review?

**Comment by ahmadmardeni1** [comment]
plagiarism check done ✅

**Comment by LinusMuema** [comment]
Hi @LeahKui 
Again, thanks for joining the eng-ed community and we are excited to have you on board. Thanks for the amazing article and we look forward to getting more amazing content from you. The article didn't even need much changing.

awesome job @mercymeave

**Pull request merged**
