### PR TITLE
How to Write a Rust GraphQL Server With MongoDB, Juniper and Actix Web (#6265 duplicate)

### LINKED ISSUE #5600: How to  Write a Rust GraphQL Server With MongoDB, Juniper and Actix Web
#### Proposed title of article

How to Write a Rust GraphQL Server With MongoDB, Juniper, and Actix Web

#### Proposed article introduction

GraphQL is an open-source query language. It is intuitive and well-designed for building APIs. GraphQL is built around HTTP to set how you get and receive resources from a server. It gives you a single endpoint that allows you to determine what data you get back based on the query that you send to that endpoint. This gives you a more flexible way to interact with your server as compared with a REST API. A REST API is based on executing different endpoints to get specific data. This will also return extra information that you don't want at the moment. However, with GraphQL API, you only get data that is specified in a GraphQL query. This way, you only make a single request to the server that queries different resources and return the data you need. Instead of sending different endpoints to different resources to return the same data.

This guide aims to create a fully-functional GraphQL server using the Rust programming language.

#### Key takeaways 

- What is a GraphQL API
- Set up a MongoDB database
- Configure a GraphQL server using Rust
- What is the Actix-Web framework
- What is the Juniper framework
- Configure a Rust GraphQL server using Juniper and Actix-Web frameworks

#### Article quality

This guide aims to introduce the Rust programmer to the concept of GraphQL. We will explain this concept and how it works. The build and application stack that has GraphQL, Rust, and MongoDB. The reader will also understand the frameworks and libraries we will use to achieve this.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Catemacharia**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #5600

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Review by jerimkaura — COMMENTED** [review]
Great article @Catemacharia 

Proceeding to tech review.

**Review by jerimkaura — APPROVED** [review]
Great article Cate. I loved how you factored in the changes I requested in the previous PR. 

However, use more involving pronouns like more. Instead of 'you' and 'your' use 'we' and 'our' as suggested by Grammarly.

Moving this to the final review.


Thanks.

**Comment by Catemacharia** [comment]
Hey @jerimkaura, Could you have forgotten to add a `final review` label?

**Comment by WanjaMIKE** [comment]
Merged #6612 into master

**Pull request merged**
