### PR TITLE
Learn how to create pdf file in C# using ironPDF

### LINKED ISSUE #5388: [Languages] Learn How To Create PDF File In C# Using IronPdf
#### Proposed title of the article
Learn How To Create PDF File In C# Using IronPdf

#### Proposed article introduction
Programming designers should realize how to make a pdf record progressively through C# code, as this is viewed as a need in practically all undertakings in this day and age. You might go over different issues where you want to make a Pdf record, for example, creating a report from client input, saving client text as pdf, separating HTML content and changing over it into pdf, and so on
You may be feeling that it would be a perplexing undertaking. In any case, because of IronPdf, It's just about as simple as ascertaining `2+3`.
You can make a pdf document from C# with only 2 lines of code.
I will prepare a step-by-step demo for learners, to show how we can create pdf document using C#.

#### Key takeaways 
- By the end of this exercise learners will be able to :
   1. Create and Configure Visual Studio Project
   2. install Nugent Package for Iron PDF 
   3. Design a window form
   4. Add the Back End Code for Save Button
   5. Add the Back End Code for Clear and Close Button
#### Article quality
For sure this tutorial will be easy,well-formatted, and in context. Furthermore, it will provide proof of all steps images and all source codes will be on point and easy to understand even for the novices.

#### References
n/a

### PR DESCRIPTION
**Pull request by fabulousDesigns**
#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #5388

### CODE REVIEW

**Comment by fabulousDesigns** [comment]
@hectorkambow hello, here is the PR. Thanks

**Comment by hectorkambow** [comment]
@section-engineering-education/content-moderator-team lets keep an eye on this PR and provide @Jeff-mwangi with any guidance he may need as he performs this test review.

Thank you

**Comment by fabulousDesigns** [comment]
@Dawe-7 Hello, could you kindly review this article, thanks.

**Comment by hectorkambow** [comment]
@section-engineering-education/peer-reviewers Anyone available to jump on this review.

**Review by Dawe-7 — APPROVED** [review]
Nice article @fabulousDesigns, kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles. Thank you.

This article will be marked `ready for final review` once we have completed the plagiarism check.

**Comment by hectorkambow** [comment]
[Learn how to create pdf file in C# using ironPDF #5522.pdf](https://github.com/section-engineering-education/engineering-education/files/7781341/Learn.how.to.create.pdf.file.in.C.using.ironPDF.5522.pdf)


@fabulousDesigns 

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.

We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or via many other blog sites.

**Pull request closed without merging**
