### PR TITLE
[Duplicate] How to deploy machine learning model as an app in Python using Gradio

### LINKED ISSUE #4190: [Machine learning] How to deploy machine learning model as an app in Python using Gradio
#### Proposed title of article
[Machine learning]How to deploy machine learning model as an app in Python using Gradio.

#### Proposed article introduction
Gradio is an open-source python library that permits you to rapidly make simple to utilize, adjustable UI parts for your ML model and any API.  Gradio also provides customizable components like buttons, textboxes, check boxes, file dialogs which make it easier to make beautiful user interfaces.

Gradio can be embedded in Python notebooks or presented as a webpage and doesn't require a separate python script.. A Gradio interface can automatically generate a public link you can share with colleagues that lets them interact with the model on your computer remotely from their own devices also once you've created an interface, you can point Gradio towards the GitHub repository where it is contained. Gradio will host the interface on its servers and provide you with a link you can share. This has made Gradio be a great and popular tool for machine learning.

Gradio is more useful in the following ways:
- Creating demos of your machine learning code for clients/collaborators/users
- Getting feedback on model performance from users
- Debugging your model interactively during development

In this tutorial, we will build a machine learning model from scratch and then deploy the model as an app using Gradio by creating a user interface for the model.

#### Key takeaways 
1. What is Gradio.
2. How to install Gradio.
3. Building a custom machine learning model.
4. Working with Gradio user interface.
5. Deploying the machine learning model as app using Gradio.

#### Article quality
This article undergoes all the stages of machine learning. We start we preprocessing our dataset, after cleaning the data we will build and train the model and we get the best prediction.
From there we introduce Gradio, we start with basics before we go deeper and implement the model user interface.

Using this custom model, a person can be able to follow from the start and be able to deploy an machine learning model using Gradio.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by kelvinkimani501**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4190

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by kelvinkimani501** [comment]
Hello @M0nicah and @ahmadmardeni1, I have made the requested changes and opened another PR. I have gone through the entire article and improved the article flow.
Kindly Review.

**Comment by kelvinkimani501** [comment]
Duplicate of #5028

**Review by M0nicah — APPROVED** [review]
🚀 awesome article @kelvinkimani501, please ensure you go through the changes I made in the commits to help improve flow and format for your future articles. Thanks.

**Comment by WanjaMIKE** [comment]
Merged #5369 into master

**Pull request merged**
