### PR TITLE
Extracting Colors from Images using Palette API in Android

### LINKED ISSUE #3130: Extracting Colors from Images using Palette API in Android
### Introduction paragraph (2-3 paragraphs):
The palette library is a support library that extracts prominent colors from images to help you create visually engaging apps. 
You can use the palette library to design layout themes and apply custom colors to visual elements in your app. For example, you can use a palette to create a color-coordinated title card for a song based on its album cover or to adjust an app’s toolbar color when its background image changes.The Palette object gives you access to the colors in a Bitmap image while also providing six main color profiles from the bitmap to help inform your design choices. In this tutorial we will extract colors from an image and display them. 

### Key takeaways: 
- What is Palette API
-  How Does it Work
- Set up the library
- Extract color profiles

### References: 
https://developer.android.com/

### PR DESCRIPTION
**Pull request by robert-muriithi**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3130

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
@Ericgacoki could you fix the minor issues highlighted in the plagiarism check
[Extracting Colors from Images using Palette API in Android #3513.pdf](https://github.com/section-engineering-education/engineering-education/files/7072285/Extracting.Colors.from.Images.using.Palette.API.in.Android.3513.pdf)

**Comment by Ericgacoki** [comment]
@robert-muriithi, please check out [my changes](https://github.com/section-engineering-education/engineering-education/pull/3513/commits/7817ac9d7e83f7b5c6f9d403ae377bec50d2cbb6) to improve your future articles.

**Comment by robert-muriithi** [comment]
Thanks. Let me check

**Comment by LinusMuema** [comment]
Hi @robert-muriithi 
Great job on the article. Thank you for joining section and we look forward to seeing more amazing content from you.

cc: @Ericgacoki

**Pull request merged**
