### PR TITLE
Implementation of linear quadratic regulator (lqr) control for the inverted pendulum on a cart using Matlab

### LINKED ISSUE #4541: Implementation of Linear Quadratic Regulator (LQR) Control for the Inverted Pendulum on a Cart
#### Introduction
The Linear Quadratic Regulator (LQR) controller is a well-known method that provides optimally controlled feedback gains to enable the closed-loop stable and high-performance design of systems. The LQR algorithm reduces the amount of work done by the control systems engineer to optimize the controller. However, the engineer still needs to specify the cost function parameters, and compare the results with the specified design goals. It is essentially an automated way of finding an appropriate state-feedback controller.
In this tutorial, we will see how to implement the LQR in Matlab. Here we design an optimal full-state feedback controller for the inverted pendulum on a cart example using the linear quadratic regulator (LQR).  Full-state feedback  is a feedback which gives a clear relationship between controller parameters and controller behaviour. In Matlab, we find that this is a simple one-line command `lqr`.

#### Key takeaways 
- Basic understanding of linear quadratic regulator.
- Application of a linear quadratic regulator.
- Matlab code to implement LQR.
#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by atienodorine3**
This closes #4541

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Plagiarism check done. Please take a moment to correct the highlighted issues. Thanks
[New Scan 5_25 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7506808/New.Scan.5_25.PM.Copyleaks.Report.pdf)

**Comment by M0nicah** [comment]
hi @atienodorine3, I have gone through the article and would like to ask you to please add more expalanations. Make everything simple, use simple words, add more explanation your code so even a beginner reader would follow along easily and would also understand what is going on.

Note: Do not assume the reader knows everything.

Ping me when you are done. :rocket: :+1:

**Comment by atienodorine3** [comment]
@M0nicah have a look at the changes I have made.

**Comment by hectorkambow** [comment]
@M0nicah  

If any more changes are needed please close the PR to allow the author the proper time to make any required edits.

**Comment by hectorkambow** [comment]
@atienodorine3 

I've also pinged our peer reviewer via slack.

**Comment by hectorkambow** [comment]
@atienodorine3 

We wanted to thank you for your patience as our team has been working diligently to work through the **recent increased volume of articles coming in.**

We are going through are ready articles in the order they were received and working on improving our review time as well.


cc: @section-engineering-education/content-moderator-team

**Review by M0nicah — APPROVED** [review]
great article @atienodorine3

**Comment by Kayere** [comment]
Hello @atienodorine3 - could you please find an alternative way to write your mathematical expressions. The current way does not render properly on the website. 

See the picture attached.

Screenshot 2021-12-02 105108

**Comment by atienodorine3** [comment]
@Kayere I think adding the ajax script can work maybe you can have a look.

**Comment by atienodorine3** [comment]
@Kayere I looked at the previous article and I see by adding the ajax script the equations are properly displayed... I have added the ajax script

**Comment by hectorkambow** [comment]
@atienodorine3 That is correct adding the script will render the equations 

cc @Kayere

**Comment by hectorkambow** [comment]
@M0nicah  @Kayere 

Any thing else needed for this PR - we'd like to get it cleared out of the queue asap - this PR has been opened for a while.

**Comment by Kayere** [comment]
Great article @atienodorine3.

**Pull request merged**
