### PR TITLE
Introduction to Vite.js 2.0

### PR DESCRIPTION
**Pull request by Danmasanii**
Created introduction to vite.js 2.0 article.
The article is about the advantages, reasons to choose vite and, how to install Vite.js 2.0 using npm and yarn.
I also included hero.jpg as the vite.js logo.

### CODE REVIEW

**Comment by zolomohan** [comment]
Hi @Danmasanii. Please go over how to set up CSS pre-processors as mentioned in the Why Vite.js section.

**Comment by zolomohan** [comment]
Please add a bio and a profile pic to the `content/author` folder in your branch. Take a look at how the other authors created their bio folders and follow the structure.

**Comment by Danmasanii** [comment]
Hi, @zolomohan changes have been committed. Thank you

**Review by zolomohan — APPROVED** [review]

**Comment by hectorkambow** [comment]
plagiarism check done

**Review by louisefindlay23 — CHANGES_REQUESTED** [review]
Hi, @Danmasanii. I've conducted the final review of your article and unfortunately we are rejecting your PR in its current state. We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the Vite.js documentation.

We suggest you rework your article to provide more original content and provide more value to readers such as building a simple web app using Vite.js and providing a tutorial.

It would also be beneficial to clarify and expand your introduction to Vite.js and its advantages over other front-end frameworks to provide more depth and make it more beginner-friendly.

Areas to Improve:
- Clarify whether Vite.js is a framework, build-tool or both? Are these phrases interchangable? Ideally your article should be accessible to developers who haven't used build-tools or modern front-end frameworks before.
- Ensure the advantages of Vite.js are unique from other front-end frameworks that you're comparing it to.
- You should inform readers what template scaffolding is and why they should use it over vanilla Vite.js or just the front-end framework itself, especially since the article is about why Vite.js is better than other front-end frameworks. If it's better, then why should they use them with template scaffolding?

I look forward to receiving your reworked PR and reviewing your improved article,
Louise - Content Moderator

**Comment by zolomohan** [comment]
Hi @Danmasanii. I'm closing this PR to clear up the queue for now. Please re-open this PR once you've reworked the article.

**Comment by Danmasanii** [comment]
Alright. Thanks for the hint.

**Pull request closed without merging**
