### PR TITLE
How to Build a Background Generator with JavaScript

### LINKED ISSUE #1961: How to Build a Background Generator with JavaScript
### Proposed title of the article
How to Build a Background Generator with JavaScript

### Introduction paragraph (2-3 paragraphs):
JavaScript is a programming language that allows you to program complex features on web pages. 

### Key takeaways: 
By the end of this tutorial, the reader will:

- Learn JavaScript Basics.
- Develop a Background generator with Javascript.

### Templates to use as guides
- [https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics)

### PR DESCRIPTION
**Pull request by Olanetsoft**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [ ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

Fixes #1961

### CODE REVIEW

**Comment by zolomohan** [comment]
@cyberShaw if you haven't started the review, may I review this article?

**Comment by cyberShaw** [comment]
> @cyberShaw if you haven't started the review, may I review this article?

Go ahead, @zolomohan!
I was a little busy, missed this notification 😅

**Comment by zolomohan** [comment]
Thanks, @cyberShaw. Will review it by EOD tomorrow :)

**Comment by Olanetsoft** [comment]
@zolomohan Any update on the review 😊

**Comment by zolomohan** [comment]
Waiting for the plagiarism check :)
Will complete my side of review on this weekend.

**Comment by hectorkambow** [comment]
[How to Build a Background Generator with JavaScript #2093.pdf](https://github.com/section-engineering-education/engineering-education/files/6406440/How.to.Build.a.Background.Generator.with.JavaScript.2093.pdf)


@Olanetsoft 

There appear to be many sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/.

cc @zolomohan

**Comment by Olanetsoft** [comment]
I will update as requested. @hectorkambow

**Comment by Olanetsoft** [comment]
@hectorkambow Changes updated

cc: @zolomohan

**Comment by zolomohan** [comment]
@hectorkambow could you run the plagiarism check again, please?

**Comment by hectorkambow** [comment]
[How to Build a Background Generator with JavaScript #2093.pdf](https://github.com/section-engineering-education/engineering-education/files/6416208/How.to.Build.a.Background.Generator.with.JavaScript.2093.pdf)

@Olanetsoft 
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

**Comment by Olanetsoft** [comment]
@hectorkambow  You just resent the old report which I have updated earlier before @zolomohan requested the second plagiarism check.

Kindly find the below report from Grammarly Premium Account indicating no plagiarism and issues.

image

Awaiting your response, Thank you 😊

**Review by zolomohan — CHANGES_REQUESTED** [review]
Hey Idris.
Upon reviewing your article, it seems like we should add more to provide more value to the reader.
We’re really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or via many other blog sites.

**Comment by zolomohan** [comment]
For now, we will be closing the PR to make room in the queue. You can reopen the PR once you’ve enhanced it with much more quality/original/unique content.

**Pull request closed without merging**
