### PR TITLE
Creating Fruit Mania Game Using Javascript

### LINKED ISSUE #4387: [Languages] Fruit mania game in javaScript : javascript for game Development
#### Proposed title of the article
[Languages] Fruit mania game in javaScript : JavaScript for game Development
#### Proposed article introduction
It is my intention to create a fruit madness game entirely in JavaScript, HTML, and CSS throughout this tutorial. It will be a one-of-a-kind demonstration of how to drag and drop components in Javascript, making it really unique. The fact is that this is one of the most often used components in many javaScript applications. In addition to this, we will learn about and practice the built-in javaScript methods that will be useful in achieving the desired result for our project.

#### Key takeaways 
**By the end of this instructional exercise learners will get the following** 
  - Attaching EventListeners to elements using `addEventListener()` method.
  - using `setAttribute()` method.
  - Timers with `setInterval()` method
  - Node navigation: `createElement()`,`appendChild`.
  - Fruit maina game
#### Article quality
Creating a basic game in Javascript is the goal of this essay, which is designed to educate learners of more of what they already know about Javascript and assist them in honing their abilities. The description of the code will be precise in order to increase the understandability of learners in the community.
#### References
N/A

### PR DESCRIPTION
**Pull request by EssyG10**
#### Pre-submission checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #4387

### CODE REVIEW

**Review by M0nicah — CHANGES_REQUESTED** [review]
Hello @EssyG10, your article required a lot of formatting changes. Please go through them to improve the quality of your future articles.

Also, you have explained more about the functions that would be used to create the game but you have not explained how the game is created. You have just given the code. It feels like you have not achieved the objective of the article.

Please explain the code that you have provided. Make it easier for the reader to understand how the game is created. Information about the functions can be found in official documentation and is not really helpful in the article.

Ping me when you are done.

**Comment by EssyG10** [comment]
@M0nicah, the changes requested have been implemented.

**Comment by M0nicah** [comment]
@EssyG10 - Please add a hero image and the article will be ready for final review. Thanks.

**Comment by EssyG10** [comment]
@M0nicah, hello there I did add a hero image, and kindly don't forget the `tech tutorial 😉 label thanks

**Comment by hectorkambow** [comment]
@EssyG10 
Thank you for your patience as our team has been working diligently to work through the recent increased volume of articles coming in. 

We are going through are ready articles in the order they were received and working on improving our review time as well. 

🚀

**Comment by LinusMuema** [comment]
Hi @EssyG10 

I can't check out into your branch because the repository has been deleted. If this isn't an issue, this PR can be closed to clear the queue.

cc: @hectorkambow & @M0nicah

**Comment by EssyG10** [comment]
@LinusMuema hi, should I create another branch

**Comment by LinusMuema** [comment]
Yes....please do

**Pull request closed without merging**
