### PR TITLE
A dive into python strings

### LINKED ISSUE #2406: A dive into python strings
### Proposed title of article
A dive into python strings

### Introduction paragraph (2-3 paragraphs):
The string data type is a crucial data type for every programmer. In python, strings are arrays of characters. Python provides a variety of operations that a programmer can perform with strings.

At the end of this tutorial, the reader should be able to have a complete understanding of string operations in python. The tutorial will guide the reader to write programs that incorporate strings in python. Among the operations include extracting string portions, modifying and manipulating string data.

### Key takeaways: 
1. Introduction to strings in python
2. Manipulating strings
3. Major string operations in python.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by diannesandra**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
This fixes #2406

### CODE REVIEW

**Comment by hectorkambow** [comment]
@diannesandra 

Good afternoon and thank you for submitting your article for publishing(and welcome to the EngEd program). Im Hector - one of the content moderators that may be doing your Final review on the article before it is published.

You article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀

Also FYI - I see you have made a few commits after creating the PR - please only create a PR when the article is fully polished and ready to be reviewed.

Otherwise you can make all those changes and commits on your forked repo 👍

Just an FYI to avoid potential closure of future articles. Thank you.

**Comment by WanjaMIKE** [comment]
@diannesandra You forgot to add an introduction section. Could you please do that. Thanks

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by diannesandra** [comment]
@WanjaMIKE, The introduction part was available before your commit, kindly check.

**Comment by WanjaMIKE** [comment]
Could you replace `python` with `Python` everywhere except on the code snippets.

**Comment by diannesandra** [comment]
> Could you replace `python` with `Python` everywhere except on the code snippets.

@WanjaMIKE Done! Check it out.

**Comment by hectorkambow** [comment]
Overall great work @diannesandra 

cc @WanjaMIKE  

Some very minor changes made on my end - please review to see what can be implemented into future articles.

**Pull request merged**
