### PR TITLE
How to configure a Relational Database Server on AWS #2662

### LINKED ISSUE #2662: How to configure a Relational Database Server on AWS
### Proposed title of the article
How to configure a Relational Database Server on AWS

### Introduction paragraph:
There are numerous reasons why you should set up the database for your next project on AWS. AWS includes a slew of features for scaling and securing your databases. Finding your way around AWS configuration settings can be difficult. The docs may not always be able to point you in the right direction. 

In this post, we will go over how to set up an RDS on AWS. We will use a flask application to connect to the RDS.

### Prerequisites 
AWS account 
Python 
Flask
Flask-MySQL

### Key takeaways:
Setting up and scaling relational databases in the cloud
Configuring a database on AWS
Setting up an application with Flask
Integrating a Relational Database with Flask 

### References:
https://flask.palletsprojects.com/en/2.0.x
https://amzn.to/3zyRDBr

### PR DESCRIPTION
**Pull request by Bamimore-Tomi**
### Article checklist
This fixes #2662
**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by hectorkambow** [comment]
@Bamimore-Tomi 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀

Thank you.

**Comment by ninjaginja** [comment]
plagiarism check completed - all good
[2120420-845f9c8f7e5feb83dd5f-1626806921679.pdf](https://github.com/section-engineering-education/engineering-education/files/6850575/2120420-845f9c8f7e5feb83dd5f-1626806921679.pdf)

**Comment by Bamimore-Tomi** [comment]
Hi @WanjaMIKE 

Seems like nothing is happening on my PR.
@hectorkambow

**Comment by WanjaMIKE** [comment]
I am working on the PR. Don't worry. Thanks

**Comment by hectorkambow** [comment]
@Bamimore-Tomi Thank you for your understanding while our Peer reviewer team works diligently to go through our EngEd articles.

**Comment by WanjaMIKE** [comment]
@Bamimore-Tomi your PR has over `70` images and not all are included in the article. Please check and delete `irrelevant` ones. You also need to add a `hero image`.

You should use the full link to sight an image. Kinda like this:

```
![O-1-graph](/engineering-education/how-to-configure-a-relational-database-server-on-aws/o-1.png)
```

**Comment by Bamimore-Tomi** [comment]
HI @WanjaMIKE 

I think I have made all the revisions you asked for.

**Comment by WanjaMIKE** [comment]
@Bamimore-Tomi you cited 22 images but the article folder has 21 images. Could you check to ensure that everything is covered. Thanks

**Comment by Bamimore-Tomi** [comment]
Hi @WanjaMIKE 

I have committed the missing image. Thanks.

**Comment by WanjaMIKE** [comment]
```Add here a name that explains the image```

Like

```configuring rds```

**Comment by Bamimore-Tomi** [comment]
Hi @WanjaMIKE 

I have made the requested updates.

**Comment by WanjaMIKE** [comment]
@Bamimore-Tomi Almost done, just a few details remaining. Could you rename all your images to appropriate names. For instance, `database.png` instead of `eok26fqxrcha19wihv3j.png`. Do not forget to change the image links.

Also

Explain add some statements to explain the code in the section below. 
```
### Creating a database table
```
Thanks

**Comment by Bamimore-Tomi** [comment]
Hi @WanjaMIKE 

I have made the requested updates.

**Comment by WanjaMIKE** [comment]
@Bamimore-Tomi Note that you need to add an author's folder and push it alongside this PR. Check what other contributors have done in the content/authors folder on your local repository. Thanks

**Comment by Bamimore-Tomi** [comment]
@WanjaMIKE 

I have done that previously.

**Comment by Bamimore-Tomi** [comment]
@WanjaMIKE

I have done that previously.

**Comment by WanjaMIKE** [comment]
What names did you use @Bamimore-Tomi

**Comment by Bamimore-Tomi** [comment]
@WanjaMIKE 

https://github.com/Bamimore-Tomi/engineering-education/tree/master/content/authors/oluwatomisin-bamimore

Oluwatomisin Bamimore

**Comment by LinusMuema** [comment]
Hi @Bamimore-Tomi 
This is a really informative article and quite intuitive. Keep up the amazing job.

cc: @WanjaMIKE Great job on the review.

**Comment by Bamimore-Tomi** [comment]
Hi @WanjaMIKE  @LinusMuema  @hectorkambow 

Thanks for merging my article. I just checked the https://www.section.io/engineering-education/ website. I can't see the merged article there. Please, is there any problem?

**Comment by WanjaMIKE** [comment]
@Bamimore-Tomi I think there is an issue but not on your part. Don't worry it will be resolved soon. cc @LinusMuema

**Comment by LinusMuema** [comment]
Sorry about that @Bamimore-Tomi 
I'll check on your issue ASAP

**Pull request merged**
