### PR TITLE
How Java Virtual Machine Works

### LINKED ISSUE #3496: How Java Virtual Machine Works
### Proposed title of article
How Java Virtual Machine Works 

### Introduction paragraph (2-3 paragraphs):
The JVM (Java Virtual Machine) is a run-time engine that allows Java programs to run. The JVM is the program that executes the main function in java programming. JVM is a component of JRE (Java Runtime Environment). The compiler in other programming languages generates machine code for a specific system. The Java compiler, on the other hand, generates code for the Java Virtual Machine.

At the end of this article, the reader shall understand how a java virtual machine works.

### Key takeaways: 
-How does JVM execution engine work?
-How JVM Memory is used.
-The Java Native Interface (JNI).

### References: 
N/A

### PR DESCRIPTION
**Pull request by Geofreytech**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #3496 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Geofreytech** [comment]
@WanjaMIKE @hectorkambow @lalith1403 
This is the new PR
Duplicate of #3568 

I still don't know why it was closed, please.

**Comment by ahmadmardeni1** [comment]
We don't think this article is ready for a final review yet. Is it ready to be published now? @Geofreytech

**Comment by Geofreytech** [comment]
@ahmadmardeni1,
@lalith1403 was the reviewer
It's ready for a final review.

**Comment by Geofreytech** [comment]
@ahmadmardeni1 
Just the author page.

**Comment by Geofreytech** [comment]
@ahmadmardeni1 
I think it's ready, thank you

**Review by lalith1403 — CHANGES_REQUESTED** [review]
There are several formatting issues, sentences are grammatically right, but tough to read. Please triple check before submitting. After 3 rounds of revisions, we close the PR.

**Comment by lalith1403** [comment]
You have not corrected the formatting errors and hard to read sentences.

**Comment by Geofreytech** [comment]
> You have not corrected the formatting errors and hard to read sentences.

consider I done @lalith1403

**Comment by Geofreytech** [comment]
@lalith1403 I have corrected the formatting errors. Please confirm. 
Thank you

**Review by lalith1403 — APPROVED** [review]

**Comment by lalith1403** [comment]
@ahmadmardeni1 Can you review this article. It has reached a good shape.

**Comment by hectorkambow** [comment]
@Geofreytech 
[How Java Virtual Machine Works #3858.pdf](https://github.com/section-engineering-education/engineering-education/files/7199029/How.Java.Virtual.Machine.Works.3858.pdf)


The % is still way too high - we can not publish content that is not 100% original.

**Comment by Geofreytech** [comment]
@hectorkambow 
I have corrected. Thank you.

**Comment by lalith1403** [comment]
@hectorkambow Can you kindly look into this PR?

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by lalith1403** [comment]
@ahmadmardeni1 This has been in the queue for around 1.5 months now. Can you kindly take a look at it whenever you get a chance?

**Pull request merged**
