### PR TITLE
Collections in c++

### LINKED ISSUE #4767: Collection in c++
**topic suggestion**
Collection in c++

**Introduction**
Collection in c++ is a framework that provides an architecture for you to store and manipulate data. In fact talk about containers. It is often used when storing or manipulating data during runtime. In this article, we will introduce collection and discuss using various examples of how we can manipulate data at runtime without having to specify storage or size.
Furthermore, we will use clear explanations to understand the Collection interface hierarchy. We will see how the sub-interfaces like list, queue, set, etc relate to each other.
Moreover, we will learn how to implement the collections sub-interfaces since we cannot implement collection itself. We will further discuss the classes of collection which some of include ArrayList, LinkedList, among others.

**Key Takeaways**
In the article, the user will get to learn:

1. Introduce Collections in c++
2. The Collection interface hierarchy
3. Relation of Collection sub interfaces
4. Implementation of interfaces
5. Classes of collection

**Reference**

N/A

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

### PR DESCRIPTION
**Pull request by tetie**
This  fixes #4767

### CODE REVIEW

**Comment by geoffrey45** [comment]
Hello @tetie
Welcome to the EngEd program. We will review your article things like technical correctness before publishing.

Please remove these files from this pull request: `~/collections-in-c++/index.md ` and `~/collections-in-c++/hero.lnk`.

**Comment by tetie** [comment]
@geoffrey45  have done  some changes kindly check

**Comment by ahmadmardeni1** [comment]
👋 Good afternoon - and welcome to the EngEd program. @tetie 
There appear to be many sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).
We're really looking for unique/original content.

I'm going to close this PR and give you some time to work on it. 
cc @geoffrey45 
[Collections in c++#5073](https://github.com/section-engineering-education/engineering-education/files/7568695/New.Scan.8_00.AM.Copyleaks.Report.1.pdf)

**Comment by tetie** [comment]
hi @ahmadmardeni1 ,  I request that you open my  article so that can be able to commit  the changes . I have them here with me.

**Comment by hectorkambow** [comment]
@tetie 

Lets please be sure that we are submitting a final & polished article that is ready to published. To help prevent any possible back and forth as much as possible. 
🚀 

This help improve any review time.

**Comment by Kayere** [comment]
Hello @tetie.

 Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Collections in c++ #5073 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7669479/Collections.in.c%2B%2B.5073.Copyleaks.Report.pdf)

**Comment by hectorkambow** [comment]
@tetie 

Good afternoon and thank you for submitting your topic suggestion. Not a problem but it seems that this PR is still quite a bit aways from being completed. 
 
In an effort to be fair to our larger EngEd community as a rule of thumb - we can only accept content (pull requests) that are complete and fully polished articles/tutorial - meaning they are ready to be published. 
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) - this allow all revisions to be done on your forked personal repo. 
 
We will be closing this PR and please re-submit it when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 
 
>NOTE: A duplicate PR will go back into the queue and will not receive any further major revisions. A duplicate PR should be 100% ready to be published, otherwise it will be closed immediately. We encourage our new contributors to go over our [resources page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) and [new contributor folder](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors) to be better familiar with the level of quality and style we are looking to publish.
 
Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.
 
👍

**Comment by tetie** [comment]
hi @hectorkambow ,am requesting that you open this article so that  i can  be able  to commit changes.

**Comment by tetie** [comment]
Hello @hectorkambow , i wish you open this article, i have got new changes on it. I hope you will respond to this  .thank you

**Pull request closed without merging**
