### PR TITLE
Tutorial submission on Testing angular application using protractor and jasmine

### LINKED ISSUE #3213: Testing Angular applications using Protractor and Jasmine
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Eze4Manuel**
This closes #3213

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Plagiarism check done.

**Comment by Eze4Manuel** [comment]
Hello, I have made the corrections you highlighted. 

I also noticed there was a change made to the content label. From tech tutorial to article. The contents have a coding lab session in which the reader can practice and really get the whole picture of how testing with protractor and jasmine works in general. An article does not contain coding labs but this does.

**Comment by Eze4Manuel** [comment]
Hello,
I am done with the corrections that were highlighted. I noticed a change in
the label for the tutorial, from a tech tutorial to an article. I do not
really get why this was made seeing that the contents of the post have a
coding session that explains to the programmer the steps he should take and
has a code rundown with explanations that he can execute to get the
required knowledge he needs. If that does not constitute a tech tutorial,
what does?.

**Comment by srishilesh** [comment]
@Eze4Manuel 

Great question.

I would suggest you take a look at [this](https://github.com/section-engineering-education/engineering-education/pull/1094#issuecomment-759455467) comment on my PR. I had the same question earlier.

In your article, you have just stated the code snippet, while a tech-tutorial explains the step-by-step procedure on solving the problem. You must walk the reader through each step, explain how it works, insert appropriate images of the results/output.

My suggestion would be - apart from giving the reader an exercise, you could take up and explain how to test a particular angular application step-by-step. That would make this article, a tech-tutorial.

Hope this helps.

Thanks.

**Comment by srishilesh** [comment]
@Eze4Manuel 

And, regarding the suggested changes, I noticed you had committed several files (around 786 files). Take a look at the `Files changed` tab. Please revert these changes, and modify only the particular `index.md`.

Ping me when done.

Thanks.

**Comment by Eze4Manuel** [comment]
Made the update requested. 
I added more description to the coding section, explaining a step-by-step breakdown of the actions performed so as to make it more like a tech tutorial.  
There's an issue wrong with my MacOS treatment of line spaces. This causes multiple versions of a single file. I tried fixing it but seems it's not a simple solution and I will have to research the solution. Do bear with me on this push

**Comment by Eze4Manuel** [comment]
Hello,
Made the update requested.
I added more description to the coding section, explaining a step-by-step
breakdown of the actions performed so as to make it more like a tech
tutorial.
There's an issue wrong with my MacOS treatment of line spaces. This causes
multiple versions of a single file. I tried fixing it but seems it's not a
simple solution and I will have to research the solution. Do bear with me
on this push

**Comment by srishilesh** [comment]
@Eze4Manuel 

If you are facing some issues with your PC, I would suggest you to work on some online markdown editor or any other software like Obsidian.

**Comment by hectorkambow** [comment]
@Eze4Manuel 

More info on what we consider a tutorial as opposed to an article. 

>https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/FAQ.md#what-is-the-difference-between-a-tutorial-and-an-article

**Comment by hectorkambow** [comment]
creating a new PR would help (and be an easier solution) and only add the needed files. 
@Eze4Manuel 

cc @srishilesh

**Pull request closed without merging**
