### PR TITLE
Data Mining using CRISP-DM methodology

### LINKED ISSUE #1081: Data Mining using CRISP-DM methodology
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Cross-industry standard process for data mining, known as CRISP-DM, is an open standard process model that describes common approaches used by data mining experts. It is the most widely-used analytics model.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- The reader will understand various steps used in this methodology
- The reader will also understand this methodology, by analyzing a case study
- The reader will be able to plan out strategies for making their data science project successful.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
- https://en.wikipedia.org/wiki/Cross-industry_standard_process_for_data_mining
- https://paginas.fe.up.pt/~ec/files_0405/slides/02%20CRISP.pdf

### PR DESCRIPTION
**Pull request by srishilesh**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixed #1081

### CODE REVIEW

**Comment by hectorkambow** [comment]
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

**Review by lalith1403 — APPROVED** [review]
It is a detailed well-written article. This article can serve as a reference point for further articles in data science. Can you come up with a better title that catches the attention of the reader?

**Comment by lalith1403** [comment]
> It is a detailed well-written article. This article can serve as a reference point for further articles in data science. Can you come up with a better title that catches the attention of the reader?

@hectorkambow Can you suggest a good title capturing the essence of the article? The current title does a good job at it, but the article is useful for all. Including CRISP-DM will limit the audience to only those searching for this approach!

**Comment by srishilesh** [comment]
Hi @lalith1403 . Thanks for the review.

You're right. But, I have one more article coming up with a new and better approach, similar to this article. In that case, I feel,  generalizing the name of the article would not be good.

**Comment by srishilesh** [comment]
Hi @lalith1403 . 

Shouldn't this blog be considered as `tech-tutorial`?

In this blog, I have explained a problem statement, and explained step-by-step processes for mining the data.

**Comment by hectorkambow** [comment]
> Hi @lalith1403 .
> 
> Shouldn't this blog be considered as `tech-tutorial`?
> 
> In this blog, I have explained a problem statement, and explained step-by-step processes for mining the data.

👋  
Good morning @srishilesh  

Great point - upon a quick glance the PR looks like an article - what we mean as a tutorial is [something like this](https://www.section.io/engineering-education/speech-recognition-in-javascript/).

They are all "articles" but the tutorials for us have code snippets and step by step instructions on how to code something.(Explaing the code snippets)

**Comment by srishilesh** [comment]
> > Hi @lalith1403 .
> > Shouldn't this blog be considered as `tech-tutorial`?
> > In this blog, I have explained a problem statement, and explained step-by-step processes for mining the data.
> 
> 👋
> Good morning @srishilesh
> 
> Great point - upon a quick glance the PR looks like an article - what we mean as a tutorial is [something like this](https://www.section.io/engineering-education/speech-recognition-in-javascript/).
> 
> They are all "articles" but the tutorials for us have code snippets and step by step instructions on how to code something.(Explaing the code snippets)

Good morning @hectorkambow 

Thank you for helping me understand. I understood the difference between "articles" and "tech-tutorials".

**Comment by hectorkambow** [comment]
@srishilesh  👋  
Good evening - upon passing this article through our 3rd party plagiarism checker it raised quite a few red flags and the % was higher than we typically accept. 

We strive to always contribute completely unique and original content to the community whenever possible. 

Please revisit the article to see where any sources would be needed.

[Data Mining using CRISP-DM methodology #1094.pdf](https://github.com/section-io/engineering-education/files/5811968/Data.Mining.using.CRISP-DM.methodology.1094.pdf)

**Comment by srishilesh** [comment]
Good morning @hectorkambow .

I have added all the sources for this article. Thank you.

**Comment by lalith1403** [comment]
@hectorkambow can you check this article? The plagiarism has been tackled by adding sources. Let us know if any additional action is required.

**Comment by hectorkambow** [comment]
> Good morning @hectorkambow .
> 
> I have added all the sources for this article. Thank you.

Thank you for adding the sources - perhaps I was not clear enough. 

We need the entire text to be as original as possible i.e - having a low % - 46% is too high. We strive for 10% or lower. 

This would mean that the words, explanations, and phrasing need to be original - and still have the sources - since they are not original ideas. 

Hope this helps clear any confusion.

**Comment by srishilesh** [comment]
Good morning @hectorkambow ,

Thanks for the clarification.

I have rephrased the article with original ideas, and added necessary sources. Please let me know if I have to make anymore changes.

Thank you.

**Comment by hectorkambow** [comment]
plagiarism check done 👍  @lalith1403

**Comment by hectorkambow** [comment]
Great article @srishilesh  
Please go over the minor edits I made during my final review (this will help with reviews as well), 

🚀 
Overall great job

cc @lalith1403

**Pull request merged**
