### PR TITLE
 Introduction To Pragmatic Functional Java

### LINKED ISSUE #4217: [Languages] Introduction To Pragmatic Functional Java
### Topic Suggestion
Introduction To Pragmatic Functional Java

#### Proposed article introduction
Practical Java (PFJ) is an effort to develop and define a whole new programming style for the popular programming language Java. coding approach which utilizes both existing and future Java capabilities to the fullest extent possible and makes use of a compiler to assist programmers in creating code that is both succinct and dependable while still being easy to understand and follow.

While Java 8 may still utilize this style, Java 11 makes it considerably more streamlined and readable. With Java 17, it becomes even more expressive and gains from every new feature of the Java language.
Even yet, the benefits of PFJ don't come for free. Developers will have to make substantial adjustments to their working practices. Making a habit change is difficult, and classic necessary ones are particularly difficult.
In this article, we will discuss this concept in a more detailed way.

#### Key takeaways
By the end of this tutorial the reader will understand the following;

 - Elements Of Pragmatic Functional Java
 - Avoid null As Much As Possible (ANAMAP rule)
 - No Business Exceptions (NBE Rule)
 - Transforming Legacy Code Into PFJ Style Code
 - Interfacing With Legacy Code
 - Providing Legacy API
 - Managing Variable Scopes
 - Brief Technical Overview of Option<T> and Result<T>

#### Article quality
This article will be a unique article. Where I will explain the concepts in a more detailed way to add value beyond what is in the official documentation. I will make sure the article adds value to the rest of EngEd.

#### References
N/A

### PR DESCRIPTION
**Pull request by Shikomary**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #4217 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by M0nicah** [comment]
Great article @Shikomary 🚀. Moving on to the final review.

**Review by M0nicah — APPROVED** [review]

**Comment by Shikomary** [comment]
Hi, @M0nicah  would you ping @Kayere to continue with the final review please.

**Comment by hectorkambow** [comment]
@Shikomary 
Thank you for your patience as our team has been working diligently to work through the recent increased volume of articles coming in. 

We are going through are ready articles in the order they were received and working on improving our review time as well. 

🚀

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
Please go over my final edits to make sure I did not change any vital portion of the article - I deleted some parts that we a bit confusing. 👀

**Pull request merged**
