### PR TITLE
Connect flash express sessions and boostrap

### LINKED ISSUE #2989: Connect-Flash, Bootstrap, Passport and Express-sessions on the go
### Proposed title of article
Connect-Flash, Bootstrap, Passport and Express-sessions on the go

### Introduction paragraph (2-3 paragraphs):
Connect-flash is node module that allows developers to send flash messages to the user interface efficiently. Connect Flash usually works with express. Express sessions are used in managing sessions in an application. Session handling is a vital part in every web application.

Demonstrating session handling requires an authentication system and that where we will need passport. Passport is an authentication middle ware used to manage authentication in an application. Bootstrap is a CSS framework used for building responsive application.

This article aims at combining all the modules and demonstrate their functionality in a single application. We will build a login system that is based on passport authentication, manage our sessions using express sessions. And show flash messages using connect-flash with bootstrap styling. 

### Key takeaways: 
1. Session handling in an authentication application
2. Styling connect-flash messages using bootstrap
3. Authentication with passport
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### PR DESCRIPTION
**Pull request by salvador02**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- x ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #2989

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Review by jerimkaura — COMMENTED** [review]
@salvador02, You must have missed the GitHub link for the project.

**Comment by hectorkambow** [comment]
@salvador02 

👋 Good afternoon - and welcome to the EngEd program.
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Connect flash express sessions and boostrap #3599.pdf](https://github.com/section-engineering-education/engineering-education/files/7080305/Connect.flash.express.sessions.and.boostrap.3599.pdf)

**Comment by salvador02** [comment]
@salvador02, I noticed most of the plagiarism came from the bootstrap  and module import snippets that cant be changed. I however tried to fix the rest. 

Thanks.

cc: @jerimkaura

**Review by jerimkaura — CHANGES_REQUESTED** [review]
Hello @salvador02, 

Thank you for such a good article. It was clear and direct. However, you must have missed the hero image. Fix that then we finalize.

**Comment by ahmadmardeni1** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Connect flash express sessions and boostrap](https://github.com/section-engineering-education/engineering-education/files/7195122/New.Scan.10_40.AM.Copyleaks.Report.1.pdf)

**Comment by salvador02** [comment]
Hello @ahmadmardeni1 

I fixed the highlights

**Comment by WanjaMIKE** [comment]
Merged #3599

**Pull request merged**
