### PR TITLE
Quantum AI

### LINKED ISSUE #5735: [Artificial Intelligence] Overview of Quantum AI
#### Introduction
Quantum AI, as the title suggests, is the application of quantum technology to the calculation of machine learning procedures. Quantum technology and machine learning are both game-changing innovations that will change how people work and operate daily. Artificial intelligence, on the other hand, will almost certainly needs a better knowledge of quantum computing and quantum physics before it can acquire true life form intellectual ability. In this article we will discuss about quantum computing and how quantum AI works to make human works more easier.

#### Key takeaways 
1. Quantum AI and quantum computing definitions
2. How quantum AI works
3. Possible application of quantum computing in AI
4. Critical milestones for quantum AI

#### Article quality
This will be a unique article with more details on the topic. In my article, I will use simple language for any person reading to have a better understanding of the concepts in quantum AI. I will make sure that this article helps the rest of EngEd and goes beyond other official documentation.

#### References
N/A

### PR DESCRIPTION
**Pull request by Romans70**
#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
 

`This closes #5735

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Review by BrianaNzivu — APPROVED** [review]
Hey @Romans70 👋 .

Welcome to Section - EngEd.
We are happy to have you here.

Very good job on the article. It is a very interesting read 👏 . First of all, good job on the article. It is a very interesting read and very minimal corrections to be made. This is very impressive considering you are a first-time contributor.

- Please go through ALL the corrections I have made so that you can not repeat the same mistakes.

That's it! :smile: 

A final review will be done now by a content moderator.
Otherwise, congratulations on publishing your article🍾.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

**Review by louisefindlay23 — APPROVED** [review]
Final review complete. Congrats on your first article. Please remember that your author name should be lowercase.

**Comment by hectorkambow** [comment]
@Romans70 Can you please DM me via Slack asap 👍  

thank you

**Pull request merged**
