### PR TITLE
Implementing Africa's Talking SMS API using Node JS

### LINKED ISSUE #4994: Implementing Africa's talking API using Node.js
#### Proposed title of article
Implementing Africa's talking API using Node.js

#### Proposed article introduction
Africa's talking API is built to power communications solutions across Africa.

It enables software developers to be able to build scalable solutions by providing powerful  SMS, USSD, voice, airtime, and payments API's.

In this article, we will implement the Africa's talking SMS API using Node.js

#### Key takeaways 
- How to set up a sandbox project on Africa's talking.
- How to set up a restful API using Node.js and TypeScript.
- How to implement Africa's talking SMS API using Node.js and TypeScript.

#### Article quality

- In-depth guide particularly with Node.js.
- Step by step guidelines for beginners.

#### References
- https://developers.africastalking.com

### PR DESCRIPTION
**Pull request by mwangiKibui**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #4994

### CODE REVIEW

**Comment by mwangiKibui** [comment]
This closes #4994

**Comment by owinowendy** [comment]
@ahmadmardeni1 I would love to review this article.

**Comment by ahmadmardeni1** [comment]
Hey @owinowendy You have to wait until the current PR assigned to you is published.

**Comment by WanjaMIKE** [comment]
Plagiarism check is done.

**Comment by WanjaMIKE** [comment]
Great tutorial @mwangiKibui

**Comment by LinusMuema** [comment]
Hi @mwangiKibui 

Good job on the article

**Comment by mwangiKibui** [comment]
@LinusMuema Thanks

**Pull request merged**
