### PR TITLE
Servlet: Filter API

### LINKED ISSUE #4142: Servlet: Filter API.
#### Proposed title of article
Servlet: Filter API.

#### Proposed article introduction
When an application is pre-and post-processed, the object being invoked is filters. You can use and configure filters for some filtering tasks. This is included in the Servlet API. The filter interface is found in the javax.servlet package. In order to create a filter, we have to implement the filter interface.
You can have a number of filters for pre-and post-processing requests. In the deployment descriptor of the web application, filters are configured.

Interfaces available in servlet filters, and their methods will be discussed in this article.

#### Key takeaways 
1. Introduction.
2. Filter usage and its advantages.
3. Filter interface
4. FilterChain interface
5. FilterConfig interface
6. An example showing the use of a servlet filter

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A

### PR DESCRIPTION
**Pull request by Tumorbenson**
This closes #4142

### CODE REVIEW

**Comment by Tumorbenson** [comment]
Hello @ahmadmardeni1 , @hectorkambow  and @BrianaNzivu ? I've made a few changes to this article. Could you please have a look at it?

**Comment by hectorkambow** [comment]
@BrianaNzivu can we get a status on this PR ? 

If any more major revisions are needed - we will be closing this PR asap. 👀

**Comment by WanjaMIKE** [comment]
@BrianaNzivu should this PR be reassigned?

**Comment by BrianaNzivu** [comment]
> @BrianaNzivu should this PR be reassigned?

No, working on it ASAP.

**Comment by BrianaNzivu** [comment]
@section-engineering-education/content-moderator-team . 
I am kindly requesting a plagiarism check on this article.

**Comment by Kayere** [comment]
Plagiarism check done.

**Comment by Tumorbenson** [comment]
@BrianaNzivu, how are you?I would like to know the progress of this pr.

**Review by BrianaNzivu — APPROVED** [review]
Hey @Tumorbenson   👋 .

The article is a very interesting read. Good job!
Just a few things I'd like to point out:
1.  It is always advisable to submit an article that is well polished. By this, I mean having an article that does not have too many grammatical corrections and functional code. I suggest that you check out our [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) page which has links to various resourceful tools for writing. 
2. I'd like to recommend taking Google's technical writing [course](https://developers.google.com/tech-writing) which is absolutely free and can come in handy.
3. Lastly please go through **ALL** the corrections I have made so that you can not repeat the same mistakes.
4.  Don't forget to name your images properly and to always have their size as 600 x 400 px.

That's it! :smile: 

A final review will be done now by a content moderator.
Otherwise, congratulations on publishing your first article🍾.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
@Tumorbenson I believe we are missing your author details. 

@BrianaNzivu

**Comment by Tumorbenson** [comment]
> @Tumorbenson I believe we are missing your author details.
> 
> @BrianaNzivu

Hello @hectorkambow? I have added the author information. Thank you.

**Review by BrianaNzivu — COMMENTED** [review]
@Tumorbenson 👋 .
Your avatar image should be a headshot of yourself (600 x 400px). Please change that ASAP.

**Comment by Tumorbenson** [comment]
> @Tumorbenson 👋 . Your avatar image should be a headshot of yourself (600 x 400px). Please change that ASAP.

Done

**Comment by hectorkambow** [comment]
@BrianaNzivu 
We should have closed this PR - please take a very keen look at future pull requests.

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by Tumorbenson** [comment]
Hello @hectorkambow , not yet received payment of this pr.

**Pull request merged**
