### PR TITLE
Machine Learning using Pandas Profiling and Scikit-learn Pipeline

### LINKED ISSUE #6176: [Machine Learning] Machine Learning using Pandas Profiling and Scikit-learn Pipeline
#### Proposed title of article
[Machine Learning] Machine Learning using Pandas Profiling and Scikit-learn Pipeline

#### Proposed article introduction
Pandas profiling is an open-source Python module with which we can quickly do an exploratory data analysis. Pandas Profiling saves us all the work of visualizing and understanding the distribution of each variable. Pandas Profiling generates a report that shows the overview, variables, interactions, correlations, missing values, and a sample of your data. This enables faster data analysis and manipulation.

Python Scikit-learn provides a Pipeline utility to help automate machine learning workflows. Pipelines work by allowing for a linear sequence of data transforms to be chained together culminating in a modeling process that can be evaluated. The Pipeline assembles several steps that can be cross-validated together while setting different parameters.

Through the use of both the Pandas Profiling and Scikit-learn Pipeline, we will be able to build a machine model. The packages will enable to follow all the machine learning workflows and stages.
#### Key takeaways 
1. Installing Pandas Profiling
2. Generating the dataset profile report.
3. Initializing the pipeline steps.
4. Creating the Pipeline transformers and estimators.
5. Automate machine learning workflows.

#### Article quality
This tutorial is unique because we will use both the Pandas Profiling and Scikit-learn Pipeline. By the two libraries, we will build a custom model that predicts customer churn. The tutorial will also use guided steps that explain the installation and the use of these libraries. This is a practical approach. We will also explore the transformers and estimators functions that are used to automate the machine learning workflows

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Bravinsimiyu**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6176

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Review by jerimkaura — COMMENTED** [review]
Hey @Bravinsimiyu :wave: 

Thank you for such a great article. We highly encourage such straightforward articles. :rocket: 

However, during my first round of review, I noticed that the is one image you uploaded but did not appear in the article. Would you please add it where it belongs? `correlations-plots.jpg`.

Looking forward to learning from you! :tada: 

Thanks!

**Comment by Bravinsimiyu** [comment]
Hello @jerimkaura, I have added the `correlations-plots.jpg` image to the article.
Thanks.

**Review by jerimkaura — COMMENTED** [review]
Thank you, i am proceeding with the review.

**Comment by louisefindlay23** [comment]
Plagiarism check complete

**Review by jerimkaura — COMMENTED** [review]
Proceeding to tech review.

**Review by jerimkaura — APPROVED** [review]
Great article @Bravinsimiyu 

Do take a look at the changes I made to improve your future articles.

Moving this to the final review.

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
