### PR TITLE
Implement Multitenancy with Multiple Databases in Django

### LINKED ISSUE #5971: [ LANGUAGES ] Implementing multitenancy in a Django website using isolated Mongo DB databases with a shared app server
#### Proposed title of the article
[ LANGUAGES ] Implementing multitenancy in a Django website using isolated Mongo DB databases with a shared app server

#### Proposed article introduction

Multitenancy is whereby one web app installation can be used to serve more than one customer and each customer's data and users are isolated from each other's. example: Imagine that you built a web-based Library Management System for universities, and you want to provide your service to many universities without having to rebuild the same system for each university and hosting each.  

Multitenancy allows you to build one site and offer instances of your site to the universities as Software as a Service(SAAS) while keeping the data of each university isolated. Each university would be a tenant of your site hence the name Multitenancy.

#### Key takeaways 
At the end of the tutorial, the reader should be able to understand :
  1. What is multitenancy
  2. Importances of multitenancy 
  3. Implementing multitenancy in Django using this method
  4. Integrating Django with Mongo Db
  5. The advantages of using this method of multitenancy implementation
  
#### Article quality
This tutorial will look at how to implement multitenancy in Django using another Db other than the Default one provided by Django.
This will be done by building the web app from scratch in a step-to-step approach and then implementing the multitenancy to the app without neglecting the details. We won't use third-party Django apps.

#### References
N/A

### PR DESCRIPTION
**Pull request by Sajeyks**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #5971

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Plagiarism check complete

**Comment by srishilesh** [comment]
Thanks for making the changes.

I'll complete my final review by tomorrow.

**Comment by srishilesh** [comment]
Apologies for the delay in review. I was sick for the past few days. Getting started with my final review now.

**Comment by Sajeyks** [comment]
> 

It's okay, understand.

**Review by srishilesh — APPROVED** [review]
Hey @Sajeyks ,

Good work.

Please go through the changes I've made.

Moving for the final review.

Thanks.

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
