### PR TITLE
Real time search with react and laravel

### LINKED ISSUE #3668: How to build Real-time search with Laravel and React
## Summary
In this how-to guide, I'll guide readers through building a real-time search experience with a Laravel API and React.js. This tutorial will cover the basics of building such an experience in React and how best the backend can handle requests so as not to exceed Laravel's default rate limit.

## Outline

- What is real-time search and why is it important?
- Setting up the React Single Page Application (SPA)
- Setting up the Laravel API
- Architectural overview of the React SPA with code examples
- Architectural overview of the Laravel API with code example
- How to implement caching to reduce API calls
- Conclusion

### PR DESCRIPTION
**Pull request by vicradon**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites? See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #3668

### CODE REVIEW

**Comment by hectorkambow** [comment]
@WanjaMIKE  

Can we get a status update on this PR? 

Thank you 👍

**Comment by WanjaMIKE** [comment]
Just finishing up. Thanks

**Comment by WanjaMIKE** [comment]
@ahmadmardeni1 maybe you could give this PR a final review whenever you are free. Thanks

**Comment by ahmadmardeni1** [comment]
Great article @vicradon

Thank you for the review @WanjaMIKE

**Pull request merged**
