### PR TITLE
Spring Boot Docker tutorial

### LINKED ISSUE #1389: How to containerize Spring Boot application using Docker
### Brief Summary: 
[Docker](https://docs.docker.com/get-started/overview/), an open-source project launched in 2013, has helped popularize technology and has helped drive the trend towards containerization and micro-services in software development that’s known as cloud-native development. In the article I will be explaining how to containerize the `Todo` application that was created in [this](https://www.section.io/engineering-education/spring-boot-crud-api/) article using Docker.

### Key Takeaways: 
1. What is Docker.
2. What is Dockerfile and how to create it.
3. Creating Docker container from Dockerfile.

### References: 
[Understanding Docker concepts](https://www.section.io/engineering-education/docker-concepts/)
[Getting started with Docker](https://www.section.io/engineering-education/getting-started-with-docker/)

### PR DESCRIPTION
**Pull request by paulodhiambo**
### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1389

### CODE REVIEW

**Comment by jumamiller** [comment]
@hectorkambow, I'll be reviewing this article!

**Comment by jumamiller** [comment]
Great work @paulodhiambo, I've learned a lot from this tutorial! 
@hectorkambow, it's ready for final review on successful plagiarism check(s)!

**Comment by hectorkambow** [comment]
[Spring Boot Docker tutorial #1575.pdf](https://github.com/section-engineering-education/engineering-education/files/6065949/Spring.Boot.Docker.tutorial.1575.pdf)


@paulodhiambo  👋  

Please see how we can re-word/re-work the article - the % is way too high that we typically accept. 

I understand this is mostly from your older article - but this may mess up any SEO - of the 1st article. 

👍  

If needed lets simply refer people to the first article for any setup.

**Comment by paulodhiambo** [comment]
@hectorkambow I have revised the article.

**Pull request merged**
