### PR TITLE
RESTful web API in Node.js using Postgres SQL and Express

### LINKED ISSUE #866: Creating a RESTful web API in Node.js using Postgres SQL and Express
### Brief Summary: 

Section blog has an introductory to [Express](https://www.section.io/engineering-education/express/) guide, and here is a [node.js with MySQL](https://github.com/section-io/engineering-education/issues/826) guide in progress.
This guide will walk through creating an API with these two libraries to move information around the server to the client-side and vice versa.

### Key Takeaways: 

This will be a beginner/introductory APP.

I'll create a server to make responses and request to a MySQL database and make a client-side page to interact with the server and the database values.

This [Tutorial](https://www.section.io/engineering-education/building-a-basic-api-with-nodejs/) talks about a node.js RESTful API but I believe the two won't collide, as I will focus database data to interact with a server with an interaction client-side page.
### References: 
https://www.tutorialspoint.com/restful/restful_introduction.htm
https://www.npmjs.com/package/mysql
https://expressjs.com/en/starter/basic-routing.html

### PR DESCRIPTION
**Pull request by kimkimani**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you placed your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
fixes #866

### CODE REVIEW

**Comment by kimkimani** [comment]
@hectorkambow, this article is past 10% by a small margin, (the recommended Plagiarism score). I believe there are some boilerplate codes, which can't be changed. i.e creating a simple Express server. The EJS code blocks contain bootstrap classes and codes, which cannot be changed for the bootstrap to take effect. The reviewer may confirm that if need be. Thank you.

**Comment by hectorkambow** [comment]
> @hectorkambow, this article is past 10% by a small margin, (the recommended Plagiarism score). I believe there are some boilerplate codes, which can't be changed. i.e creating a simple Express server. The EJS code blocks contain Bootstrap classes and codes, which cannot be changed for the Bootstrap to take effect. The reviewer may confirm that if need be. Thank you.

Thank you for the heads up @kimkimani  - if its some boilerplate code that can not be changed - that should be fine 👍 

cc @WanjaMIKE

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by WanjaMIKE** [comment]
@kimkimani could you check the numbering in this section `### Setting up the views`. I see several statements with no 1.

**Comment by WanjaMIKE** [comment]
Nice article @kimkimani I have learned a lot about node.js. You hosted the node.js web api locally. Maybe, next time you could show us how to host it on section.io node server. Cheer!

**Review by WanjaMIKE — APPROVED** [review]
Nice article @kimkimani I have learned a lot about node.js. You hosted the node.js Web API locally. Maybe, next time you could show us how to host it on section.io node server. Cheers!

**Pull request merged**
