### PR TITLE
Building Scrollable and Lazy Components in Jetpack Compose

### LINKED ISSUE #2808: Building Scrollable and Lazy components in Jetpack Compose
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

### Proposed title of article

Building Scrollable and Lazy components in Jetpack Compose

### Introduction paragraph (2-3 paragraphs):

Jetpack Compose is an Android UI Toolkit with a new declarative approach. Compose makes it easy to design and manage your app's user interface by providing a declarative API that lets you render your app's user interface without having to change front-end views. This jargon has to be explained, but the ramifications are crucial for app design. 

Many apps require the visualization of multiple items. Compose includes a set of components that only compose and lay out elements visible in the view-port of the component. `LazyColumn` and `LazyRow` are two of these components. They manage how items are displayed regardless of their number. This makes development easier and provides an interactive experience to the users.

In this tutorial, we'll learn the best practices to build such components.

### Key takeaways: 
By the end of this tutorial, the readers will be able to;

1. Understand the "Lazy" terminology in Jetpack Compose.
2. Build scrollable compose elements.
3. Implement data models within composables.

### References: 

N/A

### PR DESCRIPTION
**Pull request by Janenjoki**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #2808

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Ericgacoki** [comment]
Greetings @Janenjoki,
Welcome to Section's Eng-Ed program. We're excited to have you on board. Thank you for submitting your `first article` for review.
I'll be reviewing it to check and help you fix any errors before being published! :rocket:

**Comment by Ericgacoki** [comment]
Hello @Janenjoki,
You have covered an awesome topic and your article's structure looks good - kudos for that :rocket:. However, I see you didn't check the plagiarism checkbox in the article checklist!
Please pass your article through [Quetext](https://quetext.com) and fix plagiarism to the lowest level possible (< 10%).

Kindly ping me when you're done so that I can update the labels. Thank you!

**Comment by Janenjoki** [comment]
Hello @Ericgacoki, I have updated the article as you suggested. Please proceed with the review.

**Comment by WanjaMIKE** [comment]
Plagiarism check done.

**Comment by Ericgacoki** [comment]
> Plagiarism check done.

Thank you Mike 🤗

**Review by Kayere — APPROVED** [review]
Great article @Janenjoki.
Thank you for the review @Ericgacoki.

**Pull request merged**
