### PR TITLE
How to iterate through a collection of an object using lambdas

### PR DESCRIPTION
**Pull request by kingsleynwafor54**
cc @louisefindlay23

This contains a technical write up about the topic written  above

### CODE REVIEW

**Comment by kingsleynwafor54** [comment]
I've been waiting for a reply for over a week now, I know you are busy but you can still squeeze out time.


@louisefindlay23 
@hectorkambow

**Comment by kingsleynwafor54** [comment]
Good day supervisors !, I don't understand why my article is still lying unanswered cos I have done the corrections. Correction is part of the process and I am willing to be corrected but being kept in the dark is frustrating.  @louisefindlay23  @hectorkambow

**Comment by WanjaMIKE** [comment]
@kingsleynwafor54 the PR is on a Queue and will be reviewed as soon as possible. Thanks

**Comment by hectorkambow** [comment]
@kingsleynwafor54 

Thank you for your patience, as our small team was working diligently to get through the queue.

**Comment by hectorkambow** [comment]
@section-engineering-education/peer-reviewers 
Is anyone available to review this PR? 

See if its ready to be published?

**Comment by WanjaMIKE** [comment]
> @section-engineering-education/peer-reviewers Is anyone available to review this PR?
> 
> See if its ready to be published?

Just finishing up.

**Comment by WanjaMIKE** [comment]
@Kayere could you give this PR a final review. Thanks

**Comment by Kayere** [comment]
Hello @kingsleynwafor54, this PR has been corrupted. I will be publishing the article using a different PR 👍.

cc: @WanjaMIKE

**Comment by hectorkambow** [comment]
@Kayere 

The author should be doing that.

**Comment by Kayere** [comment]
@hectorkambow - My IDE has caused the corruption. Otherwise, the article is ready.

**Comment by kingsleynwafor54** [comment]
@hectorkambow  @WanjaMIKE  @Kayere  Thanks a lot for publishing this PR, this shows reliability and credibility.
I saw that my name and the picture wasn't on the published work, at least my name(Nwafor Kingsley Chukwudi) should be there so I can tell my friends and colleague. Thanks for a great job I deeply appreciate it!

**Comment by WanjaMIKE** [comment]
@kingsleynwafor54 we will check it out. Thanks

**Comment by hectorkambow** [comment]
https://github.com/section-engineering-education/engineering-education/pull/5191/files

**Comment by hectorkambow** [comment]
> @hectorkambow @WanjaMIKE @Kayere Thanks a lot for publishing this PR, this shows reliability and credibility. I saw that my name and the picture wasn't on the published work, at least my name(Nwafor Kingsley Chukwudi) should be there so I can tell my friends and colleague. Thanks for a great job I deeply appreciate it!

Was that your 1st article? 
If so you may have missed adding the author file. 

cc @WanjaMIKE @Kayere

**Comment by kingsleynwafor54** [comment]
@hectorkambow @WanjaMIKE  Thanks for your concern. Also, I didn't miss adding my name and picture to the author folder, anyways thanks for you looking into it I sincerely appreciate it.

**Comment by Kayere** [comment]
Hello @kingsleynwafor54, please create a PR containing your author details. Ping me on the PR once created.

**Pull request closed without merging**
