### PR TITLE
Flutter Social Authentication 

### LINKED ISSUE #2394: A beginner-friendly guide into flutter social Authentication
### Proposed title of the article
A beginner-friendly guide into flutter social Authentication

### Introduction paragraph (2-3 paragraphs):
Social authentication is an authentication technique in which one uses an existing account to log into or create a new account in another application. Besides levying a user on constantly remembering multiple passwords, social authentication ease the registration process and improves security.

Most of the well-known social platforms widely used for social authentication are Facebook, Github, Google, and Twitter.
This article aims at guiding the readers through a step-by-step understanding and implementation of social authentication in Flutter while narrowing it down to Google and Facebook. We will build a project in flutter and implement social authentication in the flutter application.
### Key takeaways: 
1. Introduction to social Authentication
2.  Setting up Firebase console for Social Authentication
3. Integrating Google and Facebook authentication in Flutter.

### References: 
- https://firebase.flutter.dev/docs/auth/social/
- https://pub.dev/documentation/firebase_auth/latest/

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by jerimkaura**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2394

### CODE REVIEW

**Comment by paulodhiambo** [comment]
@srishilesh allow me to review this article.

Cc: @hectorkambow

**Comment by srishilesh** [comment]
@paulodhiambo 

Please proceed. Thanks.

**Comment by paulodhiambo** [comment]
@jerimkaura amazing tutorial. @hectorkambow you can give it a final review.

**Comment by hectorkambow** [comment]
@jerimkaura Questions why did you go about closing and opening the PR. 

I will be publishing this article - but I believe that is is missing ONE Image - there are 12 image paths and only 11 images. 

Please include this image as a new PR to be merged after the fact. 


cc @paulodhiambo - please be sure to check for all images to be included.

**Comment by jerimkaura** [comment]
> @jerimkaura Questions why did you go about closing and opening the PR.
> 
> I will be publishing this article - but I believe that is is missing ONE Image - there are 12 image paths and only 11 images. (OAuth redirect URI)
> 
> Please include this image as a new PR to be merged after the fact.
> 
> cc @paulodhiambo - please be sure to check for all images to be included.

About closing, I uploaded the index.md file before I could run it for plag check. I closed it just to be sure it is free of plagiarism and grammar mistakes before it gets reviewed.

For the image, I have uploaded it and here is the PR #2631

Thank you @hectorkambow

**Pull request merged**
