### PR TITLE
Getting started with Google sheets API in Node.js

### LINKED ISSUE #2236: Using Google Sheets API in Nodejs
### Proposed title of article
Using Google Sheets API in Nodejs

### Introduction paragraph (2-3 paragraphs):
Google sheet is an online-based spreadsheet that enables one to create and format spreadsheets while working with other people. It allows multiple users to collaboratively work on a document in real-time. 

Google developed Sheets API to achieve similar functions in various programming languages and frameworks including Nodejs. Among other functionalities, Sheets API allows one to create, write and read values from a spreadsheet and update the spreadsheets. 

This article aims at giving readers an understanding of how Google sheets API works and how to implement it in a Nodejs application.

### Key takeaways: 
1. What is Sheets API?
2. Integrating Sheets API in Nodejs 
3. Creating spreadsheets using Sheets API
4. Manipulating spreadsheets

### References: 
https://developers.google.com/sheets/api/quickstart/nodejs

### PR DESCRIPTION
**Pull request by mia-roberts**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2236

### CODE REVIEW

**Comment by mia-roberts** [comment]
@paulodhiambo  You can check out the article.

Thank you!

**Comment by paulodhiambo** [comment]
@mia-roberts amazing tutorial on Google sheets. @hectorkambow you can give it a final review.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by hectorkambow** [comment]
@mia-roberts overall super great article - very easy to follow along. 

Some minor edits on my part - more about consistency throughout the article. 
>Noticed some:
inconsistent capital letters. …
google - and Google
api and API
cc @paulodhiambo please go through my edits to improve future reviews as well 🚀

**Comment by hectorkambow** [comment]
One MAIN Thing - i noticed line 212 I believe (look at one of my commits) was an empty code block - not sure if this was needed or was a missing code snippet - please review - and if needed we can add in after the fact .. @mia-roberts 
cc @paulodhiambo

**Pull request merged**
