### PR TITLE
Getting Started With Fastify Node.js framework and Faunadb

### LINKED ISSUE #2043: Getting started with Fastify Node.js framework and faunadb
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Getting started with Fastify Node.js framework and faunadb 

### Introduction paragraph (2-3 paragraphs):
Fastify is a framework for backend web development with a powerful plugin architecture and the least overhead. It’s primarily inspired by Hapi and Express and is one of the fastest web frameworks running on Node.js. On the other hand, [Faunadb](https://fauna.com/) is a multi-model cloud database created to integrate with the JAMstack and modern serverless architecture. It easily transforms the traditional DBMS into a Data API that gives us all the capabilities of an old-guard database, without sacrificing flexibility, scale, and performance. In this tutorial, we will building an API to see a quick overview on how to use Fauna and Fastify in Node.js.

### Key takeaways: 
1. Introduction to Faunadb
2. Introduction to Fastify Node.js framework
3. How to integrate Fastify and Faunadb in a Node.js application
4. Building a Node.js backend API using Faunadb and Fastify

### References: 
N/A.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by marienjus**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2043

### CODE REVIEW

**Comment by marienjus** [comment]
Hi @srishilesh :wave:

**Review by srishilesh — APPROVED** [review]
@marienjus 

Great article. Good work!

Please go through my commits to understand and improve on your future articles.

Just a suggestion, you could probably write articles exclusively on Fastify and FaunaDB. This would allow the readers to go through them first and understand better, before they read this article.

Moving for the final review.

Thank you.

**Comment by hectorkambow** [comment]
@marienjus FYI PRs can only be created (and submitted) once the articles are completed.

Please refrain from creating a PR to close and then re-open. Thank you.

Cc @srishilesh

**Comment by marienjus** [comment]
Okay, I understand,. @hectorkambow.

**Comment by marienjus** [comment]
What should I do about this. Is this article still ready?

**Comment by hectorkambow** [comment]
[Getting Started With Fastify Node.js framework and Faunadb #2256.pdf](https://github.com/section-engineering-education/engineering-education/files/6697303/Getting.Started.With.Fastify.Node.js.framework.and.Faunadb.2256.pdf)

👋 Good afternoon - Hector here.
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

**Comment by marienjus** [comment]
Quite surprised most of pliagirism is from variable and code keywords. I'll be fixing this @hectorkambow 👍

**Comment by hectorkambow** [comment]
Great work - very nice tutorial. @marienjus 

Please be sure to go through the minor edits I made during my final to improve future articles/reviews. 
cc @srishilesh

**Pull request merged**
