### PR TITLE
Collection in Java

### LINKED ISSUE #4354: Collection in Java
### Introduction
Collection in Java is a framework that provides an architecture for you to store and manipulate data. Collection is often used when storing or manipulating data during runtime. In this article, we will introduce collection and discuss using various examples of how we can manipulate data at runtime without having to specify storage or size. 
Furthermore, we will use flowcharts and clear explanations to understand the Collection interface hierarchy. We will see how the sub-interfaces like list, queue, set, etc relate to each other.
Moreover, we will learn how to implement the collections sub-interfaces since we cannot implement collection itself. We will further discuss the classes of collection which some of include ArrayList, LinkedList, HashSet class, HashMap class, etc

### Key Takeaways
In the article, the user will be able to learn:
1. Introduce Collections in java
2. The Collection interface hierarchy
3. Relation of Collection sub interfaces
4. Implementation of interfaces
5. Classes of collection

### Reference
N/A

### PR DESCRIPTION
**Pull request by Koros-Meshack**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4354

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Review by BrianaNzivu — CHANGES_REQUESTED** [review]
Hey @Koros-Meshack  👋 .
My name is Briana and I will be conducting the review for your article.
Good job on the article!
Just one small thing I want you to correct as I proceed with the tech review. I need you to scale down your java hierarchy image to the required 600 x 400 px. You can use [BeFunky](https://www.befunky.com/) to do this.
Also please add the table of contents to this article.

Regards

**Comment by hectorkambow** [comment]
> Hey @Koros-Meshack 👋 . My name is Briana and I will be conducting the review for your article. Good job on the article! Just one small thing I want you to correct as I proceed with the tech review. I need you to scale down your java hierarchy image to the required 600 x 400 px. You can use [BeFunky](https://www.befunky.com/) to do this. Also please add the table of contents to this article.
> 
> Regards

FYI @BrianaNzivu only the hero image should be scaled down - some in article images may not be able to be seen well if they are so small

**Comment by BrianaNzivu** [comment]
> > Hey @Koros-Meshack 👋 . My name is Briana and I will be conducting the review for your article. Good job on the article! Just one small thing I want you to correct as I proceed with the tech review. I need you to scale down your java hierarchy image to the required 600 x 400 px. You can use [BeFunky](https://www.befunky.com/) to do this. Also please add the table of contents to this article.
> > Regards
> 
> FYI @BrianaNzivu only the hero image should be scaled down - some in article images may not be able to be seen well if they are so small

Noted.
@Koros-Meshack you can add the table of contents only then.

**Comment by WanjaMIKE** [comment]
Plagiarism check done

**Review by BrianaNzivu — APPROVED** [review]
Hey @Koros-Meshack  👋 .

Very good job on the article. It is a very interesting read and has minimal mistakes 👏 .

Just a few things I'd like to point out:
- I suggest that you check out the [structure](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors) for the various articles accepted by Section.
- Lastly please go through ALL the corrections I have made so that you can not repeat the same mistakes.

That's it! :smile: 

A final review will be done now by a content moderator.
Otherwise, congratulations on publishing your article🍾.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Once again good job! 👍 

Kind Regards
*P.s Happy new year and a prosperous 2022*

**Comment by Koros-Meshack** [comment]
Am grateful for your review of my article @BrianaNzivu and thanks for your remarks.
Looking forward to interacting more.
Happy new year too.

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request closed without merging**
