### PR TITLE
How kerckhoffs principle is applied in cryptography

### LINKED ISSUE #4247: [Security] How Kerckhoff's Principle is Applied in Cryptography.
#### How Kerckhoff's Principle is Applied in Cryptography.
Kerckhoff's state that a cryptographic system should be secure even if everything about the system except the key is publicly known
According to Kerckhoff's Principle, a cryptographic system's security is solely dependent on the secrecy of its keys, and everything else, including the algorithm itself, should be regarded public knowledge. 

#### Key takeaways 
- Understand the state principle of kerckhoff's principle
- Get to know the origin of kerckhoff's principle
- Have an understanding on various fundamental principles of crypto system
- The relationship between Kerckhoff's principle and Shannon's Maxim principle
- Difference between kerckhoff's principle and Security by Obsecurity

#### Article quality
This article aims to explain how to develop secure systems with this kerckhoff's principle which is not covered in most article

#### References
[kerckhoff's principle](http://www.crypto-it.net/eng/theory/kerckhoffs.html)

### PR DESCRIPTION
**Pull request by leence00**
This fixes #4247

### CODE REVIEW

**Comment by LinusMuema** [comment]
Hi @leence00 

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[How kerckhoffs principle is applied in cryptography #5074 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7593406/How.kerckhoffs.principle.is.applied.in.cryptography.5074.Copyleaks.Report.pdf)

**Comment by leence00** [comment]
hello @WanjaMIKE have fixed the plagiarism

**Comment by WanjaMIKE** [comment]
finishing up

**Comment by WanjaMIKE** [comment]
Finishing up

**Comment by WanjaMIKE** [comment]
@leence00 I had to abort my review because I am understanding the direction of the article. You started well but in the middle of it, you lose it. There are numerous repetitions that have affected its quality. You will need to rework and resubmit. Thanks

**Pull request closed without merging**
