### PR TITLE
Visualizing Time Series Data With Chart.Js

### LINKED ISSUE #6881: Visualizing Time Series Data With Chart.Js
### Topic Suggestion
Visualizing Time Series Data With Chart.Js

#### Proposed title of article
Visualizing Time Series Data With Chart.Js

#### Proposed article introduction
Time series data is a collection of observations measured over time. Time series data is everywhere since time is a constituent of everything observable. They can be beneficial for tracking and analyzing changes over time. This guide will visualize time series data with Chart.js and InfluxDB.  InfluxDB is a database specifically designed to work with time-series data.

This article will use Chart.js and InfluxDB to visualize time series data. By leveraging the capabilities of InfluxDB along with the flexibility and power of Chart.js, you can visualize time series data efficiently. This guide will explain how the reader can use Chart.js in conjunction with InfluxDB cloud for data visualization.

#### Key takeaways 
1. Time series data
2. Visualizing Time Series Data with Chart.js and InfluxDB

- Chart.js overview
- Set up project with Chart.js
- Set up InfluxDB
- Configure the client to communicate with InfluxDB cloud
3. Using Chart.js with InfluxDB

- Use Flux to query data from InfluxDB cloud
- Visualize the data with Chart.js and create different types of charts using data from InfluxDB

#### Article quality
This is an interactive and well detailed tutorial about visualizing time series data with chart.js and InfluxDB. The content covered will be unique as this topic is not widely covered.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### PR DESCRIPTION
**Pull request by Pauline-Mwangi**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6881

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Pauline-Mwangi** [comment]
Hello @mercymeave. Thank you for the correction. I made a change

**Comment by Kayere** [comment]
Plagiarism check done ✅

**Review by mercymeave — COMMENTED** [review]
Hello, @Pauline-Mwangi 

I am noticing a few mistakes in your article. would you please go over the article to ensure it is okay grammatically?

**Comment by mercymeave** [comment]
Hello @Pauline-Mwangi 

Kindly update the `bar-chart.JPG` extension to lowercase  i.e`bar-chart.jpg` then we finalize.

Thanks.

**Comment by Pauline-Mwangi** [comment]
Hello @mercymeave, thank you for the article review. Your corrections and insights have been of much help.

**Comment by mercymeave** [comment]
> 2d9d1ff

Work on this too, i need to do final review

**Comment by mercymeave** [comment]
> Work on this too, i need to do final review

Work on this too, i need to do final review

**Comment by Pauline-Mwangi** [comment]
> Hello @Pauline-Mwangi
> 
> Kindly update the `bar-chart.JPG` extension to lowercase i.e`bar-chart.jpg` then we finalize.
> 
> Thanks.

@mercymeave the image extension is at lowercase

**Comment by mercymeave** [comment]
> > Hello @Pauline-Mwangi
> > Kindly update the `bar-chart.JPG` extension to lowercase i.e`bar-chart.jpg` then we finalize.
> > Thanks.
> 
> @mercymeave the image extension is at lowercase

BIN +37.6 KB 
[content/articles/visualize-time-series-data-with-chart-js/bar-chart.JPG](https://github.com/section-engineering-education/engineering-education/pull/7358/files#diff-102f16f7931c9b30f38ee76a797b2c7db47dbc2a32240c8a057647bc864a7081)

**Comment by Pauline-Mwangi** [comment]
> > [2d9d1ff](https://github.com/section-engineering-education/engineering-education/commit/2d9d1ff22978dcd2d0f3ace94c95dbfb2012f87b)
> 
> Work on this too, i need to do final review

Worked on it

**Comment by mercymeave** [comment]
Check slack @mercymeave

**Comment by Pauline-Mwangi** [comment]
> > > Hello @Pauline-Mwangi
> > > Kindly update the `bar-chart.JPG` extension to lowercase i.e`bar-chart.jpg` then we finalize.
> > > Thanks.
> > 
> > 
> > @mercymeave the image extension is at lowercase
> 
> BIN +37.6 KB [content/articles/visualize-time-series-data-with-chart-js/bar-chart.JPG](https://github.com/section-engineering-education/engineering-education/pull/7358/files#diff-102f16f7931c9b30f38ee76a797b2c7db47dbc2a32240c8a057647bc864a7081)

Please have a check again because on my end it's updated in lowercase

**Comment by Pauline-Mwangi** [comment]
@mercymeave updated the extension to lowercase

**Comment by hectorkambow** [comment]
> @mercymeave updated the extension to lowercase

Please be sure to do a full review of your articles before submitting - as our peer reviewers do not provide revision services. 

They check whether the material is accurate or not - if revisions are needed we will be closing the PR to allow the proper time to make the edits.

@Pauline-Mwangi

**Comment by mercymeave** [comment]
> > @mercymeave updated the extension to lowercase
> 
> Please be sure to do a full review of your articles before submitting - as our peer reviewers do not provide revision services.
> 
> They check whether the material is accurate or not - if revisions are needed we will be closing the PR to allow the proper time to make the edits.
> 
> @Pauline-Mwangi

She fixed the image extension, I am on my final touches.

**Review by mercymeave — APPROVED** [review]
Forwarding this for final review.

**Comment by WanjaMIKE** [comment]
Merged #7358 into master

**Pull request merged**
