### PR TITLE
Introduction to hibernate

### LINKED ISSUE #4029: Introduction to Hibernate
#### Proposed title of the article
Introduction to Hibernate

#### Proposed article introduction
Hibernate is a Java framework that makes it easier to create Java applications that interface with databases. Hibernate also allows you to query and retrieve data.
It creates SQL calls, freeing the developer from having to manually handle and convert the query results. In this article, we are going to at an overview of hibernate, the architecture of hibernate, installation process, advantages and disadvantages of hibernate and a hibernate example.

#### Key takeaways 
What is hibernate?
The architecture of Hibernate.
installation process.
Advantages and disadvantages of hibernate.
Hibernate example

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A

### PR DESCRIPTION
**Pull request by morwabe1234**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4029

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by morwabe1234** [comment]
Hello @BrianaNzivu? I completed the requested changes from the closed article and submitted this as a new PR, following your advice from the previous PR. Please continue with the review.
Thank you.

**Review by BrianaNzivu — CHANGES_REQUESTED** [review]
Hey @morwabe1234 👋  .

First of all, welcome to Section - EngEd. :tada: 
We are happy to have you here.

Good job on the article. It is a very interesting read.

Just a few changes I need you to make as we continue with the preliminary revisions:
- Your article has quite a lot of grammatical mistakes and unclear sentences. You can use 
[Grammarly](https://app.grammarly.com/ddocs/1287976180) to correct it. 
- I have noticed some of your images are large. All your images including your avatar image should be scaled down to 600 x 400 px as required. You can use [Befunky](https://www.befunky.com/) to do this.
- Please rename your png images from `PNG` to `png`.

In case of any question or help needed please do not hesitate to ping me here :smile:.
Also, notify me when you are done.

Regards.

**Comment by BrianaNzivu** [comment]
Hey @morwabe1234 👋 .

I see you having a copies of the original images and index.md file. Instead of one file of each I am seeing two.
Please delete the new copies.

Once more change images tagged as `PNG` which are in uppercase to `png` in lower case.
Please ping me when done.

**Comment by morwabe1234** [comment]
Hi @BrianaNzivu,I have resized and renamed  the images as you suggested and also made some corrections on grammar.You can progress with  the review.Thank you.

**Comment by BrianaNzivu** [comment]
Hey @morwabe1234 .
The section website does not support the 'jpn' format.
It only support 'jpg' or 'png'

Please correct this.

**Comment by morwabe1234** [comment]
Hi @BrianaNzivu ,I have done the correction on the images by renaming the images with .jpg format as requsted.You can proceed with the review .Thank you.

**Comment by hectorkambow** [comment]
Running a plagirism check now

**Comment by hectorkambow** [comment]
[Introduction to hibernate #4512.pdf](https://github.com/section-engineering-education/engineering-education/files/7523791/Introduction.to.hibernate.4512.pdf)

**Comment by hectorkambow** [comment]
@morwabe1234 

👋 Good afternoon - and welcome to the EngEd program. 
Unfortunately, there appear to be many sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).
We're really looking for unique/original content

cc @BrianaNzivu

**Comment by morwabe1234** [comment]
@hectorkambow ,Hello. I'm done with removing plagiarism,please open for me to submit.Thank you.

**Comment by BrianaNzivu** [comment]
> @hectorkambow ,Hello. I'm done with removing plagiarism,please open for me to submit.Thank you.

Go ahead @morwabe1234 .

**Comment by ahmadmardeni1** [comment]
👋 Good afternoon - and welcome to the EngEd program. @morwabe1234 
There appear to be many sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).
We're really looking for unique/original content - I'm going to close this PR.
cc @BrianaNzivu 
[Introduction to hibernate#4512](https://github.com/section-engineering-education/engineering-education/files/7546948/New.Scan.2_08.PM.Copyleaks.Report.pdf)

**Comment by morwabe1234** [comment]
Hello @ahmadmardeni1, you closed my article before a submitted the changes requsted for.Please open for me to submit the article, I am done with working on plagiarism.Thank you.

**Comment by Jairusonkundi** [comment]
Hello @BrianaNzivu , my article was closed before a submitted the changes requsted for.Please reopen for me to submit the article, I am done with working on plagiarism.Thank you.

**Comment by morwabe1234** [comment]
Hello @hectorkambow , my article was reopened for me to submit the requested changes but again closed within a short time  before a submitted the changes requsted for.Please open for me to submit the article, I am done with working on plagiarism.Thank you.

**Pull request closed without merging**
