### PR TITLE
Understanding IPSec

### LINKED ISSUE #7058: [Networking]Understanding IPSec
#### Proposed title of article
Understanding IPSec

#### Proposed article introduction
Internet is a vast place with numerous facilities available for the users to rely on. Communication is one such important facility. When two or more internet-connected devices communicate with each other for the transmission of resources and data, they form a network. As remarkable as it appears, sending or receiving anything over this huge network might be rather risky.
 
It is crucial to ensure that both the sender and the receiver are trustworthy because the information being transmitted may be sensitive and should not be publicly disclosed, mandating encryption. It should also be remembered that, just as sensitive information should not be sent, malicious information should not be received as well. Even if such measures are undertaken, it is important to guarantee that no third party interferes or tampers with the connection. To prevent data from being leaked and misused for illicit reasons by the third party, the connection must be secured. This is where IPSec plays its role. 
 
As the name implies, IPSEC (or IP Security) secures the internet protocol suite and establishes secure connections between network users while authenticating them. It also encrypts data to prevent unauthorized access to the data and can only be decrypted using the shared keys by the sender and receiver during a session.

#### Key takeaways 
The readers will learn about:
- IPSec
- Components of IPSec
- Introduction to cryptography
- IPSec cryptographic algorithms
- Why IPSec is needed

#### Article quality 
Other resources available are slightly more technical, making it difficult for beginners to get started with the topic. This may make it easier for them to understand the underlying terms, after which they can move on to the intermediate concepts related to IPSEC.

#### References
https://en.wikipedia.org/wiki/IPsec
https://www.techtarget.com/searchsecurity/definition/IPsec-Internet-Protocol-Security

### PR DESCRIPTION
**Pull request by kvardhan10**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #7058

### CODE REVIEW

**Comment by kvardhan10** [comment]
Also, updated my avatar image for author page

**Comment by kvardhan10** [comment]
Hey @mercymeave . What's the progress of the review phase?

**Comment by mercymeave** [comment]
Would you please go over the article once more and shorten the long paragraphs for readability?

**Comment by kvardhan10** [comment]
> Would you please go over the article once more and shorten the long paragraphs for readability?

Done @mercymeave 
Also, I want to update my avatar image. Can you verify whether the file is correct or should I modify it?

**Comment by WanjaMIKE** [comment]
Plagiarism check is done

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
@kvardhan10

**Comment by kvardhan10** [comment]
> 👍 Well done updating your profile image.
> 
> Be sure to see your live published article on the site (it should be live within 30 mins).
> 
> To give your article a boost in page engagement - share it across your social site (linkedin/twitter) and tag the EngEd program so we can also share it and give it some traction as well!
> 
> If you have not done so already, consider _**adding a skill section to your profile page.**_ This will go a long way for potential future employers.

@hectorkambow I want to add a skills section to my author page. To do that should I update my index.md file from my author folder and create a PR or is there any other way?

**Pull request merged**
