### PR TITLE
Using Formidable for parsing form data in Node.js application.

### LINKED ISSUE #2248: Using Formidable for parsing form data in Node.js application.
### Proposed title of the article
**Using Formidable for parsing form data**

### Introduction paragraph (2-3 paragraphs):
Formidable is an npm package that has been around the longest, with version 1.0 being released in 2011. This package is used to parse multipart form data, especially file uploads. A few months ago, I wrote an article about Multer which is also used for almost the same purpose. 
So, this article will also be a step-by-step tutorial on how to upload any kind of files from client-side to server-side **while focusing on different steps and strategies we can make in Formidable which makes it more famous than Multer.**

### Key takeaways: 
1. How to use Formidable to parse form data.
2. How to use different configuration methods that come with Formidable.
3. Difference between Multer and Formidable.

### References: 
N/A

### Templates to use as guides
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by sardug10**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

This fixes #2248 

Just a heads up, seeing that this article and my preceding article on this platform both, have an identical purpose, and simply the technology is different. I have used sentences from my preceding article around 10%-20% in this article. So, will it create a problem for plagiarism?

### CODE REVIEW

**Review by LinusMuema — COMMENTED** [review]
Hi @sardug10 
This is an interesting read. Just a few changes I have made in the article. 
Take a note for future articles. I think the article is ready for final review.

cc: @hectorkambow

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by hectorkambow** [comment]
[Using Formidable for parsing form data in Node.js application. #2445.pdf](https://github.com/section-engineering-education/engineering-education/files/6649792/Using.Formidable.for.parsing.form.data.in.Node.js.application.2445.pdf)

@sardug10 

Please review - as the 1st few sentences raised some red flags - 🤔 

If the sentences need some references - please add those as to not be flagged for plagiarism

**Comment by sardug10** [comment]
> [Using Formidable for parsing form data in Node.js application. #2445.pdf](https://github.com/section-engineering-education/engineering-education/files/6649792/Using.Formidable.for.parsing.form.data.in.Node.js.application.2445.pdf)
> 
> @sardug10
> 
> Please review - as the 1st few sentences raised some red flags - 🤔
> 
> If the sentences need some references - please add those as to not be flagged for plagiarism

Hello, @hectorkambow. I mentioned that the first few paragraphs are **from my previous article on this same platform.** So, should I refer to them in this article?

**Comment by hectorkambow** [comment]
> > [Using Formidable for parsing form data in Node.js application. #2445.pdf](https://github.com/section-engineering-education/engineering-education/files/6649792/Using.Formidable.for.parsing.form.data.in.Node.js.application.2445.pdf)
> > @sardug10
> > Please review - as the 1st few sentences raised some red flags - 🤔
> > If the sentences need some references - please add those as to not be flagged for plagiarism
> 
> Hello, @hectorkambow. I mentioned that the first few paragraphs are **from my previous article on this same platform.** So, should I refer to them in this article? I even mentioned that in the pull-request.

Ah understood - thank you for the clarification. 

It would be helpful for the audience to have the article as reference. 

We can add that at anytime. 

Thank you for the clarification - we'll go ahead an get the article ready to publish 👍

**Comment by hectorkambow** [comment]
Great work 👍 
@sardug10 

cc @LinusMuema

**Pull request merged**
