### PR TITLE
 How to use React to send a POST request to a Laravel application

### LINKED ISSUE #1620: How to use React to send a POST request to a Laravel application
### Proposed title of the article
How to use React to send a POST request to a Laravel application
### Introduction paragraph(s):
Maybe you are a backend engineer wanting to load data to your site using the React library, or you want to explore the use of React with Laravel or you have any other interests validating the use of Laravel with React, then you are at the right place. We are going to learn how to make a POST request to a Laravel application using React and retrieve the response.

#### Basic descriptions

- **React:** This is a JavaScript library that assists us in creating interactive and dynamic Single Page Applications. 
- **Axios:** It is a library used to handle HTTP requests to external resources in our web applications.
- **Laravel:** This is a PHP framework based on the Model View Controller architecture and it helps us create web backend applications faster.

#### Prerequisites

- A basic understanding of PHP and its working with Laravel
- A basic understanding of HTML and CSS
- A basic understanding of JavaScript and its working with React
- Php, Composer, Laravel installer installed in your machine.

Having that, we can now start delving into the topic.

#### What will be doing

We will be sending input data from a signup page and send the data to a Laravel controller which will, in turn, return JSON data and display it in an alert.

> **JSON**, JavaScript Object Notation, is a data exchange format between web applications.

### Key takeaways: 
In the end, the user will get to learn about:

- JSON and its role in HTTP requests
- The Axios library and how to use it to send HTTP POST data
- Using Axios in React
- Receiving the POST request in a Laravel application and returning the response back as JSON

### References: 

- [Jason Watmore's blog](https://jasonwatmore.com/post/2020/07/17/react-axios-http-post-request-examples)
- [Blog Pusher](https://blog.pusher.com/react-laravel-application/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Agusioma**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you placed your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1620

### CODE REVIEW

**Review by kayere — COMMENTED** [review]
Hello @Agusioma - Great article, very informative. Just one suggestion. Please make the conclusion a bit longer.

**Comment by Agusioma** [comment]
Hello @kayere .
Thank you for the review. Am working on the conclusion.

**Comment by Agusioma** [comment]
@kayere done. Please check.

**Review by kayere — APPROVED** [review]

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by hectorkambow** [comment]
@Agusioma Great work overall - please go over the changes as there were some parts I found taking a double look (or difficult to understand). 

Please include any applicable changes to future articles.

cc @kayere

**Pull request merged**
