### PR TITLE
routing-essentials

### LINKED ISSUE #1454: Basics of Routing in Computer Networking
**NOTE: We tend to stray away  or tend not to publish reviews/comparisons of commercial product offerings.**

### Brief Summary: 
Connectivity between networks, both on Local Area Network (LAN) and internet at large, are managed and controlled by the idea of computer networking and **routing** been one of the important component. For this reason, understanding how it works is very important for both the users and developers.

### Key Takeaways: 
- Understand basis of routing process
- Understand IP address and how they work together to provide network access
- How packets (data) moves from one end of a network to another
- Explain the key concepts of routing and networking at large

### References: 
[Routing at WikiPedia](https://en.wikipedia.org/wiki/Routing)

### PR DESCRIPTION
**Pull request by Taiwrash**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #1454 "](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [X] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [X] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [X] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by Taiwrash** [comment]
@hectorkambow don't forget to keep track for **peer reviewer** qualifications. Thanks

**Comment by raboba2re** [comment]
@hectorkambow  I will like to review this article

**Comment by hectorkambow** [comment]
> @hectorkambow I will like to review this article

@raboba2re 

Im noticing that this PR was opened earlier today - just as a standard rule of thumb - **we like to review from oldest to newest.
Is there an older (unassigned) PR that you could review?**

**Comment by raboba2re** [comment]
> 
> 
> > @hectorkambow I will like to review this article
> 
> @raboba2re
> 
> Im noticing that this PR was opened earlier today - just as a standard rule of thumb - **we like to review from oldest to newest. Is there an older (unassigned) PR that you could review?**

@hectorkambow  All PRs seems to be assigned Sir.

**Comment by hectorkambow** [comment]
@raboba2re 

Okay sounds good 👍 
Thank you for checking 
Please continue

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by hectorkambow** [comment]
@Taiwrash 

FYI at a quick glance this article seems extremely basic - it seems like it could be improved quite a bit. 


Again we want to make sure this goes beyond any basic explanation. 

What is the point of this topic - what is the reader learning here that they can not get anywhere else. 

🤔

**Comment by hectorkambow** [comment]
At the current stage - we may close this articles - FYI. 

CC @raboba2re 

CC @ahmadmardeni1 @LinusMuema 

Please correct me if Im wrong.

**Comment by Taiwrash** [comment]
> @Taiwrash
> 
> Thank you very much for submitting your 2nd article.
> 
> FYI at a quick glance this article seems extremely basic - it seems like it could be improved quite a bit.
> 
> Again we want to make sure this goes beyond any basic explanation.
> 
> What is the pain point this article is trying to solve - what is the reader learning here that they can not get anywhere else.
> 
> 🤔

This is truly basic to a certain level but what this article solves is curation of the contents. There is no where the whole content explained be gotten in one place and secondly I discovered in my circle of **developers community** people find it difficult to understand those basics which makes them ask questions around it several times especially those that are learning networking, hardware maintenance and others. That was why I choose it as a challenge to explain it in a very simple and straightforward language. This is not justify my actions but to explain the inspiration behind the article. Thanks for your feedback @hectorkambow

**Comment by Taiwrash** [comment]
> At the current stage - we may close this article - FYI.
> 
> CC @raboba2re
> 
> CC @ahmadmardeni1 @LinusMuema
> 
> Please correct me if Im wrong.

Cool, I will like to hear others opinions. But my point still remain **curativity** thanks

**Comment by raboba2re** [comment]
> 
> 
> At the current stage - we may close this article - FYI.
> 
> CC @raboba2re
> 
> CC @ahmadmardeni1 @LinusMuema
> 
> Please correct me if Im wrong.

@hectorkambow I went through the article briefly and I found out that you are right as some part of it were covered in [Introduction to Internet Protocol and Subnetting](https://www.section.io/engineering-education/introduction-to-subnetting/) and [Understanding Dynamic and Static Routing](https://www.section.io/engineering-education/understanding-static-dynamic-routing/).  But as @Taiwrash  rightly said, **"There is no where the whole content was explained"**. 
As such, whether the PR is  to be close or Merged, either of this decision is right, but if the PR is to be reviewed, I will work with @Taiwrash  to suggests more content to be added for the  article to stand out. 
Thank you.
>> CC @ahmadmardeni1 @LinusMuema

**Comment by ahmadmardeni1** [comment]
@hectorkambow Correct Hector, this article is extremely basic - the readers will expect a higher value.

It seems like a helpful topic but we need to improve it and add some unique ideas, the concepts here can be found easily in a lot of blogs or YouTube short videos. 

Can you write about an advanced topic? Maybe about Flsm, Vlsm, Ospf, Rip, with classful and classless. @Taiwrash 
We already have [this topic](https://github.com/section-engineering-education/engineering-education/pull/2992) covering static and dynamic routing, you can build on top of it using Packet Tracer.

Packet tracer should be used in your article to be approved because we can't focus on Hardware.

**Comment by Taiwrash** [comment]
> @hectorkambow Correct Hector, this article is extremely basic - the readers will expect a higher value.
> 
> It seems like a helpful topic but we need to improve it and add some unique ideas, the concepts here can be found easily in a lot of blogs or YouTube short videos.
> 
> Can you write about an advanced topic? Maybe about Flsm, Vlsm, Ospf, Rip, with classful and classless. @Taiwrash
> We already have [this topic](https://github.com/section-engineering-education/engineering-education/pull/2992) covering static and dynamic routing, you can build on top of it using Packet Tracer.
> 
> Packet tracer should be used in your article to be approved because we can't focus on Hardware if you choose to use a real router.

Thanks for your feedback @ahmadmardeni1 do you suggest I should improve this article or pick another topic among the suggested one. I will like to understand you better.

**Comment by ahmadmardeni1** [comment]
Pick an advanced topic. @Taiwrash

**Comment by hectorkambow** [comment]
Great feedback - thank you Gents. 

Thank you @Taiwrash for understanding - as we strive to create and curate the best quality content for the larger developer community as a whole. 

If you plan to submit a new PR/and topic form - feel free to close this one 👍 

This ultimately goes a long way to improve and elevate your portfolio to showcase to potential future employers - so the higher level quality - the higher level portfolio as well 🚀  

Keep up the great work everyone

**Pull request closed without merging**
