### PR TITLE
CopyLeaks Automation Test

### PR DESCRIPTION
**Pull request by louisefindlay23**
This is a test article to test auto comment functionality to plagiarism checks.

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Posted comment

**Comment by louisefindlay23** [comment]
Plagiarism Report downloaded. View at: http://enged-plagiarism-checker.louisefindlay.com/1646223838565.pdf

**Comment by louisefindlay23** [comment]
Plagiarism Report downloaded. View at: http://enged-plagiarism-checker.louisefindlay.com/1646223901592.pdf

**Comment by louisefindlay23** [comment]
Plagiarism Report downloaded. View at: http://enged-plagiarism-checker.louisefindlay.com/reports/1646224163288.pdf

**Comment by louisefindlay23** [comment]
Plagiarism Report downloaded. View at: http://enged-plagiarism-checker.louisefindlay.com/reports/1646215886415.pdf

**Comment by louisefindlay23** [comment]
Plagiarism Report downloaded. View at: http://enged-plagiarism-checker.louisefindlay.com/reports/1646216037099.pdf

**Comment by hborrelli1** [comment]
@louisefindlay23 thanks for jumping on this feature and making some progress! A few notes/thoughts on this work:

- Not sure if you were following the work @lalith1403 and I did on the automated comments feature. I don't think we can use Github actions (more specifically `secrets.GITHUB_TOKEN`) on forked pull requests, due to security issues. Because of this, we had to re-create the feature using Github Probot. I think this will be the case for this feature as well. 
- Another thing @hectorkambow helped bring to my attention is that we are being charged for each plagiarism check. So with this in mind we will want to be strategic about when we trigger a plagiarism check. I can foresee scenarios where students create a PR with unfinished/unpolished work. In that case we would not want to automatically trigger the plagiarism checker. Instead, maybe we can use the addition of a label as the actual trigger once we determine that it is in a place that we deem acceptable to trigger that process. 

Thanks again for taking initiative and jumping on this feature. Let me know if you have any other questions or concerns!

**Comment by louisefindlay23** [comment]
Plagiarism Report downloaded. View at: http://enged-plagiarism-checker.louisefindlay.com/reports/1646243414957.pdf

**Comment by louisefindlay23** [comment]
Plagiarism Report downloaded. View at: http://enged-plagiarism-checker.louisefindlay.com/reports/1646243414957.pdf

**Comment by louisefindlay23** [comment]
Plagiarism Report downloaded. View at: http://enged-plagiarism-checker.louisefindlay.com/reports/1646243414957.pdf

**Comment by louisefindlay23** [comment]
Plagiarism Report downloaded. View at: http://enged-plagiarism-checker.louisefindlay.com/reports/1646243414957.pdf

**Comment by louisefindlay23** [comment]
Thanks, @hborrelli1. Great advice.

1) Just discovered that GitHub has its own built-in Webhooks functionality so will use that instead of GitHub Actions. Just reworking the code in my own forked repo atm to work via this automation.

2) Yeah, it could get quite expensive (plus API plagiarism credits are unfortunately separate from web UI ones - using sandbox mode for now and when ready have about 50 free test credits to use). Perhaps using our current plagiarism check needed label?

**Comment by hborrelli1** [comment]
> Thanks, @hborrelli1. Great advice.
> 
> 1. Just discovered that GitHub has its own built-in Webhooks functionality so will use that instead of GitHub Actions. Just reworking the code in my own forked repo atm to work via this automation.
> 2. Yeah, it could get quite expensive (plus API plagiarism credits are unfortunately separate from web UI ones - using sandbox mode for now and when ready have about 50 free test credits to use). Perhaps we could use our current plagiarism check needed label?

Awesome! I think the existing label could work. Unless you think it could cause confusion with the community if students are adding that label without knowing about the adjustments we're making. You might have a better grasp on that than I do.

**Comment by louisefindlay23** [comment]
Yeah, right now, plagiarism check needed is pretty much added by default but we've talked about CMs looking over articles for glaring issues and then adding the ready for review label (and then peer reviewers would assign articles) to help tackle this issue so this could be an adaptation.

**Repo Link:** https://github.com/louisefindlay23/enged-plagiarism-checker 

Is there an EngEd subdomain (enged-automations.section.io?) we could use to run these automation experiments, @hborrelli1?

**Comment by hborrelli1** [comment]
> Is there an EngEd subdomain (enged-automations.section.io?) we could use to run these automation experiments, @hborrelli1 since some testing would need to be done in the main repo or would that be managed by yourself once automations have been finished and approved?

Do you mean to host the Express app you built for testing purposes? If so, I'm wondering if you can just use something like Heroku in the meantime? I'm thinking that once we can confirm it's working, we can think about where to host the service.

**Comment by louisefindlay23** [comment]
I should have clarified a bit, I was referring to the domain name (since I'm using one of my own subdomains) but can look into it like you say once we've confirmed it all works.

@hborrelli1, I believe I have a working version on my own EngEd Forked repo. Applying the `needs plagiarism check` label to any open PR runs the check on the `index.md` file and posts a comment on the PR with a link to view the report. I've been using [this issue](https://github.com/louisefindlay23/engineering-education/pull/23) to test. Using sandbox mode (to not use any credits) so the report details are their example but everything seems to work as expected.

**Comment by EssyWanjira** [comment]
Wow, is this a feature to automatically run plagiarism immediately after a PR is opened? If so guess will speed up :rocket:

**Comment by hborrelli1** [comment]
@louisefindlay23 I met with some of the team members about this feature and some of the questions you've outlined. Unfortunately I don't think this solution is something we can implement as is for a number of reasons. I think the main issues here revolve around security compliance and cost associated with the API. Our company requires a certain level of security compliance and we will need to dig into this a bit deeper to determine what is acceptable or not. As for pricing I think we will need to come up with more robust process to trigger the API requests - for example, we are hesitant to open up this capability if anyone can just add a label triggering a API request ($) - also a bit of security concern here. 

However, we really appreciate the awesome work here and don't want to let it go to waste! With that being said, this automation process could potentially be implemented with much less overhead if it did not require the use of a subdomain/webhook, and hosting a node app. 

If you'd like to continue working on this, we're curious if there are other options to achieve this without the use of a webhook/node app? Do you know if that would be possible? 

Additionally, this process has brought to our attention that going forward we will need to have a bit more formal approach to proposing, defining the scope, and approving contributed features such as this one. Thanks for bearing with us as we work on improving this process.

**Comment by louisefindlay23** [comment]
Hi, @hborrelli1. Thanks for the detailed information. It's really helpful in knowing what you're looking for in terms of the infastructure of feature requests and development considerations.

The CopyLeaks API works via webhooks so I believe a web app is required or could be possibly implemented through a serverless approach (such as [RequestBin](https://requestbin.com/)) which could be explored.

Have PMed you on Slack about ways the application could be secured/altered.

**Comment by hectorkambow** [comment]
closing for now - we can reopen and reference and we start to work on the copyleaks API again

**Pull request closed without merging**
