### PR TITLE
Getting started with Strapi Node.js API CMS

### LINKED ISSUE #1852: Getting started with Strapi - A Node.js API CMS
### Proposed title of article
Getting started with Strapi - A Node.js API CMS

### Introduction paragraph (2-3 paragraphs):
Node.js is one of the most used backend technologies used today. Node.js can be used to build many types of apps and APIs.

Strapi is an open-source Node.js headless content management system (CMS) for building customizable APIs. It allows developers to focus on shipping software instead of coding software by providing an API management systems. Using an easy to use interface, devs can create and expose APIs without much coding.

Strapi allows developers to quickly build the backend logic using customizable routes, plugins, components and content types. It can be integrated with major SQL
 and NO-SQL databases eg. MongoDB.

In this tutorial, we are going to create a fully functional API using Strapi.

### Key takeaways: 
By the end of this tutorial, the reader will be able to:
1. install and setup Strapi
2. Configure database for use with Strapi
3. Use Strapi content types, users, components, etc.
4. Set roles and permisiions
5. Publish and consume the API

### References: 
N/A

### PR DESCRIPTION
**Pull request by geoffrey45**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1852

### CODE REVIEW

**Review by adrianmurage — CHANGES_REQUESTED** [review]
@geoffrey45 Great article!
I left a note on an image that I think you should update.

**Comment by geoffrey45** [comment]
@adrianmurage Thank you for pointing out the issues. Check out my latest commit.

**Review by adrianmurage — APPROVED** [review]

**Comment by adrianmurage** [comment]
@hectorkambow 
This is ready for final review

**Comment by hectorkambow** [comment]
plagiarism check done

**Pull request merged**
