### PR TITLE
HOW SWEET IS KUBERNETES?

### PR DESCRIPTION
**Pull request by wizardcalidad**
I created a **How sweet is Kubernetes article.**
How sweet is Kubernetes is a topic that explains the major concept of Kubernetes to a beginner, intermediate, and probably a professional level developer or DevOps engineers better. It also touches microservices architecture and a basic implementation of it using Fleetman Tracker Application by Richard Chesterwood with docker images curled from his repository on dockerhub.com.
It is surely an interesting read.
Thanks.

### CODE REVIEW

**Review by BrianaNzivu — CHANGES_REQUESTED** [review]
Hey Qoyum Yusuf 👋🏾. First things first, welcome to Section - EngEd🎉. We are happy to have you on board. My name is Briana and I will review your article. Together, we will polish your article to make it near perfect if not perfect for publishing. 
I do hope you read the documentation on how to [submit](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/UPLOAD_INSTRUCTIONS.md) an article. We normally just require an index.md file and pictures - that is the reason why I am telling you to delete the other files. So what are you supposed to do if you want to display some code illustrations?? Simple - just have them inside your index.md.
So we can start with this small corrections as I review the main article. 🚀 

Regards.

**Comment by wizardcalidad** [comment]
Okay, thanks a bunch

**Review by wizardcalidad — COMMENTED** [review]
All recommended files has been deleted.
Thanks.

**Comment by BrianaNzivu** [comment]
Hello :wave: Qoyum Yusuf , I hope you are well.
As you know, we were working on a new structure for our EngEd Repo, which has led to a slight slow down of article publishing. Everything is almost ready now.
In order to publish your article as soon as possible, please do the following:
- Download the most recent files off this PR (Make sure to pick the latest one with my revisions and edits).
- Delete your article directory from the *articles* folders.
- Do a git pull (take a look at the new structure of the repo after a git pull).
- Upload your article files to the [new *articles* folder inside *content*](https://github.com/section-engineering-education/engineering-education/tree/master/content/articles).
Ping me via Slack or here if you have any problems.

Your patience is really appreciated.

**Comment by wizardcalidad** [comment]
Will do, thanks!

**Comment by hectorkambow** [comment]
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

**Comment by wizardcalidad** [comment]
> Thank you v much for your patience as we worked through our Repo re-structuring process.
> 
> The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions).
> 
> With most of the changes coming to completion - we will be sure to get your article published asap.
> 
> Thank you again - and we are looking forward to more amazing articles.

does that mean I should wait and not implement BrianaNzivu comment again?

**Comment by hectorkambow** [comment]
> > Thank you v much for your patience as we worked through our Repo re-structuring process.
> > The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions).
> > With most of the changes coming to completion - we will be sure to get your article published asap.
> > Thank you again - and we are looking forward to more amazing articles.
> 
> does that mean I should wait and not implement BrianaNzivu comment again?

?? Not sure I follow - you should download the latest file from this PR _ including any edits suggested by the peer reviewer.

**Comment by BrianaNzivu** [comment]
Hey @wizardcalidad .
As stated above we were migrating to the new Hugo theme and so since you submitted you PR before then we would have experienced some merging conflicts.
You can follow the steps I provided or you can delete this PR and open a new one which will have the updates.
I'd prefer you do the latter since it's easier and straight foward.
Please ping me on your new PR so that we can finish this review process ASAP.
Regards. 🚀

**Pull request closed without merging**
