### PR TITLE
Cryptography In Computer Networking

### PR DESCRIPTION
**Pull request by awinomackrine**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by jumamiller** [comment]
@awinomackrine, welcome to the Section.io community. I'll review your article!

**Comment by jumamiller** [comment]
Nice article, add author page and a hero image before we continue!

**Comment by awinomackrine** [comment]
Thank you, Juma I will push them today!

**Comment by awinomackrine** [comment]
Hello, Juma, I've made all the changes.

**Comment by jumamiller** [comment]
@awinomackrine, thank you for making the requested file structure changes, always remember to create your article file in the *articles* directory.

**Comment by jumamiller** [comment]
Let's now proceed to your article formatting.
1. I realized you've several incomplete sentences plus images from third parties.
2. You quoted Wikipedia as your source of information in almost 90% of your links which for this technical article I'dn't recommend.
3. Generally, I would start reading your article and get lost on what's happening. I would recommend you work on the flow.

**Comment by awinomackrine** [comment]
@jumamiller, I've made all the changes. Thank you!

**Comment by jumamiller** [comment]
@awinomackrine, thanks for making the requested changes, it's a great article for the start.
@hectorkambow, this article is ready for final review(a new contributor).

**Comment by hectorkambow** [comment]
@jumamiller  just an FYI -let be sure we are not forgetting the plagiarism check before a final label. 👍 (for any potentia future)

**Comment by hectorkambow** [comment]
[Cryptography In Computer Networking #1815.pdf](https://github.com/section-engineering-education/engineering-education/files/6268024/Cryptography.In.Computer.Networking.1815.pdf)

👋 Good afternoon @awinomackrine - and welcome to the EngEd program.
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our [resources page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) to see more info on plagiarism and what is considered as such.

**Comment by awinomackrine** [comment]
@hectorkambow, I've made changes, kindly check again

**Comment by owinowendy** [comment]
@ahmadmardeni1, could you add ready for final review label to this article.
cc @hectorkambow

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by hectorkambow** [comment]
please review any final edits made during my review to incorporate into future articles if applicable @awinomackrine

**Pull request merged**
