### PR TITLE
Deploying Docker Containers to Kubernetes Cluster

### LINKED ISSUE #2210: Deploying Docker Containers to Kubernetes Cluster
### Proposed title of article
Deploying Docker Containers to Kubernetes Cluster

### Introduction paragraph (2-3 paragraphs):
Docker is a tool designed to make it easier to create and deploy and run applications using containers such that a developer is allowed to package an application, all its libraries and dependencies as one during deployment.

While Docker runs on a single node, Kubernetes is meant to run across a cluster. It is more expensive and it's meant to coordinate clusters of nodes at a skinny production to enhance efficiency.

In this article I will explain a step-by-step procedure of deploying Docker containers to a Kubernetes cluster.

### Key takeaways: 
1. Building a Docker based app using flask
2. Using Load Balancers to expose containers with Kubernetes
3. Deploying a Docker container to Kubernetes cluster

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by bastian-zab**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
This fixes #2210

### CODE REVIEW

**Comment by bastian-zab** [comment]
@paulodhiambo , I finished the article you can give it a review.

**Comment by paulodhiambo** [comment]
@bastian-zab amazing article. Check on the changes I made and improve on your next article.

Cc: @hectorkambow

**Comment by hectorkambow** [comment]
@bastian-zab great work gents 🚀 
Nice tutorial -easy to follow along. 

cc @paulodhiambo

**Comment by hectorkambow** [comment]
FYI @bastian-zab the % for the plagiarism check was right on the border of what we typically accept - it would be good to run it through one before submitting (for future ones) we strive for 10% or less.

**Pull request merged**
