### PR TITLE
A Beginner Guide on How to Solve a  System of Linear Equations using Gaussian Elimination Algorithm

### LINKED ISSUE #6474: Solving System of Linear Equations using Gaussian Elimination Algorithm
#### Article introduction

A system of linear equations is a collection of one or more linear equations involving the same set of variables. This is a day-to-day activity encountered in machine learning where the data under consideration involve more variables contributing to the sane output variable.

There are various techniques for solving this problem, where some are complex and others easy to understand and implement. The Gaussian Elimination method is one of the best approaches in solving these systems. 

How do we solve a system of linear equations using the Gaussian Elimination Algorithm?
- First, we create a matrix of the coefficients of the linear system.
- We then assign A to the coefficient matrix created above, X as a vector of variables and b as a vector of solutions.
Using matrices A and b, we create an augmented matrix, i.e., attach b to matrix A as the last column.
  
We perform some operations on this matrix to make it simple to solve for unknowns. Some of these operations one can do are;

  1. Change the order of the rows
  2. Scale-up a row, i.e., multiplying with a constant
  3. To eliminate particular values, you can multiply one row with a constant and add the output to another row.
   
 So using this operation, we will learn how to reduce a system of linear equations using the Gaussian Elimination Algorithm.

So, how does the Gaussian Elimination Algorithm work?
In the first iteration, using our augmented matrix, make the first value of the first row an identity and using the $3^{rd}$ operation we outline above, you make all the values below it zeros. This first value we preserve as an identity is called a pivot.

In the second iteration, make the first value after the zero identity and, as we did in the first iteration, make all values below its zeros.

Repeat this until we obtain an upper triangular matrix.

We then create a simplified system of linear equations from this triangular matrix, which we solve by back substitution. Now, this new system of equations is usually much easier to solve than the original system.

 In this article, we will cover the Gaussian Elimination Algorithm in detail.

#### Key takeaways 
The learner will know:
- What's a system of linear equations
- How to create a matrix of coefficients from a system of linear equations.
- How to create an augmented matrix
- Finally, the learner will be able to carry out all operations involved in reducing a matrix using the Gaussian Elimination algorithm and how it's performed in R and Python.

#### Article quality
This article is meant to deliver clarity of the content by deeply explaining each concept in detail. To make it unique further, we will provide an implementation using both R and Python, and thus the learner will have a choice of the implementation session to settle by.
#### References
N/A

### PR DESCRIPTION
**Pull request by StacyJelagat**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6474

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Plagiarism check complete

**Comment by StacyJelagat** [comment]
Hi @hectorkambow,
I think in the email we were to write on the approved topics and also I submitted the PR before May 2nd. Why this now?

**Comment by hectorkambow** [comment]
@StacyJelagat 
Just seeing your comment - the white label is just to indicate that the article was submitted after the program transition announcement.

**Comment by hectorkambow** [comment]
Our team has been working diligently to clear the backlog and we should be getting this pull request ready to be published next week 🚀

**Comment by hectorkambow** [comment]
@StacyJelagat 

Just noticed that you have not included any author details (to create your author profile). 

This is how your articles will be listed under your profile. 

In order to publish the article we would need your author details - please see the new contributor folder for more info on how to submit.

**Comment by hectorkambow** [comment]
@paulodhiambo  

Quick question - has this PR gone through a tech review? 

I'm happy to go over the prelim review on my end. 👍

**Comment by paulodhiambo** [comment]
Hello @StacyJelagat please add your author bio.

**Comment by hectorkambow** [comment]
@StacyJelagat 
You'll be able to see your live published article on the site.

To give your article a boost in page engagement - be sure to share it across your social site (LinkedIn/Twitter) and tag the EngEd program so we can also share it and give it some traction/exposure as well!

If you have not done so already - consider adding a skill section to your author page. This will go a long way for potential future employers.

NOTE: Also, take into consideration that you can add any other past projects of yours: videos, talks, tutorials, articles (on ANY other site) - you can add them to your EngEd profile.

Think of the EngEd profile as your one-stop shop for everything you do in DEV - making it easier for you to share all your accomplishments when you go out for an interview or employment opp.

It can be from any blog site (or site in general).

Let me know if you have any questions moving forward.

**Pull request merged**
