### PR TITLE
End-to-end speech recognition guide in Python

### LINKED ISSUE #5583: End-to-End speech Recognition Guide in Python
### Topic Suggestion
End-End speech Recognition Guide in Python

#### Proposed title of the article
End-End speech Recognition Guide in Python

#### Proposed article introduction
Speech recognition is the process of enabling computers to identify and respond appropriately to human voices or other sounds. In the tutorial, we will discuss an End-End Speech Recognition Guide in Python. Companies like Amazon uses speech recognition to help their customers in product finding. Even speech recognition allows physically disabled people, the visually impaired, or young children to interact with them, with the added benefit of not requiring a graphical user interface (GUI). By seeing speech recognition everywhere why not be possible in making your system. This tutorial guides show some working principles of speech recognition and the different speech recognition used.
#### Key takeaways 
By the end of this tutorial, the reader will be able to gain skills in:
- Working principle of speech recognition 
- Packages involved in speech recognition
- How the packages are used in speech recognition
- Top projects having text to speech recognition

#### Article quality
The article is unique since more sites only show speech recognition building, they don't show steps or guides towards building speech recognition.
#### References
N/A

### Conclusion
By completing this article, the learner will have basic knowledge in speech recognition, packages involved in speech recognition, the working principle,s and top projects having speech-to-text Recognition.

### PR DESCRIPTION
**Pull request by josephotienoowino**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5583 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by josephotienoowino** [comment]
any reviewer assigned?

**Comment by josephotienoowino** [comment]
any reviewer assigned?

**Review by srishilesh — CHANGES_REQUESTED** [review]
@josephotienoowino 

Looks like we have 2 index files. Please consider removing `content/articles/index.md`.

On a quick glance at your PR, make sure to follow these general guidelines that allows faster review process by the reviewers:
- Break down large paragraphs into smaller ones
- Add necessary reference links/sources
- Perform a grammar check
- Explain code snippets/add comments
- Add images/examples as needed
- Add a GitHub repo URL containing full working code.
- Start markdown headers with `###`
- Add output for code snippets wherever needed.

Thanks.

**Comment by josephotienoowino** [comment]
Changes done!

**Comment by Kayere** [comment]
Hello @josephotienoowino
 Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[End-to-end speech recognition guide in Python #5855 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7822178/End-to-end.speech.recognition.guide.in.Python.5855.Copyleaks.Report.pdf)

**Comment by srishilesh** [comment]
Hi @josephotienoowino ,

Just checking out if you need any help with the PR.

You're supposed to make the plagiarism corrections, and ping me.

**Comment by josephotienoowino** [comment]
I will makes changes tomorrow and submit changes

**Comment by josephotienoowino** [comment]
> Hi @josephotienoowino ,
> 
> Just checking out if you need any help with the PR.
> 
> You're supposed to make the plagiarism corrections, and ping me.

Changes done.

**Pull request closed without merging**
