### PR TITLE
Creating a Nested Scroll Music Player App in Jetpack Compose

### LINKED ISSUE #6432: [Android] Creating a Nested Scroll Music Player App in Compose
#### Proposed title of article
Creating a Nested Scroll Music Player App in Compose

### Writing sample(s): 
My previous articles/PRs can be found [here](https://github.com/section-engineering-education/engineering-education/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Anonimdiana+is%3Amerged)

#### Proposed article introduction
Nested scroll is one of the relatively technical features to implement in an app. With Jetpack Compose, we can achieve this by combining scrollable components with different orientation as items of the other or by making use of the NestedScroll API offered by Compose.
In this tutorial, you'll learn how to implement a nested scroll functionality in a music player app using the earlier mentioned approach as it is easier to implement, customize and handle states.

Below is a **Figma** design showing how the app should look like:
music-app-design

#### Key takeaways 
By the end of this tutorial, the reader will be able to:
1. Create and combine multiple composables to **form a nested scroll**
2. **Preload Audio streams** from the internet/local storage using ExoPlayer APIs asynchronously
3. **Animate transitions** between UI components for a smooth visual effect
4. Handle music states using **compose gestures**

#### Article quality
In the past few weeks, I've been trying to implement the above described feature in my project. Unfortunately, there seems to be limited docs/guides about such features in Compose. I'm convinced that this tutorial will add value to the community and save readers significant amount of time and struggle!

#### References
N/A

### PR DESCRIPTION
**Pull request by nonimdiana**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6432

### CODE REVIEW

**Comment by hectorkambow** [comment]
@Ericgacoki 
I see you have too many PRs assigned at one time. 👀 

Lets please be sure to get the ones that are ready for final published by pinging the CM team to get those completed before assigning more PR.

**Comment by lalith1403** [comment]
plagiarism check done ✔️

**Review by Ericgacoki — APPROVED** [review]
Nice tutorial 👌🏿 Keep it up!

**Comment by hectorkambow** [comment]
Adding a white label because the topic issue was re-opened on April 14th

**Comment by nonimdiana** [comment]
Hello @hectorkambow, What does the `"white label"` label mean? 🤔 🤔

**Comment by hectorkambow** [comment]
👋  

@nonimdiana 

White label indicates that the PR was submitted/approved after the payout transition announcement. 

It means the PR will not be eligible for a payout.

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
@nonimdiana 👏  Nicely done.

You'll be able to see your live published article on the site (in about 30 mins).

To give your article a boost in page engagement - share it across your social site (LinkedIn/Twitter) and tag the EngEd program so we can also share it and give it some traction as well! 
(we will try and do the same once we feature it).

**_If you have not done so already - consider adding a skill section to your author page. This will go a long way for potential future employers._**

**Pull request merged**
