### PR TITLE
[Duplicate #6145] Pathlib vs OS Modules for File and Directory System Operation utilizing Comparable Scenarios

### LINKED ISSUE #5644: (Python) Pathlib vs OS Modules for File and Directory System Operation utilizing Comparable Scenarios
## Pathlib vs OS Modules for File and Directory System Operation utilizing Comparable Scenarios

In this article, we will run through different viable contexts to discover an agreeable decision of utilizing either Pathlib or OS for file system operation. Also, I will utilize this article to perform distinguished tasks for significant reference these tasks are not restricted to writing and reading a file, describing a document information, renaming files, creating directories and so on

The thought behind this article is to clear the examining choice knowing where every one of them fit in when working with File System Operation neither censuring a specific module, additionally to develop a quick consulting reference that is based on File System Operation.

### Key Takeaway
- It will help beginners in python or data analytics to confidently propose the right file system operation module.
- It will provide a simple road map for a quick guide at whatever point individuals intend to work with files.
- It will theoretically enhance beginners' comprehension of file system operation.
- It will eliminate the manual way of working with file system operations for individuals while working on a project.
- It will teach beginners how to reference an object in python, and this is pattern is called composition.

### Conclusion
At the end of this article I believe individuals would have understood the difference between Pathlib and OS, also I believe individuals would have been able to know where each module fit in and individuals would have been more familiar with File System Operation using two different types of File System Operation module.

Reference
[OS documentation](https://docs.python.org/3/library/os.html#querying-the-size-of-a-terminal)
[Pathib documentation](https://docs.python.org//pathlib.html)

### PR DESCRIPTION
**Pull request by akenz1901**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5644

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by akenz1901** [comment]
@srishilesh 
I have made the corrections.

**Comment by srishilesh** [comment]
Duplicate of #6145

**Comment by srishilesh** [comment]
Hey @akenz1901 ,

Thanks for making the changes. It looks better than your previous PR.

Let's wait for the plagiarism check to be done.

Meanwhile, I'll proceed with my tech review.

Thanks.

**Comment by akenz1901** [comment]
@srishilesh 
Thanks so much!!!

**Comment by louisefindlay23** [comment]
Plagiarism check complete

**Comment by akenz1901** [comment]
@louisefindlay23 
Alright, thanks so much!!

**Comment by srishilesh** [comment]
I'll complete my final review by EOD

**Comment by srishilesh** [comment]
Hey @akenz1901 ,

I've partly reviewed your PR. I found some minor markdown formatting changes (specially the headers).

Please go through the changes in my [last commit](https://github.com/section-engineering-education/engineering-education/pull/6573/commits/cd0d586a1b89b477e85b55b02a11e750530a51b0). Do the same changes for the remaining article (wherever needed).

A summary of what I've done above:
- Remove any additional new lines in the code snippets
- Make the `Output:` bolder using `**Output:**`
- For each operation like `Removing a file` the markdown header must be `####`. And, for the subsequent examples in OS modules or Pathlib modules should have `#####`.
- Update the table of contents.

I believe this shouldn't take much time for you. Ping me when it's ready.

Thanks.

**Comment by akenz1901** [comment]
> I'll complete my final review by EOD

Thanks, @srishilesh

**Comment by akenz1901** [comment]
> Hey @akenz1901 ,
> 
> I've partly reviewed your PR. I found some minor markdown formatting changes (specially the headers).
> 
> Please go through the changes in my [last commit](https://github.com/section-engineering-education/engineering-education/pull/6573/commits/cd0d586a1b89b477e85b55b02a11e750530a51b0). Do the same changes for the remaining article (wherever needed).
> 
> A summary of what I've done above:
> 
> * Remove any additional new lines in the code snippets
> * Make the `Output:` bolder using `**Output:**`
> * For each operation like `Removing a file` the markdown header must be `####`. And, for the subsequent examples in OS modules or Pathlib modules should have `#####`.
> * Update the table of contents.
> 
> I believe this shouldn't take much time for you. Ping me when it's ready.
> 
> Thanks.

@srishilesh Thank you so much for this clarification. i will work on it ASAP.

**Review by akenz1901 — COMMENTED** [review]
Correction made

**Comment by akenz1901** [comment]
Hi @srishilesh 
Thanks for yesterday, I have done the spotted corrections throughout the article.

**Review by srishilesh — APPROVED** [review]
Hey @akenz1901 ,

I've made some major changes to formatting and flow. Make sure to go through them carefully before starting your next article. Since this is your first article at Section, the review process was a little less stricter.

Too many concepts were repetitive. You must avoid them.

Also, make sure not to force push the commits like you have done here:
image

My previous 2 commits are missing. Not an issue now, since you've worked on the revisions over mine. So, my changes were not lost.

Moving for the final review. You must work hard on the formatting and flow aspects.

Thanks.

**Comment by akenz1901** [comment]
> Hey @akenz1901 ,
> 
> I've made some major changes to formatting and flow. Make sure to go through them carefully before starting your next article. Since this is your first article at Section, the review process was a little less stricter.
> 
> Too many concepts were repetitive. You must avoid them.
> 
> Also, make sure not to force push the commits like you have done here: image
> 
> My previous 2 commits are missing. Not an issue now, since you've worked on the revisions over mine. So, my changes were not lost.
> 
> Moving for the final review. You must work hard on the formatting and flow aspects.
> 
> Thanks.

@srishilesh Thank you so much, I learned a lot from the various corrections which I believe that it will guide me through all my subsequent articles.
I so much appreciate it all.

**Comment by akenz1901** [comment]
> Hey @akenz1901 ,
> 
> I've made some major changes to formatting and flow. Make sure to go through them carefully before starting your next article. Since this is your first article at Section, the review process was a little less stricter.
> 
> Too many concepts were repetitive. You must avoid them.
> 
> Also, make sure not to force push the commits like you have done here: image
> 
> My previous 2 commits are missing. Not an issue now, since you've worked on the revisions over mine. So, my changes were not lost.
> 
> Moving for the final review. You must work hard on the formatting and flow aspects.
> 
> Thanks.

I will try not to ever force push anymore. I'm so grateful.

**Comment by ahmadmardeni1** [comment]
A really long tutorial 😄 Good work team. @akenz1901 @srishilesh

**Comment by hectorkambow** [comment]
@akenz1901  Please reach out to me via Slack DM asap 👍  

Thank you

**Comment by akenz1901** [comment]
@ahmadmardeni1 😄 Thanks so much, I love writing to the best details.

**Comment by akenz1901** [comment]
@ahmadmardeni1 😄 Thanks so much, I love writing to the best details.

**Comment by akenz1901** [comment]
@hectorkambow Okay i will

**Comment by akenz1901** [comment]
@hectorkambow I just sent you a  DM

**Pull request merged**
