### PR TITLE
Broadcasting a private FM radio station using a Raspberry Pi 

### PR DESCRIPTION
**Pull request by ruphus-muita**
This article is a guide on how to broadcast a private FM radio station with the help of a Raspberry Pi.

### CODE REVIEW

**Comment by ruphus-muita** [comment]
Hi @ahmadmardeni1 and @Bayler 
Here is the new pull request

**Comment by Bayler** [comment]
> Hi @ahmadmardeni1 and @Bayler
> Here is the new pull request

Noted @ruphus-muita

**Comment by Bayler** [comment]
This new PR is a duplicate of this closed PR #2971

**Comment by ahmadmardeni1** [comment]
Please @ me when this article is ready for a final review - you will not wait in the queue again. @Bayler

**Comment by Bayler** [comment]
> Please @ me when this article is ready for a final review - you will not wait in the queue again. @Bayler

Noted @ahmadmardeni1 I'll do that when done @Bayler

**Comment by Bayler** [comment]
@ruphus-muita Welcome again to our Section Engineering program. This was an educative tutorial. Of course being your first submission, it came with its own fair share of troubles, especially with the PR issue. But don't worry, you'll get the hang of it with time. Otherwise, see you on the next one!

@ahmadmardeni1 It's all yours.

**Comment by ruphus-muita** [comment]
> @ruphus-muita Welcome again to our Section Engineering program. This was an educative tutorial. Of course being your first submission, it came with its own fair share of troubles, especially with the PR issue. But don't worry, you'll get the hang of it with time. Otherwise, see you on the next one!
> 
> @ahmadmardeni1 It's all yours. 

@Bayler Thank you for the feedback.

**Comment by ahmadmardeni1** [comment]
Congrats on your first article and welcome to Section EngEd @ruphus-muita 🎉

Thank you for the review @Bayler

**Comment by ruphus-muita** [comment]
> Congrats on your first article and welcome to Section EngEd @ruphus-muita 🎉
> 
> Thank you for the review @Bayler 

Thanks @ahmadmardeni1

**Pull request merged**
