### PR TITLE
Controlling Android Phone Using SRCPY

### LINKED ISSUE #3033: Controlling Android Phone on your Computer
Controlling Android Phone Using SRCPY
### Introduction paragraph (2-3 paragraphs):
SRCPY is a free and open-source screen mirroring tool that lets you operate an Android device from a desktop computer running Windows, Mac OS X, or Linux. Genymobile, which also created Genymotion, an Android emulator, is now working on the software.
The following are the steps of installing and running SRCPY  to mirror the Android phone on the computer By mirroring the Android phone on your computer ,you will be  able to control it from your computer.
### Key takeaways: 
* Mirror and control android device on Kali Linux via USB cable. 
* Mirror and control android device on  windows using TCP/IP.  
* Installing srcpy on Kali Linux.
* Remote controlling of an android phone

### References: 
N/A

### PR DESCRIPTION
**Pull request by nancymumbimaina**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #3033 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.
[Controlling Android Phone Using SRCPY #3566.pdf](https://github.com/section-engineering-education/engineering-education/files/7072129/Controlling.Android.Phone.Using.SRCPY.3566.pdf)

**Comment by nancymumbimaina** [comment]
Done @WanjaMIKE

**Comment by nancymumbimaina** [comment]
May i ask what is the progress of this article, please? @M0nicah

**Comment by M0nicah** [comment]
hi @nancymumbimaina 
1. The plagiarism on your article seems to be high even after the update.
2. Try to give your images an alternative text.
3. The headings are only h3. I believe there might be minor topics for the text. Use h3(###) and below.
4. Try and edit the flow of your article too. Go through it, ensure even a beginner can easily flow through. 
Make the paragraphs and sentences shorter and clear and to the point for easy understanding.

Ping me when you are done. 🚀

**Comment by nancymumbimaina** [comment]
@M0nicah 
I have done some changes as you asked and also did some more changes in the article folder.
you may look at my last commit please.

**Comment by nancymumbimaina** [comment]
> hi @nancymumbimaina
> 
> 1. The plagiarism on your article seems to be high even after the update.
> 2. Try to give your images an alternative text.
> 3. The headings are only h3. I believe there might be minor topics for the text. Use h3(###) and below.
> 4. Try and edit the flow of your article too. Go through it, ensure even a beginner can easily flow through.
>    Make the paragraphs and sentences shorter and clear and to the point for easy understanding.
> 
> Ping me when you are done. 🚀

@M0nicah  please attach the plagiarism file

**Comment by M0nicah** [comment]
Great article @nancymumbimaina ,very informative. Please go through the changes I made to help improve the format and flow of your future articles.

@WanjaMIKE, @hectorkambow, Could we run a plagiarism check on this article please?

**Comment by nancymumbimaina** [comment]
@M0nicah Thank you so much

**Comment by ahmadmardeni1** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Controlling Android Phone Using SRCPY #3566](https://github.com/section-engineering-education/engineering-education/files/7136336/New.Scan.12_02.PM.Copyleaks.Report.pdf)

**Comment by nancymumbimaina** [comment]
@M0nicah I have corrected. You may have a look. Thank you.

**Comment by ahmadmardeni1** [comment]
plagiarism check done ✅

**Comment by M0nicah** [comment]
Great article @nancymumbimaina, please review the changes I made in the commits to help improve the flow and format for your future articles. Thanks.

**Comment by WanjaMIKE** [comment]
@nancymumbimaina Kindly, add more content to the article. There are only `624` words which is below the minimum.

**Comment by nancymumbimaina** [comment]
On it , Thanks @WanjaMIKE

**Comment by nancymumbimaina** [comment]
@WanjaMIKE 
Done

**Comment by WanjaMIKE** [comment]
Merged #3566

**Comment by hectorkambow** [comment]
@nancymumbimaina Please contact me via slack 👍

**Comment by nancymumbimaina** [comment]
> @nancymumbimaina Please contact me via slack 👍

I did contact you since I did not receive anything @hectorkambow

**Pull request merged**
