### PR TITLE
Getting started with TinyDB in Python

### LINKED ISSUE #6078: [Language]Getting Started with TinyDB in Python
#### Proposed title of article
     Getting started with TinyDB in python

#### Proposed article introduction
Most of the time while dealing with your projects, you will at some time be required to store data. You could use a SQL database with a server, but that would require you to do a bit of setup. In this article, we'll learn about TinyDB and how to use it to store data in python.

TinyDB is a lightweight document-oriented database optimized for your works on Python.  TinyDB works on all modern versions of Python and PyPy. powerfully extensible: You can easily extend TinyDB by writing new storage or modifying the behavior of storage with Middlewares.

#### Key takeaways 
1. TinyDB overview
2. Installation
3. How to use TinyDB
4. Inserting data in TinyDB
5. retrieving data from TinyDB data
6. Updating and deleting data in TinyDB 

#### Article quality
In this article, I will show novices how to perform data from Crud database. Unlike the existing articles on the same my article will have a complete script that ties everything together. It will also include comments to make the learners understand and follow.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by cathy-254**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6078

### CODE REVIEW

**Comment by cathy-254** [comment]
@Jethro-magaji hello sir, working on it.

**Comment by cathy-254** [comment]
@Jethro-magaji  evening sir, I have committed the requested changes. Have a look please. Thank you

**Comment by WanjaMIKE** [comment]
Please check and correct the plagiarized areas highlighted in the report. Thanks

[New Scan 7_32 AM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/8108897/New.Scan.7_32.AM.Copyleaks.Report.pdf)

**Comment by cathy-254** [comment]
@Jethro-magaji  I have incorporated the change. You may have a look. Thank you

**Comment by Jethro-magaji** [comment]
Hi! @cathy-254 
Can you please add a free stock high resolution hero image 600x400px

**Comment by cathy-254** [comment]
@Jethro-magaji hello sir, I have added a high resolution hero image as requested you can have a look. Thank you

**Review by Jethro-magaji — APPROVED** [review]
Hi! @cathy-254 
Well done for coming up with such an amazing article. Please take note of these corrections to minimize revision next time.
Thanks.

**Comment by cathy-254** [comment]
@Jethro-magaji I have taken note of all the changes made for a better articles on the future. Thank you and I appreciate

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
