### PR TITLE
Django application deployment with Ansible

### LINKED ISSUE #3226: Automating Django deployments with Ansible and Fabric
### Automating Django deployments with Ansible and Fabric
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article a higher ranking.*

### Introduction paragraph (2-3 paragraphs):
[Ansible](https://www.ansible.com) is an open-source software provisioning, configuration management, and application-deployment tool enabling infrastructure as code. Ansible Automation Platform provides an enterprise framework for building and operating IT automation at scale.

[Fabric](http://www.fabfile.org) is a high-level Python library designed to execute shell commands remotely over SSH, yielding useful Python objects in return.

The article will explain how to automate Django deployments from Github to a Google compute engines' virtual machine instance.

### Key takeaways: 
1. Setting up Google compute engines' virtual machine instance.
2. Writing Ansible configuration files.
3. Automating deployments from Github to virtual machine instances.

### References: 
[Introduction to Google compute engine](https://codelabs.developers.google.com/codelabs/cloud-compute-engine#0)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by elizabeth962**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3226

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by okeloviolet** [comment]
@elizabeth962  i'll be reviewing this article.

**Comment by okeloviolet** [comment]
Please add a link to the complete source code.

**Comment by okeloviolet** [comment]
@elizabeth962 please provide instructions on how to execute ansible on the server.

**Comment by elizabeth962** [comment]
@okeloviolet pushing the changes.

**Comment by Kayere** [comment]
Plagiarism check done.

**Comment by elizabeth962** [comment]
@okeloviolet I have made all the changes requested

**Comment by elizabeth962** [comment]
Hello @okeloviolet @Kayere I have made the requested changes.

**Comment by hectorkambow** [comment]
@paulodhiambo  
Can you please finish up the review on this PR. 
or @Kayere  

Thank you

**Comment by Kayere** [comment]
On it @hectorkambow.

**Comment by Kayere** [comment]
@okeloviolet - Were you doing a test review?
cc: @hectorkambow

**Comment by okeloviolet** [comment]
Hello @Kayere I was doing a test review.

**Comment by ahmadmardeni1** [comment]
Jumping on this one.

**Comment by ahmadmardeni1** [comment]
Great tutorial. Please go through the changes I've made. @elizabeth962
Cc @okeloviolet Please do the same.

**Pull request merged**
