### PR TITLE
Advanced form operations In Jetpack compose

### LINKED ISSUE #4762: Advanced form operations In Jetpack compose
### [Android] Advanced form operations In Jetpack compose

Forms are an important part of applications. They help us manage user's data easily.

In Jetpack compose, Material doesn't provide a `Form` composable which means we handle the TextField's operations manually. This includes the state management, validation of the value and getting the TextField's value. As the application and the scope grows, this becomes a menace as you have two write more code for all the fields ergo prone to more errors.

This article aims to guide the user through a DRY approach to handling form fields and how to easily manage state in the TextFields.

#### Key takeaways 
1. Textfield's state management
2. Form validation in Jetpack compose
3. A dry approach to handling form fields
4. Encapsulation in Jetpack compose

#### Article quality
This article goes beyond what is provided in [the documentation](https://developer.android.com/jetpack/compose/state) and adds encapsulation to our composables. The same content isn't provided on other blog sites as compose is still a new framework.

#### References
N/A

### PR DESCRIPTION
**Pull request by LinusMuema**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

this closes #4762

### CODE REVIEW

**Comment by LinusMuema** [comment]
plagiarism check done :heavy_check_mark: 

[Advanced form operations In Jetpack compose #5167 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7608480/Advanced.form.operations.In.Jetpack.compose.5167.Copyleaks.Report.pdf)

**Review by mercymeave — COMMENTED** [review]
A great piece Linus!. Proceeding to tech review.

**Comment by LinusMuema** [comment]
Hi @mercymeave 
Any update on this?

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
Overall nice work

**Pull request merged**
