### PR TITLE
How to solve linear equations using matlab

### LINKED ISSUE #3298: Solving Linear Equations in Matlab
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction 
Mathematical problems involving equations of the form Ax=b, where A is a matrix and x and b are both column vectors are problems in linear algebra, sometimes called matrix algebra. Engineering and scientific disciplines are rife with such problems. Thus, an understanding of their setup and solution is a crucial part of the education of many engineers and scientists. 
MATLAB provides a powerful and convenient means for finding solutions to these problems, but, as we will also see, the solution is not always what it appears to be. We will see in this article how to solve these problems using Matlab since Matlab provides the best environment for solving matrix problems as it is a matrix laboratory 

### Key takeaways: 
- Basic understanding of linear algebra.
- Various ways of solving linear algebra.
- Matlab code for solving linear algebra.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by jumapaul**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3298 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by jumapaul** [comment]
@EspiraMarvin I have made the change in the flow.

**Comment by jumapaul** [comment]
@jerimkaura this article was already reviewed, its the folder structure was wrong and so I had to open a new pr to fix that.

**Comment by jumapaul** [comment]
It was reviewed by @EspiraMarvin

**Comment by EspiraMarvin** [comment]
@ahmadmardeni1  Here is the PR he opened after making folder structure changes.

the closed PR is this one https://github.com/section-engineering-education/engineering-education/pull/3505

It is ready fro final review.

**Comment by EspiraMarvin** [comment]
@jumapaul please  check your slack messages

**Comment by EspiraMarvin** [comment]
@jumapaul you have two introductions and pre-requisites, delete one

**Comment by EspiraMarvin** [comment]
Below is the format of the front matter.

---
layout: engineering-education
status: publish
published: true
url: /solving-linear-equations-using-matlab/
title: Solving Linear Equations Using Matlab
description: This article will look at how to solve linear algebra equations using Matlab. We will also look at the setup of these equations and the different types of equations.
author: paul-juma
date: 2021-08-11T00:00:00-02:25
topics: []
excerpt_separator: 
images:

  - url: /engineering-education/solving-linear-equations-using-matlab/hero.jpg
    alt: Solving Linear Equations on Matlab Hero Image
---
Equations in the form Ax=b in mathematics are linear algebra equations. In such equations, A is a matrix while x and b are column vectors. A matrix is a two-dimensional arrangement of numbers. Such equations are common in engineering and scientific disciplines. 

Thus, understanding the setup of these equations and finding solutions to the problems is an essential skill.



---
Peer Review Contributions by: [Espira Marvin](/engineering-education/authors/espira-marvin/)

**Comment by ahmadmardeni1** [comment]
I don't know what do you mean by the $ sign, and the equations. But take a look at the screenshot below. The website is rendering them like that. @jumapaul 
Please fix the issue.
cc @EspiraMarvin

**Comment by EspiraMarvin** [comment]
@jumapaul  please check the correct syntax for the equations it still shows the $ signs

**Comment by jumapaul** [comment]
@ahmadmardeni1 problem fixed.
cc @EspiraMarvin

**Comment by EspiraMarvin** [comment]
@jumapaul you've not done all check all the instructions in your slack

**Comment by hectorkambow** [comment]
Perhaps it needs a mathjax script to render? (towards the bottom). 

@jumapaul 

cc @EspiraMarvin  & @ahmadmardeni1 

>
<script type="text/javascript" async
    src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
    MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [['$','$'], ['\\(','\\)']],
      displayMath: [['$$','$$']],
      processEscapes: true,
      processEnvironments: true,
      skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'],
      TeX: { equationNumbers: { autoNumber: "AMS" },
           extensions: ["AMSmath.js", "AMSsymbols.js"] }
    }
    });
    MathJax.Hub.Queue(function() {
      // Fix <code> tags after MathJax finishes running. This is a
      // hack to overcome a shortcoming of Markdown. Discussion at
      // https://github.com/mojombo/jekyll/issues/199
      var all = MathJax.Hub.getAllJax(), i;
      for(i = 0; i < all.length; i += 1) {
          all[i].SourceElement().parentNode.className += ' has-jax';
      }
    });
    MathJax.Hub.Config({
    // Autonumbering by mathjax
    TeX: { equationNumbers: { autoNumber: "AMS" } }
    });
  </script>

**Comment by EspiraMarvin** [comment]
@hectorkambow  I tried testing with a mathjax script but it doesn't seem to work.
@ahmadmardeni1  The changes have been made, I think you can look at it now.
 I suggested we use the Matlab code syntax highlighting this way (```matlab) instead.

**Comment by ahmadmardeni1** [comment]
Hey @WanjaMIKE @LinusMuema @Kayere 
This article is a duplicate. Give it a final review, please.

**Comment by LinusMuema** [comment]
On it.....

**Comment by LinusMuema** [comment]
> Below is the format of the front matter.
> 
> layout: engineering-education
> status: publish
> published: true
> url: /solving-linear-equations-using-matlab/
> title: Solving Linear Equations Using Matlab
> description: This article will look at how to solve linear algebra equations using Matlab. We will also look at the setup of these equations and the different types of equations.
> author: paul-juma
> date: 2021-08-11T00:00:00-02:25
> topics: []
> excerpt_separator:
> images:
> 
> * url: /engineering-education/solving-linear-equations-using-matlab/hero.jpg
>   alt: Solving Linear Equations on Matlab Hero Image
> 
> Equations in the form Ax=b in mathematics are linear algebra equations. In such equations, A is a matrix while x and b are column vectors. A matrix is a two-dimensional arrangement of numbers. Such equations are common in engineering and scientific disciplines.
> 
> Thus, understanding the setup of these equations and finding solutions to the problems is an essential skill.
> 
> Peer Review Contributions by: [Espira Marvin](/engineering-education/authors/espira-marvin/)

In future articles, please ensure to add these two to the articles during your review process

**Comment by LinusMuema** [comment]
Hi @jumapaul 
Thanks for this amazing article. It's easy to follow through and quite interactive. Keep up the amazing job.

@EspiraMarvin The review was good. Take note of all the revisions and changes by CMs for better reviews in the future. Also take note of the file and folder names as the generator is case sensitive. Otherwise, great job :rocket:

**Pull request merged**
