### PR TITLE
React Social Authentication using Djoser and Django

### LINKED ISSUE #6116: Social Authentication with Djoser in React Applications.
### Topic Suggestion
Social Authentication with Djoser in React Applications.

#### Proposed title of article
Social Authentication with Djoser in React Applications.

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Djoser is a useful tool that you can use to provide authentication for your applications.It allows one to set up authentication using social accounts such as google, facebook, etc.This article aims at handling social authentication using djoser in a react application.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
1. Understand how authentication using djoser works.
2. Implement social authentication using djoser.

#### Article quality
I will be creating a simple react application that allows one to authenticate using a google account using djoser and django for backend. There will be an option for handling authentication using normal username and password.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by JohnKiguru**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6116

### CODE REVIEW

**Comment by srishilesh** [comment]
Hey @JohnKiguru ,

Thanks for submitting this PR.

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you with the changes to be made.

Meanwhile, we suggest you to go through other approved PRs/published articles to see if you have missed out anything, which might avoid a potential PR closure.

Thanks.

**Review by jerimkaura — COMMENTED** [review]
Hello @JohnKiguru 

Welcome once more to EngEd and thanks for submitting this article for review. Notice the major changes I made to ensure your article is smooth to read. 

Go over the article once more to correct the mistakes that I didn't make. For instance, Google starts with an uppercase letter but for your case, you used a lowercase.

Ensure all the corrections are made to avoid article closure. Ping me when done so that I start the tech review.

**Comment by JohnKiguru** [comment]
Done...

**Comment by louisefindlay23** [comment]
Plagiarism check complete

**Review by jerimkaura — CHANGES_REQUESTED** [review]
Hello @JohnKiguru 

I can find a Hero image for your article. Please find a suitable hero image in case that slipped through so that we get done with this.

Ensure your hero image is about 600*400 pixels. Finish on that then we wrap up.

Thanks!

**Comment by JohnKiguru** [comment]
Done...

**Review by jerimkaura — APPROVED** [review]
Great article @JohnKiguru 

MOving this to the final review.

**Comment by JohnKiguru** [comment]
Thanks

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
