### PR TITLE
Working with Gridbag layout in Java

### LINKED ISSUE #4620: Working with GridBag layout in Java
#### Proposed title of article
Working with GridBag Layout in Java

#### Proposed article introduction
Migrating from building console apps to GUI apps is one of the best fantasies of every budding developer. But the spoiler comes when the GUI isn’t pleasing to the sight.
Layouts are one of the most important parts of building GUI as it determines the looks and feels of our apps. Knowing the best layout manager to use that fits your need is as important as using the layout itself. GridBag layout manager is used to build complicated panels in our Java apps. This is made possible by some of the features it provides which include specifying rows and columns, spans, alignment, etc.
In this tutorial, we will look at the different types of layout managers in Java. And then focus on exploring the GridBag layout manager. We will walk from exploring the methods in the layout, how to use the constraints, and then build a project with the knowledge gained in the tutorial.

#### Key takeaways 
* Understand the basics of layout in Java
* Differentiate between GridBag and other layout managers in Java
* Understand the core concepts of GridBag layout manager
* Know the different approaches to GridBag layout manager in Java
* Know when to use GridBag layout manager as well as the pros and cons
* Build Java apps using GridBag layout manager

#### Article Quality
This article explores some layout managers in Java and then focuses on GridBag throughout the remaining part. It is beginner-friendly and provides an in-depth knowledge of GridBag layout manager by using both screenshots and code snippets to explain all of the components of a GridBag layout, method of usage, GridBag constraints, and many more. 

#### References
N/A

### PR DESCRIPTION
**Pull request by princeibs**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #4620

### CODE REVIEW

**Comment by princeibs** [comment]
@paulodhiambo All changes have been effected. You can now look into the article. Thanks

**Comment by princeibs** [comment]
@paulodhiambo All changes have been effected. You can now look into the article. Thanks

**Comment by princeibs** [comment]
And please let me know if there is any update I have to make to the article. Thanks
@paulodhiambo

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
Overall nicely done - easy to follow along

**Comment by princeibs** [comment]
> Overall nicely done - easy to follow along

Thanks for the feedback  @hectorkambow. I am really encouraged by this

**Comment by hectorkambow** [comment]
@princeibs please reach out via Slack DM 👍

**Comment by princeibs** [comment]
> @princeibs please reach out via Slack DM 👍

Done @hectorkambow

**Pull request merged**
