### PR TITLE
An Overview of ConvNeXt

### LINKED ISSUE #6259: [Machine Learning] An Overview of ConvNext
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

An Overview of ConvNext

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Recently, [Vision Transformers (ViTs)](https://en.wikipedia.org/wiki/Vision_transformer) have superseded ConvNets as the state-of-the-art image classification model. ConvNext aim to argue that with some redesign and by testing the limits of what a pure ConvNet can achieve, you don't need a Transformer achitecture for vision. The ConvNext model is constructed entirely from standard ConvNet modules. ConvNeXt is accurate, efficient, scalable and very simple in design. This tutorial will discuss this new model.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

A couple of things a reader will be able to understand include:
- What is ConvNext?
- How it compares to previous models
- How to implement ConvNext using Keras

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

ConvNext is a new model recently released by Facebook research. It is less that a month old since its release. Not a lot of information is available on it on the internet. This tutorial will explain to our reader what it entails, how it compares to previous models and how to implement it using Keras.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

- [A ConvNet for the 2020s](https://arxiv.org/abs/2201.03545)
- [ConvNext](https://github.com/facebookresearch/ConvNeXt)

### PR DESCRIPTION
**Pull request by smkinyan**
This closes #6259

## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by smkinyan** [comment]
@Bayler Could you please have a look at this PR?

**Comment by Kayere** [comment]
Hello @smkinyan,

 Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[An Overview of ConvNeXt #6384 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/8077998/An.Overview.of.ConvNeXt.6384.Copyleaks.Report.pdf)

**Comment by Bayler** [comment]
@smkinyan We all know how difficult it is reading a computer science research paper with a lot of mathematical jargon. Great work summarizing an entire paper in simple words our readers can understand. Next time you could try add figures as they tend to drive most points home. Otherwise, this is a nice read.

**Comment by LinusMuema** [comment]
Hi @smkinyan 

Awesome job on the article. Keep it up 🚀 

cc: @Bayler

**Pull request merged**
