### PR TITLE
Getting Started With Alpine.js

### LINKED ISSUE #4347: Getting Started With Alpine.js
#### Introduction
Alpine.js is a new, lightweight, JavaScript framework. Alpine.js lets you control your page's behavior right in your markup. It offers almost the same amount of reactivity that Vue.js offers. It is also very light, so your application size is never a worry. Alpine.js is not meant to be a replacement for Vue.js or React.js, it should be used for small applications, or in server-side rendered applications with little JavaScript need. In this article, I'd be building a TODO application to show how to manipulate the DOM easily with Alpine.js

#### Key takeaways 
* What Alpine.js is
* Alpine.js directives and applications

#### Article quality
Being a pretty new framework, there are not too many articles on Alpine.js. The few ones available don't show the applications of its directives.

#### References
1. [Alpine.js docs](https://alpinejs.dev/)
2. [GetBootstrap website](https://getbootstrap.com/)

### Conclusion
This article will get you up and running with Alpine.js.

### PR DESCRIPTION
**Pull request by Zubs**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4347

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Review by BrianaNzivu — CHANGES_REQUESTED** [review]
Hey @Zubs  👋 .

First of all, welcome to Section - EngEd. :tada: 
We are happy to have you here.

Good job on the article. It is a very interesting read.

Just a few changes I need you to make as we continue with the preliminary revisions:
- You can include the table of contents of this article just immediately after the introduction. It is done like this;
[The Covariant Return type] (#the-covariant-return-type)
- Your article has quite a lot of grammatical mistakes and unclear sentences. You can use 
[Grammarly](https://app.grammarly.com/ddocs/1287976180) to correct it. 
- All your images including your avatar image should be scaled down to 600 x 400 px as required. You can use [Befunky](https://www.befunky.com/) to do this.
- Please rename your hero image to `hero.png`.

In case of any question or help needed please do not hesitate to ping me here :smile:.
Also, notify me when you are done.

Regards.

**Comment by BrianaNzivu** [comment]
Tech review done 👍🏾

**Review by BrianaNzivu — APPROVED** [review]
Hey @Zubs 👋 .
The article is a very interesting read. Good job!
Just a few things I'd like to point out:
1.  It is always advisable to submit an article that is well polished. By this, I mean having an article that does not have too many grammatical corrections and functional code. I suggest that you check out our [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) page which has links to various resourceful tools for writing. 
2. Ensure all your images are 600 x 400px.
3. Lastly please go through all the corrections I have made so that you can not repeat the same mistakes.

That's it! :smile: 

A final review will be done now by a content moderator.
Otherwise, congratulations on publishing your first article🍾.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

**Comment by Zubs** [comment]
Thanks, @BrianaNzivu.

I look forward to making more contributions on EngEd.

Kind Regards.

**Comment by LinusMuema** [comment]
Hi @Zubs 

Awesome job on the article.

cc: @BrianaNzivu Great job!

**Pull request merged**
