### PR TITLE
 Deployment-with-Ansible

### LINKED ISSUE #2838: Deployment with Ansible
### Proposed title of article

Deployment with Ansible

### Introduction paragraph (2-3 paragraphs):

Before the targeted end-users can use an application, it has to be deployed. Deployment refers to the process by which software is made available for use. Deployment can be to a single infrastructure or a wide range of infrastructures. Deployment to a single infrastructure is easily and quickly done, but as the number of infrastructures increases, so is the amount of effort and resources needed to deploy. 
The consistency of the environment is also more likely to change due to higher chances of human error. Another challenge that commonly arises when an application needs to be updated is that, the Updated applications become obsolete by the time the system finishes updating all the applications. Here is where Ansible comes to the rescue. Ansible enables us to deploy applications consistently and reliably. It allows the configuration of several systems from one single system. Application artifacts can also be easily pushed to different systems with the help of Ansible

### Key takeaways: 

•	What is Ansible
•	How to implement Ansible in an organization
•	Ansible integration with other tools 
•	Merits of using Ansible in deployment
•	Who should use Ansible?

### References: 
N/A

### PR DESCRIPTION
**Pull request by amchilos01**
this fixes #2838

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by okeloviolet** [comment]
@amchilos01 I'll be reviewing this article.

cc @hectorkambow

**Comment by okeloviolet** [comment]
@amchilos01 your article seems to be short. Please provide an example where you use Ansible to deploy an application, this will add value rather than explaining what Ansible is.

**Comment by WanjaMIKE** [comment]
> @amchilos01 I'll be reviewing this article.
> 
> cc @hectorkambow

Please go ahead

**Comment by amchilos01** [comment]
@okeloviolet I have committed a few changes as recommended, kindly have a look at it and revert. Thanks

**Comment by hectorkambow** [comment]
Good afternoon @amchilos01  and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and **official documentations.** 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to publish a topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀

**Pull request closed without merging**
