### PR TITLE
Handling RecyclerView Clicks the Right Way

### LINKED ISSUE #2409: Handling Recyclerview Clicks the Right Way
### Proposed title of article
Handling Recyclerview Clicks the Right Way

### Introduction paragraph (2-3 paragraphs):
The RecyclerView class supports the display of a collection of data. It is a modernized version of the ListView and the GridView classes provided by the Android framework.

When trying to handle clicks on a RecyclerView, many developers tend to do it the wrong way which is against android  best practices. There are a number of ways that we can do this, but for this article we will use the most appropriate way. This means creating a Click Class that has appropriate methods inside the adapter class.

### Key takeaways: 
- What is a RecyclerView?
- Handling clicks in a RecyclerView?
- Cons of using other method?

### References: 
- [Android Documentation] (developer.android.com/)

### PR DESCRIPTION
**Pull request by JoelKanyi**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**

This fixes #2409.
  
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by katungi** [comment]
Hello @JoelKanyi , please check the boxes in the PR description. Also make a note to include the issue that this PR closes.

**Comment by JoelKanyi** [comment]
This fixes #2409

**Comment by katungi** [comment]
Hello @JoelKanyi 

Thanks for submitting your first PR...That is awesome. We are glad to welcome you to our community.
This article will now undergo Preliminary Review which mainly checks for flow and grammatical errors.

**Comment by katungi** [comment]
Hey @JoelKanyi, I have done some minor changes, but the article is still a long way to go. Please pass through a grammar checker like Hemmingway or grammarly to remove those small mistakes. Please do so in order to continue with the review.

cheers

**Comment by JoelKanyi** [comment]
Hello, @katungi I have tried and fixed all possible mistakes, you can go through it and let me know if you have any questions.

**Comment by katungi** [comment]
Hello @JoelKanyi, I am really impressed by the changes you made to the article, everything looks good. I only have one complaint at the moment. The flow of the article is good but, I would rather the steps in the article have a short but descriptive title, followed by a short description. 

For example, in step 1 
##### Step 1: Make sure you have created your project,
 you can change it to something like: 
##### Step 1: Creating the project
Then add a small description like:
##### Step 1: Creating the project
In this step, we will create a new project, <explain how to do so or provide an example from the docs> , you can refer to the image below for guidance.

This will be better because some of your titles do not fully explain what the code is doing and since the explanation to the code is at the far end of the section, you may lose a lot of impatient readers. I would rather you fully explain the code in every step. Please make that change.

**Comment by JoelKanyi** [comment]
Hello @katungi thanks for the feedback, I will revisit the article and add short titles with descriptions

**Comment by katungi** [comment]
Hey @JoelKanyi ,just checking in,  have you made any progress with the corrections? 
If you need any help, don't hesitate to ask me, or the community on slack 🥳

**Comment by ahmadmardeni1** [comment]
Any update on this PR? @JoelKanyi

**Comment by JoelKanyi** [comment]
I have been struggling with school exams but tommorow I'll work on the
small changes that I was requested to make

**Comment by hectorkambow** [comment]
@katungi  

I noticed the student has made some changes - this PR may be ready to move on to the next step(s)?

**Comment by katungi** [comment]
Hey @hectorkambow , I must have missed the notification. Will get on the review asap.

**Review by katungi — COMMENTED** [review]
Hey @JoelKanyi , thanks for making the changes. I have made some more minor changes for the article to flow better. 
This article now looks ready for final review, after a plagiarism check.
cc: @hectorkambow

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by JoelKanyi** [comment]
> Hey @JoelKanyi , thanks for making the changes. I have made some more minor changes for the article to flow better.
> I also saw on LinkedIn that it is your birthday. Happy Birthday from the entire `Peer-Reviewers team`.
> This article now looks ready for final review, after a plagiarism check.
> 
> cc: @hectorkambow

Thank you @katungi

**Comment by ahmadmardeni1** [comment]
Your index.md file is empty @JoelKanyi - Please fill it in with your info ([Example](https://github.com/section-engineering-education/engineering-education/blob/master/content/authors/Dennis-Kariuki/index.md)) so we can publish your tutorial.

You should check the author's folder as well in your review. @katungi

**Comment by JoelKanyi** [comment]
> Your [index.md](https://github.com/section-engineering-education/engineering-education/blob/50a0a81a65834b39af73c31ef5cc5d6d3ab34b3c/content/authors/joel-kanyi/index.md) file is empty @JoelKanyi - Please fill it in with your info ([Example](https://github.com/section-engineering-education/engineering-education/blob/master/content/authors/Dennis-Kariuki/index.md)) so we can publish your tutorial.
> 
> You should check the author's folder as well in your review. @katungi

Done sir

**Comment by ahmadmardeni1** [comment]
Thank you @JoelKanyi And welcome to Section EngEd.🎉

Thank you for the review @katungi.🚀

**Comment by JoelKanyi** [comment]
> Thank you @JoelKanyi And welcome to Section EngEd.🎉
> 
> Thank you for the review @katungi.🚀

Thank you @ahmadmardeni1

**Pull request merged**
