### PR TITLE
Why and How Microservice messaging works in Kubernetes?

### LINKED ISSUE #2580: Why and How Microservice messaging works in Kubernetes?
### Proposed title of article
Why and How Microservice messaging works in Kubernetes?

### Introduction:
Struggling with connecting and maintaining your microservices in Kubernetes? As the number of microservices grows, the difficulty and complexity of maintaining your distributed fleet of services grow exponentially. Messaging can provide a clean solution to this issue, but legacy message queues come with their own set of problems. 
In this article, I’ll share the benefits of messaging in Kubernetes and the difficulties that can come with legacy solutions. I'll also briefly look at KubeMQ, which attempts to address some of the traditional problems with messaging in Kubernetes.

### Key takeaways: 
In this article, the reader will understand:
- why we need messaging in Kubernetes?
- the difficulties faced by messaging in Kubernetes
- the Kubernetes-native-approach to solve the Kubernetes related messaging issues

### References: 
N/A

### PR DESCRIPTION
**Pull request by martha-ngugi**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**

This fixes #2580.
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by martha-ngugi** [comment]
This fixes issue #2580

**Comment by hectorkambow** [comment]
@martha-ngugi 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀

Thank you.

**Comment by BrianaNzivu** [comment]
Hello 👋🏾 @martha-ngugi .
Briana here.
I'll be conducting the review for your article.
I'd still like to apologize on behalf of the Section EngEd team for the delayed review due to the long queue of articles but I believe right now we are set to go.🚀

Looking foward to working with you.

Regards.

**Review by BrianaNzivu — APPROVED** [review]
Hey @martha-ngugi :wave: 
Briana here.
First, I'd like to really appreciate your well-written and polished article.
Good job!! :clap: 
It's been a walk in the park reviewing this article.
I don't think there is anything to bring to your attention except for the very few changes I have. Please go through them.
Otherwise **GREAT** job. :rocket: 

Kind Regards.

**Comment by martha-ngugi** [comment]
@BrianaNzivu I have noted the changes. Thank you very much.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by BrianaNzivu** [comment]
Hey @martha-ngugi :wave: .
That is it. 😄
I believe this article is ready for a final review.

In case of any question or clarification (currently or in the future) do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or via my personal email (briananzivu@gmail.com).
It has been a pleasure reading and reviewing this article.  
Looking forward to seeing you contribute more to EngEd. 🚀 

Kind Regards.

**Comment by martha-ngugi** [comment]
@BrianaNzivu Thank you, looking forward to working with you again.

**Review by LinusMuema — APPROVED** [review]

**Comment by hectorkambow** [comment]
great work @martha-ngugi 

cc @BrianaNzivu & @LinusMuema 

very minor edits for format

**Pull request merged**
