### PR TITLE
Added how-to-implement-caching-in-adonisjs-5

### LINKED ISSUE #2001: The Best Caching Strategy for AdonisJS RESTFUL API
### Proposed title of article
A Caching Strategy for AdonisJS RESTFUL API

### Introduction paragraph (2-3 paragraphs):
I will be showing you the best practice in handling Caching in Adonisjs, discussing in details the best strategies involved in handling a scalable Caching System in your RESTFUL API. We will build a real-world app to demonstrate how to boost performance with a good Caching Strategy.

### Key takeaways: 
Students will learn how to build a high-performance app with Adonisjs
Students will learn how to implement a Caching System in AdonisJS Restful API
Students will learn how to choose the right Caching Strategy depending on the project.
Students will learn about the concept of Caching and how to scale large App with it.
Students will learn best practices in building performance-oriented Web apps with AdonisJS.

### References: 
https://dev.to/vigzmv/a-simple-caching-strategy-for-node-rest-apis-part-1-72a
https://blog.appsignal.com/2021/03/10/powerful-caching-with-redis-for-nodejs-applications.html
https://hackernoon.com/how-to-setup-caching-in-nodejs-using-redis-tq143usy

### PR DESCRIPTION
**Pull request by Kaperskyguru**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2001

### CODE REVIEW

**Comment by Kaperskyguru** [comment]
Hello @srishilesh,

Been a while. I will really love it if you could take a look at this article.

Thanks.

**Comment by srishilesh** [comment]
Hey @Kaperskyguru,

Thanks for asking.

Currently, I'm held up with reviewing 3 or 4 articles.

Please wait until some peer reviewers assigns himself. I will review this, if no other reviewer takes it up.

Thank you.

**Comment by zolomohan** [comment]
Hey @Kaperskyguru. It seems like you have all the articles from the old folder structure in this PR. Can you rectify this?

**Comment by Kaperskyguru** [comment]
I don't know what I have to do, my article is inside the content/articles folder, should I move it out of there?

**Comment by hectorkambow** [comment]
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

**Comment by Kaperskyguru** [comment]
@hectorkambow @zolomohan thanks for the information.

What's the status of this PR.

What do I do to.move it forward?

**Comment by geoffrey45** [comment]
Hello @Kaperskyguru I will be working on this pull request.

As you can see, this pull request has thousands of files "changed". This can cause a merge conflict. To solve this, please close this pull request and open a fresh one. Please make sure that the new one indicates that only the files changed are the ones you have really adeed or changed.

Im case you run into problems, leave a message for me in Slack.

Leave a comment for me on the new pull request 👌. I'll work on it ASAP.

cc: @zolomohan @srishilesh

**Pull request closed without merging**
