### PR TITLE
Effects and Side Effects handling in Jetpack Compose

### LINKED ISSUE #4223: [Android] Side-effects and Effects Handling in Jetpack Compose
#### Introduction
Composables should be side-effect free. However, when they're necessary to mutate the state of the app, they should be called from a controlled environment that is aware of the lifecycle of the composable. When you need to make changes to the state of the app, we use the Effect APIs so that those side effects are executed in a predictable manner.
A side effect is simply anything that escapes the scope of a function, such effects can cause our app to fail. Effects Handler is safe environment where we do side-effects handling.

#### Key takeaways 
- What are Side-effects and how they occur
- How to create side-effect free Composables
- How to handle side-effects on our code

#### References
https://developer.android.com/

### PR DESCRIPTION
**Pull request by tanscy-cassie**
This fixes  #4223

### CODE REVIEW

**Comment by tanscy-cassie** [comment]
This fixes issue #4223

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Comment by Ericgacoki** [comment]
@tanscy-cassie, I'll work on this later today!
Thanks for your patience.

**Comment by WanjaMIKE** [comment]
Merged #5042 into master

**Pull request merged**
