### PR TITLE
Implementing Frontend Pagination in React

### LINKED ISSUE #4679: Implementing Frontend Pagination in React
### Implementing Frontend Pagination in React
For easy navigation and user experience enhancement, most web apps do not show all fetched data on a single page. Instead, data is displayed on a sequence of pages and the user can navigate through the different pages with the click of a button. This is made possible by a feature known as pagination. 

Pagination can either be implemented on the server-side (where the client requests data in groups e.g., a list of the first 20 items) or on the client-side (where the client fetches all the data with a single request and the pagination is implemented on the frontend). In this tutorial, we are going to cover client-side/frontend pagination. We will use React(a JavaScript library for creating user interfaces), Bootstrap(to style our webpage)

### Prerequisites:
- Basic React knowledge 
- Basic Bootstrap knowledge
- Basic understanding of the Fetch API 

### Key takeaways: 
- Implementing pagination in React apps

### PR DESCRIPTION
**Pull request by kimanikevin254**
This fixes #4679

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Comment by kimanikevin254** [comment]
@M0nicah, any feedback?

**Review by M0nicah — CHANGES_REQUESTED** [review]
hi @kimanikevin254, before I begin the review, kindly go through the article once more and correct any grammer mistakes that might be present.
Remove the extra spaces present in most of the sections.

Ping me when you are done. :rocket:

**Comment by kimanikevin254** [comment]
@M0nicah, I checked my article again in Grammarly and there are no grammar mistakes. 

Everything is okay 🚀

**Review by M0nicah — APPROVED** [review]
great article @kimanikevin254

**Comment by hectorkambow** [comment]
Jumping on this one

**Comment by hectorkambow** [comment]
Overall nice work 👍

**Pull request merged**
