### PR TITLE
Java vs C#

### LINKED ISSUE #2343: Java Vs C#
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Java Vs C#

### Introduction paragraph (2-3 paragraphs):

Java and C# are both Object-Oriented languages used for developing  Web applications, Networking applications, Database applications, Mobile application, Videos games, Service applications and so much more.

Let's look at the primary difference between the two.

Java is an Object-Oriented, class-based and general-purpose programming language. Developers can use the principal – “write once, run anywhere” with Java. Java was invented in 1995.  It requires Java Development Kit to run on a machine.

C# is an Object-Oriented Programming language and it is portable as it can develop software for many computer systems. C# was invented in 2002. Programs written in C# utilize the .NET Framework to run on a machine. 

In this article, we shall compare between Java and C#.

### Key takeaways: 
1.  Application - Where the languages can be used
2. Installation - The requirement of each language to run on a machine
3. Cross-platform - Which of the languages is easily compatible to other platforms
4. Project - Where does each language suit the best. i.e, suited for complex web-based concurrency projects or game development projects
5. Syntax - which one offers developer friendly syntax

### References: 
N/A

### PR DESCRIPTION
**Pull request by Alicewangari**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2343

### CODE REVIEW

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by Alicewangari** [comment]
@adrianmurage I have made the changes.

**Review by adrianmurage — APPROVED** [review]

**Comment by adrianmurage** [comment]
Great work @Alicewangari 
Looking forward to seeing more of your work on EngEd

**Comment by hectorkambow** [comment]
Great work @Alicewangari - and welcome to the EngEd program. Looking forward to more great articles. 

Please be sure to go through my final edits to improve future articles and reviews. 

cc @adrianmurage

**Pull request merged**
