### PR TITLE
How to Get Started with Kotlin Flows API Zip Operator 

### LINKED ISSUE #4969: [Android] Getting Started with Kotlin Flows API Zip Operator for Parallel Multiple Network Calls in Android
### Topic Suggestion
[Android] Getting Started with Kotlin Flows API Zip Operator for Parallel Multiple Network Calls in Android

#### Proposed title of article
Getting Started with Kotlin Flows  Zip Operator for Parallel Multiple Network Calls in Android

#### Proposed article introduction
Flow API in Kotlin is a better way to handle the stream of data asynchronously that executes sequentially.  Zip Operator is an operator that combines the emissions of two flow collections together via a specified function and emits single items for each combination based on the results of this function.

Parallel Multiple Network Calls is used in Android when we want to make two network calls in parallel and want the results of both the network calls in a single callback when both the network calls are completed.

#### Key takeaways 
- What is Kotlin Flow API.
- What is Kotlin Flow Zip operator.
- Uses of Kotlin Flow Zip operator.
- Advantages of Using Kotlin Flow Zip Operator in Android.
- How to make the multiple network calls in parallel using Kotlin Flow Zip Operator.

#### Article quality
 The article is going to be unique since am going to make it beginner friendly. Since it is a new concept in Android development I researched and realized that there are are less content in the internet for reference and this is going to help developers to learn and understand it.

#### References
- https://blog.mindorks.com/kotlin-flow-zip-operator-parallel-multiple-network-calls
- https://developer.android.com/kotlin/flow

### PR DESCRIPTION
**Pull request by Emmah-Lashly**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #4969

### CODE REVIEW

**Comment by Emmah-Lashly** [comment]
Hello @WanjaMIKE, @ahmadmardeni1, and @louisefindlay23 please assign a reviewer to this PR. Thank you.

**Comment by Emmah-Lashly** [comment]
Hello @Jethro-magaji ,
I have done the changes as requested, thank you.

**Comment by WanjaMIKE** [comment]
@Emmah-Lashly Are you recycling code? It seems to show plagiarism.

[New Scan 7_34 AM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/8108911/New.Scan.7_34.AM.Copyleaks.Report.pdf)

**Review by Jethro-magaji — APPROVED** [review]
Hi! @Emmah-Lashly 
Well done for such an amazing article, please take note of these corrections so that you can minimize revisions in your next article.
Thanks.

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
