### PR TITLE
PHP Implode and Explode

### LINKED ISSUE #3106: PHP Implode and Explode
### Proposed title of article*

PHP Implode and Explode

### Introduction paragraph (2-3 paragraphs):

When working with arrays and strings in PHP, the functions PHP implode and PHP explode are frequently utilized. I will show the leader how to use implode in PHP with a code example in this article. With a code example, I will also demonstrate how to utilize explode in PHP.

I will also demonstrate how to generate an array from a string using the explode statement. The explode() function converts a string to an array, whereas the implode() function creates a string from an array's elements.

### Key takeaways:
 
1. PHP Implode Function
2. PHP Explode Function

### References: 
N/A

### PR DESCRIPTION
**Pull request by amarawrite**
Complete article

### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #3106 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.
[PHP Implode and Explode #3549.pdf](https://github.com/section-engineering-education/engineering-education/files/7072141/PHP.Implode.and.Explode.3549.pdf)

**Comment by amarawrite** [comment]
Hi, @WanjaMIKE 
cc @M0nicah 
I have made the changes on my article. It is now okay waiting to see my article being reviewed and published.
Thank you

**Comment by amarawrite** [comment]
hi, @WanjaMIKE 
Would you please update me on the progress of my article. It has been quiet some time with no feedback please let me know.
Thank you.

**Comment by amarawrite** [comment]
Hello, @hectorkambow 
 cc @WanjaMIKE 
Would you update me on the progress of this PR please, 
It is now 10 days with no updates or replies.
Thank you.

**Comment by M0nicah** [comment]
Hi @ahmadmardeni1 could we please run a plagiarism check on this article. There has been no response for a while now.
@amarawrite made some changes.

cc: @WanjaMIKE , @hectorkambow

**Comment by ahmadmardeni1** [comment]
👋 Good afternoon - and welcome to the EngEd program.
There appear to be many sentences in this article that are taken verbatim from third-party sources, like [this](https://www.c-sharpcorner.com/UploadFile/051e29/implode-and-explode-function-in-php/), and [this](https://www.simplilearn.com/tutorials/php-tutorial/string-to-array-in-php). 

We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).
We're really looking for unique/original content - I'm going to close this PR. Please feel free to suggest an alternate topic to explore. 🚀
cc @M0nicah 

[PHP Implode and Explode#3549f](https://github.com/section-engineering-education/engineering-education/files/7153587/New.Scan.10_37.AM.Copyleaks.Report.pdf)

**Pull request closed without merging**
