### PR TITLE
How To Load Test Django Applications With Locust

### LINKED ISSUE #7311: Load testing a Django Application With Locust
### Topic Suggestion
How To Use Locust to Load Test Django Applications

#### Proposed title of article
Load Testing Django Applications With Locust

#### Proposed article introduction
Load testing is the practice of testing how an application performs when a lot of users start using it concurrently. The load referred to here is simply the various requests being made to that application at the same time by the users.

Often times we build applications and we have no idea how they will perform when hundreds or even thousands of users try to use it concurrently until we launch them. How do we properly test our applications to make sure they can handle hundreds or even thousands of concurrent requests from hundreds or even thousand of users so we can sit back and have that deserved cup of coffee after launching? This is what we will learn in this article, we will also learn about one or two database optimization functions in Django to further boost the performance of our application.

#### Key takeaways 
- Learners will learn how to test the behavior of their applications when a lot of users try to use it
- Learner will learn about some database optimization tools in Django
- Learners will learn how to use Faker library to generate data for their database to simulate production database

#### Article quality
- My article aims to explain load testing concepts to learner as simple as possible by building a real project.
- My article also cover addition topics like database optimization through Django ORM which will be useful in building performant applications.

#### References
Locust documentation: [Locust](https://locust.io/)
Django documentation: [Django](https://docs.djangoproject.com/en/4.0/)
Faker documentation: [Faker](https://faker.readthedocs.io/en/stable/)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Olamidun**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #7311

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### Markdown file added:
an index.md file which is the article about how to test django apps with locust

### Article description
Wrote an article on how to load test Django applications using an open source library called Locust.

### Image Files Added
- all_endpoint_test_table.png
- five_users_test_chart.png
- five_users_test_chart2.png
- five_users_test_graph.png
- locust_homepage.png
- locust_response.png
- two_fifty_users_chart.png

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Plagiarism check complete

**Comment by louisefindlay23** [comment]
@Olamidun, please follow the Topic Suggestion This Closes instructions to link your topic suggestion to this PR.

**Comment by Olamidun** [comment]
> @Olamidun, please follow the Topic Suggestion This Closes instructions to link your topic suggestion to this PR.

Okay I will, thanks

**Comment by Olamidun** [comment]
> @Olamidun, please follow the Topic Suggestion This Closes instructions to link your topic suggestion to this PR.

Hi @louisefindlay23 , I have linked my topic suggestion to the PR like you requested.

**Comment by hectorkambow** [comment]
Jumping on this one

**Pull request merged**
