### PR TITLE
Creating a shopping cart api in java

### PR DESCRIPTION
**Pull request by kingsleynwafor54**
This describes how a shopping cart works and how you can construct .

### CODE REVIEW

**Comment by kingsleynwafor54** [comment]
@john-amiscaray  I have created a new pull request.

**Comment by john-amiscaray** [comment]
@kingsleynwafor54 Still something seems off. If you look at the `commit` section on Github, you'll see that in a couple of your commits there seem to be some irrelevant files in this repo that you never worked on. Additionally, in the `Files Changed` section, you'll see your previous article listed there when it seems you haven't worked on it recently. I'm not quite sure what's going on here. **Please refer to the [upload instructions](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/UPLOAD_INSTRUCTIONS.md) in case you are making a mistake somewhere and try making a new pull request again**. Otherwise, you should have a talk with one of the content moderators (i.e. Hector, Ahmad, Louise, etc.) to see what might be going wrong.

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Comment by srishilesh** [comment]
@kingsleynwafor54 

On taking a look at your commits, I feel that you have pushed your new article without fetching the latest master.

I would suggest you to follow the below steps:

```bash
git fetch section
git pull --rebase section master
git push origin
```

> Here, `section` is the remote origin for the repository.

Once you do that, checkout out to a new branch from the latest master, then put in all your files and create a PR.

Make sure you are in `master`.

```bash
git checkout -b [NEW_BRANCH]
[ADD ALL NEW FILES]
git commit -a -m "Init"
git push origin [NEW_BRANCH]
```

Hope it helps. Let me know if you still face any issues.

Thanks.

cc. @john-amiscaray @hectorkambow

**Comment by john-amiscaray** [comment]
@srishilesh Thanks for the help. @kingsleynwafor54 Can you please make a new pull request following the above steps.

**Comment by kingsleynwafor54** [comment]
@srishilesh @john-amiscaray  thanks a lot, I will do just that.

**Comment by srishilesh** [comment]
Duplicate of #6221. Closing this PR.

**Pull request closed without merging**
