### PR TITLE
Walsh hamard transform for signal and image compression using matlab

### LINKED ISSUE #4431: Walsh-method transform for signal filtering and image compression in Matlab
#### Introduction
The Walsh-Hadamard transform is a non-sinusoidal, orthogonal transform that is widely used in areas of signal and image processing. Here, the signal is decomposed into a set of basis functions (similar to harmonics in Fourier). These basis functions are known as the Walsh function which are rectangular or square waves with values of +1 or -1. Like the fast Fourier transform(FFT), the Walsh-Hadamard transform has a fast version which is known as fast Walsh-Hadamard transform(FWHT).

The Walsh-Hamard has a wide application in the field of science and engineering. These applications are such as image processing, speech processing, signal and image compression, power spectrum analysis, spread spectrum analysis e.t.c. In this tutorial, we will look at signal and image compression using Matlab. We will look at its theory and its computation for both 1d and 2d signals.

#### Key takeaways 
- Forward and inverse walsh-Hamard transform.
- Computing Walsh-Hamard of 1-D and 2-D signal.
- Fast Walsh-Hamard transform algorthm.
- Matlab code for image compression and filtering noisy signal using WHT.
#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by peterAdongo**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #4431 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Kayere** [comment]
Plagiarism check done ✔️

**Comment by M0nicah** [comment]
hello @peterAdongo , Kindly add a simple explanation for your code snippets so the readers could follow along easily.

Also ensure that you go through the article and correct any mistakes, before I continue with the review.

Ping me when you are done. 👍

**Comment by peterAdongo** [comment]
@M0nicah changes made

**Comment by WanjaMIKE** [comment]
@M0nicah do you need any help with the PR?

**Comment by M0nicah** [comment]
Yes, please.

Monica W.

**Comment by M0nicah** [comment]
> @M0nicah do you need any help with the PR?

yes I do

**Comment by Kayere** [comment]
Great article @peterAdongo.
Thank you for the review @M0nicah.

**Pull request merged**
