### PR TITLE
Integrating firebase database in django

### LINKED ISSUE #3658: Full-Stack Reactive Website in Django (no JavaScript)
### Proposed title of article
Full-Stack Reactive Website in Django (no JavaScript)

### Introduction paragraph (2-3 paragraphs):
A modern website that requires complex user interaction is built using a dedicated frontend framework like React, Vue among others. However, there is some complexity that goes with it. Based on experience, trying this route of building a full-stack application we have time complexity, more money to host the dedicated frontend, SEO complexity, syntax differences, in some cases duplicate business logic and a whole lot more.

We can achieve the same reactive website with technologies like React without leaving our Django project or adding another language to our toolkit. It, therefore, is less complex, less code and has a faster development time.

There are several technologies out there that achieve this functionality for us like [Sockpuppet](https://sockpuppet.argpar.se/), [reactor](https://github.com/edelvalle/reactor/) and [Unicorn](https://www.django-unicorn.com/docs/). However, for this tutorial, we would be taking a look at Unicorn to achieve interactivity within our website without any custom JavaSript.

### Key takeaways: 
1. Reactive Web App without a dedicated frontend framework
2. Unicorn

### PR DESCRIPTION
**Pull request by shosenwales**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #3658.

### CODE REVIEW

**Comment by jerimkaura** [comment]
hello @shosenwales 

Consider reading the docs to get the process of opening a pull request. 

ping me if you have any troubles doing the same.

Thanks

**Comment by shosenwales** [comment]
Hi @jerimkaura ,

I think i might need help

**Comment by shosenwales** [comment]
Fixes #3685

**Comment by ahmadmardeni1** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.


[Integrating firebase database in django](https://github.com/section-engineering-education/engineering-education/files/7216594/New.Scan.9_43.AM.Copyleaks.Report.1.pdf)

**Comment by louisefindlay23** [comment]
@shosenwales, please remember to follow the Topic suggestion this closes instructions in the PR template correctly to link your topic suggestion to your PR. This helps ensure a swift payout.

You should remove the backticks from the line below and add your issue number there. You added it in a new comment which doesn't work. It must be in the initial comment.

**Comment by shosenwales** [comment]
Hi @louisefindlay23 

I don't really get you. Could you please re-explain

**Comment by louisefindlay23** [comment]
@shosenwales, I've made a [screencast](https://www.loom.com/share/09dc4d0920524f7ca7360da85531b476) which should show what I mean. Let me know if you need any further clarification. 

I've made the changes for you in this PR but in the future, make sure to link them correctly.

**Comment by shosenwales** [comment]
@louisefindlay23 

Thanks.

**Comment by shosenwales** [comment]
Hi @ahmadmardeni1 

Made some fixes, kindly go through.

**Review by jerimkaura — APPROVED** [review]
@shosenwales  nice piece. Work on your future articles by going through the changes. Proceeding to tech review.

**Comment by shosenwales** [comment]
@jerimkaura thanks i will

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Pull request merged**
