### PR TITLE
Creating a finger counter using computer vision, OpenCv and Python

### LINKED ISSUE #5409: Creating A Finger Counter Using Computer Vision, OpenCv And Python
### Topic Suggestion
Creating A Finger Counter Using Hand Tracking, Computer Vision, And OpenCv

### Writing sample(s): 
[Sample](https://www.section.io/engineering-education/machine-learning-regression-evaluation-metrics/)

#### Proposed title of article
Creating a finger counter using computer vision, opencv and python 
#### Proposed article introduction
When it comes to coding, the best way to practice is by creating interesting projects. These projects should not be too simple. They should be engaging and require someone to interact with the various entities involved. That is why for the purpose of this tutorial we will focus on an interesting topic.

In this tutorial, we will create a program that will use computer vision and hand tracking to detect a hand. It will also be able to identify the number of fingers shown to it through the webcam and display the number. 

#### Key takeaways 
- How hand-tracking is done using python.
-  How OpenCV is implemented in this project
- How to combine computer vision, OpenCV, and python to create a finger counter

#### Article quality
This article will be unique as it will show the reader how hand-tracking is done not importing an already created module. It will also have a code that is well explained for the user to easily follow through. 

#### References
N/A

### PR DESCRIPTION
**Pull request by FINCH285**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5409

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
plagiarism check done.

**Review by Dawe-7 — CHANGES_REQUESTED** [review]
Awesome article @FINCH285, very informative and easy to follow through. Just one suggestion, check on your capitalization. The words `opencv`, `python` and `mediapipe` should be be capitalized as `OpenCv`, `Python` and `MediaPipe`. Kindly change this throughout the article and ping me when done.

**Comment by FINCH285** [comment]
@Dawe-7 
Done with the requested changes

**Review by Dawe-7 — APPROVED** [review]
Awesome Job on the article @FredBenson. Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles. Thank you.

**Comment by lalith1403** [comment]
Jumping on this one 🚀

**Comment by lalith1403** [comment]
Upon a quick review, several grammatical errors still exist. Please address the readability issues in the article. Thank you.

**Comment by FINCH285** [comment]
@Dawe-7  fixed the grammatical errors

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
