### PR TITLE
[Duplicate of #6166] - Managing React State with Hookstate 

### LINKED ISSUE #3187: Handling React state management with Hookstate
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Handling React state management with Hookstate

### Introduction paragraph (2-3 paragraphs):
Building React applications has a major challenge with managing state. Many libraries such as redux exist but are highly opinionated forcing us to use actions and reducers.
This is where [Hookstate](https://hookstate.js.org/) library comes in to simplify state management in React apps. Hookstate works almost exactly like the React useState Hook. It utilizes React hooks, and a couple of other impressive techniques to deliver great development experience and performance. Among its advantages include:
- First-class Typescript support
- Plugins System making it easy to use, add features and feature-rich
- Development Tools to trace, set state values, and breakpoints on state changes

### Key takeaways: 
- Setting up Hookstate in React
- A guide on Hookstate and its features
- Building a React application with Hookstate
- Creating, updating, and handling events and global store in Hookstate 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by marienjus**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3187

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by marienjus** [comment]
@srishilesh This is a complete rewrite of the previous one. I have implemented the changes (might be different on the current flow).

**Comment by srishilesh** [comment]
Hey @marienjus ,

I had a glance at your PR. I don't think all the suggestions were addressed. Can you please go through your previous PR once again?

Let me know when done.

Thanks.

**Comment by srishilesh** [comment]
Duplicate of #6166

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
Upon a quick glance we noticed that this articles has some grammatical errors (or is a bit difficult to read) and does not seem ready to be published.

In order to keep our backlog to a minimum, we will be closing this PR, as all edits should be completed on authors forked repo not in the queue.

**Comment by srishilesh** [comment]
@hectorkambow 

Reopening this PR, since the author had very minor changes to be done.

cc. @marienjus

**Comment by srishilesh** [comment]
I'll complete my final review by tomorrow EOD.

**Comment by srishilesh** [comment]
Jumping on this one now.

**Review by srishilesh — APPROVED** [review]
Hey @marienjus ,

Great work!

Make sure to go through the minor changes that I've made.

Moving for the final review.

Thanks.

**Comment by ahmadmardeni1** [comment]
Great work team. @marienjus @srishilesh

**Pull request merged**
