### PR TITLE
Creating A Screen Recorder Using Python And Pycharm

### LINKED ISSUE #4402: (Python)Creating A Screen Recorder Using Python And Pycharm
#### Proposed title of article
How to create a screen recorder using python

#### Proposed article introduction
Screen recorders come in handy in some tasks, e.g when creating tutorials to enhance training effectiveness. Some of these recorders come in subscriptions that may not be pocket-friendly. Python helps us create our own screen recorder hence saving us on cost.

In this tutorial, we are going to demonstrate how to create a screen recorder that will also be performing webcam recording. We will be using the following python packages:

- Datetime.
- Python image library
- NumPy.
- win32api
- cv2

#### Key takeaways 

1. Creating a screen recorder.
2. Working with the mentioned python packages.
3. Integrating a webcam recorder into the screen recorder.

#### Article quality
Most articles don't integrate the webcam recorder. In this article, we will show the reader how to integrate a webcam recorder into the screen recorder.
#### References
N/A

### PR DESCRIPTION
**Pull request by kirurisimon**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4402

### CODE REVIEW

**Comment by adrianmurage** [comment]
Hey @kirurisimon   👋 .
The article is a very interesting read. Good job!

A final review will be done now by a content moderator.
Otherwise, congratulations on publishing your first article🍾.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://sectionio-community.slack.com/team/U014P3U0U13) or my personal email (adrianmurage21@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

**Comment by FINCH285** [comment]
@adrianmurage 
Hey. Thanks for reviewing my article. I will go through the changes you have made to better my future articles. See you at the next one.

**Comment by kirurisimon** [comment]
@adrianmurage 
Hey. Thank you for reviewing my article. I will go through the changes you have made to better my future articles. See you at the next one

**Comment by hectorkambow** [comment]
Jumping on this one

**Comment by hectorkambow** [comment]
@kirurisimon 
👍 overall nice work - very detailed and straight forward tutorial 
 
Please review and suggestions/changes made by your peer reviewer and/or myself during a final review. 

cc @adrianmurage

**Pull request merged**
