### PR TITLE
C# or C++ for game development?

### LINKED ISSUE #3237: C++ or C# for Game Development?
### Introduction paragraph (2-3 paragraphs):
C# and C++ are both object oriented programming languages used in used different mutual application one of the being Game Development

C++ was developed first and has become one of the most popular language used for game development. Other languages developed later like C# have brought in factors to be considered when selecting the right language.

C# is growing popular due to its compatibility with different game engines. It is mostly used for .NET platforms and unity game engine.
Considerations to help a programmer chose his/ her right language will be discussed

### Key takeaways: 
1. Software requirements and installations
2. Compatible / Cross platform
3. User friendliness and complexity
4. When to use C#
5. When to use C++

### References: 
N/A

### PR DESCRIPTION
**Pull request by del-ui**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3237 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by M0nicah** [comment]
Hello @del-ui,
Welcome to Section's engineering education program.🚀 We are glad to have you! This is a good article you have here and I will be going through it.
Thank you for your contribution.😁

**Comment by del-ui** [comment]
I will be waiting for feedback

**Comment by WanjaMIKE** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.
[C# or C++ for game development #3528.pdf](https://github.com/section-engineering-education/engineering-education/files/7072268/C.or.C%2B%2B.for.game.development.3528.pdf)

**Comment by WanjaMIKE** [comment]
Significant plagiarism recorded!

**Comment by del-ui** [comment]
i have updated everything, hope it's alright now

**Comment by Kayere** [comment]
Congratulations for publishing your first article @del-ui. Keep up the great work 🚀.

Thank you for the review @M0nicah.

**Review by Kayere — APPROVED** [review]

**Comment by del-ui** [comment]
this closes #3528

**Pull request merged**
