### PR TITLE
Migrated core-concepts-of-django-for-mastering topic #2627

### PR DESCRIPTION
**Pull request by hectorkambow**
major changes for flow
fixed author profile index

https://github.com/section-engineering-education/engineering-education/pull/2627/files

### CODE REVIEW

**Comment by hectorkambow** [comment]
@katungi 

Please go over my edits - this article was not at all ready to be published - it required much polishing up. 

Go over my edits to see what can be applied to improve future reviews 👍

**Comment by Horlawhumy-dev** [comment]
Wow! Thanks to section.io for the opportunity given to me. 
Can I get the url to my article on the website please? Been a newbie in this company, I would like to know the next step after the article has been merged.
And lastly kindly re-open the proposed article with issue #2637, so that I can start working on it.

**Comment by katungi** [comment]
Heeey, @Horlawhumy-dev , after merging the article will be published. You are free to start working on the other article.
You can ping Hector on the issue so he can re-open it.
Thanks you for your contribution🥳

**Comment by Horlawhumy-dev** [comment]
I have confirmed the publishing, thank you. 
@hectorkambow sir, I need you to reopen the issue #2637.

**Comment by Horlawhumy-dev** [comment]
Please @hectorkambow  sir! I am having issue with payment details for this article. I think it's due for payment.

**Comment by Horlawhumy-dev** [comment]
Also, I could not join the slack community. Come to my rescue sir @hectorkambow @katungi

**Pull request merged**
