### PR TITLE
Embracing API-first Approach Beyond Product Designing

### LINKED ISSUE #3950: [API] Embracing API-first Approach Beyond Product Designing
### Proposed title of article
[API] Embracing API-first Approach Beyond Product Designing 

### Introduction paragraph (2-3 paragraphs):
An API-first approach is steadily becoming a popular way of designing products, but the principle is not only relevant in products. The approach is also relevant to app development and automation. 
In this piece, I’ll be making the case for why an API-first approach is relevant to automation as well as app development.

### Key takeaways: 
What Is API-First App Development? 
What is API-first design? 
Why API first? 
Why developers need API-first approach. 
Why API is relevant to automation. 
### References: 
N/A

### PR DESCRIPTION
**Pull request by Polojigide**
this closes #3950

### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Kayere** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Embracing API-first Approach Beyond Product Designing #4651 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7453155/Embracing.API-first.Approach.Beyond.Product.Designing.4651.Copyleaks.Report.pdf)

**Comment by Polojigide** [comment]
@mbaabuones Done.

**Comment by mbaabuones** [comment]
> 
> 
> @mbaabuones Done.

@Polojigide Please add the author bio and photo as described above. Ping me when you are done so that I can proceed with the next step.

*As a first time contributor, you are required to submit an author bio and a photo (named 'avatar'). These files should be uploaded in the **authors** folder situated in the **contents** folder.*

**Comment by hectorkambow** [comment]
@Polojigide 
Please be sure to add your author image and bio along side this PR. 👍 in order to be able to publish it and give you credit for your work.

**Comment by Polojigide** [comment]
@mbaabuones I have added my bio and headshot image.

**Comment by hectorkambow** [comment]
@mbaabuones Let us know any next steps - if the articles still seems to need extra revisions - lets consider closing to allow the author the proper time to make the required edits outside of the queue.

**Comment by mbaabuones** [comment]
> 
> 
> @mbaabuones I have added my bio and headshot image.

@Polojigide You should indicate at least two names in your author bio. Please add a second name.

**Comment by mbaabuones** [comment]
> 
> 
> @mbaabuones Let us know any next steps - if the articles still seems to need extra revisions - lets consider closing to allow the author the proper time to make the required edits outside of the queue.

@hectorkambow The author has already made all the suggested changes.

**Comment by Polojigide** [comment]
@mbaabuones

**Comment by lalith1403** [comment]
@section-engineering-education/content-moderator-team I will be performing the final round of review on this PR.

**Pull request merged**
