### PR TITLE
Understanding hybrid data models

### LINKED ISSUE #5329: [Databases] Understanding hybrid data models
#### Proposed title of article
Understanding hybrid data models

#### Proposed article introduction
Relational databases hold a leading position in the database industry and are better known as workhorses of the database industry. They are one of the most popular and commonly used mediums for recording, manipulating, and retrieving data. They find its application in varied and protean requirements including data mining, business intelligence, and analytical querying.

However, new requirements from database developers started coming up with the arrival of web 3.0 and data explosion with big data and social networks. These requirements focused more on relationships in data, thus making graph-structured data important. Graph
databases provide flexible structure to address graph data. 
However, there are various domains that give rise to graph and relational queries, which leads to the development of the hybrid database. 

Hybrid model design is the integration of two popular database models in a single framework in order to abolish the drawbacks of each system. In this proposed guide, we will use some of the JSON functionalities that are also available in MariaDB to demonstrate the concept of hybrid data models.

#### Key takeaways 
At the end of the proposed guide, the learner will be able to understand:
- how to model structured and semi-structured data
- how to index and query JSON data with MariaDB
- how to enforce the data integrity of JSON data

#### Article quality
The proposed article will explain in detail hybrid data models and how to implement them using examples that would be easy to understand by beginner readers. Unlike most of the articles found online which assume the reader is at the advanced level. The examples used and command are simple and straightforward.

#### References
N/A

### PR DESCRIPTION
**Pull request by g-wekesa**
The article covers the below:
how to model structured and semi-structured data, how to index and query JSON data with MariaDB and also how to enforce the data integrity of JSON data.

## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #5329

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by srishilesh** [comment]
Hello @g-wekesa ,

Welcome to EngEd community!

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started with the review process.

Meanwhile, we suggest you to go through other approved PRs/articles to see how the authors have formatted their articles, to avoid any potential closure of your PR.

Thanks.

**Comment by lalith1403** [comment]
plagiarism check done ✔️

**Comment by M0nicah** [comment]
🚀 awesome article @g-wekesa  , please be sure to go through the changes I made in the commits to help improve flow and format for your future articles. 
Thanks!

**Comment by g-wekesa** [comment]
> 🚀 awesome article @g-wekesa , please be sure to go through the changes I made in the commits to help improve flow and format for your future articles. Thanks!

@M0nicah The changes made during the review process have been noted and I will improve in future articles.
Thank you for the review.

**Comment by Kayere** [comment]
Congratulations on publishing your first article @g-wekesa.
Thank you for the review @M0nicah.

**Pull request merged**
