### PR TITLE
Adding Individual Author RSS Feeds

### LINKED ISSUE #7105: Author RSS Feeds
Creating an RSS Feed for each author which will allow them to embed a list of their articles where RSS Feeds are supported. Similar in idea to the [web app](https://github.com/louisefindlay23/section-author-feed) I made to create JSON Feeds for authors, this would be simple RSS Feeds generated from the EngEd website.

This would allow users to subscribe to future articles from a specific author (to follow them) similar to the email subscription idea @ahmadmardeni1 had however through RSS which is simpler to add to the site and maintain as it uses Hugo's built-in capabilities. Authors would just need to use a RSS reader such as Feedly to view the feed.

**Describe the task(s) you'd like to see done**
Generate an .xml RSS Feed for every author with a list of their articles

**Additional Benefits**
- Authors can embed the RSS Feed in many locations (where JSON feed like in the web app I developed may not be supported)

**Alternatives Building on this Feature**
To fufill @ahmadmardeni1's original email subscription idea

- Use the RSS Feed generated in an email subscription feature - future additional feature request
- Subscribers could use a service similar to IFTTT to send an email when a new feed item (from the feed that would be created) was generated

### PR DESCRIPTION
**Pull request by louisefindlay23**
### What This PR Does

- Adds a term in category RSS Feed template for individual author RSS feeds so readers can subscribe to an author's post via an RSS service (such as Feedly)
- Changes the author profile files to be a taxonomy in addition to a section - only `louise-findlay` and `ahmad-mardeni` as a test

### Files Edited

- **Authors Taxonomy Term RSS Feed Template** - `/layouts/authors/rss.xml`
- **Louise Findlay's Author Profile** - `/content/authors/louise-findlay/index.md`
- **Ahmad Mardeni's Author Profile** - `/content/authors/ahmad-mardeni/index.md`

### How to Test

1. Checkout this PR branch
2. Start the local hugo server - `hugo server -D`
3. Navigate to [localhost:1313/authors/louise-findlay/index.xml](http://localhost:1313/authors/louise-findlay/index.xml)
4. Verify that the RSS Feed shown matches the screenshot below and that the Author Profile still looks as previously
5. Navigate to [localhost:1313/authors/ahmad-mardeni/index.xml](http://localhost:1313/authors/ahmad-mardeni/index.xml) and verify the articles listed are only from this author

### Screenshot

Ahmad Mardeni's RSS Feed

### Future Steps

- Add `authors: {author-foldername}` to the front-matter of all other author profiles to display the feeds for other authors

### Related Issue

This closes #7105.

### CODE REVIEW

**Review by hborrelli1 — APPROVED** [review]
Looks great, nice work!

**Comment by hectorkambow** [comment]
@louisefindlay23  👋  

Quick question regarding the parameter "authors" - was wondering if that could be more descriptive (as to not confuse other authors or new authors coming in). 🤔 

Could be be something like rss-feed, rss-authors. Something to separate it from other similar syntax.

cc @hborrelli1 - what are your thoughts on this - perhaps I'm looking at it from a different angle.

**Comment by louisefindlay23** [comment]
Thanks, @hborrelli1. 🚀

@hectorkambow, the authors parameter is used because it matches the section/taxonomy name that was created for the author pages.

When I researched this, Hugo only generates the RSS feeds because the authors parameter matches the taxonomy that was created otherwise it doesn't work i.e. it has to match the name of the folder (authors) under the content directory. I'm not sure if it's possible to change it and have it still to work. @hborrelli1, is more experience with Hugo than I am so he might know a way to do this.

**Comment by hborrelli1** [comment]
@hectorkambow  good point. 

@louisefindlay23, the parameters in front matter are all custom with the exception of [some predefined values](https://gohugo.io/content-management/front-matter#front-matter-variables). Where it matters is [here](https://github.com/louisefindlay23/engineering-education/blob/96a75ce0850d21658e63e18269c4365e6f26a226/layouts/authors/rss.xml#L19) where you're comparing the value to the Permalink of the current author. I agree it might be useful to change that front matter variable to something a little more clear, such as `rss-author` or something similar to what @hectorkambow mentioned.

**Comment by louisefindlay23** [comment]
> @hectorkambow good point.

Yeah, I agree that `rss-author` would be cleaner and better but I not sure if it's possible without the taxonomy tag in `config.toml` for author pages.

> @louisefindlay23, the parameters in front matter are all custom with the exception of [some predefined values](https://gohugo.io/content-management/front-matter#front-matter-variables). Where it matters is [here](https://github.com/louisefindlay23/engineering-education/blob/96a75ce0850d21658e63e18269c4365e6f26a226/layouts/authors/rss.xml#L19) where you're comparing the value to the Permalink of the current author. That line could become something like ` {{ if eq .Params.rss-author $a }}`.

 With the way, Hugo builds RSS feeds, https://gohugo.io/templates/rss/, this uses a Term in Categories template, `layouts/categories/taxonomy.rss.xml` so Hugo uses the template RSS file to build a new XML file for every author.

> I agree it might be useful to change that front matter variable to something a little more clear, such as `rss-author` or something similar to what @hectorkambow mentioned.

The `content/authors/rss.xml` template file doesn't take effect (Hugo won't generate the `index.xml` page under the author) unless there's a front-matter parameter that matches the folder name above the RSS template file and the same taxonomy in `config.toml` so if I change it something like `rss-authors`, Hugo won't use the RSS Template file and `/engineering-education/authors/{author-name}/index.xml` results in 404 Page Not Found.

I'm not sure if it's possible to change this using Hugo's built-in RSS Feed functionality. Would it be better, @hborrelli1 if I looked into alternative approaches outside Hugo's built-in RSS Feed generator where it might be possible to avoid adding this extra `authors` parameter?

**Comment by hectorkambow** [comment]
Lets also ask the other CM team mates - as it may just be confusing to me and not the other students. 

@louisefindlay23  

@section-engineering-education/content-moderator-team

**Comment by hborrelli1** [comment]
> The `content/authors/rss.xml` template file doesn't take effect (Hugo won't generate the `index.xml` page under the author) unless there's a front-matter parameter that matches the folder name above the RSS template file and the same taxonomy in `config.toml` so if I change it something like `rss-authors`, Hugo won't use the RSS Template file and `/engineering-education/authors/{author-name}/index.xml` results in 404 Page Not Found.

I see, that makes a little more sense now. 


> I'm not sure if it's possible to amend this using Hugo's built-in RSS Feed functionality. Would it be better, @hborrelli1 if I looked into alternative approaches outside Hugo's built-in RSS Feed generator where it may be possible to avoid adding this extra `authors` parameter and just use the existing ones?

I'm not sure I fully understand this. What do you mean by "... parameter and just use the existing one"? Does this rss-feed do something that the built in one cannot?

**Comment by louisefindlay23** [comment]
> > I'm not sure if it's possible to amend this using Hugo's built-in RSS Feed functionality. Would it be better, @hborrelli1 if I looked into alternative approaches outside Hugo's built-in RSS Feed generator where it may be possible to avoid adding this extra `authors` parameter and just use the existing ones?
> 
> I'm not sure I fully understand this. What do you mean by "... parameter and just use the existing one"? Does this rss-feed do something that the built in one cannot?

Sorry, I wasn't very clear. Hopefully this makes more sense. I was asking is it vital that the `authors` parameter be changed (i.e. Hector's suggestion to use something like `rss-author`) in order to merge this? If so, I'll probably need to look into alternative ways of implementing this feature request rather than using Hugo's built-in RSS Feed functionality which this PR does (that relies on `authors`).

**Comment by hborrelli1** [comment]
@louisefindlay23, thanks for the clarification. I think if that is the case, we can keep it as is. 

@hectorkambow we will likely want to update the docs so it is clear for other students.

**Comment by hectorkambow** [comment]
> @louisefindlay23, thanks for the clarification. I think if that is the case, we can keep it as is.
> 
> @hectorkambow we will likely want to update the docs so it is clear for other students.

👍 very well - that sounds good to me! As long as we can explain to other students and it doesn't cause a confusion - we should be good to go. 

Very true - @louisefindlay23 if you could update the docs with any changes you made (we want to always follow best practice - whenever we make any updates to the Repo - we go and ALSO update our docs to reflect that) with proper syntax and accompanying screenshot! 


We want to make this a re-occurring practice with any changes to code, instructions, guidelines, tips, etc (similar to how we do here at Section). We want to work on keeping our repo up to date to help any new contributors, peer reviewers, or CMs with what changed and how they can fix it if need be.

**Comment by ahmadmardeni1** [comment]
> Lets also ask the other CM team mates - as it may just be confusing to me and not the other students.
> 
> @louisefindlay23
> 
> @section-engineering-education/content-moderator-team

I don't think that causes any confusion. As you said, we can update the docs.

**Comment by hborrelli1** [comment]
Great job @louisefindlay23!

**Comment by hectorkambow** [comment]
reverting for now

**Comment by hectorkambow** [comment]
@louisefindlay23  👋  Good afternoon Louise 

Wanted to follow up on this enhancement to see if we could further pinpoint the issue. 

If we could try to find out why it was causing that issue with the broken author pages to see if we can fix and merge again. 🚀 

cc @hborrelli1

**Comment by louisefindlay23** [comment]
Hi, @hectorkambow. I thought it might be worth creating a PR to merge this onto another branch of the main repo help to see if the issue can be reproduced there? On my forked repo, the issue isn't present.

**Comment by hborrelli1** [comment]
@louisefindlay23 I also noticed its not happening locally for me. I'm having trouble finding the reason it breaks some pages and not others.

**Comment by hectorkambow** [comment]
I do recall Harry having a similar issue (I believe) Not entirely sure (since forked repos may sometimes act differently) 

But If you have the latest (pulled) down it should work the same. 

My only guess (taking in mind that I am not a developer) is the similar syntax of authors. 

When Mike noticed that Ahmads author profile was not working - the only similarity I saw was that the URL had /authors/ in there. 

>An important question we should ask is: Do we want to continue with this feature for the time being (or do we table it for now and come back to it later) - to potentially work on other features. 

Does the value proposition merit the time/effort (knowing we have other items in the backlog that we could also begin to implement). 
@louisefindlay23 @hborrelli1 

cc @section-engineering-education/content-moderator-team

**Comment by hborrelli1** [comment]
@louisefindlay23 and @hectorkambow my guess is that by adding that new taxonomy, we are somehow overwriting the taxonomy of the author pages - likely only for authors that have the `authors` parameter in their front matter. Not sure if that is the case, but could be possible.

**Comment by louisefindlay23** [comment]
Yeah, possibly the `single.html` template isn't being applied since it's also a category/taxonomy.

Since we can't seem to reproduce the issue with the Authors Feed PR that Mike pointed out in our forked repos, and on a new branch in the main repo, would it be possible to reapply the PR but only add the `authors` parameter in my author profile so I can see if this triggers the issue and if so, better determine why this occurs and how to fix it as we haven't so far been able to reproduce this?

**Comment by louisefindlay23** [comment]
See #7436 for current progress.

**Pull request merged**
