### PR TITLE
How to Analyze Code Using Static Application Security Testing Method

### LINKED ISSUE #3538: Introduction to Static Application Security Testing Method
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Introduction to Static Application Security Testing Method

### Introduction paragraph (2-3 paragraphs):
This article will introduce a reader to application vulnerability testing, outlining the various ways of performing the same. The article will further focus on the static secutity testing method outlining how it works and its advantages.
This article will try to make a brief comparison between the static testing method and dynamic method and any other methods in existences.

### Key takeaways: 
The reader should master:
1. What is SAST
2. How SAST works
3. Advantages and Disadvantages SAST
4. Differences between SAST and DAST

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by RuthAMare**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #3538.

### CODE REVIEW

**Comment by hectorkambow** [comment]
@RuthAMare 

Is this article complete it seems rather light on substance??

**Comment by RuthAMare** [comment]
@hectorkambow , yes it is complete.
Its just a basic walkthrough introduction to Security testing.
But if there's anything you'd like me to enhance, i'll gladly do so.

**Comment by paulodhiambo** [comment]
@RuthAMare as @hectorkambow stated the article seems incomplete. Please add an example on how to use sast to analyze code.

**Comment by RuthAMare** [comment]
Hey @paulodhiambo and @hectorkambow 
I have enhanced the content to be a bit more informative and rich on substance.
Thanks.

**Comment by ahmadmardeni1** [comment]
👋 Good afternoon
There appear to be many sentences in this article that are taken verbatim from [third-party sources](https://www.synopsys.com/glossary/what-is-sast.html). We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).
We're really looking for unique/original content.

cc @paulodhiambo @hectorkambow 

[How to Analyze Code Using Static Application Security Testing Method](https://github.com/section-engineering-education/engineering-education/files/7136367/New.Scan.12_01.PM.Copyleaks.Report.1.pdf)

**Pull request closed without merging**
