### PR TITLE
Constuctors and init block in kotlin

### LINKED ISSUE #4978: [KOTLIN ] Constructors and Init blocks in Kotlin
#### Proposed title of article
 Constructors and Init blocks in Kotlin

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Effective Kotlin reguires the use of classes we are going to talk about how to Instatiate objects using Constructors and the init Block
 The Constructor will initialize new objects or instances of the class and  we are going to cover the Best practices in object oriented programming

#### Key takeaways 
1. Understanding init block in kotlin
2. How to instantiate objects using constructors 
3. Best practices for object oriented programming(OOP)

#### Article quality
I am going to produce an article that is well understandable by the users making them understand what does the Init block do in Kotlin and when to use the it

#### References
N/A

### PR DESCRIPTION
**Pull request by kamothosimon**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #issue-number`

This closes #4978
> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by john-amiscaray** [comment]
Hello, @kamothosimon welcome to the program nice to see a new contributor. Keep in mind that your first article will likely be a bit of a learning process so don't be discouraged if I give you many corrections or ask for many revisions, the same happened with me and my first article. This is just so you can learn better for next time and produce better work. Of course, we shouldn't expect your greatest work the very first time. Let me know throughout the review process if you have any questions, comments, or concerns. Thanks.

**Review by john-amiscaray — CHANGES_REQUESTED** [review]
Please implement my requested revisions before we continue the review. As part of our standard procedure, I will be closing this pull request to open space in the queue while you edit your article. **This does not mean your article is rejected for publication. Once you are done editing, please open a new pull request and ping me in the comments of it.**

If you have any questions and/or need assistance in implementing my feedback, feel free to message me via Slack.

**Comment by kamothosimon** [comment]
@john-amiscaray I've completed the necessary changes, and you may now open it

**Comment by john-amiscaray** [comment]
@kamothosimon please open a new pull request instead. That is a part of the standard procedure here.

**Comment by john-amiscaray** [comment]
> @kamothosimon please open a new pull request instead. That is a part of the standard procedure here.

Be sure to ping me in the comments of it so I can find it and other reviewers know that I'm assigned to it

**Pull request closed without merging**
