### PR TITLE
What are White-Hat and Black-Hat SEO Techniques?

### LINKED ISSUE #2458: What are White-Hat and Black-Hat SEO Techniques?
### Proposed title of article
What are White-Hat and Black-Hat SEO Techniques?

### Introduction paragraph (2-3 paragraphs):
Search Engine Optimization(SEO) is a kind of internet advertising method in which the websites are optimized to enhance the quality and quantity of their search engine traffic. It is beneficial due to the fact that a website will get hold of extra traffic from a search engine by getting ranked better at the Search Engine Results Page(SERP). This article will address two types of SEO techniques namely, White-Hat and Black-Hat.

White hat SEO technique is the way of using optimization techniques that comply with the policies and rules given by the search engines. Similarly, black hat SEO technique is the way of using optimization techniques that do not comply with the policies and rules given by the search engines. 

### Key takeaways: 
The reader will be able to understand:
- What is SEO?
- How does it help?
- White-Hat and Black-Hat SEO Techniques
- Functionalities of the same
- Which one to opt for?

### References: 
https://www.weidert.com/blog/white-hat-seo-black-hat-seo

### PR DESCRIPTION
**Pull request by kvardhan10**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2458

### CODE REVIEW

**Comment by kvardhan10** [comment]
@ahmadmardeni1 New PR is up🚀
@collins-a index.md is updated. If any more changes are required let me know🙌

**Comment by raboba2re** [comment]
@hectorkambow  I will like to review this article.

**Comment by collins-a** [comment]
> @hectorkambow  I will like to review this article. 

Hey @raboba2re, unfortunately this PR happens to be a duplicate of a PR that I was already reviewing.

**Comment by raboba2re** [comment]
@collins-a  no problem. thank you 

CC @hectorkambow

**Review by collins-a — COMMENTED** [review]
@kvardhan10 thank you for making the changes requested. However, you have two hero images. Please delete one before we move to the next stage.

**Comment by kvardhan10** [comment]
@collins-a Done!

**Review by collins-a — APPROVED** [review]

**Comment by hectorkambow** [comment]
Overall nice work 👍  

The topic was borderline - but it may be helpful to a lot of our EngEd contributors as reference to get more traction on their articles.

**Pull request merged**
