### PR TITLE
Filter Machine with Vanilla JavaScript

### LINKED ISSUE #2452: Filter Machine with Vanilla JavaScript
### Proposed title of article
Creating functional filter/search feature with JavaScript

### Introduction paragraph (2-3 paragraphs):
In this article we will be building a filter bar which respond to user search in real time using vanilla javascript. Most amazing part is the step by step explanation of each code snippet

### Key takeaways: 
- Readers will be able to build search/filter app with JavaScript
- Improve CSS and HTML skills
- implement new JavaScript methods
- Learn how to use online tools to code

### References: 
N/A

### PR DESCRIPTION
**Pull request by Taiwrash**
### Article checklist

This fixes #2452 
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by hectorkambow** [comment]
@Taiwrash 
Good afternoon and thank you for submitting your article for publishing. It has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it.  🚀

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by Taiwrash** [comment]
> plagiarism check done

Is this question for me?

**Comment by adrianmurage** [comment]
> 
> 
> > plagiarism check done
> 
> Is this question for me?
@Taiwrash 
No,
Just a confirmation that @hectorkambow has done the plagiarism check

**Comment by adrianmurage** [comment]
@Taiwrash 
You need to add your author page 

Check the [author directory](https://github.com/section-engineering-education/engineering-education/tree/master/content/authors) to see how it's done

**Comment by Taiwrash** [comment]
> @Taiwrash
> You need to add your author page
> 
> Check the [author directory](https://github.com/section-engineering-education/engineering-education/tree/master/content/authors) to see how it's done

I just make a PR to add myself as an author

**Comment by hectorkambow** [comment]
> > @Taiwrash
> > You need to add your author page
> > Check the [author directory](https://github.com/section-engineering-education/engineering-education/tree/master/content/authors) to see how it's done
> 
> I just make a PR to add myself as an author. See below link to the PR #2886
> 
> @hectorkambow @adrianmurage

Thank you for adding your author info - those files could have gone into this PR - so they would all be merged/published at the same time. 

@Taiwrash 

cc @adrianmurage

**Comment by hectorkambow** [comment]
@adrianmurage  

Is this article ready for a final review?

**Comment by Taiwrash** [comment]
> > > @Taiwrash
> > > You need to add your author page
> > > Check the [author directory](https://github.com/section-engineering-education/engineering-education/tree/master/content/authors) to see how it's done
> > 
> > 
> > I just make a PR to add myself as an author. See below link to the PR #2886
> > @hectorkambow @adrianmurage
> 
> Thank you for adding your author info - those files could have gone into this PR - so they would all be merged/published at the same time.
> 
> @Taiwrash
> 
> cc @adrianmurage

Fixing this right away. @hectorkambow  thanks for your feedback

**Comment by Taiwrash** [comment]
> @Taiwrash
> You need to add your author page
> 
> Check the [author directory](https://github.com/section-engineering-education/engineering-education/tree/master/content/authors) to see how it's done

Author page added to the right branch and everything fixes @hectorkambow  @adrianmurage

**Comment by adrianmurage** [comment]
@Taiwrash 
Before we can mark your article as ready for final review, it needs a **hero image**

**Comment by Taiwrash** [comment]
> @Taiwrash
> Before we can mark your article as ready for final review, it needs a **hero image**

Hero image added @adrianmurage @hectorkambow  thanks for your supports

**Comment by adrianmurage** [comment]
@Taiwrash 
Good job on your first contribution. 
Take note of the improvements you need to make in regard to grammar and sentence structure in your future contributions.
I look forward to seeing more of your work!

**Comment by ahmadmardeni1** [comment]
Welcome to Section EngEd and congrats on your first tutorial 🎉

Thank you for the review @adrianmurage

**Pull request merged**
