### PR TITLE
react-component-instantiation

### LINKED ISSUE #4847: React Component  Instantiation
#### Proposed title of article
React Components  Instantiation

#### Proposed article introduction
There are different types of react components: Functional Components,  Class Components, Pure Components and Higher-Order Components.React Component is a small,reusable chunk of code that is responsible  for one job which often involves rendering HTML.
JSX  stands for JavaScript XML. JSX  allows us to write HTML in React. JSX makes it easier to write and add HTML in React. JSX elements can  be either HTML like or component instances .JSX uses capitalization to distinguish between the two .That is the react specific reason why component class names must begin with capital letters.In JSX that first letter means its a component instance and not an HTML tag.In the case of the class component, React creates an instance of the class using the `new` keyword.

#### Key takeaways 
- What is component instantiation
- How to instantiate a component using react
- Difference between HTML like  and Component instances in JSX elements
- New keyword meaning and how it is used in react
- How React creates an instance of class using `new` keyword

#### Article quality
In this article the reader will learn about `new` keyword in react.js and how it is used.The reader will also learn how to instantiate react components ,what is react components and the  difference between HTML like  and Component instances in JSX elements

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by 1-creator**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?
This closes #4847

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Please always use the template provided by us.
I edited your initial comment and added the template. Check what matches your article.

**Comment by 1-creator** [comment]
sure,thanks

**Comment by jumamiller** [comment]
@1-creator, the article is too short, could you add more content?

**Comment by 1-creator** [comment]
Sure, I will

**Comment by 1-creator** [comment]
@jumamiller I have added more content.

**Comment by WanjaMIKE** [comment]
@1-creator Please ensure that you go through the community's documentation to avoid such issues which usually impact quality

**Comment by 1-creator** [comment]
Okay

**Review by jumamiller — CHANGES_REQUESTED** [review]
@1-creator, you have not explained the codes very well. For example, you inform readers of instances created in most cases, while you have a couple of lines with methods and properties.

**Comment by 1-creator** [comment]
@jumamiller I have explained the code check it out.Thanks

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Review by jumamiller — CHANGES_REQUESTED** [review]
Hello @1-creator, apart from inline comments, could you just explain the code clearly? Readers don't pay attention to comments!

**Comment by 1-creator** [comment]
Hello @jumamiller I made the suggested changes.

**Comment by hectorkambow** [comment]
@jumamiller 

Can we get a status on the PR - if it needs any more revisions - lets consider closing the PR to allow the author the proper time to make the required edits. 

Then that can be submitted via a NEW pull request.

**Comment by jumamiller** [comment]
Hello @1-creator, I will close this article for now, kindly ensure you explain your codes pretty well. I also noticed that your paragraphs have single sentences(not all cases). Kindly polish the article and ping me here when done to reopen!

**Comment by 1-creator** [comment]
Ok sure

**Pull request closed without merging**
