### PR TITLE
Encapsulation in C++

### LINKED ISSUE #4200: Encapsulation in C++
**Introduction**
`Encapsulation` is the process of wrapping together code with similar properties. Depending on the language you are using, encapsulation may pose different syntax in relation to the language used. In this article, we are going to look at how we can achieve encapsulation by the use of C++ language. 

By use of clear examples and explanations, we will also see how data hiding is done and its relation to encapsulation. We'll also take a look at roles of access specifies in relation to encapsulation.

**Key Takeaways**
By the end of the article, the learner should be able to understand.
1. Introduction to Encapsulation
2. Roles and Importance of Encapsulation
3. Data Hiding in relation to Encapsulation
4. Roles of Access Specifiers in Encasulation

**Reference**
N/A

### PR DESCRIPTION
**Pull request by jamarh35**
This Closes #4200

### CODE REVIEW

**Comment by zolomohan** [comment]
Hi @jamarh35. Welcome to Section EngEd 😄 

Encapsulation is a pretty basic concept in programming languages. There are numerous amount of resources on this topic.
Is there something you can add to make this article unique/original?

cc @section-engineering-education/content-moderator-team

**Comment by jamarh35** [comment]
Greetings @zolomohan 
In the article, I will add an explanation of how encapsulation is implemented. Here there will be the use of a real-life code snippet example that will help the user understand more about encapsulation. Moreover, I'll add a detailed description of the types of encapsulation. Lastly, the article will ensure the user understands how encapsulation relates to inheritance. This will be achieved by highlighting the differences and similarities of both encapsulation and inheritance.

**Comment by jamarh35** [comment]
Hello @zolomohan 
I have made the requested addition.
The article is now ready for review.

**Comment by ahmadmardeni1** [comment]
Why did you delete the template before submitting your PR? @jamarh35

**Comment by jamarh35** [comment]
Greetings @ahmadmardeni1 
I did not delete any template... The template checkboxes were empty by default by the time of submitting the PR

**Comment by zolomohan** [comment]
> Greetings @zolomohan In the article, I will add an explanation of how encapsulation is implemented. Here there will be the use of a real-life code snippet example that will help the user understand more about encapsulation. Moreover, I'll add a detailed description of the types of encapsulation. Lastly, the article will ensure the user understands how encapsulation relates to inheritance. This will be achieved by highlighting the differences and similarities of both encapsulation and inheritance.

Hi @jamarh35

Since Encapsulation is programming 101, there's a lot of resources for this topic available on the internet. I don't think this topic will provide a lot of value to our program. Please consider working on another topic. 

If you have a unique view on Encapsulation that you can enhance this article with and make it stand out from the rest, please let me know.

**Pull request closed without merging**
