### PR TITLE
How to send emails using emailjs in vue3

### LINKED ISSUE #5580: How to send emails using Emails.js in Vue3
### Topic Suggestion
How to send emails using Emails.js in Vue3

### Writing sample(s): 
https://adanna-io.medium.com/checking-your-vue-application-with-the-vue-devtools-7563fb750f46
https://adanna-io.medium.com/angular-vue-or-react-which-is-better-and-why-d4e590fc72f8
https://ada.hashnode.dev/libraries-you-should-know-to-add-beauty-to-your-website-appearance-as-a-front-end-developer

#### Proposed title of article
How to send emails using Emails.js in Vue3

#### Proposed article introduction
[LANGUAGES] How to send emails using Emails.js in Vue3
Email.js is a javascript library that helps send emails using different client-side technologies. It is completely serverless and easy to set up. It is a library that supports multiple email services like Gmail, Fastmail, Outlook, Yahoo, and many others whichever suits our needs.

The Email.js library becomes very handy when receiving and sending emails. Let's say you have a portfolio and in there, you have a contact form where your potential employer can connect with you, with email.js all you have to do is connect it to one of the supported email services, create an email template and use it to trigger an email. So any message sent through that contact form will be sent right into your mailbox. No backend code is needed.

I will be walking you through the steps of signing up, choosing a supported email service, creating a template and also, showing you how to set it up on a Vue application using Vue3 composition API.

#### Key takeaways 
  1.  For Frontend developers having little or no knowledge about server-side technologies, By the end of this article one will be able to know how to integrate this library in Vue of which no server-side code is needed.
   2. After reading this article the reader should be able to know and understand how DOM manipulation is done on Vue3 as we will be manipulating the form element in the app to fully see the library's power in action.

#### Article quality
Vue3 is a new version of Vuejs that was recently released as a more efficient way of building Vue applications. There are not enough tutorials out there about it. That is to say, a whole lot of developers are yet to get a grasp of it. In this article I will be using this library with a different approach. On the email.js documentation, integrating it on a Vue3 application is not available. I refactored the code to make it work on vue3 which is a lot easier. I will not just be talking about how to use this library on a Vue application, I will also be talking about how to use this library specifically for Vue3.

#### References
(https://www.emailjs.com/docs/)

### PR DESCRIPTION
**Pull request by mercybassey**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #5580

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
This article shows a high level of plagiarism. Some sentences and code have been directly copied from other online sources.
We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.
[New Scan 6_15 AM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7791737/New.Scan.6_15.AM.Copyleaks.Report.pdf)

**Comment by mercybassey** [comment]
Can this PR be reopend after making necessary corrections? This article is no where on the internet.

**Comment by geoffrey45** [comment]
Hello @mercybassey Your article can be still be reviewed for publishing if you work on the plagiarism. 

Push your final work and mention @WanjaMIKE in this pull request for plagiarism recheck.

**Comment by mercybassey** [comment]
@WanjaMIKE I have worked on the plagiarism and I have pushed my final work. Thank you @WanjaMIKE

**Pull request closed without merging**
