### PR TITLE
Introduction to Deep learning using python 

### LINKED ISSUE #4168: Introduction to Deep Learning using Python
#### Proposed title of article
Introduction to Deep Learning with Python. 

#### Proposed article introduction

Deep learning is a type of machine learning  and Artificial intelligence based on artificial neural network. For one to achieve high level features from data it is essential to use Deep learning. It imitates the way humans gain certain types of knowledge which then becames useful in data science which includes statistics and predictive modeling. 
    This article will be a very important tool to get you started in the field of Deep learning.You will be guided through every single step of Deep learning. What you thought was hard will be the simplest thing you have ever tried to understand.A journey of a thousand steps begins with a single step. This is your first step into the journey of Deep learning. 

#### Key takeaways 
a) what is deep learning and why python for deep learning. 
b) How deep learning works. 
c) Application Areas of deep learning. 
d) The need for deep learning today
e) instalation of softwares and tools to get you started with deep learning. 

#### Article quality
This article will give simple and understandable examples of deep learning and how to use deep learning using simple and understandable grammar. It will make it easier for someone who doesn't know programming to understand and be more interested to venture in to this field. 

#### References
N/A

### PR DESCRIPTION
**Pull request by mbuguac**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4168

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Kayere** [comment]
Plagiarism check done ✔️

**Comment by mbuguac** [comment]
Hello where are you with the Article review?? @Kayere @mercymeave

**Review by mercymeave — CHANGES_REQUESTED** [review]
Good evening @mbuguac :wave: 

Thank you for submitting your first article for review. I will be your reviewer. However, I have a few concerns. 

In issue  #4168 you said that you would explain every code you write and use a real-life example. Deep learning is a wide and deep topic that covering it in such an abstract way might not be very helpful for our readers. Take a look at [this](https://www.datacamp.com/courses/introduction-to-deep-learning-in-python) and [this](https://www.simplilearn.com/tutorials/deep-learning-tutorial/deep-learning-with-python) articles, how different is yours from them?

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to pursue another more in-depth topic - or continue working on this one by flushing it out a bit more by working on a real-world example explained in an easier language.

We will be closing the PR simply to make room in the queue - but we can gladly reopen it anytime once the article is publish ready

**Comment by mbuguac** [comment]
Thanks for your feedback I will look on how I can give examples of codes
and explain them better.

**Comment by mercymeave** [comment]
Hello, whats your progress?

**Comment by mbuguac** [comment]
Am still in the process of writing an example of a program I should be
through by thusday.

**Comment by mercymeave** [comment]
Hello @mbuguac 

Thank you for taking the time to work on this PR. However, it is taking unusually long in the queue. We will be closing this PR to create more room for other well-polished ones. 

This is not a problem. We can re-open the PR once it is done. Ping me via slack or here to re-open it once you get done.

**Comment by mbuguac** [comment]
It is done am uploading it today. You ca please reopening. I apologize for
the delay

**Comment by mbuguac** [comment]
Thank you for your response. Am have a bit of a challenge with my internet.
I will let you know when I am ready so that you can reopen.

**Comment by mbuguac** [comment]
@mercymeave  i am now ready to push

**Comment by mercymeave** [comment]
Hello @mbuguac 

I highly recommend that you open a new PR for the changes. With the recent changes to improve our review times we have been rolling out - we can treat it as a new PR.

It is not fair to the other PRs and authors who have gone through our DOCS, past published articles, and worked hard to submit a fully polished article.

Its not fair that they have to continue waiting while the sub-par articles get worked on, revised, and published before theirs

**Comment by mbuguac** [comment]
Thank you. Let me do that..

**Pull request closed without merging**
