### PR TITLE
Getting Started with DBSCAN Clustering in Python

### LINKED ISSUE #4677: Getting Started with DBSCAN Clustering Algorithm in Machine Learning
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed article introduction

DBSCAN is a more advanced clustering algorithm compared to the K-means clustering and the hierarchical clustering algorithms. First of all, DBSCAN stands for ''Density-Based Spatial Clustering of Applications with Noise''. Unlike the K-Means algorithm, the best thing with this algorithm is that we need not provide the number of clusters required prior. DBSCAN algorithm groups points that are close to each other together based on distance measurement, usually *Euclidean distance* and a *minimum number of points*. An important property of this algorithm is that it helps us track down the outliers as the points in low-density regions. The DBSCAN algorithm requires two parameters, i.e.,

 * **Eps:** This is the maximum distance between two points for them to be considered as a neighbour. It is considered as a threshold for considering two points as neighbours. If the distance between any two points is less than or equal to the *Eps*, these points are considered neighbours.  
* **MinPoints:** This refers to the minimum number of points required to form a cluster. It is considered as a threshold for considering a cluster as a cluster. Basically, if the number of points in a cluster is greater than or equal to the *MinPoints*, this cluster is considered as a cluster.

## Types of Points in a DBSCAN Cluster
There are three types of points after the DBSCAN clustering is complete. Let's understand these points:
1. **Core:** It is a point with at least m points within distance n from itself. (what m and n are to be explained in the article)
2. **Border:** This point has at least one Core point at a distance n.
3. **Noise:** which is a point that is neither a Core nor a Border. And it has less than m points within distance n from itself.
   * Further explanation to be provided in the article

### DBSCAN Algorithm 
Finally, we will look at the algorithmic steps for DBSCAN. 
These algorithmic steps will be as follows:

* **Step 1:** Find all the neighbour points within *Eps* and identify the core points or visit with more than MinPts neighbours.
* **Step 2:** For each core point, if it is not assigned to a cluster, create a new cluster.
* **Step 3:** Find recursively all its density connected points and assign them to the same cluster as the core point.
* **Step 4:** Iterate through the remaining unvisited points in the dataset. Those points that do not belong to any cluster are noise.
  
In the article, we shall discuss the above intuition in detail, make every subsection clear enough, and then implement our algorithmic steps above in python to obtain our clustering model.

#### Key takeaways 
1. The learner will be able to define the DBSCAN  algorithm.
2. The learner will know the advantages of this algorithm over the other clustering algorithms.
3. The learner will know the Parameters in the DBSCAN Model.
4. The learner will know the types of points in the DBSCAN clustering.
5. Finally, the learner will understand the flow of the DBSCAN algorithm and how to implement it in python.

#### Article quality
This article will focus on the clarity of the concept and delivery of the well-structured content. Therefore, no unnecessary details will be included in this material.
#### References
N/A
### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Daniel695**
This closes #4677

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
The plagiarism score is quite high. Please correct the highlighted areas. Thanks

[New Scan 12_30 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7512703/New.Scan.12_30.PM.Copyleaks.Report.pdf)

**Review by jerimkaura — COMMENTED** [review]
Hello @Daniel695 :wave: 

Thank you for writing such a clear article :rocket: It is easy to read and has minimum errors. We encourage our authors to write such straight articles :+1: 

I will proceed to tech review.

**Comment by jerimkaura** [comment]
Hello @WanjaMIKE  would you please do a plagiarism check on this PR?

**Comment by WanjaMIKE** [comment]
Plagiarism check done. Please correct the highlighted areas
[New Scan 6_47 AM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7623550/New.Scan.6_47.AM.Copyleaks.Report.pdf)

**Comment by hectorkambow** [comment]
@Daniel695 

cc @jerimkaura

**Comment by Daniel695** [comment]
@WanjaMIKE  
Plagiarism is now corrected

**Review by jerimkaura — APPROVED** [review]
Hello @lalith1403 

Would you please take a final look into this PR

**Comment by hectorkambow** [comment]
I can jump on this one @lalith1403

**Comment by hectorkambow** [comment]
If you have not started 👍 
For final review

**Comment by lalith1403** [comment]
Sure @hectorkambow. Thanks 😊

**Comment by hectorkambow** [comment]
👍  

Overall nice work gents

**Pull request merged**
