### PR TITLE
Azure devops api development

### LINKED ISSUE #5926: [API] Azure DevOps API deployment
#### Proposed title of article
Azure DevOps.NET API deployment

#### Proposed article introduction

Workflow management, code collaboration, and app development and deployment are all made easier with Azure DevOps. Collaboration between developers, project managers, and other stakeholders is fostered through Azure DevOps.
We'll learn how to continually integrate and deploy.NET APIs using Azure DevOps.

#### Key takeaways 
- By the end of this instructional exercise we will have covered the following:
1. Setting up SQL Azure database
2. Set up an Azure Application.
3.  Using Azure DevOps, create a Build and Release pipeline.
4. Update .NET app
5. Initiate the Pipeline

#### Article quality
By reading this article learners will understand how Azure DevOps simplifies the management of servers for application deployment. As well as how each machine communicates with Azure DevOps to coordinate app deployment. We will have a clear explanation with well illustrated screen shots to allow learners to understand every bit stated above.

#### References
N/A

### PR DESCRIPTION
**Pull request by fabulousDesigns**
#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #5926

### CODE REVIEW

**Comment by Dawe-7** [comment]
@fabulousDesigns, thanks for pinging me via slack. I'd review your article but i have to clear my backlog first before taking up any more reviews.  Please wait until a peer-reviewer pings you to get started with the review.

**Comment by srishilesh** [comment]
Hey @fabulousDesigns ,

The peer-reviewers are working towards completing existing reviews to take up more. Please wait patiently until a peer-reviewer pings you to get started.

Thanks.

**Comment by louisefindlay23** [comment]
Plagiarism check complete

**Comment by WanjaMIKE** [comment]
You have too many images in this article and less content. Could you check on how you can balance it out and then create a duplicate PR. Thanks

**Pull request closed without merging**
