### PR TITLE
Securing Localhost URLs using Ngrok and self-signed SSL Certificates in Django

### LINKED ISSUE #7364: Securing Localhost URLs using Ngrok and self-signed SSL Certificates in Django
### Writing sample(s): 
https://www.section.io/engineering-education/authors/phina-kersly/

#### Proposed title of the article
Securing Localhost URLs using Ngrok and self-signed SSL Certificates in Django

#### Proposed article introduction
Let us say you are a developer and you need to show your locally running website to someone who is not close to you. One of the best ways is to use Ngrok to expose the local server to the entire internet by a single command.

Nevertheless, that is just one case. A second case comes when working with images stored locally that need to be consumed in some other frontend application. For example, some frontend tools like android studio do not accept images from insecure sites( with HTTP instead of HTTPS). So we need to secure the endpoints we expose to the consumers to solve this.

This article aims at building a custom Django application that exposes endpoints and configures a self-signed SSL =certificate that ensures that the endpoints are secured. Finally, it will direct the reader on how to expose the secured endpoint using Ngrok.

#### Key takeaways 
1. Wring a custom rest framework application
2. Exposing endpoints using Ngrok
3. Securing URLs with Django
4. Generating a self-signed SSL certificate

#### Article quality
This article combines Ngrok with the powers of locally self-signed certificates in a single Django application. While developing APIs, we need to consider that the exposed endpoints are secure. This article intends to cover how exactly to do that on Django.

#### References
Please list links to any published content/research you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by phinaomondi**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #7364

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by lalith1403** [comment]
plagiarism check done ✔️

**Review by jerimkaura — APPROVED** [review]
Great article 🎉

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
@phinaomondi 
👏 Very well done 🚀

Be sure to see your live published article on the site (it should be live within a 10-30 mins).

To give your article a boost in page engagement - share it across your social site (linkedin/twitter) and tag the EngEd program so we can also share it and give it some traction as well!

_**If you have not done so already - consider adding a skill section to your author page. This will go a long way for potential future employers.**_

**Pull request merged**
