### PR TITLE
 controlling-web-pages-visible-to-different-users-using-php

### PR DESCRIPTION
**Pull request by davidokoth006**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by mercymeave** [comment]
Hello @davidokoth006 

Thanks for submitting your first article.

Please check the checkboxes to show that you have completed the task required before submitting a PR. Also, link this PR to its respective issue.

Thanks.

**Comment by davidokoth006** [comment]
I do not understand why merging is blocked. since I'm a beginner, I would request that you elaborate more on "merging is blocked" and perhaps guide me on how I can go around it, please.

**Comment by WanjaMIKE** [comment]
@davidokoth006 I think the merging issue will be handled by the CM side. Do not worry. Thanks

**Comment by davidokoth006** [comment]
Thanks you.

**Comment by WanjaMIKE** [comment]
Please add an author folder. Thanks

**Comment by WanjaMIKE** [comment]
I do not see a commit on this PR. Please push the author details

**Comment by davidokoth006** [comment]
I have already added authors details.

**Comment by hectorkambow** [comment]
@davidokoth006 

👋  good afternoon David - just noticed that this PR does not have an approved issue form (topic suggestion form) attached to it. 

The previous one was closed due to inactivity and it was never re-submitted (or approved).

**Comment by davidokoth006** [comment]
Hello
Can I re-submit the issue?

**Comment by WanjaMIKE** [comment]
@davidokoth006 No need for now

**Comment by davidokoth006** [comment]
Will the article progress from where it has reached now?

**Comment by hectorkambow** [comment]
Yes sir - we are just working out way up the queue now. 

Most if not all should be cleared out by the end of the month.

**Comment by hectorkambow** [comment]
But this topic will need a new topic suggestion form (to be approved) .

**Comment by davidokoth006** [comment]
Do I need to raise a new issue?

**Comment by hectorkambow** [comment]
@davidokoth006 

Yes sir - all PR must be 1st approved via an Topic suggestion form. 

https://github.com/section-engineering-education/engineering-education/issues/new?assignees=&labels=topic+suggestion&template=enged-content-idea-suggestion.md&title=

**Comment by WanjaMIKE** [comment]
Merged #7622 into master

**Comment by hectorkambow** [comment]
The pull request was merged (it auto closes) once the article is published. 

Can you please DM via Slack asap. 👍  

thank you
 @davidokoth006

**Pull request merged**
