### PR TITLE
Getting Started With Elarian

### LINKED ISSUE #4577: Getting started with Elarian
### Topic Suggestion
Getting started with Elarian

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Proposal Submission
This article 

#### Proposed title of the article
Getting started with Elarian JavaScript SDK

#### Proposed article introduction
Quality customer service is essential. For businesses to achieve this, it is usually a lengthy and time-consuming process. Elarian is a framework that simplifies how we build data-driven applications with quality customer engagement. With robust application services such as SMS, USSD, WhatsApp, Telegram bots, and M-Pesa fully integrated, the developers have a single unit of abstraction.

This article dives into the elarian JavaScript SDK where we build a USSD service in the test sandbox under the elarian dashboard.

For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

ONLY viable topics to pick from:
- API
- Artificial Intelligence
- Blockchain
- Containers
- Edge Computing
- Languages
- Machine Learning
- Networking
- Node.js
- Security

#### Key takeaways 
1. Introduction to Elarian framework
2. How to integrate JavaScript backend SDK with Elarian cloud services
3. Building an SMS service in Elarian

#### Article quality
My article goes beyond the documentation guide to create an interactive application. This article is well elaborated with less technical terms to enable beginners and experts to easily understand the elarian SDK.

#### References

N/A

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Qodestackr**
This fixes #4577

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Review by mercymeave — COMMENTED** [review]
Hello @Qodestackr 

Thank you for submitting such a great topic introducing new tech. I am proceeding to tech review.

**Review by mercymeave — APPROVED** [review]
Hello @Qodestackr 

Thanks for such a great article. Looking forward to more direct and resourceful articles from you.

This piece os ready for final review.

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
