### PR TITLE
Vue.js Vs React.js

### LINKED ISSUE #2182: Vue.js Vs React.js
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Vue.js Vs React.js

### Introduction paragraph (2-3 paragraphs):
Vue.js and React.js are both front-end JavaScript frameworks. React.js is the leading front-end framework. Each of these frameworks has its demerits and merits depending on its nature. 

Vue.js is a progressive framework that has more features than React. It is flexible in terms of its structure and easier in integrating with other tools. Vue.js recently uses typescript unlike where the first version was using JavaScript and typescript as optional. React.js is used for building UI with components. It allows for rendering and controlling content to the DOM. The React developers use JavaScript and JSX. The React.js developers use the architectural design of their choice. The difference between React and Vue.js lies in the way they are built, The tooling and the syntax. 

### Key takeaways: 
- What Vue.js entails
- What React.js entails
- Key similarities between Vue.js and React.js
- Advantages of using Vue.js and React.js as a front-end JavaScript Frameworks

### References:
N|A 

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by winlinda**
This fixes #2182

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by zolomohan** [comment]
Hi @winlinda. After taking a quick look at your article, it seems like you've just scratched the surface when it comes to comparisons. Your article should provide more value than existing articles. That's the goal of this program. 

You could go over much more differences from a technical standpoint:

- How the structure of projects in these frameworks differ
- How these frameworks bundle the code.
- How the syntax of components differs. You can explain these with examples. 

These are just from the top of my head. Build on these points and add more content to your article to improve the value your article provides to fellow developers.

**Comment by winlinda** [comment]
@zolomohan requested additional information done. Thank you

**Comment by winlinda** [comment]
Requested changes done. Thank you

**Comment by hectorkambow** [comment]
@winlinda 
Thank you for the article suggestion, however glancing over the written article here it may seem that this is a bit outside of our preferred published work. 

The article was a bit difficult to follow along - and it seems much of the information is readily available either via other blogs or the official documentation itself.

We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 
_**Please we would like to encourage you to suggest an alternate topic to explore**_ or re-work this on with a project in mind that highlights the core concepts of one or both to compare them. 🚀

**Comment by zolomohan** [comment]
@hectorkambow after a quick glance, I agree with you. There are tons of existing blog articles and videos covering the differences between these frameworks. Also, this article seems to have only covered the basic differences and I've noticed some grammatical issues too. 

We can close this for now until the author re-works the article or comes up with a new one.

**Comment by hectorkambow** [comment]
@winlinda We will closing this PR - just to clear up the queue - the article can still be worked on or a you can suggest a new one. 

Not a problem at all - if you'd like to modify this one we can re-open at any time.

**Pull request closed without merging**
