### PR TITLE
Android security rules

### LINKED ISSUE #4201: [Android] Implementing Security Rules In Android Applications
#### Proposed title of article
[Android] Implementing Security Rules In Android Application

#### Proposed article introduction
When you safeguard the data that you exchange between your app and other apps, or between your app and a website, you improve your app's stability and protect the data that you send and receive. 

The article is going to cover the security rules that are required to make an android app secured. It will cover on how to:
- Apply network security measures
- Disallow access to your app's content providers
- Store data safely
- Share data securely across apps
- Provide the right permissions
- Add a network security configuration
- Ask for credentials before showing sensitive information
- Apply signature-based permissions
All these ensures that the application's security is maintained as well as user's data. 

#### Key takeaways 
- What are the android security rules.
- Reasons for Android security rules.
- How to implement security rules.

#### Article quality
My article has covered a wide range of security rules in android. It also have hands-on practical codes showing the implementation of security rules.

#### References
https://developer.android.com/topic/security/best-practices

### PR DESCRIPTION
**Pull request by Collince-Okeyo**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4201

### CODE REVIEW

**Comment by Collince-Okeyo** [comment]
Hello @hectorkambow , @ahmadmardeni1  , @Kayere  the article is now ready for review. Please open it and assign a reviewer. Thanks in advance

**Comment by Kayere** [comment]
Hello @Collince-Okeyo

 Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Android security rules #5332 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7677531/Android.security.rules.5332.Copyleaks.Report.pdf)

**Comment by Collince-Okeyo** [comment]
Hello @Kayere , I have gone through the article and corrected the plagiarism.

**Review by jerimkaura — COMMENTED** [review]
Hello @Collince-Okeyo 

Thank you for such a great headstart into android security rules. I love how you collected the basics and provided examples of how to implement them. 

I have made some grammatical corrections that are worth looking at. In the meantime, I will process to tech review.

**Comment by Collince-Okeyo** [comment]
Thank you @jerimkaura , what about the plagiarism check. Will a second one be done.

**Comment by jerimkaura** [comment]
Yes one of the Content Moderators will do another plagiarism check.

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
FYI this is an article not really a tutorial. 
@Collince-Okeyo 

cc @jerimkaura  Please review our docs again to get a better understanding between an article and a tutorial. 👍  

🚀

**Pull request merged**
