### PR TITLE
Java Swing Components Set and Get Methods

### LINKED ISSUE #3162: Java Swing for Desktop Application
### Proposed title of article
Java Swing for Desktop Application 

### Introduction paragraph:
Java Swing is part of Java Foundation Classes. It is used to create window based application which makes it suitable for developing desktop based application. It is built on top of abstract windowing toolkit application programming interface written in Java programming language. 
In this article, I will demonstrate how the common Java swing components are used in desktop application development. We will learn the basic setters and getters methods of the Java Swing components commonly used in desktop application. At the end of the article we will be able to create a usefully application sample which can interact with a user. 

### Key takeaways: 
1.	Describing and defining Java Swing Components setters methods
2.	Describing and Defining Java Swing Components getters methods
3.	Getting Started with Java Swing Components Action and Event Methods

### References: 
https://www.javatpoint.com/java-swing
https://www.section.io/engineering-education/introduction-to-java-swing/

### PR DESCRIPTION
**Pull request by JosephAyoma**
Article describes common swing component setters and getters methods used in swing desktop application

### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #3162

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Plagiarism check done

**Review by Dawe-7 — CHANGES_REQUESTED** [review]
@JosephAyoma, Nice article. I've left some helpful suggestions that will improve the quality of your article. Ping me when you're done.

**Comment by JosephAyoma** [comment]
@Dawe-7 The requested changes have been made.

**Review by Dawe-7 — APPROVED** [review]
@hectorkambow,  this article is ready for final review.

cc: @Kayere

**Comment by hectorkambow** [comment]
Overall great job gents

Made some minor adjustments - please review to improve future articles and reviews. 👍 

@JosephAyoma 

cc @Dawe-7

**Comment by JosephAyoma** [comment]
Thank you @hectorkambow I will do as advised

**Pull request merged**
