### PR TITLE
How to implement binary search tree using python

### LINKED ISSUE #3015: How to implement Tree node classes and binary search tree in python
### Proposed title of article
How to implement tree nodes classes and binary search tree

### Introduction paragraph (2-3 paragraphs):
. In this article we will learn how to construct binary search tree using nodes and references in python
  iterating  in all the keys of  the tree in order we will have a parent and child nodes.
### Key takeaways: 
1, it gives an understanding of how to insert new code in the tree
2. Implementing  retrieval of a value in a key 
3. How to handle insertion of a duplicate key during a search
 4. Deleting of a key in our binary search tree.
 5. How to traverse a binary tree using the  traversal algorithm

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by samtecinnovator**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3015

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by samtecinnovator** [comment]
just want to ask if there are any updates

**Comment by samtecinnovator** [comment]
ping me if there are any updates.

**Comment by WanjaMIKE** [comment]
@adrianmurage do you need help with the review?

**Comment by adrianmurage** [comment]
@WanjaMIKE 
yes, kindly take over

**Comment by WanjaMIKE** [comment]
Okay

**Comment by WanjaMIKE** [comment]
@samtecinnovator you need to add a conclusion to the article. You also need to explain your code rather than just pasting it in the article. Thanks

**Comment by WanjaMIKE** [comment]
@samtecinnovator Please check the numerous changes I have made across the article to improve in your future submission. Thanks

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
👍 overall nice work - very detailed and straight forward tutorial  @samtecinnovator 
 
Please review and suggestions/changes made by your peer reviewer and/or myself during a final review. 

cc @WanjaMIKE 👍 great work - minor edits for structure - also added the new author.md paramater.

**Pull request merged**
