### PR TITLE
What is NetDevOps? Top NetDevOps Tools for your Windows Operating System

### LINKED ISSUE #3159: Top NetDevOps tools that are important for your Windows OS
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):

Most network engineers are known to love working in Linux-based environments.

This blog will teach the reader basic development toolset network developers need to set up your Windows workstation as a development environment for networking.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

Since network engineering is heavily carried on Other operating systems such as Linux, this article will help the network engineers who work on the Windows operating system to know and learn the tools they need to make it easier and faster to work as a network NetDevOp.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Wachira48**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Issue this PR closes

This closes #3159.

### CODE REVIEW

**Comment by louisefindlay23** [comment]
@Wachira48, please remember to fill in the `This closes #issue-number` in the Article Checklist by removing the backticks and replacing `issue-number` with the issue number of your topic suggestion so you can be correctly paid out and your topic suggestion closed when this has been merged. Have done this for you above.

**Comment by hectorkambow** [comment]
[What is NetDevOps Top NetDevOps Tools for your Windows Operating System #3390.pdf](https://github.com/section-engineering-education/engineering-education/files/7027914/What.is.NetDevOps.Top.NetDevOps.Tools.for.your.Windows.Operating.System.3390.pdf)


Minor sentences worth looking over 

@Wachira48 

plagiarism check done

**Review by collins-a — COMMENTED** [review]
Hey @Wachira48, thank you for the in depth article on NetDevOps and your patience with the review.

After conducting an initial review, I've noted that a beginner may struggle with the terminology of the article. Consider rephrasing parts of the article highlighted by [Hemingway editor](https://hemingwayapp.com/) that would reduce the grade to perhaps 9.

Also, consider adding a reference or two to add value to the reader in their research beyond the article.

Ping me when ready.

**Comment by hectorkambow** [comment]
@Wachira48 
Please take keen notes on all the changes and advice provided by your peer reviewer. 

>Thank you for jumping on the revision. 

Just as an FYI - please refrain from submitting PR (pull requests) before the article(s) are fully polished and ready to be published. 

All revisions and edits should be made on your (forked) repo - we can ask our community peers to review our work there - but we should only be submitting articles once they are ready to be published. 

Our team of peer reviewers do NOT provide revisions services - we can only review the article for accuracy of content and code. 
Thank you v much 🚀 

cc @collins-a

**Comment by Wachira48** [comment]
> Hey @Wachira48, thank you for the in depth article on NetDevOps and your patience with the review.
> 
> After conducting an initial review, I've noted that a beginner may struggle with the terminology of the article. Consider rephrasing parts of the article highlighted by [Hemingway editor](https://hemingwayapp.com/) that would reduce the grade to perhaps 9.
> 
> Also, consider adding a reference or two to add value to the reader in their research beyond the article.
> 
> Ping me when ready.

@Collince-Okeyo. There are several links I referenced whenever necessary in areas that I believe a reader should seek more info.

I have tried rephrasing some sentences, unfortunately, some Hemingway highlighted sentences are hard to change as this will change the real meaning some sentences try to converse.

**Comment by Wachira48** [comment]
@collins-a

**Comment by hectorkambow** [comment]
> > Hey @Wachira48, thank you for the in depth article on NetDevOps and your patience with the review.
> > After conducting an initial review, I've noted that a beginner may struggle with the terminology of the article. Consider rephrasing parts of the article highlighted by [Hemingway editor](https://hemingwayapp.com/) that would reduce the grade to perhaps 9.
> > Also, consider adding a reference or two to add value to the reader in their research beyond the article.
> > Ping me when ready.
> 
> @collins-a . There are several links I referenced whenever necessary in areas that I believe a reader should seek more info.
> 
> I have tried rephrasing some sentences, unfortunately, some Hemingway highlighted sentences are hard to change as this will change the actual meaning some sentences try to converse.

Agreed - Hemmingway app should be used a guide - as it may be a bit off sometime. 


With that in mind - the article should have enough information and references that a beginner could follow along. 

If needed a prerequites can be added in the beginning to explain to the reader the level they should be at before following along. 

Lets recall that this will be used to build your portfolio for potential employers. 

@Wachira48 

cc @collins-a

**Comment by collins-a** [comment]
> > Hey @Wachira48, thank you for the in depth article on NetDevOps and your patience with the review.
> > After conducting an initial review, I've noted that a beginner may struggle with the terminology of the article. Consider rephrasing parts of the article highlighted by [Hemingway editor](https://hemingwayapp.com/) that would reduce the grade to perhaps 9.
> > Also, consider adding a reference or two to add value to the reader in their research beyond the article.
> > Ping me when ready.
> 
> @collins-a . There are several links I referenced whenever necessary in areas that I believe a reader should seek more info.
> 
> I have tried rephrasing some sentences, unfortunately, some Hemingway highlighted sentences are hard to change as this will change the actual meaning some sentences try to converse.

> > > Hey @Wachira48, thank you for the in depth article on NetDevOps and your patience with the review.
> > > After conducting an initial review, I've noted that a beginner may struggle with the terminology of the article. Consider rephrasing parts of the article highlighted by [Hemingway editor](https://hemingwayapp.com/) that would reduce the grade to perhaps 9.
> > > Also, consider adding a reference or two to add value to the reader in their research beyond the article.
> > > Ping me when ready.
> > 
> > 
> > @collins-a . There are several links I referenced whenever necessary in areas that I believe a reader should seek more info.
> > I have tried rephrasing some sentences, unfortunately, some Hemingway highlighted sentences are hard to change as this will change the actual meaning some sentences try to converse.
> 
> Agreed - Hemmingway app should be used a guide - as it may be a bit off sometime.
> 
> With that in mind - the article should have enough information and references that a beginner could follow along.
> 
> If needed a prerequites can be added in the beginning to explain to the reader the level they should be at before following along.
> 
> Lets recall that this will be used to build your portfolio for potential employers.
> 
> @Wachira48
> 
> cc @collins-a

@Wachira48 thank you for the changes. As mentioned, a prerequisites section would be great to inform readers of the technical level to expects.

I acknowledge the numerous links to additional resources. However, in the future, consider having a _further reading_ section at the end of the article as:
1. A reader may not necessarily want to backtrack through the article to seek links to further information on a specific concept.
2. A reader may find value in having a few related articles, guides, etc. to be their next read.

I suggest adding a prerequisites section and we'll be ready for the final review.

**Comment by hectorkambow** [comment]
@Wachira48 

Good afternoon and thank you for submitting your topic to the EngEd program and jumping on your revisions. 
As a rule of thumb - we can only accept articles (pull requests) that are fully polished and complete articles - articles that are ready to be published.
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue). 

@collins-a  if it seems this PR is still quite a bit aways from being completed. We will be closing this PR to allow @Wachira48  the time to revise and polish the article to be published. 

If closed - once it is completed (and ready to be published) go ahead and please re-submit as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 
 
👍

**Comment by Wachira48** [comment]
> @Wachira48
> 
> Good afternoon and thank you for submitting your topic to the EngEd program and jumping on your revisions.
> As a rule of thumb - we can only accept articles (pull requests) that are fully polished and complete articles - articles that are ready to be published.
> 
> All revisions and edits should be completed on your own forked repo (as to not take up room in the queue).
> 
> @collins-a if it seems this PR is still quite a bit aways from being completed. We will be closing this PR to allow @Wachira48 the time to revise and polish the article to be published.
> 
> If closed - once it is completed (and ready to be published) go ahead and please re-submit as a new PR (and you can add the duplicate label) and ping the reviewer and myself.
> 
> 👍

@hectorkambow @collins-a, I have added the two sections, 
Prerequisites and Further reading

**Review by collins-a — APPROVED** [review]

**Comment by collins-a** [comment]
> @Wachira48
> 
> Good afternoon and thank you for submitting your topic to the EngEd program and jumping on your revisions.
> As a rule of thumb - we can only accept articles (pull requests) that are fully polished and complete articles - articles that are ready to be published.
> 
> All revisions and edits should be completed on your own forked repo (as to not take up room in the queue).
> 
> @collins-a if it seems this PR is still quite a bit aways from being completed. We will be closing this PR to allow @Wachira48 the time to revise and polish the article to be published.
> 
> If closed - once it is completed (and ready to be published) go ahead and please re-submit as a new PR (and you can add the duplicate label) and ping the reviewer and myself.
> 
> 👍

@hectorkambow I'm satisfied with the changes made, the article is technically competent and gives enough detail on NetDevOps tools and more. The only caveat would be the technical nature of the article, making it difficult to simplify the terminology used without losing some meaning. Otherwise, good to go!

CC. @Wachira48

**Comment by hectorkambow** [comment]
@Wachira48 
Please be sure to go through my final edits to improve future articles and reviews 👍 
cc @collins-a

**Pull request merged**
