### PR TITLE
Building and run unikernels with OPS

### LINKED ISSUE #4390: Building and Run Unikernels with OPS
### Topic Suggestion
Building and Run Unikernels with OPS 
#### Proposed title of article
Building and Run Unikernels with OPS 

#### Proposed article introduction
Because of their size, security, and performance, unikernels have long been hailed as the next generation of cloud architecture, allowing megatrends like microservices and serverless to thrive while combatting the never-ending barrage of data breaches, cryptojacking, and other issues. However, there's a major issue. Developers have been slow to respond. Some outside the ecosystem have blamed bogus issues such as a lack of debugging, but this isn't the case. For example, gdb is frequently used by everyone I know that uses unikernels.

#### Key takeaways 
1 Introduction to OPS
2 Code, build and run Unkernel

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Gladysoby**
this is a duplicate

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #4390 
.

### CODE REVIEW

**Comment by Gladysoby** [comment]
@jumamiller i have done the changes.

**Comment by Kayere** [comment]
Hello @Gladysoby 

 Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Building and run unikernels with OPS #5465 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7693169/Building.and.run.unikernels.with.OPS.5465.Copyleaks.Report.pdf)

**Comment by lalith1403** [comment]
Hello @Gladysoby,
 Upon running your article through our 3rd party plagiarism checker, it seemed to raise a few flags, and the % was higher than we typically accept.

We will be closing this article indefinitely due to repeated plagiarism violations.

**Comment by hectorkambow** [comment]
The conclusion seems to be heavily flagged @Gladysoby

**Comment by lalith1403** [comment]
> Hello @Gladysoby,  Upon running your article through our 3rd party plagiarism checker, it seemed to raise a few flags, and the % was higher than we typically accept.
> 
> We will be closing this article indefinitely due to repeated plagiarism violations. [New Scan 5_58 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7706039/New.Scan.5_58.PM.Copyleaks.Report.pdf)

The conclusion and some parts of the code seem to be copied. Can you correct that and let ping the peer reviewer once done?

**Comment by Gladysoby** [comment]
@jumamiller i have made the changes

**Review by jumamiller — APPROVED** [review]

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
@jumamiller 
 This article was a bit difficult to read! 

cc @Gladysoby please be sure to go over any and all edits made by the review to improve future articles and review and avoid article closure.

**Pull request merged**
