### PR TITLE
How to Build Apps with Serverless Architecture?

### LINKED ISSUE #2667: How to Build Apps with Serverless Architecture?
### Proposed title of article
How to Build Apps with Serverless Architecture?

### Introduction:
When a team considers building a serverless app, they have to re-adapt to the specifics of Сloud architecture. This article will discuss the stages of building frontend and backend in the serverless application model, discuss its opportunities and limitations, and reference best examples.

### Key takeaways:
At the end of the article, the reader will be able to:
- understand the concept of Serverless Architecture
- know if Serverless Architecture can be used to build mobile applications
- understand the advantages of Serverless Architecture for Apps development
- understand how the Serverless Application model works
- know examples of Serverless applications

### References: 
N/A

### PR DESCRIPTION
**Pull request by kerubo-tech**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**

This closes #2667
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by kerubo-tech** [comment]
This solves issue #2667

**Review by mbaabuones — CHANGES_REQUESTED** [review]
@kerubo-tech Thank you for submitting your article. I'm pleased to welcome you to the Section Engineering Program. I'm happy that you have already uploaded your author bio, photo and hero image. That is commendable. 

After going through your article, I noticed that it is similar to this article: 
https://blog.techmagic.co/how-to-build-apps-with-serverless-architecture/

There are a lot of similarities, including the titles and structure. A reader may fail to note any significant differences between your article and the above article. At Section Engineering, we want to ensure that there is value addition in articles. We also want to ensure that our articles are slightly different from other related articles. In this regard, please revise your article to add value to it. Although readers are allowed to borrow ideas or content from other related articles, they are advised to write unique articles. Please use this information to revise your article. Ping me when you are done so that I can review the revised content.

**Comment by kerubo-tech** [comment]
@mbaabuones Noted, I will make the changes you have requested. Thanks

**Comment by kerubo-tech** [comment]
@mbaabuones I have made the changes, you can look at them. Thank you

**Comment by ninjaginja** [comment]
plagiarism check completed - all good
[2120420-f12b3e8378b59343351d-1626808343533.pdf](https://github.com/section-engineering-education/engineering-education/files/6850711/2120420-f12b3e8378b59343351d-1626808343533.pdf)

**Comment by mbaabuones** [comment]
> 
> 
> @mbaabuones I have made the changes, you can look at them. Thank you

@kerubo-tech Thank you. Please note the minor changes I have made.

**Review by mbaabuones — APPROVED** [review]

**Comment by kerubo-tech** [comment]
> > @mbaabuones I have made the changes, you can look at them. Thank you
> 
> @kerubo-tech Thank you. Please note the minor changes I have made.

I have noted the changes, I will improve on the next article. Thanks

**Comment by LinusMuema** [comment]
Hi @kerubo-tech 
This is an amazing article that is quite informative. Great job!
Also, thank you for joining the eng-ed community. We look forward to seeing more great content like this from you.

cc: @mbaabuones

**Comment by kerubo-tech** [comment]
> Hi @kerubo-tech
> This is an amazing article that is quite informative. Great job!
> Also, thank you for joining the eng-ed community. We look forward to seeing more great content like this from you.
> 
> cc: @mbaabuones

@LinusMuema Thank you

**Pull request merged**
