### PR TITLE
Why is Docker so Popular

### LINKED ISSUE #2212: Why is Docker so Popular
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article's higher ranking.*
Why is Docker so popular? What makes it a big deal

### Introduction paragraph (2-3 paragraphs):
Docker is an open platform container technology for developers and sysadmins to build, ship, and run distributed applications, whether on laptops, data center VMs, or the cloud. Docker has been a game-changer since its release in 2013. It has become a massively popular containerization technology. In this article, we will discuss why Docker is a big deal.

### Key takeaways: 

What is Docker?
How popular is Docker?
Reasons Why is Docker so popular and why the rise of containers?
Advantages of Docker Containers
Which companies use Docker?

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by mosesreigns**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
Fixes #2212

### CODE REVIEW

**Comment by mosesreigns** [comment]
Fixes #2212

**Comment by mosesreigns** [comment]
@srishilesh , I saw self-assigned this #2232 PR. I've updated it with this new PR.

**Comment by srishilesh** [comment]
@mosesreigns Thanks for letting me know.

Currently, I'm held up reviewing other PRs in my queue. Some other peer reviewer will review this PR.

Thanks

**Comment by ahmadmardeni1** [comment]
Hello @mosesreigns 👋 
I will review your article. Please add a hero image. Consider using [this template](https://github.com/ahmadmardeni1/Canva) and take a look at the [containers folder](https://github.com/ahmadmardeni1/Canva/tree/main/Containers).👀

**Comment by mosesreigns** [comment]
Thank you @ahmadmardeni1 , I've added a hero.

**Review by ahmadmardeni1 — APPROVED** [review]

**Comment by ahmadmardeni1** [comment]
Hello @mosesreigns 👋
This is a great article, good job!
Please add a conclusion and further reading sections. And make sure to go through my minor changes.

**Comment by ahmadmardeni1** [comment]
@mosesreigns 👋
Good job, this is a great article and it will be ready for a final review when the plagiarism check is done.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by ahmadmardeni1** [comment]
Hello 👋 @mosesreigns 
As you know, we were working on a new structure for our EngEd Repo, which has led to a slight slow down of article publishing. Everything is almost ready now.

In order to publish your article as soon as possible please do the following:
- Download the most recent files off this PR (Make sure to pick the latest one with my revisions and edits).
- Close this PR.
- Open new PR in our new folder. You can find the *article* folder inside *content*.
- Mention me in a comment to let the other peer reviewers know that am the one responsible for your PR.

Ping me via Slack if you have any problems.

**Comment by mosesreigns** [comment]
Check it out @ahmadmardeni1

**Comment by hectorkambow** [comment]
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

**Comment by hectorkambow** [comment]
folder structure is not correct - I dont think you have done a git pull to your forked branch.

**Pull request closed without merging**
