### PR TITLE
Building and run unikernels with ops

### PR DESCRIPTION
**Pull request by Gladysoby**
(Duplicate)

### CODE REVIEW

**Comment by Gladysoby** [comment]
@louisefindlay23 i have done the changes

**Comment by Gladysoby** [comment]
Help me delete the other outdated articles above.
Thank you.

**Comment by Gladysoby** [comment]
@louisefindlay23  any progress about the article
Thank you.

**Comment by louisefindlay23** [comment]
I've removed the extra files, @Gladysoby so your PR is now ready for review from @srishilesh.

**Comment by srishilesh** [comment]
Hey @louisefindlay23,

I'm not very familiar with this topic.

Probably, someone from the @section-engineering-education/peer-reviewers team could help us with the review.

Thanks.

**Comment by Gladysoby** [comment]
@hectorkambow 
Its been some days this article has no reviewer.
Those assigned have left.
Please help 🙏
Thank you.

**Comment by srishilesh** [comment]
> @hectorkambow Its been some days this article has no reviewer. Those assigned have left. Please help 🙏 Thank you.

@section-engineering-education/peer-reviewers If anyone has experience working on a this topic or a related topic before, please assign it to yourself, and review it.

**Comment by jumamiller** [comment]
@srishilesh, this is a duplicate, am not sure if plagariasm had been done...so I'll just add the label.

**Comment by srishilesh** [comment]
> @srishilesh, this is a duplicate, am not sure if plagariasm had been done...so I'll just add the label. 

@jumamiller 

Thanks for jumping into this review.

**Comment by hectorkambow** [comment]
@jumamiller 

This PR seems rather light on substance - and some sentences are rather difficult to get through. 

cc @Gladysoby

**Comment by jumamiller** [comment]
@Gladysoby, let's work on this article outside the queue. It has a lot of fixes to be worked on, which might take some time. Feel free to reach me on Slack, meanwhile I'll suggest you changes work on.

**Comment by hectorkambow** [comment]
@Gladysoby 

We will be closing this PR as some sentences were a bit difficult to understand while reading - and noticed some run on sentences as well. 

We encourage you to go through our resources, past published works, and examples to get a better sense of the level of quality our EngEd community expects 🚀 . 

These articles are used by students to gain potential future employment and they should reflect our best work. 

We ask that every piece of content adds value to the larger developer community as well. 

We look forward to reviewing your polished work when it is publish ready. 👍

**Pull request closed without merging**
