### PR TITLE
Composition in Java

### LINKED ISSUE #3713: Composition in Java
#### Introduction
`Composition` is one of the most common fundamentals in the java programming language. Composition describes a class that references one or more objects of other classes. It allows for Code re-use by modeling a has-a association between objects, help in design APIs among other of its `advantages` we will discuss. 

In this tutorial, we will introduce composition in OOP and also learn the `implementation` of composition in java. We will further use an example to fully explain and evaluate the idea of composition in java. 
We will also see the `benefits` of composition in oop. Moreso, we will learn the `difference` between inheritance and composition since people often confuse the two fundamentals.

Moreover, the article proposed will use a detailed code snippet to explain to the user how composition occurs. There will also be an example that will help the user practice and try to see their level of understanding of Composition in Java. 

Besides the variety of examples, we will have a sample project that the user will be able to run on their Editors to further grasp the idea of Composition. We will use this project to differentiate Composition in Java and other OOP languages.

### Key Takeaways
1. Advantages of Composition
2. Roles of Composition
3. Implementation of Composition
4. Benefits
5. Difference between composition and Inheritance

### Reference
N/A

### PR DESCRIPTION
**Pull request by Ykz-Jnr**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3713

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Review by jerimkaura — COMMENTED** [review]
Hello @Ykz-Jnr 👋 

Welcome to EngEd. It is awesome to have you on board. Thank you for submitting your first article for review 🤝 . I will be your reveiwer.

We usually do the reveiw in two rounds; preliminary reveiw and tech review. 

For now, I will begin with the former to ensure your article is grammatical correct and all the requirements are met.

 Kindly be patient as we work on the article in the queue.

**Comment by Kayere** [comment]
Plagiarism check done ✔️

**Comment by jerimkaura** [comment]
Good evening @Ykz-Jnr 

I have finished the first round of revisions. Thank you for such a clear and easy-to-read article. I made some changes to enhance the flow of the article. Kindly take note of the corrections.

I will be proceeding to tech review where I will be testing out your code to ensure it works well.

**Review by jerimkaura — COMMENTED** [review]
Good evening @Ykz-Jnr 

I have finished the first round of revisions. Thank you for such a clear and easy-to-read article. I made some changes to enhance the flow of the article. Kindly take note of the corrections.

I will be proceeding to tech review where I will be testing out your code to ensure it works well.

**Review by jerimkaura — CHANGES_REQUESTED** [review]
Hello @Ykz-Jnr 

The author page folder should be in lower case for instance, instead of `Kimani-K` use `kimani-k`.

Work on that and ping me when done.

**Comment by Ykz-Jnr** [comment]
Greetings @jerimkaura 
I have made all the changes requested.
please continue with the review.

**Review by jerimkaura — CHANGES_REQUESTED** [review]
Good morning @Ykz-Jnr 

You seem to have forgotten about snippet identifiers. The snippet identifier tells the Markdown file whether your code is java, dart, python or Javascript. 

Please work on that then we proceed with the review. Make sure you edit the same file I edited to avoid merge conflicts.

**Review by Ykz-Jnr — COMMENTED** [review]
Changes made as requested @jerimkaura

**Review by jerimkaura — COMMENTED** [review]
Take note of the changes made.

**Review by jerimkaura — APPROVED** [review]

**Review by jerimkaura — APPROVED** [review]
Hello @Ykz-Jnr 

Thank you for such a great article. Let us wait for the final review.

**Comment by Ykz-Jnr** [comment]
Thanks for the review @jerimkaura

**Comment by hectorkambow** [comment]
Thank you for your patience as our team has been working diligently to work through the recent increased volume of articles coming in. 

We are going through are ready articles in the order they were received and working on improving our review time as well. 

🚀

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
👍 overall nice work - very detailed and straight forward tutorial 
 
Please review and suggestions/changes made by your peer reviewer and/or myself during a final review.

**Pull request merged**
