### PR TITLE
CRUD Operations with Strapi GraphQL API

### LINKED ISSUE #4927: [API] CRUD operations with Strapi GraphQL API
#### Introduction
CRUD (Create, Read, Update, Delete) operations are composed of pages or endpoints allowing users to interact with entities stored in a database. Strapi, an open source headless CMS, connects writer's front-end with Strapi's back-end.

GraphQL gives engineers admittance to simply the specific information they need in a particular solicitation by utilizing only one endpoint, which gets what the front end application expects and returns exactly.

The CRUD operations are used to modify a GraphQL service by defining types and fields of those types then provide functions for each type.

#### Key takeaways 
- Requirements
- CRUD with GraphQL server
- Fetching single and multiple contents
- Implementing GraphQL in Strapi
- Reading and writing data in GraphQL

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by ehlaji**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4927 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by hectorkambow** [comment]
@ehlaji 
Thank you for your patience as our team has been working diligently to work through the recent increased volume of articles coming in.
We are going through are ready articles in the order they were received and working on improving our review time as well.
🚀

**Comment by hectorkambow** [comment]
@section-engineering-education/peer-reviewers 


is anyone available to jump on this PR ASAP. 

Thank you

**Comment by vifabulous** [comment]
@katungi Is there any progress with this PR?

**Comment by katungi** [comment]
Hey @vifabulous , thank you for taking your time to add to the amazing knowledge pool we are building.
My name is Daniel, I will be taking you through the review process. Let's get started 🎊 , I am so excited to learn more from you 🚀

**Comment by vifabulous** [comment]
@katungi is there any progress with this PR?

**Comment by katungi** [comment]
> @katungi is there any progress with this PR?

Please make the small change so I can continue with the review.

**Comment by katungi** [comment]
Hello @vifabulous, after going through your article, I have to say that the article is really informative and well done. However, it is riddled with minor grammatical  mistakes. Here are some suggestions to fix that:
- Go through the article from a reader's POV and see the mistakes you can fix.
- Run the article through Grammar checking software like Grammarly to help improve the quality of the article.

Once you have fixed that, please ping me so we move forward. 

**NOTE**: If you do not improve the quality of the article, It will be closed.

**Comment by ehlaji** [comment]
@katungi I have done some grammar fixes. You can take a look

**Comment by hectorkambow** [comment]
> Hello @ehlaji, after going through your article, I have to say that the article is really informative and well done. However, it is riddled with minor grammatical mistakes. Here are some suggestions to fix that:
> 
> * Go through the article from a reader's POV and see the mistakes you can fix.
> * Run the article through Grammar checking software like Grammarly to help improve the quality of the article.
> 
> Once you have fixed that, please ping me so we move forward.
> 
> **NOTE**: If you do not improve the quality of the article, It will be closed.

@katungi can we get a status on this PR. 

👍 well done with the comments

**Comment by katungi** [comment]
Hey @ehlaji , I have gone through the PR and thanks for making the necessary changes. I would like to continue to the tech review. However, as I was reading through your work, I got a sense that the code snippets were not correct. 
Please check that all the code snippets are correct and well formatted.
Once you are through, we will finish up with the tech review.

**Review by louisefindlay23 — CHANGES_REQUESTED** [review]
Your article appears to have many sentences that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced.

Please rework the [affected content](https://github.com/section-engineering-education/engineering-education/files/7790486/New.Scan.7_24.PM.Copyleaks.Report.pdf).

**Comment by katungi** [comment]
Hello @ehlaji , How are the changes going? Just a reminder that if you need any help, you can leverage the community 🎊

**Comment by WanjaMIKE** [comment]
@katungi should we close the PR to allow the author complete the changes outside the queue?

**Comment by ehlaji** [comment]
> @katungi should we close the PR to allow the author complete the changes outside the queue?

Am working on it

**Pull request closed without merging**
