### PR TITLE
Understanding selenium architecture and frameworks

### LINKED ISSUE #5824: Understanding Selenium Architecture and Frameworks
### Topic Suggestion
Understanding Selenium Architecture and Frameworks.
#### Proposed title of article
Understanding Selenium Architecture and Frameworks.
#### Proposed article introduction
Selenium is an open source software automation testing which is commonly used. It makes it possible to test any kind of web application because it supports  automation framework.
Selenium is composed of four elements which are, integrated Development environment for selenium, remote control, grid and Web Driver. The four elements combined makes, are utilized for automation testing.
Selenium framework, is the workspace created to mould a code for automation process of a web-base application. This framework makes it easier to maintain a code, enhance efficiency and allow multiple programmers to comfortably enhance the code. Several framework are supported by selenium which we are going to cover.
#### Key takeaways 
- Architecture for Selenium
   - Remote control.
   - Web drive.
   - Integrated Development Environment.
   - Grid.
- Framework
  - Types of Frameworks supported by selenium.
  - Components of Selenium framework.
  - supported file formats.
  - Creating a framework.
  - Advantages of selenium framework.
#### Article quality
In this article am going to take the user through the architecture of selenium and the numerous framework that selenium supports. Am going to user a beginner friendly language for the user to understand.
#### References
N/A

### PR DESCRIPTION
**Pull request by stanley886**
#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5824

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by hectorkambow** [comment]
@stanley886 
👍  

Thank you for submitting your article - please triple check that the article is fully polished and ready to be published (error-free) to avoid any PR closures.

**Comment by lalith1403** [comment]
plagiarism check done ✔️

**Comment by lalith1403** [comment]
👋 Good afternoon - and welcome to the EngEd program.
Many sentences in this article appear to be taken from third-party sources. We can't publish any content that is not original or adequately cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is an excellent resource to reference.
We're looking for unique/original content.

**Comment by stanley886** [comment]
> 👋 Good afternoon - and welcome to the EngEd program. Many sentences in this article appear to be taken from third-party sources. We can't publish any content that is not original or adequately cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is an excellent resource to reference. We're looking for unique/original content.

@lalith can i still work on this article and rectify the mentioned mistakes??

**Comment by hectorkambow** [comment]
You're welcome to fix any mistakes but the article will receive no (monetary) compensation upon being published. 

It will go towards building your EngEd profile to share with potential employers. 

@stanley886  

This is an effort to help streamline reviews and be fair to larger EngEd community.

**Comment by stanley886** [comment]
> You're welcome to fix any mistakes but the article will receive no (monetary) compensation upon being published.
> 
> It will go towards building your EngEd profile to share with potential employers.
> 
> @stanley886
> 
> This is an effort to help streamline reviews and be fair to larger EngEd community.

@hectorkambow  but this article was approved before the pay program for contributers ended.

**Comment by hectorkambow** [comment]
👍 totally understand but that has nothing to do with the quality being submitted - all articles have always been expected to be submitted polished and error free (as stated on our docs). 

Our PR team does not provide revisions services.

**Pull request closed without merging**
