### PR TITLE
Deploying a serverless Django application with Zappa on AWS

### LINKED ISSUE #4117: Deploying a Django REST API serverless application with AWS and Zappa
#### Proposed article introduction
Serverless computing was created with the main goal of enabling developers build, run applications without having to interact or manage servers. This does not mean the application runs without a server, but that the management of the server would be done by AWS. 
This process is quite exciting although implementing serverless applications in Django may be challenging. However, we will be using Zappa, an open-source python tool for creating, deploying, and managing serverless python applications on AWS Lambda. 

In this tutorial, we will be building a serverless Django REST API and deploying the application to AWS Lamba using Zappa.

#### Key takeaways 
1.  Building a serverless Django RESTAPI application
2. How to implementing Zappa 
3. Working with AWS Lamba

#### Article quality
In this tutorial I intend on first, giving a detailed explanation for what serverless application means and how it aids developers. Also explaining concepts such as Zappa, AWS Lamba, etc., and how they work. The tutorial will contain a step-by-step guide on how these processes work right from building a REST API to the deployment process.

#### References
N/A.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Anitaachu**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4117

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Anitaachu** [comment]
This closes #4117

**Review by jerimkaura — COMMENTED** [review]
Hello @Anitaachu 

Check on the changes I have highlighted. I am proceeding to tech review.

**Comment by Kayere** [comment]
Hello @Anitaachu

 Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Deploying a serverless Django application with Zappa on AWS #5315 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7677170/Deploying.a.serverless.Django.application.with.Zappa.on.AWS.5315.Copyleaks.Report.pdf)

**Comment by Anitaachu** [comment]
Hi@jerimkaura, I have gone through the changes. Thank you.

**Comment by Anitaachu** [comment]
Thank you @kayere I have gone through the attached PDF and I noticed that 90% of the red flags were caused by generally Django and Zappa code snippets.

**Review by jerimkaura — CHANGES_REQUESTED** [review]
Hello @Anitaachu :wave: 

Thank you for the great article. Our community encourages authors for such in-depth articles. :rocket:

I have made a few changes that are worth looking at. Especially when using images. You can look at my changes or have a look at our documentation for more. I made corrections for you in this one.

One more thing, kindly resize your hero image to about `600 * 400` as required.

**Comment by Anitaachu** [comment]
Thank you @jerimkaura. I have taken note of the corrections and images. I have also made changes with regards to resizing the hero image.  Thanks!

**Review by jerimkaura — COMMENTED** [review]
Thank you for submitting such a great article. Let us wait for the final review.

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
