### PR TITLE
Getting started with packet tracer

### LINKED ISSUE #2929: Getting started with packet tracer
### Introduction paragraph (2-3 paragraphs):
A packet  tracers is a network simulator. This means  it can be used to imitate  a live networking environment. This imitation is key especially in a learning environment where a learner is just getting started with network developments. There are many types of  network simulators and Packet tracer is one of them.

In this article I will be introducing what a packet tracers is, discussing the processes involved in its installation and finally I will discuss  its  functionality at  length.
### Key takeaways: 
1. The reader will be able to understand what a packet tracer is and why it is needed in networking.
2. The reader will be able to  get the installation process of a packet trace
3. The reader will learn how to use a packet tracer in network simulation.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by achiengrhoda**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
This fixes #2929

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. :rocket:
Thank you. @achiengrhoda

**Comment by marienjus** [comment]
Good evening @achiengrhoda, I've been pointed by @hectorkambow regarding the peer reviewer team and I'd be willing to review this article :+1:

**Comment by ahmadmardeni1** [comment]
Thank you for submitting your topic. @achiengrhoda 
After some careful consideration, it struck us that this topic should not have a tutorial. The installation process is very easy and the readers will expect a higher value.

We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

Also, your article has not been through any spell or grammar checker. Please make sure to go through [our resources](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors). [Grammarly](https://app.grammarly.com/) and [Hemingway](https://hemingwayapp.com/) are the best tools and can help a lot.

You are more than welcome to pursue another more in-depth topic. Or you can build on top of [this tutorial](https://github.com/section-engineering-education/engineering-education/pull/2992). Any advanced topic using Packet Tracer is more than welcomed and will be a great addition to our program.

We will be closing the PR simply to make room in the queue - Please @ me when you open a new PR with an advanced topic and I will make sure that you will not wait in the queue again.

@marienjus Please do not continue your review here - choose another PR, @ me, and I will add the labels.

**Comment by marienjus** [comment]
Sure lot of articles and good documentation are available for this already. I believe we should improve by writing original and unique content.

**Pull request closed without merging**
