### PR TITLE
Building a Java Application with Jenkins in Docker

### PR DESCRIPTION
**Pull request by Kikiodazie**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by Kikiodazie** [comment]
This fixes issue #2171

**Comment by WanjaMIKE** [comment]
```Hello 👋
As you know, we were working on a new structure for our EngEd Repo, which has led to a slight slow down of article publishing. Everything is almost ready now.
In order to publish your article as soon as possible, please do the following:

Download the most recent files off this PR (Make sure to pick the latest one with my revisions and edits).
Delete your article directory from the articles folders.
Do a git pull (take a look at the new structure of the repo after a git pull).
Upload your article files to the new articles folder inside content.
Ping me via Slack if you have any problems.```

**Comment by hectorkambow** [comment]
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

**Comment by Kikiodazie** [comment]
Sure @WanjaMIKE I will get right to it.

**Comment by Kikiodazie** [comment]
Thank you @hectorkambow. Sounds great.

**Comment by Kikiodazie** [comment]
Hello @WanjaMIKE I am still patiently waiting on your revisions and edits, so I can move the article to the right directory.

**Comment by WanjaMIKE** [comment]
@Kikiodazie just migrate it right away. Thanks

**Comment by Kikiodazie** [comment]
> @Kikiodazie just migrate it right away. Thanks

Ok then. Will do that.

**Comment by Kikiodazie** [comment]
Hey, @WanjaMIKE, I just moved my article files to the new articles folder inside the content folder. Kindly check if I did it right.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by Kikiodazie** [comment]
> plagiarism check done

Thanks @hectorkambow

**Comment by Kikiodazie** [comment]
@WanjaMIKE @hectorkambow Good day. Any update on the review? Patiently waiting.

**Comment by WanjaMIKE** [comment]
I will update you shortly. Thanks

**Comment by Kikiodazie** [comment]
> I will update you shortly. Thanks

Ok then. Thanks.

**Comment by WanjaMIKE** [comment]
always use ```###``` rather than ```##``

**Comment by WanjaMIKE** [comment]
Alaways use these ``` ```` ``` to enclose your code as I have done

**Comment by Kikiodazie** [comment]
> Alaways use these ` ` ``` to enclose your code as I have done

All noted. Thanks for the correction.

Anything I am to do, please let me know.

**Review by WanjaMIKE — APPROVED** [review]
Nice work. Quite a detailed tutorial.

**Comment by Kikiodazie** [comment]
> Nice work. Quite a detailed tutorial.

Thank you 😊. This means a lot🙌🏾

**Comment by hectorkambow** [comment]
Great work gents - very informative tutorial - easy to follow along. 

Some very minor edits made on my end - please take a look to see if they can be incorporated to future articles .

cc @WanjaMIKE 
🚀

**Comment by Kikiodazie** [comment]
> Great work gents - very informative tutorial - easy to follow along.
> 
> Some very minor edits made on my end - please take a look to see if they can be incorporated to future articles .
> 
> cc @WanjaMIKE

Thanks, @hectorkambow. I appreciate the feedback. Have a great weekend.

**Comment by Kikiodazie** [comment]
And thank you, @WanjaMIKE, for the review. Have a great weekend too.

**Comment by hectorkambow** [comment]
Yes sir 🚀  

@Kikiodazie 
https://www.section.io/engineering-education/building-a-java-application-with-jenkins-in-docker/

**Comment by WanjaMIKE** [comment]
@Kikiodazie Yes. ```merged``` means published. Here is the link ```https://www.section.io/engineering-education/building-a-java-application-with-jenkins-in-docker/```

**Comment by Kikiodazie** [comment]
> @Kikiodazie Yes. `merged` means published. Here is the link `https://www.section.io/engineering-education/building-a-java-application-with-jenkins-in-docker/`
> 
> I did not see `Hector's` reply

No problem.

**Comment by Kikiodazie** [comment]
> Yes sir 
> 
> @Kikiodazie
> https://www.section.io/engineering-education/building-a-java-application-with-jenkins-in-docker/

Yayyyyyyy I am so so excited. This just made my day. Thank you guys :sob:

**Pull request merged**
