### PR TITLE
Making An API With Gatsby

### LINKED ISSUE #4597: [API] Making An API With Gatsby-  A complete guide
#### Proposed title of article
[API] Making An API With Gatsby-  A complete guide 

#### Proposed article introduction
In web development, an API is commonly specified as a collection of standards, such as HTTP request messages and response message structures, usually in XML or JSON format.
Gatsby (GatsbyJS) is a web application and website framework built on React and GraphQL. On the JAMstack, it is developed using client-side JavaScript (or other scripting languages), reusable APIs, and prebuilt Markup.

Using Gatsby Functions, I'll show how to create an API and what to watch out for while deploying it to Gatsby Cloud.

#### Key takeaways 
1.  An overview of  API and Gatsby.
2. get started with our project
- installing all dependencies needed.
- build our API
3. Start our Gatsby DevServer
4. Make A Browser Request
5. deploy our API to Gatsby Cloud
6. API testing

#### Article quality
Building an API using Gatsby will be comprehensive, distinctive, and useful. I will use simple language and graphics to help the readers comprehend.

#### References
N/A

### PR DESCRIPTION
**Pull request by Daniel-muriithi**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

`This closes #4597

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Hi, @Daniel-muriithi. Upon reviewing this article for pre-review checks, it contains technical inaccuracies (such as the definition of CDN) and its coherence, grammar and content isn't up to the standard that we maintain.

Please work and polish your article further using our [resources](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors) to get your article into a ready to review and ideally publishable state.

**Comment by Daniel-muriithi** [comment]
Hello @louisefindlay23, I request you reopen this PR for me so that I can commit the changes. Thank you

**Comment by Daniel-muriithi** [comment]
hello @louisefindlay23 I have updated the requested changes please check. Thank you

**Comment by Daniel-muriithi** [comment]
hello @louisefindlay23 I have updated the requested changes please check. Thank you

**Comment by hectorkambow** [comment]
@Daniel-muriithi 

Thank you v much for revisiting the PR (article). 

I did a quick glance through the content provided & Good afternoon and thank you for submitting your topic to the EngEd program. It still seems this PR is still quite a bit aways from being completed. 
 
As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published. 

All revisions and edits should be completed on your own forked repo (as to not build up a backlog in the queue). 

We will close this and please re-submit when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 

Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.
 
👍 

Please be sure to visit our Resources page for more examples, guides, and tools to improve overall technical writing.

**Pull request closed without merging**
