### PR TITLE
Php reg ex

### LINKED ISSUE #3208: Introduction to PHP RegEx
### Introduction paragraph (2-3 paragraphs):
PHP regular expressions commonly known as RegEx are pattern matching algorithms that are performed in expressions. RegEx use everyday arithmetic operators to create complex expressions that can be used for email address and IP address validation.

In this article I will be explaining what regular expressions are, the need to use the regular expressions and finally the different types of regular expressions used in PHP and their functionalities. I will also be discussing how to implement the above discussed types of RegEx in detail.

### Key takeaways: 
1. The reader will understand what PHP RegEx is.
2. The reader will understand the different types of PHP RegEX.
3. The reader will be able to understand the different areas of implementation of RegEx and be able to use the Regular Expressions.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by stevekwachie**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.
This fixes #3208

### CODE REVIEW

**Review by jerimkaura — APPROVED** [review]
Good article @stevekwachie, next time take note of the changes made.

**Comment by jerimkaura** [comment]
@stevekwachie 

You need to create an author page for your article. Use [this guide](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/UPLOAD_INSTRUCTIONS.md) to create one. 

Ping me when you are done.

**Comment by WanjaMIKE** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.
[Php reg ex #3482.pdf](https://github.com/section-engineering-education/engineering-education/files/7072320/Php.reg.ex.3482.pdf)

**Comment by hectorkambow** [comment]
[Php reg ex #3482.pdf](https://github.com/section-engineering-education/engineering-education/files/7080242/Php.reg.ex.3482.pdf)

👋 Good afternoon - and welcome to the EngEd program.
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

**Comment by stevekwachie** [comment]
> [Php reg ex #3482.pdf](https://github.com/section-engineering-education/engineering-education/files/7080242/Php.reg.ex.3482.pdf)
> 
>  Good afternoon - and welcome to the EngEd program.
> I'll be running a final review on your PR when ready.
> Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
> Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
> Be sure to see our resources page to see more info on plagiarism and what is considered as such.

@hectorkambow ....its corrected

**Comment by hectorkambow** [comment]
@stevekwachie 

This article seems a bit light on substance - it seems to go over some snippets that may be covered in the other documentation. 


@jerimkaura 
You have gone through the article throughly what are your thoughts?? 


cc @WanjaMIKE  & @ahmadmardeni1 any input would be appreciated.

**Comment by jerimkaura** [comment]
> @stevekwachie
> 
> This article seems a bit light on substance - it seems to go over some snippets that may be covered in the other documentation.
> 
> @jerimkaura
> You have gone through the article throughly what are your thoughts??
> 
> cc @WanjaMIKE & @ahmadmardeni1 any input would be appreciated.

Hello @hectorkambow, I hope you are well. 

Regex, as used in PHP, has not much depth so I didn't expect anything further unless the student wanted to give it a deeper approach used in writing a context-free grammar (CFG) during compiler design; but that would have changed the whole idea of the article.

Let me know what your further thoughts are.

Thank you!

cc: @stevekwachie , @WanjaMIKE , @ahmadmardeni1

**Pull request closed without merging**
