### PR TITLE
Understanding Closures in Ruby

### LINKED ISSUE #2523: Understanding Closures in Ruby
### Proposed title of article

Understanding Closures in Ruby

### Introduction paragraph (2-3 paragraphs):

Closures is a sensitive concept in programming, it's a function whose body references a variable declared in its parent scope. In order to understand closures effectively we will tackle proc and lambda concepts, why it matters and it's differences. These key concepts can improve and introduce strong code designs.
With closures we can write effective and interesting code and provide an understanding to code written in other libraries.

### Key takeaways: 
Able to identify closures in a code base and write your own closures.
Define closures know what is lexical scoping and free variables.
Able to identify proc and lambdas.
Know the differences between proc and lambda and where to use if in need.

### References: 
- Ruby docs - https://ruby-doc.org/core-3.0.1/Proc.html
- Mastering Ruby Closures book
- The Well-Grounded Rubyist book

### PR DESCRIPTION
**Pull request by Njunu-sk**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
 
This fixes #2523.     
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [X] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [X] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [X] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by hectorkambow** [comment]
@Njunu-sk 
Good afternoon and thank you for submitting your article for publishing. It has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀

**Comment by hectorkambow** [comment]
[Understanding Closures in Ruby #2755.pdf](https://github.com/section-engineering-education/engineering-education/files/6792985/Understanding.Closures.in.Ruby.2755.pdf)


@Njunu-sk 

There appear to be many sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/)

**Comment by ahmadmardeni1** [comment]
Can you run another plagiarism check please? @hectorkambow

**Comment by ninjaginja** [comment]
plagiarism check completed - all good
[2120420-dd961f3ca325953134fd-1626876066834.pdf](https://github.com/section-engineering-education/engineering-education/files/6856296/2120420-dd961f3ca325953134fd-1626876066834.pdf)

**Comment by ahmadmardeni1** [comment]
Hey @Njunu-sk 👋 
Your local branch doesn't have your author folder for some reason - I don't know how it was deleted on your end.

Please sync your forked repo and branch with "master", which should bring back your author profile since it is available on our repo.

**Comment by ahmadmardeni1** [comment]
Great article - good work @Njunu-sk @WanjaMIKE

**Pull request merged**
