### PR TITLE
How to control a Servo Motor using a Raspberry Pi 3

### LINKED ISSUE #4807: [Internet of Things]How to control a Servo Motor using a Raspberry Pi 3
### Topic Suggestion
How to control a Servo Motor using a Raspberry Pi 3

#### Proposed title of article
How to control a Servo Motor using a Raspberry Pi 3

#### Proposed article introduction
This article will seek to explain how a raspberry pi can be programmed to control a servo motor. The aim is to simulate a simple  IoT scenario where the motor simulates a car engine and the Raspberry Pi the control system.
We will attempt to start and stop the simulated car engine through the Raspberry pi to explore the importance of IoT in automobile.

#### Key takeaways 
1. Introduction to Motors
2. Comparison of Servos and DC motors
3. Step by Step programming of Raspberry Pi to control Servo motors.

#### Article quality
This article will include both the theory of DC and motors and the steps of how the servo motors can be controlled by a raspberry pi.

#### References
N/A

### PR DESCRIPTION
**Pull request by RuthAMare**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?
This closes #4807

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Please always use the template provided by us.
I edited your initial comment and added the template. Check what matches your article.

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅
But I think this article is light on substance - What do you think? @Dawe-7

**Review by Dawe-7 — CHANGES_REQUESTED** [review]
Awesome article @RuthAMare. Kindly resize your hero image to 600x400 pixels as we move on to tech review.

**Comment by Dawe-7** [comment]
> Plagiarism check done ✅ But I think this article is light on substance - What do you think? @Dawe-7

@ahmadmardeni1, at a glance, the article looks very brief but i think @RuthAMare's article has a good flow and the content is well explained in my opinion. Any thoughts @ahmadmardeni1 ?

**Comment by RuthAMare** [comment]
Hi @Dawe-7
Thanks, the hero image is at 640x425 which I think is close to the desired size.
Should I just go ahead and resize it anyway?

**Comment by Dawe-7** [comment]
> Hi @Dawe-7 Thanks, the hero image is at 640x425 which I think is close to the desired size. Should I just go ahead and resize it anyway?

@RuthAMare, Yes, kindly do so.

**Review by Dawe-7 — APPROVED** [review]
Nice article @RuthAMare. Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles. Thank you.

**Comment by RuthAMare** [comment]
> Nice article @RuthAMare. Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles. Thank you.

Thank you @Dawe-7

**Comment by hectorkambow** [comment]
Jumping on this one

**Comment by hectorkambow** [comment]
Made some minor edits before merging. 


Quick questions (may have to edit after the fact) 

@RuthAMare 
 The image within the article do they need any sources?? 
 
 cc @Dawe-7 always make sure we are checking the sources for any images.

**Comment by RuthAMare** [comment]
> Made some minor edits before merging.
> 
> Quick questions (may have to edit after the fact)
> 
> @RuthAMare The image within the article do they need any sources??
> 
> cc @Dawe-7 always make sure we are checking the sources for any images.

@hectorkambow , no they don't.
Most of them are free images, others are my own implementation.

**Comment by Dawe-7** [comment]
> Made some minor edits before merging.
> 
> Quick questions (may have to edit after the fact)
> 
> @RuthAMare The image within the article do they need any sources??
> 
> cc @Dawe-7 always make sure we are checking the sources for any images.

Noted @hectorkambow.

**Pull request merged**
