### PR TITLE
Getting Started with Code Generation in Flutter

### LINKED ISSUE #3365: Getting Started with Code Generation in Flutter
### Proposed title of article
Getting Started with Code Generation in Flutter

### Introduction paragraph (2-3 paragraphs):
Flutter model code generation allows you to automate these time-consuming activities so you can focus on what matters. Simply write the repeated code pattern once and build a generator that generates files with code based on the pattern you defined.

In this article, you'll create a code generator that locates all of a class's variables, stores them in a map, then produces getters and setters to save and read from the map.

### Key takeaways: 
-When should code generation be used?
-What are annotations and how do I utilize them?
-A generator's method of generating code.
-In a Flutter project, how to produce models.

### References: 
N/A

### PR DESCRIPTION
**Pull request by FranciscaNg**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This fixes #3365 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your article for publishing. @FranciscaNg 
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. :rocket:
Thank you.

**Comment by hectorkambow** [comment]
@FranciscaNg 

[Getting Started with Code Generation in Flutter #3455.pdf](https://github.com/section-engineering-education/engineering-education/files/7027972/Getting.Started.with.Code.Generation.in.Flutter.3455.pdf)

👋 Good afternoon - and welcome to the EngEd program.
There appear to be many sentences in this article that are taken from a third-party source. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/)

cc @jerimkaura

**Comment by FranciscaNg** [comment]
Can i rewrite the article and resubmit please, @hectorkambow

**Comment by ahmadmardeni1** [comment]
You asked me to re-open the PR. Please commit the changes and I will do a plagiarism check. @FranciscaNg

**Comment by FranciscaNg** [comment]
Committed @ahmadmardeni1 
Than you.

**Comment by ahmadmardeni1** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags, and the % was higher than we typically accept (47%) - This article is similar to [this one](https://www.raywenderlich.com/22180993-flutter-code-generation-getting-started).

Please see attached PDF - I'm going to close this PR. Feel free to suggest another topic.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Getting Started with Code Generation in Flutter #3455](https://github.com/section-engineering-education/engineering-education/files/7111373/New.Scan.9_50.AM.Copyleaks.Report.1.pdf)

We won't open this PR again. @jerimkaura

**Pull request closed without merging**
