### PR TITLE
How Robotic Data Automation is Accelerating AIOps Implementations

### LINKED ISSUE #6352: How Robotic Data Automation is Accelerating AIOps Implementations
#### Proposed article introduction
Robotic Data Automation (RDA) is a new paradigm to help automate data integration and data preparation activities involved in dealing with machine data for Analytics and AI/Machine Learning applications. RDA is not just a framework, but also includes a set of technologies and product capabilities that help implement the data automation

Robotic Data Automation Fabric (RDAF) infuses AIOps and robotic data workflow automation across the customer’s distributed edge using next-generation technologies like NLP (natural language processing), NLG (natural language generation), distributed messaging, and integrated development environment (IDEs) for building customized, on-the-fly, instantaneous pipelines using low-code databots. 
#### Key takeaways 
The value of RDA
Robotic process automation (RPA) vs Robotic Data Automation (RDA) 
Robotic data automation fabric and data observability
RDAF and edge analytics
#### Article quality
Being a fairly new concept, there are only a few available articles related to Robotic Data Automation (RDA). In addition to giving an in-depth review of what RDA is, this article compares RDA to RPA and explains how Robotic Data Automation Fabric and edge analytics work together. 

#### References
https://www.youtube.com/watch?v=dwq9AQFoXBo
https://www.roboticdata.ai/bot-library/

### PR DESCRIPTION
**Pull request by jesmweni**
this closes #6352

## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Comment by jesmweni** [comment]
Hi @collins-a 
Any feedback on this article?

**Comment by jesmweni** [comment]
Hi @collins-a 
Any feedback on this article?

**Comment by collins-a** [comment]
> Hi @collins-a Any feedback on this article?

Hi @jesmweni, thank you for your patience. The PR itself has a bit of an issue. Looking to figure it out then give direction/complete the review.

**Review by collins-a — APPROVED** [review]
@jesmweni good article on the impact of RDA on AIOps. Looking forward to even better content.

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
