### PR TITLE
How to Containerize an Angular Application Featuring Nginx Using Docker Containers

### LINKED ISSUE #2388: How to containerize an Angular Application featuring Nginx Using Docker containers
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article
How to containerize n Angular Application with Nginx Using Docker containers

### Introduction paragraph (2-3 paragraphs):
Docker is a lightweight virtual machine (VM) that lets you specify virtual computers known as containers. These containers are made up of software images provided by various official software vendors. These containers, unlike traditional VMs, are super light and are not resource-intensive. Multiple containers can usually run in parallel with little impact on the host machine's resources. And that is absolutely what docker containers are made for. The lightweight docker containerization philosophy separates each service that your application requires and runs them in isolated environments.

Docker makes it simple to set up these environments. With a single yml file, you'll be able to build several containers that will all work together within a single network and communicate with each other to create a single functioning application. Containers enable developers to bundle up an application and all of its essential components, including libraries and other dependencies and distribute it as a single package.

On the other hand, Angular is a single-page app design javascript front-end framework and a development platform for building innovative and advanced apps. Similar to React and Vue used to run the application on the client-side. Angular is also often used with back-end APIs to create powerful full-stack applications, such as making HTTP requests to a MERN stack.

In this guide, we'll set up a simple docker-compose script to get you up and to run with Docker, docker-compose, and a local Angular environment on your computer featuring Nginx for reverse proxy. No need to install angular CLI and Node.js locally. Docker-compose will help us lay down some instructions to get Angular containerized and ready to run some code.

### Key takeaways: 
Set up Docker
Writing a Dockerfile
Writing docker-compose.yml
Running the Docker Container

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Rose-stack**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
Fixes #2388

### CODE REVIEW

**Comment by hectorkambow** [comment]
plagiarism check done

**Review by WanjaMIKE — CHANGES_REQUESTED** [review]
Could you please add a `conclusion` @Rose-stack

**Comment by WanjaMIKE** [comment]
@Rose-stack Waiting .....

**Comment by Rose-stack** [comment]
> Could you please add a `conclusion` @Rose-stack

A conclusion added @WanjaMIKE

**Comment by ahmadmardeni1** [comment]
Good work, this is a great tutorial @Rose-stack @WanjaMIKE  🚀

**Pull request merged**
