### PR TITLE
(Machine Learning) Effectiveness of support vector machine in health asessment #5935

### LINKED ISSUE #5935: (Machine Learning) Effectiveness of support vector machine in analyzing medical data
### Topic Suggestion
(Machine Learning) Effectiveness of support vector machine in analyzing medical data

#### Proposed title of the article
Effectiveness of support vector machine (SVM) in analyzing medical data
#### Proposed article introduction
SVM has been termed as one of the key models which are vital in the prognosis and prediction of various diseases. SVM is vital in analyzing medical databases which are vital in predicting and diagnosing various health conditions.
The article's focus is to understand ways in which SVM diagnose and prognoses various health conditions using medical data. The article also highlights why SVM is effective in handling medical data compared to other algorithms.

#### Key takeaways 
1. Understand ways in which SVM transforms medical data to outputs which are vital in diagnosing and prognosis of various health condition
2. Various health conditions that can be diagnosed and prognosis using SVM?
3. why SVM is an effective model in handling medical data compared to other algorithms?
#### Article quality
The article is unique since it will be able to assess the in-depth use of SVM in analyzing medical data to address medical problems
#### References
None for now

### PR DESCRIPTION
**Pull request by slynn22**
Index.md and hero.jpg uploaded

## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5935 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by slynn22** [comment]
@louisefindlay23, i did a mistake when uploading and this is order "(Machine Learning) Effectiveness of support vector machine in analyzing medical data #5935" which you approved the topic

**Comment by srishilesh** [comment]
Hello @slynn22 ,

Thanks for submitting this PR.

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you with the changes to be made.

Meanwhile, we suggest you to go through other approved PRs/published articles to see if you have missed out anything, which might avoid a potential PR closure.

Thanks.

**Comment by slynn22** [comment]
Okay

**Comment by slynn22** [comment]
@srishilesh hope all i well, my PR is yet to be reviewed

**Comment by srishilesh** [comment]
Hey @slynn22 ,

Apologies for the delay, The peer-reviewers are trying to clear up their existing reviews to take up more.

Let me give my personal opinion on this PR.

On having a quick glance at your PR, the content looks very diluted. We have several blogs that covers the general use cases of ML algorithms in different industries. Moreover, the facts that you've stated aren't really backed by proper research (Statements like `SVM is the best algorithm and memory efficient` - You must back them proper research). And, I don't think it's a very in-depth article diving into any technical concepts.

I feel this could have been better if you have covered the exact problem that we face, and the solution to overcome it. For example, you have stated about outlier detection using SVM - your points are more generalized and not specific to the healthcare industry.

These are just my opinions. I may be wrong. Let's get another pair of eyes to verify it.

@lalith1403 What do you think about this topic? Do you think the author can improve further on existing work? If so, can you suggest a few ideas?

Please let the author know about the next steps.

Thanks.

**Pull request closed without merging**
