### PR TITLE
What is RabbitMQ? Dockerize a RabbitMQ Instance using Docker Containers

### LINKED ISSUE #3018: What is RabbitMQ? How to Build and Dockerize a RabbitMQ Instance using Docker Containers
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

What is RabbitMQ? How to Build and Dockerize a RabbitMQ Instance using Docker Containers

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

RabbitMQ is an open-source distributed message queue that supports many communication protocols. It is a message broker, and it receives from senders (producer) and forwards messages to receivers (consumer). Producer, consumer, and RabbitMQ broker do not have to reside on the same host. Messages flow through RabbitMQ and your applications. These messages can only be stored inside a queue. A queue is essentially a large message buffer. Many producers can send messages that go to one queue, and many consumers can try to receive data from one queue.

This guide will discuss RabbitMQ broker in detail and then dockerized a RabbitMQ instance using docker containers.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

What is RabbitMQ
The essential components of RabbitMQ
RabbitMQ Publisher and Consumer
Set up RabbitMQ using docker containers
RabbitMQ Use cases
Other technologies similar to RabbitMQ 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Faithdroid**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

 This fixes #3018

### CODE REVIEW

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by Faithdroid** [comment]
@paulodhiambo, Any progress on the reviews?

**Comment by LinusMuema** [comment]
Hi @paulodhiambo 
Is this article ready for final review? Because I can see you still have some pending reviews.
You could do away with that then add the ready-for-final review label.

**Comment by Faithdroid** [comment]
> Hi @paulodhiambo
> Is this article ready for final review? Because I can see you still have some pending reviews.
> You could do away with that then add the ready-for-final review label.

@LinusMuema, I can see a ready-for-final review label already.
Screenshot 2021-08-20 124451

**Comment by LinusMuema** [comment]
I know...But there is "1 pending reviewer" which might mean he has other unreviewed issues.
So I need him to confirm the review is done.
Screenshot from 2021-08-20 12-51-36

**Comment by paulodhiambo** [comment]
Hello @LinusMuema the article is ready for final review

**Comment by LinusMuema** [comment]
Please make sure you finish any pending reviews or unresolved suggestions before adding the "ready for final review" label in the future to avoid uncertainty.

**Comment by LinusMuema** [comment]
Hi @Faithdroid 
Thanks for this article. It is quite informative and interesting. Just check my commits for minor edits.
Also, your folder name was quite long. Ensure you check my changes for future reference.

cc: @paulodhiambo

**Pull request merged**
