### PR TITLE
[Duplicate of #5438] how-to-build-a-full-stack-application-with-supabase-react-and-tailwindcss-in-nextJs 

### LINKED ISSUE #5106: How to Build a Full Stack Application With Tailwind CSS and Supabase in NextJs
### Topic Suggestion
How to Build a Full Stack Application With Tailwind CSS and Supabase in NextJs

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

- [https://www.section.io/engineering-education/how-to-build-authentication-api-with-jwt-token-in-nodejs/](https://www.section.io/engineering-education/how-to-build-authentication-api-with-jwt-token-in-nodejs/)
- [https://www.section.io/engineering-education/how-to-build-a-clock-with-javascript-and-svg/](https://www.section.io/engineering-education/how-to-build-a-clock-with-javascript-and-svg/)
- [https://www.section.io/engineering-education/a-friendly-beginner-guide-to-typescript/](https://www.section.io/engineering-education/a-friendly-beginner-guide-to-typescript/)

#### Proposed title of the article
How to Build a Full Stack Application With Tailwind CSS and Supabase in NextJs

#### Proposed article introduction

The React Framework for Production, Next.js, provides the finest developer experience with all the capabilities you need for production: hybrid static and server rendering, TypeScript support, smart bundling, route pre-fetching, and more. There is no need to configure anything.

Supabase is a free and open-source Firebase alternative.
It includes all of the backend services you'll require to create a product. You can utilize it entirely or just the services you need, such as database, authentication, and file storage.

Tailwind is a CSS framework with a focus on utility for quickly creating bespoke user interfaces.

#### Key takeaways 
In this article, the reader will learn
- How to scaffold a NextJs project and also the basics
- How to integrate supabase into a NextJs application
- How to build a full-stack application with supabase and tailwind CSS

#### Article quality
This article provides a step-by-step tutorial to building a full-stack application with tailwind CSS and supabase in a NextJs application.

#### References
- [https://supabase.io/docs/](https://supabase.io/docs/)
- [https://nextjs.org/](https://nextjs.org/)
- [https://tailwindcss.com/](https://tailwindcss.com/)

### PR DESCRIPTION
**Pull request by Olanetsoft**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5106 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by hectorkambow** [comment]
@Olanetsoft Please ping the reviewer that was on before.

Please note that the article should have been proofread (multiple times at this point), to catch anything the reviewer may have missed. Any extra revisions (needed) from this point will close the PR indefinitely

**Comment by Olanetsoft** [comment]
I will proof read and ensure its fine before I ping the reviewer,  thanks.

**Comment by Olanetsoft** [comment]
@Kayere All changes updated, Kindly review.

Looking forward to hearing from you

cc: @hectorkambow

**Comment by Olanetsoft** [comment]
Plagiarism Review/Check 👇

Screenshot 2021-12-14 at 00 04 13

**Comment by srishilesh** [comment]
@M0nicah 

Duplicate of #5438.

Looks like you had assigned yourself for reviewing this PR earlier. Assigning this PR to you.

**Comment by WanjaMIKE** [comment]
Please correct the plagiarized errors highlighted in the attached report. Thanks
[New Scan 5_45 AM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7791645/New.Scan.5_45.AM.Copyleaks.Report.pdf)

**Comment by Olanetsoft** [comment]
Hello, @WanjaMIKE. Happy New Year!

Going through the report you shared, I realized most of the things highlighted by copy leaks have to do with react syntax and even tailwind CSS styles, and these things are reusable everywhere. 

Not sure if this is considered plagiarism in Section Engineering because it's the regular syntax used for building and styling web applications.

See screenshot of the highlighted content below:

Screenshot 2022-01-09 at 01 10 25
Screenshot 2022-01-09 at 01 09 48
Screenshot 2022-01-09 at 01 09 23
Screenshot 2022-01-09 at 01 08 53

Cc: @hectorkambow

**Comment by M0nicah** [comment]
should I continue with the review? @WanjaMIKE , @hectorkambow

**Comment by WanjaMIKE** [comment]
There are sentences highlighted in the report showing plagiarism. Please go through them. Thanks

**Comment by hectorkambow** [comment]
Closing PR due to it being stale!

**Pull request closed without merging**
