### PR TITLE
[API, Node.js, FormData, Fetch] How To Use FormData Web API With Fetch to POST Form Data As JSON To An API Endpoint

### LINKED ISSUE #5852: How To Use FormData Web API With Fetch to POST Form Data As JSON To An API Endpoint
## Proposed title of the article
How To Use FormData Web API With Fetch to POST Form Data As JSON To An API Endpoint

## Proposed article introduction
The Fetch API is used to make requests from a web on the front end through to the back end API endpoint, but if you want to send the data to the API as JSON, a bit of extra work is needed. This article demonstrates how to make use of the FormData and Fetch API to send form data as JSON.

## Key takeaways 
- In-depth guide and core concepts around the FormData and Fetch APIs.
- How to make use of the built-in browser APIs to send form data as JSON.
- How to receive form data as JSON at an API endpoint.

## Article quality
In this article, we explore the core concept of FormData and Fetch APIs from the ground up in a clear and concise manner making it friendly for beginners and people with no prior knowledge of the two APIs.
With an example then make use of the built-in FormData and Fetch APIs(no external packages) to implement step by step form that sends data as JSON to an API endpoint.

## References
[Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)
[FormData API](https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by gisioraelvis**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5852

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by gisioraelvis** [comment]
I'm done with the corrections, kindly review my article.
Thanks

**Comment by gisioraelvis** [comment]
@hectorkambow 
Kindly review my article.
Thanks

**Comment by srishilesh** [comment]
@gisioraelvis 

Looks like this PR two different `index.md` files. Please make sure to remove unwanted files.

**Comment by gisioraelvis** [comment]
@srishilesh 
Screenshot from 2022-01-09 22-38-38

There's only one index.md

**Comment by srishilesh** [comment]
@gisioraelvis 

I would suggest you to take a look here - under `Files Changed` tab:

image

**Comment by gisioraelvis** [comment]
@srishilesh 
How do I delete the other files, they are not mine, don't know how they got to my PR.

**Comment by gisioraelvis** [comment]
> @srishilesh Screenshot from 2022-01-09 22-38-38

Those and my author files are the only ones I pushed

**Comment by srishilesh** [comment]
> @srishilesh How do I delete the other files, they are not mine, don't know how they got to my PR.

@gisioraelvis 

There are chances that you wouldn't have pulled/rebased the master branch before raising a PR.

Now, your PR has merge conflicts.

I would suggest you to refer the contribution guidelines [here](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/UPLOAD_INSTRUCTIONS.md).

You would have to do these:

```bash
git fetch section
git pull --rebase section master
git push origin
```

**Pull request closed without merging**
