### PR TITLE
Using Edge Computing to handle Content Migration

### LINKED ISSUE #7072: [Edge Computing] Using edge computing to handle content migration
#### Proposed title of article
Using edge computing to handle content migration

#### Proposed article introduction
Content migration involves moving of one content from one content management system to another. The process at times sounds simple and straightforward, but it usually reveals areas of improvement in the site architecture, the design, and the content itself. In case any of these happens the migration process shifts from just 'lift and shift' to reorganizing and redesigning the architecture or content.

A typical migration involves the redesign of information architecture, page, content audit, new taxonomy, or even rewriting content. Sometimes migration may involve switching from one URL to another which poses a number of challenges. Most of these challenges can be solved using edge computing as it will be covered in the proposed article.

#### Key takeaways 
At the end of the article the reader will understand:
- the concept of edge computing and content migration
- the strategies followed for a successful content migration
- the issues associated with content migration and how edge computing offers solutions to each of them

#### Article quality
The article is useful to the entities preparing to perform a successful content migration as it uses a practical approach to possible issues that can arise and be handled using edge computing.

#### References
N/A

### PR DESCRIPTION
**Pull request by ephnjor2021**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #7072

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Review by mercymeave — COMMENTED** [review]
Hello @ephnjor2021 

Please add an `index.md` in your author folder that describes you. Something like a bio.

**Comment by mercymeave** [comment]
> Hello @ephnjor2021
> 
> Please add an `index.md` in your author folder that describes you. Something like a bio.

Hello @ephnjor2021, Ignore this, when I saw the avatar, I thought maybe it's your first time contributing 😊. Seems you have a profile already. Thanks 🙏

**Review by mercymeave — APPROVED** [review]
Great read. Moving this to a final review.

**Comment by ephnjor2021** [comment]
@mercymeave Thank you

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Comment by WanjaMIKE** [comment]
Merged #7494 into master

**Pull request merged**
