### PR TITLE
Using a Hard Margin vs Soft Margin in Support Vector Machines

### LINKED ISSUE #4084: [Machine Learning] Using a Hard Margin Vs Soft Margin in Support Vector Machines.
#### Proposed title of article
Using a Hard Margin vs. Soft Margin in Support Vector Machines.

#### Proposed article introduction
As long as the algorithm is given a training set of labeled data, it will generalize between different classes using the support vector machine. The SVM's primary job is to look for a hyperplane that can tell the difference between the two classes of data.
Using Support Vector Machines, you can perform classification and regression with ease. The type of margin to use is crucial while trying to solve a problem.

This tutorial will go through the differences between utilizing a hard margin and a soft margin while performing SVM algorithms.

#### Key takeaways 
- Overview of Support Vector Machines
- The Role of Margin in SVMs
- Support Vector Machines with a Hard Margin
- Support Vector Machines with a Soft Margin
- Hard Margin vs. Soft Margin

#### Article quality
I will make this article unique and beginner-friendly, where I will explain the concepts more straightforwardly to ensure that it adds value beyond what is in the official blogs and docs. My article will go beyond a basic explanation and include a step-by-step basis to ensure that it helps the rest of EngEd.

#### References
N/A

### PR DESCRIPTION
**Pull request by dorky1**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #4084 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by dorky1** [comment]
Hello, @Bayler 
I have made all the changes that you requested.
Thank You.

**Comment by dorky1** [comment]
@Bayler 
Would you put this PR as a Tutorial?

**Comment by Bayler** [comment]
> @Bayler Would you put this PR as a Tutorial?

This is an article. As a rule of thumb, anything that explains a concept is an article. If it is walking a reader through some process of installation, implementation, or explanation of a concept through code,, it is a tutorial.

**Comment by hectorkambow** [comment]
@dorky1 
Good afternoon and thank you for submitting your topic suggestion.

_It seems this PR is still quite a bit aways from being completed_. **As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published.** 
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue). 
 
We will be closing this and please re-submit when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 

Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

**Comment by dorky1** [comment]
Hello, @Bayler 
Would you tell me the progress of this PR please.
Thank You.

**Comment by Bayler** [comment]
@dorky1 Welcome to our Eng-Ed Community. We are delighted to have you as part of our tech community. Please take note of all the commits I've made and just a point to note, to avoid future PR closures, make sure that you submit a polished PR which is ready to be published. 
Regards,
@Bayler

**Comment by WanjaMIKE** [comment]
Merged #4566 into master

**Pull request merged**
