### PR TITLE
Monitoring a Microsoft SQL Server database using Solar Winds Database Performance Analyzer

### PR DESCRIPTION
**Pull request by ruphus-muita**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by srishilesh** [comment]
@ruphus-muita 

On a quick glance at the PR, I noticed that it had merge conflicts on the following files:

```
content/articles/hosting-a-webserver-using-a-raspberry-pi/index.md
content/authors/eunice-wanjiku/index.md
```

Also, I noticed few other files were removed. Please revert them back before we start the review. (Have a look at the `Files Changed` tab to get more info)

Thanks

**Comment by ruphus-muita** [comment]
@srishilesh I had uploaded the wrong content. So I deleted that and instead uploaded the correct article files.

**Comment by srishilesh** [comment]
@ruphus-muita 

There are 2 ways to solve this:
1) Follow the instructions as mentioned in the contribution guide, create a new PR, and mention it as duplicate of #3471 
2) Revert your current changes to the previous commit, and add only the files respective to this article.

Hope this helps.

Thanks.

**Comment by ruphus-muita** [comment]
@srishilesh only the uploaded files solves issue #2938 there was an error while uploading that's why i deleted the unnecessary files. Is it possible for you to continue with the available files?

**Comment by ruphus-muita** [comment]
@hectorkambow  Kindly check the merging issue with this pull request and advise accordingly.

**Comment by ruphus-muita** [comment]
@srishilesh I am closing this PR I will ping you after opening a new one

**Pull request closed without merging**
