### PR TITLE
Multithreading in java

### LINKED ISSUE #1936: Multithreading in Java
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Multi-threading in Java

### Introduction paragraph (2-3 paragraphs):
A thread is a lightweight process. They can be used to perform complicated tasks in the background without interrupting the main program. Any process can have multiple threads running concurrently in it that is referred to as multi-threading. It enables us to improve the responsiveness of a system.
For example in a web browser, we can have one thread which will load the user interface and another thread which will actually retrieve all the data that needs to be displayed in that interface.

We will learn how to create threads in your programs. It can be created by extending the Thread class or implementing the runnable interface.

### Key takeaways: 
1. What is a thread and multi-threading
2. Why we need Multi-threading
3. Create threads by extending the thread class 
4. Create threads by implementing the runnable interface.

### References: 
N/A

### PR DESCRIPTION
**Pull request by Jeff-mwangi**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #1936

### CODE REVIEW

**Comment by Jeff-mwangi** [comment]
@LinusMuema i have reopened the PR.

**Comment by hectorkambow** [comment]
@zolomohan You are taking on too many reviews at one time - please refrain from reviewing more than 1-2 at a time. 👍

**Comment by cyberShaw** [comment]
Hey, @zolomohan. If you haven't started the review, could I review it?
Thanks.

**Comment by LinusMuema** [comment]
Hi @cyberShaw 
I had already started the review process. This is just a new PR to fix a merge conflict issue....

**Comment by LinusMuema** [comment]
Hey @cyberShaw 
You can refer to [this pr](https://github.com/section-engineering-education/engineering-education/pull/2107) for confirmation

**Comment by cyberShaw** [comment]
Oh yeah, sorry @LinusMuema I just saw.
I'll re-assign this PR to you

**Comment by LinusMuema** [comment]
No problem 😊

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by LinusMuema** [comment]
Hi @hectorkambow 
I have added the front matter and peer reviewer line. You can go ahead and finally give the article a final review before publishing.

**Comment by LinusMuema** [comment]
Hi @Jeff-mwangi 
The article will go into the queue but I will talk with @hectorkambow so it can be reviewed faster....✌

**Comment by Jeff-mwangi** [comment]
Thank you @hectorkambow  and @LinusMuema

**Comment by hectorkambow** [comment]
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

**Pull request closed without merging**
