### PR TITLE
How to use brotli compression method

### LINKED ISSUE #5731: [API] How to use Brotli compression method for web applications
### Topic Suggestion
How to use Brotli compression method for web applications

### Writing sample(s): 
https://www.section.io/engineering-education/how-to-troubleshoot-and-monitor-a-database/
https://www.section.io/engineering-education/integration-of-ros-with-arduino/

#### Proposed title of article
How to use Brotli compression method for web applications

#### Proposed article introduction
Static assets such as **.js** ,**.CSS** and **.json** text files are commonly used in web application projects, with redundancy and compression playing an important role. Compression reduces the amount of bandwidth required for website rendering, which speeds up the process.
Brotli is a lossless compression algorithm that combines a current form of the LZ77 algorithm, Huffman coding, and 2nd order context modeling to compress data. 

#### Key takeaways 
1. what is Brotli
2. How brotli works
3. Application of brotli
4. Configuring with Nginx
5. Configuring with AWS CloudFront distribution

#### Article quality
This article will add an instance of brotli compression to an already existing instance of Nginx, while also taking the reader through a step by step process in creating a dynamic brotli module.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Newton-cyber**
#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #5731 `

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
You have uploaded 2 articles. Please delete the second one. @Newton-cyber

**Comment by srishilesh** [comment]
@Newton-cyber 

Looks like there is a mismatch between your PR title (Brotli compression method) and the contents of the `index.md` (talks about Arduino).

Please add only necessary files.

**Comment by srishilesh** [comment]
@Newton-cyber 

Just checking if the changes are made.

If you need more time, we can close this PR for now.

**Comment by srishilesh** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
