### PR TITLE
[duplicate] Recovering WiFi Passwords From Windows/MacOS/Linux

### PR DESCRIPTION
**Pull request by LucidRay**

### CODE REVIEW

**Comment by LucidRay** [comment]
Hello @hectorkambow @zolomohan 
 This is an article update from PR #4232

**Comment by hectorkambow** [comment]
@zolomohan  

Let me know if you can jump on this one (if your comp issue is straighten out). 

Otherwise we can re-assign it. 

Also - upon checking it please take a glance to see if the PR still needs any extra edits.

**Comment by zolomohan** [comment]
I can take it @hectorkambow

**Comment by zolomohan** [comment]
Hi @LucidRay, 
This article is still light on substance and the info provided here can be found easily on the internet. 
Is there anything you can add to make your article unique/original?

**Comment by zolomohan** [comment]
https://mackeeper.com/blog/find-wi-fi-password-on-mac/
https://www.geeksforgeeks.org/how-to-find-the-wi-fi-password-using-cmd-in-windows/
https://www.geeksforgeeks.org/wi-fi-password-connected-networks-windowslinux/

These are some of the examples that I could find with a quick search.

@section-engineering-education/content-moderator-team What do you guys think about this topic?

**Comment by LucidRay** [comment]
Hello @zolomohan @section-engineering-education/content-moderator-team 
I think  since my article is a tutorial increase in content may make me be out of topic... i believe that my article is unique by the sense that unlike other articles my article compiles how to recover WiFi passwords from all OS i.e Linux , Windows and MacOS using their terminals and it uses simple grammar hence it's beginner-friendly.

**Comment by zolomohan** [comment]
Alright, The beginning portions of the article only refer to Windows. Please fix that. 

@section-engineering-education/content-moderator-team This article does bring recovering passwords from all operating systems together. Your thoughts?

**Comment by LucidRay** [comment]
Hello @zolomohan 
The requested changes are in place

**Review by zolomohan — APPROVED** [review]

**Comment by Kayere** [comment]
Congratulations on publishing your first article @LucidRay. Please go through the changes made by your peer reviewer and I to help improve the quality of your future articles.

@zolomohan - Please make sure to cross-check the location of the article files in your next reviews 👍. I found the article and author details folders in the wrong locations.

Otherwise, great job 🚀.

**Pull request merged**
