### PR TITLE
Creating Responsive Line and Bar charts with React and Semantic-UI

### LINKED ISSUE #4724: Creating Responsive Line and Bar charts with React and Semantic-ui
### Introduction:
Graphic illustration is an essential form of content presentation in front-end web development. Line and bar charts may have various applications such as, to show statistics of user engagements, user growth, ratings, etc. React.js, semantic-ui and CSS can be used to generate various line and bar charts as we will discuss in this article.
### Key Takeaways:
It is expected that at the completion of this article the reader will be equipped with the knowledge and necessary skill to understand and perform and the following: 
i.	Installing and adding the semantic-ui dependency to your web project
ii.	Getting started with React functional components
iii.	Creating reusable components with React.js
iv.	Generating Line and Bar charts with React.js
v.	Styling the components with CSS and semantic-ui
### References:
https://react.semantic-ui.com/elements/

#### Article quality
This article will walk the reader through the various steps required to generate line and bar charts from an array of numbers used as coordinates. The article will also teach the reader how to create a reusable chart component. Using semantic UI design libraries in creating charts is a unique concept that will be discussed in-depth.

### PR DESCRIPTION
**Pull request by FredBenson**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4724

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by FredBenson** [comment]
hello
@lalith1403, @jerimkaura 
I have made the required changes to the previous PR #4944. please proceed with the final review thank you
cc.
@hectorkambow

**Comment by FredBenson** [comment]
@jerimkaura, @lalith1403 I'm yet to receive any response from you. #4944 was one commit away from being merged.

**Comment by hectorkambow** [comment]
Thank you @srishilesh 

@jerimkaura is this article ready for a final review? 

Take in mind that (generally) any duplicate article should NOT require any additional revisions - & should be fully ready to publish. 

If any more (major) changes, revisions, or edits are required we will be closing the PR indefinitely. 

cc @FredBenson

**Comment by jerimkaura** [comment]
> Thank you @srishilesh
> 
> @jerimkaura is this article ready for a final review?
> 
> Take in mind that (generally) any duplicate article should NOT require any additional revisions - & should be fully ready to publish.
> 
> If any more (major) changes, revisions, or edits are required we will be closing the PR indefinitely.
> 
> cc @FredBenson

Yes the article is ready for final review.

**Comment by hectorkambow** [comment]
@FredBenson Please reach out via Slack DM 👍

**Pull request merged**
