### PR TITLE
Using C# to demonstrate Lock in Thread

### LINKED ISSUE #5427: Using C# to demonstrate Lock in Thread
#### Proposed title of article
[Languages] Using C# to demonstrate Lock in Thread

#### Proposed article introduction
If another thread attempts to access the code currently being executed, the lock construct ensures that no other thread can access it. In multithreading programming, the other thread trying to enter the portion of code where an already existing thread is is made to wait or be blocked until the execution of the thread which is already executing in the piece of code completes. This lock is released once the current thread has finished its work in the part of code, enabling the other threads to continue working in the portion of code as needed.

#### Key takeaways 
By the end of this tutorial, the learner will be able to understand:
- What is meant with Lock in thread and what it entails in C# and moreso where to use it
- Functionality of the Lock feature in C#
- How to work with Lock in C#
- What are the advantages and disadvantages of this concept

#### Article quality
To make this article unique, I will explain all the concepts related to the topic in an in-depth manner. I will cover all possible approaches to this concept adding proper examples with precise outputs and comments. I will also include images wherever necessary. I will employ straightforward language to enhance understanding to make it more exciting and beginner-friendly. The learner will appreciate being subjected to problems with threads likely to arise while working with this lock concept, as I will still be covering it.

#### References
N/A

### PR DESCRIPTION
**Pull request by Nganga89**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

`This closes #5427

### CODE REVIEW

**Comment by Dawe-7** [comment]
Hello @Nganga89, a member from our team of peer reviewers will take a look at your article. I can also review it once i clear my backlog. Thanks.

**Comment by jerimkaura** [comment]
> Hello @Nganga89, a member from our team of peer reviewers will take a look at your article. I can also review it once i clear my backlog. Thanks.

Hello @Dawe-7 let me review this. 

Thanks.

**Comment by Dawe-7** [comment]
> > Hello @Nganga89, a member from our team of peer reviewers will take a look at your article. I can also review it once i clear my backlog. Thanks.
> 
> Hello @Dawe-7 let me review this.
> 
> Thanks.

Go ahead @jerimkaura

**Comment by Dawe-7** [comment]
> > Hello @Nganga89, a member from our team of peer reviewers will take a look at your article. I can also review it once i clear my backlog. Thanks.
> 
> Hello @Dawe-7 let me review this.
> 
> Thanks.

Jumping on this one @jerimkaura

**Comment by louisefindlay23** [comment]
Plagiarism check complete

**Review by Dawe-7 — CHANGES_REQUESTED** [review]
Awesome article @Nganga89, kindly add a prerequisites section as we move on to tech review.

**Comment by Nganga89** [comment]
Hello @Dawe-7, done with the requested change please check thank you.

**Review by Dawe-7 — APPROVED** [review]
Nice article @Nganga89 . Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles. Thank you.

**Comment by Kayere** [comment]
Great article @Nganga89.
Thank you for the review @Dawe-7.

**Pull request merged**
