### PR TITLE
Creating a Custom TypeConverter to Help in Storing Custom Types in Room Database

### LINKED ISSUE #6270: [Android] Creating a Custom TypeConverter to Help in Storing Custom Types in Room Database
#### Proposed article introduction
Sometimes, you need your app to store a custom data type such as Date, Bitmap, etc. in a single database column. You support complex types by providing type converters, which are methods that tell Room how to convert complex types to and from known types that Room can persist. You can identify type converters by using the @TypeConverter annotation.

But sometimes this normal  `TypeConverter` isn't enough. Imagine a scenario where you need to store a `List` of Objects e.g Users, Cars, e.t.c. This requires you to come up with a way that you can convert your Data Type to something that `Room` can understand i.e. maybe that `List` of `Objects` to `String`.

In this tutorial, we will create a custom `TypeConverter` and use it in the Room database.

#### Key takeaways 
- What is a TypeConverter?
- What are the complex types in the Room database
- How to create and use a custom TypeConverter in Room database

#### Article quality
This tutorial will help the reader come up with a custom code that he/she doesn't have to write every time when trying to store complex types in database in their Android apps. The tutorial will be short and direct to the point. Most of the blog sites have not covered this topic.

#### References
- N/A

### PR DESCRIPTION
**Pull request by osirevaline**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6270

### CODE REVIEW

**Comment by Kayere** [comment]
Hello @osirevaline,

 Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Creating a Custom TypeConverter to Help in Storing Custom Types in Room Database #6635 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/8087459/Creating.a.Custom.TypeConverter.to.Help.in.Storing.Custom.Types.in.Room.Database.6635.Copyleaks.Report.pdf)

**Comment by osirevaline** [comment]
@Ericgacoki I have fixed the little plagiarism

cc @Kayere

**Comment by hectorkambow** [comment]
@Ericgacoki why are we adding the plagiarism label again?

**Comment by hectorkambow** [comment]
> @Ericgacoki why are we adding the plagiarism label again?

it was around 13 & NO need to re-run another check for this level of %. We should try to stick to one check per PR (if possible).

**Comment by Ericgacoki** [comment]
Hello @osirevaline
Was this an intentional closure? 🧐 If not, I can reopen and proceed with the review.

**Comment by osirevaline** [comment]
> Hello @osirevaline Was this an intentional closure? monocle_face If not, I can reopen and proceed with the review.

I don't wish to continue with it

**Comment by Ericgacoki** [comment]
Alright!

**Comment by osirevaline** [comment]
Hello @https://github.com/orgs/section-engineering-education/teams/content-moderator-team I have transferred the issue to someone else to continue writing and enhance the article - @feswalsalim

**Pull request closed without merging**
