### PR TITLE
adding authors md file with headshot

### PR DESCRIPTION
**Pull request by rajendraprasadp**
added index.md file with images under content->article and content->authors.

### CODE REVIEW

**Comment by hectorkambow** [comment]
@rajendraprasadp 

If you delete these two files - we can merge and your EngEd author profile will be live on our site 🚀 
image

**Comment by rajendraprasadp** [comment]
Ok I'll do that..If you guys have access you please continue by deleting
those.

**Comment by rajendraprasadp** [comment]
deleted the 2 files

**Comment by hectorkambow** [comment]
🚀

**Pull request merged**
