### PR TITLE
Building Telegram Bot using Python

### PR DESCRIPTION
**Pull request by shosenwales**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by srishilesh** [comment]
@shosenwales 

We have very similar [Section articles](https://www.section.io/engineering-education/search/?q=telegram%20bot) on building a Telegram bot. 

How is your article different from theirs? Does your article target any particular use-case of Telegram bots?

Moreover, I find the same code in [this article](https://newbedev.com/telegram-bot-about-the-bot-code-example).

At Section, we always try to publish unique content that provides values to the readers. Please feel free to modify the article content, targeting any particular use-case. 

Thanks.

cc. @hectorkambow

**Comment by hectorkambow** [comment]
@shosenwales What Topic form is this TIED with?

**Comment by hectorkambow** [comment]
#2496 

Please always put the TOPIC form on the PR to know which on it is tied with Thank you

**Comment by shosenwales** [comment]
Hi,

My initial topic idea was to create a simple bot and host on
PythonAnywhere, but apparently their free accounts can't be used for
Telegram bots anymore.

Not withstanding, i'll rewrite the whole article with a use-case in mind

**Comment by shosenwales** [comment]
Hi @srishilesh, i made changes to the article. Kindly go through.

**Comment by srishilesh** [comment]
@shosenwales 

This looks great.

Though, the current version has over 750 words (752 words exactly), this article doesn't provide much a value to the reader. One suggestion on enhancing this article:

Here, you are doing one way interaction with the user - like posting quotes every 20 seconds. Rather, I would suggest you to implement 2 way interactions - like the user can type `/random` to get a random quote, or `/search` for finding quotes by a specific person, or an API where the user specifies the number of quotes to view. You can have a look at [this](https://quotes.res) website for some more ideas.

You have many free public APIs to do this.

cc. @hectorkambow

**Comment by shosenwales** [comment]
Hi @srishilesh 

Thanks for the suggestion. Will look into it right away.

**Comment by shosenwales** [comment]
Looks like the link you sent isn't correct

**Comment by shosenwales** [comment]
Hi, @srishilesh I just made changes. Kindly go through

**Comment by hectorkambow** [comment]
[Building Telegram bot using python #2721.pdf](https://github.com/section-engineering-education/engineering-education/files/6792972/Building.Telegram.bot.using.python.2721.pdf)

@shosenwales 

There appear to be many sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/)

**Comment by shosenwales** [comment]
@hectorkambow 

Apologies....I just fixed the issue, kindly go through it.

**Review by srishilesh — APPROVED** [review]
Hey @shosenwales,

Thanks for making the changes.

Great article. Moving for the final review.

Make sure to go through my commits

Thanks

**Review by louisefindlay23 — APPROVED** [review]
Final review complete, @shosenwales.

Thanks for peer reviewing, @srishilesh.

**Pull request merged**
