### PR TITLE
How to develop a Business Directory using CodeIgniter and MySQL?

### LINKED ISSUE #3067: How to develop a Business Directory using CodeIgniter and MySQL?
### Proposed title of article
How to develop a Business Directory using CodeIgniter and MySQL?

### Introduction paragraph:
CodeIgniter is a PHP MVC framework which developers use to build web applications rapidly. It provides out-of-box libraries for connecting to the database such as MySQL and performing various tasks such as sending emails, uploading files, managing sessions among others.
This article will provide steps on how to build a simple web directory using CodeIgniter and MySQL. Since CodeIgniter is an MVC framework, the Model will be related to the database, View will be the HTML part seen on the web browser and Controller will be the logic that connects our Models with the Views.

### Key takeaways: 
At the end of the article the reader will be able to:
- set up MySQL database
- define and code the application's model
- create a controller that loads data from the model and pass it to the view
- create various views of the application and the routes to connect to those specific views

### References: 
N/A

### PR DESCRIPTION
**Pull request by kerubo-tech**
The tutorial will help the reader to set up MySQL database, define and code the application's model, create a controller that loads data from the model and pass it to the view
create various views of the application and the routes to connect to those specific views

### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3067

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by kerubo-tech** [comment]
This closes #3067

**Review by jerimkaura — COMMENTED** [review]
Amazing & easy to read article @kerubo-tech

**Comment by louisefindlay23** [comment]
@kerubo-tech, in the future, please add your This Closes comment in the original PR message as it usually doesn't work by adding a new comment.

**Comment by kerubo-tech** [comment]
> Amazing & easy to read article @kerubo-tech

@jerimkaura Thank you

**Comment by kerubo-tech** [comment]
> @kerubo-tech, in the future, please add your This Closes comment in the original PR message as it usually doesn't work by adding a new comment.

@louisefindlay23 Noted with thanks

**Comment by hectorkambow** [comment]
plagiarism check done

**Review by jerimkaura — APPROVED** [review]

**Comment by Kayere** [comment]
Great article @kerubo-tech.
Thank you for the review @jerimkaura.

**Pull request merged**
