### PR TITLE
How to choose the appropriate microservices framework for your project?

### LINKED ISSUE #3524: How to choose the appropriate microservices framework for your project?
### Proposed title of article
How to choose the appropriate microservices framework for your project?

### Introduction:
Microservices architecture allows developers to split a huge monolithic single application into small applications and services that perform lightweight tasks.
Business capabilities and independently deployable models are the primary goals of microservices development. Microservices architecture is built using different programming languages, they can be deployed and interconnected.

Businesses and developers face challenges in choosing the right microservice framework when building their robust applications as fast as possible and at a minimal cost. The article will equip the learners with the aspects to consider when selecting a microservice framework for their projects and compare between different frameworks available.

### Key takeaways: 
At the end of the article, the learner will be able to:
- understand the benefits offered by microservices
- understand critical aspects to consider when selecting the right framework for the project
- highlight different frameworks for developing microservice architecture

### References: 
N/A

### PR DESCRIPTION
**Pull request by martha-ngugi**
The article concentrates on the pros and cons offered by microservices architecture. The aspects to considered when selecting the right microservices framework in terms of planning and organizing, microservices design, development, data storage and management, microservices deployment and hosting, and microservices maintenance and operations. Explain popular frameworks used to develop microservices such as Spring Boot, Eclipse Vert.x, Oracle Helidon, GoMicro, and Molecular.

### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #3524 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
plagiarism check done ✅
Minor edit to do. Please take a look at the report below.

[How to choose the appropriate microservices framework for your project?](https://github.com/section-engineering-education/engineering-education/files/7161158/New.Scan.10_32.AM.Copyleaks.Report.pdf)

**Comment by martha-ngugi** [comment]
> plagiarism check done ✅
> Minor edit to do. Please take a look at the report below.
> 
> [How to choose the appropriate microservices framework for your project?](https://github.com/section-engineering-education/engineering-education/files/7161158/New.Scan.10_32.AM.Copyleaks.Report.pdf)

@ahmadmardeni1 I have fixed the minor issues highlighted.
Thank you. cc @paulodhiambo

**Comment by paulodhiambo** [comment]
@martha-ngugi, **a point to note :** articles should be written in active voice, not passive voice.

**Comment by martha-ngugi** [comment]
> @martha-ngugi, **a point to note :** articles should be written in active voice, not passive voice.

@paulodhiambo Noted, in the next articles I will check on the matter. 
Thank you

**Comment by WanjaMIKE** [comment]
Merged #3753 into master

**Pull request merged**
