### PR TITLE
[Duplicate of #5335]: Build a weather forecast app with nextjs

### LINKED ISSUE #4754: Build a weather forecast app in next js
#### Proposed title of article
Build a weather forecast app in Next.js

#### Proposed article introduction
In this tutorial, I'll be creating a weather application in next js. We'll be using an external API to grab live web data from cities around the world. We'll also use the API to check out the weather forecast of the week.
It's a really basic starter project and for those who have a basic react knowledge and want to go into server side rendered react app with next js then this article is for you. The only prerequisites is for you to have a basic react knowledge

#### Key takeaways 
Use this area to get your ideas down on the bulk of your article or tutorial.
At the end of this tutorial the readers should be able to:
- know what next js is
- when to use it
-Know the  key advantages next js has over react
- Install next js
- Be able to create application in next js
- fetch an external API in next
#### Article quality
This tutorial doesn't just dive into building the app but I'll also take my time to explain what next js is all about and also give tips on when to use it based on my experiences whilst also comparing using the create react app with create next app

#### References
https://nextjs.org/docs/api-reference/create-next-app

### Conclusion
So in this tutorial we've learnt what next js is all about, when to use them, we also compared it with just using the create react app and let's not forget we  built a weather app in next js. Job well done guys would you please share if you found this helpful.

Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Outline
- Title
- Introduction
- What is Next.js
- Why should you use it
- Comparing Next.js with React
- Building the weather app (this includes requirements)
- Conclusion

### PR DESCRIPTION
**Pull request by oyedeletemitope**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **YES)**
- [ ] Is your article properly formatted in Markdown? -  YES)**
- [ ] Have you used our preferred heading structure? - **Yes)**
- [ ] Does your article follow any of the suggested structure formats? - **Yes**

- [ ] Is your article over 750 words? - **Yes**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] My article goes beyond just explaining the framework but an in-depth knowledge is also given
- [ ] Does your article provide enough value and detail about your topic? - **Yes**
- [ ] Can your article be understood by beginners? - **Yes**.

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **I have an Hero image but the size 640 x 360, 600kb. Using this image is purely optional as it can be discarded if it doesn't meet the requirement.** 
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **i can assure you that I rechecked every words using Grammarly and also compared  it using copyleaks. for plagiarism. i can assure you that this article is unique and any similarity in the code is purely coincidental** 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **Yes**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation? - **Yes**
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?-**Yes**

`This closes #4754

### CODE REVIEW

**Comment by oyedeletemitope** [comment]
Any update on the review

**Comment by srishilesh** [comment]
> Any update on the review

@oyedeletemitope 

Apologies for the delay.

Will complete my review by tomorrow.

**Review by srishilesh — APPROVED** [review]
@oyedeletemitope 

Good work!

Make sure to go through my commits, to understand all the changes.

Moving for the final review.

Thanks.

**Comment by oyedeletemitope** [comment]
Thank you sir. I'm going through them as we speak.

**Comment by srishilesh** [comment]
@oyedeletemitope 

I've moved this PR for the final review. Please wait for a CM to publish it.

**Comment by Kayere** [comment]
Congratulations on publishing your first article @oyedeletemitope - Please go over the changes made by your peer reviewer and I to help improve the quality of your future articles.

cc: @srishilesh

**Comment by oyedeletemitope** [comment]
Thank you for the corrections made in order to help me improve. I really appreciate your efforts

**Pull request merged**
