### PR TITLE
Quantum key distribution: An overview

### LINKED ISSUE #6090: [Security] Quantum Key Distribution: An overview.
### Topic Suggestion
[Security] Quantum Key Distribution: An overview

#### Proposed title of article
[Security] Quantum Key Distribution: An overview.

#### Proposed article introduction
Quantum key Distribution (QKD), one of the most advanced sub-disciplines of Quantum Information Technology, aims in coming up with novel, sophisticated methods of securely exchanging cryptographic keys by use of basic quantum mechanics concepts such as entanglement and measurement. Since the 1970s, with the advent of quantum cryptography, a number of quantum key distribution or key agreement protocols have been proposed by researchers and academics, with the earliest one being proposed in the year 1984.

#### Key takeaways 
- Understand the types of QKD schemes.
- Understand the intricate workings of major QKD protocols
- Understand the advantage of QKD schemes over conventional classical cryptographic schemes.
- Comprehend potential downside and attacks against QKD schemes.

#### Article quality
This article intends to go deeper into this field while at the same time presenting its ideas in a simple, palatable way for beginners.

#### References
(https://arxiv.org/pdf/1209.0365) [Attacks on quantum key distribution protocols that employ non-ITS authentication.]

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by pop-ecx**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #6090

### CODE REVIEW

**Comment by srishilesh** [comment]
Hello @pop-ecx ,

Welcome to EngEd program!

Thanks for submitting this PR.

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started with the review.

Meanwhile, we suggest you to go through approved PRs/published articles to see if you have missed out anything. This would help us avoid any potential closure of the PR.

Could you please rename the PR and link it to an issue?

Thanks.

**Comment by pop-ecx** [comment]
Hey @srishilesh. It has been 9 days now since submitting my PR and I'm not seeing any progress with regards to that. Is everything alright? Should I be worried?

**Comment by srishilesh** [comment]
Hey @pop-ecx ,

The peer-reviewers are working towards completing existing reviews to take up more. Please wait patiently until a peer-reviewer pings you to get started.

Thanks.

**Comment by geoffrey45** [comment]
Hello @pop-ecx,

I'm Geoffrey, I will be reviewing your article. Your article will now be checked for things like plagiarism, technical accuracy, etc, then published.

Nice to meet you 🤝

**Comment by louisefindlay23** [comment]
Plagiarism check complete

**Comment by pop-ecx** [comment]
Hey @geoffrey45. Nice to meet you too.

**Comment by pop-ecx** [comment]
hey @geoffrey45, I've followed through on your suggestion and added the relevant links to terms as well as a conclusion.

**Review by geoffrey45 — COMMENTED** [review]
@pop-ecx Please add a 600x400 `hero.jpg/png` in your article forder to be used as hero image.

**Comment by pop-ecx** [comment]
@geoffrey45 hero image added.

**Pull request merged**
