### PR TITLE
Bitcoin Vs. Ethereum: Technical Perspective

### LINKED ISSUE #1193: Bitcoin vs Ethereum: Technical Differences
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
These are the two largest cryptocurrencies in the world. But, Ethereum was introduced around 6 years after Bitcoin. This article discusses the key differences between the two and why there was a need for Ethereum. The differences lie in the way consensus is reached, time taken to verify the blocks, and other aspects. Towards the end of the article, we will discuss the applications and the value proposition that each of these currencies propose.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Introduction to Bitcoin and Ethereum. 
2. Technical differences: Comparison based on the mining process, consensus protocols used, hash rates, rewards, and blockchain structure.
3. Value proposition

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

### PR DESCRIPTION
**Pull request by lalith1403**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please *include the PDF generated with plagiarism check*. Place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1193

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
@lalith1403 could you check the plagiarism and attach the pdf.

**Comment by lalith1403** [comment]
I am not able to attach the PDF since it is a pro feature. I am attaching the screenshot. 

image

**Comment by WanjaMIKE** [comment]
@lalith1403 a well written article. Easy to read, review, and understand. I removed a link to `medium.com`. I thought it could direct readers to a competing site for reading articles. Otherwise, nice work.

**Review by WanjaMIKE — APPROVED** [review]
@lalith1403 a well written article. Easy to read, review, and understand. I removed a link to `medium.com`. I thought it could direct readers to a competing site for reading articles. Otherwise, nice work. 
@hectorkambow Lalith had checked for plagiarism as shown in the screenshot.

**Comment by hectorkambow** [comment]
plagiarism check done

**Pull request merged**
