### PR TITLE
Understanding systemd

### LINKED ISSUE #1386: Understanding systemd
### Idea Summary
systemd is a tool used for service initialization amongst Linux based systems.
It's a big divergence from the common System V init implementation such that it's able to flexibly manage dependencies during service startup.
systemd is a relatively new and sophisticated technology which might be intimidating for one to learn as it also has a lot of features.
I will be discussing systemd and its configuration, dependency management and system control using unit files, service activation etc.

### Key Takeways:

- An understanding of why and how systemd is a solution to Sytem V init - deficiencies.
- The different types of unit files and how they work to perform boot-time tasks
- Have an understanding of systemd's method of dependency management
- The reader would be able to manage, edit and write systemd unit files
- Use systemctl as a tool for instrospecting and controlling the state of systemd and service manager

### References: 
- https://wiki.archlinux.org/index.php/Systemd.
- https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files
- https://people.redhat.com/pladd/systemd_NYRHUG_2016-03.pdf

### PR DESCRIPTION
**Pull request by Bashorun97**
### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1386

### CODE REVIEW

**Comment by jumamiller** [comment]
@hectorkambow, this article has been fixed! Ready for final review!

**Comment by zolomohan** [comment]
Hi @jumamiller @Bashorun97 
If this is a duplicate PR, please close the old PR. :)

**Comment by Bashorun97** [comment]
> Hi @jumamiller @Bashorun97
> If this is a duplicate PR, please close the old PR. :)
> 
> I believe #1465 is the old PR.

Alright, it's closed now.

**Comment by hectorkambow** [comment]
plagiarism check done

**Pull request merged**
