### PR TITLE
The Basics of Fraud Detection Analytics

### LINKED ISSUE #4705: [Security] The Basics of Fraud Detection Analytics
#### Proposed title of article
The Basics of Fraud Detection Analytics

#### Proposed article introduction
Technology advancements have come with the risk of internet-related fraud. Fraud in organizations has led to loss of revenue, which has led to the increased demand for fraud detection analytics. Fraud detection analytics enable organizations to detect fraudulent activities early enough to prevent further occurrence or reduce the associated loss. 

This article will provide an overview of fraud detection analytics and explain why it is important in the tech industry. It will also take you through the fraud analytics methods and give you some tips for building a reliable fraud detection framework. 

#### Key takeaways 
1. Importance of fraud detection analytics in the tech industry
2. Fraud analytics process
3. Fraud analytics methods
4. Tips for building a reliable fraud detection framework
5. Use cases for fraud analytics
6. Conclusion

#### Article quality
This article is unique because it uses a different approach from other similar articles published online. It goes beyond these articles by providing handy tips for building a reliable fraud detection framework. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### PR DESCRIPTION
**Pull request by annwawesh**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4705

### CODE REVIEW

**Review by mbaabuones — CHANGES_REQUESTED** [review]
@annwawesh Amazing article! The article is easy to understand and the content has been well organized. Please fix the minor issues highlighted in the article. Ping me when you are done.

**Comment by annwawesh** [comment]
@mbaabuones I have made the suggested changes.

**Comment by LinusMuema** [comment]
plagiarism check done :heavy_check_mark:

**Review by mbaabuones — APPROVED** [review]

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
Overall very nice work 🚀

**Pull request merged**
