### PR TITLE
Integration Challenges and Solutions in Software Development

### LINKED ISSUE #1274: Integration Challenges and Solutions in Software Development
### Brief Summary: 
Integration problems remain hidden throught the development process and become visible at the end of the project. Problems that come with integration leads to extra cost, delays, lower project quality, and may cause failure of the project. This article will address integration challenges during software development and solutions.

### Key Takeaways: 
1. Software Integration
2. Importance of software integration.
3. Software Integration challenges
4. Success factors for software integration

### References: 
N/A

### PR DESCRIPTION
**Pull request by JudyNduati**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you placed your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1274

### CODE REVIEW

**Comment by JudyNduati** [comment]
This fixes #1274

**Review by srishilesh — APPROVED** [review]
Hey @JudyNduati,

Thanks for the PR.

This article looks amazing and beginner friendly. I have learned a lot about system integrations and its importance. I have made minor changes to the flow and formatting. Also, I have added a few sections to enhance the readability. Make sure you go through these changes to improve on your future articles. 

I'm moving this article to the final review.

Thank you

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by hectorkambow** [comment]
@JudyNduati  great article 👍  

Really learned quite a bit about system intregration. 

adding a tiered label due to the level of revision from our reviewer 👍

**Comment by hectorkambow** [comment]
@srishilesh  Please be sure to suggest the changes to be made - we can not make the changes for the contributors unless its a super small change like a missing letter or comma (,). 

👍  

Thank you

**Comment by srishilesh** [comment]
> @srishilesh  Please be sure to suggest the changes to be made - we can not make the changes for the contributors unless its a super small change like a missing letter or comma (,). 
> 
> 👍  
> 
> Thank you 

@hectorkambow 

Sure. Usually, I make suggestions to the article, I review. But, this article had a few errors in flow and formatting, and didn't require much changes from the author. So, I changed them by myself.

Anyway, I'll make sure to suggest the changes from the next time.

Thanks.

@JudyNduati Sorry for the inconveniences caused.

**Pull request merged**
