### PR TITLE
[Duplicate] Understanding different types of menus in android with kotlin

### LINKED ISSUE #4003: [Android] Understanding Different Types of Menus in Android with Kotlin
#### Proposed article introduction
In Android applications, menus are essential building blocks. In this tutorial, you will learn how to design and show menus in your Android apps. 

Why do we need menus:
- To free up screen space
- To perform different operations
- Navigating to other part of the application

We'll look at three different types of menus:
- Options menu
- Contextual menu
- Popup menu

#### Key takeaways 
- You'll learn about the different types of menus.
- How to create  menus
- You'll learn how to build advanced menus like checkable menus and intent-based menus.
- Design guidelines and best practices for Menus

### Conclusion
After completing this tutorial, you'll have the skills and understanding of Android menus necessary to create efficient and user-friendly menus in your Android apps.

### PR DESCRIPTION
**Pull request by benta-odek**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4003

### CODE REVIEW

**Comment by benta-odek** [comment]
hello @hectorkambow and @Ericgacoki 
Have made the necessary changes and opened a new pull request
thank you

**Comment by Ericgacoki** [comment]
Duplicate of [#4747](https://github.com/section-engineering-education/engineering-education/pull/4747)

cc: @Kayere

**Comment by Ericgacoki** [comment]
Hey @benta-odek , I've just spotted white space(s) in some of your file names. Replace the white space  with a hyphen. 
file names

**Comment by benta-odek** [comment]
hello @Ericgacoki  have removed the white spaces

**Review by Ericgacoki — APPROVED** [review]

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
