### PR TITLE
[Duplicate#7097]Morphological operations in image processing using openCV

### LINKED ISSUE #5435: Morphological operations in image processing using OpenCV python.
### Proposed title of the article
Morphological operations in image processing using OpenCV python.

### Proposed article introduction
In this tutorial, we will learn about morphological operations. 
What are morphological operations? -These are image processing transformations applied to either grayscale or binary images. These operations require a structuring element, which is used to define the neighborhood of pixels the operation is applied to. how to use morphological operations to increase the size of objects in images as well as decrease them.
We also discuss on  the most important morphological operations that you’ll use inside your own applications:

### Key takeaways
The reader of this article will understand:

The concept of smoothing technique.
The concept of structuring element.
Commonly used operation(s) i.e erosion,dilation 
Edge detection using Canny filter.
How to convert the color image into grayscale shades.
Performing opening and closing operations
Concept of the morphological gradient.
Know the difference between tophat/whitehat and black hat operations. 

### Article quality
This article will not only equip the reader with the knowledge of morphological techniques but also assist him/her with applications of these operations using proper code samples and generating their output.

### References
N/A.

### PR DESCRIPTION
**Pull request by samtecinnovator**
#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #5435

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
I will check the changes.

**Comment by samtecinnovator** [comment]
looking forward.

**Comment by hectorkambow** [comment]
@WanjaMIKE  

This is a 3rd duplicate - if any edits are needed we will be closing this PR 👍

**Comment by WanjaMIKE** [comment]
Noted @hectorkambow

**Comment by hectorkambow** [comment]
Will be closing this PR - the structure does not seem to be finalized. 

Most of the paragraphs are in bullet format instead of being in a paragraph format. Some headers are not capitalized

**Comment by hectorkambow** [comment]
Will be closing this PR - the structure does not seem to be finalized. 

Most of the paragraphs are in bullet format instead of being in a paragraph format. Some headers are not capitalized

**Pull request closed without merging**
