### PR TITLE
Email authentication and verification Node.js and Firebase

### LINKED ISSUE #1822: Email authentication and verification using Nodejs, Express, and Firebase
### Proposed title of article
Email authentication and verification using Nodejs, Express, and Firebase

### Introduction paragraph (2-3 paragraphs):
Email authentication is one of the most vital application features to implement. Unlike usernames and passwords, emails are easy to remember or retrieve when forgotten. When a system uses email authentication and verification, its users can verify their accounts by clicking a link sent to their emails. Moreover, password recovery procedure is made easier, since the application can allow users to request a password reset, and complete the process with a simple click of a link.

Firebase is a back-end framework that leverages programmers from the need to create their own back-end, encrypt passwords, and deploy their applications. Firebase streamlines the process of user authentication, database management, and analytics. Through firebase, authenticate users when signing in, sending them a link to click to sign in. In the process, the users' emails get verified. This prevents your application from loading the database with dummy emails.

This article helps you learn how to build user authentication and verification using Firebase and Nodejs. We will build and mini-login and registration system to test our implementation.

### Key takeaways: 
1.	Setting up a Nodejs application
2.	Connecting a Nodejs application with Firebase
3.	Email authentication using Nodejs.

### References: 
1. https://firebase.google.com/docs/auth/web/email-link-auth

### PR DESCRIPTION
**Pull request by phinaomondi**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1822

### CODE REVIEW

**Comment by cyberShaw** [comment]
@phinaomondi Can I start reviewing this now (If the article is complete)?

**Comment by jerimkaura** [comment]
Yes it's complete. @cyberShaw

**Comment by phinaomondi** [comment]
> @phinaomondi Can I start reviewing this now (If the article is complete)?

@cyberShaw  Yes you can, I completed the article yesterday.

**Comment by cyberShaw** [comment]
Alright, I'll do the review now. 🚀

**Comment by phinaomondi** [comment]
Thank you @cyberShaw

**Comment by hectorkambow** [comment]
Thank you v much for your patience as we worked through our Repo re-structuring process.

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions).

With most of the changes coming to completion - we will be sure to get your article published asap.

Thank you again - and we are looking forward to more amazing articles.

**Comment by hectorkambow** [comment]
plagiarism check done

**Review by cyberShaw — CHANGES_REQUESTED** [review]
Hey @phinaomondi!

I have a couple important changes that need to be made. 

- Please move your content to the new folder structure. (into content/articles)
- I did a grammar check and saw that there are quite a few typos. Please run the article through a grammar checker and fix those changes.

Once you're done with this, we can move on to tech review.

**Comment by phinaomondi** [comment]
Hey @cyberShaw. I made the following changes:

1. Fixed typing mistakes

2. Moved the article to the suggested directory

Kindly check them out. Thank you.

**Comment by cyberShaw** [comment]
> Hey @cyberShaw. I made the following changes:
> 
> 1. Fixed typing mistakes
> 2. Moved the article to the suggested directory
> 
> Kindly check them out. Thank you.

Thanks for making the changes, we can now do the tech review

**Review by cyberShaw — CHANGES_REQUESTED** [review]
Great article, @phinaomondi!

I had a couple concerns:

1. You have not explained the part where the code checks if you're authenticated or not and accordingly renders HTML in the profile page. (screenshot attached below)
image

2. There are some places where in your code, you have typed `erorr` instead of `error`, please change that in the REPL link. I've made the change in `index.md`

**Comment by phinaomondi** [comment]
@cyberShaw  Fixed the changes and inserted the missing segment. Kindly check.

**Comment by cyberShaw** [comment]
> @cyberShaw Fixed the changes and inserted the missing segment. Kindly check.

Please add the extra section to the Table of Contents, please

**Comment by phinaomondi** [comment]
> > @cyberShaw Fixed the changes and inserted the missing segment. Kindly check.
> 
> Please add the extra section to the Table of Contents, please

@cyberShaw Done!

**Comment by hectorkambow** [comment]
@phinaomondi Thank you very much - the article is now ready to publish. 

Please do be sure to mind the formatting (not sure why but many lines broke our page margins) perhaps the text was written in word pad or somewhere other than a text editor (my wild guess) 

A few images were incorrectly named - I believe one is included and not needed?? 

Not sure.  we can add later if need be. 

Go through all the suggestions made by your Peer reviewer and myself during my final to help speed publishing along and avoid potential future article closure. 🚀 

Grear work - looking forward to more awesome tutorials.

**Comment by hectorkambow** [comment]
cc @cyberShaw please do the same go through my final review - articles ready for final review should be more polished before the final label. 👍

**Pull request merged**
