### PR TITLE
Setup & run Docker containers on computer engine

### LINKED ISSUE #2804: Setting and Running Docker Containers on Google Compute Engine
### Proposed title of article
Setting and Running Docker Containers on Google Compute Engine

### Introduction paragraph (2-3 paragraphs):
Google Compute Engine (GCE) is an infrastructure-as-a-service (IaaS)  that enables programmers to run workloads on physical Google hardware. To this end, Google Compute Engine avails several virtual machines (VMs) that can be used as large-scale processing clusters. For this reason Google Computer Engine is a helpful for utilizing the vast Google Infrastructure.

Containers are convenient methods to run your application in multiple instances at the same time. Containers and enables one to run the same application but on different platforms conveniently. However, containers need to  be hosted somewhere where an application and its dependencies are packaged together. This is where Google Compute Engine comes in.  In this article, the reader will be able to install and run a Docker container on the Google Compute Engine.

### Key takeaways: 
1. Understanding Google Computer Engine
2. Creating Docker containers
3. Dockerizing a flask application
4. Installing and running Docker Containers on Google Cloud Engine
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by victorelvice**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #2804

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by hectorkambow** [comment]
@victorelvice 

[Setup & run Docker containers on computer engine #3637.pdf](https://github.com/section-engineering-education/engineering-education/files/7117830/Setup.run.Docker.containers.on.computer.engine.3637.pdf)


👋 Good afternoon - and welcome to the EngEd program.
There appear to be many sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).
We're really looking for unique/original content

cc @jerimkaura

**Comment by victorelvice** [comment]
> @victorelvice
> 
> [Setup & run Docker containers on computer engine #3637.pdf](https://github.com/section-engineering-education/engineering-education/files/7117830/Setup.run.Docker.containers.on.computer.engine.3637.pdf)
> 
> wave Good afternoon - and welcome to the EngEd program.
> There appear to be many sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).
> We're really looking for unique/original content
> 
> cc @jerimkaura

Good afternoon @hectorkambow , I understand how much section.io is strict concerning plagiarism. However, from the plagiarism report, most of the highlights are from an my previous article in section.io. It was same concept but with different implementation and technologies. I am sure this is a unique implementations of the concept except for the snippets that I  lifted from my previous article Because the article was not about the snippets but deployment.

Let me know what you think.

Thanks!

cc: @jerimkaura

**Comment by hectorkambow** [comment]
We will re-open and run another report once the PR is revised 👍

**Comment by victorelvice** [comment]
@jerimkaura, kindly take a look at this PR

@hectorkambow

**Comment by ahmadmardeni1** [comment]
plagiarism check done ✅

**Review by jerimkaura — COMMENTED** [review]
Proceeding to tech review

**Review by jerimkaura — APPROVED** [review]
Thank you for this article @victorelvice, looking forward to more informative article like this one. Just be patient and wait for the final review from one of the content moderators.

**Comment by LinusMuema** [comment]
Hi @victorelvice 
Great work on the article. The final review is done.

cc: @jerimkaura

**Pull request merged**
