### PR TITLE
Getting started with Visual Basic .NET

### LINKED ISSUE #2924: Getting started with Visual Basic .NET
### Introduction paragraph (2-3 paragraphs):
Desktop application development is among the high-growth fields in tech. We use different technologies to create the apps and among them is Visual basic.net.
Visual Basic.net is a multi-paradigm, object-oriented programming language. We implement it in the .NET framework developed by Microsoft. We widely use it in creating desktop applications. In this tutorial, we will look at the most important basic parts of Visual Basic. net step by step.

### Key takeaways: 
1. set up an environment for running Visual Basic.net i.e. Visual Studio
2. Understand visual basic.net syntax
3. write a hello world program

### References: 
N/A

### PR DESCRIPTION
**Pull request by Dyrstiu**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #2924

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Plagiarism check done.

**Comment by WanjaMIKE** [comment]
Plagiarism check done.

**Comment by lalith1403** [comment]
@Dyrstiu Can you navigate me to your author's folder? I am unable to find it.

**Comment by lalith1403** [comment]
This is a very well written article with easy to understand explanations and steps. Well done :).

**Comment by Dyrstiu** [comment]
Thank you for the review @lalith1403

**Comment by Dyrstiu** [comment]
@lalith1403 <https://github.com/lalith1403>
Here is the path to my author's page
engineering-education/authors/felix-vaati/

**Comment by LinusMuema** [comment]
Hi @Dyrstiu 
This article is really amazing and easy to follow through. Absolutely awesome. Keep up the good work.

cc: @lalith1403

**Pull request merged**
