### PR TITLE
Creating a one to one video call Android app with Agora SDK using Kotlin

### LINKED ISSUE #4752: [Android] Creating a One-to-One Video Call Android App with Agora SDK with Kotlin
#### Proposed article introduction
Agora is a video, voice and live interactive streaming platform, helping developers deliver rich in-app experiences—including embedded voice and video chat, real-time recording, interactive live streaming, and real-time messaging. 

Agora’s Video SDK makes it easy to embed real-time video chats into web, mobile and native apps.

Agora's Video Call APIs can add exciting features like AR facial masks and sound effects to social apps, while screen sharing, whiteboards, and other capabilities may help business and educational apps. 

In this tutorial, we will implement the SDK in an Android App so as to add video call features to the app.

#### Key takeaways 
- What is Agora SDK?
- How to Create and get Access Key for Agora
- Implementing the SDK for a One-to-One Video call app.

#### Article quality
Articles about Agora SDK 1-to-1 video calling are very few and most of those that are are written in Java, whereby I will write this article in Kotlin. Also, most blogs and videos on Youtube mostly focuses on implementing the SDK in Flutter.

#### References
- [Agora SDK Documentation](https://docs.agora.io/en)
- [Agora Video Call](https://docs.agora.io/en/Video/API%20Reference/java/index.html)

### PR DESCRIPTION
**Pull request by sheecodes**
This fixes #4752

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Review by Ericgacoki — CHANGES_REQUESTED** [review]
Hey @sheecodes, have a look at the issues mentioned below and ping me when you're done fixing them!

**Comment by sheecodes** [comment]
Hello @Ericgacoki 
I have fixed the requested changes

**Review by Ericgacoki — APPROVED** [review]
Awesome tutorial @sheecodes. Keep it up 👏

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
Overall very nice work 👍

**Pull request merged**
