### PR TITLE
Implementing Database Driven Push Notifications in Android with Firebase

### LINKED ISSUE #5992: [Android] Implementing Database Driven Push Notifications in Android with Firebase
#### Proposed article introduction
Push notifications come in handy when you want to give your app's users timely information based on the product that the app is dealing with. Take, for example, an app that deals with giving out and repaying loans. It will be a bad user experience when a user makes a payment and he/she is not notified on the amount paid, balance and other relevant information.

In this tutorial, we will understand what Push notifications are and  their importance. We will then dive deep in understanding how one can send Push notifications based on changes in the Firebase Realtime database.

#### Key takeaways 
- An understanding of what Push notifications are.
- Setting up push notifications both on the Firebase console and on an Android project.
- An understanding of how to send Push notifications based on interactions with the database

#### Article quality
Most of the articles and blog posts on the internet focus on explaining how to setup Push notifications with Firebase and very few explains the concept of Database Driven Push Notifications in Android. This article and I will bring out this topic clearly, making it easy for developers of all levels to understand.

#### References
N/A

### PR DESCRIPTION
**Pull request by JoelKanyi**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5992

### CODE REVIEW

**Comment by srishilesh** [comment]
@Ericgacoki 

Make sure to assign yourself to the PRs that you are reviewing.

**Comment by LinusMuema** [comment]
Hi @JoelKanyi 

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Implementing Database Driven Push Notifications in Android with Firebase #6369 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7989140/Implementing.Database.Driven.Push.Notifications.in.Android.with.Firebase.6369.Copyleaks.Report.pdf)

**Comment by Ericgacoki** [comment]
> Hi @JoelKanyi
> 
> Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.
> 
> [Implementing Database Driven Push Notifications in Android with Firebase #6369 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7989140/Implementing.Database.Driven.Push.Notifications.in.Android.with.Firebase.6369.Copyleaks.Report.pdf)

Kindly let me know when you're done! I case you need additional help (or have any questions), feel free to reach out to me on Slack!

**Comment by JoelKanyi** [comment]
@Ericgacoki , made the changes

**Comment by Ericgacoki** [comment]
@LinusMuema
Could you please  run the plagiarism check again! Thanks🙂

**Comment by louisefindlay23** [comment]
Plagiarism check complete

**Review by Ericgacoki — APPROVED** [review]

**Pull request merged**
