### PR TITLE
File handling in java and C#

### LINKED ISSUE #4159: Difference between File handling in Java and C#
#### Proposed title of article
[Languages] Difference between File handling in Java and C#

#### Proposed article introduction
 A file is a unit of storage that stores data permanently in the form of a sequence of bytes on a disk. File handling now is a process of storing data in a file using a program.

In Java, we use FileReader and FileWriter classes respectively to read and write data from text files whereas, for C# we will use the FileStream class which is used to read from and write to any location within the file. C# also uses the StreamWriter class which we will discuss more in this article. 

File handling helps in preserving the data or information generated after running the program. File handling in Java and C# permits, creating, deleting, updating, and reading files.

#### Key takeaways 
- How to use the classes specific for file handling
- How to create, delete, update and read  files 
- Importance of file handling

#### References
N/A

### PR DESCRIPTION
**Pull request by apondi-911**
This fixes #4159

### CODE REVIEW

**Comment by paulodhiambo** [comment]
@apondi-911 please link the issue related to this PR.

**Comment by apondi-911** [comment]
This fixes #4159

**Comment by apondi-911** [comment]
Am asking about the progress?

**Comment by paulodhiambo** [comment]
@WanjaMIKE please check plagiarism on this article.

**Comment by WanjaMIKE** [comment]
@paulodhiambo plagiarism check done. Could you take time and compare this article with this https://www.geeksforgeeks.org/file-handling-java-using-filewriter-filereader/ Are they similar?

**Comment by paulodhiambo** [comment]
@apondi-911 please ensure your content is unique. Explain your code snippets, I will be closing this article for now to clear the queue. Once you are done with the correction, I will reopen. For any assistance, ping via slack.

**Pull request closed without merging**
