### PR TITLE
[Duplicate of #5782] - Building a lyrics search app using vanilla JavaScript with OVH API

### PR DESCRIPTION
**Pull request by shegz101**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by shegz101** [comment]
@srishilesh @WanjaMIKE have created a new Pr

**Comment by srishilesh** [comment]
Duplicate of #5782

**Comment by srishilesh** [comment]
Hey @WanjaMIKE ,

The author has created a new duplicate PR for #5782 with all the final review changes that you made. It's waiting to be merged.

Thanks.

**Comment by WanjaMIKE** [comment]
@srishilesh seems there is still an issue with the PR. I will ask Hector to check it out. Thanks

**Comment by shegz101** [comment]
@WanjaMIKE could it be that the issue is from my end.

**Comment by WanjaMIKE** [comment]
> @WanjaMIKE could it be that the issue is from my end.

Seems the issue is specific/isolated to this PR.

**Comment by shegz101** [comment]
@WanjaMIKE what can be done to resolve the issue.

**Comment by srishilesh** [comment]
> @WanjaMIKE what can be done to resolve the issue.

Not sure.

Let @hectorkambow take a look at it, to see what can be done.

**Comment by shegz101** [comment]
@srishilesh @WanjaMIKE could it be that the issue are the PRs i opened which are linked to the issue (topic suggestion). I think the PRS were not closed and they are linked to the my topic suggestion (issue).

**Comment by hectorkambow** [comment]
@shegz101  Lets please do some investigating and see if we can create a PR that does not have any issues - we are not seeing this problem with any other newly submitted pull request.

**Comment by shegz101** [comment]
@hectorkambow may I know the what the issue is exactly.

**Comment by srishilesh** [comment]
> @hectorkambow may I know the what the issue is exactly.

@shegz101 

The issue is - during the final review before publishing, the CMs usually render/preview the article locally using Hugo server. There seems to be some issue with this PR that it doesn't allow the article to be rendered.

We are not sure what exactly is the issue.

Until then, what I suggest you to do is:
- Take a copy of the latest version of this PR (latest files - according to the last commit) - store the files locally somewhere
- Then, you'll have to re-fetch the latest master by following these commands: (Make sure you are in `master` branch)

```bash
git fetch section
git pull --rebase section master
git push origin
```

- Once you do this, checkout to a new branch (**don't use your current branch `new-pr`, create a new one**)
- Put the copied local files back to this branch.
- Create a new PR.

**Expected result: A new PR with just 1 commit containing all the latest changes**

image

**In your new PR, the commits must show `1`.**

Hope you understand the procedure. Ping me in case of any questions.

Meanwhile, let me recheck on this issue by trying to render in Hugo.

Closing this PR for now. Ping me in the new PR.

Thanks.

**Comment by shegz101** [comment]
@srishilesh Thanks. I would let you know when am done.

**Comment by shegz101** [comment]
@srishilesh am getting error that section is not a git repo

**Comment by srishilesh** [comment]
> @srishilesh am getting error that section is not a git repo

@shegz101 

It need not be "section". It can be your remote origin that points to this repo.

**Comment by shegz101** [comment]
Ok

**Pull request closed without merging**
