### PR TITLE
Manipulating Excel(Spreadsheet) data and files in Android using the Apache POI library

### LINKED ISSUE #5810: [LANGUAGES] Manipulating Excel(Spreadsheet) data and files in Android using the Apache POI library
### Topic Suggestion
[ANDROID || LANGUAGES] Manipulating Excel(Spreadsheet) data and files in Android using the Apache POI library

### Writing sample(s): 
My samples are found [here](https://www.section.io/engineering-education/javascript-math-animations/)

#### Proposed title of the article
Manipulating Excel(Spreadsheet) data and files in Android using the Apache POI library

#### Proposed article introduction
Maybe you are trying to preprocess data for some custom on-device model or you want to create your own spreadsheet app, you have to know how to first manipulate the spreadsheets. In his article, we will look at creating a spreadsheet file, opening it, and then performing common statistical functions in it.

#### Key takeaways 
The user will learn about:
- Accessing spreadsheets in Android.
- Using Kotlin to implement this.
- Performing common statistical functions such as mode, median, variance, standard deviation, etc.
- Additionally, how Retrofit plays a hand in this.

#### Article quality
It will be simple to follow and guide the user on getting the files from local storage. We will also perform the statistical functions, something other blogs haven't shown.

> We might also look at saving changes done to a spreadsheet. I'm still doing my research on this.

#### References
I used [this](https://www.geeksforgeeks.org/how-to-read-data-from-google-spreadsheet-in-android/) to get insights. It talks about reading one from Google Sheets.

### PR DESCRIPTION
**Pull request by vinstex**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5810

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Ericgacoki** [comment]
Hello @vinstex, is this article complete? If so, please wait for `plagiarism check` after which you'll make the necessary changes!

**Comment by vinstex** [comment]
Noted. It was just some minor cheanges, but I'm done. Thank you.

**Comment by vinstex** [comment]
@Ericgacoki, any update on the review progress?

**Comment by Ericgacoki** [comment]
@vinstex
I barely had something to edit 👏. Keep up the good work 🚀🚀

**Comment by vinstex** [comment]
@Ericgacoki, thank you for the review.

**Pull request merged**
