### PR TITLE
[Duplicate of #5038]: Object detection with YOLOv5 and PyTorch

### LINKED ISSUE #4636: [Machine Learning] Object Detection using YOLOV5  and PyTorch
#### Proposed title of article
Object Detection using YOLOV5 and PyTorch

#### Proposed article introduction
Object detection is a computer vision task that involves identifying objects in image and video data. Object detection is mostly applied in security, autonomous vehicles, face recognition, etc. 

In this tutorial, we will be building an object detection model using the YOLOV5 algorithm. YOLOV5(You Only Look Once) is a fast and accurate object detection algorithm that works by splitting images into a grid where each grid cell identifies an object by itself.

We will be implementing the YOLO object detection model in PyTorch and training it using the COCO dataset.

#### Key takeaways 
- Understanding YOLOV5
- Understanding object detection
- Using Pytorch

#### Article quality
This article provides more handy tips and dives deeper into object detection with YOLOV5.

#### References
- https://cocodataset.org/#download
- https://pytorch.org/hub/ultralytics_yolov5/

### PR DESCRIPTION
**Pull request by FREDERICO23**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4636 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by FREDERICO23** [comment]
@srishilesh I believe this should now be it. I've done all the requested changes. 
cc @hectorkambow

**Comment by srishilesh** [comment]
I'll complete my tech review by tomorrow.

**Review by srishilesh — APPROVED** [review]
@FREDERICO23 

Great work. Finally, we made it to the final review after several revisions. Good job!

Make sure to go through my commits to understand the changes.

Moving for the final review.

Thanks.

**Comment by srishilesh** [comment]
@section-engineering-education/content-moderator-team  This PR is duplicate of #5038. Requesting for the final review.

**Comment by Kayere** [comment]
Great article @FREDERICO23.

Thank you for the review @srishilesh 🚀.

**Pull request merged**
