### PR TITLE
Voice Identification using Classification Algorithms

### LINKED ISSUE #4077: voice identification using classification algorithms
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed title of article
[Machine learning] voice identification using classification algorithms 

#### Proposed article introduction
Many high-tech goods gradually invaded our daily lives during the information age, drastically altering our lifestyles. Information technologies, on the other hand, are continuing to progress towards a more human-centered approach. Biometric identification technology has gradually superseded several of the previous authentication methods that need to be investigated before people can properly manage them. Biometric identification results include face recognition technologies used in public areas, law enforcement agencies, and Siri voice mobile assistant on iPhone and Bixby Voice on Galaxy.

#### Key takeaways 

1.  Classification
2.  Feature extraction and configuration parameters
3. The proposed speech identification system

#### Article quality
The classification techniques for the problem of personality recognition by voice using machine learning approaches are discussed in this article. In the speech preprocessing procedure, we used the MFCC method. A comparative examination of five classification methods was performed to answer the problem.
#### References
machine learning

### Conclusion
In this article, a number of classification algorithms and speech preprocessing issues will be considered.
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by JOEOBY**
#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #4077

### CODE REVIEW

**Comment by JOEOBY** [comment]
@hectorkambow  this is the update of the article and i  have done the necessary changes.
cc @Bayler (help delete the extra files added)

**Comment by Bayler** [comment]
> @hectorkambow this is the update of the article and i have done the necessary changes. cc @Bayler (help delete the extra files added)

@JOEOBY I can't. I don't have the write access to do that. You should be able to do that from your end. I'm not sure how. You can research how to do that using the terminal.

**Comment by JOEOBY** [comment]
@Bayler any progress on the article.
Thanks.

**Comment by Bayler** [comment]
> @Bayler any progress on the article. Thanks.

As the article was flagged for having plagiarized content, I cannot proceed until plagiarism check is done. Please be patient.

**Comment by hectorkambow** [comment]
@section-engineering-education/content-moderator-team 

This PR has been waiting for a plagiarism check for a week? 👀

**Comment by hectorkambow** [comment]
Doing a plagiarism check now 👍

**Comment by hectorkambow** [comment]
@Bayler 

Please be sure to ping us with such wait times (via Slack).

**Comment by hectorkambow** [comment]
@Bayler 

If any more major revisions are needed - we will be closing this PR asap. 

PS: we could check for any glaring grammatical errors before a plagiarism check - no need to perform another check if the article is not up to par and will be closed. 👍

**Comment by hectorkambow** [comment]
Plagiarism check done 👍 @Bayler

**Comment by JOEOBY** [comment]
@hectorkambow  you can jump on to this..
Thanks 👍😊

**Comment by hectorkambow** [comment]
will be doing a final review for this one

**Comment by hectorkambow** [comment]
@JOEOBY 

Upon trying to do a final review - the article was a bit difficult to understand. It also seemed like a lot of the info is well covered elsewhere.

We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or via many other blog sites

**Pull request closed without merging**
