### PR TITLE
Getting Started With AGM

### LINKED ISSUE #3416: Getting Started with Google Maps in Angular 12 applications
### Proposed title of article
Getting Started with Google Maps in Angular 12 applications

### Introduction paragraph (2-3 paragraphs):
You may have seen many websites, mobile applications with GIS Map integrations. There are many map solutions but Google Maps is one of the best nevertheless for commercial use, you must buy subscription. In this tutorial, we shall focus on only Google Maps for free usage.

This is a comprehensive tutorial about how to work with Google Maps in the Angular 12 application. In this tutorial, we will learn how to create an interactive Google Map in Angular.

We will learn how to add Google Maps using Google Maps API manually, we are going to rely on Open source Google API to achieve the task.

Also, we will use Angular Google Maps (AGM) Core plugin to embed the map in the Angular 12 application. It is a superb plugin to create Google Maps components in Angular.

### Key takeaways: 
- Create Angular Application
- Install Angular Google Maps Plugin
- Get Maps API Key
- Add Google Maps Module in App Module
- Create Google Map in Angular

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by bhanjibrilliant**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?
This closes #3416

### CODE REVIEW

**Comment by hectorkambow** [comment]
@bhanjibrilliant 

Just pinging you on this PR - as I'm making some room in the backlog queue.

No rush if you're still working on this one - if you need more time we can always re-open at a later date.

**Comment by bhanjibrilliant** [comment]
@jumamiller, I have made all changes, kindly reopen the PR.

**Comment by jumamiller** [comment]
Hello @bhanjibrilliant, your hero image is missing, kindly upload before we move to final review!

**Comment by bhanjibrilliant** [comment]
> Hello @bhanjibrilliant, your hero image is missing, kindly upload before we move to final review!

Uploaded!

**Review by jumamiller — APPROVED** [review]
@bhanjibrilliant, great work!

**Comment by hectorkambow** [comment]
Will be testing it on my end.

**Comment by hectorkambow** [comment]
Images did not render during the preview. 🤔  

Forked repo may be out of date. (not up to date with main repo).

**Pull request merged**
