### PR TITLE
[API] Building a CRUD API with the Dapper ORM in ASP.NET Core

### LINKED ISSUE #4576: [API] Building and Documenting a CRUD API with the Dapper ORM and Swagger in ASP.NET Core
#### Proposed title of the article
[API] Building a CRUD API with the Dapper ORM in ASP.NET Core

#### Proposed article introduction
ORM stands for Object Relational Mapper(ORM). It could also stand for Object Relational Mapping, which explains the technique that ORMs use. An ORM is usually a library that makes communicating with our database easy. It uses a mechanism that makes our database look like one very big object. ORMs employ [abstraction](https://en.wikipedia.org/wiki/Abstraction_(computer_science)) to ‘hide’ the unwanted details and focus on the very important and basic functionalities. After abstraction, our data is then broken into smaller chunks which are referred to as [models](https://en.wikipedia.org/wiki/Database_model). In this article, we'll be learning how to build a Todo API by using [Dapper](https://dapper-tutorial.net/) to make queries. After development, we will also be documenting our API with swagger.

#### Key takeaways 
After reading the article, the reader should:
- Know what ORMs are and how they work
- Be able to create an ASP.NET Core API project
- Be able to make queries with the Dapper ORM
- Document an ASP.NET core API with Swagger

#### Article quality
This article goes as far as explaining what ORMs are and how they work. It also tells the user about Dapper and why it's a good choice for an ORM. It explains the methods that are provided by Dapper and how they work. It walks the reader through the whole process of creating a Dotnet API project. As a bonus, the user also learns how to document the API with Swagger.

#### References
- https://en.wikipedia.org/wiki/Abstraction_(computer_science)
- https://en.wikipedia.org/wiki/Database_model
- https://dapper-tutorial.net/

### PR DESCRIPTION
**Pull request by olumidayy**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4576

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Please always use the template provided by us.
I edited your initial comment and added the template. Check what matches your article.

**Comment by olumidayy** [comment]
Thanks, @ahmadmardeni1. I've made changes accordingly.

**Review by jumamiller — CHANGES_REQUESTED** [review]
Hi @olumidayy, a great article here. Could you explain the code snippets!

**Comment by olumidayy** [comment]
Hi, @jumamiller ! Thanks for the review. I was trying to cut down the article length since it is actually about dapper and how to use it. 😅
I have, however, added more explanation to the snippets.

**Comment by LinusMuema** [comment]
Hi @olumidayy 

Your article appears to have many sentences that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).
We're really looking for unique/original content.

[Building a CRUD API with the Dapper ORM in ASP.NET Core #4970 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7593384/Building.a.CRUD.API.with.the.Dapper.ORM.in.ASP.NET.Core.4970.Copyleaks.Report.pdf)

**Comment by olumidayy** [comment]
Hi, @LinusMuema. I went through the report that you attached and the only external reference that was added was to my own issue which was supposed to be closed by this pull request. And that is rightly so because I used the same introduction and prerequisites as the ones I added in the article proposal. I made sure to conduct proper plagiarism checks prior to submitting. Please let me know if I'm wrong or I'm doing something incorrectly. @LinusMuema 

> Hi @olumidayy
> 
> Your article appears to have many sentences that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/). We're really looking for unique/original content.
> 
> [Building a CRUD API with the Dapper ORM in ASP.NET Core #4970 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7593384/Building.a.CRUD.API.with.the.Dapper.ORM.in.ASP.NET.Core.4970.Copyleaks.Report.pdf)

**Comment by LinusMuema** [comment]
There's a lot of verbatim content from [this article](https://dapper-tutorial.net/step-by-step-tutorial)

**Comment by olumidayy** [comment]
Alright, thanks. So what's the way forward? Will this pull request be re-opened after I make the necessary changes or will I need to open a new one?
@LinusMuema

**Comment by LinusMuema** [comment]
Hi, you can open a new PR since the article needs major reworking to remove the verbatim and red flags.

**Comment by olumidayy** [comment]
Alright, thanks

**Pull request closed without merging**
