### PR TITLE
[Duplicate of #5695] - Morphological-operations-in-image-processing-using-openCV-python

### LINKED ISSUE #5435: Morphological operations in image processing using OpenCV python.
### Proposed title of the article
Morphological operations in image processing using OpenCV python.

### Proposed article introduction
In this tutorial, we will learn about morphological operations. 
What are morphological operations? -These are image processing transformations applied to either grayscale or binary images. These operations require a structuring element, which is used to define the neighborhood of pixels the operation is applied to. how to use morphological operations to increase the size of objects in images as well as decrease them.
We also discuss on  the most important morphological operations that you’ll use inside your own applications:

### Key takeaways
The reader of this article will understand:

The concept of smoothing technique.
The concept of structuring element.
Commonly used operation(s) i.e erosion,dilation 
Edge detection using Canny filter.
How to convert the color image into grayscale shades.
Performing opening and closing operations
Concept of the morphological gradient.
Know the difference between tophat/whitehat and black hat operations. 

### Article quality
This article will not only equip the reader with the knowledge of morphological techniques but also assist him/her with applications of these operations using proper code samples and generating their output.

### References
N/A.

### PR DESCRIPTION
**Pull request by samtecinnovator**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #5435 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.
sunflower-horizon
Dilatedimage
Erodedimage
filteredImg
hero
[index.md](https://github.com/section-engineering-education/engineering-education/files/7863455/index.md)
Oroginalimage
RandomGrayimage
RandomrgbColor

### CODE REVIEW

**Comment by samtecinnovator** [comment]
polished previous article as new PR ping me for updates.

**Comment by srishilesh** [comment]
Duplicate of #5695 .

**Comment by samtecinnovator** [comment]
polished the article.

**Comment by srishilesh** [comment]
@section-engineering-education/peer-reviewers 

Is anyone available to review this PR?

**Comment by srishilesh** [comment]
Hello @samtecinnovator ,

I had a quick glance at your PR. It seems that we have 2 `index.md` files with several other unwanted files. Please remove them.

Moreover, the article doesn't follow the markdown guidelines like:
- The heading does not start with `###`
- Improper capitalization of letters
- Not enough explanation for code snippets
- Indentation

I would highly recommend you to take a look at other approved/merged PRs or published articles to see how other authors have formatted them, and how they have structured the flow.

Since there are several revisions to be made, I'll be closing this PR.

Thanks.

**Pull request closed without merging**
