### PR TITLE
how to create a user login page using java gui

### LINKED ISSUE #2578: How to create a user login page using Java GUI
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Danmasanii**
Created a how-to create a user login page using java GUI article.
The article will show the reader how to create a simple user login page in java and how to authenticate a user. I also included a png hero image, png LoginPage image, and a png folder structure image.

Closes #2578.

### CODE REVIEW

**Comment by hectorkambow** [comment]
@Danmasanii 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀

Thank you.

**Comment by srishilesh** [comment]
@Danmasanii 

Welcome to EngEd community!

Based on your commits, you have modified several files (possibly an issue while pulling files using git). Please ensure you upload only one `index.md` file.

Also, make sure to add authors info with a headshot image under `/content/authors`.

Refer contributing guide for more information.

Thanks.

**Comment by Danmasanii** [comment]
> @Danmasanii
> 
> Welcome to EngEd community!
> 
> Based on your commits, you have modified several files (possibly an issue while pulling files using git). Please ensure you upload only one `index.md` file.
> 
> Also, make sure to add authors info with a headshot image under `/content/authors`.
> 
> Refer contributing guide for more information.
> 
> Thanks.



> @Danmasanii
> 
> Welcome to EngEd community!
> 
> Based on your commits, you have modified several files (possibly an issue while pulling files using git). Please ensure you upload only one `index.md` file.
> 
> Also, make sure to add authors info with a headshot image under `/content/authors`.
> 
> Refer contributing guide for more information.
> 
> Thanks.

Thank you, I uploaded only one index.md file in article folder and author folder. thank you

**Comment by srishilesh** [comment]
@Damephena 

The issue still persists.

I believe this commit `af6d6370004207259ad6edf87da7df3b0ae307c8` is causing the issue, since you have not rebased with the master.

From this commit `d6e61a60a8c2c3751f0515230bb16df25099edd0`, it looks right.

Read the [uploading instructions guide](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/UPLOAD_INSTRUCTIONS.md). You would have to do the following:

git fetch section
git pull --rebase section master
git push origin

Thanks.

**Comment by Danmasanii** [comment]
> @Damephena
> 
> The issue still persists.
> 
> I believe this commit `af6d6370004207259ad6edf87da7df3b0ae307c8` is causing the issue, since you have not rebased with the master.
> 
> From this commit `d6e61a60a8c2c3751f0515230bb16df25099edd0`, it looks right.
> 
> Read the [uploading instructions guide](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/UPLOAD_INSTRUCTIONS.md). You would have to do the following:
> 
> git fetch section
> git pull --rebase section master
> git push origin
> 
> Thanks.

I tried running the above code but i keep getting this response.
SAVE_20210716_234057

SAVE_20210716_234027

Thanks

**Comment by duncandegwa** [comment]
Hello @Danmasanii 
Please go through this [article](https://www.section.io/engineering-education/how-to-submit-your-first-article/) it will help PR correctly

Feel free to ping via slack if you have any issues

**Comment by srishilesh** [comment]
Thanks @duncandegwa for sharing this. @Danmasanii Please see if this works.

```
git fetch section
git pull --rebase section master
git push origin
```

This must be done before you had created a new PR. If nothing works, I suggest you to create new PR, and ping me.

**Comment by Danmasanii** [comment]
@duncandegwa 

Thanks for the hint.
Closing #2814 pull request

**Comment by Danmasanii** [comment]
> Hello @Danmasanii
> Please go through this [article](https://www.section.io/engineering-education/how-to-submit-your-first-article/) it will help PR correctly
> 
> Feel free to ping via slack if you have any issues

Thanks

**Pull request closed without merging**
