### PR TITLE
Introduction to PHP Operators

### LINKED ISSUE #2545: Introduction to PHP Operators
### Proposed title of article
Introduction to PHP Operators

### Introduction paragraph (2-3 paragraphs):
PHP Operator is a symbol i.e used to perform operations on operands. In simple words, operators are used to perform operations on variables or values. For example:

$num=10+20;//+ is the operator and 10,20 are operands  

In PHP, we have different types of operators depending on the number of operands they take. There are some operators that take only one operand and perform an operation on it. This type of operators are called unary operators. Another type of operators are binary operators which take two operands.

### Key takeaways: 
1. Instaling PHP and Xampp in Linux
2. Define what is an operator and an operand
3. Learn the roles of different operators
4. Category of PHP Operators
5. Use Operators to perform mathmatical computation

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by mussooo**
### Article checklist
This Fixes #2545

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by mussooo** [comment]
Hey @jerimkaura, I've opened a new PR. You may proceed with the review. Thank you!

**Comment by jerimkaura** [comment]
Hey @ahmadmardeni1 

This PR is a duplicate of #2895

Could you please give this duplicate PR a final review?  I had done my review in the old PR and @mussooo made the changes I asked for.

cc. @hectorkambow

**Comment by ahmadmardeni1** [comment]
Thank you for your review 🚀 @mussooo 

This PR still needs a plagiarism check before the final review.

**Comment by jerimkaura** [comment]
> Thank you for your review  @mussooo
> 
> This PR still needs a plagiarism check before the final review.

@ahmadmardeni1, I was on my test review so I still have to rights to add labels.

**Comment by ahmadmardeni1** [comment]
Don't worry about it. Just @ me and I will add the labels for you. @jerimkaura

**Comment by jerimkaura** [comment]
Alright @ahmadmardeni1, Thank you!

**Comment by ninjaginja** [comment]
plagiarism check complete - all good
[2120420-5a307c19dd792ed7e882-1626820339072.pdf](https://github.com/section-engineering-education/engineering-education/files/6851596/2120420-5a307c19dd792ed7e882-1626820339072.pdf)

**Comment by ahmadmardeni1** [comment]
Welcome to Section and congrats on your first PR @mussooo 

After some careful consideration, we realized this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. As we're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We believe this is the best way for students to build a great portfolio (for potential employers) is by building what does not exist and what can provide the most value.

You are more than welcome to continue working on this one by flushing it out a bit more (i.e. "add some more detailed examples that show where you’d actually use them in a real-life web app")

cc @jerimkaura

**Comment by ahmadmardeni1** [comment]
Also, please go over the changes I made to improve the future reviews. @jerimkaura

**Comment by ahmadmardeni1** [comment]
Hey 👋 @mussooo 
You told me on Slack that you edited your tutorial - you didn't commit the changes.

**Comment by hectorkambow** [comment]
👋  Good afternoon @mussooo 
Just wanted to ping you to make sure you've committed the changed needed so we can proceed with our review(s).

**Comment by mussooo** [comment]
@hectorkambow changes committed. Please have a look.

cc @ahmadmardeni1 
I apologize for the delay.

**Comment by ahmadmardeni1** [comment]
Welcome to Section EngEd and congrats on your first article.🎉 @mussooo

**Pull request merged**
