### PR TITLE
Working with AdMob Interstitial Google Ads in the Android application - Kotlin 

### LINKED ISSUE #6328: Working with AdMob Interstitial Google Ads in the Android application - Kotlin
### Topic Suggestion
Working with AdMob Interstitial Google Ads in the Android application - Kotlin

#### Proposed article introduction
Every developer has reasons as to why they always develop new applications. Many of them may create an app that does not generate a profit in comparison to the amount they spent. In addition, the developer may develop an interest in collaborating with other organizations through advertising their products and services, maybe with a fee. This can only be integrated using AdMob Interstitial Google Ads to achieve the objective by adding the ad to the application. When the user is surfing through the application on the internet, the ad will pop up in the application and the interested party may get more information about the advert.

This tutorial will be an in-depth guide to what is AdMob Interstitial ads and how you can integrate them into an android app using Kotlin language.

#### Key takeaways 
1. Walkthrough to AdMob Interstitial Google Ads.
2. Setting up the Android Studio.
3. Adding the relevant dependencies of the project.
4. Designing the user interface.
5. Writing the Kotlin code.
6. Testing the application.
7. Conclusion.

#### Article quality
The article will be beginner-friendly by using precise explanations and simple code syntax that will make developers build interest to add ads in the daily applications they develop and monetize from them. 

#### References
N/A

### PR DESCRIPTION
**Pull request by kipsd254**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #6328

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Plagiarism check complete. It might be a good idea to add a sentence or two in the introduction to explain to users that the goal of the articles is that they implement AdMob Interstitial Google Ads.

**Comment by hectorkambow** [comment]
👀  

@davigin 

Are you still working on this PR? 

Both the PR & topic form have been closed - it would need to be re-submitted.

**Comment by kipsd254** [comment]
Yes @hectorkambow everything is in place. Hope @paulodhiambo will reopen the topic when reviewing.

**Comment by kipsd254** [comment]
Hi @hectorkambow,
Am sure the topic and the PR was submitted months before the transition. I am sure you mentioned the transition will affect topics that will be suggested lately not the PR's. On the inactivity, i was sure there was a backlog of articles and still i had to recheck the article submission content just to be perfect. Am sure reopening should not lead to the label but the submission of the topic. @srishilesh combine your efforts here for a rule on the white label.

**Comment by WanjaMIKE** [comment]
Merged #7018 into master

**Comment by hectorkambow** [comment]
> Hi @hectorkambow, Am sure the topic and the PR was submitted months before the transition. I am sure you mentioned the transition will affect topics that will be suggested lately not the PR's. On the inactivity, i was sure there was a backlog of articles and still i had to recheck the article submission content just to be perfect. Am sure reopening should not lead to the label but the submission of the topic. @srishilesh combine your efforts here for a rule on the white label.

This was submitted before the transition - but due to its inactivity and closure (on March 31st) are the main reasons for the label. 

PR (articles are expected to be submitted once finished) - we try to prevent PRs being re-submitted over and over (in an effort to reduce the backlog we had). 

We hope this helps explain the situation.

**Comment by hectorkambow** [comment]
Please go through the list of author and see how many profile you have created - so we can delete the ones that are not needed.

**Pull request merged**
