### PR TITLE
Developing a one-to-one mapping application leveraging hibernate

### LINKED ISSUE #1716: Developing a one-to-one mapping application leveraging hibernate.
### Title:
Developing a one-to-one mapping application leveraging hibernate.

### Introduction:
Hibernate is an object relational mapping tool(ORM) for mapping object-domain model to relational database. This means that hibernate creates the tables according to the classes(objects) created and annotated as entities and also generate the fields in the classes annotated as columns in the database. Hibernate also is responsible for CRUD operations apart from when complex queries are required resulting to use of hibernate query language(HQL).

In this tutorial the reader will learn how to implement a one-to-one relationship application by applying the four CRUD operations and how cascading is handled by hibernate.

### Key takeaways:
1.The reader should be able to configure or set up a hibernate application.  
2.The reader should be able to develop a hibernate application.  
3.The reader should be able to control cascading using hibernate.  

### References:
- [Hibernate user guide](https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html)  
- [Maven repository](https://mvnrepository.com/)  
- [one-to-one relationship](https://www.baeldung.com/jpa-one-to-one)

### PR DESCRIPTION
**Pull request by davidmbochi**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please *include the PDF with plagiarism check*. Place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

[//]: # (This fixes #1716)

### CODE REVIEW

**Comment by Manley12** [comment]
@davidmbochi Don't forget to fill out the checklist. It helps with the review process!

**Comment by davidmbochi** [comment]
@Manley12  I filled out the checklist.

> @davidmbochi Don't forget to fill out the checklist. It helps with the review process!

**Review by Manley12 — COMMENTED** [review]
Overall the article sounds great. 

There are a few minor changes that would improve the article, however.

**Comment by hectorkambow** [comment]
@davidmbochi  

This article has a [merge conflict](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/FAQ.md#i-have-a-merge-conflict---how-do-i-resolve-it) - please close this Pull request to submit a new one with only your files.

**Pull request closed without merging**
