### PR TITLE
How to use CSS Selectors

### LINKED ISSUE #2650: CSS Selectors and how to use them to Style Your Web Page
### Proposed title of article
 CSS Selectors and how to use them to Style Your Web Page

### Introduction paragraph (2-3 paragraphs):
CSS selectors are one of the most important parts of CSS. They let you style specific HTML elements on your website differently.

You wouldn't be able to style your page the way you want it to look without CSS selectors.

If you want to create amazing elements then you need to understand the CSS selectors and what you can do with them. You need to understand the basic CSS selectors before you work your way up to the advanced CSS selectors.

This article will cover both. By the end, you will be able to use CSS selectors to create your incredible elements.

### Key takeaways: 

1. Definition of CSS Selectors
2. CSS Element Selectors
3. Universal Selector
4. How to Group CSS Selectors
5. Advanced CSS Selectors

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Beatricewanjiru**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
This fixes #2650

### CODE REVIEW

**Review by Ericgacoki — COMMENTED** [review]
@Beatricewanjiru, this is indeed a very nice article. I've made a few changes to improve the flow and to fix a few points you might have missed out. Please be sure to check them out.

Moving on to `tech review` 🚀

**Comment by Beatricewanjiru** [comment]
@Ericgacoki, thanks for the ping. I will check out your changes to improve on my next articles.

**Comment by Beatricewanjiru** [comment]
@Ericgacoki, I have updated the hero image. Please have a look at it.

**Review by Ericgacoki — APPROVED** [review]

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by kayere** [comment]
@Beatricewanjiru 
@Ericgacoki 
I'll be doing a final review for this article.

**Comment by hectorkambow** [comment]
@kayere 

👀  
Will be trying out a test final review 👍

**Review by kayere — APPROVED** [review]
Great article @Beatricewanjiru. Very informative.

@Ericgacoki - Please go over the changes I have made to help improve future reviews.

@hectorkambow - I am done with the final review.

**Pull request merged**
