### PR TITLE
Javascript split

### LINKED ISSUE #2861: JavaScript Split – How to Split a String into an Array in JavaScript.
### Proposed title of the article
JavaScript Split – How to Split a String into an Array in JavaScript.

### Introduction paragraph (2-3 paragraphs):
The split() method in JavaScript is a technique that parts a string into a variety of substrings and returns the new exhibit. 
If an empty string (" ") is utilized as the separator, the string is parted between each character. 
The split() technique doesn't change the first string.

In this article, I shall look deeply at how you can use the split method in JavaScript by understanding what the split method entails first and then digging deep into the real usage of the split method in JavaScript.

### Key takeaways: 
1. The split() Method in JavaScript
2.  Splitting  a String by Each Character
3. Splitting  a String into One Array
4. Splitting  a String Using a Non-matching Character

### References: 
N/A

### PR DESCRIPTION
**Pull request by Joshuathuo**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #issue-number`
This closes #2861

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by jumamiller** [comment]
@Joshuathuo, I've noticed you didn't follow our  set standards/structure whiile working on this article. Kindly go over  [here](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors) to find more. Alternatively, head over to already published articles  [here](https://www.section.io/engineering-education) to understand how they are done.  Thanks.

**Comment by Joshuathuo** [comment]
@jumamiller What have I gone against please

**Comment by jumamiller** [comment]
Hi, thanks for getting back,

The article is not well structured. For example, you have introduced the concept without the introduction part, what the reader expects to get at the end of the article. You have not told us what you'll  be covering in the tutorial. That's why I've suggested the above resources to get you started quickly. If you're stuck anywhere, feel free to reach me on Slack.

**Comment by Joshuathuo** [comment]
Thanks @jumamiller . Meaning that I have to include the introductory part

**Comment by jumamiller** [comment]
> Thanks @jumamiller . Meaning that I have to include the introductory part

Go over to the suggested resources (refer to first comment).

**Comment by hectorkambow** [comment]
@Joshuathuo 

[Javascript split #3433.pdf](https://github.com/section-engineering-education/engineering-education/files/7027946/Javascript.split.3433.pdf)

There appear to be many sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/)

**Pull request closed without merging**
