### PR TITLE
Build a web scraper using ExpressJs, NodeJs and Cheerio 

### LINKED ISSUE #5887: Build a web scraper using ExpressJs, NodeJs and Cheerio
#### Introduction
Sometimes we find the need to extract data from a website, but it becomes a challenge when there is no API available for developers. Most websites allow for the extraction of data through a process called "Web Scraping" as long as legal policies are adhered to.
Web scraping helps in the automation of tasks such as manually listing all the products in a company's website, copying out the country code of all the countries in a website's drop-down list, and almost any form of information a website may contain. Data scientists find Web scraping to be a very useful tool as they can scrape data and organize them in tables for proper analysis, developers can build APIs from the data.
In this tutorial we will build a simple web scraper using backend technologies (NodeJs, ExpressJs) for running the web scraper code on the server, Cheerio - a tool for parsing the websites HTML in NodeJs, and Axios for making HTTP requests. We will be extracting product names, prices, and ratings from Amazon's website. The web scraper can be customized based on the developer's needs. 

#### Key takeaways 
At the end of the article the reader should:
- Be able to build a simple web scraper
- Understand how to parse HTML elements with Cheerio
- Be able to customize the web scraper based on their needs.

#### Article quality
This article aims to introduce web scraping to beginners and advanced developers. It is detailed and quickly gets the reader up to speed with building web scrapers and applying them to popular websites.

#### References
- https://www.npmjs.com/package/cheerio
- https://www.section.io/engineering-education/getting-started-with-web-scraping-using-python/
- https://www.youtube.com/watch?v=BqGq9MTSt7g

### PR DESCRIPTION
**Pull request by deverten**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5887

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by srishilesh** [comment]
Hello @deverten ,

Thanks for submitting this PR.

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you with the changes to be made.

Meanwhile, we suggest you to go through other approved PRs/published articles to see if you have missed out anything that might avoid a potential PR closure.

Thanks.

**Comment by WanjaMIKE** [comment]
is the `index.md` file empty?

**Comment by deverten** [comment]
> is the `index.md` file empty?

i just fixed it. Thanks

**Comment by deverten** [comment]
@srishilesh @WanjaMIKE can you please take a look at the PR again. Thank you

**Comment by srishilesh** [comment]
> @srishilesh @WanjaMIKE can you please take a look at the PR again. Thank you

@deverten 

I can see the `index.md` file now.

Please until a peer-reviewer pings you to get started with the review.

**Review by Jethro-magaji — CHANGES_REQUESTED** [review]
Hi ! @deverten 
Well done for such an amazing article, however there are some changes you need to make. Please go over my review and make these changes.
Use 1st person "You" or "Your" instead of "We", "Our" or "lets", correct in all instances.
Thanks.

**Comment by deverten** [comment]
> Hi ! @deverten Well done for such an amazing article, however there are some changes you need to make. Please go over my review and make these changes. Use 1st person "You" or "Your" instead of "We", "Our" or "lets", correct in all instances. Thanks.

I have effected the changes now. Thanks

**Comment by hectorkambow** [comment]
@Jethro-magaji  

We should be avoiding this:
image
Any PR that needs MAJOR revisions should be closed ASAP

**Comment by louisefindlay23** [comment]
Plagiarism check complete

**Comment by Jethro-magaji** [comment]
> @Jethro-magaji  
> 
> We should be avoiding this:
> image
> Any PR that needs MAJOR revisions should be closed ASAP

Alright, Noted. Thanks.

**Review by Jethro-magaji — APPROVED** [review]
Hi! @deverten 
Well done for such an amazing article, please take note of these corrections so that you can minimize revisions in your next article.
Thanks.

**Comment by deverten** [comment]
> Hi! @deverten Well done for such an amazing article, please take note of these corrections so that you can minimize revisions in your next article. Thanks.

Noted! Thank you

**Comment by hectorkambow** [comment]
@deverten Please see the article - as the cheerio.PNG image was not able to be rendered - & I could not find the file in github. 

Please re-add the image and we can merge the changed afterwards 🚀  

cc @Jethro-magaji please walk the student on how to do this

**Comment by Jethro-magaji** [comment]
> @deverten Please see the article - as the cheerio.PNG image was not able to be rendered - & I could not find the file in github. 
> 
> Please re-add the image and we can merge the changed afterwards 🚀  
> 
> cc @Jethro-magaji please walk the student on how to do this 

Alright, noted

**Pull request merged**
