### PR TITLE
Running and Managing Docker Containers

### LINKED ISSUE #2142: Running and Managing Docker Containers
### Proposed title of the article

*Running and Managing Docker Containers*

### Introduction paragraph (2-3 paragraphs):

**Docker** is a tool used to create and run applications using containers that can run virtually anywhere. Some benefits of using Container Technology include enhanced scalability, abstracting your application's underlying infrastructure, efficiency, etc.

In this article we will get an overview of the Docker Image Format, Building the images, and the Docker Container Runtime. Moreover, we will also check about optimizing image sizes, limiting resource usage, and data cleanup.

### Key takeaways: 

After reading this article, the reader will have a kickstart knowledge about:

1. Container images
2. Building Application Images using Docker
3. The Docker Container Runtime 

### References: 

BOOK - Kubernetes: Up and Running by Kelsey Hightower, Brendan Burns, and Joe Beda

### PR DESCRIPTION
**Pull request by Agusioma**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
 This fixes #2142

### CODE REVIEW

**Comment by hectorkambow** [comment]
@Agusioma 
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

cc @geoffrey45

**Comment by hectorkambow** [comment]
[Running and Managing Docker Containers #2179.pdf](https://github.com/section-engineering-education/engineering-education/files/6423623/Running.and.Managing.Docker.Containers.2179.pdf)

**Comment by Agusioma** [comment]
@hectorkambow I have fixed the flags. Please verify

**Comment by geoffrey45** [comment]
@hectorkambow I've checked this article for plagiarism using Quetext, it's plagiarism free.

It is ready for final review.

**Comment by geoffrey45** [comment]
Hello  @Agusioma   :wave:

As you know, we were working on a new structure for our EngEd Repo, which led to a slight slow down of article publishing. Everything is almost ready now.

In order to publish your article as soon as possible, please do the following:
- Download the most recent files off this PR (Make sure to pick the latest one with my revisions and edits).
- Delete your article directory .ie. `running-and-managing-docker` from the `articles` folders.
- Do a git pull (take a look at the new structure of the repo after a git pull).
- Upload your article files to the [new *articles* folder inside *content*](https://github.com/section-engineering-education/engineering-education/tree/master/content/articles) ie. `/content/articles`.

Ping me via Slack if you have any problems.

**Comment by Agusioma** [comment]
@geoffrey45 Closing this. New one at #2359

**Comment by hectorkambow** [comment]
https://www.section.io/engineering-education/running-and-managing-docker/

**Pull request merged**
