### PR TITLE
Adding custom floating action button to bottom navigation bar in android

### PR DESCRIPTION
**Pull request by Jackline-ke**
This fixes issue #4756

### CODE REVIEW

**Comment by Collince-Okeyo** [comment]
Hello , @ahmadmardeni1, I would love to review this article.
CC @hectorkambow

**Comment by ahmadmardeni1** [comment]
Hey, @Collince-Okeyo Are you a test peer reviewer? 
I can't find his name on the list. @hectorkambow

**Comment by WanjaMIKE** [comment]
@Collince-Okeyo Unfortunately, the peer review program is closed for now.

**Comment by LinusMuema** [comment]
Hi @Jackline-ke 

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Adding custom floating action button to bottom navigation bar in android #5086 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7593607/Adding.custom.floating.action.button.to.bottom.navigation.bar.in.android.5086.Copyleaks.Report.pdf)

**Review by Jackline-ke — COMMENTED** [review]
Worked on plagiarism

**Comment by Jackline-ke** [comment]
Hello! @LinusMuema  
I have worked on the plagiarism and  I can see it flagged auto-generate code by Android Studio.

**Comment by WanjaMIKE** [comment]
From ```### Step one``` explain your article in sentences rather than using dashes. Also please use complete sentences rather than 2 or 3 words.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. Not a problem but it seems that this PR is still quite a bit aways from being completed. 
 
In an effort to be fair to our larger EngEd community as a rule of thumb - we can only accept content (pull requests) that are complete and fully polished articles/tutorial - meaning they are ready to be published. 
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) - this allow all revisions to be done on your forked personal repo. 
 
We will be closing this PR and please re-submit it when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 
 
>NOTE: A duplicate PR will go back into the queue and will not receive any further major revisions. A duplicate PR should be 100% ready to be published, otherwise it will be closed immediately. We encourage our new contributors to go over our [resources page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) and [new contributor folder](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors) to be better familiar with the level of quality and style we are looking to publish.
 
Closing a PR does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.
 
👍

**Comment by hectorkambow** [comment]
@Jackline-ke

**Pull request closed without merging**
