### PR TITLE
Valuetuple and valuetuple structure in c#

### LINKED ISSUE #3732: ValueTuple and ValueTuple structure in C#
### Proposed title of article
ValueTuple in C#

### Introduction paragraph (2-3 paragraphs):
The value type Tuple is represented by the ValueTuple structure, which was introduced in C# 7.0.It lets you save a data set with several values that may or may not be connected to one another. It can hold elements ranging from 0 to 8, as well as elements of various sorts. Duplicate components can also be stored in a value tuple.
In this article we will talk about the creating and initializing ValueTuple , accessing ValueTuple named and unnamed members, returning ValueTuple from a method, using ValueTuple helper, ValueTuple deconstruction, and lastly ValueTuple structure.
### Key takeaways: 
1.  Creating and initializing ValueTuple.
2.  Accessing ValueTuple named and unnamed members.
3.  Returning ValueTuple from a method.
4.  Using ValueTuple helper.
5.  ValueTuple deconstruction.
6.  ValueTuple structure.

### References: 
N/A.

### PR DESCRIPTION
**Pull request by MICHELLENGEI**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #3732 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Okay

**Comment by markiesar57** [comment]
> Okay

Thank you

**Comment by WanjaMIKE** [comment]
Currently, it appears you are paraphrasing this article `https://www.geeksforgeeks.org/valuetuple-struct-in-c-sharp/`. Therefore, the article does not have much value. Please work more on this article and resubmit. Thanks

**Comment by MICHELLENGEI** [comment]
@WanjaMIKE 
I have made changes kindly have a look at it
Thank you

**Comment by WanjaMIKE** [comment]
Sure. I will. Thanks

**Comment by WanjaMIKE** [comment]
@MICHELLENGEI make sure to look at the changes, I have made across the article to improve in your future submission. This article took a long time to review and had numerous errors.

**Comment by WanjaMIKE** [comment]
@ahmadmardeni1 could you give this PR a final review. Thanks

**Comment by MICHELLENGEI** [comment]
> @MICHELLENGEI make sure to look at the changes, I have made across the article to improve in your future submission. This article took a long time to review and had numerous errors.

@WanjaMIKE  I have taken time to look at the changes you have made. I'm looking forward to writing more better articles that will take less time in submission. Thank you for your patience with me.

**Comment by ahmadmardeni1** [comment]
Welcome to Section EngEd and congrats on your first article @MICHELLENGEI 

Thank you for the review @WanjaMIKE 
Minor edits 👍

**Pull request merged**
