### PR TITLE
Building a Checkout Form With Stripe Elements

### LINKED ISSUE #5708: Building a checkout form with stripe elements
### Topic Suggestion
Building a checkout form with stripe elements 

### Writing sample(s): 
https://www.section.io/engineering-education/getting-started-with-dot-net-maui-for-cross-platform-apps/
https://www.section.io/engineering-education/using-mldotnet-for-object-detection-in-winforms/
https://www.section.io/engineering-education/different-techniques-of-encoding-data-for-transmission/

#### Proposed title of the article
Building a checkout form with stripe elements 

#### Proposed article introduction
Stripe elements provide developers with prebuilt UI components that allow them to create beautiful checkout flows for their applications. Stripe elements are good when you want to change your application into a payment solution. 

In this article, we will look at how to integrate Stripe elements into an ASP.NET Core project. We shall have a look at each of the following subtopics.
- Introduction to stripe elements
- Explore a custom form
- Payment collection workflow
- Add a stripe checkout to our application
- Customize our payout form
- How taxation is handled

#### Key takeaways 
From this article the reader will be able to;
- Add a stripe checkout to the application
- Know how taxation is handled
- customize a payout form
- Have knowledge of stripe elements

#### Article quality
In this article, I will be taking the reader through the reader through the content and knowledge of stripe elements and how they can be added to a .NET Core application.

#### References
N/A

### PR DESCRIPTION
**Pull request by Geo-free**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [X] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #5708

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Kayere** [comment]
@M0nicah - We will be keeping a keen eye on this PR as @Geo-free expressed an interest in becoming a Peer reviewer 👍🏾.

**Comment by hectorkambow** [comment]
@section-engineering-education/content-moderator-team 

👋  

@Geo-free has expressed interest in doing a try-out pull request to move on to a test review.

**Review by M0nicah — APPROVED** [review]
Great article @Geo-free 
Please go through the changes I made so you could improve the flow in your future articles. Thank you.

**Comment by lalith1403** [comment]
Hello @Geo-free, thank you for a great article. Please go through the changes made by the peer-reviewer.

Hello @M0nicah, there were several readability issues during the review. I would suggest double-checking the review process and ensuring no readability issues exist.

**Comment by Geo-free** [comment]
@lalith1403 
Thank you for the final review and the comment ....I will work on the mentioned commits to improve.

**Comment by Geo-free** [comment]
@lalith1403 
Thank you for the final review and the comment ....I will work on the mentioned commits to improve.

**Pull request merged**
