### PR TITLE
Creating a Flipped Box Card in Android Jetpack Compose

### LINKED ISSUE #5420: [Android] Creating a Flipped Box Card in Android Jetpack Compose
#### Proposed article introduction
Just like how a paper looks when it is flipped on one side, as a developer you may like to create a card that is flipped on one side. This card may be used to display some notes or items in your app.

When using XML to design layouts, this is nearly impossible. With Jetpack Compose, there is no direct Modifier that can be used to achieve this. This is when Canvas in Compose comes in handy.

In this tutorial, we will go through some Canvas concepts in Compose, then we will jump directly to create a Flipped Card. 

#### Key takeaways 
- A quick recap of some advanced concepts of Canvas in Jetpack Compose
- Clipping a shape - Rectangle
- Cutting edges in a shape.
- Creating a Flipped Card Composable

#### Article quality
This article will be very helpful to those developers who are not yet into Compose and would like to use some features of Canvas to customize the default Box Composable. It will be beginner friendly and concise.

#### References
- Canvas for Jetpack Compose

### PR DESCRIPTION
**Pull request by osirevaline**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5420

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Plagiarism check is done.

**Review by Dawe-7 — CHANGES_REQUESTED** [review]
Nice article @osirevaline. I noticed your hero image is not of the required size (600x400 pixels), kindly resize it. Also, i feel your conclusion is too brief, try adding more content. Ping me when done, thanks.

**Comment by osirevaline** [comment]
Happy new year @Dawe-7 
I have made the requested changes.

**Review by Dawe-7 — APPROVED** [review]
Nice article @osirevaline  , kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles. Thank you.

@Kayere, this article is ready for final review.

**Comment by louisefindlay23** [comment]
Please remove the underscores from your image filenames and use hyphens instead.

**Comment by osirevaline** [comment]
Hello @louisefindlay23 , thanks for pointing out that mistake, I will from now on and in other articles use hyphens in my images.
cc @Dawe-7 
cc @hectorkambow

**Comment by Dawe-7** [comment]
> Hello @louisefindlay23 , thanks for pointing out that mistake, I will from now on and in other articles use hyphens in my images. cc @Dawe-7 cc @hectorkambow

@louisefindlay23, could we kindly have a final review of this PR, thanks.

**Review by louisefindlay23 — APPROVED** [review]
Final review complete. Congrats on your published article.

**Pull request merged**
