### PR TITLE
Why load balance application

### LINKED ISSUE #3477: Why Use Load Balancing in an Application.
###Proposed title of article
Why Use Load Balancing in an Application?

###Introduction:
Load Balancing is a critical component of a distributed system. It Spreads traffic across a cluster of servers to improve responsiveness and availability of applications, websites or databases. Load balancers tracks availability of resources while distributing requests. If a server is not available or has an elevated error rate the Load Balancer will stop sending that server traffic.

###Key takeaways:
At the end of this article the learner will be able to:
1) Understand what a Load balancer is.
2) Know the Advantages of using Load balancers.
3) Know the different types of Load balancer algorithms that can be used in an application. 

References:
N/A

### PR DESCRIPTION
**Pull request by munyite-megzs**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? 
- [x] Is your article properly formatted in Markdown?
- [x] Have you used our preferred heading structure? 
- [x] Does your article follow any of the suggested structure formats?
- [x] Is your article over 750 words? 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? 
- [x] Can your article be understood by beginners? 
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it?

#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit.
- [x] Have you checked your article for readability? 
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3477

### CODE REVIEW

**Comment by munyite-megzs** [comment]
@hectorkambow thank you for the heads up about my previous PR("load-balancing-application") that was closed. I am done with the changes.
@M0nicah kindly the article is ready for review. Thank you.

**Comment by Kayere** [comment]
Plagiarism check done ✔️.

**Review by M0nicah — APPROVED** [review]
great article @munyite-megzs, be sure to review the changes I made in the commits to help improve the flow and format for your future articles. Thanks.

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
Overall nice work - please be sure to go through any edits made to improve future articles.

**Pull request merged**
