### PR TITLE
[DUPLICATE] How to Build a Deep Learning Model Using TensorFlow with Python

### LINKED ISSUE #4194: How To Build Deep learning Models Using Tensorflow With Python
#### Proposed article introduction
Google designed and distributed TensorFlow, a Python library for fast numerical computing.
It's a foundation library that can be used to develop Deep Learning models directly or via wrapper libraries built on top of TensorFlow to make the process easier.
In this article, readers will be able to learn more about the TensorFlow Deep Learning library.

#### Key takeaways 
What's Tensorflow?
Importance of deep learning
Steps of Tensorflow Algorithm

#### Article quality
This article goes over the entire machine learning process. We begin by preprocessing our data, after which we will create and train the model to obtain the best prediction.

Unlike the other articles my article will give step to step procedure on how to deploy deep learning models using Tensorflow  with python. I'll use simple grammar, and with all these my article will be useful to readers who are still beginners in machine learning.

### PR DESCRIPTION
**Pull request by TimedH**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x ] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #4194

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by TimedH** [comment]
This is an update of PR #4828

**Comment by hectorkambow** [comment]
@lalith1403 
If any more major revisions are needed - we will be closing this PR asap. 👀

@TimedH 
Please be sure you are going over the entire article for any other mistakes or errors, as our peer reviewers are not responsible to point out every mistake - that is the authors responsibility to properly review and proofread their work.

**Comment by lalith1403** [comment]
@TimedH
It seems this PR is still quite a bit away from being completed.

As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published.

We will be closing this article indefinitely until it can meet the EngEd standards the community expects.

**Comment by EssyH** [comment]
@lalith1403 kindly tell me the problem with this article?

**Comment by TimedH** [comment]
hello @lalith1403 
can you kindly tell the specific problem with this article

**Comment by lalith1403** [comment]
There are several grammatical errors. Please use services such as Grammarly and Hemmingway App. Refer to contribution guidelines for more details.

**Comment by TimedH** [comment]
Ok thanks...I'll check on it

**Pull request closed without merging**
