### PR TITLE
[Duplicate of #7238] - How to build an Internet Service Provider Management System in MERN Stack

### LINKED ISSUE #6915: How to build an Internet Service Provider Management System using MongoDB, Express, React and Node.js
### Topic Suggestion
How to Build an Internet Service Provider Management System using MongoDB, Express, React and Node.js

### Writing sample(s): 
https://dev.to/wanguiwaweru/matplotlib-basics-1aao
https://dev.to/wanguiwaweru/graphs-in-python-1pom

#### Proposed title of article
How to build an Internet Service Provider Management System using MongoDB, Express, React and Node.js

#### Proposed article introduction
In this tutorial, we will learn how to integrate our knowledge of various technologies including MongoDB, React and Node.js to create a functional web application. Internet Service Providers (ISPs) need an informative and dynamic platform to facilitate better management ensuring customer satisfaction and accurate business records.

We will build a management system that allows ISPs to create, read, update and delete customer information and update relevant subscriptions. The ISPs can also retrieve records on the payment status of various customers. The main objective of this tutorial is to provide foundational knowledge on how to create a MERN stack application through a real-life project.

#### Key takeaways 
- Create, Read, Update and Delete (CRUD) operations using MERN stack. 
- Creating a React app.
- MongoDB collections.
- Creating a RESTAPI with Express.

#### Article quality
This tutorial aims to enhance the learners ability to build production-ready fullstack applications. Learners will gain an understanding how the technologies in the MERN stack can be used to build robust products.

#### References
N/A

### PR DESCRIPTION
**Pull request by wanguiwaweru**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6915

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.
Hey @srishilesh,
This fixes #7238

### CODE REVIEW

**Comment by lalith1403** [comment]
plagiarism check done ✔️

**Comment by srishilesh** [comment]
I'll complete my final review by tomorrow.

**Comment by hectorkambow** [comment]
@srishilesh 
Im seeing this is a duplicate - therefore if any more (major) edits are needed we will be closing this PR.

**Comment by srishilesh** [comment]
> @srishilesh Im seeing this is a duplicate - therefore if any more (major) edits are needed we will be closing this PR.

Noted. Will close if the PR requires any major revisions.

**Review by srishilesh — APPROVED** [review]
Hey @wanguiwaweru ,

Thanks for making the changes. Apologies for the delay in final review.

Please have a careful look at the changes I've made before you get started with a new article.

Moving for the final review.

Thanks

**Comment by wanguiwaweru** [comment]
Thank you. I will apply the insights in the next article.

**Comment by hectorkambow** [comment]
We will be reviewing this (& publishing if it is ready) ASAP.

**Comment by hectorkambow** [comment]
👏  

Great work! 

Looking forward to more great article post 
and the comment on this article will be great 🚀

**Comment by wanguiwaweru** [comment]
> 👏
> 
> Great work!
> 
> Looking forward to more great article post and the comment on this article will be great 🚀

Thank you for the review. Looking forward to working on more articles and hackathons at EngEd.

**Pull request merged**
