### PR TITLE
[Duplicate of #6155] Getting started with Nessus Scanner

### LINKED ISSUE #5934: [Security] Getting started with Nessus scanner
#### Proposed title of article
Getting started with Nessus Scanner

#### Proposed article introduction
In this tutorial, I will be introducing you to the Nessus scanner and how to be a good Pen-tester using Nessus.
Nessus is a Web vulnerability scanner that allows you to scan your server/Website for vulnerabilities and provide tips on how to fix them. This is open-source software that is available for all, it is available on Windows but it comes inbuilt in Kali-Linux which makes things even easier.

#### Key takeaways 
The reader should be able to
- Install Nessus and know how to use it.

#### Article quality
Most sites covering the same topic only show you how the installation works and how to scan for vulnerabilities, but how to fix this vulnerabilities with nessus they don't show you.
So I will hold you by the hand and show you different ways to help secure a real site with Nessus after a successful scanning is done. You will be using Nessus to find, fix and update servers to increase your security levels.

### PR DESCRIPTION
**Pull request by Adespscientist**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5934

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Adespscientist** [comment]
@Bayler  I have made changes to this PR

**Comment by Bayler** [comment]
> @Bayler  I have made changes to this PR

I'm not satisfied with the changes. I can still see a lot of grammatical/punctuation mistakes.  Ensure your article is polished before pinging.

**Comment by Adespscientist** [comment]
@Bayler.
Help check if the grammar/punctuation errors have been fixed. Thank you

**Comment by Bayler** [comment]
@Adespscientist Is it hard to perform a grammarly check on your article? We have free tools like [grammarly](https://app.grammarly.com/) that can help you with that. I'm afraid your article is not at par with our level of writing standards. As mentioned in the previously closed PR #6155, I referenced free Google resources to help improve on your technical writing skill. You need to go through all the instructions in our documentation. It's clear you haven't done that. In addition, go through all the articles I've reviewed to get a feel of the best writing styles. As it is, it can't be reviewed until you improve on your writing. I will be closing this PR. 

cc; @section-engineering-education/content-moderator-team @hectorkambow

**Comment by Adespscientist** [comment]
I am so sorry. I have fixed all issues with grammarly.

**Pull request closed without merging**
