### PR TITLE
Statefull vs Stateless Architectures

### LINKED ISSUE #2966: Statefull vs. Stateless Architectures
### Proposed title of the article
Statefull vs. Stateless Architectures

### Introduction paragraph (2-3 paragraphs):
Networks protocols control how data is transferred between different devices in a network. However, you should understand that networking protocols are divided into two: stateful and stateless protocols. Additionally, whether something is stateful or stateless depends on how long the state of interaction with it is being recorded and how that information needs to be stored. 

### Key takeaways: 
- Definition and basic history of stateful and stateless architectures
- The various protocols that utilize the two architectures
- The differences between the two architectures 
- Some of the advantages of each of the architectures 

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Su-sid**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

`This closes #2966

### CODE REVIEW

**Comment by LinusMuema** [comment]
Hi @Su-sid 

Your article appears to have many sentences that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).

We're really looking for unique/original content.

[Statefull vs Stateless Architectures #5168 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7608513/Statefull.vs.Stateless.Architectures.5168.Copyleaks.Report.pdf)

**Comment by Su-sid** [comment]
Hello @LinusMuema, can you open the PR if I add the necessary references?

**Comment by LinusMuema** [comment]
Create a new pr with the changes.
Make sure you go through the pdf well as the second closure is final

**Comment by Su-sid** [comment]
@LinusMuema .Thanks and understood.

**Pull request closed without merging**
