### PR TITLE
Strict Type Validation With Pydantic - (Duplicate of #4445)

### LINKED ISSUE #4169: [API] Strict Type Validation with Pydantic
#### Proposed article introduction
Validating all of your API's inputs will prevent it from a variety of vulnerabilities. It could be time-consuming to write your own validation logic. Many API frameworks have type validation out of the box, whereas lightweight programming frameworks like Flask do not. Type validation can be made easier with frameworks like Pydantic. In this post, we'll look at a variety of Pydantic features and examples of how to use them.

#### Key takeaways 
- Pydantic 
- Integrating Pydantic with APIs
- Advantages of strict type validation

#### Article quality
This article will focus more on type validation and topics around it. It will also cover intricate features like data classes.

#### References
https://pydantic-docs.helpmanual.io/

### PR DESCRIPTION
**Pull request by Bamimore-Tomi**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4169

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Bamimore-Tomi** [comment]
Hi @srishilesh

**Comment by Bamimore-Tomi** [comment]
Hi @hectorkambow  and @srishilesh 

What else do I need to do?

**Comment by srishilesh** [comment]
> Hi @hectorkambow  and @srishilesh 
> 
> What else do I need to do?

@Bamimore-Tomi 

Please wait until a content moderator reviews and publishes it.

**Comment by Bamimore-Tomi** [comment]
Hi @srishilesh @hectorkambow @WanjaMIKE

This PR has been open for 23days. Does it usually take this long to get a content moderator to review?

**Comment by hectorkambow** [comment]
@Bamimore-Tomi 👋  Thank you for following up and patience as our team has been working diligently to work through the recent increased volume of articles coming in. 

We are going through are ready articles in the order they were received and working on improving our review time as well. 

🚀  

Thank you again in advance for your understanding - we will be sure to jump on this ASAP. 

cc @section-engineering-education/content-moderator-team

**Comment by Bamimore-Tomi** [comment]
Hi @hectorkambow, thanks for your response.

I am finding it difficult to join the slack workspace. I see I need to have a @section.io email address.

Please can you send an invite directly to my email - tomibami2020@gmail.com?

Then, I've also noticed your new policy on Paypal. I want to update my Paypal address to - tomibami2020@gmail.com.

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by Bamimore-Tomi** [comment]
Hi @hectorkambow 

I requested to update my Paypal to tomibami2020@gmail.com so that I can be compensated for my last article.

I am also trying to join the section slack workspace, but I can't because I don't have an email address on the requested domains.  Please, I need an invite from you.

Thank you.

**Comment by Bamimore-Tomi** [comment]
I am trying to join the section slack workspace, but I can't because I don't have an email address on the requested domains. Please, I need an invite from you.

Thank you.
@hectorkambow @LinusMuema @WanjaMIKE

**Comment by srishilesh** [comment]
@Bamimore-Tomi 

I've sent an invite for joining the Slack workspace.

Let me know if you're still unable to join.

**Pull request merged**
