### PR TITLE
Automating Excel Sheet in Python

### LINKED ISSUE #6991: [Language]Automating Excel Sheet in Python
### Topic Suggestion
Automating Excel Sheet in Python 

#### Proposed article introduction
Data Analysis forms a crucial part of gaining valuable insights from your customers. Multiple organizations are trying innovative ways to simplify the process of Data Analysis. Some are trying to completely automate this process whereas others are using multiple tools to set up the same. Another innovative technique used by companies to perform Data Analysis is linking their data source with a programming language and having it automate their Data Analysis.
Python Excel Automation is an innovative process that one can use to create visual reports on Python just the same way as you would on Excel seamlessly. Organizations can leverage Python Excel Automation to leverage their business tasks according to their needs.

#### Key takeaways 
By the end of the article, the readers will have:
- Analyze the Excel Dataset
- Create a Pivot Tables using Pandas
- Design the Reports using Openpyxl
- Automate the Report with Python
- Schedule the Python Script
#### Article quality
This article will give the learner a step-by-step guide on setting up Python Excel Automation. It will also give the learner an overview of both Python and MS Excel along with their features. 

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by taves-hub**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6991

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see [attached PDF](https://github.com/section-engineering-education/engineering-education/files/8358212/automating-excel-sheet-in-python.Copyleaks.Report.pdf) - and revisit the article to ensure we are contributing wholly unique and original content.

Your article is 44% similar to [this one](https://hevodata.com/learn/python-excel-automation/) on the same subject. I am closing this article now and you should rework your article in full in order to be unique. Perhaps use a real-life practical example?

**Comment by taves-hub** [comment]
@louisefindlay23 Hello sir, I have worked on the areas that raised flag also i  have implemented  real life examples to make it more understandable. Can you reopen such that I may push the changes. Thank You

cc
@Dawe-7

**Comment by taves-hub** [comment]
@Dawe-7 Good Evening sir, I have incorporated the changes and implemented real life examples as requested. Can you have a look at it. Thank you.

**Comment by Dawe-7** [comment]
> @Dawe-7 Good Evening sir, I have incorporated the changes and implemented real life examples as requested. Can you have a look at it. Thank you.

@taves-hub, upon a quick read, i could notice some readability issues even in your introductory section. There are a few incomplete sentences and very long sentences. Before we officially begin the review, kindly proofread your article for any errors that may pop-up when reviewing.

**Comment by taves-hub** [comment]
@Dawe-7 working on it

**Comment by taves-hub** [comment]
@Dawe-7  I have made some changes to enhance readability and grammar fix. Have a look, thank you .

**Comment by taves-hub** [comment]
@Dawe-7  I have made some changes to enhance readability and grammar fix. Have a look, thank you .

**Review by Dawe-7 — APPROVED** [review]
Nice article @taves-hub  Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles.

This article will be ready for final review after a plagiarism check is run.

**Comment by taves-hub** [comment]
@Dawe-7 noted thank you sir

**Comment by WanjaMIKE** [comment]
Plagiarism check is done. Could you check the highlighted sentences in the attached report
[New Scan 9_00 AM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/8450356/New.Scan.9_00.AM.Copyleaks.Report.pdf)

**Comment by taves-hub** [comment]
@Dawe-7 hello sir, I have fixed the sentences that raised flags as suggested by @WanjaMIKE . There are some libraries that raised flag and cannot be over written therefore no change.  Thank you

**Review by Dawe-7 — APPROVED** [review]
@taves-hub. Kindly ensure you go through the changes made throughout the review process. This article is ready for final review.

**Comment by Dawe-7** [comment]
@section-engineering-education/content-moderator-team, can we kindly have a final review of this PR.

**Comment by hectorkambow** [comment]
Noted: just going through the queue in order - we will get to this one asap.!

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
