### PR TITLE
Creating a Hand Tracking Module using Python, OpenCv, and MediaPipe

### LINKED ISSUE #6095: [Languages] Creating A Hand Tracking Module Using Python, OpenCv And MediaPipe
### Topic Suggestion
Creating a hand tracking module using python, OpenCv and MediaPipe

### Writing sample(s): 
[Sample](https://www.section.io/engineering-education/license-plate-detection-and-recognition-using-opencv-and-pytesseract/)
#### Proposed title of article
Creating a hand tracking module using python, OpenCV and MediaPipe

#### Proposed article introduction
When creating projects that involve hand tracking we tend to write the same piece of code over and over again. This not only costs us time but also leads to boredom as we are repeating the same task for every project. We can solve this problem by writing the piece of code once and then converting it into a module. This way we can always call the module to the project we are working on to do the hand tracking.

In this tutorial, we are going to learn how to come up with a code that does hand tracking. We will then learn how to convert the code into a module that we can call whenever we require it to track hands in any project we are working on.

#### Key takeaways 
The reader will:

1. Learn how to create a program that performs hand tracking.
2. Learn how to convert the code into a module that he/she can call to track hands in any project.
3. Understand how OpenCV and MediaPipe libraries are used to create the hand tracking program.

#### Article quality
The article will show the reader each step involved from coming up with the source code to creating a module out of it. The codes will also be well explained not copy-pasted ones. 

#### References
N/A

### PR DESCRIPTION
**Pull request by kirurisimon**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #6095

### CODE REVIEW

**Comment by kirurisimon** [comment]
@Dawe-7 submitted a PR

**Comment by srishilesh** [comment]
Hello @kirurisimon ,

Thanks for submitting this PR.

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started.

Meanwhile, we suggest you to go through existing approved PRs/published articles to see if you have missed out anything.

Thanks.

**Comment by louisefindlay23** [comment]
Plagiarism check complete

**Review by Dawe-7 — COMMENTED** [review]
Nice tutorial @kirurisimon, before we get it for final review,  there are two images which are too large. Kindly resize your `installation.png` and `model.png`. Use the [Pixlr Image Editor](https://pixlr.com/e) to resize the images.

https://pixlr.com/e/

**Comment by kirurisimon** [comment]
@Dawe-7 
Am done with the requested changes.

**Review by Dawe-7 — APPROVED** [review]
Awesome Job on the article @kirurisimon . Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles. Thank you.

**Pull request merged**
