### PR TITLE
Neumorphism vs Glassmorphism and Their Implementation Using CSS and HTML

### LINKED ISSUE #5520: [LANGUAGES] Neumorphism Vs. Glassmorphism and Their Implementation Using CSS and HTML
### Topic Suggestion
Neumorphism Vs. Glassmorphism and Their Implementation Using CSS and HTML

### Writing sample(s): 

- [How to Add Pure CSS Waves to Your Website](https://www.section.io/engineering-education/pure-css-wave-animations-website/)

#### Proposed article introduction
An interactive and captivating user interface design has the capability of ensuring that a user remains intrigued and fulfilled by a webpage when implemented correctly. There are numerous ways developers can ensure that their user interface design makes their creations stand out from the rest. In this article, we are going to explore how using neomorphism, and glassmorphism can change the look and feel of your next webpage.

#### Key takeaways 

By reading this article, you will get to learn about:
-The two UI design strategies 
-The importance of an intriguing and captivating user interface design.
-How the two design strategies will improve your web user interface.
-The various points of your page that each design strategy fits appropriately. 
-How to implement the two design patterns to a login page with ease using CSS and HTML.

#### Article quality
This article features a detailed discussion on how the two design patterns compare and contrast. The article includes suggestions on the various application areas of each design pattern and places extra emphasis on the login page of a website.

#### References
N/A

### PR DESCRIPTION
**Pull request by lin-chez**
#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [X] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #5520

### CODE REVIEW

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by lin-chez** [comment]
@WanjaMIKE Could you kindly perform a plagiarism check on this PR and assing it a reviewer.Thanks.😊

**Comment by john-amiscaray** [comment]
@lin-chez Hello there! Upon doing a quick skim through your article, while I did enjoy what I saw so far, after a quick Google search, I believe that the proper spelling of `neomorphism` is actually `neumorphism` (a u between the e and the m instead of an o as you did). Please fix the spelling of it throughout your article and in the folder name before I continue with my review.

**Comment by lin-chez** [comment]
@john-amiscaray I will have to close this PR and open a new one. I have noticed there has been an issue with the number of files changed of the PR. Please be patient as I make the needed changes.

**Pull request closed without merging**
