### PR TITLE
Understanding mobile databases in networking

### LINKED ISSUE #4998: Understanding Mobile Databases in Networking
#### Proposed title of article
Understanding mobile databases in networking

#### Proposed article introduction
Mobile database is one which is connected to a computer device over a wireless mobile network.
A mobile database is managed by a Database Management System (DBMS)
Mobile database:
- Handle local queries without connectivity
- It is resided on mobile devices
- Physically separate from the central database server
- Capable of communicating with a central database server or other mobile clients from remote sites
In this topic we are going to cover:
- Types of mobile databases
- Characteristics of mobile environments
- Transaction Management in Mobile Database Systems
- Advantages of mobile databases 
- Disadvantages of mobile databases 
- Requirements of mobile databases 
- Mobile Database Recovery

#### Key takeaways 
The reader should be able how different mobiles communicate even in different locations
The reader should understand how mobile databases function

#### Prerequisites
The reader should have basic knowledge on how databases work and mobile computing.

#### Article quality
Unlike other articles, this article will focus on mobile databases in general.

### PR DESCRIPTION
**Pull request by Muthoni-Irungu**
This fixes #4998

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
👋 Good afternoon - and welcome to the EngEd program. @Muthoni-Irungu 
There appear to be many sentences in this article that are taken verbatim from a third-party source. And I think this article is light on substance - I'm going to close it. 
cc @BrianaNzivu 

[Understanding mobile databases in networking#5034](https://github.com/section-engineering-education/engineering-education/files/7553844/New.Scan.10_29.AM.Copyleaks.Report.pdf)
s.

**Comment by Muthoni-Irungu** [comment]
hello @ahmadmardeni1 Can my PR be opened so that I make the necessary changes?

**Comment by BrianaNzivu** [comment]
Hi ahead @Muthoni-Irungu

Cc @ahmadmardeni1

**Comment by Muthoni-Irungu** [comment]
hello @BrianaNzivu I made the necessary changes
cc @ahmedmardeni1

**Comment by hectorkambow** [comment]
[UNDERSTANDING MOBILE DATABASES IN NETWORKING.pdf](https://github.com/section-engineering-education/engineering-education/files/7652587/UNDERSTANDING.MOBILE.DATABASES.IN.NETWORKING.pdf)


👋 Good afternoon - and welcome to the EngEd program.
There appear to be many sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).
We're really looking for unique/original content

**Comment by Muthoni-Irungu** [comment]
hello @hectorkambow can you please open my article I checked the plagiarism and fixed it

**Comment by Muthoni-Irungu** [comment]
@BrianaNzivu all done,,can you check please and tell me what I need to rectify

**Comment by Kayere** [comment]
Plagiarism check done

**Comment by Muthoni-Irungu** [comment]
@BrianaNzivu how is the progress?

**Comment by BrianaNzivu** [comment]
> @BrianaNzivu how is the progress?

Working on it ASAP.
I was waiting for the plagarism check to be done.

**Comment by Muthoni-Irungu** [comment]
Okay

**Review by BrianaNzivu — APPROVED** [review]
Hey @Muthoni-Irungu  👋 .
First, apologies for the delayed review.
Great job on the article! I am noticing a lot of improvement in your writing.
Just a final comment: 
- You can use tools such as [Quetext](https://www.quetext.com/) which is free, to check for plagiarism in your article. Also, you can use [Quilbot](https://quillbot.com/) which can help you paraphrase some plagiarized statements.
- Please go through all the changes I have made to avoid repeating the same mistakes in your future articles.

That's it! :smile: 

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

p.s I love the improvement, keep it up.

**Comment by Muthoni-Irungu** [comment]
Thank you,,

**Comment by hectorkambow** [comment]
> @BrianaNzivu all done,,can you check please and tell me what I need to rectify

@Muthoni-Irungu we believe there may be a miscommunication going on - our reviewer team do not provide revisions services. 

Any article that comes in should be polished (error free) and ready to publish. 

Our team only provides a review to ensure for accuracies. Thank you

**Comment by Muthoni-Irungu** [comment]
@hectorkambow but the final review hasn't be done.,,

**Comment by hectorkambow** [comment]
> @hectorkambow but the final review hasn't be done.,,

@Muthoni-Irungu Understood - what we are referring to is the amount of revisions (and review time) the PR required 

Review does not equal revisions. The final review is done to make sure the article renders well on the website not to fix any mistakes. 

👍 

>In an effort to be fair to our larger EngEd community as a rule of thumb - we can only accept content (pull requests) that are complete and fully polished articles/tutorial - meaning they are ready to be published.

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by Muthoni-Irungu** [comment]
Does this mean my article can't be published?

**Comment by hectorkambow** [comment]
Im in the process of doing a final review on it now - since it has been worked on 👍 (to see if it is ready to be published).

That is more general FYI (moving forward) yet if this PR still needs more edits - I will be closing it 🚀

**Pull request merged**
