### PR TITLE
Getting Started with Hierarchical Clustering in Python

### LINKED ISSUE #4945: Getting Started with Hierarchical Clustering in Python
#### Proposed article introduction
Hierarchical clustering is an unsupervised learning algorithm. This algorithm is used in clustering datasets with similar properties. Hierarchical clustering inherits its name from the word hierarchy, which simply means ranking or arranging things in order of their importance. This is what hierarchical clustering does. It identifies clusters in the dataset.

 There are two types of hierarchical clustering:
- **Agglomerative clustering:** Also known as *AGNES* (Agglomerative Nesting), this clustering works on the assumption that each data point in the dataset is an independent cluster of its own. So, in the beginning, each data point is considered as a single-element cluster (leaf). From this, it tries to reduce the number of clusters at each stage by merging the two most similar clusters into a new cluster. This process iterates until we obtain one big cluster(root) whose elements are clusters of other clusters. *AGNES* is a bottom-up clustering approach. In python, we will visualize the structure of this clustering using a famous plot known as *dendrogram*. Another thing we shall precisely talk of is how the two points are chosen as the best two for merging and not other points. There is a lot of mathematics that goes on for the algorithm to find similar points. We shall talk of that in our intuition part of this article.

- **Divisive hierarchical clustering:** Also known as DIANA (Divise Analysis), this clustering approach works in a top-down manner. In other words, we can say this algorithm is an inverse order of AGNES. It begins with the root, in which all objects are included as a single cluster. At each step of the iteration, the most heterogeneous cluster is divided into two. Then, the process is iterated until all objects are in their cluster or obtain the optimal number of clusters.

In the real world, the initial assumption of DIANA that the data is homogeneous holds less weight than the initial assumption of the *AGNES* that all data points are different from each other. So in this article, we shall give more weight to Agglomerative clustering too.

The primary focus on Agglomerative clustering will be on:
- How it carries its calculations.
- Important parameters we pass in its method when implementing in python. This will lead us to a discussion of what's Linkage and its different types. 
- We shall also talk about when we should stop the clustering process.
- We shall talk of when hierarchical clustering is the best approach to clustering and when it's not.
- Finally, we shall learn how to implement this algorithm in python using the scikit learn library.

#### Key takeaways 
 - By the end of the tutorial, the learner will know:
 - How hierarchical algorithm is all about.
 - How it works
 - The calculations associated with Agglomerative clustering
 - The important parameters we need to pass in its method when implementing in python.
 - When they should stop the clustering process.
 - When to apply hierarchical clustering to the given clustering problem and when not to.
 - How to implement this algorithm in python using the scikit learn library.
 
#### Article quality
This article will focus on the clarity of the intuition content and well explained coding session. It will ensure that the beginner can read the material comfortably and benefit from a high level of understanding of the algorithm's theory and implementation.

### PR DESCRIPTION
**Pull request by DennisKimt**
This closes #4945

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
👋 Good afternoon - and welcome to the EngEd program. @DennisKimt 
There appear to be many sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).
We're really looking for unique/original content.

I'm going to close this PR and give you some time to work on it. 
cc @paulodhiambo 

[Getting Started with Hierarchical Clustering in Python#5075](https://github.com/section-engineering-education/engineering-education/files/7568704/New.Scan.8_00.AM.Copyleaks.Report.2.pdf)

**Comment by paulodhiambo** [comment]
@DennisKimt move the images to the right directory.

**Comment by hectorkambow** [comment]
@paulodhiambo 

If any other revisions are needed on this PR - we will be closing it to allow the author to make those changes (out side the queue).

This PR has been closed for 20+ days and the author should have proofread everything accordingly. 

cc @lalith1403  

cc @section-engineering-education/content-moderator-team

**Comment by lalith1403** [comment]
plagiarism check done ✔️

**Comment by Kayere** [comment]
Congratulations on publishing your first article @DennisKimt. It is a nice read. We hope it is the first of many great articles. Keep up the good work!

Thank you for the review @paulodhiambo - please don't forget to add the `<!--more-->` excerpt_separator in your next reviews👍🏾.

**Pull request merged**
