### PR TITLE
Feature #6363: Trying through forked repo

### PR DESCRIPTION
**Pull request by lalith1403**

### CODE REVIEW

**Comment by lalith1403** [comment]
@section-engineering-education/content-moderator-team @hborrelli1 Can you check this?

**Comment by lalith1403** [comment]
Most probably need to add this app to our repo. https://probot.github.io/apps/auto-comment/

**Comment by hborrelli1** [comment]
@lalith1403 not sure that we should use this as it doesn't seem like the creator is maintaining this project anymore. I saw that in the [Issues Tab](https://github.com/boyney123/auto-comment/issues) he mentions he is not maintaining this anymore. And other people are saying its broken as well. So I'm going to remove this app from the repository. 

Maybe we should keep looking for other solutions.

**Comment by lalith1403** [comment]
@hborrelli1 Definitely. Thank you for pointing that out 👍

**Pull request closed without merging**
