### PR TITLE
Semaphore in Java

### LINKED ISSUE #4787: [language] Semaphore in Java
#### Proposed title of article
Semaphore in Java

#### Proposed article introduction
Java's semaphore clock. A counter on a semaphore restricts access to a shared resource. Access is granted if the counter is higher than zero. Zero indicates that access has been denied. Permits that allow access to the shared resource are being counted by the counter. As a result, a thread needs a semaphore permit in order to access the resource in question.
An attempt is made to obtain permission from the resource owner to utilize a semaphore.
Semaphores with counts bigger than zero have a permit to decrement their count, and so do threads with counts greater than zero. In the absence of a permit, the thread will be suspended. The count of the semaphore is incremented when a thread releases a permit to use a shared resource. It is possible that another thread is waiting for a permit at the same time as this one.

#### Key takeaways 
- Working of semaphore in Java
- Constructors in Semaphore class 
- Using Semaphores as Locks

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

#### Article quality
Other blogs don't go into great length on a semaphore in Java, but they do cover the fundamentals of the concept. It will be covered in great length in this article how semaphores work, how constructors in the Semaphore class work, and how semaphores can be used to lock and unlock objects. As a result, because of their simplicity, code snippets and content descriptions will be understandable to novices, intermediates, and professionals alike.

### PR DESCRIPTION
**Pull request by MarkMoki**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?
This fixes #4787

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
👋 Good afternoon - and welcome to the EngEd program. @MarkMoki 
There appear to be many sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).
We're really looking for unique/original content.

I'm going to close this PR and give you some time to work on it. 
cc @BrianaNzivu 


[Semaphore in Java#5076](https://github.com/section-engineering-education/engineering-education/files/7568718/New.Scan.8_01.AM.Copyleaks.Report.pdf)

**Comment by MarkMoki** [comment]
@ahmadmardeni1 Hello
How is You
I am ready to revice. Please Reopen My PR.

**Comment by MarkMoki** [comment]
@ahmadmardeni1 @BrianaNzivu
Hello
I have the changes with me. Please open so I can commit them. Thanks.

**Comment by BrianaNzivu** [comment]
There you go @MarkMoki

Cc @ahmadmardeni1

**Comment by MarkMoki** [comment]
@ahmadmardeni1 Done

**Comment by louisefindlay23** [comment]
Plagiarism check complete

**Comment by MarkMoki** [comment]
@BrianaNzivu could you give it a review. Thanks.

**Comment by hectorkambow** [comment]
@section-engineering-education/peer-reviewers is anyone available to review this article?

**Comment by BrianaNzivu** [comment]
> @section-engineering-education/peer-reviewers is anyone available to review this article?

On it.

**Review by BrianaNzivu — APPROVED** [review]
Hey @MarkMoki  👋 .
I would love to sincerely apologize for the delayed review of your article.
The article is a very interesting read. Good job!
Just a few things I'd like to point out:
1.  It is always advisable to submit an article that is well polished. By this, I mean having an article that does not have too many grammatical corrections and functional code.  Your article was quite unclear before the changes I made. I suggest that you check out our [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) page which has links to various resourceful tools for writing. 
2. I'd like to recommend taking Google's technical writing [course](https://developers.google.com/tech-writing) which is absolutely free and can come in handy.
3. Lastly please go through all the corrections I have made so that you can not repeat the same mistakes.

That's it! :smile: 

A final review will be done now by a content moderator.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

**Comment by MarkMoki** [comment]
@BrianaNzivu The article talks about the implementation of semaphores. Is it not a tutorial?

**Comment by MarkMoki** [comment]
> Hey @MarkMoki 👋 . I would love to sincerely apologize for the delayed review of your article. The article is a very interesting read. Good job! Just a few things I'd like to point out:
> 
> 1. It is always advisable to submit an article that is well polished. By this, I mean having an article that does not have too many grammatical corrections and functional code.  Your article was quite unclear before the changes I made. I suggest that you check out our [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) page which has links to various resourceful tools for writing.
> 2. I'd like to recommend taking Google's technical writing [course](https://developers.google.com/tech-writing) which is absolutely free and can come in handy.
> 3. Lastly please go through all the corrections I have made so that you can not repeat the same mistakes.
> 
> That's it! 😄
> 
> A final review will be done now by a content moderator.
> 
> In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email ([briananzivu@gmail.com](mailto:briananzivu@gmail.com)). I am **ALWAYS** here to help.
> 
> It has been a pleasure reading and reviewing this article.
> 
> Looking forward to seeing you contribute more to EngEd. 🚀
> 
> Kind Regards.

Thanks

**Comment by hectorkambow** [comment]
@MarkMoki 

Thank you for the topic suggestion. It seems that information that you covered is already readily available through the [documentation and other blog sites](https://www.google.com/search?q=Semaphore+in+Java&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8).

Yet we're really looking for original content, and based on the description that you've provided. We're really looking for unique/original content that will add value to both the EngEd community and the overall developer community.

**Comment by MarkMoki** [comment]
Can you please reopen so that I can add more data.

**Comment by MarkMoki** [comment]
@BrianaNzivu should I open a new PR?

**Comment by ahmadmardeni1** [comment]
Good afternoon @MarkMoki 
You can't open a new PR. This content is widely available and well covered. Please feel free to suggest a new unique topic to explore. 
cc @BrianaNzivu

**Pull request closed without merging**
