### PR TITLE
How to integrate PHP emails using Mailtrap

### LINKED ISSUE #3620: How to integrate PHP emails using Mailtrap
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
How to integrate PHP emails using Mailtrap

### Introduction paragraph (2-3 paragraphs):
Sending email messages are very common for a web application, for example, sending welcome email when a user create an account on your website, sending newsletters to your registered users, or getting user feedback or comment through website's contact form, and so on.

You can use the PHP built-in mail() function for creating and sending email messages to one or more recipients dynamically from your PHP application either in a plain-text form or formatted HTML.
In this tutorial, I will show how to send these emails and show them on the mailtrap.
### Key takeaways: 
1.Sending Plain Text Emails
2.Sending HTML Formatted Emails
3.PHP built-in mail function ()
4.Simple Transmission Protocol (SMTP)
5.PHP mailing packages
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by owinowendy**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #3620

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by owinowendy** [comment]
@jumamiller @simonmwaniki, @hectorkambow : I have created this article to help us solve the issue with the previous article #3979.

@jumamiller, kindly review. Thank you!

**Comment by jumamiller** [comment]
Added the article update to ensure we don't forget to compensate @simonmwaniki accordingly.

cc @hectorkambow @simonmwaniki

**Comment by jumamiller** [comment]
> Added the article update to ensure we don't forget to compensate @simonmwaniki accordingly.
> 
> cc @hectorkambow @simonmwaniki

I've also added the front-matter to include Simon's name : `simon-mwaniki`.

**Review by jumamiller — APPROVED** [review]
@owinowendy, this is a great article! Very easy to follow.

**Comment by jumamiller** [comment]
> @owinowendy, this is a great article! Very easy to follow.

ALERT: This is a special article that should be attended to by @hectorkambow!

Thank you team!

**Comment by hectorkambow** [comment]
> Added the article update to ensure we don't forget to compensate @simonmwaniki accordingly.
> 
> cc @hectorkambow @simonmwaniki

Not following? The article update label is used when an author is making an update to an existing (already published) article. 

Is that what this is? @jumamiller

**Comment by hectorkambow** [comment]
> > @owinowendy, this is a great article! Very easy to follow.
> 
> ALERT: This is a special article that should be attended to by @hectorkambow!
> 
> Thank you team!

Not following @jumamiller

**Comment by jumamiller** [comment]
> > > @owinowendy, this is a great article! Very easy to follow.
> > 
> > 
> > ALERT: This is a special article that should be attended to by @hectorkambow!
> > Thank you team!
> 
> Not following @jumamiller

Hi, I sent you a message on Slack!

**Comment by hectorkambow** [comment]
@jumamiller  

Just wanted to remind you that we need to run a plagiarism check as well. (dont forget the labels) 👍 

I'll run that as well - just wanted to add the reminder.

**Comment by Kayere** [comment]
Hello @owinowendy,

 Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[How to integrate PHP emails using Mailtrap #5404 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7692889/How.to.integrate.PHP.emails.using.Mailtrap.5404.Copyleaks.Report.pdf)

**Comment by louisefindlay23** [comment]
@Kayere, does this still need work to improve the plagiarism score? If so, please remove the ready for final review label.

**Comment by owinowendy** [comment]
@jumamiller @louisefindlay23  plagariasm issue fixed!

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
