### PR TITLE
Designing an Authentication API using Service Classes in Flutter

### LINKED ISSUE #3469: Designing an Authentication API using Service Classes in Flutter
### Proposed title of article
Designing an Authentication API using Service Classes in Flutter

### Introduction paragraph (2-3 paragraphs):
Service classes are a great way to keep the implementation details of third-party code out of your program. They come in handy when you need to invoke an API function from numerous locations in your code.

We'll look at how to use service classes to encapsulate and separate 3rd-party libraries and APIs from the rest of the application in this post. We'll look at authentication as a specific example.

### Key takeaways: 
-What is a service class?
-How can we use FirebaseAuth to build a generic authentication service?
-How can we update our top-level widget to use the new service class?

### References: 
N/A

### PR DESCRIPTION
**Pull request by vincentkims49**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #3469 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your article for publishing. @vincentkims49 
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. :rocket:
Thank you.

**Comment by vincentkims49** [comment]
@ahmadmardeni1 , @WanjaMIKE , @hectorkambow 
Hopefully this article hasn't been left out.

**Comment by ahmadmardeni1** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Designing an Authentication API using Service Classes in Flutter](https://github.com/section-engineering-education/engineering-education/files/7111456/New.Scan.11_01.AM.Copyleaks.Report.1.pdf)

**Comment by vincentkims49** [comment]
Done @ahmadmardeni1

**Comment by vincentkims49** [comment]
@ahmadmardeni1 
I have corrected the plagiarisms. Some content is slightly changed since I'm focusing on giving the required or the appropriate information concerning the topic. 
Thanks.

**Comment by hectorkambow** [comment]
@vincentkims49 

This article seems a bit light on substance 

cc @ahmadmardeni1 @jerimkaura

**Comment by vincentkims49** [comment]
@hectorkambow I'll add some more information if necessary.

**Comment by vincentkims49** [comment]
@hectorkambow @ahmadmardeni1 @jerimkaura 
I have done some corrections and added more information to the article. You may have a look please.

**Comment by jerimkaura** [comment]
> @hectorkambow @ahmadmardeni1 @jerimkaura
> I have done some corrections and added more information to the article. You may have a look please.

@ahmadmardeni1 , @hectorkambow

**Comment by hectorkambow** [comment]
@jerimkaura  Have you reviewed the new changes? What is the status of this PR - is it ready for a final review?

**Comment by jerimkaura** [comment]
Will do the new changes soon. I was held up with exams

**Comment by jerimkaura** [comment]
Hello @vincentkims49, Seems like you did not add much information apart from renaming a few variables. Consider adding more value to the article and making it understandable to beginners. How about something like a real flutter application demonstrating the concept.

cc: @hectorkambow , @ahmadmardeni1

**Comment by vincentkims49** [comment]
> Hello @vincentkims49, Seems like you did not add much information apart from renaming a few variables. Consider adding more value to the article and making it understandable to beginners. How about something like a real flutter application demonstrating the concept.
> 
> cc: @hectorkambow , @ahmadmardeni1

Sure I will add, @jerimkaura

**Comment by vincentkims49** [comment]
> Hello @vincentkims49, Seems like you did not add much information apart from renaming a few variables. Consider adding more value to the article and making it understandable to beginners. How about something like a real flutter application demonstrating the concept.
> 
> cc: @hectorkambow , @ahmadmardeni1

I have added some more information. All the dart code that I had provided earlier consists of all the steps of designing an authentication API using the service classes. The information added was to ensure that the reader understands in more detail what the steps in the tutorial are all about and to gain some more outside the scope area the tutorial is about.
Thank you.

**Comment by vincentkims49** [comment]
> > Hello @vincentkims49, Seems like you did not add much information apart from renaming a few variables. Consider adding more value to the article and making it understandable to beginners. How about something like a real flutter application demonstrating the concept.
> > cc: @hectorkambow , @ahmadmardeni1
> 
> I have added some more information. All the dart code that I had provided earlier consists of all the steps of designing an authentication API using the service classes. The information added was to ensure that the reader understands in more detail what the steps in the tutorial are all about and to gain some more outside the scope area the tutorial is about.
> Thank you.

@jerimkaura

**Review by jerimkaura — APPROVED** [review]
@vincentkims49 

Thank you for the additional information. It looks clear now.

Let's wait for the final review.

Thank you!

**Comment by vincentkims49** [comment]
@ahmadmardeni1 
I have done some few changes you may look at my last commit, Thank you

**Comment by ahmadmardeni1** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Designing an Authentication API using Service Classes in Flutter](https://github.com/section-engineering-education/engineering-education/files/7169495/New.Scan.10_48.AM.Copyleaks.Report.pdf)

**Comment by vincentkims49** [comment]
@ahmadmardeni1 @Kayere 
Done with the flags.
Please confirm this. Thank you.

**Comment by jerimkaura** [comment]
@ahmadmardeni1  would you please do a plagiarism check on this once more?

**Comment by ahmadmardeni1** [comment]
This is the fourth plagiarism check, and the % is still high.

👋 Thank you for contributing your 1st article - and Welcome to the EngEd Program. @vincentkims49 
Many sentences in this article are taken verbatim from [this article](https://codewithandrea.com/articles/designing-an-authentication-service-api/).

Due to this, we will be closing this PR. 
There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).

Feel free to explore another topic when ready - We encourage you to submit a more in-depth topic or one that builds upon what we already have. 👍
cc @jerimkaura

**Pull request closed without merging**
