### PR TITLE
Making cURL requests in Node.js

### LINKED ISSUE #2266: Making cURL requests in Node.js
### Proposed title of article
Making cURL requests in Node.js

### Introduction paragraph (2-3 paragraphs):

cURL(client URL) is a free tool used to make network requests from the command-line or terminal using various protocols available. It's very useful when one wants an application to make a request without necessarily engaging a user e.g checking and validating the access token for using an API. For backend developers like me, it may come in handy when we want to send form data to test our APIs without designing a user interface for a form.

Other than the command-line, we can use cURL and display responses gotten from the requests on a webpage. In this article, we are going to look at using cURL in Node.js using the **node-libcurl** library. 

### Key takeaways: 

At the end, the reader will get to know about:
1. cURL requests
2. The uses and advantages of cURL
3. Using the **node-libcurl** library for making cURL requests in Node.js

### References: 

[node-libcurl documentation](https://www.npmjs.com/package/node-libcurl)
[PairBlog](https://blog.pair.com/2018/01/26/curl-description-basic-use-cases/#:~:text=cURL%2C%20often%20just%20%E2%80%9Ccurl%2C,data%20to%20and%20from%20servers.&text=You%20can%20also%20do%20simple,that%20will%20get%20you%20started.)

### PR DESCRIPTION
**Pull request by vinstex**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com)
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2266

### CODE REVIEW

**Comment by kayere** [comment]
Hello @vinstex, welcome to sections engineering education program. I'll be reviewing your article. It looks like an interesting topic.
Could you please add your author details before we continue.

**Comment by vinstex** [comment]
@kayere. Added the profile details.

**Review by kayere — APPROVED** [review]
Great article @vinstex, please go over the changes I made to help improve the quality and format of your future articles. Otherwise, the article is now ready for final review.

**Comment by hectorkambow** [comment]
plagiarism check done

**Review by louisefindlay23 — APPROVED** [review]
Final review complete. Congrats on publishing your first article, @vinstex. Thanks for peer reviewing, @kayere.

**Comment by hectorkambow** [comment]
@kayere Dont forget to add your PRL (peer review line) to get credit. 
👍 I'll take care of it this time.

**Comment by kayere** [comment]
Oow, Thanks @hectorkambow. I'll be keen next time.👍

**Pull request merged**
