### PR TITLE
Write Excel in Python

### LINKED ISSUE #4191: [Languages] Write Excel using Python
#### Proposed title of article
Write Excel using Python

#### Proposed article introduction
One of the most intuitive and user-friendly ways to manipulate large datasets is using spreadsheets. 
There are a lot of spreadsheet packages available today. However, when it comes to analyzing datasets, Excel takes the lead as the most preferred spreadsheet package.

In the article, we shall learn the basics of integrating Excel with Python.  Our most significant concern will be to understand:
1. Getting Started With openpyxl and xlsxwriter.
2. Create, read and load existing workbooks.
3. Add and delete worksheets
4. Basic excel operations
5. How to visualize your dataset.

#### Key takeaways 
1. Learner will learn all about openpyxl and xlsxwriter.
2. Learner will understand how to create, read, and write Excel files using these libraries. 
3. Learners will learn how to manipulate the dataset and will have fun while doing it.

#### Article quality
With these libraries, I'd go beyond simply writing and reading Excel files. I'd go into data cleansing and visualization in further detail.

#### References
- [geeksforgeeks](https://www.geeksforgeeks.org/reading-excel-file-using-python/)

### Conclusion
N/A

### PR DESCRIPTION
**Pull request by Bennykillua**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #4191`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

This fixes #4191

### CODE REVIEW

**Comment by Bennykillua** [comment]
Hi @srishilesh 

Thanks.  I just added the Author info along with a headshot image under /content/authors directory.

**Comment by Kayere** [comment]
Plagiarism check done ✔️

**Review by srishilesh — APPROVED** [review]
@Bennykillua 

Great article. It was very beginner friendly.

And, just wanted to appreciate, as a first time contributor at EngEd you've followed all the guidelines as mentioned. Keep up the good work!

Make sure to go through minor edits made by me, to further improve on your future articles.

Moving for the final review.

Thanks.

**Comment by Bennykillua** [comment]
@srishilesh 

Thanks for the feedback and appreciation. I would through the minor edit made.

**Comment by hectorkambow** [comment]
@Bennykillua 
Thank you for your patience as our team has been working diligently to work through the recent increased volume of articles coming in. 

We are going through are ready articles in the order they were received and working on improving our review time as well. 

🚀

**Comment by Bennykillua** [comment]
> @Bennykillua Thank you for your patience as our team has been working diligently to work through the recent increased volume of articles coming in.
> 
> We are going through are ready articles in the order they were received and working on improving our review time as well.
> 
> 🚀

**Comment by lalith1403** [comment]
@section-engineering-education/content-moderator-team I will be reviewing this one 👍

**Review by lalith1403 — APPROVED** [review]

**Pull request merged**
