### PR TITLE
Understanding Duck Typing in Python

### LINKED ISSUE #5931: Understanding Duck Typing in Python
#### Proposed title of article
Understanding Duck Typing in Python

#### Proposed article introduction
Duck Typing is a Dynamic Typing notion in which an object's type or class is less essential than the method it defines. We don't check types at all when we use Duck Typing. Rather, we look for the existence of a specific function or trait.
The name comes from the duck test, which states, "If it looks like a duck, swims like a duck, and quack like a duck, then it probably is a duck”.
In this article we'll deeply discuss duck typing comparing it with other typing methods in different dynamic languages such as JavaScript and Ruby. we'll also appreciate its origin and advantages of having it in programming.

#### Key takeaways 
- Definition and general introduction to duck typing
- Benefits of having duck typing
- Comparison with Static and other dynamic typing methods
- Concept of calling functions and executing them 

#### Article quality
This article will provide an in-depth explanation of duck typing as well as incorporate a language easy to be understood by the reader. The reader will appreciate the fact that this tutorial shall provide practicable examples in calling and executing functions in duck typing therefore, making it beginner-friendly. The subject topic will also be compared with other different fields of programming to ensure reader will be oriented all round issue.

#### References
N/A

### PR DESCRIPTION
**Pull request by Simsamrosh**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #5931

### CODE REVIEW

**Comment by srishilesh** [comment]
Hello @Simsamrosh,

Welcome to EngEd! Thanks for submitting this PR.

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started with the review.

Meanwhile, we suggest you to go through approved PRs/published articles to see if you have missed out anything. This would help us avoid any potential closure of the PR.

Thanks.

**Comment by Simsamrosh** [comment]
Hello @lalith1403 kindly have a look at my PR. Thank you.

**Comment by lalith1403** [comment]
Hello @Simsamrosh, please check for basic spelling mistakes, especially in the code. Make sure to pull the changes I have made before you start making the requested changes.

**Comment by Simsamrosh** [comment]
Hello @lalith1403 I have done the requested change please check. Thanks

**Comment by Simsamrosh** [comment]
Any update on the PR @lalith1403

**Comment by lalith1403** [comment]
@Simsamrosh, sorry for the delay in the review. Due to personal reasons, I am getting to the review now.

**Review by lalith1403 — APPROVED** [review]

**Comment by WanjaMIKE** [comment]
Merged #6361 into master

**Pull request merged**
