### PR TITLE
Getting Started with Simplex Method in python

### LINKED ISSUE #5602: Getting Started with Simplex Optimization Algorithm in Machine Learning
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
Enter topic suggestion here...

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Getting Started with Simplex Optimization Algorithm in Machine Learning

Use keyword research to improve your article's SEO.

#### Proposed article introduction
The simplex method is one of the Convex Optimization machine learning methods and is used for solving a linear programming problem using the slack variable, the tableau, and a pivot variable as means to finding the optimal solution to an optimization problem.

To solve a linear programming model using the Simplex algorithm, We follow the following steps:
- Re-writing the problem into standard form
- Introducing slack variable
- Creating an initial simplex table
- Identifying the Entering variable(EV), i.e., the variable with the most negative value in the objective function.
Determine the pivot variable and apply the Gauss-Jordan elimination row-reduction to make the pivot value one and all the values below and above it zero.
- Create a new tableau
- Check for optimally
- Identify optimal values.
- Repeat the process until all Z values are non-negative that when the solution is optimal.

In this article, we shall break down the simplex method into the above steps and follow a real problem throughout our discussion to solve a linear programming problem. Later, we shall leverage a python library called scipy that contains an optimization function, and we shall implement the problem we shall have solved above and see if we really get the same answer. Again the trick is on how we present the matrices we fit the python function. We might miss the format and end up obtaining a totally wrong output. We shall learn the way we normally represent these matrices in this article.

#### Key takeaways 
By the end of the session the reader will have a good understanding of;
1. What is the Simplex algorithm
2. How to set up an optimization problem for Simplex method
2. How the Simplex algorithm work(all steps until we have a an optimal solution)
3. How Simplex algorithm is implemented in python
#### Article quality
As the real-world problems are only in the problem statement form and not set up for solving, this article will teach how to formulate the optimization problem from the problem statement so as to ensure we have the correct setup for the Simplex method. This might sound like an easy task, but trust me, formulating an optimization problem is not straightforward. For example, one might know all the steps for solving a Simplex method problem and not know how to formulate a correct optimization problem. Due to this, the learner ends up optimizing the wrong function, and as a result, the final answer is not reliable.

Many articles online teach how the simplex method works only using an already formulated problem. This is because it's easy to do so, but setting up an optimization problem from the problem statement is not a straightforward task. So they chose to leave it in the hands of the learners. When the learner comes across such an unstructured problem, it becomes highly challenging for them and even unable to present the problem in the desired manner to get started. What makes this article different is that the learner will be taught how to solve a simplex method and a clever way to formulate optimization functions from the problem statement so that they do not end up optimizing a wrong function. In this article, we are not going to optimize an already set up problem; instead, we shall set up the problem of our own so that the learner can know how to do so by themselves in future problems.
#### References
N/A

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Daniel695**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5602 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Review by jerimkaura — COMMENTED** [review]
Hello @Daniel695 

This is a very interesting topic. Cant wait to learn more during my review. :rocket: 

Proceeding to tech review.

**Comment by WanjaMIKE** [comment]
This paragraph seems to show plagiarism. Please correct it. Thanks

```
Manufacture of bicycles builds racing, touring, and models. The bicycles are made of both aluminum and steel. The company has available 91800 units of steel and 42000 of aluminum. The racing, touring, and mountain models need 17, 27, and 15 units of steel, and 12, 21, and 15 units of aluminum, respectively. How many of each type of bicycle should be made to maximize the profit if the company makes 8 dollars per racing bike, 12dollars per touring bike, and 22 dollars per mountain bike? What is the maximum possible profit?```

**Review by jerimkaura — APPROVED** [review]
Hello @Daniel695 :wave:

Thank you for your great article. I had fun with the review. Keep this up. However, take note of the corrections I made especially with the punctuations and contractions. Overall great work. Let us wait for the final review. Thanks, Dan!

**Comment by hectorkambow** [comment]
Jumping on this one 👍

**Comment by hectorkambow** [comment]
@jerimkaura  
Please be sure you are reviewing things throughly, found quite a few errors that slipped through. Various grammatical errors 🤔

**Comment by hectorkambow** [comment]
Also noticed this is missing a mathjax script to get the equations to render.

**Comment by hectorkambow** [comment]
@Daniel695 

Not sure if these tables should look like this 🤔 

image

**Pull request merged**
