### PR TITLE
Handling Web App authentication using Auth0, ASP.NET Core and Nuxt.js

### LINKED ISSUE #3556: Handling Web App authentication using Auth0, ASP.NET Core and Nuxt.js
### Proposed title of article
Handling Web App authentication using Auth0, ASP.NET Core and Nuxt.js

### Introduction paragraph:
Authenticating and authorizing users in a system can be difficult and time-consuming. If not done right it can also lead to serious security consequences such as malicious users accessing and stealing personal or sensitive information from the system.

Large organizations can implement complex authorization/authentication systems which tend to consume time and are expensive. However, businesses and developers can opt to go for cost-effective and minimize the development time by using existing solutions for secure authentication and authorization. In this tutorial, we will use Auth0 to authenticate the users into the system.

### Key takeaways: 
At the end of the guide, the learner will be able to:
- configure and use Auth0 to generate an access token for authentication
- configure ASP.NET Core to authenticate the request
- use Nuxt.js to implement the frontend of the app and handle routing

### References: 
N/A

### PR DESCRIPTION
**Pull request by ogoti-lilian**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #3556

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Kayere** [comment]
Plagiarism check done ✔️

**Comment by hectorkambow** [comment]
@katungi 

Is this PR a duplicate ? lets be sure to always add the proper label and past PR - so any reviewer is aware this is the authors second attempt at a PR. 

cc @ogoti-lilian 

@section-engineering-education/peer-reviewers 

cc @section-engineering-education/content-moderator-team

**Comment by hectorkambow** [comment]
@ogoti-lilian 
Thank you for your patience as our team has been working diligently to work through the recent increased volume of articles coming in. 

We are going through are ready articles in the order they were received and working on improving our review time as well. 

🚀

**Comment by ogoti-lilian** [comment]
> @ogoti-lilian Thank you for your patience as our team has been working diligently to work through the recent increased volume of articles coming in.
> 
> We are going through are ready articles in the order they were received and working on improving our review time as well.
> 
> 🚀

@hectorkambow Noted with Thanks

**Comment by ogoti-lilian** [comment]
@hectorkambow You can conduct the review on this one. 
Thank you

**Comment by LinusMuema** [comment]
lemme jump on this one

**Comment by LinusMuema** [comment]
Hi @ogoti-lilian 

thanks for the amazing article. Please take note of the changes during review for future articles.

cc: @katungi check image extenstions in articles. They should be small caps.

**Comment by ogoti-lilian** [comment]
> Hi @ogoti-lilian
> 
> thanks for the amazing article. Please take note of the changes during review for future articles.
> 
> cc: @katungi check image extenstions in articles. They should be small caps.

@LinusMuema The changes made have been noted. I will improve in future articles. Thank you.

**Pull request merged**
