### PR TITLE
Collections in C++

### LINKED ISSUE #4767: Collection in c++
**topic suggestion**
Collection in c++

**Introduction**
Collection in c++ is a framework that provides an architecture for you to store and manipulate data. In fact talk about containers. It is often used when storing or manipulating data during runtime. In this article, we will introduce collection and discuss using various examples of how we can manipulate data at runtime without having to specify storage or size.
Furthermore, we will use clear explanations to understand the Collection interface hierarchy. We will see how the sub-interfaces like list, queue, set, etc relate to each other.
Moreover, we will learn how to implement the collections sub-interfaces since we cannot implement collection itself. We will further discuss the classes of collection which some of include ArrayList, LinkedList, among others.

**Key Takeaways**
In the article, the user will get to learn:

1. Introduce Collections in c++
2. The Collection interface hierarchy
3. Relation of Collection sub interfaces
4. Implementation of interfaces
5. Classes of collection

**Reference**

N/A

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

### PR DESCRIPTION
**Pull request by tetie**
#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [X] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4767

### CODE REVIEW

**Comment by annkambua** [comment]
@jumamiller , kind this is a new pr,   a duplicate of #5862  you can continue with review.

 thanks.

**Comment by tetie** [comment]
@jumamiller , kindly this is a new pr duplicate of #5862  you can continue with review. 
Thanks

**Comment by jumamiller** [comment]
Hi, this is a duplicate and yet it has the very problems it initially had, for example, there are several files, which one should be reviewed?

**Comment by tetie** [comment]
> Hi, this is a duplicate and yet it has the very problems it initially had, for example, there are several files, which one should be reviewed?

@jumamiller I have removed the unnecessary files now you can proceed with the review, I will appreciate.

**Review by jumamiller — APPROVED** [review]

**Comment by hectorkambow** [comment]
NOTE: This is a 3rd or 4th duplicate.

**Comment by hectorkambow** [comment]
@jumamiller question? Are collections in C++ and C# similar or are they different enough that another article can be published? 

https://re.sajari.com/token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjoiY2xpY2siLCJkZXN0aW5hdGlvbiI6Imh0dHBzOi8vd3d3LnNlY3Rpb24uaW8vZW5naW5lZXJpbmctZWR1Y2F0aW9uL2Mtc2hhcnAtY29sbGVjdGlvbnMvIiwidmFscyI6eyJjb2xsZWN0aW9uIjpbInNlY3Rpb24taW8iXSwiY29tcGFueSI6WyIxNTY4MjM0MTE2MDc4NjE0ODY4Il0sImZpZWxkIjpbInVybCJdLCJwcm9qZWN0IjpbIjE1NjgyMzQxMTYwNzg2MTQ4NjgiXSwicS5pZCI6WyJmZHM3MXduaDNtcjczOXp2Il0sInEuc2wiOlsiMSJdLCJxLnVpZCI6WyJmZHM3MXduaDNtcjczOXp2MCJdLCJ2YWx1ZSI6WyJodHRwczovL3d3dy5zZWN0aW9uLmlvL2VuZ2luZWVyaW5nLWVkdWNhdGlvbi9jLXNoYXJwLWNvbGxlY3Rpb25zLyJdfX0.AVCPkzaTGwn9wC3JLy1UShoed3GqPaKzdkp6oLXPcyM

cc @tetie

**Comment by tetie** [comment]
> @jumamiller question? Are collections in C++ and C# similar or are they different enough that [another ](https://re.sajari.com/token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjoiY2xpY2siLCJkZXN0aW5hdGlvbiI6Imh0dHBzOi8vd3d3LnNlY3Rpb24uaW8vZW5naW5lZXJpbmctZWR1Y2F0aW9uL2Mtc2hhcnAtY29sbGVjdGlvbnMvIiwidmFscyI6eyJjb2xsZWN0aW9uIjpbInNlY3Rpb24taW8iXSwiY29tcGFueSI6WyIxNTY4MjM0MTE2MDc4NjE0ODY4Il0sImZpZWxkIjpbInVybCJdLCJwcm9qZWN0IjpbIjE1NjgyMzQxMTYwNzg2MTQ4NjgiXSwicS5pZCI6WyJmZHM3MXduaDNtcjczOXp2Il0sInEuc2wiOlsiMSJdLCJxLnVpZCI6WyJmZHM3MXduaDNtcjczOXp2MCJdLCJ2YWx1ZSI6WyJodHRwczovL3d3dy5zZWN0aW9uLmlvL2VuZ2luZWVyaW5nLWVkdWNhdGlvbi9jLXNoYXJwLWNvbGxlY3Rpb25zLyJdfX0.AVCPkzaTGwn9wC3JLy1UShoed3GqPaKzdkp6oLXPcyM)article can be published?
> 
> cc @tetie

Hi, @hectorkambow  , collections in c++ are different from those in c# though they may sound same,this is proved  right from the way they are implemented and the compilation so the article is worth to be published.
Thank you
>cc @jumamiller .

**Comment by hectorkambow** [comment]
image

@tetie

**Comment by tetie** [comment]
Hello, @hectorkambow  it seems there is still issues with the article, then what am i supposed to do to it

**Comment by jumamiller** [comment]
Hello @hectorkambow, the author file had the conflict, I have resolved it, you may try again. Thank you!

cc @tetie

**Comment by jumamiller** [comment]
> Hello, @hectorkambow it seems there is still issues with the article, then what am i supposed to do to it

You had conflicting author files!

**Comment by tetie** [comment]
conflict resolved 
cc @hectorkambow 
cc @jumamiller

**Comment by jumamiller** [comment]
Rename the author file to `index.md`. Why don't you read documentation to get it right once?

**Comment by jumamiller** [comment]
> Rename the author file to `index.md`. Why don't you read documentation to get it right once?

Any other revisions will lead to the PERMANENT closure of this PR and the linked issue.

**Comment by tetie** [comment]
@jumamiller its done

**Review by jumamiller — APPROVED** [review]

**Comment by Kayere** [comment]
Hi @tetie, please go through the changes made in my commit to help improve the quality of your future articles.

cc: @jumamiller.

**Pull request merged**
