### PR TITLE
[Duplicate] Creating User Authentication UI with Compose for Desktop

### LINKED ISSUE #6706: Creating User Authentication UI(Login and Signup) with Compose Desktop
### Topic Suggestion
[Kotlin] Creating User Authentication UI(Login and Signup) with Compose Desktop

#### Proposed title of article
Creating User Authentication UI(Login and Signup) with Compose Desktop

#### Proposed article introduction
With Compose Multiplatform, one can create a very interesting layout using Kotlin and Jetpack compose for Desktop applications. Having a good user authentication layout attracts users to sign in to your system easily. Compose desktop has made this achievable with a lot of ease unlike SWINGS in Java which requires one to write lots of code. This tutorial will help the reader to understand how to use Compose Desktop to create well-structured desktop applications just like in Android. 

#### Key takeaways 
- How to use Compose Desktop.
- How to implement Layout designs using Compose Desktop.
- Compose desktop design patterns

#### Article quality
This article is going to be unique since Compose Desktop is a new technology that is just coming into existence. it is going to help the learner to get started with Compose Desktop. It will help the learner to also migrate from using the tiresome SWING library in Java. 

#### References
[Compose Desktop](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Getting_Started)

### PR DESCRIPTION
**Pull request by Collince-Okeyo**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6706

### CODE REVIEW

**Comment by Collince-Okeyo** [comment]
Hello @hectorkambow , @mohamedgh16 , @Kayere , @ahmadmardeni1 , @louisefindlay23 , please check my duplicate PR.

**Comment by hectorkambow** [comment]
image

**Comment by hectorkambow** [comment]
@Collince-Okeyo 
Thank you for re-submitting the article.
Since this article has been submitted twice before it will not be eligible for a payout. 

In an interest to be fair to the other members of the community.  We will be sure to review and published it (pending any other errors). 

It will be reviewed in the order it was re-submitted 👍   

Thank you v much.

**Comment by Collince-Okeyo** [comment]
How is the progress with this PR @WanjaMIKE , @hectorkambow

**Comment by hectorkambow** [comment]
Jumping on this one

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
Was not able to render the article - I think GitHub is having issues - will return to this PR asap.

**Comment by Collince-Okeyo** [comment]
@hectorkambow 
What is the fate of this article?

**Comment by hectorkambow** [comment]
@Collince-Okeyo 

Thank you v much for following up. 

Was able to render the article and made some minor edits. 

👏 Nicely done.

You'll be able to see your live published article on the site (in about 30 mins).

To give your article a boost in page engagement - share it across your social site (LinkedIn/Twitter) and tag the EngEd program so we can also share it and give it some traction as well!
(we will try and do the same once we feature it).

_**If you have not done so already - consider adding a skill section to your author page. This will go a long way for potential future employers.**_

**Pull request merged**
