### PR TITLE
A Look at Some Bootstrap Examples

### LINKED ISSUE #2827: The best bootstrap examples
### Proposed title of article
The best bootstrap examples

### Introduction paragraph (2-3 paragraphs):

Bootstrap is a popular web development front-end framework. It comes with ready-to-use components and design elements for formatting HTML content. Bootstrap is supported by modern browsers like Chrome, Firefox, Opera, Safari, and Internet Explorer.

For different layouts, Bootstrap features a responsive grid system. It's an excellent place to start when creating a mobile-friendly website. Optional JavaScript features like collapsible content, carousels, and modals are also included.

Bootstrap provides an easy solution both for design and responsiveness. It is packed with beautiful elements that can be further styled with your custom CSS, as well as a full grid system to keep your website responsive across all screens while using a clean and understandable syntax.
 

### Key takeaways: 
1. Installing Bootstrap with a Package Manager
2. How to add Bootstrap on a page
3. The Grid System
4. The container
5. The Jumbotron

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Erastuskanyatta**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #2827 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by EspiraMarvin** [comment]
@ahmadmardeni1  @hectorkambow If this is not a duplicate, you can assign me for a test review

**Comment by hectorkambow** [comment]
plagiarism check done

**Review by Dawe-7 — CHANGES_REQUESTED** [review]
@Erastuskanyatta, Great article. I have just a few changes for you. First, your authors folder should contain two files: ` index.md` (Brief description of who you are and interests) and `avatar.png` (snapshot image of you). Delete the ` avatar.jpeg` file and add the `index.md` file in your authors folder. Take a look at this first time contributor [author files](https://github.com/section-engineering-education/engineering-education/pull/1783/files) to understand that.

Also add the  missing link for `Sass` . Ping me once you're done with the changes and we'll move to tech review.

**Comment by Erastuskanyatta** [comment]
@Dawe-7, please have a look at my last commit.  About the author details,  kindly have a look at my commits above.
Thank you.

**Comment by Dawe-7** [comment]
> @Dawe-7, please have a look at my last commit. About the author details, kindly have a look at my commits above.
> Thank you.

@Erastuskanyatta, thanks for the clarification. Everything looks good, thanks for the changes.

**Review by Dawe-7 — APPROVED** [review]
@Kayere , this article is ready for final review.

**Comment by WanjaMIKE** [comment]
@Erastuskanyatta You have just covered minor aspects of Bootstrap. Nowadays, there is no section 2 or follow up article. I will encourage you to add more content to improve its value. For instance, there are things such as flex, utilities, carousel, badges, progress bars, spinners,  icons, media objects etc. This is an extensive topic and is not adequately covered in your tutorial.

**Comment by Dawe-7** [comment]
> @Erastuskanyatta You have just covered minor aspects of Bootstrap. Nowadays, there is no section 2 or follow up article. I will encourage you to add more content to improve its value. For instance, there are things such as flex, utilities, carousel, badges, progress bars, spinners, icons, media objects etc. This is an extensive topic and is not adequately covered in your tutorial.

@Erastuskanyatta Could you add more content to your article. I second with @WanjaMIKE, this topic is extensive. Once you add more content we can proceed.

**Comment by Erastuskanyatta** [comment]
@Dawe-7, how is my last commit?

cc @WanjaMIKE

**Comment by Dawe-7** [comment]
> @Dawe-7, how is my last commit?
> 
> cc @WanjaMIKE

@Erastuskanyatta i still feel you have not covered the content adequately. What do you think @WanjaMIKE

**Comment by WanjaMIKE** [comment]
Kindly, work on this PR and open a new one when its ready. I will be closing this one. Thanks

**Pull request closed without merging**
