### PR TITLE
Collection in C++

### LINKED ISSUE #4767: Collection in c++
**topic suggestion**
Collection in c++

**Introduction**
Collection in c++ is a framework that provides an architecture for you to store and manipulate data. In fact talk about containers. It is often used when storing or manipulating data during runtime. In this article, we will introduce collection and discuss using various examples of how we can manipulate data at runtime without having to specify storage or size.
Furthermore, we will use clear explanations to understand the Collection interface hierarchy. We will see how the sub-interfaces like list, queue, set, etc relate to each other.
Moreover, we will learn how to implement the collections sub-interfaces since we cannot implement collection itself. We will further discuss the classes of collection which some of include ArrayList, LinkedList, among others.

**Key Takeaways**
In the article, the user will get to learn:

1. Introduce Collections in c++
2. The Collection interface hierarchy
3. Relation of Collection sub interfaces
4. Implementation of interfaces
5. Classes of collection

**Reference**

N/A

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

### PR DESCRIPTION
**Pull request by tetie**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4767

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by tetie** [comment]
Hi @jumamiller 
Please take a look at this article. It is a duplicate from earlier before.

**Comment by jumamiller** [comment]
Hi,Seems you've multiple article's `index.md` files. Let's ensure we have the right files for review!

**Comment by tetie** [comment]
Hi @jumamiller,   what   am i  supposed to do in this article

**Comment by tetie** [comment]
Hi  @jumamiller ,       I openned another pr a duplicate of article  #5073  and it has got changes needed

**Comment by jumamiller** [comment]
Hi, I meant you have 2 indices files for the article, which one should I review?

**Comment by tetie** [comment]
Hi @jumamiller , i deleted the extra index.md files. Proceed with the review, thanks.🚀

**Comment by jumamiller** [comment]
Which file is this `collections-in-c++/hero.lnk `.

**Comment by jumamiller** [comment]
> Which file is this `collections-in-c++/hero.lnk `.

As a rule of thumb, ensure all code snippets are well explained!

**Comment by tetie** [comment]
Hi @jumamiller ,  i will do it as soon as possible thank you

**Comment by jumamiller** [comment]
Hello @tetie, can I get status on this PR, it's a duplicate and should be well polished. And ensure we have minimal mistakes such as writing `c++` instead of `C++`. Kindly work on it as soon as possible!

**Comment by Kayere** [comment]
Plagiarism check done ✅

**Comment by tetie** [comment]
hi @jumamiller , have done the changes you can proceed to review. thanks

**Comment by jumamiller** [comment]
@tetie, I have seen this article had been closed severally. The key reason is being unable to make the requested changes. For instance, I requested that we should have `C++` instead of `c++`. This had not been done among others. I have made all these major edits.

Now, kindly, ensure your code is working and attach all links to the complete code since I can see several mistakes in the snippets.

**Comment by tetie** [comment]
Okay i will do it,  thanks

**Comment by jumamiller** [comment]
Hi, what is this file for: `collections-in-c++/hero.lnk`?

**Comment by jumamiller** [comment]
I will close this article for now. Feel free to submit a ready-to-publish article with the right files.

Thank you!

**Comment by tetie** [comment]
Hi @jumamiller  , i request that you open this article so that i can commit changes .
Thank you

**Comment by tetie** [comment]
Hi @jumamiller,  kindly open this article  so that I 
Can be able to  commit changes

**Pull request closed without merging**
