### PR TITLE
Creating an Applet with Threads in Java

### LINKED ISSUE #4407: creating an Applet with thread in java
#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

#### Proposed title of article
creating an applet using thread in java 
#### Proposed article introduction
In this tutorial am going to show you how to create Applet in java using threads, besides am going to show some basic functions of threads in java language. We will also create thread and implement it in applet using java.  And show some codes in the tutorial for the implementation.

#### Key takeaways 
By the end of this tutorial the learner will be able to:

- Know how to implement threads in java.
- How to call ThreadsApppletclass in java.

#### Article quality
I will be giving steps by steps process from creating some of the directories of implementing threads in Applets, which most of blog sites often ignore

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by AndrewOdera**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4407

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by AndrewOdera** [comment]
@Dawe-7

**Comment by AndrewOdera** [comment]
Any progress sir?

**Review by Dawe-7 — APPROVED** [review]
Hello @AndrewOdera, The article is an interesting read. Nice job!
Just a few things I'd like to point out that you should be keen on in your future articles:
- It is always advisable to submit an article that is fully polished - By this, I mean having an article that does not have too many grammatical corrections. I suggest that you check out our [resources page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) which has links to various resourceful tools for writing.
- Ensure all your images are 600x400 pixels.
- Lastly please go through ALL the corrections I have made so that you can not repeat the same mistakes - I noticed that you make just a few changes requested and discard the others made by me in the commits. KIndly avoid this for us to avoid going back and forth in review.

-  When changes are requested, it is advisable to go through them taking note and when you create a new PR ensure that ALL changes made before should be effected in the new PR along with the new ones.

That's it, a final review will be done now by a Content Moderator. Otherwise, congratulations on contributing your first article to the EngEd program.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via Slack (Marsa) or my personal email (dantedawek@gmail.com).
I am ALWAYS here to help.

Looking forward to seeing you contribute more to the EngEd program.

**Comment by AndrewOdera** [comment]
Thank you

**Comment by AndrewOdera** [comment]
Hello! Any progress from final rewiew?

**Comment by hectorkambow** [comment]
Our CM team will be sure to review this one after they go through the queue 👍

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
@AndrewOdera  I am seeing that this PR has some changes that have not been pushed? 

When I check it out it will not let me make any edits because it thinks some changes are pending?

image
cc @Dawe-7

**Comment by hectorkambow** [comment]
Overall nice job gents 🚀

**Pull request merged**
