### PR TITLE
Complete guide on using sequelize basic and advanced features - (Duplicate of #4593)

### LINKED ISSUE #2949: Complete Guide on using Sequelize basic and advanced features.
### Proposed title of article
Complete Guide on using Sequelize basic and advanced features.

### Introduction paragraph (2-3 paragraphs):
Sequelize is a JavaScript library that manages database. It supports all the popular databases such as PostgreSQL, MySQL, SQLite and MSSQL. This kind of package is known as an Object Relation Mapper, ORM’s are used to convert object relational syntax to database schema. Sequelize is used with NodeJS.
Sequelize only support relational databases, database like mongo DB or other NoSQL databases are not supported.  Sequelize supports solid transaction, eager and lazy loading, relations, read replication and other cool features.

### Key takeaways: 

- How to install sequelize
- How to install drivers associated with the different database
- Connecting to the database and testing the connection
- How to use Sequelize CLI
- Model Querying (Inserting, Updating, Deleting)
- Associations (One to One, One to Many, Many to Many).

### References: 
[Manual | Sequelize](https://sequelize.org/master/index.html)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Josh4324**
This closes #2949

### CODE REVIEW

**Comment by Josh4324** [comment]
@srishilesh New Pr

**Comment by srishilesh** [comment]
Duplicate of #4593

**Comment by srishilesh** [comment]
Will start my review ASAP

**Comment by srishilesh** [comment]
Moving to the tech review.

**Review by srishilesh — APPROVED** [review]
@Josh4324 

Great article. It was a bit too long. From next time, make sure to keep it short.

Make sure to go through my commits to understand all the changes.

Moving for the final review.

Thanks.

**Comment by hectorkambow** [comment]
@Josh4324 
Thank you for your patience as our team has been working diligently to work through the recent increased volume of articles coming in. 

We are going through are ready articles in the order they were received and working on improving our review time as well. 

🚀

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
