### PR TITLE
How to Build a FullStack Reactive Svelte application with MongoDB

### LINKED ISSUE #5227: How to Build a FullStack Reactive Svelte application with MongoDB
#### Proposed title of article

How to Build a FullStack Reactive Svelte application with MongoDB

#### Proposed article introduction

Svelte is a new fronted JavaScript approach to building user interfaces. This introduces a new alternative that use can use besides React, Angular, Vue. However, Svelte is a compiler, whereas the other alternatives are frameworks/libraries. When you build your apps with Svelte, you run the Svelte compiler that automatically goes over your code and files. This creates bundled JavaScript instructions that execute in the DOM at runtime. Instead of using techniques like virtual DOM diffing, Svelte writes code that surgically updates the DOM when the state of your app changes.

With such amazing backend technology, connecting to backend services and accessing data from a server will be essential. In this guide, we learn more about Svelte and how to create a Svelte application with MongoDB.

#### Key takeaways 

- What is Svelte
- Svelte Features
- Set up a Svelte basic application
- Set up a  Svelte backend
- Connect Svelte backend with MongoDB

#### Article quality

Svelte is used to build a frontend application just like the likes of React, Angular, and Vue. There might be a need to connect to a backend server that uses a database such as MongoDB. This guide will help the reader build a complete full-stack reactive Svelte-inspired application.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by kimkimani**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5227

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by lalith1403** [comment]
plagiarism check done ✔️

**Review by mercymeave — COMMENTED** [review]
Hey @kimkimani 

Thank you for such a straightforward and easy-to-read article.  I will proceed to tech review.

**Review by mercymeave — APPROVED** [review]
Hello @kimkimani :wave: 

Thank you for such a great article. I had fun reading it, and the review was easy. Great work! :rocket:

**Comment by hectorkambow** [comment]
I'll leave the Final Review to the CM team - as they will assess the test reviews.

@section-engineering-education/content-moderator-team  

cc @ahmadmardeni1 @Kayere @LinusMuema

**Comment by ahmadmardeni1** [comment]
I'm on it. @hectorkambow

**Comment by ahmadmardeni1** [comment]
Great work team @mercymeave @kimkimani
A quick note: Make sure your images' names match the URLs.

**Pull request merged**
