### PR TITLE
A Beginner's Guide to Nonlinear Optimization with Bisection Algorithm 

### LINKED ISSUE #6280: A Beginner's Guide to Nonlinear Optimization with Bisection Algorithm
#### Proposed article introduction
The Bisection method is one of the simplest and most reliable iterative methods
for the solutions of non-linear equations. This algorithm is mostly used to optimize complicated non-linear Optimization function (cost functions) in deep learning (a sub-field of Machine Learning that uses a neural network to learn from data). Bisection method, also known as Binary chopping or Halfinterval method, relies on the fact that if f(x) is real and continuous in the interval a<x<b, and f(a) and f(b) are of opposite signs, such that,
 f(a)*f(b)<0, then there exist at least one real root between a and b. This means there may be more than one root within this interval. Given the initial interval that contains the root, the Bisection Method works this way:

1. First, partition the initial interval [a,b] into two sub-intervals [a,x_0] and [x_0,b] where x_0 is the midpoint of the initial interval. This is done using the formula:
x_0 = (a+b)/2

2. Evaluate the function f(x) at x_0.

We then consider three cases in determining the root or the new interval containing the root we are looking for.

1. If f(x_0)=0, then x_0 is the required root.

2. If f(x_0) is less than or equal to zero, i.e., is negative, then f(x_0) and f(b) have opposite signs. Therefore, the new interval will be [x_0,b].

3. If f(x_0).0, then the opposite signs for the most closes x points is between f(a) and f(x_0). Therefore, the new interval containing the root is [a,x_0].

Now;
- If case one occurs, the bisection process is terminated since the root has been found.
- If either case $(2)$ or $(3)$ occurs, the process is repeated until the root is obtained to the desired tolerance.

In this article we will look exact how this algorithm work, solve some optimization function using this it, state it's advantages and disadvantages and later learn how it is implemented in python.

#### Key takeaways 
By the end of the session, the learner is expected to, comfortably, be able to:
- Theoretically, explain how the Bisection method works.
- Explain what Zeros of a polynomial function are.
- Perform the Bisection Method by hand. We will come out of the theoretical world and work on a real-world example in this session.
- Determine the number of iterations required to obtain the root of a polynomial function prior to performing the Bisection Method.
- Outline the main shortcomings of the Bisection method and have an idea of the related algorithms that address these problems.
- Implement the Bisection method using the Scipy library in Python.

#### Article quality:
Most of the tutorials online focus a lot on the theory behind the Bisection method, and in comparison, less effort is put into the implementation. The articles that implement this algorithm are usually very shallow on the intuition making the beginner very unfriendly with the content. This article will provide complete content where the learner can learn the theory behind the Bisection algorithm and at the same time implement what they have learned.

Since it will be a two in one article, we will try as much as possible to be straight to the point but without sacrificing the quality of the content. So, the simplification of the content and in-depth coverage of the topic are two elements that will grant this article a uniqueness among all other articles already in place on the same topic. Furthermore, the clarity of the implementation session, i.e., highly explained code snippets, will add value to this article.

#### References
N/A

### PR DESCRIPTION
**Pull request by Daniel695**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6280

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by srishilesh** [comment]
Hello @Daniel695 ,

Thanks for submitting this PR.

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started.

Meanwhile, we suggest you to go through existing approved PRs/published articles to see if you have missed out anything.

Thanks.

**Comment by Jethro-magaji** [comment]
Hi! @Daniel695 
I just went through your article, it turns out your article would be needing a thorough editing, the EngEd peer review team don't offer editing services. Please, run your article on tools like Grammarly and ProWritingAid for better editing.

For now, I will be closing your PR to give you time to polish your article. When you're ready, ping me to reopen it.

Visit the EngEd new contributor's docs [here](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md) to guide you.
Here's a [link](https://github.com/section-engineering-education/engineering-education/pull/6210/commits/acc44893d4ec258f4e077b9ce8e3e2ca2b9d6a9f) to a PR with little or no revision to guide you on formatting. However, if you have any questions or require help, you can reach out to me on the EngEd slack channel.
Thanks.

**Comment by Daniel695** [comment]
Hello @Jethro-magaji 
am done with the grammar changes you'd requested. Kindly, open this PR so that I can update

**Comment by srishilesh** [comment]
Hey @Jethro-magaji ,

Thanks for checking on this PR.

As a quick note, it would be great if you could point out a few instances of such errors (or any other enhancements) - it would help the author to correct them and avoid any potential closure of the newly created PRs. We might need to justify the reason for PR closure.

Make sure to do that from next time.

Thanks.

**Comment by Jethro-magaji** [comment]
> Hey @Jethro-magaji ,
> 
> Thanks for checking on this PR.
> 
> As a quick note, it would be great if you could point out a few instances of such errors (or any other enhancements) - it would help the author to correct them and avoid any potential closure of the newly created PRs. We might need to justify the reason for PR closure.
> 
> Make sure to do that from next time.
> 
> Thanks.

Thanks noted, I will do that next time.

**Comment by Jethro-magaji** [comment]
> Hey @Jethro-magaji ,
> 
> Thanks for checking on this PR.
> 
> As a quick note, it would be great if you could point out a few instances of such errors (or any other enhancements) - it would help the author to correct them and avoid any potential closure of the newly created PRs. We might need to justify the reason for PR closure.
> 
> Make sure to do that from next time.
> 
> Thanks.

Thanks noted, I will do that next time.

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
@Jethro-magaji  

I believe there may be some confusion with the image paths. 

The image type (eg: .png .jpg) should match the image file type. 

Noticed you had all capital .PNG

**Pull request merged**
