### PR TITLE
Why Backup won't work for Stateful containers?

### LINKED ISSUE #2887: Why Backup won't work for Stateful containers?
### Proposed title of article
Why Backup won't work for Stateful containers?

### Introduction:
Any data that containers create need to be backed up. It is easier to backup data stored in stateful apps compared to stateless apps. However, there has been a myth that containers are stateless, which may be the truth or false. 
In this article, we will debunk these myths and misconceptions and explore why backup solutions may not work for stateful containers.

### Key takeaways: 
At the end of this article, the learner will be able to:
- understand where containers stores state
- explain where and why most backup solutions fail
- find out the right solution for backup

### References: 
N/A

### PR DESCRIPTION
**Pull request by verah-tech**
The article explains where containers stores state, why most backup solutions fail, guides on the methods to backup and recover containers and finds out the right solution for backup

### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #2887.

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Could you fix the minor issues identified in this plagiarism check
[Why Backup won't work for Stateful containers #3519.pdf](https://github.com/section-engineering-education/engineering-education/files/7072272/Why.Backup.won.t.work.for.Stateful.containers.3519.pdf)

**Comment by verah-tech** [comment]
> Could you fix the minor issues identified in this plagiarism check
> [Why Backup won't work for Stateful containers #3519.pdf](https://github.com/section-engineering-education/engineering-education/files/7072272/Why.Backup.won.t.work.for.Stateful.containers.3519.pdf)

@WanjaMIKE I have fixed the issues. Kindly review them.
Thank you

**Review by BrianaNzivu — APPROVED** [review]
Hey @verah-tech 👋 .

It is such a coincidence we meet again.

First of all, **AMAZING** job on the article. 
Barely any corrections to be made, well-written, and very easy to read and understand. 

I have no comment to make except for you to go through the minor changes I have made.

Keep up the great work once again! 👏 

Regards. 🚀

**Comment by verah-tech** [comment]
> Hey @verah-tech 👋 .
> 
> It is such a coincidence we meet again.
> 
> First of all, **AMAZING** job on the article.
> Barely any corrections to be made, well-written, and very easy to read and understand.
> 
> I have no comment to make except for you to go through the minor changes I have made.
> 
> Keep up the great work once again! 👏
> 
> Regards. 🚀

@BrianaNzivu It is amazing we met again, the changes you have made I have noted them and I will improve on the next article I will write. Thank you for reviewing looking forward to working with you on more articles.

**Comment by ahmadmardeni1** [comment]
Upon running your article through our 3rd party plagiarism checker, it seemed to raise a few flags, and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Why Backup won't work for Stateful containers? #3519](https://github.com/section-engineering-education/engineering-education/files/7109661/New.Scan.11_11.AM.Copyleaks.Report.pdf)

**Comment by verah-tech** [comment]
@ahmadmardeni1 The minor issues raised with the article have been fixed. Thank you
cc @BrianaNzivu

**Comment by ahmadmardeni1** [comment]
Plagiarism check done.

This article is light on substance, is it complete? @verah-tech 
cc @BrianaNzivu

**Comment by verah-tech** [comment]
@ahmadmardeni1 The highlighted article's key takeaways issue no: #2887 have been covered and finalized. Thank you cc @BrianaNzivu

**Comment by ahmadmardeni1** [comment]
I still think this article is light on substance. What do you think? @BrianaNzivu

**Comment by BrianaNzivu** [comment]
Hey @ahmadmardeni1 👋🏾.
I belive she has covered everything as discussed in the issue for this PR. 

The article is actually very knowledgeable and @verah-tech has put it in the most straightforward way possible covering most of the key areas using a few sentences. Unfortunately, there is nothing to add in this article since it's probably the most detailed article covering this topic compared to most blogs. 

I personally believe it's one of the best articles I have read and reviewed on Containers.

Regards 🚀
Cc @verah-tech

**Comment by hectorkambow** [comment]
👍 
Awesome - is this PR still under review? @ahmadmardeni1 

cc @BrianaNzivu  

or is it ready for a final review?

**Review by BrianaNzivu — APPROVED** [review]
Hey @verah-tech  👋 .
Just a final comment: 
- When it comes to plagiarism, always try and run your article on [Quetext](https://www.quetext.com/) to avoid any extra revision round.  You can also use [Quilbot](https://quillbot.com/) to paraphrase some statements.

That's it! :smile: 

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

**Comment by WanjaMIKE** [comment]
@BrianaNzivu remember `<!--more-->` in the front matter.

**Comment by WanjaMIKE** [comment]
Merged #3519

**Pull request merged**
