### PR TITLE
Unit Testing with Vue-test-utils

### LINKED ISSUE #6913: Unit Testing with Vue-test-utils
### Topic Suggestion
Unit Testing with Vue-test-utils

### Writing sample(s): 
https://www.section.io/engineering-education/how-to-receive-emails-using-emailjs-in-vue3/

#### Proposed title of article
Unit Testing with Vue-test-utils

#### Proposed article introduction
[Languages]
As a developer, you happen to write unit tests 90% of the time. It is good practice to write tests; in addition, it is an in-demand skill. [Vue-test-utils](https://v1.test-utils.vuejs.org/) is a library built on top of jest and it is the official library for testing Vue applications. With Vue-test-utils one can check if a component is performing just as it should or if a user is seeing what he/she is meant to see on every component or if a component is accepting the props being passed to it by its parent component and so many functionalities as well.   It's very easy to use and I am ready to share its different use cases and best practices in this article.

#### Key takeaways 
After reading this article, the reader should be able to:
- Know how to write unit tests with the Vue-test-utils library
- Know how to write async tests
- Know why he/she should test

#### Article quality
In this article, I will be going in-depth as I will explain how to write tests for different use cases. 

#### References
https://v1.test-utils.vuejs.org/
https://github.com/vuejs/test-utils

### PR DESCRIPTION
**Pull request by mercybassey**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6913

### CODE REVIEW

**Review by jumamiller — CHANGES_REQUESTED** [review]
Hi, `jsx` doesn't seem to be supported by markdown!  Vue is Javascript. Kindly update where applicable!

**Comment by mercybassey** [comment]
> Hi, `jsx` doesn't seem to be supported by markdown! Vue is Javascript. Kindly update where applicable!

@jumamiller requested markdown changes are done.

**Comment by jumamiller** [comment]
@mercybassey; The article has a couple of grammatical mistakes, ensure you run it via Grammarly checker. The tech review has failed from the beginning. The starter project clone doesn't contain the components/view you're describing.

- Either guide readers on how to create a new project from scratch or provide a complete scaffold with the right files.
> I'm still emphasizing; use active voices and go straight to the point. Improve communication and the article's general structure. Know when to use bold texts, or to give links. Organize your work!

**Comment by mercybassey** [comment]
@jumamiller the grammatical errors are corrected, except for the words in backticks that are not recognized by Grammarly. The Github project references for both the starter project and the full project are up to date and contain the right files.

**Review by jumamiller — APPROVED** [review]

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
This was a fantastic tutorial 👏 great work @mercybassey  


cc @jumamiller  

nicely done - looking forward to reviewing more great articles like this 🚀

**Comment by hectorkambow** [comment]
Minor fixes towards the end on some links 👍

**Pull request merged**
