### PR TITLE
Top 5 Docker Logging Best Practices 

### LINKED ISSUE #2346: Top 5 Docker Logging Best Practices
### Proposed title of article
Top 5 Docker Logging Best Practices
### Introduction paragraph (2-3 paragraphs):
As with developing any application, logging is a central part of the process and especially useful when things go wrong. But logging in the world of containerized apps is different than with traditional applications. Logging Docker effectively means not only logging the application and the host OS, but also the Docker service.

There are a number of logging techniques and approaches to keep in mind when working with Dockerized apps. This article explains what Docker logging is, discusses Docker logging challenges, and outlines the top 5 best practices and their strengths. 

### Key takeaways: 

1. What is Docker logging? 
2. Challenges with Docker logging.
3. Docker logging methods and best practices.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by BashiirIsla**
this fixes #2346 
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
I believe you are a first-time contributor. Welcome to Section, please add your author info and a picture in the [correct folder structure](https://github.com/section-engineering-education/engineering-education/tree/master/content/authors). @BashiirIsla

**Comment by ahmadmardeni1** [comment]
Also, please change the hero image, it is not related to the topic. You can search for another one or use one of [our templates](https://github.com/ahmadmardeni1/Canva).

**Comment by ahmadmardeni1** [comment]
I believe you are a first-time contributor. Welcome to Section, please do the following:

- Add your author info and a picture in the [correct folder structure](https://github.com/section-engineering-education/engineering-education/tree/master/content/authors). @BashiirIsla 

- Change the hero image, it is not related to the topic. You can search for another one or use one of [our templates](https://github.com/ahmadmardeni1/Canva).

- Add a further reading section, you are free to add whatever resources you want but in this case; we have a lot of articles covering docker/containers so only add our articles/tutorials. You can find it [here](https://www.section.io/engineering-education/topic/containers/).

**Comment by BashiirIsla** [comment]
@ahmadmardeni1  This is my second article. No need for author info.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by BashiirIsla** [comment]
@ahmadmardeni1 Kindly, what is the status of this article?

**Comment by ahmadmardeni1** [comment]
It is in the queue. I will finish the revision by today. @BashiirIsla

**Comment by ahmadmardeni1** [comment]
This is a great article, good job👍 @BashiirIsla

**Comment by BashiirIsla** [comment]
> This is a great article, good job👍 @BashiirIsla

Thank you for the great review insights @ahmadmardeni1

**Review by louisefindlay23 — APPROVED** [review]
@BashiirIsla, congrats your article has passed final review.

Thanks, @ahmadmardeni1 for peer reviewing.

**Pull request merged**
