### PR TITLE
Using kotlinx coroutines in firebase authentication and realtime database in android

### LINKED ISSUE #5015: [Android] Using Kotlinx Coroutines in Firebase Authentication and Realtime Database in Android
#### Proposed article introduction
Firebase Authentication provides backend services, easy-to-use SDKs, and ready-made UI libraries to authenticate users to your app. Also, the Firebase Realtime Database is a cloud-hosted database. Data is stored as JSON and synchronized in realtime to every connected client. All this two makes the work of Android Developers easier because they don't want to write on their own backend. 

In Android, while making network calls such as user Authentication, sending or querying data from Firebase Database; it is advisable that you don't perform such tasks on the `Main Thread`. You should do such tasks on the `Background Thread` and then update the UI accordingly. 

In Kotlin, a Coroutine is a concurrency design pattern that you can use on Android to simplify code that executes asynchronously. On Android, Coroutines helps manage long-running tasks that might otherwise block the main thread and cause your app to become unresponsive.

When we perform Firebase tasks using `Coroutines`, our code looks cleaner with no boilerplate code, making it more readable and understandable, and in the long run, it improves app productivity.

#### Key takeaways 
- A review of Kotlinx Coroutines.
- Replacing the `OnCompleteListeners` Interfaces with `await` function.
- Creating a `SafeCall` Extension function for making network calls.

#### Article quality
My article will be beginner friendly, making it easier for readers to understand the concepts. Also most of the articles online don't use Jetpack Components, so in my article, I will use some concepts of Jetpack Components such us `Livedata` and `ViewModel` and the `Repository` pattern.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
- Kotlin Coroutines.
- Firebase Documentation.

### PR DESCRIPTION
**Pull request by JoelKanyi**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5015

### CODE REVIEW

**Comment by Kayere** [comment]
Hello @JoelKanyi.

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Using kotlinx coroutines in firebase authentication and realtime database in android #5268 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7669716/Using.kotlinx.coroutines.in.firebase.authentication.and.realtime.database.in.android.5268.Copyleaks.Report.pdf)

**Comment by JoelKanyi** [comment]
@Ericgacoki 
Have fixed plagiarism

**Comment by Kayere** [comment]
Plagiarism check done.

**Review by Ericgacoki — APPROVED** [review]

**Comment by LinusMuema** [comment]
Hi @JoelKanyi

Awesome job on the article.

cc: @Ericgacoki

**Comment by hectorkambow** [comment]
@Ericgacoki & @LinusMuema  

The author has expressed interest in doing a test review - wanted to ask how the review went for this PR ?

**Comment by LinusMuema** [comment]
Well @hectorkambow 
I didn't find any issues with the article. I guess as I received it for the final review, it was clean. :rocket:

I have also noticed the author has had a good track. We could give him a test to check his reviewing skills 🙂

**Pull request merged**
