### PR TITLE
[Duplicate of #6673]  Getting Started With Debugging In Android Using Chucker 

### LINKED ISSUE #5579: [Android]Getting Started With Debugging In Android Using Chucker
### Topic Suggestion
[Android]Getting Started With Debugging In Android Using Chucker

#### Proposed title of article
Getting Started With Debugging In Android Using Chucker

#### Proposed article introduction
Chucker simplifies the inspection of HTTP(S) requests/responses fired by your Android App. Chucker works as an OkHttp Interceptor persisting all those events inside your application, and providing a UI for inspecting and sharing their content.

Apps using Chucker will display a push notification showing a summary of ongoing HTTP activity. Tapping on the notification launches the full Chucker UI. Apps can optionally suppress the notification, and launch the Chucker UI directly from within their own interface.

#### Key takeaways 
- What is Chucker and its applications in Android development.
- How Chucker simplifies the inspection of HTTP(S) requests/responses fired by your Android App.
- How to display a push notification when using Chucker.
- Advantages of using Chucker.

#### Article quality
This article is going to be unique since am going to use MVVM pattern to illustrate the concept of Chucker debugging. I am also going to make it beginner friendly to allow easy understanding. I am also going to show a push notification which is an added advantage to the reader. Although there are certain sites about Chucker, there are still problems with developers understanding the concept.

#### References
[Chucker](https://github.com/ChuckerTeam/chucker)

### PR DESCRIPTION
**Pull request by Hepatrique**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5579

### CODE REVIEW

**Comment by Hepatrique** [comment]
Hello @Dawe-7 , I have created a duplicate PR as requested.

**Review by Dawe-7 — APPROVED** [review]
Nice article @Hepatrique. Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles.

@hectorkambow ,this article is ready for final review. It is a duplicate of the PR which had merge conflicts.

**Comment by Hepatrique** [comment]
Thanks for the heads up @Dawe-7, I shall do that on my next article.

**Comment by Kayere** [comment]
Great article @Hepatrique.
Thank you for the review @Dawe-7.

**Pull request merged**
