### PR TITLE
Integration of ROS with Arduino

### LINKED ISSUE #3076: integration of ROS with Arduino
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction paragraph (2-3 paragraphs):
ROS is an operating system that contains softwares, tools and libraries to help build robot applications. ROS works in linux ubuntu or linux debian and therefore, integration of ROS with Arduino, a ROS driver for Arduino-based-Robots is used as a starting point and easily generalized to a wide variety of other robots also based on Arduino controller boards.
we will learn samples of arduino code through the the Arduino software. In order to emulate ROS language directly in Arduino code, we need rosserial stack.
### Key takeaways: 
1. what is ROS?
2. Code and connect an Arduino circuit
3. Interface ROS with arduino

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Newton-cyber**
integration of ROS with Arduino

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lanxg=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
This fixes #3076

### CODE REVIEW

**Comment by hectorkambow** [comment]
plagiarism check done

**Review by Dawe-7 — COMMENTED** [review]
@Newton-cyber, Before we begin the review process, kindly make the following changes:
1.  Format your paragraphs properly and remove the unnecessary lines after the conclusion. Check out this [article](https://github.com/section-engineering-education/engineering-education/pull/2985/files) to understand how it's done but don't include the `front matter` (the section before the introduction). 
2. Save your hero image as `hero.jpg` and not `hero.jpeg`, your article as `index.md` and not `index.md.md`
3. Move your author's details to the author's folder. It's not supposed to be in the article's folder.

**Comment by Dawe-7** [comment]
@Newton-cyber, Ping me when you are done.

**Comment by Newton-cyber** [comment]
@Dawe-7, The changes you had requested are in place

**Review by Dawe-7 — CHANGES_REQUESTED** [review]
@Newton-cyber, great article, It's easy to follow through and informative. I've left you a few suggestions that will improve the quality of your article. Consider making the changes and we can move on to tech review.

**Review by Dawe-7 — CHANGES_REQUESTED** [review]
@Newton-cyber, great article, It's easy to follow through and informative. I've left you a few suggestions that will improve the quality of your article. Consider making the changes and we can move on to tech review.

**Comment by Newton-cyber** [comment]
@Dawe-7 I have made changes

**Review by Dawe-7 — APPROVED** [review]
Great article @Newton-cyber 

@Kayere, this article is ready for final review.
cc: @hectorkambow

**Review by Kayere — COMMENTED** [review]
Congratulations for publishing your first article @Newton-cyber. Please go over the changes made by your peer reviewer and I to help improve the quality of your future articles.

Thank you for the review @Dawe-7🚀.

**Pull request merged**
