### PR TITLE
Top 7 Docker Container Monitoring Tools

### LINKED ISSUE #2131: Top 7 Docker Container Monitoring Tools
### Proposed title of article
Top 7 Docker Container Monitoring Tools
### Introduction paragraph (2-3 paragraphs):
Monitoring systems help DevOps teams detect and solve performance issues faster. With Docker and Kubernetes steadily rising, it’s essential to get container monitoring and log management right from the start.

Due to its popularity, monitoring docker containers sometimes boils down to a problem of choice, as there exist a variety of tools from which to choose, each of them has its pros and cons.

This article will delve deep into what container monitoring is and why you need it and compare the best container monitoring tools available today.

### Key takeaways: 
1.	Why Should You Monitor Docker Containers 
2.	Monitoring VS orchestration
3.	Docker Container Monitoring Tools
MetricFire
Docker CLI (docker stats)
cAdvisor
Scout
Data Dog
Sensu monitoring framework
Sematext

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by BridgetMwikali**
this fixes #2131

### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by zolomohan** [comment]
Hi @BridgetMwikali. I noticed that you haven't added markup for the headings. Use `###` for the headings.

**Comment by BridgetMwikali** [comment]
@zolomohan I have made the requested changes.

**Comment by zolomohan** [comment]
HI @BridgetMwikali. There is something wrong with the Table markdown. This is how it looks. Can you please fix it?

image

**Comment by hectorkambow** [comment]
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by BridgetMwikali** [comment]
@zolomohan I do not think there is an issue with that table. I am getting the same result when I convert my word document to mackdown.

**Comment by zolomohan** [comment]
@BridgetMwikali It's not recommended to convert word files it markdown. They aren't always perfect. I write the articles directly using Markdown. Please figure out what's causing the issue and fix them. 

If you can't fix the table, maybe you can move the pros and cons to each section instead of a table.

**Comment by zolomohan** [comment]
@BridgetMwikali Please let me know when you fix the table. We can move to the final review.

**Comment by BridgetMwikali** [comment]
@zolomohan I have moved the pros and cons section.

**Comment by zolomohan** [comment]
Hi @BridgetMwikali. Can you update your branch to the new directory structure. Ping me via slack if you need assistance.

**Pull request closed without merging**
