### PR TITLE
How KubeMQ users build scalable messaging platforms with Kubernetes Operators?

### PR DESCRIPTION
**Pull request by ephnjor2021**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by ephnjor2021** [comment]
This solves issue #2611

**Comment by hectorkambow** [comment]
@ephnjor2021 
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀

Thank you.

**Review by mbaabuones — CHANGES_REQUESTED** [review]
@ephnjor2021 Good article. Every time you write an article, ensure that there is value addition when compared with other related articles. I noticed that your article is not significantly different from the following articles:
1. https://marketplace.redhat.com/en-us/blog/how-kubeMQ-customers-build-scalable-messaging-platforms-with-kubernetes-operators
2. https://techosmo.com/hacker-noon/how-the-kubemq-messaging-platform-uses-operators-to-succeed/
Please revise your article to ensure that your article has some value addition. When you finish working on these changes, go through your work to review key aspects such as grammar and flow.

**Comment by ephnjor2021** [comment]
@mbaabuones Noted, Can I close the pull request and make the revision to add more value to be reopened at a later date.
Thank you

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by mbaabuones** [comment]
> 
> 
> @mbaabuones Noted, Can I close the pull request and make the revision to add more value to be reopened at a later date.
> Thank you

@ephnjor2021 You can make the changes on this pull request via your forked PR. No need to close this PR.

**Comment by ephnjor2021** [comment]
@mbaabuones I have made the changes to the article. Kindly review them.
Thank you.

**Comment by mbaabuones** [comment]
> 
> 
> @mbaabuones I have made the changes to the article. Kindly review them.
> Thank you.

Thank you. Please note the minor changes that I have made.

**Review by mbaabuones — APPROVED** [review]

**Comment by ephnjor2021** [comment]
> > @mbaabuones I have made the changes to the article. Kindly review them.
> > Thank you.
> 
> @ephnjor2021 Thank you. Please note the minor changes that I have made.

Noted with thanks

**Comment by hectorkambow** [comment]
overall great work gents  @ephnjor2021 

Some minor edits for flow and format 

please review to potentially improve future articles.

cc @mbaabuones

**Pull request merged**
