### PR TITLE
Image processing with Coil in Android

### LINKED ISSUE #2443: Image processing with Coil in Android using Kotlin
### Proposed title of article
Image processing with Coil in Android using Kotlin

### Introduction paragraph (2-3 paragraphs):

An application that doesn't process images, is pretty weird and tedious nowadays. One of the essential skills that an Android developer should have is knowing how to correctly work with images especially from a remote source. Nevertheless, this can be done in different ways based on the feature you want to implement in your app. In most cases, you might need to perform not only loading but also memory and disk caching, down-sampling the image in memory, re-using Bitmaps, and automatically pausing/cancelling requests.

In this tutorial we will learn how to perform the above mentioned tasks and many more using a **fast**,  **lightweight**, and **easy-to-use** library called `Coil`. This library is made in 100% Kotlin which makes it suitable for modern Android development.

### Key takeaways: 

By the end of this tutorial, the reader is expected to be able to:

1. Understand why Coil is preferred over other image processing libraries.
2. Load images from  remote sources using Coil.
3. Perform various image transformations.
4. Effectively handle errors encountered in any task.

### References: 

N/A

### PR DESCRIPTION
**Pull request by nonimdiana**
This fixes #2443

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by nonimdiana** [comment]
Reopening to fetch changes 🔄

**Comment by nonimdiana** [comment]
Closing to avoid having 2 PRs `open` at the same time!

**Comment by nonimdiana** [comment]
Ready to reopen for review but have to wait for the corresponding issue to be reopened!

**Comment by hectorkambow** [comment]
@kayere 
Please wait on the review

**Comment by hectorkambow** [comment]
@nonimdiana 

Thank you for submitting your 2nd article. 
Could you please close this PR and submit your finished article in a new PR so it goes into our queue. 

Thank you 🚀

**Pull request closed without merging**
