### PR TITLE
Implementing Skeleton Loading In Next.js With Tailwind CSS

### LINKED ISSUE #6157: Skeleton loading implementation In NextJs With Tailwindcss.
### Topic Suggestion
Skeleton loading implementation In NextJs With Tailwindcss.

### Proposed article introduction
The skeleton component is a placeholder that is used to improve the user experience in an application while waiting for content or data from an API endpoint to be rendered on the user interface. This article is an in-depth guide on how to implement the skeleton component and reasons why you should use it in your NextJS application.

Key takeaways
What is the skeleton loading?
Why you should use the skeleton loading in your application.
An in-depth guide on how to implement Tailwindcss skeleton loading in a NextJS application.

Article quality
This is a beginner-friendly and in-depth guide that covers the implementation of skeleton loading with tailwindcss while fetching data in a NextJS application.

References
- [Tailwindcss](https://tailwindcss.com/docs/installation)
- [NextJS](https://nextjs.org/docs/getting-started)
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by gisioraelvis**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #6157

### CODE REVIEW

**Comment by gisioraelvis** [comment]
Hello @Jethro-magaji 
Kindly take a look at my article, it's ready for review.

**Comment by WanjaMIKE** [comment]
Please correct some of the sentences showing plagiarism. Thanks

[New Scan 6_21 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/8126884/New.Scan.6_21.PM.Copyleaks.Report.pdf)

**Comment by gisioraelvis** [comment]
> Please correct some of the sentences showing plagiarism. Thanks
> 
> [New Scan 6_21 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/8126884/New.Scan.6_21.PM.Copyleaks.Report.pdf)

@WanjaMIKE 
I have corrected the sentences showing plagiarism

**Comment by Dawe-7** [comment]
> > Please correct some of the sentences showing plagiarism. Thanks
> > [New Scan 6_21 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/8126884/New.Scan.6_21.PM.Copyleaks.Report.pdf)
> 
> @WanjaMIKE I have corrected the sentences showing plagiarism

@WanjaMIKE, can we run another plagiarism check on this article, thanks.

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Comment by gisioraelvis** [comment]
@Dawe-7 
Progress on review, been on Preliminary for over 4days now!

**Review by Dawe-7 — CHANGES_REQUESTED** [review]
Awesome article @gisioraelvis. Just two suggestions:
1. Add the heading `When not to use skeleton loaders` to the table of contents`.
2. Ensure your images are of required size 600x400 pixels. Make sure you resize your hero image along with other images used in the article.

Make the changes so we can move on to tech review.

**Comment by gisioraelvis** [comment]
> Awesome article @gisioraelvis. Just two suggestions:
> 
> 1. Add the heading `When not to use skeleton loaders` to the table of contents`.
> 2. Ensure your images are of required size 600x400 pixels. Make sure you resize your hero image along with other images used in the article.
> 
> Make the changes so we can move on to tech review.

@Dawe-7 
I have implemented the requested changes, let's move on to tech review.

**Review by Dawe-7 — APPROVED** [review]
Nice article @gisioraelvis . Kindly go through the changes (especially on spacing) made throughout the review process so as to improve on the flow and format of your future articles.  

This article is ready for final review.

**Comment by gisioraelvis** [comment]
> Nice article @gisioraelvis . Kindly go through the changes (especially on spacing) made throughout the review process so as to improve on the flow and format of your future articles.
> 
> This article is ready for final review.

Thanks @Dawe-7 
I have taken note of the changes

**Pull request merged**
