### PR TITLE
Creating Responsive Layouts with MaterialUI in ReactJS

### LINKED ISSUE #2463: Creating responsive layouts with MaterialUI in ReactJS
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Creating responsive layouts with MaterialUI in ReactJS

### Introduction paragraph (2-3 paragraphs):
Oftentimes, when we build websites or web applications, one of the important aspects of the whole process is to make it responsive, asides from the functionalities. 

Making a web(site/app) responsive is among the quirks of accessibility that it must have so anyone with any type of device can be able to make use of the app or website.

Responsiveness has to do with how an application behaves and appears when it is being accessed on different devices. 

These devices range from mobile phones with different screen sizes and Personal computers or desktop computers. 

It is then, the obligation of a Frontend developer to create or write styles that would conform with the layout of the app to the different screen sizes of devices.

In this article we’d take a look at how to create layouts that are responsive at different device widths and breakpoints using a React framework, called [NextJS](https://nextjs.org/) and [Material UI](https://material-ui.com/) to make the process of creating such layouts less painful. 

### Key takeaways: 
The reader(s) will be able to grasp the following concepts when they're done reading this article:
- How to create a React application with nextJS
- Understand what Material UI is all about
- Components and Props

### References: 
None for now.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Caleb335**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #2463"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by Caleb335** [comment]
There are so many commits...

I guess this is a result of the former issue.

And I'm noticing some changes in the repository structure. I can't find the all the other contents (articles) in the repo. Just mine alone. Kindly take a look at the screenshot below 👇🏼 

Screenshot from 2021-06-11 16-31-22

**Comment by duncandegwa** [comment]
Delete the old repo...... then clone again to get the new structure

**Comment by Caleb335** [comment]
Alright I'd do just that.

**Comment by Caleb335** [comment]
Hi @WanjaMike,

There's an issue with this PR. I've created another PR with the updated structure of the new repository.

You can find it [here](https://github.com/section-engineering-education/engineering-education/pull/2597). Kindly take a look at it and let me know what's next so I can close this PR.

**Pull request closed without merging**
