### PR TITLE
Understanding Probability Distributions and their Simulations in R

### LINKED ISSUE #6652: Understanding Probability Distributions and their Simulations in R
#### Proposed title of the article

Understanding Probability Distributions and their Simulations in R

#### Proposed article introduction
When working with distribution, we typically want to know one of the four things below.

1. The density pdf of a particular value.
2. The distribution CDF.
3. The quantile value corresponding to a particular probability.
4. A random draw of values from a particular distribution.
R has functions for obtaining density, distribution, quartile, and a random value.

The general R naming is given as:
- pname: This calculates the density at input X
- pname: This calculates the cumulative probability density(CDF) at input X
- qname: This calculates quartile at an input X
- rname: This generates a random draw from a particular distribution

where the 'name' in all the four cases above represents the name of the given distribution.

Random value generation is a common activity in machine learning especially in Bayesian statistics where the posterior distribution can be intractable and therefore difficult to estimate parameters of interest from them. In such cases, we draw samples randomly from them using methods such as Monte Carlo simulation which is then used to estimate the population parameters. For the learner to be able to advance to such a level, first they should know the basics of how we draw samples from a certain distribution.

In this article, we will cover both the continuous and discrete probability distributions and how we simulate them as well as drawing samples from such simulated distributions. 

#### Key takeaways 
1. What's the probability distribution
2. What is the continuous and discrete probability distributions
3. Under the continuous probability distributions, the learner will know:
  - Uniform distribution; its pdf and how to simulate its distribution
  - Normal distribution; its pdf and how we simulate its distribution. Since the normal distribution is highly applicable in the real world, we shall have some application problems which we will learn how we can solve them using R instead of solving by hand.
  - Chi-Square distribution; how to simulate and solve its problems using R
  - Student-distribution; how to simulate and solve its problems using R
  - Exponential distribution; how to simulate and solve its problems using R
4. Under the discrete probability distribution the learner will know:
  - Binomial distribution: Here we will solve some practical problems using R code.
  - Poisson distributions: We will learn how to solve probability problems of Poisson distribution using R.
  
 5. How to draw samples from the simulated distributions

#### Article quality
  This article aims to make the learner able to solve any probability problem using R software instead of doing so by hand as in practice some problems might be highly challenging to address by hand. So, it will cover the topic in-depth and ensure clarity of the content so that the learner can grasp the content very easily.

#### References
N/A

### PR DESCRIPTION
**Pull request by BejaminNaibei**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6652

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Comment by lalith1403** [comment]
Hey @BejaminNaibei, can you add your author folder name in place of the author placeholder?

**Comment by BejaminNaibei** [comment]
Hey @lalith1403, I  have added the author name.

**Comment by WanjaMIKE** [comment]
Merged #7440 into master

**Pull request merged**
