### PR TITLE
Using Azure Functions and C# to Create Serverless APIs

### LINKED ISSUE #2979: Using Azure Functions and C# to Create Serverless APIs
### Proposed title of the article*
Using Azure Functions and C# to Create Serverless APIs

### Introduction paragraph (2-3 paragraphs):
Azure Functions is a serverless compute tool that makes it simple to run short amounts of code (or "functions") in the cloud. It has the potential to make our development even more fruitful. You will write only the code you need for the task at hand, without worrying about the rest of the program or the infrastructure required to run it.

In this tutorial, I will show the reader how to use Azure Functions to develop HTTP Trigger APIs utilizing Entity Framework Core Layer as an ORM and C# code, as well as a SQL Database for data storage.

### Key takeaways: 
1. Setting up the Azure Function
2. Database Schema and Entity Model
3. Setting up the Connection with SQL Database by using EF Core
4. Initialize Dependency Injection
5. Injecting the DbContext into a function
6. Implementing Functions
7. Testing the APIs using Postman

### References: 
N/A

### PR DESCRIPTION
**Pull request by wanjadeno**
My index file

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2979

### CODE REVIEW

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by wanjadeno** [comment]
hello @paulodhiambo wish to inquire the progress of my article.
Thank you

**Comment by wanjadeno** [comment]
Hi @paulodhiambo what's up with my PR? No updates seen for 10 days

**Comment by hectorkambow** [comment]
@paulodhiambo 
Can we please get a status update on this PR?

**Comment by paulodhiambo** [comment]
@wanjadeno please add explanations of the code snippets you have in the article. At least add comments to the code snippets.

**Comment by wanjadeno** [comment]
Hi, @paulodhiambo 
I have made all the changes that you requested.
Thank you.

**Comment by paulodhiambo** [comment]
@Wachira48 please add your author profile.

**Comment by wanjadeno** [comment]
@paulodhiambo I have added my profile

**Review by paulodhiambo — APPROVED** [review]

**Comment by LinusMuema** [comment]
Hi @wanjadeno 
This is a really great article but I feel like it could really use some `prerequisites`. This helps a user understand what is needed before they go deep into the article. For instance, as I was reviewing, I met some new terms and tech that I could have used before to prepare me as I read through. Please add that then we can merge the article.

cc: @paulodhiambo check the image URLs and file names in future articles. There was a small issue with them.

**Comment by LinusMuema** [comment]
Also, Welcome to section @wanjadeno 
Thanks for joining our community and we hope to see more awesome content from you :rocket:

**Comment by hectorkambow** [comment]
@wanjadeno 

Good afternoon and thank you for submitting your topic to the EngEd program and jumping on your revisions. 
As a rule of thumb - we can only accept articles (pull requests) that are fully polished and complete articles - articles that are ready to be published. 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue). 

Please be sure to go over any edits made by your peer reviewer and our content moderator to improve future articles and reviews - and prevent PR closures. 👍

**Comment by wanjadeno** [comment]
hello @LinusMuema I have added the prerequisites section as you had requested. Thank you

**Comment by LinusMuema** [comment]
Changes received.

**Pull request merged**
