### PR TITLE
Data visualization with tables in React

### LINKED ISSUE #3667: Data Visualization with Tables in React.
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Data Visualization with Tables in React.

### Introduction paragraph (2-3 paragraphs):
Working with tables in React has always been a burden for a very long time now. issue related to the styling, responsiveness, and the proper rendering of data on tables has been encountered by a lot of developers whenever they're trying to render a lot of data onto the UI of a web-application

In this article, we are going to look at an approach that would enable us to properly visualize data on tables with an npm package, called `react-table`. It is a library that focuses on the React Hooks pattern, therefore abstracting the need to manually create or write out HTML table elements. 

### Key takeaways: 
The reader(s) will be able to:

- Create extensively rich tables that would be accessible for people
- Interact with JSON dummy data that would be rendered on the table UI
- Get an understanding of how columns works, how to create an instance of such column with the JSON data that is available.

### References: 
None

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Caleb335**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3667

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Caleb335** [comment]
Hi @WanjaMIKE, kindly review.

Thanks.

**Comment by ahmadmardeni1** [comment]
plagiarism check done ✅

**Review by jerimkaura — CHANGES_REQUESTED** [review]
Hello @Caleb335 

Can you go through your article keenly to ensure it is error-free? You have a lot of unnecessary double-quotes `"` symbols through the article. 

Ping me when you are done.

**Comment by Caleb335** [comment]
Hi @jerimkaura,

Thank you so much for the feedback. I'd let you know when I'm done fixing them.

**Comment by Caleb335** [comment]
Hi @jerimkaura,

I've removed the quotation marks. Kindly review. 

Thanks

**Comment by jerimkaura** [comment]
> Hi @jerimkaura,
> 
> I've removed the quotation marks. Kindly review.
> 
> Thanks

Hello @Caleb335, Unfortunately,y ou undid all the changes I made in the previous review.

**Comment by jerimkaura** [comment]
Whenever you are making a change to the PR, do a `git pull` so that you fetch the latest updates before you push your changes.

**Comment by Caleb335** [comment]
@jerimkaura I did a `git pull origin branch-name` before I pushed my changes.

Let me know what I can do now. Thanks.

**Review by jerimkaura — APPROVED** [review]
Hello, @Caleb335  I hope you are well.

You have a very resourceful article here, but please take not of the following:

1. Avoid contractions in formal writing. For instance instead of `we'll` use `we will`.
2.  Finish all your sentences with a period `.` and every sentence should begin with an upper case.
3. Avoid long wording to make your article concise and enhance readability. For instance, instead of `In this section, we’ll be covering the final steps of this process.` Use, `This section covers this process' final steps.`
4. Be more formal and professional with headings. For example instead of `### Now, unto the Table component itself.` You can use `### The table component`

I have made the corrections for you but take note of the above in your subsequent articles.

**Comment by Caleb335** [comment]
Thank you very much for this feedback @jerimkaura.

I'd put all of them into practice in my consecutive articles.

**Comment by jerimkaura** [comment]
> > > Thank you very much for this feedback @jerimkaura.
> > > I'd put all of them into practice in my consecutive articles.
> > 
> > 
> > Check this [out](https://www.google.com/search?q=i%27d+meaning&oq=i%27d&aqs=chrome.2.0i512j46i512j0i512j46i512l2j0i512j46i512j0i512l3.6665j0j7&sourceid=chrome&ie=UTF-8)
> 
> Wrong context. My bad 🤦🏼‍♂️
> 
> Should be "I will" right?

Yea.

**Comment by Caleb335** [comment]
> > > > Thank you very much for this feedback @jerimkaura.
> > > > I'd put all of them into practice in my consecutive articles.
> > > 
> > > 
> > > Check this [out](https://www.google.com/search?q=i%27d+meaning&oq=i%27d&aqs=chrome.2.0i512j46i512j0i512j46i512l2j0i512j46i512j0i512l3.6665j0j7&sourceid=chrome&ie=UTF-8)
> > 
> > 
> > Wrong context. My bad 🤦🏼‍♂️
> > Should be "I will" right?
> 
> Yea.

Noted with many thanks. 🍷

**Review by jerimkaura — APPROVED** [review]
Hello @Caleb335 

Thank you for the wonderful article. Go over the suggested changes for better articles in future.

**Comment by Caleb335** [comment]
@jerimkaura, I'll take cognizance of all that you have mentioned.

Thank you once again! 😎

**Pull request merged**
