### PR TITLE
K8 Edge App 2022 Hackathon: 'Plagariased Title Search Engine'

### LINKED ISSUE #7559: K8 Edge App 2022 Hackathon: "Loading Tweets From Twitter using NIFI And Running on K8"
**April 11th - 18th 2022**

In this edge-based hackathon, we will focus on Section's [Kubernetes Edge Interface (KEI)](https://www.section.io/docs/explanations/kei/) solution. [KEI](https://www.section.io/kubernetes-edge-interface/) makes many edge clusters appear as a single cluster, enabling developers to quickly and easily deploy applications across a distributed Edge.

To participate in this hackathon, EngEd students are expected to create a true Kubernetes application for the Edge that is deployed using the KEI process.

Review the judging criteria listed below.

Below you will find full details on the hackathon and any requirements.

### Eligibility
Open to all EngEd students (participants can work individually or in teams of EngEd students). **By submitting this issue form you will have successfully signed up and we will reach out with next steps.** 

### Requirements
Once your K8s Edge application is complete and deployed, create a pull request to attach your submission to. 

Please complete and submit the following required sections listed below via a [Pull Request](https://github.com/section-engineering-education/engineering-education/compare) once your project is ready to be submitted. 

- Your Full Name, email, and EngEd author link.

- Project name, brief description of the project, a public URL link to your Edge app, and a short video that explains how your app works and how you deployed it using KEI. 

- The video should (be about 3 minutes) demonstrate your project using KEI. Videos must be uploaded to YouTube or Vimeo and made public.

- Please include a text description of your project, including how the featured tech (KEI) was utilized. Include what you enjoyed about working with KEI, what you didn't, what worked for you, and what didn’t work for you? Any barriers to get started or points of confusion.

- Include all requested materials alongside your Pull Request before the deadline!

- Proofread your project submission and review the judging criteria again to make sure you have addressed all the areas against which we will review your app.

- Test every link included.

- _Submit your project via a pull request on GitHub titled_ "EngEd - K8s Edge App 2022 Hackathon: Your Project Title Here" and **link** this original issue form to your project pull request.

### Prizes
1st prize: $1250
2nd prize: $750
3rd prize: $500

The first 20 participants to complete (and successfully submit) their projects are eligible to receive a complimentary virtual pass to [KubeCon](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/) ($75.00 value). Simply DM us in the EngEd community channel.

The top 3 winning applications will be points of reference at our booth at the KubeCon event mentioned above.

All other projects will receive honorable mentions on our website.

### Judging criteria: 
- The quality of the project (code effectiveness and code clarity) points for creativity and originality.
- Implementation of the Idea: Includes how well and quickly the project was developed and deployed using the KEI process.
- Was the application successfully deployed to the edge using KEI?
- The application functions completely and as described in the description.

### PR DESCRIPTION
**Pull request by jumamiller**

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Did you make booking.com?

**Comment by jumamiller** [comment]
no, just a placeholder..template...will be updating the images!

**Comment by louisefindlay23** [comment]
Glad to see that you managed to get it deployed successfully, @jumamiller. Shame it's just after the deadline. 

Love the homepage design and the project idea is brilliant. How did you find using Vue? Have you had much experience with it, prior to this project? Any particular reason to use Vue 2 over 3? It's a framework, I'm very interested in learning more about.

**Comment by jumamiller** [comment]
Hi @louisefindlay23, I've been using Vue since January when I joined my current place of work for an internship.  

- The reason I chose Vue 2 is due to the problems with the Vue 3,  which is not yet stable enough to support a couple of packages. For instance, it doesn't support Vuetify (from the last time I checked).
- Vue is very easy to use, in this case, I scaffolded this site within 30 mins, which would have not been the case if I used, say Angular.

**Comment by hectorkambow** [comment]
👏

**Comment by hectorkambow** [comment]
Super cool!

**Comment by jumamiller** [comment]
> Super cool!

Thank you, sir.

**Pull request closed without merging**
