### PR TITLE
How to set up Prisma Client Server that uses MongoDB as the database

### LINKED ISSUE #5660: How to set up Prisma Client Server Schema that uses MongoDB as the database
### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

https://www.section.io/engineering-education/authors/rose-waitherero/

#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

How to set up Prisma Client Server Schema that uses MongoDB as the database

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Prisma is an ORM that allows you to write type-safe database schemas. Prisma will enable you to write type-safe database schemas. When setting a database, everything needs to be well set to define what that database will look like. In this case, Prisma abstracts you from writing database queries. Thus you have to make sure you write safe database access schemas.

Prisma supports databases structures such as SQL and NoSQL. This allows you to create an ORM schema for various structured database data. This guide teaches how to set up a Prisma Client server with MongoDB and use it to create an API.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

- Set MongoDB Atlas cloud
- Data modeling using Prisma for a MongoDB database
- Setting up a MongoDB Prisma client
- Connect MongoDB to Prisma client
- Create a MongoDB Prisma REST API 

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

SQL and NoSQL have different data structures. This guide will use Prisma as an ORM to generate schemes for a MongoDB JSON document. The reader will learn how to structure schemas for a MongoDB database. The reader will also be able to connect this prima schema to a MongoDB and create a server that leverages the advantages of running Prisma with MongoDB

Most existing tutorials only have the MongoDB-Prisma connector. This tutorial will still have this as a heading but still, go ahead and create a RESTFUL API that will show the reader how to use this MongoDB-Prisma connector in a typical project (edited) 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Rose-stack**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #5660

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Kindly, correct the sentences showing plagiarism in the attached report. Thanks

[New Scan 5_03 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7856554/New.Scan.5_03.PM.Copyleaks.Report.pdf)

**Comment by katungi** [comment]
Hello @Rose-stack , I'm Daniel. I will be reviewing the article. I am a Prisma Ambassador therefore I am super impressed by the article. I applaud the clear explanations and easy to follow language and flow.

**Comment by katungi** [comment]
Done with the tech review. This article is brilliant. Awesome work @Rose-stack . I believe this article is ready for final review.

**Comment by Kayere** [comment]
Nice article @Rose-stack - Please go through the changes made by @katungi and I to help improve the quality of your future articles. Also, be sure to go through your articles before submitting them for review as this had a couple of typos. Otherwise, great work.

Thank you for the review @katungi.

**Comment by hectorkambow** [comment]
@Rose-stack  

Can you please DM via slack thank you

**Comment by Rose-stack** [comment]
Sure @hectorkambow

**Comment by Rose-stack** [comment]
> Done with the tech review. This article is brilliant. Awesome work @Rose-stack . I believe this article is ready for final review.

Thank you very much @katungi

**Pull request merged**
