### PR TITLE
Added Other Template Files

### PR DESCRIPTION
**Pull request by louisefindlay23**

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Doesn't seem to alter anything so far. It did take a while for the changes to reflect and numerous cache-purging refreshes in the previous PR. Or another possibility is that the Hugo build has errored out but I don't have access to that info. 

Will check the changed pages later to see if this changes.

**Comment by hborrelli1** [comment]
@louisefindlay23 It looks like your author page is experiencing the same issue again: 
image

**Comment by louisefindlay23** [comment]
> @louisefindlay23 It looks like your author page is experiencing the same issue again: 
> 
> image
> 
> 

Yeah. I tried to deploy a fix (this PR) which I thought would resolve it but it hasn't seemed to. 

Not sure why since according to the Hugo docs, the file I added should correspond the template for the page. 🤔

**Comment by hborrelli1** [comment]
I have a feeling that because we have authors as a category, we are getting issues running into using `authors` as a param in the front matter. 

It looks like you might be able to just use a different name in the front matter. Something like `authorRss`. 

In the [rss.xml:19](https://github.com/louisefindlay23/engineering-education/blob/83eca8dd070fb0ed3d0995433072c2e0339c619d/layouts/authors/rss.xml#L19), You would just need to update `{{ if eq .Params.author $a }}` to `{{ if eq .Params.authorRss $a }}`. Have you tried this approach?

**Comment by louisefindlay23** [comment]
> I have a feeling that because we have authors as a category, we are getting issues running into using `authors` as a param in the front matter.
> 
> It looks like you might be able to just use a different name in the front matter. Something like `authorRss`.
> 
> In the [rss.xml:19](https://github.com/louisefindlay23/engineering-education/blob/83eca8dd070fb0ed3d0995433072c2e0339c619d/layouts/authors/rss.xml#L19), You would just need to update `{{ if eq .Params.author $a }}` to `{{ if eq .Params.authorRss $a }}`. Have you tried this approach?

Yes. Unfortunately, the result is that the RSS feed (index.xml) doesn't get generated due to how Hugo renders templates.

> With the way, Hugo builds RSS feeds, [gohugo.io/templates/rss](https://gohugo.io/templates/rss/), this uses a Term in Categories template, `layouts/categories/taxonomy.rss.xml` so Hugo uses the template RSS file to build a new XML file for every author.
> 
> The `content/authors/rss.xml` template file doesn't take effect (Hugo won't generate the `index.xml` page under the author) unless there's a front-matter parameter that matches the folder name above the RSS template file and the same taxonomy in `config.toml` so if I change it something like `rss-authors`, Hugo won't use the RSS Template file and `/engineering-education/authors/{author-name}/index.xml` results in 404 Page Not Found.

I assumed that defining a template for the [Taxonomy List in Categories](https://gohugo.io/content-management/taxonomies#default-destinations) template would override how Hugo displays by default the author page (as a taxonomy) but it doesn't seem to have made any changes. Was there anything in the Hugo build log, @hborrelli1 for 2nd April 9:34 (your time)?

**Pull request merged**
