### PR TITLE
How to Integrate  Real-time  Webcam on a Web Page Using Javascript

### LINKED ISSUE #2628: How to Integrate Real-time Webcam on a Web Page Using Javascript
### Proposed title of the article
 How to Integrate Real-time Webcam to a Web Page Using Javascript

### Introduction paragraph (2-3 paragraphs):
Many websites now include real-time camera integration for purposes such as verification, online calls, and streaming. As a result, this is a useful feature to have on your website or online application.
JavaScript is a scripting or programming language that allows you to implement complex features on web pages — such as displaying timely content updates, interactive activities etc. In this article, we'll be using javascript to integrate real-time webcam functionality on a web page.

### Key takeaways: 
- Understanding the basics of Javascript
- Javascript actions on the browser
- Integration of real-time webcam on a web page

### References: 
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript
https://en.wikipedia.org/wiki/Webcam

### PR DESCRIPTION
**Pull request by Olanetsoft**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
 Fixes #2628

### CODE REVIEW

**Comment by srishilesh** [comment]
@Olanetsoft 

Thanks for the PR.

Will do the review by tomorrow.

**Comment by hectorkambow** [comment]
@Olanetsoft 

👋 Good afternoon.
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.


Also noticing this article is quite short - lets be sure to add extra info not available on other blog and/or official docs. 

👍 
cc @srishilesh 

[How to Integrate Real-time Webcam on a Web Page Using Javascript #2875.pdf](https://github.com/section-engineering-education/engineering-education/files/6803600/How.to.Integrate.Real-time.Webcam.on.a.Web.Page.Using.Javascript.2875.pdf)

**Comment by Olanetsoft** [comment]
Thank you,  I will review and update shortly.

**Comment by Olanetsoft** [comment]
@hectorkambow Updated 😊

cc @srishilesh

**Comment by srishilesh** [comment]
@Olanetsoft 

How's this article different from [this](https://www.geeksforgeeks.org/how-to-integrate-webcam-using-javascript-on-html5/)?

I find almost similar codes - with slight modifications of variables and functions.

At Section, we always strive to publish unique content. It would be great if you could utilize this concept in solving a problem or targeting a different use case altogether. Please brainstorm on this and get back on how this could be improved.

cc. @hectorkambow

**Comment by Olanetsoft** [comment]
@srishilesh thanks for the feedback.

The webcam integration process looks similar almost everywhere because it's same language "JavaScript" , but what is quite different is the mode of explanation and detail step to step guide.

After research, I realise that in as much its JavaScript its kind of similar but I will drill down more on the explanation of what the content entails for better understanding if that's fine @srishilesh ???

**Comment by srishilesh** [comment]
> @srishilesh thanks for the feedback.
> 
> The webcam integration process looks similar almost everywhere because it's same language "JavaScript" , but what is quite different is the mode of explanation and detail step to step guide.
> 
> After research, I realise that in as much its JavaScript its kind of similar because the access to webcam on web document doesn't change(e.g doc object) but I will drill down more on the explanation of what the content entails for better understanding if that's fine @srishilesh ???

@Olanetsoft 

I totally agree and understand.

Anyway, let's get @hectorkambow 's opinion before we proceed.

Thanks.

**Comment by hectorkambow** [comment]
@Olanetsoft 
@srishilesh 

great points both of you - thank you @srishilesh For catching this. 

Thank you @Olanetsoft  for your explanation. 

**If the topic was to build on how we can improve what is out there, then it would be spectacular.** 

We dont want to publish - rehashed ideas or concepts. (or reexplain thing in more words).

Besides just adding more of an explanation - is there any way we could take this article topic to the next level - what is the point of integrating a real time webcam using JavaScript. 

If this topic is out there - we can refer our reader there to get this built - what can we add on top of improving what currently exists out there. 

In order to publish the article - we would need to build on what exists - not simply re-hash or re-explain what is already out there. 

What would be some next logical steps with such a project. 

Hope this helps draw some more value out of the topic before we continue. 

cc @ahmadmardeni1 @louisefindlay23

**Comment by hectorkambow** [comment]
@Olanetsoft 
Just wanted to get a status update on this PR 👍 

thank you

**Comment by Olanetsoft** [comment]
@hectorkambow  I tried to find out more about what has to be added to make this article more relevant, and after doing so, I came up with the idea of adding deployment or dockerizing the project. I'm not sure if I can go ahead with that.

**Comment by srishilesh** [comment]
@Olanetsoft 

I don't think it would be a good idea. Since, dockerizing the project would be just an additional step to the existing work. We already have articles on how to dockerize and deploy applications.

How about using extending this work with WebRTC for peer-to-peer connections? (Just an idea)

For example, two people can communicate using their cameras from 2 different systems - more like Google meet or Zoom for 2 people. Maybe a simpler browser version of it.

This is just my suggestion. Feel free to suggest any new ideas.

Thanks.

cc. @hectorkambow

**Comment by Olanetsoft** [comment]
@srishilesh I will check this out and give feedback soon. Thank you 😊

**Comment by srishilesh** [comment]
@Olanetsoft 

Just noticed that someone else has also worked on this suggestion.

If you're moving ahead with this idea, make sure you don't use the same technologies or see that there is no much overlap in the implementations with [this PR](https://github.com/section-engineering-education/engineering-education/pull/3087).

Informing this ahead, so that your efforts doesn't go in vain.

Thanks.

**Comment by hectorkambow** [comment]
@Olanetsoft I'll be closing this PR to make some room in the queue. 
Please create a fresh PR with the ready to publish article (with the changes that you are making) 👍 
Link this PR and the original Issue as well to keep track.

**Comment by Olanetsoft** [comment]
Okay

**Pull request closed without merging**
