### PR TITLE
Intent Classification with Rasa and Spacy

### LINKED ISSUE #3632: Intent Classification with Rasa and Spacy
### Proposed title of article
 Intent Classification with Rasa and Spacy

### Introduction paragraph (2-3 paragraphs):
Intent classification is the automated categorization of text data based on customer goals. Intent classification uses machine learning and natural language processing to automatically associate words or expressions with a particular intent. For example, a machine learning model can learn that words such as buy or acquire are often associated with the Intent to Purchase.
Intent recognition forms an essential component of chatbots and finds use in sales conversions, customer support. This has been applied in many chatbot systems to engage customers thus knowing the needs of customers. Within a chatbot, intent refers to the goal the customer has in mind when typing in a question or comment.
In this tutorial, we shall use Rasa and Spacy in building our model. 
Rasa is a tool to build custom AI chatbots using Python and natural language understanding (NLU). Rasa provides a framework for developing AI chatbots that uses natural language understanding (NLU). It also allows the user to train the model and add custom actions

### Key takeaways: 
1. What is Intent Classification.
2. Difference between NLU and NLP.
3. Installing Rasa and Spacy.
4. Building our customer-specific model.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by kelvinkimani501**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3632 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by Jethro-magaji** [comment]
I would like to review this one @hectorkambow 
cc @ahmadmardeni1

**Comment by ahmadmardeni1** [comment]
Sure thing @Jethro-magaji

**Comment by ahmadmardeni1** [comment]
plagiarism check done ✅

**Comment by Jethro-magaji** [comment]
Hi @kelvinkimani501
Well done for coming up with such a wonderful article. However, I have some suggestions for you; I noticed there are some grammatical errors in your writing like using the first person plural (We) instead of the 2nd person singular (You) and other typos too. I highly recommend using Grammarly and ProWritingAid extensions to edit your writing if you haven't done so. When you're done editing, let me know to make a final review thanks.

**Comment by kelvinkimani501** [comment]
Hello @Jethro-magaji, I have used Grammarly to make the changes and added your suggestions. Kindly review.
Thanks

**Comment by kelvinkimani501** [comment]
Hello @Jethro-magaji, I have added some more changes, I had not seen the conversations earlier.

**Comment by Jethro-magaji** [comment]
Hi @kelvinkimani501 
Well done for making the changes as requested, and for coming up with an amazing tutorial.

cc @ahmadmardeni1 
This article is ready for final review.

**Comment by WanjaMIKE** [comment]
Merged # 3790 into master

**Pull request merged**
