### PR TITLE
 Sockets programming in PHP

### LINKED ISSUE #3234: Socket Programming in Php
### Proposed title of article
Socket Programming in Php

### Introduction paragraph (2-3 paragraphs):
Every programming language comes with a method for implementing server-client communication. The program uses this method to allow data to be sent between the server and the client. This technique is also available in PHP, as it is in other computer languages. Socket programming is a programming style in which the server and the client are both applications that require a connection to be created between them in order for them to communicate. In terms of PHP, it also allows us to apply the socket programming idea. In this article,you will learn how to use  PHP programming language to perform socket programming.
### Key takeaways: 
1.Socket Class Methods
2.Socket Client
3.Socket Server
4.Simple TCP/1P Server
5Simple TCP/IP Client

### References: 
N/A

### PR DESCRIPTION
**Pull request by fabulousDesigns**
#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3234

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Spring Boot Configuration Basics #3619.pdf](https://github.com/section-engineering-education/engineering-education/files/7086292/Spring.Boot.Configuration.Basics.3619.pdf)

**Comment by fabulousDesigns** [comment]
@ahmadmardeni1 I double-checked my article.

**Comment by ahmadmardeni1** [comment]
30% is very high.
Again, please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[New Scan 10_09 AM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7098117/New.Scan.10_09.AM.Copyleaks.Report.pdf)

**Comment by fabulousDesigns** [comment]
@ahmadmardeni1 My article has been revised and updated.🤞

**Comment by hectorkambow** [comment]
% is still nearly the same. 

[Sockets programming in PHP #3607.pdf](https://github.com/section-engineering-education/engineering-education/files/7101296/Sockets.programming.in.PHP.3607.pdf)


Will be closing this PR - We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/)

**Pull request closed without merging**
