### PR TITLE
Understanding Quality of Service (QoS)

### PR DESCRIPTION
**Pull request by Su-sid**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by Su-sid** [comment]
this fixes #2416

**Comment by Su-sid** [comment]
Hello @collins-a  please continue with your review on this new PR. Sorry for any inconvenience caused.

**Review by collins-a — CHANGES_REQUESTED** [review]
Hey @Su-sid. Thank you for making changes so promptly. However, some of the changes feel a bit rushed. There are a few suggestions from my previous review, that have yet to be tweaked adequately.

For your article to be polished enough for the next stage, take your time to:
1. Have a thought-out prerequisites section.
2. Have a _definition of terms_ section for a number of the acronyms and concepts that are introduced but not defined or covered. This helps not to distort the flow of the article with defining terms mid-point. 
2. Rephrase your introductory paragraph to introduce the article.
3. Add a link to back up QoS enhancing user experience.
4. Rework your conclusion to be more than just a summary. Could be an extra line conveying your own thoughts on the topic, Or what you want the reader to take away. This gives your article more life.
5. Proofread your changes. I notice the file has a lot of duplicated points. Please eliminate those which aren't meant to be on the final submission. Specifically, those that do not reflect the changes that have been made. Plus, note how I had updated the headings from an earlier commit (eliminated roman numbering and asterisks). Any heading that does not maintain this should be eliminated. And, don't forget a Grammarly check when done.

Take your time, then ping me when done. Looking forward to moving to the next stage.

**Comment by Su-sid** [comment]
@collins-a done with the revision.

**Review by Su-sid — COMMENTED** [review]
.

**Comment by hectorkambow** [comment]
@collins-a does this need a plagiarism check ??

**Comment by collins-a** [comment]
Hey @hectorkambow I believe you already did one on the original PR 😃

**Review by collins-a — APPROVED** [review]
@Su-sid thank you for making quality changes and bringing out more of your voice through the changes.

Again, always remember to do a Grammarly check after making any changes. Good luck

**Comment by Su-sid** [comment]
@collins-a  Thank you for reviewing my article. I gained some insights that will help me write better articles.😁👍

**Review by louisefindlay23 — APPROVED** [review]
Final review complete, @Su-sid. 

Great article which I'm sure will be of interest to our readers. I found it interesting and easy to follow even without in-depth networking knowledge. 

Thanks, @collins-a for peer reviewing and prompting for extra depth and detail.

**Pull request merged**
