### PR TITLE
[Duplicate of #6190] - Building a lyrics search app using vanilla JavaScript with OVH API

### PR DESCRIPTION
**Pull request by shegz101**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by shegz101** [comment]
@srishilesh and @WanjaMIKE i have created a new pr and i feel this won't have any issue

**Comment by shegz101** [comment]
@srishilesh thanks for what you said I should d0. I noticed my former PRs were behind by thousands of commits on the section repo.

**Comment by WanjaMIKE** [comment]
It still has the same error @shegz101

**Comment by shegz101** [comment]
it still has the same error! i don't know what is wrong

**Comment by shegz101** [comment]
it still has the same error! i don't know what is wrong

**Comment by shegz101** [comment]
Am still trying to figure out the issue

**Comment by srishilesh** [comment]
@shegz101 

Let me try rendering after setting up Hugo.

I'll try to find out the cause.

**Comment by shegz101** [comment]
@srishilesh Alright, I hope we get the cause of the issue.

**Comment by shegz101** [comment]
@srishilesh Good morning, is there any update. I will try to look into the issue today with my friends that have better experience. Thanks.

**Comment by srishilesh** [comment]
@shegz101 

Let me check and get back to you.

**Comment by shegz101** [comment]
@srishilesh Alright.

**Comment by shegz101** [comment]
@WanjaMIKE @srishilesh is there any suggestion on what can be done. And is it that the codes are not rendering in Hugo, because I have little or no experience at all?

**Comment by shegz101** [comment]
@WanjaMIKE @srishilesh is it that the images don't show when rendered with Hugo. I just committed some changes, help me try to re-render.

**Comment by shegz101** [comment]
@WanjaMIKE @srishilesh I will be closing this Pull request and opening another, I altered some things when I deleted the forked repo and deleted the cloned repo from my local desktop. I would ping you in the new PR.

**Comment by shegz101** [comment]
@WanjaMIKE @srishilesh I just noticed that the URL for the article t is not the same as the name of the folder where all the files for this PR is.

**Comment by srishilesh** [comment]
> @WanjaMIKE @srishilesh I just noticed that the URL for the article t is not the same as the name of the folder where all the files for this PR is.

Yeah. You're right.

Please create another PR and let me know.

Great find.

**Pull request closed without merging**
