### PR TITLE
[API] Building a CRUD API with the Dapper ORM in ASP.NET Core

### LINKED ISSUE #4576: [API] Building and Documenting a CRUD API with the Dapper ORM and Swagger in ASP.NET Core
#### Proposed title of the article
[API] Building a CRUD API with the Dapper ORM in ASP.NET Core

#### Proposed article introduction
ORM stands for Object Relational Mapper(ORM). It could also stand for Object Relational Mapping, which explains the technique that ORMs use. An ORM is usually a library that makes communicating with our database easy. It uses a mechanism that makes our database look like one very big object. ORMs employ [abstraction](https://en.wikipedia.org/wiki/Abstraction_(computer_science)) to ‘hide’ the unwanted details and focus on the very important and basic functionalities. After abstraction, our data is then broken into smaller chunks which are referred to as [models](https://en.wikipedia.org/wiki/Database_model). In this article, we'll be learning how to build a Todo API by using [Dapper](https://dapper-tutorial.net/) to make queries. After development, we will also be documenting our API with swagger.

#### Key takeaways 
After reading the article, the reader should:
- Know what ORMs are and how they work
- Be able to create an ASP.NET Core API project
- Be able to make queries with the Dapper ORM
- Document an ASP.NET core API with Swagger

#### Article quality
This article goes as far as explaining what ORMs are and how they work. It also tells the user about Dapper and why it's a good choice for an ORM. It explains the methods that are provided by Dapper and how they work. It walks the reader through the whole process of creating a Dotnet API project. As a bonus, the user also learns how to document the API with Swagger.

#### References
- https://en.wikipedia.org/wiki/Abstraction_(computer_science)
- https://en.wikipedia.org/wiki/Database_model
- https://dapper-tutorial.net/

### PR DESCRIPTION
**Pull request by olumidayy**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4576

### CODE REVIEW

**Comment by hectorkambow** [comment]
@section-engineering-education/peer-reviewers

is anyone available to jump on this PR ASAP.

Thank you

**Review by paulodhiambo — CHANGES_REQUESTED** [review]
@olumidayy amazing article, just minor changes, then I proceed to tech review,

**Comment by olumidayy** [comment]
Hi, @paulodhiambo . Thanks for the review. I have made the requested changes and pushed.

**Comment by Kayere** [comment]
Hello @Amoh-writer.

 Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.

Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.

Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[[API] Building a CRUD API with the Dapper ORM in ASP.NET Core #5201 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7660403/API.Building.a.CRUD.API.with.the.Dapper.ORM.in.ASP.NET.Core.5201.Copyleaks.Report.pdf)

**Comment by olumidayy** [comment]
Hi @Kayere . Thanks for the review. If the attached report is anything to go by, it shows that a considerable amount of the similarities(about 3%) point to the issue that should be closed by this PR. This is rightly so as I was required to provide an ntroduction to the article in the issue and this was the same intro used in the article itself. 

The other similarities came from the code snippets. More specifically, the similarities came from the imports in the code snippets. It is very common for this to occur if i happen to use the same packages that someone else used in their project. The actual code itself, i.e. everything asides imports, had little to no similarities to other references. I sincerely hope the plagiarism check could be reveis

**Comment by hectorkambow** [comment]
reviewer pinged via slack as well @paulodhiambo

**Comment by paulodhiambo** [comment]
Hello @olumidayy please remove the file  .vscode/settings.json

**Comment by olumidayy** [comment]
Done @Kayere .

**Comment by hectorkambow** [comment]
@paulohiamdo we usually do not need to run TWO plagiarism checks unless the 1st ones was over 30% (typically). 
|

Especially if some were boilerplate code.

**Comment by hectorkambow** [comment]
@paulodhiambo can we get a status on this PR - if any more edits are needed. 
WE WILL be closing the PR 👍

**Pull request merged**
