### PR TITLE
Comparing SQL Delight to Room Database in Android

### LINKED ISSUE #5440: [Android] Comparing the New Database Framework  (SQL Delight) to Room Database in Android
#### Proposed article introduction
In the world of mobile development, databases are often used for local data storage on client devices. One of the options for working with databases for Android projects is the Room library. The Room persistence library provides an abstraction layer over SQLite to allow fluent database access while harnessing the full power of SQLite.

On the other hand we have SQL Delight which is a cross platform SQL library that generates type-safe Kotlin APIs from SQL statements for various relational databases. SQL Delight also provides a multiplatform implementation of the SQLite driver.

It verifies your schema, statements, and migrations at compile-time and provides IDE features like autocomplete and refactoring which make writing and maintaining SQL simple.

In this article, we are going to dive into the strength and weakness of SQL Delight, also we will compare its performance, syntax and many more with the Room database.

#### Key takeaways 
- Understand what SQL Delight is and how it works.
- Features of SQL Delight database.
- Differences between SQL Delight with Room Database.
- Advantages and disadvantages of SQL Delight.
- Understand if SQL Delight is the right choice for multi-table databases with different types of relationships.

#### Article quality
The article will try and bring comparisons of both databases, it will be rich in unique content that will be good for beginner looking the right choice of a database to use in their projects. It will be clear sentences that are concise. Other than the theories, the article will contain some technical parts of implementing the SQL Delight database in Android.

#### References
- SQL Delight Documentation.
- Room Database Documentation.

### PR DESCRIPTION
**Pull request by sheecodes**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5440

### CODE REVIEW

**Comment by Kayere** [comment]
Plagiarism check done ✅

**Review by Ericgacoki — APPROVED** [review]
Nice tutorial @sheecodes! and by the way, thank you for your patience 🤗

**Comment by WanjaMIKE** [comment]
Nice work guys @sheecodes @Ericgacoki

**Comment by WanjaMIKE** [comment]
Merged #5912 into master

**Pull request merged**
