### PR TITLE
Understanding machine learning algorithms and how to Implement them

### LINKED ISSUE #5363: [Machine learning] Understanding machine learning algorithms and how to Implement them
#### Proposed title of article
[Machine learning] Understanding machine learning algorithms and how to Implement them

#### Proposed article introduction
Artificial Intelligence is advancing at a breakneck pace in the field of innovation. Machine learning is used in almost all of the services we use on a regular basis. Machine learning is an area of Artificial Intelligence that deals with the creation and development of algorithms, and it is what allows today's computers to learn. Machine learning is progressively gaining traction and establishing itself as a significant technique in a variety of fields, including health, education, and business.

Machine learning tries to create a system that is automated, improves over time, and can function without the need of code. The machines are fed high-quality data and educated with a variety of techniques. The algorithm to choose is determined by the type of data that has to be automated.

#### Key takeaways
1. What is Machine Learning?
2. Understanding different Types of Machine Learning Algorithms
       - Supervised Machine Learning
       - Unsupervised Machine Learning
       - Semi-supervised Machine Learning
       - Reinforcement Machine Learning
3. Features of Machine Learning
4. The implementation of K-Nearest Neighbors Algorithm

#### Article quality
This article will provide an in-depth knowledge in machine learning algorithms. Since other blog sites only provide documentation for machine learning algorithms, I'll show The reader how to use the K-Nearest Neighbors Method to implement a machine learning algorithm. The article will also be written in an easy-to-understand manner to raise awareness of this open-source library among its users. The article will also be entertaining and expressed in a unique manner.

#### References
N/A

### PR DESCRIPTION
**Pull request by carteblanchemunene**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #5363

### CODE REVIEW

**Comment by hectorkambow** [comment]
@section-engineering-education/content-moderator-team this author has expressed interest in potentially joing the peer reviewer team. 

This pull request will be vetted for quality to guage if a test review is in order. 🚀

**Review by jumamiller — APPROVED** [review]

**Comment by carteblanchemunene** [comment]
@hectorkambow

**Comment by jumamiller** [comment]
@carteblanchemunene #tag with complete message kindly.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by hectorkambow** [comment]
@section-engineering-education/content-moderator-team  

Can we please review & analyze this Pull request? To see if the author can move on to a "test review". 


cc @Kayere @LinusMuema @ahmadmardeni1

**Review by louisefindlay23 — CHANGES_REQUESTED** [review]
@carteblanchemunene, great article. Very informative and easy to read. 

One area I would advise you to improve on is your images. It would be good if you could rename them to be more descriptive (detailing what the image represents), instead of just image1, image2 and so forth. 

This helps both image SEO (to help rank your article in search engines) and will help readers using screen reader technology if you update the alt text also.

**Comment by carteblanchemunene** [comment]
Hello @louisefindlay23 I have updated the requested changes please check.
Thank you.
cc @jumamiller

**Comment by hectorkambow** [comment]
> @carteblanchemunene, great article. Very informative and easy to read.
> 
> One area I would advise you to improve on is your images. It would be good if you could rename them to be more descriptive (detailing what the image represents), instead of just image1, image2 and so forth.
> 
> This helps both image SEO (to help rank your article in search engines) and will help readers using screen reader technology if you update the alt text also.

great feedback 🚀

**Comment by carteblanchemunene** [comment]
hello @louisefindlay23 am done with the requested changes please continue with the final review.

**Review by louisefindlay23 — CHANGES_REQUESTED** [review]
Thanks for making the changes, @carteblanchemunene. 

I noticed the contrast on your hero image is quite poor. It makes the title hard to read and see the image underneath. Please change this or use of our image templates.

**Review by louisefindlay23 — APPROVED** [review]

**Pull request merged**
