### PR TITLE
Kubernetes Cost Optimization Using Autoscaling Methods

### LINKED ISSUE #2625: Kubernetes Cost Optimization Using Autoscaling Methods
### Proposed title of article
Kubernetes Cost Optimization Using Autoscaling Methods 

### Introduction paragraph (2-3 paragraphs):
Running more workloads on the same server instance might seem more cost-effective. But tracking which projects or teams generate Kubernetes costs is hard. Knowing whether you’re getting any savings from your cluster is also a challenge.  But there’s one tactic that helps: rightsizing. The tighter your Kubernetes scaling mechanisms are configured, the lower the waste and costs of running your application.  

One of the strengths of Kubernetes as a container orchestrator lies in its ability to manage and respond to dynamic environments. One example is Kubernetes’ native capability to perform effective autoscaling of resources. However, Kubernetes does not support just a single autoscaler or autoscaling approach. 

In this post, we discuss how to use Kubernetes autoscaling mechanisms and drive cloud costs down.

### Key takeaways: 
1. Horizontal vs. Vertical autoscaling in Kubernetes. 
2. Kubernetes autoscaling methods
3. How each method works
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.
N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by mumbi00**
this fixes #2625

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. :rocket:
Thank you. @mumbi00

**Comment by BrianaNzivu** [comment]
Hey @mumbi00 :wave: 
Briana here.
First things first welcome to Section Eng-Ed. :tada: 
We are happy to have you here.

I have noticed you do not have an author bio and a headshot image and we would like to give you credit for your work.
This is how you can do it:
- Check the author folder under the content folder.
- Create a folder with your name (small caps and use '-' instead of a space).
- Create an index.md which will contain your details. Please refer to this [bio](https://github.com/section-engineering-education/engineering-education/blob/master/content/authors/briana-nzivu/index.md).
- Lastly, in the same folder upload an image of yourself preferably (600x400) and name it avatar.(can be png or jpg)

**Remember to do this on your forked branch.**

In case of any problem, question or clarification do not hesitate to reach out.
I am here to help.

Regards.

**Comment by mumbi00** [comment]
Hi @BrianaNzivu 
What is the status of this article? I think it has taken a lot of time to review.

**Comment by BrianaNzivu** [comment]
> Hi @BrianaNzivu 
> What is the status of this article? I think it has taken a lot of time to review. 

Hey Mumbi👋🏾.
I am done with the review. 
Currently waiting for a plagiarism check to be done.

Cc @hectorkambow

**Comment by BrianaNzivu** [comment]
> > Hi @BrianaNzivu 
> > What is the status of this article? I think it has taken a lot of time to review. 
> 
> Hey Mumbi👋🏾.
> I am done with the review. 
> Currently waiting for a plagiarism check to be done.
Then from then on your article can proceed to the final review stage. 
> 
> Cc @hectorkambow

**Comment by BrianaNzivu** [comment]
> > Hi @BrianaNzivu 
> > What is the status of this article? I think it has taken a lot of time to review. 
> 
> Hey Mumbi👋🏾.
> I am done with the review. 
> Currently waiting for a plagiarism check to be done.
> 
> Cc @hectorkambow

**Comment by BrianaNzivu** [comment]
After the check has been done (hoping you have a plagiarism of 10% and below) your article will proceed to the final review stage.🚀

Regards.

**Comment by hectorkambow** [comment]
plagiarism check done

**Review by BrianaNzivu — APPROVED** [review]
Hey @mumbi00 👋 .
First, I'd like to acknowledge how your article is well written with barely any corrections.
Keep up the good work!

Just two things I'd like to point out:
1. In order to even make your article's review process easier, I'd recommend you cross-check your work using [Grammarly](https://app.grammarly.com/). It is a great tool.
2. Please go through all the corrections I have made in order to avoid them in the coming articles.

That's it! :smile: 
I am done with my review.

Next, a content moderator will do a final review. After that, your article will be published.

Otherwise,
Congratulations on publishing your first article!! 🥳 

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

**Comment by ahmadmardeni1** [comment]
Welcome to Section EngEd and congrats on your first article 🎉 @mumbi00 

Thank you for the review @BrianaNzivu

**Pull request merged**
