### PR TITLE
Fixing author details

### LINKED ISSUE #3562: How to design the logistic map using matlab
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
One of the most challenging topics in science is the study of chaos. As an example of chaos, consider fluid flowing
round an object. If the velocity of the fluid is not very large the fluid flows in a smooth steady way, called "laminar
flow", which can be calculated for simple geometries. However, if the velocity is increased the flow becomes more
complicated, and depends on time and space in a non-trivial way which is essentially impossible to calculate. This
"turbulent" behavior is called "chaos".
The logistics map is a classic example of transition from stable to chaotic behavior as a single parameter changes value. This script plots the semi-stable values of x(n+1) = r*x(n)*(1-x(n)) as r is varied. Historically it has been one of the most important and paradigmatic systems during the early days of research on deterministic chaos. In this article, we will look on how to design logistic map in Matlab

### Key takeaways: 
- Proper understanding of the logistic map.
- Matlab code for logistic map.
- Applications of logistic map.
### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by simonmwaniki**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #3562

### CODE REVIEW

**Comment by hectorkambow** [comment]
This is a duplicate to what old PR @simonmwaniki 

cc @jumamiller

**Comment by jumamiller** [comment]
PR #3979

**Comment by simonmwaniki** [comment]
@hectorkambow PR #3979

**Comment by hectorkambow** [comment]
@jumamiller 
Just following up to see if the ready for final label should be on this one? 🤔  

Or is it still under review?

**Comment by hectorkambow** [comment]
🤔  

Not sure what you mean by article update? Is this not a new article waiting to be published??? @jumamiller

**Comment by jumamiller** [comment]
> thinking
> 
> Not sure what you mean by article update? Is this not a new article waiting to be published??? @jumamiller

Had been published, but with wrong author details!

**Comment by jumamiller** [comment]
There are multiple files for this article, making it hard to update author details!

**Comment by simonmwaniki** [comment]
@jumamiller can we talk through slack... I texted you but you never replied. you can find me @simo kimwani please because i dont understand why you closed the pr

**Comment by hectorkambow** [comment]
@jumamiller  did we ever fix the author details for this PR?

**Comment by jumamiller** [comment]
> @jumamiller did we ever fix the author details for this PR?

I asked the author to open new PR, which we're yet to receive!

**Comment by hectorkambow** [comment]
@simonmwaniki 

Ah I see -

The author reached out to on Sunday:
image

🤔 

cc @jumamiller

**Pull request closed without merging**
