### PR TITLE
How To Build GraphQL APIs with ExpressJS and Typescript

### LINKED ISSUE #4120: [Node.js] How To Build GraphQL APIs with ExpressJS and Typescript
#### Introduction
GraphQL is a query language for APIs and a runtime for fulfilling those queries with existing data. It's an API specification like REST, but with GraphQL, we can use one query to get all we need. Instead of making multiple requests to the server, we can also specify the fields that we need. Say, for example, we have a user model and a posts model, with REST to get the posts made by a user, we first need to get the user then make another request to get posts of a user. Still, with graphql, we can do all of these with one query. We specify that we need posts made by the user alongside the user data. Aside from fetching data, we can also mutate data on the database using mutations.
For example, if the article is based on machine learning, use the following: [Machine learning] Introduction to Machine Learning.
If the article is based on developing an Android application, use the following: [Android] Developing Apps using Android.

#### Key takeaways 
1. What GraphQL is
2. How to build a simple graphql API in express javascript that does not persist data
3. Adding database support
4. Switching to Typescript

#### Article quality
Most articles on graphQL and express do not use Typescript, but being a great fan of Typescript, I'd be explaining how to migrate our Javascript code in this article to Typescript.

#### References
1. [GraphQL Website](https://graphql.org/)
2. [Typescript docs](https://www.typescriptlang.org/)
3. [Express GraphQL](https://www.npmjs.com/package/express-graphql)
4. [Mongoose ODM](https://mongoosejs.com/)

### Conclusion
This article will give you an in-depth guide to what you need to get started with Express, GraphQL and Typescript.

### PR DESCRIPTION
**Pull request by Babatunde13**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4120 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by katungi** [comment]
Hey @Babatunde13,
Your PR seems to be missing the checklist in the description. Could you please take time and fill it in?

**Comment by Babatunde13** [comment]
Hey @katungi, thanks for the feedback. I've updated the description.

**Comment by srishilesh** [comment]
@Babatunde13 

I'll be taking over to review this PR, since @katungi is facing some issues related to git.

On a quick glance at your PR, here are my suggestions:
- Rename these images to a more meaningful name, and update them in the article as well.
- The image path looks incorrect. Please go through the guidelines/refer other articles.
- The code indentation for a few code blocks doesn't look right.
- Ensure you have a hero image of 600x400, and you perform a grammar check.

Please ping me when these changes are done.

Thanks

**Comment by srishilesh** [comment]
@Babatunde13 

Do we have any updates?

If you still need more time, we can close this PR. You can create a new PR with all the required changes.

Let me know ASAP.

Thanks.

**Comment by Babatunde13** [comment]
Sorry for the delay, will make the update today!

**Comment by Babatunde13** [comment]
Hello @srishilesh thanks for your feedback, I've updated the PR to fix all the things you pointed out. As for the indentation issue, the codes are well formatted and indented.

**Comment by srishilesh** [comment]
@section-engineering-education/content-moderator-team 

Can we check for plagiarism on this PR? Waiting for it, before I could start the tech review.

**Comment by Babatunde13** [comment]
Hey @srishilesh I did plagiarism check on the PR already. I guess we're ready for the tech review then!
Thanks 😊

**Comment by srishilesh** [comment]
> Hey @srishilesh I did plagiarism check on the PR already. I guess we're ready for the tech review then!
> Thanks 😊 

@Babatunde13 

Thanks for checking on the plagiarism.

The content moderators team would be running a plagiarism check, just to verify if the score is less than 10%.

**Comment by srishilesh** [comment]
Looks like it's taking time for the plagiarism check.

Let me jump in for the tech review.

**Comment by hectorkambow** [comment]
Plagiarism check done 

cc @section-engineering-education/content-moderator-team

**Comment by srishilesh** [comment]
Working on the final changes.

**Review by srishilesh — CHANGES_REQUESTED** [review]
@Babatunde13 

I've made some major changes to formatting and flow. Make sure to go through them, before you get started with your next article.

Overall, great work!

Moving for the final review.

Thanks.

**Comment by lalith1403** [comment]
Jumping on this one 💯

**Review by lalith1403 — APPROVED** [review]
Refer to the changes made. Overall great work. Easy to read and understand. Thank you :)

**Pull request merged**
