### PR TITLE
Getting started with Kubernetes Clusters

### LINKED ISSUE #2143: Getting started with Kubernetes Clusters
### Proposed title of the article

Getting started with Kubernetes Clusters

### Introduction paragraph (2-3 paragraphs):

A **Kubernetes Cluster** is a dynamic system that places and manages containers, grouped in pods, running on nodes, along with all the interconnections and communication channels working to perform a certain operation. In this article, we will first look at how to install Kubernetes on a Cloud Provider and locally in our machines. We will also look at how to use the Kubernetes Client(`kubectl`)  to check our clusters and a few cluster components available such as the *Kubernetes Proxy, Kubernetes UI,* and *Kubernetes DNS*.

### Key takeaways: 

We will get an overview of:

1.  Installing Kubernetes on a Cloud Provider and locally in our machines
2. The Kubernetes Client(`kubectl`) 
3. Kubernetes Cluster components

### References: 
N/A

### PR DESCRIPTION
**Pull request by munubi254**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2143

### CODE REVIEW

**Comment by lalith1403** [comment]
@zolomohan, I would like to review this if you haven't started yet.

**Comment by zolomohan** [comment]
yeah @lalith1403. Sure, go ahead.

**Comment by hectorkambow** [comment]
[Getting started with Kubernetes Clusters #2207.pdf](https://github.com/section-engineering-education/engineering-education/files/6416196/Getting.started.with.Kubernetes.Clusters.2207.pdf)


@munubi254 

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

**Comment by munubi254** [comment]
@hectorkambow  Thank you, I'll rectify the wording as soon as possible though some flags raised were for Kubernetes commands which one cannot change. How about that?

**Comment by munubi254** [comment]
@hectorkambow I've done some changes. please check

**Comment by lalith1403** [comment]
@munubi254 There are a lot of grammatical errors. Ping me once you have rectified all the errors. There are various tools, such as Grammarly, Hemmingway App, that help with this. Refer to other articles for more information and the standard expected of authors.

**Comment by munubi254** [comment]
@lalith1403 I'm really sorry for that. I've rectified a bit I had forgotten on the first paragraph..the other errors flagged are for Kubernetes commands. Please check.

**Comment by munubi254** [comment]
@lalith1403 @hectorkambow

**Comment by lalith1403** [comment]
> @lalith1403 @hectorkambow 

Will review it today. Thank you.

**Review by lalith1403 — CHANGES_REQUESTED** [review]
Refer to the changes made. there are several convoluted sentences that I am not satisfied with. For example, 
> This option is highly recommended if one is getting started with Kubernetes because it's better to quickly get started with
Kubernetes, learn about it and then learn how to install it in our physical machines. As much as using cloud-based solutions requires us to pay and have an active network connection to the cloud,  the **minikube** tool only creates a *single-node cluster*, which doesn’t demonstrate all aspects of a complete Kubernetes cluster.

This is too lengthy a sentence. I had asked you to consider using online tools to reduce sentence lengths and ensure grammar is spot on. I would ask you to go through the options again, reduce the lengths of sentences and let me know. I have made some changes for your reference.

**Comment by munubi254** [comment]
@lalith1403 I've tried making some fixes. Please check

**Comment by munubi254** [comment]
@lalith1403 Am closng this for conformity with the new repo. My new PR Is at #2360

**Comment by hectorkambow** [comment]
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

**Comment by munubi254** [comment]
@lalith1403

**Comment by hectorkambow** [comment]
great work @munubi254 

awesome intro article - easy to follow along - looking forward to more in depth ones as well 🚀 


cc @lalith1403

**Pull request merged**
