### PR TITLE
Blazor Server-Side Application Using ASP.NET Core To Perform CRUD Operations

### LINKED ISSUE #4790: Creating a Blazor Server-Side Application Using ASP.NET Core To Perform CRUD Operations
### Topic Suggestion
Creating a Blazor Server-Side CRUD Application Using ASP.NET Core

### Writing sample(s): 
https://www.section.io/engineering-education/java-timer-tasks/

#### Proposed title of the article
Creating a Blazor Server-Side CRUD Application Using ASP.NET Core

#### Proposed article introduction
Server-side processing occurs when a page is requested for the first time and when pages are posted back to the server. For example, validation, saving and retrieving data, and navigating to other pages are all examples of server-side processing. 

In this tutorial, we will learn how to make a Blazor Server-Side Application from scratch and perform CRUD operations in it.
The types of CRUD operations we will perform include;
- creating a data list
- reading data from the list
- updating the list
- deleting data from the list.

#### Key takeaways 
After reading through this tutorial, the reader should be able to;
have a better understanding of what CRUD operations are.
be able to create a blazor server-side CRUD application using ASP.NET Core that adds, deletes, and edits data in a blazer server app.
If the reader is a beginner, be able to have a syntax of C# from this article.

#### Article quality
In this article, I will be taking the reader through step by step process on how he or she can be able to create a Blazor Server-Side CRUD Application Using ASP.NET Core and a detailed explanation of what the code he or she writes in each model does.

#### References
N/A

### PR DESCRIPTION
**Pull request by Joesongoma**
This closes #4790

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Plagiarism check is done. @Dawe-7 could you check if this article is similar to https://blog.medhat.ca/2019/06/blazor-server-side-app-with-crud.html

**Comment by Dawe-7** [comment]
> Plagiarism check is done. @Dawe-7 could you check if this article is similar to https://blog.medhat.ca/2019/06/blazor-server-side-app-with-crud.html

@WanjaMIKE, the article might seem similar in a way but the content and code is different from what the author has written.

**Review by Dawe-7 — CHANGES_REQUESTED** [review]
Great article @Joesongoma. Kindly add more content in your conclusion as we move on to tech review. Also, your hero image should be 600x400 pixels. Adjust your other images accordingly because and avoid very large/small images.

**Comment by Joesongoma** [comment]
> 

@Dawe-7 
I will work on it in the course of the day. Thank you.

**Comment by Joesongoma** [comment]
@Dawe-7 
Changes done.

**Review by Dawe-7 — APPROVED** [review]
Awesome article @Joesongoma. Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles. Thank you.

**Comment by Joesongoma** [comment]
@Dawe-7 
Thanks for the feedback and review, I will surely go through it.

**Comment by Kayere** [comment]
Great work gentlemen 🚀.

**Pull request merged**
