### PR TITLE
Ipay mpesa stk push api using python

### LINKED ISSUE #6434: [API] How to implement iPay Mpesa STK push API using python
### Topic Suggestion
[API] How to implement iPay Mpesa STK push API using python

### Writing sample(s): 
https://www.section.io/engineering-education/authors/dianne-sandra/

#### Proposed title of article
How to implement iPay Mpesa STK push API using python

#### Proposed article introduction
iPay is a payment gateway for Africa. It has made it easier for merchants to accept transaction systems such as VISA, Mastercard, Kenswitch, M-Pesa, Airtel Money. They have the following APIs: Customer to Business(C2B), Business to Business(B2B), Business to Customer(B2C) and STK push. In this tutorial we'll be consuming thier STK-Push endpoints. 

STK push is a request that triggers a USSD prompt on a phone. The prompt contains the amount being deducted, account name of the merchant and the pin input field. iPay has made it possible for developers to send the prompt for both M-Pesa and Airtel Money users using a single codebase.

#### Key takeaways 
1. Create STK prompts for M-Pesa and Airtel Money.
2. Query iPay Transactions.
3. Create Hashes using HMAC.
4. Change Python Objects to JSON.

#### Article quality
This article is the only one that explains how to initate iPay STK-push requests for M-Pesa. It also explains how to query transactions made through iPay servers using python. It throughly explains how iPay systems process REST API requests. The code snippets provided are easy to follow and can be plugged into projects.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
1. [iPay Africa Documentation](https://dev.ipayafrica.com/index.html)

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by diannesandra**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6434 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Plagiarism check complete. Please be sure to check for errant formatting such as full stops in the wrong place and grammar such as adding a space before a parenthesis. Also, please rename your file `mpesa-confirm` to have a lowercase file extension.

**Review by mercymeave — COMMENTED** [review]
Grea piece.

Moving to tech review.

**Review by mercymeave — APPROVED** [review]
Great work @diannesandra 

Let us wait for the final review.

**Comment by hectorkambow** [comment]
@section-engineering-education/content-moderator-team 
image

I'll be jumping on this one

**Pull request merged**
