### PR TITLE
[Duplicate of #6445] - How to build a web crawler with Java

### LINKED ISSUE #5668: How to build a web crawler with Java
#### Introduction paragraph (2-3 paragraphs):
A web crawler is a bot or an automated script designed to traverse or explore the world wide web in a specific manner.

This tutorial will guide readers on how to inspect the HTML code base of a web page using the "view-source" mechanism, we'll explore the real-life use cases and application of a web crawler, we'll have a basic understanding of the breadth-first search algorithm of a Graph data structure, as well as the challenges involved when building a web crawler. We'll also build a web crawler that traverses the embedded URL's on a web page. The web crawler we shall build will demonstrate the theoretical knowledge I'll be providing in this tutorial.

#### Key takeaways:
At the end of the article, the reader should be able to:

* Have a thorough knowledge of the uses cases of a web crawler
*  Build a web crawler that suits a broad range of use cases
*  Obtain additional knowledge of the Graph data structure and the bread-first search algorithm.
* Understand the challenges involved with building a web crawler.

#### Article quality
This article will not only focus on the concept of web crawling but by extension, will explore the engineering and data structure involved in building the script. Before pitching this topic, I studied other articles that have been published on this topic. I noticed that there aren't sufficient contents that have been published on this topic, and even those published, all approached the topic from a complex perspective, with some of them applying Java API's that are not beginner-friendly such as database integration, Java Document API and so on. 

This article will be as beginner-friendly as possible and will approach the topic in a way that is applicable in any kind of system. I aim to take it from the granular level of the data structures involved in building a web crawler, extend it to cover the challenges of building a web crawler and ensure that it is understood by Software Engineers of varying levels of expertise.

### PR DESCRIPTION
**Pull request by olu-damilare**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5668

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by olu-damilare** [comment]
Hello @srishilesh, I've made the modifications you suggested in the [previous PR](https://github.com/section-engineering-education/engineering-education/pull/6445).

**Comment by Kayere** [comment]
Plagiarism check done ✅

**Review by srishilesh — APPROVED** [review]
Hey @olu-damilare ,

Good work! Thanks for making the required changes.

However, you must improve on the overall formatting and flow. Make sure to go through my commits carefully to understand how it can be improved.

Moving for the final review.

Thanks.

**Comment by LinusMuema** [comment]
Hi @olu-damilare 

Awesome job on the article. I actually enjoyed reading it.

cc: @srishilesh 💯

**Pull request merged**
