### PR TITLE
[Duplicate of #6828] - Spotting of Passing Objects using Python

### LINKED ISSUE #6679: Spotting of Passing Objects Using Python
#### Proposed title of article

Spotting of Passing Objects Using Python 

#### Proposed article introduction
Spotting of moving objects has become crucial in our lives today. Talking of security, cameras help us a great deal in executing this
function. Other key areas cut across tracking of living organisms and also vehicles in traffic control. 
In this tutorial, we will be performing the identification and recognition of moving objects.
We will be requiring a few tools before carrying on, that is, the laptop's webcam and most of all an external library to be installed
and downloaded which is the OpenCV module. With those at hand, we will be able to tackle our project at hand.

#### Key takeaways 
1. Installation of external libraries
2. Detection of the contours of the object.
3. Capturing of the recognized moving objects.
4. Returning the detected object.

#### Article quality
Unlike other articles, the code will be well explained and not just copy-pasted. But designed in an eccentric way for easier understanding and consumption. Deeply emphasizing the importance and use of the WebCam in relation to OpenCV
#### References
N/A

### PR DESCRIPTION
**Pull request by lizpart**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This closes  #6679

### CODE REVIEW

**Comment by lizpart** [comment]
@srishilesh Created the new PR

**Comment by lizpart** [comment]
This is a duplicate of #6828

**Comment by srishilesh** [comment]
@lizpart 

Thanks for making the requested changes.

On a quick glance, it looks good.

I'll start my tech review tomorrow.

**Comment by srishilesh** [comment]
Starting my final review.

**Comment by lalith1403** [comment]
plagiarism check done ✔️

**Review by srishilesh — APPROVED** [review]
Hey @lizpart ,

Great article.

I've made some major changes to formatting and flow. Please go through them very carefully, before you start writing your next article.

Moving for the final review.

Thanks.

**Comment by LinusMuema** [comment]
Hi @lizpart 

Please go over the changes in the review and my final edits to ensure your future articles are better. Otherwise, great job.

cc: @srishilesh

**Pull request merged**
