### PR TITLE
Advancement Of Swing Framework in Java

### LINKED ISSUE #4112: [Languages]Advancement of Swing Frameworks in Java
#### Proposed title of article

Advancement of Swing Frameworks in Java

#### Proposed article introduction

Swing in Java is an Application Programming Interface (API) for providing graphical user interface elements to Java Programs. It was created mainly to provide more powerful and flexible components than Java AWT (Abstract Window Toolkit). The AWT is still a crucial part of Java, its component set is no longer widely used to create graphical user interfaces. Today, most programmers are using Swing for this purpose.
Swing is a set of classes that usually provides more powerful and flexible GUI components than does the AWT. Simply put, Swing provides the feel and look of the modern Java GUI.
In this article, we will learn all you need to get started with swings in Java.

#### Key takeaways 

1. Learners will have a clear understanding of Lightweight swing components. 
2. Learners will know how swing supports pluggable look and feel.
3. Learners will understand how painting in Swing is done.
4. Learners will understand the concept of event handling.

#### References
N/A

### PR DESCRIPTION
**Pull request by lizpart**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4112

### CODE REVIEW

**Comment by Kayere** [comment]
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.

I will be closing this PR to allow you some time to make the changes.

[Advancement Of Swing Framework in Java #4535 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7459600/Advancement.Of.Swing.Framework.in.Java.4535.Copyleaks.Report.pdf)

**Comment by Kayere** [comment]
@lizpart, you can push your changes. Ping me when you are done so that I can do another plagiarism check.

**Comment by lizpart** [comment]
@Kayere Completed the changes you requested and can have it checked again.

**Comment by lizpart** [comment]
@WanjaMIKE  my article has not been processed for plagiarism hence cannot proceed with further reviews. I was requesting if you could have it checked upon.

**Comment by hectorkambow** [comment]
Plagiarism check done @lizpart 

cc @Kayere 

@BrianaNzivu 

@section-engineering-education/content-moderator-team

**Comment by lizpart** [comment]
@BrianaNzivu  It has come to my attention that this article is at the top of the queue with the rest being ready for final review,  So I was humbly  requesting if you don't mind having it finished up for me.

**Comment by BrianaNzivu** [comment]
> @BrianaNzivu  It has come to my attention that this article is at the top of the queue with the rest being ready for final review,  So I was humbly  requesting if you don't mind having it finished up for me.

Of course... Working on it as we speak.

**Comment by lizpart** [comment]
@BrianaNzivu  Thanks 🤝 for feedback. Am humbled 🙂

**Comment by hectorkambow** [comment]
@BrianaNzivu 

Let us know any next steps (after your review) - if the articles still seems to need extra revisions - lets consider closing to allow the author the proper time to make the required edits outside of the queue. 
👍

**Comment by BrianaNzivu** [comment]
Hey @lizpart 👋 
I do not know why I cant make any edits to your indesx.md file.
Maybe you can delete the current one and upload it again as a new file.


Please ping me when done.

**Comment by lizpart** [comment]
@BrianaNzivu Have already Allowed for edits by maintainers, seems I had not checked it earlier. You may proceed

**Review by BrianaNzivu — APPROVED** [review]
Hey @lizpart  👋 .

The article is a very interesting read. Good job!
Just a few things I'd like to point out:
1.  It is always advisable to submit an article that is well polished. By this, I mean having an article that does not have too many grammatical corrections and functional code. I suggest that you check out our [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) page which has links to various resourceful tools for writing. 
2. Lastly please go through all the corrections I have made so that you can not repeat the same mistakes.

That's it! :smile: 

A final review will be done now by a content moderator.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

**Comment by Kayere** [comment]
Great article @lizpart.
Thank you for the review @BrianaNzivu.

**Pull request merged**
