### PR TITLE
How to share data between a docker container and the host computer 

### LINKED ISSUE #2683: How to share data between a docker container and the host computer
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

One reason docker is superb is the ability to containerize an application without installing additional dependencies on your local computer. Nevertheless, docker runs on a virtualization architecture. This creates an isolated environment for running your application away from the host machine. Docker engine takes the role of assigning resources from the host to the virtualized isolated application. Once such application is containerized, the application virtualized data are isolated from the host. This means when you virtualize an application, all its data will be hosted within the dockerize containers. In this case, the host and the application are running on different infrastructures. At times you may want your virtually containerized application to share data and files directly from the host computer. This blog will teach you how to share data between a docker containerized application and the host computer. We will also go over how to copy files of an existing application and containerize them within the virtual docker containers.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Joakim-gakure**
### Article checklist
"This fixes #2683 

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by Bayler** [comment]
Hello @Joakim-gakure Welcome to the engineering education program, I will be your peer reviewer.

**Comment by Bayler** [comment]
@Joakim-gakure this was a good read. No major revisions. Being your first article, I'm impressed. Please take note of the minor edits I've made so that you don't repeat them in your next article.

However, noted a few things which I want you to include in your article before we can proceed for final review after the Plagiarism check is done:
1. Being a new contributor, I'll need you to include your author profile with your author bio and head shot. The author bio should be named as index.md while your head shot as avatar.png files. Make sure to include the two files in one folder. Rename the folder with your name i.e., joakim-gakure. Finally, add them into this [folder](https://github.com/section-engineering-education/engineering-education/tree/master/content/authors).
2. It is important to add a Prerequisites section for new readers. Also add a Table of contents section with links to their respective headers. Please use this [article](https://github.com/section-engineering-education/engineering-education/pull/2870/files) as a guide.
3. Finally, I need you to an elaborated conclusion section.

**Comment by hectorkambow** [comment]
@Joakim-gakure 

[How to share data between a docker container and the host computer #2860.pdf](https://github.com/section-engineering-education/engineering-education/files/6803511/How.to.share.data.between.a.docker.container.and.the.host.computer.2860.pdf)


👋 Good afternoon - and welcome to the EngEd program.
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

cc @Bayler

**Comment by Bayler** [comment]
@Joakim-gakure Please go over the revisions.

**Comment by Joakim-gakure** [comment]
> @Joakim-gakure Please go over the revisions.

@Bayler, I have updated the file and removes plagiarized lines, unfortunately, I cannot Reddit the Nginx HTML code. Code is provided by the  Nginx server thus I cannot add many changes to it, to remove the few plagiarism flags

**Comment by Bayler** [comment]
> > @Joakim-gakure Please go over the revisions.
> 
> @Bayler, I have updated the file and removed plagiarized lines, unfortunately, I cannot edit the Nginx HTML code. Code is provided by the Nginx server thus I cannot add many changes to it, to remove the few plagiarism flags

@Joakim-gakure You haven't added the author page as requested

**Comment by ninjaginja** [comment]
plagiarism check completed - all good
[2120420-23e945b92f25560d7743-1626986835916.pdf](https://github.com/section-engineering-education/engineering-education/files/6865131/2120420-23e945b92f25560d7743-1626986835916.pdf)

**Comment by Joakim-gakure** [comment]
> > > @Joakim-gakure Please go over the revisions.
> > 
> > 
> > @Bayler, I have updated the file and removed plagiarized lines, unfortunately, I cannot edit the Nginx HTML code. Code is provided by the Nginx server thus I cannot add many changes to it, to remove the few plagiarism flags
> 
> @Joakim-gakure You haven't added the author page as requested. Also, make sure to join our Slack channel (link in your Section's acceptance email) to get updates and to be easily reached.

Hello, @Bayler I have added my Bio to this pull request. Thank you.

**Comment by Bayler** [comment]
@Joakim-gakure are you on slack? It's been so hard to reach you. Please note that revisions that take long to be worked on might warrant a closure of the PR

**Comment by Joakim-gakure** [comment]
> @Joakim-gakure are you on slack? It's been so hard to reach you. Please note that revisions that take long to be worked on might warrant a closure of the PR

Not yet, I haven't joined slack, I will make sure I do

**Comment by Bayler** [comment]
> > @Joakim-gakure are you on slack? It's been so hard to reach you. Please note that revisions that take long to be worked on might warrant a closure of the PR
> 
> Not yet, I haven't joined slack, I will make sure I do
On the Section welcome email, there is a link that will direct you to our slack channel. Use it to join.

**Comment by Bayler** [comment]
> > > @Joakim-gakure are you on slack? It's been so hard to reach you. Please note that revisions that take long to be worked on might warrant a closure of the PR
> > 
> > 
> > Not yet, I haven't joined slack, I will make sure I do

On the Section welcome email, there is a link that will direct you to our slack channel. Use it to join.

**Comment by Joakim-gakure** [comment]
> > > > @Joakim-gakure are you on slack? It's been so hard to reach you. Please note that revisions that take long to be worked on might warrant a closure of the PR
> > > 
> > > 
> > > Not yet, I haven't joined slack, I will make sure I do
> 
> On the Section welcome email, there is a link that will direct you to our slack channel. Use it to join.

Thank you, I will check.

**Comment by Joakim-gakure** [comment]
@Bayler , is everything well set up ?

**Comment by Bayler** [comment]
> @Bayler , is everything well set up ?

So far so good. Just be on the lookout incase we need you to make any changes

**Comment by Joakim-gakure** [comment]
> > @Bayler , is everything well set up ?
> 
> So far so good. Just be on the lookout incase we need you to make any changes

Now ready for the final review round?

**Comment by Bayler** [comment]
> > > @Bayler , is everything well set up ?
> > 
> > 
> > So far so good. Just be on the lookout incase we need you to make any changes
> 
> Now ready for the final review round?

Yes. It's now ready.

**Comment by ahmadmardeni1** [comment]
This is a great tutorial, welcome to Section EngEd, and congrats on your first article 🎉

Great review, thank you @Bayler

**Pull request merged**
