### PR TITLE
[Duplicate] Getting Started with Ray Tracing Algorithm in ML

### LINKED ISSUE #5491: Getting Started with Ray Tracing Algorithm in Machine Learning
### Topic Suggestion
Getting Started with Ray Tracing Algorithm in Machine Learning

#### Proposed title of article
Getting Started with Ray Tracing Algorithm in Machine Learning
#### Proposed article introduction
The most successful image synthesizing technique is the Ray Tracing Algorithm. This technique has a greater ability than other scanline rendering methods to produce a high level of realism virtually. However, the computational cost is higher. In today's digital world, computer graphics are the most basic requirement. 

When we need to create a virtual image that looks very real and is indistinguishable from a regular photograph, we use computer graphics. There are numerous approaches that can be taken in order to accomplish this. One such rendering method is ray tracing. This is used to generate an image by tracing the path of light as pixels in an image plane and simulating its effects when it encounters virtual objects.

#### Key takeaways 
Types of Ray Tracing Algorithm
How Ray Tracing Algorithm works?
Hybrid Ray Tracing Algorithm
A Brief History of Ray Tracing Algorithm

#### Article quality
In my article I'll take the reader vividly through Hybrid Ray Tracing Algorithm and other types of Ray Tracing Algorithm, I'll also give a brief history of it and elaborate how it works. I'll make sure to use simple grammar hence my article will be beginner-friendly

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by LucidRay**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5491 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by LucidRay** [comment]
hello @mbaabuones I've just submitted the duplicate of PR #6601 ......hope it's all good now

**Review by mbaabuones — APPROVED** [review]

**Comment by hectorkambow** [comment]
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.

**Comment by hectorkambow** [comment]
image

**Comment by hectorkambow** [comment]
image

**Comment by hectorkambow** [comment]
@LucidRay  

@mbaabuones 

Is this PR ready for a final review?

**Comment by mbaabuones** [comment]
> @LucidRay
> 
> @mbaabuones
> 
> Is this PR ready for a final review?

@hectorkambow This PR is ready for final review.

**Comment by hectorkambow** [comment]
will be jumping on this one

**Comment by hectorkambow** [comment]
@LucidRay 
This PR was missing a hero image


and the image source - please go through to review any edits made by your peer reviewer or myself. 

cc @mbaabuones please do the same.

**Pull request closed without merging**
