### PR TITLE
How to develop an API architecture(Duplicate PR of #4875)

### LINKED ISSUE #4735: [API] How to develop an API architecture
#### Proposed title of article
How to develop an API architecture

#### Proposed article introduction
Industries have recently experienced enormous growth in the use of mobile applications that are frequently communicating with the backend over the network or web. This has no doubt made use of APIs an important business resource that any organization cannot overlook.
As a result through the use of APIs, businesses have recorded massive digital success. Over the past few years, huge multinational businesses have been using APIs to increase and diversify their channels enhancing the digital revolution. A number of SMEs are also adopting the trend.
So the biggest dilemma arises for business owners on how to develop APIs that suit their needs. The developers have to use specific API architecture which leverages on which API to use for the business. This article will expound more on the same.

#### Key takeaways 
At the end of the article the learner will understand:
- the concept of APIs and their purposes
- what is meant by API architecture and its components
- the core practices and objectives of designing an API architecture
- the key architectural styles of designing the API and several layers of API architecture

#### Article quality
Most of the articles found online are much concentrated with specific API architectural design which does not cover what each developer may require compared to this article which covers several designs

#### References
N/A

### PR DESCRIPTION
**Pull request by kerubo-tech**
This closes #4735

### CODE REVIEW

**Comment by kerubo-tech** [comment]
@mbaabuones The requested changes have been made, kindly continue to review. Thank you
 cc @hectorkambow

**Review by mbaabuones — APPROVED** [review]
@kerubo-tech Thank you for revising the article. Subsequently, ensure your article is ready for publication before opening a PR. Good job!

**Comment by kerubo-tech** [comment]
> @kerubo-tech Thank you for revising the article. Subsequently, ensure your article is ready for publication before opening a PR. Good job!

@mbaabuones Noted with thanks. I will improve in future articles.

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
Overall nice work 🚀

**Pull request merged**
