### PR TITLE
intro-to-deep-learning-using-python

### PR DESCRIPTION
**Pull request by mbuguac**
This fixes issue #4168

### CODE REVIEW

**Comment by mbuguac** [comment]
It is done @WanjaMIKE

**Comment by hectorkambow** [comment]
@WanjaMIKE 
Can we get a status on this PR?

**Comment by hectorkambow** [comment]
Plagiarism check done. 

It would be wise to go over the PDF to see what came up @mbuguac 
[intro-to-deep-learning-using-python #5080.pdf](https://github.com/section-engineering-education/engineering-education/files/7652609/intro-to-deep-learning-using-python.5080.pdf)

**Comment by WanjaMIKE** [comment]
@mbuguac could you resolve the plagiarism report before we proceed. Thanks

**Comment by mbuguac** [comment]
It is all done. Am still waiting on your review.

**Comment by mbuguac** [comment]
Am am requesting that you close this pull request. Have having some challenges. I will request for a reopening when everything is ready. @WanjaMIKE

**Comment by WanjaMIKE** [comment]
What challenges are you facing? @mbuguac

**Comment by mbuguac** [comment]
It's about the machine I was using. It is no longer available.

**Comment by WanjaMIKE** [comment]
Okay

**Pull request closed without merging**
