### PR TITLE
How to Build REST APIs With Typescript Without Any Frameworks (only using the native modules)

### LINKED ISSUE #6313: How to Build RESTful APIs With Typescript Without Any Frameworks From Scratch(only using the native modules)
### Topic Suggestion
Enter topic suggestion here...

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 

https://www.section.io/engineering-education/authors/rose-waitherero/

#### Proposed title of article

How to Build RESTful APIs With Typescript Without Any Frameworks From Scratch(only using the native modules)

#### Proposed article introduction

In most cases, when building APIs with languages such as Typescript, developers use open-source libraries and frameworks such as Express.js, CORS, etc. These libraries are readily available in the NPM registry.

Whenever you use such packages, there is a lot of abstraction as you don't utilize the core functionalities of Typescript code. Your application's low-level logic Typescript code is hidden from you as these packages process and execute vanilla Typescript behind the scenes of your application. This guide will help the reader build RESTful APIs With Typescript Without Any Frameworks From Scratch(only using the native modules).

#### Key takeaways 

- Set up Typescript
- Setting up a simple Typescript HTTP server
- Setting up a CRUD Typescript REST API
- Setting up the API controllers
- Adding the API routes using Typescript 
- Fetch task
- Add a new task
- Update a task
- Delete a task
- Testing the API

#### Article quality

This guide will help the reader build an HTTP API server that runs Typescript at its core. This will help to understand the bare bone of vanilla Typescript. In this case, we will not use any frameworks such as express and cors. We will use native and core modules that leverage the vanilla Typescript.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Rose-stack**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #6313

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by srishilesh** [comment]
Hey @Rose-stack ,

Nice topic. I'm looking forward to read your final article. (I'm new to typescript)

As a beginner, I think when you write articles for building REST APIs, you should be covering the CRUD operations. Doing so, the reader will have better understanding how each method works. I believe you wouldn't have covered the CRUD operations.

It would be great if you can cover the CRUD operations. What do you think?

Also, you should add a GitHub URL containing the source code.

Thanks.

**Comment by srishilesh** [comment]
Hey @Rose-stack ,

Do we have any updates?

**Comment by Rose-stack** [comment]
Hello @srishilesh,  I sent a DM on slack

**Comment by srishilesh** [comment]
Hey @Rose-stack ,

Thanks for your reply via Slack.

I'm posting a few excerpts from our chat - just to let the team know about the conversations:

> However, I had significant challenges while coming up with this. At first, the app runs using the native modules. That means I didn't use any NPM packages, as they are not native, and the app is supposed to run on the vanilla typescript. However, using these NPM packages is excellent. They make your work easier and more efficient by reducing redundant code.
However, based on this tutorial, the goal is to show how typescript works in its purest form and how you may use it without external libraries or frameworks. This is great. However, you will have to write a lot of code that would be provided otherwise by Express and other frameworks. For example, you would have to create a whole database driver from scratch to set up a database. This makes it hard to create this under one tutorial like this.
To still keep the tutorial relevant, I decided to create a basic yet purest API without external libraries. This way, I believe the reader will get a grip of how to get started with vanilla typescript and how to run intermediate-level applications with typescript. 

My reply was:

> Thanks for the reply. It totally makes sense.
Can we add on other API operations too for the REST API you've built? Taking any beginner tutorial on REST APIs would deal with CRUD operations. Since, you've only used native modules, I believe we don't have much articles on the internet.
So, why not cover all the CRUD operations? That way your content would be the best out there on the internet.

As I had replied, it would be great if we add all the CRUD operations to your article. I believe it's just adding and explaining 3 other endpoints.

The reason I've asked is - the current state of the article is a little low on content. I'm suggesting out a few ideas that could help add more value. You may also free to add additional content.

Thanks.

**Comment by srishilesh** [comment]
Closing this PR to allow the author to make additional enhancements to the article.

**Comment by srishilesh** [comment]
Hey @Rose-stack ,

Do we have any updates?

Let me know if you need any help.

**Comment by srishilesh** [comment]
Hey @Rose-stack ,

Any updates?

**Pull request closed without merging**
