### PR TITLE
Building Chat Application with Django Channel 

### LINKED ISSUE #4370: Building Chat Application Using Django Channels
### Introduction

In this article,  we will be developing from scratch a simple chat application by implementing the chat server using Django Channels.  Channels wraps Django’s native asynchronous view support, allowing Django projects to handle not only HTTP but protocols that require long-running connections too like WebSockets, chatbots, and more.

### Keys Take away
1. Introduction to Channels and its concepts
2. Setting up Django project
3.  Configuration of the chat server 
4. Testing the chat app using different browsers.

### Reference
https://channels.readthedocs.io/en/latest/introduction.html

### PR DESCRIPTION
**Pull request by damikanye**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #4370

### CODE REVIEW

**Comment by paulodhiambo** [comment]
@damikanye please change the article directory name form "Building Chat Application with Django Channels" to "building-chat-application-with-django-channel".

**Comment by damikanye** [comment]
Done @paulodhiambo

**Comment by damikanye** [comment]
Plagiarism checking has been done sir @paulodhiambo.

**Comment by WanjaMIKE** [comment]
@paulodhiambo could you compare this PR with https://smazee.com/blog/realtime-chat-app-using-python. I find them quite similar

**Comment by WanjaMIKE** [comment]
Most of the code are similar to the above blo
[New Scan 11_09 AM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7527176/New.Scan.11_09.AM.Copyleaks.Report.pdf)
g

**Comment by paulodhiambo** [comment]
@damikanye I close the article as you fix the plagiarism issue, make sure your content is unique. For assistance, don't hesitate to ping me via slack.

**Comment by damikanye** [comment]
I have reviewed it. Thank you for the corrections.

@paulodhiambo 
cc: @WanjaMIKE

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Comment by LinusMuema** [comment]
Hi @damikanye 

This is a really good article. However, there are some images missing so the article can't be published as it is currently. Also, I am noticing that as you progress with the article, you find new requirements like docker and django. I'd suggest you add a prerequisites section before you dive into the tutorial as this will help readers get prepared before moving on with the article. Then you can remove comments like `Note: you will need docker`.

cc: @paulodhiambo please check on the resources as you go on with the review.

**Comment by damikanye** [comment]
Thank you sir @LinusMuema for the notice. I have added the required section and uploaded the images.

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by LinusMuema** [comment]
Hi @hectorkambow 
Sorry I had already started doing the final review a few mins ago

**Comment by LinusMuema** [comment]
Just merging right now

**Pull request merged**
