### PR TITLE
how to troubleshoot and monitor a database

### LINKED ISSUE #3476: How to troubleshoot and monitor a Database
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction paragraph (2-3 paragraphs):
Database monitoring is the process of examining database performance and resources in order to build and maintain a high-performance and high-availability application architecture.
Databases are at the heart of many organization's most important business procedures. The complexities of applications is increasing, and IT infrastructures are getting increasingly varied. Database troubleshooting that delivers rapid, accurate problem resolution is important for helping IT diagnose problems before they affect end-users, especially with complex applications working across heterogeneous infrastructures.

### Key takeaways: 
- how to monitor a database
- Database monitoring tools
- Database network traffic
- SQL server performance monitoring
- Decrypting an encrypted data 

### References: 
- N/A
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by extravaganza77**
#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #3476

### CODE REVIEW

**Comment by dentonya** [comment]
Hello @hectorkambow requesting to Review this article

**Comment by srishilesh** [comment]
@extravaganza77 

I believe we already have [one such article](https://github.com/section-engineering-education/engineering-education/pull/3523) in the PR queue.

How's yours different from this?

cc. @WanjaMIKE

**Comment by WanjaMIKE** [comment]
@extravaganza77 Kindly, go through this article -`https://github.com/section-engineering-education/engineering-education/pull/3523` and see how you can make it unique. Thanks

**Comment by extravaganza77** [comment]
@WanjaMIKE 
My article will take the reader through a step by step process of monitoring a Database, and list the top most database monitoring tools as oppose to the use of SоlаrWinds  Dаtаbаse  Рerfоrmаnсe  Аnаlyzer  fоr  SQL  Server in PR#3523. Besides, I will offer best guidelines to reduce network traffic for ensuring network quality enhancement.

**Comment by srishilesh** [comment]
@extravaganza77 

Looks good.

PR#3523 talks only steps for installation and setting up Solar winds. So, you may proceed with this article.

On the other hand, the formatting and structure of this article doesn't follow the guidelines. For example:
- The markdown headers for topics are not `###`
- Too much spacing between words
- Extra unnecessary new lines
- Grammar checks

Overall, it needs some changes in formatting and flow.

I would suggest you to take a look at few of my articles [here](https://www.section.io/engineering-education/authors/srishilesh-p-s/). See how I have formatted, what topics I've covered. See the markdown version [here](https://github.com/section-engineering-education/engineering-education/pulls?q=+author%3Asrishilesh+)

Ping me when the changes are done.

Thanks.

**Comment by ahmadmardeni1** [comment]
plagiarism check done ✅

**Comment by srishilesh** [comment]
@extravaganza77 

Please let me know if you've done the suggested changes

**Comment by extravaganza77** [comment]
@srishilesh 
The requested changes are in place. kindly check, thanks

**Comment by srishilesh** [comment]
I'll complete my final review by EOD

**Review by srishilesh — APPROVED** [review]
@extravaganza77 

Great article. It was beginner friendly.

Make sure to go through my commits to understand the changes.

Moving for the final review.

Thanks.

**Comment by WanjaMIKE** [comment]
@extravaganza77 check the numerous changes I have made across the articles. Thanks

**Comment by WanjaMIKE** [comment]
Merged #3675 into master

**Pull request merged**
