### PR TITLE
Getting Started with Recursive Feature Elimination in Python

### LINKED ISSUE #4796: [Machine Learning] Feature Selection with Recursive Feature Elimination (RFE) Algorithm in Python
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

### Topic Suggestion
Enter topic suggestion here...

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Feature Selection with Recursive Feature Elimination (RFE) Algorithm in Python

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Feature Selection with Recursive Feature Elimination (RFE) Algorithm in Python
 Feature Selection is the process of automatically or manually selecting those features which contribute most to the predictive model. The Feature Selection method is a crucial technique because having irrelevant features in a dataset can increase the model's complexity and lower its accuracy. Therefore, it helps us select only those features that are statistically significant for Predictive Analysis. Among various techniques used in the Feature selection, Recursive Feature Elimination (RFE) is one.

### Recursive Feature Elimination
RFE is a Wrapper-based feature selection method that searches for a subset of relevant features from the feature space by starting with all features in modelling and then successfully removing less important features until the desired number remains. This is achieved by fitting the given machine learning algorithm used in the model's core, ranking features by importance, discarding the least important features, and re-fitting the model. This process is repeated until a specified number of features remains.

When the whole model is created, a measure of variable importance is computed. These measures rank the predictors from most important to the least. At each search stage, the least important predictors are iteratively eliminated before rebuilding the model. Features are scored either using the provided machine learning model, such as some Tree-Based algorithms like decision trees or Random Forest, which offers importance scores or a statistical method.

In this article, we shall intuitively cover the principal concepts of the RFE algorithm and later learn how to implement it in python.

#### Key takeaways 
By the end of this tutorial, the reader is expected to know the following.
1. What's the Feature Selection and why is it important.
2. What are different techniques used in the feature selection.
3. What's the Recursive Feature Elimination technique.
4. How does the RFE algorithm work.
5. How to implement the RFE algorithm in python.

#### Article quality
Although this is an implementation article, I'll spend a reasonable amount of time and try to provide the learner with an intuitive introduction to the RFE algorithm that is easy for a beginner to understand. In this article, I will not dive into the implementation session unless the beginners are aware of what they are implementing. In short, this article will not assume learners have prior knowledge of the intuition behind the RFE algorithm as many online articles assume. The coding session will ensure all code snippets are clearly explained.

I believe in presenting the content in this article uniquely in a manner that is of high benefit to learners.

#### References
N/A
### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Madrinmarison**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4796

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Review by mercymeave — COMMENTED** [review]
Hello @Madrinmarison 

This is a very straightforward and interesting article. I love how you did it. :rocket: 

Proceeding to tech review.

**Comment by WanjaMIKE** [comment]
Plagiarism check done.

**Review by mercymeave — CHANGES_REQUESTED** [review]
Hello @Madrinmarison 

Kindly add a valid hero image for your article. THe acceptable formats are png, jpeg, jpg. Zip files are not allowed.

**Comment by Madrinmarison** [comment]
Hello @mercymeave !
The hero image is now updated.

**Review by mercymeave — APPROVED** [review]
Hello @Madrinmarison 

Great article here. Work on any changes made to improve future articles.

**Comment by ahmadmardeni1** [comment]
Good work @Madrinmarison @mercymeave

**Pull request merged**
