### PR TITLE
How to Recover Data from Digital Storage Media using Autopsy

### LINKED ISSUE #5399: [Security] How to Recover Data from Digital Storage Media using Autopsy
#### Proposed title of article
How to Recover Data from Digital Storage Media using Autopsy

#### Proposed article introduction
This article will tackle the common causes of data loss in digital storage media and how data loss can possibly  be avoided. It will further outline the prerequisite precautionary measures to be taken before any data recovery operation is carried out on any digital media.
Finally, it will outline some of the tools used in data recovery and give the reader a walk through the process of data recovery using autopsy as a digital forensics data recovery tool.

#### Key takeaways
At the end of this article the reader should know: 
1. Causes of data loss.
2. Tools used in data recovery.
3. Prerequisites of data recovery.
4. Step by step process of data recovery.

#### Article quality
This article will not only cover a detailed process of data recovery but also give precautionary measures to be taken before data loss incidents and data recovery operation.

#### References
Autopsy.com

### PR DESCRIPTION
**Pull request by RuthAMare**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
`This closes #5399`

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
@RuthAMare please correct the following section. It shows some plagiarism. Thanks

plagi

**Comment by RuthAMare** [comment]
Hi @WanjaMIKE  , the sentences been rephrased.
Thanks.

**Comment by RuthAMare** [comment]
@WanjaMIKE what's the status of this article?👀

**Comment by WanjaMIKE** [comment]
Tech review @RuthAMare

**Comment by LinusMuema** [comment]
Hi @RuthAMare 

Awesome job on the article.

cc: @WanjaMIKE

**Pull request merged**
