### PR TITLE
Getting Started with PHP 7+ without using a framework

### LINKED ISSUE #3092: Getting Started with PHP 7 without using a framework
### Proposed title of article
Getting Started with PHP 7 without using a framework

### Introduction:
In the past times, PHP developers were forced to use frameworks to maintain their projects professionally. Since the introduction of the composer package manager and PHP standards writing PHP code became easier and more manageable.
In this tutorial, we will build a small API project with basic routing, third-party packages, and testing without using a framework. 

The goal will be to create a simple blog API, each post will have an **id**, **title**, and **body**. The user will be able to list, create and view a post. We will use a JSON file as our database, and all the requests or responses will be in JSON format.

### Key takeaways: 
At the end of the tutorial the reader will be able to:
- create and setup a composer
- add logging and routing for the project
- implement the blog API
- add a testing module to the project

### References: 
N/A

### PR DESCRIPTION
**Pull request by lewe01**
The guide briefly covers how to create and setup a composer, adding logging and routing for the project, implement the blog API and adding a testing module to the project.

### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3092.

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by lewe01** [comment]
This closes #3092

**Comment by WanjaMIKE** [comment]
The latest php version is `8`.  This means your article could be obsolete. Could you focus on Php version `8` instead.

**Comment by lewe01** [comment]
> The latest php version is `8`. This means your article could be obsolete. Could you focus on Php version `8` instead.

The tutorial is based on php7 and greater, I tested with the latest php environment. Thank you

**Comment by WanjaMIKE** [comment]
> > The latest php version is `8`. This means your article could be obsolete. Could you focus on Php version `8` instead.
> 
> The tutorial is based on php7 and greater, I tested with the latest php environment. Thank you

okay

**Comment by okeloviolet** [comment]
@lewe01 I'll be reviewing this article.
Cc: @hectorkambow

**Comment by lewe01** [comment]
@okeloviolet Noted with thanks

**Comment by hectorkambow** [comment]
[Getting Started with PHP 7+ without using a framework #3458.pdf](https://github.com/section-engineering-education/engineering-education/files/7080205/Getting.Started.with.PHP.7%2B.without.using.a.framework.3458.pdf)


👋 Good afternoon - and welcome to the EngEd program.
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

**Comment by lewe01** [comment]
@hectorkambow cc @WanjaMIKE The issues highlighted have been fixed. Kindly review them. Thank you.

**Comment by verah-tech** [comment]
@WanjaMIKE Kindly assist to review the article

**Comment by lewe01** [comment]
@WanjaMIKE Kindly assist to review the article

**Comment by WanjaMIKE** [comment]
@lewe01 Sure I will do that by tomorrow. Thanks

**Comment by hectorkambow** [comment]
Overall nice work gents @lewe01 

cc @WanjaMIKE  

Please be sure to review any edits made to improve future articles and reviews. 


@WanjaMIKE please be sure to ping the other CMs to review any "ready for final" that you did the peer review for - for a second set of eyes - and so the PR does not go days without any final review 👍

**Comment by lewe01** [comment]
> Overall nice work gents @lewe01
> 
> cc @WanjaMIKE
> 
> Please be sure to review any edits made to improve future articles and reviews.
> 
> @WanjaMIKE please be sure to ping the other CMs to review any "ready for final" that you did the peer review for - for a second set of eyes - and so the PR does not go days without any final review 👍

@hectorkambow Noted, I will improve on the edits made on future articles.
Thank you. cc @WanjaMIKE

**Pull request merged**
