### PR TITLE
Introduction to WLAN frequency bands

### PR DESCRIPTION
**Pull request by RuthAMare**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by BrianaNzivu** [comment]
Starting grammar review.

**Review by BrianaNzivu — CHANGES_REQUESTED** [review]
Hey @RuthAMare . Great article!
Your article barely needs any changes but I will just make a few grammar corrections. Be on the lookout. Meanwhile, there is just one correction that I need you to make. Do let me know when you are done.
Regards.

**Comment by RuthAMare** [comment]
> Hey👋🏾@RuthAMare . Great job! I really love how your article is already polished even before the review process. Keep up the good job.
> Your article is also very well articulated and just enjoyable to read.
> Aside from that, take note of some of the edits and changes I have made.
> Once again, keep up the good work.

@BrianaNzivu thank you for the dedication to this article.

**Comment by BrianaNzivu** [comment]
> > Hey👋🏾@RuthAMare . Great job! I really love how your article is already polished even before the review process. Keep up the good job.
> > Your article is also very well articulated and just enjoyable to read.
> > Aside from that, take note of some of the edits and changes I have made.
> > Once again, keep up the good work.
> 
> @BrianaNzivu thank you for the dedication to this article. 

You are welcome. Keep up the good work 🌟

**Comment by BrianaNzivu** [comment]
Hello :wave: Ruth, I hope you are well.
As you know, we were working on a new structure for our EngEd Repo, which has led to a slight slow down of article publishing. Everything is almost ready now.
In order to publish your article as soon as possible, please do the following:
- Download the most recent files off this PR (Make sure to pick the latest one with my revisions and edits).
- Delete your article directory from the *articles* folders.
- Do a git pull (take a look at the new structure of the repo after a git pull).
- Upload your article files to the [new *articles* folder inside *content*](https://github.com/section-engineering-education/engineering-education/tree/master/content/articles).
Ping me via Slack or here if you have any problems.

Your patience is really appreciated.

**Comment by RuthAMare** [comment]
> Hello  Ruth, I hope you are well.
> As you know, we were working on a new structure for our EngEd Repo, which has led to a slight slow down of article publishing. Everything is almost ready now.
> In order to publish your article as soon as possible, please do the following:
> 
> * Download the most recent files off this PR (Make sure to pick the latest one with my revisions and edits).
> * Delete your article directory from the _articles_ folders.
> * Do a git pull (take a look at the new structure of the repo after a git pull).
> * Upload your article files to the [new _articles_ folder inside _content_](https://github.com/section-engineering-education/engineering-education/tree/master/content/articles).
>   Ping me via Slack or here if you have any problems.
> 
> Your patience is really appreciated.

Okay, thanks

**Comment by RuthAMare** [comment]
Hello @BrianaNzivu i have done the change, am not sure if it worked as you requested
please let me know if something doesn't work right.

**Comment by hectorkambow** [comment]
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

**Comment by hectorkambow** [comment]
image


@RuthAMare 

I think the Git pull was unsuccessful - see image - only your article files should be on this PR. 

I would try again - by creating a brand new PR - after doing a git pull to your forked repo - then upload your files on a new branch. 👍

**Comment by BrianaNzivu** [comment]
Hey @RuthAMare .
Are you OK?
Do you need any assistance?
If you do so nit hesitate to reach out via slack or to ping me here 🚀

**Comment by RuthAMare** [comment]
> Hey @RuthAMare .
> Are you OK?
> Do you need any assistance?
> If you do so not hesitate to reach out via slack or to ping me here 🚀

yes i do...on my end i don't see any conflicts so i dont know what to correct.

**Comment by BrianaNzivu** [comment]
Hi Ruth.
I know it can be frustrating.
What I can advice you to do is close this PR and just open a new PR of course after a successful git pull. It's way easier. 
Once you open the new PR just reference this PR so that we know it's a duplicate.
And then maybe you can ping me so that I keep track of the PR.

**Pull request closed without merging**
