### PR TITLE
Fix Twitter Meta Image data

### PR DESCRIPTION
**Pull request by hborrelli1**
- Create absolute url so Twitter can display the proper meta image.
- Url created was duplicating the `/engineering-education` portion of the url, so added a `replaceRE` method to remove the duplicate URL section.
- Ran GoLang script to add an Images param to all author profiles front matter. 
- Added Author name to Image alt tag on Author Profiles.

### CODE REVIEW

**Comment by hectorkambow** [comment]
FYI:

@louisefindlay23 
@katungi

**Comment by louisefindlay23** [comment]
Scans fine using one of the OpenGraph meta checkers.

**Review by ninjaginja — APPROVED** [review]
LGTM

**Comment by ninjaginja** [comment]
@hectorkambow we'll likely want to add some docs for the new author image URL parameter. (Harry can advise on the changes.)

**Pull request merged**
