### PR TITLE
How to Work With Customized Axios for Mulitple Servers in Vue 

### LINKED ISSUE #7231: [Languages]How to Work With Customized Axios for  Mulitple Servers in Vue 3
#### Proposed title of article
How to Work With Customized Axios for  Mulitple Servers in Vue 3

#### Proposed article introduction
In this tutorial, I will walk you through the concepts of Axios in Vue 3. The main aim will solely be to teach you everything you need to know about Axios, and how you can customize it to be able to make requests to multiple servers from your Vue application.

By default, Axios is shipped and only make a request to a single server. This is not an ideal situation when it comes to large scale applications, such as banking systems. Normally, these systems would make multiple, concurrent requests to different servers. To achieve this in Vue SPA, we will customize these Axios to be able to make these requests.
#### Key takeaways 
- Understanding the inner workings of the Axios package for Vue.
- Customizing the Axios package to make requests to multiple servers in Vue 3.
- Integrate the Axios in large scale Vue application.
- Deploying a packaged Vue application.

#### Article quality
The main aim of this tutorial is to help Vue developers to build and customize the Axios package to make requests to multiple servers.
This is a unique feature that most tutorials lack and would come in hand for for developers who work in large scale applications with high reusability demands.

> However my google search did not show any results for this topic!

### PR DESCRIPTION
**Pull request by NaomiSeint**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #7231

### CODE REVIEW

**Comment by jumamiller** [comment]
Hi, @WanjaMIKE I'm currently working on this article, I contacted the author on slack to finish the conclusion part. Thank you

**Comment by NaomiSeint** [comment]
Hi, @jumamiller I have fixed a few typos, I'm now updating a few parts then it will be done.
Thank you.

**Comment by jumamiller** [comment]
Hi @NaomiSeint on the store, do we consider Namespace as one of the properties? I can see you listed 5 as the main.

**Comment by jumamiller** [comment]
> Hi @NaomiSeint on the store, do we consider Namespace as one of the properties? I can see you listed 5 as the main.

i.e `namespace: true`

**Review by jumamiller — APPROVED** [review]

**Comment by jumamiller** [comment]
Great work!

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
@NaomiSeint 
Nicely done 🚀 
Be sure to see your live published article on the site (it should be live within 30 mins).

To give your article a boost in page engagement - share it across your social site (linkedin/twitter) and tag the EngEd program so we can also share it and give it some traction as well!

If you have not done so already - consider adding a skill section to your author page. This will go a long way for potential future employers.

**Pull request merged**
