### PR TITLE
[Duplicate] How kerckhoffs principle is applied in cryptography

### LINKED ISSUE #4247: [Security] How Kerckhoff's Principle is Applied in Cryptography.
#### How Kerckhoff's Principle is Applied in Cryptography.
Kerckhoff's state that a cryptographic system should be secure even if everything about the system except the key is publicly known
According to Kerckhoff's Principle, a cryptographic system's security is solely dependent on the secrecy of its keys, and everything else, including the algorithm itself, should be regarded public knowledge. 

#### Key takeaways 
- Understand the state principle of kerckhoff's principle
- Get to know the origin of kerckhoff's principle
- Have an understanding on various fundamental principles of crypto system
- The relationship between Kerckhoff's principle and Shannon's Maxim principle
- Difference between kerckhoff's principle and Security by Obsecurity

#### Article quality
This article aims to explain how to develop secure systems with this kerckhoff's principle which is not covered in most article

#### References
[kerckhoff's principle](http://www.crypto-it.net/eng/theory/kerckhoffs.html)

### PR DESCRIPTION
**Pull request by leence00**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #4247`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by leence00** [comment]
Hello @WanjaMIKE have made the necessary changes and opened an new pr which is a duplicate of this  #5074

**Comment by geoffrey45** [comment]
@WanjaMIKE Are you still reviewing this article?

**Comment by WanjaMIKE** [comment]
@geoffrey45 you can take it up. Thanks

**Comment by lalith1403** [comment]
plagiarism check done ✔️

**Comment by geoffrey45** [comment]
Hello @leence00

After reading your article, it looks like a direct copy of the WikiPedia article: [Kerckhoffs's principle](https://en.wikipedia.org/wiki/Kerckhoffs's_principle).

We don't accept copied content, so I'll be closing this article.

**Pull request closed without merging**
