### PR TITLE
Running Laravel migrations on an existing database.

### LINKED ISSUE #4690: [API] Running Laravel migrations on an existing database.
#### Proposed title of article
Running Laravel migrations on an existing database

#### Proposed article introduction
Let's imagine your company needs to make a change and use Laravel from the raw PHP technology, or it needs to shift from another framework to Laravel. In addition to that, there is an existing database with thousands, if not millions, of records. Would you delete the database first and run fresh Laravel migrations? Or would you create fresh migrations and do some fragile data exportations? You can give up as well and advise the company on the complexity of the issue, right?

All the options given are not suitable and we need a way to carefully run our migrations on the existing tables. In this article, we will learn how to do that without interfering with any preexisting data. We will run our migrations on a live hosted database using a sample table without the need of installing any package.

#### Key takeaways 
1. Running migrations on an existing database.
2. Running the migrate command in scripts rather than the terminal.
3. Protecting fields from mass assignment.

#### Article quality
It will definitely provide more information about running terminal commands in the scripts for the live environment. Additionally, no package will be used.

#### References
N/A

### PR DESCRIPTION
**Pull request by Agusioma**
This fixes #4690

### CODE REVIEW

**Comment by okeloviolet** [comment]
@hectorkambow I'll be reviewing this article.

**Comment by okeloviolet** [comment]
@ahmadmardeni1 please check plagarism.

**Comment by Agusioma** [comment]
Greetings @okeloviole. Please check.

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅
But this article is light on substance - What do you think? @okeloviolet

**Comment by Agusioma** [comment]
Thank you @ahmadmardeni1. I'll add more content by evening.

**Comment by Agusioma** [comment]
@okeloviolet . I have done some changes. Please check

**Comment by hectorkambow** [comment]
@okeloviolet 

Can we get a status update on this PR. 

If it seems to need more edits, revisions, or changes - lets please consider closing the PR to allow the author the proper time to make the required changes.

**Comment by Agusioma** [comment]
@okeloviolet hero image added.🤙🏿

**Comment by okeloviolet** [comment]
@hectorkambow the article is ready for final review.

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
@Agusioma 
Please be sure to do a git pull on your forked repo before submitting your next article. 

I believe your forked repo may not be up to date.

**Comment by Agusioma** [comment]
Noted @hectorkambow. Thank you.

**Pull request merged**
