### PR TITLE
Using ML.NET For Object Detection In WinForms

### LINKED ISSUE #4427: Using ML.NET for object detection in WinForms
#### Proposed title of the article
Using ML.NET for object detection in WinForms

#### Proposed article introduction
Object detection is the ability of a program to be able to detect objects in an image. ML lets the .NET developers to implement this feature by using the ML.NET framework that they can use to create custom ML models using C# or F# without having to leave the .NET ecosystem.

In this article, we shall be looking at how we can implement the same ML.NET framework in a windows forms app to create a C# project that is able to detect objects in an image.

#### Key takeaways 
A better understanding of ML.NET
Understand the basic knowledge of object detection
Be able to create an object detection system using C# in the windows forms app

#### Article quality
Object detection is mainly a concept implemented using python. In this article, we shall be a C# language to implement the same with the ML.NET framework in the windows forms app.

#### References
N/A

### PR DESCRIPTION
**Pull request by GeoffreyKangu**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [X] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [X] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [X] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [X] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [X] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [X] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [X] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [X] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [X] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [X] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [X] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [X] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [X] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [X] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [X] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [X] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4427 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by GeoffreyKangu** [comment]
@M0nicah  
I have fixed plagiarism.

**Review by M0nicah — COMMENTED** [review]
Hello @GeoffreyKangu, awesome article you have here. Just one note, please go through the article and add relevant sub-headings. The article will flow better with sub-headings.

**Comment by GeoffreyKangu** [comment]
@Monicah
I have made the requested changes.

**Comment by LinusMuema** [comment]
Hi @GeoffreyKangu 

Awesome job on the article. Keep it up.
About the code snippets, you can provide a step by step approach to writing articles. You can check other articles on section to see how. 

cc: @M0nicah

**Comment by GeoffreyKangu** [comment]
> Hi @GeoffreyKangu
> 
> Awesome job on the article. Keep it up. About the code snippets, you can provide a step by step approach to writing articles. You can check other articles on section to see how.
> 
> cc: @M0nicah 
I sure will, thanks for the feedback, I will improve on the article.

**Pull request merged**
