### PR TITLE
Null Safety Support for Flutter and Dart

### LINKED ISSUE #3489: Null Safety Support For Flutter & Dart
### Proposed title of article
Null Safety Support For Flutter & Dart
### Introduction paragraph (2-3 paragraphs):
In basic terms, null safety means that a variable cannot have a ‘null' value unless it was started with null. All runtime null-dereference problems will now be shown at compile-time, thanks to null safety. By catching null errors during development rather than at runtime, Null Safety helps you prevent a wide range of issues.

In this article, the learner shall understand all the null safety features and their benefits.

### Key takeaways: 
-What are Null Safety principles?
-What are Nullable and Nonnullable types?.
-When it comes to design principles, what do you mean by "no safety?"
-Unsound null safety.
-Making the use of a null safety easier
-Null-safety migration
-Null-safety migration in Flutter
-Reasons to migrate a Flutter app to null safety
### References: 
N/A

### PR DESCRIPTION
**Pull request by FranciscaNg**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #3489

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Review by BrianaNzivu — CHANGES_REQUESTED** [review]
Hey @FranciscaNg 👋 .

First of all, welcome to Section - EngEd. :tada: 
We are happy to have you here.
Good job on the article. It is a very interesting read.
Just a few changes I need you to make as we continue with the preliminary revisions:
- Each article in Section has its own structure on how it is written. For instance, your article is more of a how-to guide. Please check out this [document](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md) and try and structure your article according to this guide.
- Your article has quite a lot of grammatical mistakes and unclear sentences. You can use 
[Grammarly](https://app.grammarly.com/ddocs/1287976180) to correct it. 
- Please upload a headshot image of yourself for your Avatar image.


In case of any question or help needed please do not hesitate to ping me here :smile:.
Also, notify me when you are done.

Regards.

**Comment by FranciscaNg** [comment]
@BrianaNzivu 
Changes requested are affected. You may have a look, please.

About the avatar, can I use a free one from the websites, please?

**Comment by BrianaNzivu** [comment]
> @BrianaNzivu
> Changes requested are affected. You may have a look, please.
> 
> About the avatar, can I use a free one from the websites, please?

Hey @FranciscaNg .
Sadly you can't. You have to use your personal headshot image.

**Comment by FranciscaNg** [comment]
@BrianaNzivu 
Image changed, thank you.

**Review by BrianaNzivu — APPROVED** [review]
Hey @FranciscaNg :wave: 
Good job!
The article will now go through a plagiarism check.

Be on the lookout in case of any change.

Regards :rocket: .

**Comment by FranciscaNg** [comment]
Thanks

**Comment by ahmadmardeni1** [comment]
I'm a little bit confused here. The similarity score is > 70% but the source is: https://www.gitmemory.com/BrianaNzivu
 @BrianaNzivu

**Comment by FranciscaNg** [comment]
@ahmadmardeni1

**Comment by BrianaNzivu** [comment]
> I'm a little bit confused here. The similarity score is > 70% but the source is: https://www.gitmemory.com/BrianaNzivu
> @BrianaNzivu
> 
> [Null Safety Support for Flutter and Dart#3733](https://github.com/section-engineering-education/engineering-education/files/7216641/New.Scan.9_59.AM.Copyleaks.Report.pdf)

Hey @ahmadmardeni1 :wave: 
I am also very confused. I have no idea what is happening in fact.
Let me try and figure it out on my end, I will reach out ASAP.

Regards.
cc @FranciscaNg

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Comment by BrianaNzivu** [comment]
Hey @FranciscaNg  👋 .
The article is a very interesting read. Good job!
Just a few things I'd like to point out:
1.  It is always advisable to submit an article that is well polished. By this, I mean having an article that does not have too many grammatical corrections and functional code. I suggest that you check out our [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) page which has links to various resourceful tools for writing. 
2. Lastly please go through all the corrections I have made so that you can not repeat the same mistakes.

That's it! :smile: 

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

**Comment by FranciscaNg** [comment]
Thank you @BrianaNzivu 
What about the tech tutorial label?

**Comment by BrianaNzivu** [comment]
This is more of a how-to guide tutorial than a tutorial that is why I have labeled it as an article rather than a tech article.

*A how-to guide is an article that's in-between a software review and tutorial. It's more of a general overview of how to use a technology rather than a tutorial providing in-depth code snippets to accomplish a single goal but is less detailed than a software review and focuses on the practical aspects rather than its history.*

**Comment by FranciscaNg** [comment]
> This is more of a how-to guide tutorial than a tutorial that is why I have labeled it as an article rather than a tech tutorial.
> 
> _A how-to guide is an article that's in-between a software review and tutorial. It's more of a general overview of how to use a technology rather than a tutorial providing in-depth code snippets to accomplish a single goal but is less detailed than a software review and focuses on the practical aspects rather than its history._

Thanks

**Comment by WanjaMIKE** [comment]
@FranciscaNg kindly, check the edits I have made across the article. I had to delete some sentences that were difficult to read.

**Comment by WanjaMIKE** [comment]
Merged #3733 into master

**Pull request merged**
