### PR TITLE
Constructors in kotlin

### LINKED ISSUE #4978: [KOTLIN ] Constructors and Init blocks in Kotlin
#### Proposed title of article
 Constructors and Init blocks in Kotlin

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Effective Kotlin reguires the use of classes we are going to talk about how to Instatiate objects using Constructors and the init Block
 The Constructor will initialize new objects or instances of the class and  we are going to cover the Best practices in object oriented programming

#### Key takeaways 
1. Understanding init block in kotlin
2. How to instantiate objects using constructors 
3. Best practices for object oriented programming(OOP)

#### Article quality
I am going to produce an article that is well understandable by the users making them understand what does the Init block do in Kotlin and when to use the it

#### References
N/A

### PR DESCRIPTION
**Pull request by kamothosimon**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4978

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by kamothosimon** [comment]
@john-amiscaray i have done the reguested changes

**Comment by john-amiscaray** [comment]
@kamothosimon Based on your commits it seems to me that you've removed the file from Git, made changes to it on your local machine, and then added it back and committed it. I'd prefer you to just edit the file directly, not removing it from Git in between because then I can compare what changes you made in your file via Github using the git diff. It helps with the review process so I'd appreciate it if you did that next time

**Review by john-amiscaray — CHANGES_REQUESTED** [review]
@kamothosimon It still doesn't seem to me that you've had your code auto-formatted using IntelliJ. There are still some formatting issues with your code. Let me know if you are stumbling across some difficulties with this because I thought it would be a simple fix for you to do. I'm leaving this for you to do because as a peer reviewer I should expect the author to format their code properly themselves so that I only have to worry about checking that it works properly. I won't be closing this PR however because I don't think doing this should take too long.

**Review by john-amiscaray — CHANGES_REQUESTED** [review]
@kamothosimon I just remembered you are a first-time contributor. As a first-time contributor, you need to add an author bio page in your pull request. You can find some example author bios in the `/content/authors` folder of the repo. This is where you can place your author bio in a new folder. Your new folder would be called `simon-ngaruiya`. Let me know if you have any questions setting it up.

**Comment by john-amiscaray** [comment]
@kamothosimon small thing: please rename your file from `avater.jpg` to `avatar.jpg`. After that, we should be good to go!

**Review by john-amiscaray — APPROVED** [review]

**Comment by john-amiscaray** [comment]
@kamothosimon All seems good. Great job. Just waiting on the final review.

**Comment by hectorkambow** [comment]
image

**Comment by hectorkambow** [comment]
👀 jumping on this one

**Comment by hectorkambow** [comment]
Will be closing this PR as the topic seems widely covered else where - the hero image is also used in other places 🤔  

https://www.google.com/search?q=Constructors+in+kotlin&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8

**Pull request closed without merging**
