### PR TITLE
How to containerize a MySQL based server and PHPMyAdmin/Adminer with docker and run SQL queries

### LINKED ISSUE #2565: Setup a Containerized Docker MySQL Database Server and use PHPMyAdmin or Adminer for Viewing the MySQL Database
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

### Introduction paragraph (2-3 paragraphs):
You can use several relational database management systems (RDBMS) to run SQL queries, such as MySQL PostgreSQL, SQLite SimpleDB, and Elasticsearch. At times it is hectic to set up an SQL server in your local computer. Let's say you are using a Windows environment and you want to run a MySQL database server. In this case, you have download software that supports the RDBMS and Apache server to run SQL commands and access your databases and records, such as WAMP and XAMPP. While installing these environments, something can go wrong, or maybe your computer needs other dependencies and libraries locally installed to support these programs. This makes it hard, especially for a beginner configure, a WAMP server to run SQL queries. Furthermore, it can be hard to specify which versions of MySQL you want to run. You have to download that specific version and reinstall it on your computer.

With docker, things get a little easier. This time you don't need to install all dependencies that you locally need to set up a MySQL server. Docker helps you to containerize software environments so that you can run them as containers. This way, you set a couple of commands that you want your application environment to run on. Then docker will execute these instructions for you, set up that specific environment, and deliver fully packaged and containerized application dependencies and libraries. This allows you to specify things like the version of the MySQL server you want to run.

You don't need to install and configure the MYSQL environment to access databases and records. Docker provides you with images (official software) that you use and run within your docker containers, such as PHPMyAdmin, Adminer, and Sequel Pro (for Mac OS), to access your record database.

When you need to execute SQL queries, you will only set up a dockerize yml file, run a few commands, and docker will set everything ready for you. As a beginner, you can be able to run and use SQL queries in a containerized environment.

In this tutorial, we will dockerize a MySQL Database Server and set up PHPMyAdmin or Adminer to interact with the MySQL Database. In simple words, dockerize means create a docker image (a virtualized instance) of an application.

Whenever you are dockerizing an application, you first need to write a docker-compose file and specify the instances you want to containerize to form your application stack. Let's go ahead and demonstrate how we can create this MYSQL, PHPMyAdmin, or Adminer stack.

### Key takeaways: 

Set up docker and docker-compose
Write docker-compose.yml
Set MYSQL sever
Set and run PHPMyAdmin
Set and run Adminer as an alternative to PHPMyAdmin

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Wachira48**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
This fixes #2565

### CODE REVIEW

**Comment by hectorkambow** [comment]
@Wachira48 
Good afternoon and thank you for submitting your article for publishing. It has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by srishilesh** [comment]
@Wachira48 

Thanks for the PR.

Will do the review by tomorrow.

**Review by srishilesh — APPROVED** [review]
@Wachira48 ,

Amazing article. It's very beginner friendly.

I've made some major changes to the flow and formatting. Make sure to go through my commits.

Moving for the final review.

Thanks.

**Comment by LinusMuema** [comment]
Hi @Wachira48 
I made some minor edits for flow. There was also an issue with the article title and URL. It is preferable to use shorter titles (than the one you had) keeping into consideration the keywords. You need to avoid fluff words like "and", "or", "but". This is important for SEO.
Please take note of that and my changes for future articles. 

cc: @srishilesh

**Pull request merged**
