### PR TITLE
Building a Kubernetes-based solution in a Hybrid Environment by using KubeMQ

### LINKED ISSUE #2612: Building a Kubernetes-based solution in a Hybrid Environment by using KubeMQ
### Proposed title of article
Building a Kubernetes-based solution in a Hybrid Environment by using KubeMQ

### Introduction:
As Kubernetes has become the standard for deploying, managing, and scaling container-based workloads, it has introduced features to allow clusters to exist across multiple clouds, span clouds, and on-premises environments, and even connect clouds and edge computing deployments. 

However, Kubernetes is a platform for deploying applications and isn’t inherently aware of location, topologies, or architectural distribution. While it can provide scalability and connect clouds to the edge, it falls to the application that is built and deployed on Kubernetes to work within that environment.
Requiring a developer to be aware of that level of detail pushes overhead and complexity too far into the development lifecycle. This article will take a look at Messaging Platform abstraction layer to come up with the solution to the above problem.

### Key takeaways: 
In this article the learner will be able to:
- briefly understand the concept of KubeMQ as a messaging platform abstraction layer
- understand how KubeMQ bridges large multiple clusters together in a hybrid environment
- know how KubeMQ supports Edge Computing by bridging information from many hardware devices and build real-time capabilities at the edge

### References: 
N/A

### PR DESCRIPTION
**Pull request by lewe01**
This article covers:

- the concept of KubeMQ as a messaging platform abstraction layer

- how KubeMQ bridges large multiple clusters together in a hybrid environment

- how KubeMQ supports Edge Computing by bridging information from many hardware devices and build real-time capabilities at the edge

### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**

This closes #2612
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by lewe01** [comment]
This solves issue #2612

**Comment by louisefindlay23** [comment]
Thank you for submitting your article for publishing, @lewe01.

Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it.

Thank you.

**Comment by hectorkambow** [comment]
plagiarism check done

**Review by kayere — COMMENTED** [review]
Great article @lewe01.

Just one note, the author details are only required when publishing your first article. Could you please remove them before we proceed to final review. Or, let me know if this is the first time you are publishing your details.

**Comment by lewe01** [comment]
> Great article @lewe01.
> 
> Just one note, the author details are only required when publishing your first article. Could you please remove them before we proceed to final review. Or, let me know if this is the first time you are publishing your details.

@kayere Thank you. It is not my first time contributing to the section eng program, I had previously published two articles with them. During the theme update that was performed recently, my author details could not be found in the repo hence I had to create again.  Kindly confirm.

**Review by kayere — APPROVED** [review]

**Comment by hectorkambow** [comment]
overall nice work @lewe01 

cc @kayere

**Pull request merged**
