### PR TITLE
[Duplicate of #5147]: Saving and Loading Stacked Ensemble Classifiers in ONNX format in Python

### LINKED ISSUE #5060: [Machine learning] Saving and Loading Stacked Ensemble Classifiers in ONNX format in Python
### Topic Suggestion

[Machine learning] Saving and Loading Stacked Ensemble Classifiers in ONNX format in Python

#### Proposed article introduction
Stacked ensemble models are learners that increase predictive performance over stand-alone learners by combining the results of two or several models and running them through a meta-learner. The stacked models are different (not a single type), unlike in bagging methods (just decision trees) and each of the model in the stack does not correct the predictions of the previous ones as it happens in boosting.

Saving this type of a model in ONNX format and using it in production can prove challenging as this scenario is not adequately documented.

ONNX is an open source format for deep and traditional machine learning developed by Microsoft that has a unified schema for saving models despite the library they were developed in. Launched in December 2017, it gives data scientists and Machine learning engineers a way to persist models without worrying about platform inconsistencies and library version deprecation.

#### Key takeaways 
In this article, the reader will learn how to:
  - install ONNX and onnxruntime
  - determine the ONNX input initialtypes 
  - serialize and save a stacked ensemble to ONNX format
  - load it to production using an Onnx runtime Inference session.

#### Article quality
Serializing stacked ensemble models in ONNX format and using it in production can prove challenging as this scenario is not adequately documented by the library maintainers.
The documentation is not friendly to beginners, thus a step-by-step article would be significantly helpful.

#### References
- [Scikit-Learn ONNX Introduction](http://onnx.ai/sklearn-onnx/introduction.html)
- [ONNX installation guide](https://pypi.org/project/onnx/)

### Conclusion
NA

### PR DESCRIPTION
**Pull request by iannjari**
Created: /content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
This article gives a tutorial on Saving and Loading Stacked Ensemble Classifiers in ONNX format in Python
Image: /content/articles/save-and-load-stacked-ensembles-in-onnx/index.md

Added Author Profile: /content/authors/ian-njari/index.md
Avatar: /content/authors/ian-njari/avatar.jpg

Added Hero Image: /content/articles/save-and-load-stacked-ensembles-in-onnx/hero.png

This closes #5060
Made corrections as suggested by @srishilesh  in PR #5147 

cc @hectorkambow

### CODE REVIEW

**Comment by srishilesh** [comment]
Jumping on this one for tech review.

**Comment by hectorkambow** [comment]
@srishilesh 
Thank you - lets take a look at the recent changes provided.

IF any other revisions are needed - lets provide some guidance on how to get the article up to par - and CLOSE the PR. To allow the author the proper time to make any and all needed corrections.

This is a duplicate PR - if any more changes were needed (in general) we should close the PR immediately, especially if its a duplicate PR (generally there are always exceptions).

**Comment by srishilesh** [comment]
Apologies for the delay, will complete the review by tomorrow.

**Comment by iannjari** [comment]
Thanks @srishilesh , it's appreciated.

**Comment by iannjari** [comment]
> Apologies for the delay, will complete the review by tomorrow.

@srishilesh 👀

**Comment by srishilesh** [comment]
> > Apologies for the delay, will complete the review by tomorrow.
> 
> @srishilesh 👀

@iannjari 

Thanks for reminding me about it. Somehow, got carried away with reviewing other PRs.

Starting my final review now.

**Review by srishilesh — APPROVED** [review]
@iannjari 

I've made some major changes to formatting and flow.

Make sure to go through my commits, to understand them.

Moving for the final review.

Thanks.

**Comment by iannjari** [comment]
> @iannjari
> 
> I've made some major changes to formatting and flow.
> 
> Make sure to go through my commits, to understand them.
> 
> Moving for the final review.
> 
> Thanks.

Thank you @srishilesh.
I have noted the changes you made RE: punctuation, flow and paragraph formatting for future articles.

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
