### PR TITLE
How to use Modular patterns in Node.js 

### LINKED ISSUE #1968: How to use Modular patterns in Node.js
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

How to use Modular patterns in NodeJS

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

When building applications, you don’t write all your code in one single file. First, this would very hard to manage. This been a large application, it would be very hard for a developer to come back to this code and refactor or extend the application functionalities. However, you can break down this complex application into small reusable parts.

Typically, what developers do is that an application is divided into several logical files. Each file has a different bit of code with certain functionality. This way, it will be easier to maintain your codebase because each file has less code to accomplish a specific task. It is easier to debug right and share the code do another developer, this easier maintenance.

This concept is common in most programming languages. The concept is called modularity (Modular patterns). In this case, every single file is a module. Let’s say, for example, you are creating a calculator application. In this case, you can have a file that handles addition. Another file that handles substation functionality. Each file has a specific arithmetical task.

Modular patterns can be used to export these files to the main file. This pattern can be implemented in several ways, but that depends on the modular programming paradigm of the host programming language.

In Node.js, the concept of Modular patterns has additional features that go beyond the regular module (file) pattern. The Node.js modular functionality can be used to import own external files, core Node.js modules, and NPM modules. This tutorial will focus on creating modules, exporting and importing them to different files using Node.js.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

How to create a module
Export functions and objects
Exports vs. module.exports 
A use-case of Node.js NPM module (library)

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Wachira48**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1968

### CODE REVIEW

**Comment by Wachira48** [comment]
fixes  #1968

**Review by srishilesh — APPROVED** [review]
Hey @Wachira48,

Welcome to EngEd community!

Wonderful article. It was very beginner friendly. And, I learned a lot about modularizing codes.

There were very minor changes to your article. I have made changes to it. Make sure you go through them, to understand and improve on your future articles.

Please add your bio and a headshot image under `/authors` directory. Check out the resources page for further information.

Also, add a `hero` image of dimensions 600x400. You can download images from Unsplash, and resize it using [Pixlr](https://pixlr.com/e/).

Let me know when they're done, we can move on to the final review.

Reach out to me, in case of any questions.

Thank you.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by srishilesh** [comment]
Hey @Wachira48 ,

Any updates?

**Comment by srishilesh** [comment]
Hello 👋 @Wachira48 
As you know, we were working on a new structure for our EngEd Repo, which has led to a slight slow down of article publishing. Everything is almost ready now.

In order to publish your article as soon as possible, please do the following:

- Download the most recent files off this PR (Make sure to pick the latest one with my revisions and edits).
- Delete your article directory from the articles folders.
- Do a git pull (take a look at the new structure of the repo after a git pull).
- Upload your article files to the [new articles folder inside content](https://github.com/section-engineering-education/engineering-education/tree/master/content/articles).

Ping me via Slack if you have any problems.

**Comment by Wachira48** [comment]
I will submit them today.

**Comment by Wachira48** [comment]
@srishilesh, I have submitted my bio, a headshot image and a hero image

**Review by srishilesh — APPROVED** [review]
Hey @Wachira48,

Thanks for making the changes. The article looks really polished now.

Moving this article for the final review.

Thank you.

**Comment by hectorkambow** [comment]
Article was merged (published) but our website is still being updated on the backend - which is why it is not showing yet - we are working asap to get it up. 👍

thank you v much for your patience .

**Pull request closed without merging**
