### PR TITLE
Effectiveness of SVM in medical data analytics

### PR DESCRIPTION
**Pull request by slynn22**
#### Formatting and structure checks
- [✔ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [✔ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [✔ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [✔ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [✔ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ✔] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ✔] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ✔]** Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [✔ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ✔] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [✔ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ✔] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [✔ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [✔ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ✔] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [✔ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

### CODE REVIEW

**Comment by slynn22** [comment]
@collins-a you checked on my article some months ago, would you mind checking on this?

**Comment by slynn22** [comment]
@collins-a thank you so much. If you know anyone who can check on such articles kindly ask them to. Thank you

**Comment by BrianaNzivu** [comment]
Hey @collins-a 👋 
Can I proceed with the review?

cc @slynn22

**Comment by collins-a** [comment]
> Hey @collins-a 👋 
> Can I proceed with the review?
> 
> cc @slynn22 

Hey @BrianaNzivu of course, go right ahead

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Comment by BrianaNzivu** [comment]
Hey @slynn22 👋 . Which issue does this article close? Please link it.

**Comment by slynn22** [comment]
it closes #6229

**Review by BrianaNzivu — APPROVED** [review]
Hey @slynn22  👋 .

Very good job on the article. It is a very interesting read 👏 . 
Just a few comments;
- Improve your sentence structure and arrangement. It is causing clarity issues in your article.
- Please go through ALL the corrections I have made so that you can not repeat the same mistakes.

That's it! :smile: 

A final review will be done now by a content moderator.
Otherwise, congratulations on publishing your article🍾.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

**Comment by slynn22** [comment]
Thank you so so much. I appreciate your response and looking forward to
more engagement. I highly appreciate it

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
