### PR TITLE
Writing a Flutter Web Plugin 

### LINKED ISSUE #3384: Writing a Flutter Web Plugin
### Proposed title of article
 Writing a Flutter Web Plugin

### Introduction paragraph (2-3 paragraphs):
Flutter's web support provides the same mobile and online experiences. You can now create apps for iOS, Android, and the web using the same codebase, thanks to the flexibility of the Flutter framework. Because it is the same Flutter framework and the web is merely another device target for your project, you can convert current Flutter code written in Dart into a web experience. In addition to translating Dart to JavaScript, adding web functionality to Flutter requires creating Flutter's fundamental graphics layer on top of conventional browser APIs.

Aside from the Android and iOS plugins, I'll be utilizing a feasible technique for adding web support to a Flutter plugin in this article.

### Key takeaways: 
-How to add web support to a Flutter plugin.
-How to refactor your plugin.
-How to register the plugin.

### References: 
N/A

### PR DESCRIPTION
**Pull request by FaithZawadi**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #3384 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by FaithZawadi** [comment]
@jerimkaura @WanjaMIKE @hectorkambow 
I have done the corrections

**Comment by nancymumbimaina** [comment]
Duplicate of #3557

**Review by jerimkaura — CHANGES_REQUESTED** [review]
Hello @FaithZawadi 

In the previous PR, Mike told you to explain your snippets well. PLease do so so that we finalize on this PR

**Comment by FaithZawadi** [comment]
@jerimkaura you may have a look. 
Done.

**Review by jerimkaura — APPROVED** [review]
Thank you for making the changes @FaithZawadi 

Hello @WanjaMIKE, Would you please give this PR a final review?

**Comment by FaithZawadi** [comment]
@WanjaMIKE just did some changes. You may have a look.
Thank you.

**Pull request merged**
