### PR TITLE
Create a Next.js Blog App with TypeScript, Apollo Server and FaunaDB

### LINKED ISSUE #4975: Create a Next.js Blog App with TypeScript, Apollo Server, FaunaDB and Deploy to Versel
#### Proposed title of article

Create a Next.js Blog App with TypeScript, Apollo Server, FaunaDB, and Deploy to Versel

#### Proposed article introduction

Fauna DB is a hosted cloud database that is entirely serverless. It's extremely fast and scales infinitely in the cloud. Fauna DB lets you manage your database data from its web interface or the command line. It has the ability to handle complex data modeling use cases.

SQL is preferred for its security and data consistency, and NoSQL is preferred for its flexibility, scalability, and productivity. Fauna DB is a hybrid of these two. It combines the safety and security of SQL with the productivity and scalability of NoSQL.

This guide will Fauna DB model the data relationships and create an API that you can use to connect to your frontend application. We will bootstrap Next.js with TypeScript, create a blog app that leverages the serverless Fauna DB, and then deploy the application using the Next.js Versel.

#### Key takeaways 

- Fauna DB Basics
- Next.js Basics
- Create Fauna DB backed API
- Create the Next.js Fronted
- Run the Next.js Fauna DB blog app

#### Article quality

This article shows the reader how to create a scalable application using Next.js and Fauna DB. In this guide, we will use Typescript as the base language. Finally, deploy the entire application using Versel.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Catemacharia**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4975

### CODE REVIEW

**Comment by hectorkambow** [comment]
plagiarism check done

**Review by Dawe-7 — APPROVED** [review]
Nice article @Catemacharia. Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles. Thank you.

@Kayere, this article is ready for final review.

**Comment by hectorkambow** [comment]
Jumping on this one

**Comment by hectorkambow** [comment]
🚀  

Overall very easy to follow along 👏

**Pull request merged**
