### PR TITLE
Managing Work Queues With Beanstalk and Supervisor on Ubuntu 20.04 with Laravel 8 

### LINKED ISSUE #6212: Managing  Work Queues With Beanstalk and Supervisor on Ubuntu 20.04 with Laravel 8
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community memebers to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

**NOTE: Any topic suggestion copied/taken/modified from YouTube may Lead to a permanent ban from the community.**

### Topic Suggestion
Enter topic suggestion here...

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
Managing  Work Queues With Beanstalk and Supervisor on Ubuntu 20.04 with Laravel 8

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Building extensive applications sometimes come with some additional problems. These may include operations to upload CSV files which may take time to parse and save into your database.  

The solution to such problems is using the Laravel queued jobs that process these operations in the background.

In this tutorial, I'll teach you everything you need to know about Laravel queues and later on introduce the concepts of [beanstalk](https://beanstalkd.github.io) and Supervisor in Ubuntu 20.04.

Beanstalk is a simple, fast work queue. 

It allows you to run time-consuming tasks asynchronously, such as sending emails, connecting to external APIs, or processing images. 

By doing so, you will reduce your web app latency. In addition, laravel provides out-of-the-box support for beanstalkd.

#### Key takeaways 
- - Understanding the concepts of beanstalkd
- Learning how to integrate the Laravel work queues with beanstalkd
- Running the application with Supervisor on ubuntu 20
#### Article quality
In this article, we discuss the concept of Beanstalk on the latest version of Ubuntu. This is very distinct since the installation process is quite different from previous versions.

Managing queues with Beasnstalkd is very rare since we mostly use Redis. So this article gives people who prefer beanstalk an opportunity to understand this new approach.

Lastly, this article focuses mainly on the Linux environment, which of course provides access to the Supervisor for ease of installation and setup.

> Unlike the existing light article on this topic, this tutorial will give readers a more in-depth explanation on why we use queues with beanstalkd and how we can configure the same without on virtual machines without interfering with the local machine, hence very unique.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by roselyneodero**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes
This closes #6212

### CODE REVIEW

**Comment by jumamiller** [comment]
Hi, since this is your first article, kindly upload your author details! Kindly reach out for any help!

**Comment by roselyneodero** [comment]
Hello, I have added the required files, kindly let me know if you need anything else, thanks.

**Comment by roselyneodero** [comment]
Hello I have updated the version of Laravel to 9.

**Review by jumamiller — APPROVED** [review]

**Comment by lalith1403** [comment]
plagiarism check done ✔️

**Comment by hectorkambow** [comment]
👏

**Comment by hectorkambow** [comment]
@roselyneodero nicely done. 

Be sure to see you published work live on the site. 

I'd also recommend to add to your skills sections (this will go a long way with potential employers).

**Pull request merged**
