### PR TITLE
PID controllers using Matlab

### LINKED ISSUE #2292: PID controllers in Matlab
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Introduction:
The performance of a system is usually on basis of a few parameters. These parameters are of the time domain as well as the frequency domain. 
PID controller is an acronym that stands for proportional integral derivative. These acronyms form the basis of the controllers. This means that we have Proportional controllers, Integral controllers, and derivative controllers. When all these modes are combined, we have the PID controllers. It is used to makes some factors such as temperature, pressure, and flow constant. It uses a control loop feedback to ensure that the output wanted is what you get. A controller can are the system's response modifiers. They come in various forms such as standalone units or PLC programming.
In this tutorial, we will see how to use the Matlab `PID()` function and the various effect of changing the parameter Kp, Ki, and Kd. This will help us understand what is going on in the controller.

### Key takeaways: 
- What PID controllers are and the functions.
- How the PID controllers work.
- Understand the program behind the controllers.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by jumapaul**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2292

### CODE REVIEW

**Review by srishilesh — CHANGES_REQUESTED** [review]
@jumapaul 

Good work!

I've suggested some major changes after reviewing first half of the article. This article is very technical and not very beginner friendly. Moreover, the article lacks clarity, and needs to be refined a lot. 

You must write articles that are easier to understand, and very beginner friendly.

Regarding the code snippets, use meaningful variable names - the names looks confusing (Transfer function -> tf). Before writing code, state the objectives of that particular code snippet, and add inline comments.

Finally, perform a grammar check.

Let me know when all these changes are done.

Thanks.

**Comment by jumapaul** [comment]
@srishilesh requested changes made.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by srishilesh** [comment]
@jumapaul 

Thanks for the changes.

Could you please add a hero image of size 600x400?

**Comment by jumapaul** [comment]
@srishilesh requested change made

**Review by srishilesh — APPROVED** [review]
@jumapaul 

Thanks for making the changes.

Please make sure to go through my commits to understand and improve on your future articles.

Also, from next time make sure to use proper variable names (not shorthands) - the variable name must be self-descriptive.

Moving for the final review.

Thanks.

**Pull request merged**
