### PR TITLE
A REST API built with Golang without any frameworks, only using the native modules

### LINKED ISSUE #6666: A REST API built with Golang without any frameworks, only using the native modules.
### Writing sample(s): 

https://www.section.io/engineering-education/authors/joakim-gakure/

#### Proposed title of article

A REST API built with Golang without any frameworks, only using the native modules.

#### Proposed article introduction

I found this issue "[How to Build RESTful APIs with Typescript Without Any Frameworks from Scratch (only using the native modules)](https://github.com/section-engineering-education/engineering-education/issues/6313)". It gave me an idea that I can apply the same using the Golang programming language.

Go is a fast-growing language among developers. Its popularity is still growing and unshaken. Golang ecosystem has a tone of native libraries. However, it has third-party libraries that developers can still choose to use.

When creating Rest API with go, you might choose to use libraries such as Gorm, Go fiber, Gin, fasthttp, etc. On the same, you can still combine this with other third-party libraries to come up with the API of your choice.

However, due to the many libraries that the Go ecosystem has, you can still choose native libraries that you don't have to download and build your APIs. In this guide, we will build a complete and functional REST API. This API will only use native libraries that Golang has.

#### Key takeaways 

- Why Golang
- Why use native modules
- Build a basic server using native modules
- Create a CRUD Golang REST API using native modules
- Fetch from the API
- Post to the API
- Update a record from the API
- Delete a record from the API
- Testing the API
- Third parties packages that you can use to set up Go REST APIs

#### Article quality

This guide aims to help the reader to learn how to make an HTTP server in Golang without using external libraries. The whole application will run with libraries that are core to Golang. Thus no installing any modules of third-party packages such as Gorm, Go fiber, Gin and etc.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Joakim-gakure**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [ ] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [ ] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [ ] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [ ] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [ ] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [ ] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [ ] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [ ] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [ ] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [ ] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [ ] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6666.

### CODE REVIEW

**Comment by Kayere** [comment]
Plagiarism check done ✅

**Comment by hectorkambow** [comment]
@Joakim-gakure  
@Jethro-magaji  

Can we get an update on this PR?

**Comment by Jethro-magaji** [comment]
> @Joakim-gakure @Jethro-magaji
> 
> Can we get an update on this PR?

Am currently working on it...

**Review by Jethro-magaji — APPROVED** [review]
Hi! @Joakim-gakure 
Well done for coming up with such an amazing article. Please take note of these corrections for the sake of next time.
Thanks.

**Comment by WanjaMIKE** [comment]
Merged #7222 into master

**Pull request merged**
