### PR TITLE
Building a Responsive and Collapsible Sidebar with Ant Design Library and React

### LINKED ISSUE #3423: Building a Responsive and Collapsible Sidebar with Ant Design Library and React
### Introduction:
The three-column web page design is the most widely used web design architecture by modern developers as it provides an efficient way of content presentation. Designing the perfect responsive sidebar, a decade ago was a difficult task that required element manipulation with CSS, but these days modern design libraries such as Ant design library has reduced the complexity of building the perfect sidebar.
### Key Takeaways:
At the completion of this article it is expected that the reader will understand and be able to perform the following
Getting Started with Ant Design Library.
Fundamentals of Ant Design Library.
Elements and Components of Ant Design Library.
Building a responsive sidebar with icons and links using Ant Design Library and React.
Error handling in Ant Design.
### References:
https://ant.design/docs/react/introduce

### PR DESCRIPTION
**Pull request by Tioumoh**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3423.

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by hectorkambow** [comment]
[Building a Responsive and Collapsible Sidebar with Ant Design Library and React #3676.pdf](https://github.com/section-engineering-education/engineering-education/files/7117975/Building.a.Responsive.and.Collapsible.Sidebar.with.Ant.Design.Library.and.React.3676.pdf)


@Tioumoh 

👋 Good afternoon - and welcome to the EngEd program.
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

**Comment by Tioumoh** [comment]
@hectorkambow plagiarism issues fixed.
thanks

**Comment by mercymeave** [comment]
@ahmadmardeni1  would you please conduct another plagiarism check on this PR

**Review by mercymeave — APPROVED** [review]
@Tioumoh check on the changes I or any other reviewer left to perfect future articles.

**Comment by ahmadmardeni1** [comment]
Plagiarism check done ✅

**Comment by WanjaMIKE** [comment]
Merged #3676 into master

**Pull request merged**
