### PR TITLE
Understanding the Slice(), Splice() and Split() methods in JavaScript

### LINKED ISSUE #2318: How To Use The .splice() Array Method
### Proposed title of article
How To Use The .splice() Array Method

### Introduction paragraph (2-3 paragraphs):

What is the splice() method? It is a built-in method for JavaScript Array objects which enables one to update the content of an array by removing or replacing current components with new ones.
This method alters the original array and returns a new array with the removed or replaced elements.
This tutorial will focus on how the splice() method is used to remove, add and replace elements within an array.

### Key takeaways: 
After this article the learner will be able to:
- Remove array elements with splice()
- Add array elements using splice()
- Remove and add elements without removing any elements using splice()

### References: 
N/A

### PR DESCRIPTION
**Pull request by twish-254**
This fixes #2318 
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by BrianaNzivu** [comment]
Hey @twish-254 👋.
Briana here.
Upon further discussion with other reviewers, it has come to our attention that your article does not meet the required standards to be published. Simply because your article has been covered in detail by various sites.
According to our guidelines:
*"We lean towards content that offers an original viewpoint/approach around programming-centric topics."*

All hope is not lost though. What I can advise you to do is to enhance this article in that you can make it a tutorial by illustrating how to use the .splice() array method in a more unusual, unique, and ingenious way to perform various functions in a web/software app.

At least it will meet the content standards and we will publish it, which will be a win-win for both parties.

In case you have any problem or question, do not hesitate to ping me here, via  [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or via my personal email (briananzivu@gmail.com).

Regards🚀

**Comment by BrianaNzivu** [comment]
Hey @twish-254 . 
I will close this pr temporarily so that I can be able to review other ready articles. 
This should not worry you. If you want to submit or commit to it, just let me know and I shall open it for you. 😄 

Regards.

**Comment by hectorkambow** [comment]
[Demystifying the Slice(), Splice() and Split() methods in JavaScript #2727.pdf](https://github.com/section-engineering-education/engineering-education/files/7150253/Demystifying.the.Slice.Splice.and.Split.methods.in.JavaScript.2727.pdf)


👋 Good afternoon - and welcome to the EngEd program.
There appear to be many sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as quetext.com, and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/).
We're really looking for unique/original content

**Comment by twish-254** [comment]
@hectorkambow  i have revised my article and removed the plagiarism.

**Comment by ahmadmardeni1** [comment]
plagiarism check done ✅

Please proceed with the review @BrianaNzivu

**Review by BrianaNzivu — CHANGES_REQUESTED** [review]
Hey @twish-254 👋 .

Good job on the article. It is a very interesting read.
Just a few changes I need you to make as we continue with the preliminary revisions:
- Each article in Section has its own structure on how it is written. For instance, your article is more of a how-to guide. Please check out this [document](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md) and try and structure your article according to this guide.
- Your article has quite a lot of grammatical mistakes and unclear sentences. You can use 
[Grammarly](https://app.grammarly.com/ddocs/1287976180) to correct it. 
- Please include the prerequisites required for this article.

In case of any question or help needed please do not hesitate to ping me here :smile:.
Also, notify me when you are done.

Regards.

**Comment by twish-254** [comment]
@BrianaNzivu I have made the requested changes

**Comment by hectorkambow** [comment]
👀  

Upon a quick glance - it seems this PR is still quite a bit aways from being completed. 
 
As a rule of thumb - please only submit articles (pull requests) with a complete and fully polished article - ready to be published. 
 
All revisions and edits should be completed on your own forked repo (as to not take up room in the queue). 
 
We will be closing this and please re-submit when it is ready to be published as a new PR (and you can add the duplicate label) and ping the reviewer and myself. 

@twish-254 

cc @BrianaNzivu

**Pull request closed without merging**
