### PR TITLE
Planting Timber Logs the Right Way

### LINKED ISSUE #2569: Planting Timber Logs the Right Way
Proposed title of the article
Planting Timber Logs the Right Way
Introduction paragraph (2-3 paragraphs):
Timber is a logger with a small, extensible API. In addition to the regular Android log classes, it also provides a utility.

When logging in android, many developers tend to use the traditional log classes which tend to be tiresome and time-consuming. Timber, a library by Jake Wharton has made logging easy and simple. in this article, we'll be discussing the best and easiest way to plant timber trees. 

Key takeaways:
What is a Timber library?
Planting timber trees using Timber.plant.
The drawbacks of using other log classes.
References:
[https://github.com/JakeWharton/timber)

### PR DESCRIPTION
**Pull request by Owallah**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2569

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
@Owallah you should request the topic to be reopened before creating a PR. https://github.com/section-engineering-education/engineering-education/issues/2569

**Comment by Owallah** [comment]
Hello Mr. Odhiambo.
How's the progress so far?

**Comment by Owallah** [comment]
> @Owallah you should request the topic to be `reopened` before creating a PR. #2569

I already requested and it was opened. Thanks for the headsup.

**Comment by hectorkambow** [comment]
@Owallah 
I'll be running a final review on your PR when ready.
Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[Planting Timber Logs the Right Way #3191.pdf](https://github.com/section-engineering-education/engineering-education/files/6963483/Planting.Timber.Logs.the.Right.Way.3191.pdf)

**Comment by Owallah** [comment]
@hectorkambow 
I have worked on the plagiarism as you instructed.  I had some issues though, the site quetext couldn't allow me to sign-up. So I used prepostseo instead to check the plagiarism percentage after I was done. Receive my apologies in advance if it wasn't as effective as quetext is.

**Review by Owallah — COMMENTED** [review]
Thanks for the changes.

**Comment by Owallah** [comment]
Good morning @paulodhiambo

**Comment by hectorkambow** [comment]
> @hectorkambow
> I have worked on the plagiarism as you instructed. I had some issues though, the site quetext couldn't allow me to sign-up. So I used prepostseo instead to check the plagiarism percentage after I was done. Receive my apologies in advance if it wasn't as effective as quetext is.

That it totally acceptable - we encourage you to use any tool as long as it helps out. 

We will re-check it 👍

**Comment by Owallah** [comment]
@hectorkambow 
Thank you.

**Review by Owallah — COMMENTED** [review]
Thank you @paulodhiambo

**Comment by Owallah** [comment]
Hello @paulodhiambo

**Comment by Owallah** [comment]
What's the progress so far?

**Comment by Owallah** [comment]
Good morning @paulodhiambo 
I hope you had a great weekend.

**Review by Owallah — COMMENTED** [review]
Thank you @paulodhiambo

**Review by paulodhiambo — APPROVED** [review]

**Comment by Owallah** [comment]
@paulodhiambo 
Is there anything I'm supposed to do at this stage of plagiarism check?

**Review by Owallah — COMMENTED** [review]
@paulodhiambo 
Thank you

**Comment by paulodhiambo** [comment]
> @paulodhiambo
> Thank you

You don't have to do anything.

**Comment by Owallah** [comment]
@paulodhiambo 
It's okay

**Comment by hectorkambow** [comment]
[Planting Timber Logs the Right Way #3191 2nd.pdf](https://github.com/section-engineering-education/engineering-education/files/7034515/Planting.Timber.Logs.the.Right.Way.3191.2nd.pdf)

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept.
Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content.
Be sure to see our resources page to see more info on plagiarism and what is considered as such.


Seeing the same % 🤔

**Comment by Owallah** [comment]
Good morning sir @hectorkambow ,
I have seen the message you have sent above. Going through the document, I have noticed that the plagiarism checker is flagging most of my own written code. I guess this is what is raising the percentage.
I am however going to look at the text part and try and change a few things.
Thank you.

**Comment by Owallah** [comment]
Hello @hectorkambow and @paulodhiambo 
I have done a few changes to the article. This is in reference to the message @hectorkambow sent earlier.
As stated earlier, in the document sent, most of my code was being flagged. This can however not be simplified further as it will distort the code.
Again some of the content which I have stated `From the official documentation` has been flagged. This too cannot be simplified further as it is exactly what the official documents say. If I change that, that portion will lose meaning.
Looking forward to your reply. Thank you!

**Comment by Owallah** [comment]
Hello @paulodhiambo 
Any progress so far?

**Comment by paulodhiambo** [comment]
@hectorkambow will check the plagiarism again.

**Comment by Owallah** [comment]
It's okay @paulodhiambo

**Comment by Owallah** [comment]
Hello @hectorkambow , @WanjaMIKE , @paulodhiambo 
Good morning.

**Comment by Owallah** [comment]
Any progress on the plagiarism check?

**Comment by WanjaMIKE** [comment]
@Owallah Some minor issues still appear to be flagged in the plagiarism report. Could you check them out. 
[Planting Timber Logs the Right Way #3191.pdf](https://github.com/section-engineering-education/engineering-education/files/7074771/Planting.Timber.Logs.the.Right.Way.3191.pdf)

**Comment by Owallah** [comment]
Hello @WanjaMIKE I have received your message. I have viewed the document. I have one problem though

**Comment by Owallah** [comment]
Most of what the plagiarism check has flagged is the code. I can however not change that.

**Comment by Owallah** [comment]
Most of it is autogenerated by Android Studio. 
an example is this
`<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:app="http://schemas.android.com/apk/res-auto"
xmlns:tools="http://schemas.android.com/tools"
android:layout_width="match_parent"
android:layout_height="match_parent"
tools:context=".MainActivity">`

Changing that will cause errors to the whole xml code

**Comment by WanjaMIKE** [comment]
> Most of it is autogenerated by Android Studio.
> an example is this
> `<?xml version="1.0" encoding="utf-8"?> <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android" xmlns:app="http://schemas.android.com/apk/res-auto" xmlns:tools="http://schemas.android.com/tools" android:layout_width="match_parent" android:layout_height="match_parent" tools:context=".MainActivity">`
> 
> Changing that will cause errors to the whole xml code

Yes, You can leave the boilerplate code. Only the minor sentences need to be changed. Thanks

**Comment by Owallah** [comment]
Hello @WanjaMIKE 
I have done changes. Please check it out

**Comment by Owallah** [comment]
Hello @paulodhiambo

**Comment by hectorkambow** [comment]
@paulodhiambo - please let me know if you believe the article is ready for a final review

**Comment by hectorkambow** [comment]
@paulodhiambo 

I believe Mike ran a plagiarism check on this yesterday - does it need another?

**Comment by paulodhiambo** [comment]
@WanjaMIKE said the percentage of plagiarism was still a bit higher.

**Comment by Owallah** [comment]
@hectorkambow and @paulodhiambo 
Yeah, @WanjaMIKE  had instructed that I work on a few texts and I did and committed the changes I made.

**Comment by WanjaMIKE** [comment]
@paulodhiambo please proceed. The plagiarism check was completed. Thanks

**Comment by LinusMuema** [comment]
Hi @Owallah 
Thank you for this amazing article. Keep up the amazing job.

cc: @paulodhiambo

**Pull request merged**
