### PR TITLE
Structuring Large Applications with Blueprint and Application Factory…

### LINKED ISSUE #2365: Structure Large Applications in Flask Using Blueprints and Flask Application Factory
### Proposed title of article
Structure Large Applications in Flask Using Blueprints and Flask Application Factory

### Introduction paragraph (2-3 paragraphs):
This article will explain and illustrate how to structure web applications on a large scale with the Python Flask backend web framework. 

### Key takeaways: 
- Work Environment Setup
- Understanding and implementing Blueprints and Application Factory
- Working with configuration and environment variable
-  Summary and Conclusion

### References: 
N/A

### PR DESCRIPTION
**Pull request by corpsgeek**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
Closes #2365
   
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by corpsgeek** [comment]
@louisefindlay23 and @srishilesh  here is the PR in a new branch and all changes

**Comment by louisefindlay23** [comment]
@corpsgeek, thanks for making a new branch. However, your forked repo seems to still being using the old repo structure (because the articles directory exists instead of /content/articles).

In order for me to final review your article, you should:

- First, download the most recent files off this PR
- Next, delete your articles directory
- Then, pull the upstream branch (main EngEd repo) into your forked repo
- Finally, upload your article files to the new articles folder inside content ie. /content/articles.

Let me know if you have any issues.

cc - @srishilesh

**Comment by corpsgeek** [comment]
I guess its fixed now @louisefindlay23 ?

**Comment by srishilesh** [comment]
> I guess it is fixed now @louisefindlay23 ?

@corpsgeek 

Doesn't look like it's fixed. Your last commit shows changes in more than 6000 files.

**Comment by corpsgeek** [comment]
Yeah, I pulled from the master at the same time it uploaded other folders structure on my end.

**Comment by corpsgeek** [comment]
updated*

**Comment by corpsgeek** [comment]
The alternative route would be for me to fork the master branch afresh and upload the article then create a new PR

**Comment by srishilesh** [comment]
> The alternative route would be for me to fork the master branch afresh and upload the article then create a new PR

@corpsgeek 

Yep. I believe that would be the easiest way to go forward.

Make sure to add the latest reviewed files.

Ping me and @louisefindlay23 after you create a new PR.

Thanks

**Comment by srishilesh** [comment]
> @corpsgeek, thanks for making a new branch. However, your forked repo seems to still being using the old repo structure (because the articles directory exists instead of /content/articles).
> 
> In order for me to final review your article, you should:
> 
> * First, download the most recent files off this PR
> * Next, delete your articles directory
> * Then, pull the upstream branch (main EngEd repo) into your forked repo
> * Finally, upload your article files to the new articles folder inside content ie. /content/articles.
> 
> Let me know if you have any issues.
> 
> cc - @srishilesh

@louisefindlay23 

Just a quick question. I failed to notice this earlier.

I believe these files follow the expected directory structure `/content/articles/`. Not sure if you had sent this message by mistake.

Thanks.

**Review by louisefindlay23 — APPROVED** [review]
Great article, @corpsgeek. Thanks for making the changes. Final review complete.

Thanks for your help, @srishilesh and for peer reviewing.

**Pull request merged**
