### PR TITLE
Build a messaging API using Twilio’s API and Express.Js

### LINKED ISSUE #6560: [API]Build a messaging API using Twilio’s API and Express.Js
*NOTE*: All **1st-time contributors** should know Topic approval and PR submission does NOT guarantee your Topic/Article will be published. Our team of Peer Reviewers and Content Moderators will review all PRs that come in to make sure they adhere to the standard of quality we expect from the EngEd community. 

We expect all community members to go through provided examples, resources, and previously published material before submitting content. As a rule of thumb, please only submit articles (pull requests) that are complete, formatted correctly, and include a fully polished article (ready to be published and error-free). 

All revisions and edits should be *completed on your own forked repo (as to not take up room in the queue)*. **Any PR that is submitted incomplete (meaning not ready to be published as is) will be closed.** A PR being closed does NOT mean the article can not be published (or fixed) it simply means that the edits, revisions, and fixes will happen outside of the queue.

**NOTE: Any topic suggestion copied/taken/modified from YouTube may Lead to a permanent ban from the community.**

### Topic Suggestion
[API]Build a messaging API using Twilio’s API and Express.Js

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
https://dev.to/sodiq123/building-a-user-login-system-with-express-js-and-fauna-4p32
https://dev.to/sodiq123/todo-api-with-express-js-and-mongodb-14ej

#### Proposed title of article
Build a messaging API using Twilio’s API and Express.Js

Use keyword research to improve your article's SEO.
Twilio, API, Nodejs

#### Proposed article introduction
Twilio has a couple of APIs that allow you to send and receive a high volume of SMS messages anywhere in the world. Once you get your registered Twilio phone number, you can use the APIs to manage outbound messages (“sending”) and inbound messages (“receiving”).

In this article, you will learn how to send and receive SMS messages with Node.js and Express and save the sent messages in a MongoDB database.

We will first send an SMS with Node.js and the Twilio Messages API. We'll then build an API that can send SMS messages using Express. We'll focus in this article on sending SMS messages using the third-party message API. Still, if you want to send and receive messages with Facebook Messenger, Viber, or WhatsApp, you can do that as well with the Message API.

You can extend the application we're building here to reply to incoming SMS messages or include more complex, interactive elements and give you a head start building autoresponders for your SMS needs.

#### Key takeaways 
What is Twilio
-Give an in-depth explanation to the reader on Twilio and Twilio’s message API.
-Explanation of how Twilio’s message API works.

Getting Started
-Setup Twilio account
-Set up a node server that provides the API for sending a message and the API structure.
-Explore the functionalities of the API endpoints which includes:
-Create a User ({ name, email, password })
-Log a user In (email, password)
-Adding authentication using Jwt
-Add a contact to your Twilio account
-The user can create a contact (In terms of a phone book)
-The user can get a contact by its Id
-The user can delete a contact
-The user can get all contacts
-The user can update a contact ({name, number})
-The user has contacts to send messages to (A number registered with your Twilio Account).
-Save sent messages (More like message history).

#### Article quality
The article is intended for mid-level developers. It takes an in-depth look at authentication and authorization and how to use third-party APIs which in this case, Twilio and how to add MongoDB with Nodejs.

#### References
https://www.twilio.com/blog/what-does-twilio-do
https://console.twilio.com/us1/develop/sms/try-it-out/get-set-up?frameUrl=%2Fconsole%2Fsms%2Fget-setup%3Fx-target-region%3Dus1

### Conclusion
This article takes a look at authentication and authorization, how to implement third party APIs and how to use MongoDB in your Nodejs project.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by Sodiq-123**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6560

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Some plagiarism was highlighted in the article. Check the attached PDF. Thanks
[New Scan 6_13 AM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/8924965/New.Scan.6_13.AM.Copyleaks.Report.pdf)

**Comment by Sodiq-123** [comment]
Thank you @WanjaMIKE

**Comment by Sodiq-123** [comment]
@hectorkambow are all checks done to merge this pull request so I can suggest another article topic.

**Comment by hectorkambow** [comment]
> @hectorkambow are all checks done to merge this pull request so I can suggest another article topic.

That should be fine yes.

**Comment by Sodiq-123** [comment]
Alright, thanks

**Comment by hectorkambow** [comment]
Our team has been working diligently to clear the backlog and we should be getting this pull request ready to be published next week 🚀

**Comment by WanjaMIKE** [comment]
@Sodiq-123 Remember to format your article well. Right now there are no headings. Thanks

**Comment by WanjaMIKE** [comment]
Not sure if hosted images will get published

**Pull request merged**
