### PR TITLE
Why Move from ETL to ELT for your Fintech Products?

### LINKED ISSUE #5446: Why Move from ETL to ELT for your Fintech Products?
#### Proposed title of article

Why Move from ETL to ELT for your Fintech Products? 
#### Proposed article introduction
Many fintech companies now find themselves collecting more data than ever before. But this data won't be of much use if it is just sitting in an Excel spreadsheet somewhere. So these firms need a fast, effective way of importing this into their analytics solutions. And for many, this is where ETL technology comes in.

Standing for Extract, Transform and Load, these solutions take raw data from whatever initial form it arrives in, cleans and transforms it into a more standardized format that is easier for data scientists to work with, and add it to a data warehouse where it can be processed. This has become an everyday activity for many firms, but it's not the only way of getting information from the source and into a data warehouse. Increasingly, there's another similar, but not identical, alternative to consider in the form of ELT solutions.

#### Key takeaways 

- ETL vs ELT.
- Should you use ETL or ELT for fintech data?
- ETL and ELT security.
- ETL and ELT tools.

#### Article quality
This article is not just another general comparison of ETL and ELT. It is unique in that it compares ELT and ETL in terms of their application in extracting fintech data.
#### References
N/A

### PR DESCRIPTION
**Pull request by jesmweni**
this closes #5446

## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [ ] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by hectorkambow** [comment]
@section-engineering-education/peer-reviewers

Is anyone available to review this PR?

Thank you

**Comment by collins-a** [comment]
@hectorkambow on it

**Comment by WanjaMIKE** [comment]
Please paraphrase the following paragraphs. They seem to show some plagiarism. Thanks

```ETL stands for Extract, Transform, and Load. ELT is an abbreviation for Extract, Load, and Transform. ETL has been the conventional approach for data management for many years. Shifts towards ELT are increasingly becoming popular since Fintech companies started embracing cloud-based services.```

```Both ETL and ELT are data integration processes that combine data from several sources then load it into a data target system. The primary difference between ETL and ELT lies in the sequence of activities. In ETL, data transformation occurs on a staging area before loading it to the target. ```

**Comment by collins-a** [comment]
Hello @jesmweni. Welcome to EngEd! As a new contributor, I encourage you to add a brief **Author Bio** (index.md file) and **Headshot image** (avatar file). Include these files in the authors folder within the GitHub repo via your forked repo similar to the article files so as to be credited for your hard work.

Ping me after you do so, so that I may continue with reviewing your article.

**Comment by jesmweni** [comment]
@collins-a I have done some edits and added author bio.

**Comment by collins-a** [comment]
> @collins-a I have done some edits and added author bio.

Hi @jesmweni, thank you for adding the author bio. However, please consider replacing the avatar.jpg file as it is preferably a headshot of you as opposed to any other type of image.

**Comment by jesmweni** [comment]
> > @collins-a I have done some edits and added author bio.
> 
> Hi @jesmweni, thank you for adding the author bio. However, please consider replacing the avatar.jpg file as it is preferably a headshot of you as opposed to any other type of image.

@collins-a

**Review by collins-a — APPROVED** [review]
@jesmweni well-written article contrasting ETL and ELT. I hope to see more of your articles with such depth and quality.

Please note that you can also include your LinkedIn, GitHub, or Twitter URLs as illustrated in the [upload instructions](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/UPLOAD_INSTRUCTIONS.md).

**Comment by hectorkambow** [comment]
Jumping on this one

**Pull request merged**
