### PR TITLE
Creating dynamic web content with createjs

### LINKED ISSUE #2140: Creating Dynamic Web Content With CreateJS
We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article higher ranking.*

Creating Dynamic Web Content With CreateJS

### Introduction paragraph (2-3 paragraphs):

The Web has evolved a lot nowadays to allow for more lively content. In particular, HTML5 introduced new features for dynamic graphics and sounds. These have made it easier to create cool content from infographics to mini-games. One tool to help you do this is called CreateJS.

CreateJS is a suite of Javascript libraries to help you create interactive content. It allows for easy canvas manipulation, animations, sound effects, and asset loading. CreateJS is made up of four libraries, EaselJS, TweenJS, SoundJS, and PreloadJS. You can use them independently or in combination. In this guide, we will be going over some of the key features of each of these libraries so you can use them to create fun web content.

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

- What are the Libraries that comprise CreateJS and what do they do?
- How to load assets
- Drawing canvas graphics
- How to animate sprites and shapes
- How to play sounds

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by john-amiscaray**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
 
This fixes #2140 
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by kayere** [comment]
Hello @john-amiscaray, sorry for the delayed review. I was going through your PR and it seems to have conflicts with three published articles. Could you please resolve the conflict(if possible) before we proceed. Otherwise, you can create a fresh PR. Please update me with your progress.

**Comment by john-amiscaray** [comment]
> 
> 
> Hello @john-amiscaray, sorry for the delayed review. I was going through your PR and it seems to have conflicts with three published articles. Could you please resolve the conflict(if possible) before we proceed. Otherwise, you can create a fresh PR. Please update me with your progress.

No worries, that's okay. I'm not sure how I seemed to have accidentally modified some files in this branch I'll try to fix them shortly.

**Comment by hectorkambow** [comment]
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

**Comment by hectorkambow** [comment]
I think the forked repo may need a git pull - to get the new structure then you can re-add your files

**Comment by john-amiscaray** [comment]
> 
> 
> I think the forked repo may need a git pull - to get the new structure then you can re-add your files

Alright thanks for reminding me, I will do so

**Comment by john-amiscaray** [comment]
> 
> 
> Hello @john-amiscaray, sorry for the delayed review. I was going through your PR and it seems to have conflicts with three published articles. Could you please resolve the conflict(if possible) before we proceed. Otherwise, you can create a fresh PR. Please update me with your progress.

I believe the conflicts should be fixed now. Sorry for that

**Review by kayere — APPROVED** [review]
Great article @john-amiscaray. Please go over the changes that I have made to help improve the format and grammar of your future articles.

**Comment by john-amiscaray** [comment]
@kayere Thanks for the review, I really appreciate it and will take your feedback for future articles. Although correct me if I'm wrong but I believe you've made a minor grammatical mistake in your commit in this sentence: 
>Each of these libraries is independent of the other *but you can be used together*. 

where it says "but you can be used together". The sentence was referring to the fact that the libraries that CreateJS is comprised of can be used together or independently. Anyways, I'll just push a quick commit to fix that. Thanks.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by hectorkambow** [comment]
Notice the minor edits I have made here - the article was really well put together - easy to follow along. 

Notice the Heading - I deleted/replaced the unneeded capital letters in the headings. 

Spacing - notice that paragraphs that seemed too long - I spaced them out. Any paragraph more than 3 sentences needs to spread apart. 

Any sentence with an semi-colon: I space out. 

Make note of how I rearranged the intro paragraph. Anything about the ----more tag will be previewed in the main page box view. (in this view we can not have ' or " as they will not rendered properly.)

Any words that are Italic with the "_" underscore - change to "*" asterisk to be italic. 

I do this for most articles that come in @ahmadmardeni1 👀  

cc @john-amiscaray 

@kayere

**Comment by hectorkambow** [comment]
great work gents @john-amiscaray 
cc @kayere

**Pull request merged**
