### PR TITLE
A General Purpose Intelligence System

### LINKED ISSUE #4915: [Machine Learning] Pathways: A General Purpose Intelligence System
### Topic Suggestion
[Machine Learning] Pathways: A General Purpose Intelligence System

#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Pathways: A General Purpose Intelligence System

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Today's artificial intelligence models are trained to accomplish only a single task. However, Google's new Pathways model aims to perform different tasks in an effective manner. Google aims to build one model that can perform different tasks; a general purpose intelligence system. The model they aim to build is similar to the way our brain actually works. Instead of having a single neural network that you can train, you have this giant neural network that can do all the tasks at once. It is a relatively new model released by Google on 28th October 2021. This article will discuss this new model.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

In this article, a reader will get to understand the Pathways model, a promising new approach to AI, how it's actually intended to work, and what such a model would mean to the AI industry.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

Pathways is a relatively new model released by Google on 28th October 2021 . So, not a lot of articles exist out there on the subject. This makes this article unique and I believe it will benefit most of our readers.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

- [Introducing Pathways: A next-generation AI architecture](https://blog.google/technology/ai/introducing-pathways-next-generation-ai-architecture/)

### PR DESCRIPTION
**Pull request by monicada**
This Closes #4915

### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by LinusMuema** [comment]
Hi @monicada 

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[A General Purpose Intelligence System #5129 Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7608141/A.General.Purpose.Intelligence.System.5129.Copyleaks.Report.pdf)

**Comment by monicada** [comment]
@Bayler done.

**Comment by hectorkambow** [comment]
@monicada 
It would be wise to go over the PDF to see what came up in our 3rd party plagiarism check. 
[A General Purpose Intelligence System #5129.pdf](https://github.com/section-engineering-education/engineering-education/files/7652623/A.General.Purpose.Intelligence.System.5129.pdf)

**Comment by monicada** [comment]
@Bayler I've made the changes, please check.

**Comment by Bayler** [comment]
@monicada Welcome to our EndEd program. We are delighted to have you being part of our program. The article will now proceed for final review.

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
🚀

**Pull request merged**
