### PR TITLE
How to split a monolithic architecture into micro-frontends

### LINKED ISSUE #5629: [Languages] How to split a monolithic architecture into micro-frontends
#### Proposed title of article
How to split a monolithic architecture into micro-frontends

#### Proposed article introduction
There exists several open-source and third-party libraries that reduce the development effort while keeping the complexity minimal. But, in reality, applications tend to grow in complexity over time hence demanding higher scalability and responsiveness.

A monolithic application tends to contain a lot of components and have complex logic. It is also hard to maintain and scale the application product. Integrating new developers is also challenging.

A better approach would be to split the application logic into smaller pieces which is easier to maintain and also analyze its codebase. Also, it is easy to assign different components to different teams which makes them independent.

In the proposed topic, we will look into details about micro-frontends and their benefits over monolith architectures. We will also implement an example application to demonstrate the breaking down of monolithic applications to a micro-frontend.

#### Key takeaways 
At the end of the article, a learner will be able to understand:
- the concept of monolith architecture and micro-frontend architecture
- the features and advantages of micro-frontends
- the technical demonstration of how to create a micro-frontend in Angular

#### Article quality
The guide focuses more on splitting a monolith application into micro-frontends using a practical example for the learner to grasp firmly the concepts laid down. Unlike the other articles online which focus more on building the micro-frontends.

#### References
N/A

### PR DESCRIPTION
**Pull request by ephnjor2021**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #5629

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by srishilesh** [comment]
Hello @ephnjor2021 ,

Thanks for submitting this PR.

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started with the review.

Meanwhile, we suggest you to go through approved PRs/published articles to see if you have missed out anything. This would help us avoid any potential closure of the PR.

Thanks.

**Comment by LinusMuema** [comment]
Hi @ephnjor2021 

In as much as your plagiarism check score is acceptable, I couldn't help but notice several sentences that match an article on hacker noon. Please check on them before you continue.

cc: @mercymeave 

[Uploading How to split a monolithic architecture into micro-frontends #6310 Copyleaks Report.pdf…]()

**Comment by ephnjor2021** [comment]
Hello @LinusMuema I will check on the document. Thank you
cc @mercymeave

**Comment by ephnjor2021** [comment]
> Hi @ephnjor2021
> 
> In as much as your plagiarism check score is acceptable, I couldn't help but notice several sentences that match an article on hacker noon. Please check on them before you continue.
> 
> cc: @mercymeave
> 
> Uploading How to split a monolithic architecture into micro-frontends #6310 Copyleaks Report.pdf…

@LinusMuema Could you please attach the plagiarism report again as am trying to download it to no success, the download link is not working.
Thank you. cc @mercymeave

**Comment by mercymeave** [comment]
Hello @ephnjor2021, what is your progress with this article? If you need more time then let me close is as you work on the chnages.

**Comment by ephnjor2021** [comment]
> Hello @ephnjor2021, what is your progress with this article? If you need more time then let me close is as you work on the chnages.

Hi @mercymeave I will make the requested changes shortly. Thank you

**Comment by ephnjor2021** [comment]
Hi @mercymeave The requested minor changes have been made, feel free to continue with the review process.
Thank you.

**Review by mercymeave — CHANGES_REQUESTED** [review]
Hello @ephnjor2021 

You have a great article here. However, your article seems to have a lot of readability issues, complex sentences and punctuation mistakes. 

I recommend you read the whole article to identify and correct the mistakes. Remember we encourage our authors to have very easy to read articles to save time on review and improve the quality of our platform.

I made a few changes at the beginning. You could how I minified some statements to make them clear and follow the trend.

Thanks.

**Comment by ephnjor2021** [comment]
> Hello @ephnjor2021
> 
> You have a great article here. However, your article seems to have a lot of readability issues, complex sentences and punctuation mistakes.
> 
> I recommend you read the whole article to identify and correct the mistakes. Remember we encourage our authors to have very easy to read articles to save time on review and improve the quality of our platform.
> 
> I made a few changes at the beginning. You could take a look on how I minified some statements to make them clear and follow the trend.
> 
> Thanks.

Noted

**Comment by ephnjor2021** [comment]
> Hello @ephnjor2021
> 
> You have a great article here. However, your article seems to have a lot of readability issues, complex sentences and punctuation mistakes.
> 
> I recommend you read the whole article to identify and correct the mistakes. Remember we encourage our authors to have very easy to read articles to save time on review and improve the quality of our platform.
> 
> I made a few changes at the beginning. You could take a look on how I minified some statements to make them clear and follow the trend.
> 
> Thanks.

Hello @mercymeave, the requested changes have been made. You can proceed with the review process.
Thank you.

**Review by mercymeave — APPROVED** [review]
Great work @ephnjor2021 

Consider going over the changes made to improve future articles.

**Comment by ephnjor2021** [comment]
> Great work @ephnjor2021
> 
> Consider going over the changes made to improve future articles.

@mercymeave Noted with thanks.

**Review by louisefindlay23 — CHANGES_REQUESTED** [review]
@ephnjor2021, the text of your hero image doesn't contrast enough with your background so it's hard to read the title of your article. Please fix this so I can publish your article.

**Comment by lewe01** [comment]
> @ephnjor2021, the text of your hero image doesn't contrast enough with your background so it's hard to read the title of your article. Please fix this so I can publish your article.

@louisefindlay23  Noted

**Comment by ephnjor2021** [comment]
> @ephnjor2021, the text of your hero image doesn't contrast enough with your background so it's hard to read the title of your article. Please fix this so I can publish your article.

@louisefindlay23 Noted

**Comment by ephnjor2021** [comment]
@louisefindlay23 I have fixed the minor issue with the hero image. You can proceed. 
Thank you cc @mercymeave

**Review by louisefindlay23 — APPROVED** [review]

**Pull request merged**
