### PR TITLE
Imbalanced-Learn Python Package for Machine Learning

### LINKED ISSUE #5012: [Machine Learning] Imbalanced-Learn Python Package for Machine Learning
#### Proposed title of article
[Machine Learning] Imbalanced-Learn Python Package for Machine Learning

#### Proposed article introduction
Imbalanced-Learn is a Python package that is used to handle imbalanced datasets during machine learning. An imbalanced dataset is a dataset in which the number of observations is not equal to the number of classes in a classification dataset. This imbalance leads to inconsistent and inaccurate prediction results.

Most models that are built using the imbalanced data will have a bias towards predicting the majority classes in the dataset and ignore the minority classes. Class imbalance is identified by observing the distribution of classes within your data or using visualizing libraries to plot the class distributions. 

Imbalanced-Learn has various techniques that will be used to handle this problem. These techniques are such as Random Undersampling technique: resample all classes but the majority class, Random Oversampling technique: resample all classes but the majority class.
In this tutorial, we shall discuss these techniques in detail and implement them practically using Python.

#### Key takeaways 
1. What is Imbalanced-Learn?
2. How to install Imbalanced-Learn.
3. Exploring Imbalanced-Learn methods and techniques.
4. Implementing Undersampling technique and Oversampling technique.
5. Model building with Class weight balancing

#### Article quality
In this tutorial we will use two approaches to handle the imbalanced dataset as follows:
1. Random Undersampling: Here we resample all classes but the minority class to reduce model bias.
2. Random Oversampling: Here we resample all classes but the majority class to ensure that the model learns from every dataset.
We will perform Model building with both oversampled balanced class and undersampled balanced class. After that, we will compare the results using class weight balancing to evaluate the model performance. This ensures we have a more reliable model.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by charles721**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5012

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by srishilesh** [comment]
@section-engineering-education/content-moderator-team 

Can we run plagiarism check on this PR before I jump into this for a tech review?

The formatting changes looks good to me.

**Comment by srishilesh** [comment]
@hectorkambow @section-engineering-education/content-moderator-team 

Can we have this PR plagiarism checked?

**Comment by srishilesh** [comment]
Looks like it's taking time for the plagiarism check.

Let me jump in for the tech review.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by srishilesh** [comment]
Will complete my final review by tomorrow.

**Review by srishilesh — APPROVED** [review]
@charles721 

Great work!

I've made some minor changes to formatting and flow. Make sure to go through my commits to understand them.

Moving for the final review.

Thanks.

**Comment by hectorkambow** [comment]
jumping on this one

**Pull request merged**
