### PR TITLE
Creating a data visualization dashboard using MPAndroid Chart library and SQLite

### LINKED ISSUE #5724: [ANDROID || LANGUAGES] - Creating a data visualization dashboard using MPAndroid Chart library
### Topic Suggestion
Creating a data visualization dashboard using MPAndroid Chart library and SQLite

### Writing sample(s): 
My writing samples are found [here](https://www.section.io/engineering-education/authors/sandra-moringa/).

#### Proposed title of article
Creating a data visualization dashboard using MPAndroid Chart library and SQlite

#### Proposed article introduction
The easiest way for a user to get insight from information is through the use of data visualization. The most common tool for that is charts. In this article, we will create an admin dashboard that allows the user to view his/her data using different kind of charts. Kotlin and an open-source chart library, MPAndroidChart, will be used.

#### Key takeaways 
The reader will gain knowledge in:
1. Using the Kotlin and MPAndroidChart library
2. Getting data from an sqlite database
3. Creating a dashboard using cards

#### Article quality
The article will not only guide the user on using the MPAndroidChart library but it will show him/her how to dynamically populate the charts using data from a database. 

#### References
1. [MPAndroidChart GitHub code examples](https://github.com/PhilJay/MPAndroidChart)
2. [Vishal Kamboj Youtube videos](youtube.com/channel/UC92ii7ym_NNs_grqya_zsgg)

### PR DESCRIPTION
**Pull request by munubi254**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #5724

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
Plagiarism check done.

**Review by BrianaNzivu — CHANGES_REQUESTED** [review]
Hey @munubi254   👋 .
My name is Briana and I will be reviewing your article.
First of all, good job on the article. It is a very interesting read and very minimal corrections to be made.
Just a few changes I need you to make that I have mentioned as we continue with the tech review.
1.  Please structure your article according to this [sample](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md). I need you to clearly highlight your steps.
2.  Refer to the single comments I have made.

**Note: Please make sure to make changes to the updated index.md**

In case of any question or help needed please do not hesitate to ping me here :smile:.

Regards.

**Comment by munubi254** [comment]
OK @BrianaNzivu

**Comment by munubi254** [comment]
@BrianaNzivu please check the changes made and advise.

**Comment by BrianaNzivu** [comment]
Tech review done 👍

**Review by BrianaNzivu — APPROVED** [review]
Hey @munubi254 👋 .

Very good job on the article. It is a very interesting read 👏 .

Just a few things I'd like to point out:
- I suggest that you check out the [structure](https://github.com/section-engineering-education/engineering-education/tree/master/new_contributors) for the various articles accepted by Section.
-  It is always advisable to submit an article that is well polished. By this, I mean having an article that does not have too many grammatical corrections and functional code. I suggest that you check out our [resources](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) page which has links to various resourceful tools for writing. 
- Lastly please go through ALL the corrections I have made so that you can not repeat the same mistakes.

That's it! :smile: 

A final review will be done now by a content moderator.
Otherwise, congratulations on publishing your article🍾.

In case of any question or clarification (currently or in the future), do not hesitate to reach out via [Slack](https://app.slack.com/client/T5X14SH7G/D01A6MT673R) or my personal email (briananzivu@gmail.com). 
I am **ALWAYS** here to help.

It has been a pleasure reading and reviewing this article.

Looking forward to seeing you contribute more to EngEd. 🚀

Kind Regards.

**Comment by lalith1403** [comment]
Jumping on this one team 🚀

**Comment by lalith1403** [comment]
Well done @munubi254 and @BrianaNzivu.

**Pull request merged**
