### PR TITLE
Google OAuth in React Native Application using Firebase

### LINKED ISSUE #1708: Google OAuth in React Native Application using Firebase
### Proposed title of the article

Google OAuth in React Native Application using Firebase

### Introduction paragraph(s):
OAuth is an open standard for access delegation, commonly used as a way for Internet users to grant websites or applications access to their information on other websites but without giving them the passwords.

In this tutorial, we will learn how to authenticate users with their Google accounts using the authentication module in Firebase in a Non-Expo React Native application.

### Key takeaways

- Set up Firebase Project for Google OAuth.
- Add Login/Create account screen.
- Use the Firebase Auth module and authenticate users.
- Logout from the authenticated screen.

### References: 
N/A

### PR DESCRIPTION
**Pull request by zolomohan**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [ ] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1708

### CODE REVIEW

**Comment by zolomohan** [comment]
Hi @hectorkambow. This is the second article in my React Native Firebase authentication series. 
I'm forced to re-use some sections from the previous articles to maintain a standalone reading by the reader. 

I find it difficult and un-easy to jump between articles and documentations, thus I tend to structure everything required in a single article when I write tutorials. 

This might trigger the plagiarism checker by marking some sentences from my [previous article](https://www.section.io/engineering-education/react-native-firebase-phone-authentication/). Just a heads up.

Rest assured, both the articles deal with very different topics. The reason for re-using the sections is because both topics require the same modules, thus the setup and common procedures are the same.

**Review by srishilesh — APPROVED** [review]
Hey @zolomohan,

Thanks for the PR.

Amazing article. I learnt a lot from it. It's very beginner friendly. Keep up the good work!

Moving this article for the final review.

Thank you.

**Comment by zolomohan** [comment]
@srishilesh Thank you for your kind words.

**Comment by zolomohan** [comment]
I couldn't run the plagiarism check because the article is above 1000 words. The free tier has a 1000 word limit.
But I assume the percentage is going to be a bit higher because of my [previous article](https://www.section.io/engineering-education/react-native-firebase-phone-authentication/) and the common steps.

**Comment by hectorkambow** [comment]
[Google OAuth in React Native Application using Firebase #1813.pdf](https://github.com/section-engineering-education/engineering-education/files/6231976/Google.OAuth.in.React.Native.Application.using.Firebase.1813.pdf)


@zolomohan  

correct - but the area that is of more concern is the areas from:
 https://lucid.blog/usmansbk/post/react-native-android-authentication-with-firebase-791

just want to make sure that overlap is not boilerplate code - and again we should figure out some solution to the % in general as every new article is higher and higher.

**Comment by zolomohan** [comment]
Hi @hectorkambow. Just went through it and fixed the triggers. About 10 matches were from the [mentioned article](https://lucid.blog/usmansbk/post/react-native-android-authentication-with-firebase-791). 6 of them were caused by comments in the code, and 2 due to common import statements. Unfortunately, the import statement is crucial, but I removed the comments.

Hope it's good to go.

**Pull request merged**
