### PR TITLE
Understanding Shared Memory Programming With Pthreads and OpenMP

### LINKED ISSUE #6135: Understanding shared memory programming with Pthreads and OpenMP
#### Proposed title of the article
Understanding shared memory programming with Pthreads and OpenMP.

#### Proposed article introduction
Data is sent between applications more efficiently via shared memory. Depending on the circumstances, programs may execute on a single processor or numerous processors. Shared memory refers to communication inside a single program, such as between its innumerable threads.

There may be many threads in the process. The lightweight process is another term for a thread. By splitting a process into many threads, parallelism may be achieved. Multiple tabs in a browser, for example, may each be a separate thread. MS Word uses numerous threads to format text, handle inputs, and so on. Below are some additional benefits of multithreading.

This tutorial will use the Pthreads and OpenMP programming paradigms to demonstrate how to create parallel applications.

#### Key takeaways 
By the end of this article, the reader will have understood:

- the system architecture.
- what shared memory, threads and processes are. 
- the parallel computing: shared memory models.
- what Pthread is and why use Pthread.
- what OpenMP is and why use OpenMP.
- how threads work, their safety and limits
- the Pthreads API 
- working with OpenMP and Pthreads.

#### Article quality
This article aims to go further into this topic while also presenting its principles in a straightforward, understandable manner for newcomers.

References

#### References
N/A

### PR DESCRIPTION
**Pull request by carteblanchemunene**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

#### Topic suggestion this closes

This closes #6135

### CODE REVIEW

**Comment by carteblanchemunene** [comment]
Hello @Dawe-7 I have created another PR and implemented changes. Please check

**Comment by hectorkambow** [comment]
@Dawe-7 

I see you have too many PRs assigned at one time. 👀 

Lets please be sure to get the ones that are ready for final published by pinging the CM team to get those completed before assigning more PR. 🚀

**Comment by Dawe-7** [comment]
@section-engineering-education/content-moderator-team, can we kindly have a final review of this PR

**Review by Kayere — APPROVED** [review]
Nice article @carteblanchemunene. Thanks for the review @Dawe-7

**Pull request merged**
