### PR TITLE
Creating a Video Conferencing App with 100ms SDK in Android

### LINKED ISSUE #6951: [Android] Creating a Video Conferencing App with 100ms SDK in Android
#### Proposed title of article

Creating a Video Conferencing App with 100ms SDK in Android

#### Proposed article introduction
100ms is a cloud platform that allows developers to add video and audio conferencing to Web, Android and iOS applications.

The platform provides REST APIs, SDKs, and a dashboard that makes it simple to capture, distribute, record, and render live interactive audio and video.

It adds live video conferencing to your app in 10x fewer lines of application code than any other fully customizable video SDK. It was built by the team that created live video infrastructure powering billions of minutes a day at Facebook and Disney+Hotstar.

In this tutorial we will create a simple android application from scratch and video conferencing capabilities to the app with the help of the 100ms SDK.

#### Key takeaways 
- What is 100ms SDK.
- How is 100ms SDK different from other video conferencing SDKs.
- Pricing.
- How to integrate it into your Android app.

#### Article quality
The article will be beginner friendly and straight to the point. 100ms SDK being new, few articles have been written explaining how it should be used. So I will do my best to explain things well.

#### References
- [100ms Android Docs](https://www.100ms.live/docs/android/v2/foundation/Basics)

### PR DESCRIPTION
**Pull request by tomleposo**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #6951

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Plagiarism check complete

**Comment by WanjaMIKE** [comment]
@Ericgacoki do you need help with this PR?

**Comment by Ericgacoki** [comment]
I'm working on it. I'll be done ASAP! 🙂

**Comment by hectorkambow** [comment]
@Ericgacoki any update on this PR ?

Just wondering if this is ready for a final review?

**Review by Ericgacoki — APPROVED** [review]
Hello @tomleposo
We appreciate your hard work in composing such a lengthy and very informative tutorial. Keep it up 👏.

Thanks for your patience.

**Comment by Ericgacoki** [comment]
@hectorkambow this PR is ready for final review.

cc: @section-engineering-education/content-moderator-team

**Comment by hectorkambow** [comment]
🚀 

@tomleposo 

A skill section will go a long way with potential future employers

**Pull request merged**
