### PR TITLE
CRUD Operations with YII2 Framework Using GII

### LINKED ISSUE #2111: CRUD Operations with YII2 Framework Using GII
###  Proposed title of article

CRUD Operations with YII2 Framework Using GII

### Introduction paragraph (2-3 paragraphs):

Programmers who have ever worked with the database are likely to have also worked with CRUD Operations.

CRUD is an acronym that stands for Create, Read, Update, Delete. Each letter in the acronym can refer to all functions executed in relational database applications.

The function of each letter in the CRUD acronym is as shown below:

CREATE: Performs the INSERT statement to create a new record.

READ: Reads the table records based on the primary keynoted within the input parameter.

UPDATE: Executes an UPDATE statement on the table based on the specified primary key for a record within the WHERE clause of the statement.

DELETE Deletes a specified row in the WHERE clause.

YII2 is a PHP Framework for rapidly developing modern Web applications.

GII is a YII2 module, which provides web-based code generation facilities.

In this article, we are going to look at CRUD operations in YII2 using GII in detail.

### Key takeaways: 

In this article the reader will be able to:

1. Define the term CRUD

2. Create a simple database record 

3. Configure and use GiiModule in the Yii framework

4. Enable GII in Yii2

5. Store data in database using GII

### PR DESCRIPTION
**Pull request by Beatricewanjiru**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
This fixes #2111

### CODE REVIEW

**Review by kayere — COMMENTED** [review]
Great article @Beatricewanjiru, very informative and easy to follow. Just one question. I have seen that you have mentioned a folder that will be created on Linux OS after installing Xampp. Does this mean that the procedure can only be done on that OS?

**Comment by Beatricewanjiru** [comment]
@kayere that procedure is only meant for Linux users only,(For instance UBUNTU users). That's why I mentioned that statement.

**Comment by kayere** [comment]
Great. Thanks for the clarification.
The article is now ready for final review.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by ahmadmardeni1** [comment]
Congrats on your first article✨ @Beatricewanjiru 

Please go through my changes and make sure to avoid these mistakes in your next articles/tutorials.

Please do the same, to improve the reviews for the future @kayere Also, be sure to check the first-time contributor author info in the future reviews.

**Comment by kayere** [comment]
Thanks @ahmadmardeni1 - I'll be sure to do so.👍

**Pull request merged**
