### PR TITLE
Dockerizing an ASP.NET Core Web API app and SQL Server

### LINKED ISSUE #3884: Dockerizing an ASP.NET Core Web API app and SQL Server
### Proposed title of article
[Containers] Dockerizing an ASP.NET Core Web API app and SQL Server

### Introduction paragraph:
In the past years, ASP.NET web apps used to be deployed on Windows Server and IIS which were not cloud-native. However, since the introduction of open-source and cross-platform .NET Core and SQL Server for Linux, the applications are now cloud-friendly.
Moreover, with the combination of container management platforms such as Docker, it is easy to run high-performance .NET services in the cloud.
In this tutorial, we will build a CRUD application in ASP.NET Core with SQL Server and run it in a Docker container.

### Key takeaways: 
At the end of the tutorial, the learner will be able to:
- configure ASP.NET and SQL Server to run on Docker
- create a REST API to perform CRUD operations
- use Entity Framework Core to interact with SQL Server Docker container

### References: 
- https://docs.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows
- https://docs.docker.com/samples/dotnetcore/
- https://www.sqlshack.com/how-to-set-up-and-run-sql-server-docker-image/

### PR DESCRIPTION
**Pull request by lewe01**
### Article checklist

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #3884

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by hectorkambow** [comment]
plagiarism check done

**Review by Dawe-7 — CHANGES_REQUESTED** [review]
Hello @lewe01, just a few changes and this article will be ready for final review. I noticed your hero image is not the required size as specified in the EngEd [docs](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/UPLOAD_INSTRUCTIONS.md#create-author-bio-folder-structure). Kindly resize it to 600x400 pixels. Also, make sure your others images are neither very large nor very small and if any is taken from other sites, add a source.

**Comment by lewe01** [comment]
> Hello @lewe01, just a few changes and this article will be ready for final review. I noticed your hero image is not the required size as specified in the EngEd [docs](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/UPLOAD_INSTRUCTIONS.md#create-author-bio-folder-structure). Kindly resize it to 600x400 pixels. Also, make sure your others images are neither very large nor very small and if any is taken from other sites, add a source.

@Dawe-7 Am grateful for your review process. I have resized most of the images according to the suggestions you made. Most of the images are test results screenshots. 
Thank you

**Review by Dawe-7 — APPROVED** [review]
Awesome article @lewe01. Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles. Thank you.

@Kayere, this article is ready for final review.

**Comment by lewe01** [comment]
> Awesome article @lewe01. Kindly go through the changes made throughout the review process so as to improve on the flow and format of your future articles. Thank you.
> 
> @Kayere, this article is ready for final review.

@Dawe-7 Noted with thanks. I will observe the suggestions made in future articles.

**Comment by WanjaMIKE** [comment]
Merged #5183 into master

**Pull request merged**
