### PR TITLE
Integrating TailwindCss with Flask

### PR DESCRIPTION
**Pull request by Curiouspaul1**
### Article checklist
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by Curiouspaul1** [comment]
This fixes #2237

**Comment by Curiouspaul1** [comment]
@hectorkambow I just made a new PR as requested

**Comment by hectorkambow** [comment]
image

**Comment by hectorkambow** [comment]
I ve delete what I could - but im seeing missing code snippets as well - we want to make sure the article is complete.

**Comment by katungi** [comment]
Hello @Curiouspaul1 Sorry for the delay.
When creating a new PR please be sure to go through the instructions on how to keep your local copy and fork up to date. You have a lot of merge conflicts which are dangerous when published. You can find that specific information [here](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/UPLOAD_INSTRUCTIONS.md#then-use-this-every-time-before-contributing-a-new-article-to-keep-it-up-to-date)
@hectorkambow  tried to fix some but you are at a better position to clean them up.

Please clean them up asap.
Cheers.

**Comment by katungi** [comment]
@hectorkambow This article is good for final review. The author resolved the merge conflicts and the article is good to go.

**Comment by Curiouspaul1** [comment]
hello, please whats the update on this

**Comment by hectorkambow** [comment]
Thank you v much for your patience as we worked through our Repo re-structuring process. 

The purpose behind this restructure - was to better allow us to handle more volume and allow students to publish more articles and get more involved with the community (with open-source contribution and suggestions). 

With most of the changes coming to completion - we will be sure to get your article published asap. 

Thank you again - and we are looking forward to more amazing articles.

**Comment by hectorkambow** [comment]
> hello, please whats the update on this

Hello @Curiouspaul1 - we were working on clearing out the queue - and should get this one published this week. 

Thank you v much for your patience. 

Placed the final review label to make sure it does not get overlooked.

**Comment by hectorkambow** [comment]
@Curiouspaul1 

Im sorry Im just noticing - that this PR is not ready to be merged or reviewed. 

It has 76 files attached. Your PR should only have the files in your article - I think there was something done incorrectly with the git push/pulls.

cc @katungi  

Please be sure to be checking for these type of issues.

**Comment by hectorkambow** [comment]
@Curiouspaul1 

Are you in the Slack channel ?

**Comment by Curiouspaul1** [comment]
> @Curiouspaul1
> 
> Are you in the Slack channel ?

Yes

**Comment by Curiouspaul1** [comment]
> @Curiouspaul1
> 
> Im sorry Im just noticing - that this PR is not ready to be merged or reviewed.
> 
> It has 76 files attached. Your PR should only have the files in your article - I think there was something done incorrectly with the git push/pulls.
> 
> cc @katungi
> 
> Please be sure to be checking for these type of issues.

I fixed this issue the last time and @katungi verified this . My PR only has 16commits

**Comment by Curiouspaul1** [comment]
Screenshot_20210601-180530

**Comment by hectorkambow** [comment]
> > @Curiouspaul1
> > Im sorry Im just noticing - that this PR is not ready to be merged or reviewed.
> > It has 76 files attached. Your PR should only have the files in your article - I think there was something done incorrectly with the git push/pulls.
> > cc @katungi
> > Please be sure to be checking for these type of issues.
> 
> I fixed this issue the last time and @katungi verified this . My PR only has 16commits

I thought so as well - I recall that we did try to fix it. 

Not sure why Im still seeing this @Curiouspaul1 

image

**Comment by hectorkambow** [comment]
Files changed 76. That is the # im looking at.

**Comment by hectorkambow** [comment]
Again I think the best would be to make a fresh PR - after doing a Git pull on the forked master - create a new branch and include the files for your articles - your author files. 

I'll be sure to review it and publish it today - it will not go the back of the queue  - Im trying to get this one published asap.

**Comment by katungi** [comment]
Hey @Curiouspaul1  , indeed we had the same problem and you fixed it sometime back. I agree with @hectorkambow , just close and make a new PR

**Comment by Curiouspaul1** [comment]
okay ..thanks

**Pull request closed without merging**
