### PR TITLE
Is NoSQL DBMS a Replacement for Relational Database Management System?

### LINKED ISSUE #6043: Is NoSQL DBMS a Replacement for Relational Database Management System (RDMS)?
#### Proposed title of article
Is NoSQL DBMS a Replacement for Relational Database Management System (RDMS)?

#### Proposed article introduction
Relational databases have been a prevalent technology for decades. They're mature, proven, and widely implemented. Competing database products, tooling, and expertise abound. Relational databases provide a store of related data tables. These tables have a fixed schema, use SQL (Structured Query Language) to manage data, and support ACID guarantees.

No-SQL databases refer to high-performance, non-relational data stores. They excel in their ease-of-use, scalability, resilience, and availability characteristics. Instead of joining tables of normalized data, NoSQL stores unstructured or semi-structured data, often in key-value pairs or JSON documents. No-SQL databases typically don't provide ACID guarantees beyond the scope of a single database partition. High volume services that require sub-second response time favour NoSQL datastores.
#### Key takeaways 

1. Is NoSQL an RDBMS?
2. The CAP theorem
3. Can NoSQL replace RDMS? The reasons why or why not. 
4. When to choose NoSQL DBMS
5. When to choose RDMS

#### Article quality
Other available articles discuss the key differences between NoSQL DBMS and RDMS. In my case, I will present a high-level discussion on why the world is moving towards NoSQL DBMS. 

#### References
N/A

### PR DESCRIPTION
**Pull request by Greggmun**
this closes #6043

## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [ ] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

`This closes #issue-number`

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by srishilesh** [comment]
Hey @Greggmun ,

Thanks for submitting this PR.

Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you with the changes to be made.

Meanwhile, we suggest you to go through other approved PRs/published articles to see if you have missed out anything, which might avoid a potential PR closure.

Thanks.

**Comment by LinusMuema** [comment]
Hi @Greggmun 

Upon running your article through our 3rd party plagiarism checker it seemed to raise a few flags and the % was higher than we typically accept. Please see attached PDF - and revisit the article to ensure we are contributing wholly unique and original content. Be sure to see our resources page to see more info on plagiarism and what is considered as such.

[New Scan 5_48 PM Copyleaks Report.pdf](https://github.com/section-engineering-education/engineering-education/files/7973023/New.Scan.5_48.PM.Copyleaks.Report.pdf)

**Comment by Greggmun** [comment]
@LinusMuema 
I see the similarity score is 2.2% from the report you've attached. What similarity score do you normally accept.

**Comment by LinusMuema** [comment]
Hi @Greggmun 
Sorry about that I had confused your articled with another that had a similar score but had one sentence that matched another article. 

I can see yours was a description that brought about that. It's okay to proceed.

**Review by collins-a — CHANGES_REQUESTED** [review]
@Greggmun good article. The tone of the article is great. The contrast between the two DBMS is well done. However, I suggest doing a Grammarly check, then pinging me once the changes are done.

**Comment by hectorkambow** [comment]
> @Greggmun good article. The tone of the article is great. The contrast between the two DBMS is well done. However, I suggest doing a Grammarly check, then pinging me once the changes are done.

@collins-a This article should have been closed if it needed more revisions

**Comment by hectorkambow** [comment]
@Greggmun 

Good afternoon and thank you for submitting your topic suggestion. Not a problem but it seems that this PR is still quite a bit aways from being completed. 
 
In an effort to be fair to our larger EngEd community as a rule of thumb - we can only accept content (pull requests) that are complete and fully polished articles/tutorial - meaning they are ready to be published. 
 
All revisions and edits **should be completed on your own forked repo** (as to not take up room in the queue) - this allows all revisions to be done on your forked personal repo.

**Comment by Greggmun** [comment]
Hi @collins-a 
Kindly reopen this PR so that I can upload an updated version.

**Comment by collins-a** [comment]
> Hi @collins-a Kindly reopen this PR so that I can upload an updated version.

Hello @Greggmun, you shall have to submit a duplicate PR with the changes then ping me for a review.

**Pull request closed without merging**
