### PR TITLE
Recovering Wi-Fi Passwords from Windowx/Mac/Linux

### LINKED ISSUE #3839: Uncovering WiFi Passwords From Windows
### Proposed title of article
Uncovering WiFi Passwords From Windows

### Introduction paragraph (2-3 paragraphs):

In windows Wi-Fi passwords from saved Wi-Fi networks are hidden from the user, unlike other OS i.e. android, windows has terminals that can be used to acquire the Wi-Fi passwords from the saved Wi-Fi networks in the device.
With the use of PowerShell and cmd (also known as command prompt) we can be able to find the hidden Wi-Fi passwords by using simple cmd and PowerShell commands. This will enable users to use the passwords to connect other devices to the same Wi-Fi networks.

### Key takeaways: 
What is PowerShell?
What is cmd?
Which Windows versions have PowerShell installed?
Steps to find the WiFi password using cmd
Steps to find the WiFi password using PowerShell

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by LucidRay**
#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #3839

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by louisefindlay23** [comment]
@LucidRay, please remove the backticks from This closes to correctly link your topic suggestion to your PR.

**Comment by LinusMuema** [comment]
@ahmadmardeni1 is doing plagiarism checks this week

**Comment by zolomohan** [comment]
> > @LucidRay, please remove the backticks from This closes to correctly link your topic suggestion to your PR.
> 
> Edited it for you @LucidRay. Make sure you don't add backticks the next time 😃
> 
> @LucidRay regarding the article, CMD and Powershell is very similar. Both the shells are using the same commands in your article. I don't think we need two separate sections for each shell. You can combine them together and say that the commands are the same for both CMD and Powershell.
> 
> But doing this is going to make this article very short. Could you include how to recover the wifi password from all the operating systems like Mac and Linux too? This will add more value to this article.
> 
> cc @hectorkambow @louisefindlay23

@LucidRay any updates regarding this?

**Comment by LucidRay** [comment]
Hello, @zolomohan thanks for the idea....still working on it

**Comment by hectorkambow** [comment]
Team can we please take a look at this (it just need a tech review) & final review.

I've pinged the peer reviewer on 10/22 - with no major response.

Thank you 👀

@section-engineering-education/content-moderator-team 

Same with this one.

**Comment by hectorkambow** [comment]
@Kayere  Thank you sir. 
🚀

**Comment by zolomohan** [comment]
@LucidRay @hectorkambow @Kayere 

The tech review for this article is completed. Something must've gone wrong when I updated the Labels 🤔 
I've used WSL and a Macbook to verify the commands.

We can proceed with a final review.

I'll update the front matter now.

**Comment by zolomohan** [comment]
@hectorkambow @section-engineering-education/content-moderator-team 

Added Front Matter. This PR is good to go ✔️

**Review by zolomohan — APPROVED** [review]

**Comment by ahmadmardeni1** [comment]
Welcome to Section EngEd @LucidRay
This article is light on substance and the info provided here can be found easily on the internet. Is there anything you can add to make your article unique/original? 
cc @zolomohan

**Comment by hectorkambow** [comment]
👍 

cc @zolomohan  - lets be sure to go through articles with a more rigorous eye to avoid more edits towards the end (or closures at the end of the review). 

🚀

**Pull request closed without merging**
