### PR TITLE
Maps api in a webpage

### LINKED ISSUE #2633: Using Google Maps API in your website
### Proposed title of article
Using Google Maps API in your website

### Introduction paragraph (2-3 paragraphs):
Google Maps API is web mapping API that allows  developers to easily add location maps in a website. The API provides satellite views, streets view, aerial photography and street maps. This API is very useful to locate places in a website like businesses, sportsgrounds, roads and streets. 

This article will take the user through implementation of the API in JavaScript such that by the end of the article, a user should have a Google Map perfectly imbedded into a website with a functionality to autocomplete places search and get direction on the map using Places and Directs API. The user will be enter the location to start and the destination then we visualize the directions to the place and estimate the distance 

### Key takeaways: 
1. Getting Google  API keys for Google map, Places, and Directions
2.  Imbedding Google Map into a website using JavaScript
3. Adding place Markers and Different views in Google Maps
4.  Getting directions on a map
5. Autocomplete city names 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### PR DESCRIPTION
**Pull request by mercymeave**
### Article checklist

**ATTENTION: In your PR - add the ISSUE (topic form) # that this PR corresponds to. You can do this by also adding a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.**
      
      
**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**If you have not already please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve our overall technical writing.**

#### Preliminary Checks - Formatting and Structure 
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker? We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**

This fixes #2633

### CODE REVIEW

**Review by jerimkaura — CHANGES_REQUESTED** [review]
Hello @mercymeave,

kindly link your table of content to the various sections of your article to enable easier navigation.

Ping when you are done or in case of any issues.

**Comment by mercymeave** [comment]
@jerimkaura check it out.

**Review by jerimkaura — APPROVED** [review]

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by jerimkaura** [comment]
This is an amazing article here @mercymeave :rocket: 

 I like how your flow was smooth with an easy language. You can improve to make it even better by checking out the corrections I made.

@hectorkambow  would you please give it a final review?

**Comment by Kayere** [comment]
Great article @mercymeave.
Thank you for the review @jerimkaura.

**Pull request merged**
