### PR TITLE
[Duplicate] How to generate reports in a SpringBoot App leveraging Jaspersoft 

### LINKED ISSUE #4968: [Java] How to generate reports in a SpringBoot App leveraging Jasper
####  introduction
We use reports in our day to day activities whether we are purchasing products and services online or managing the transactions of an information system in an organisation. 

These reports include summary reports, financial reports, inventory reports, sales report and budget report just but to mention a few. These reports help in generating insights to an organisation and making the right decision based on the knowledge generated from them.

For example, an  inventory report can help an organisation on deciding on the appropriate reorder level to use during acquisition of products.

In this tutorial, the reader will learn how to design an inventory report, integrate it in a SpringBoot application and use custom products to generate a standard report that can be used in an organisation.

#### Key takeaways 
- What is Jasper
- What is Jasper Studio
- How to design a report
- How to integrate Jasper in our application
- How to generate the report using our custom data from the database

#### References
N/A

#### Article quality
This article focuses on how to add the functionality of printing a report in a web page allowing the user to realise the action with just the press of a button.
The article also explains in details how to implement a report having the format of a pdf and clues on how other type of formats can be generated where necessary.

### PR DESCRIPTION
**Pull request by davidmbochi**
## Our **Peer Reviewer and Content Moderator teams do NOT provide any revisions services.** All revisions and edits should be completed on your own forked repo (as to not take up room in the queue) in order for our team to review them all in a timely manner. 

**ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.**

>As a rule of thumb - please be sure to only submit articles (pull requests) that are fully polished and ready to be published. Be sure to go through our resources documents for extra and 3rd party (vetted) resources to help improve overall technical writing.

> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and tricks on how to improve your overall technical writing so reviews are swifter, increase the chance of a payout and provide more value to our readers.

> For first-time contributors and for more details on our submission guidelines, **see our [Contributing Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**.

#### Formatting and structure checks
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/CONTRIBUTING.md)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Is the article you are submitting an in-depth and unique article? Does it go beyond what is in the official docs and what is covered in other blog sites. See these articles as [examples](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md).
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**

- [x] Have you included a hero image that is **600x400 pixels**, under **300KB in size**, and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
      
#### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you checked your code runs correctly and you've highlighted all necessary dependencies for installation?
- [x] Are the software programs and packages you're highlighting in your article up to date, using current versions and not deprecated?

This closes #4968 

> Finally, delete the article checklist notes in blockquotes and submit your PR. We look forward to reviewing your article.

### CODE REVIEW

**Comment by davidmbochi** [comment]
Hello @john-amiscaray 
I have added the requested changes.

**Comment by john-amiscaray** [comment]
@davidmbochi there were a couple of minor inaccuracies I fixed just now that I forgot to mention in my last review. The `spring.jpa.hibernate.ddl-auto` property does something different than what you talked about in the article. See [this post](https://stackoverflow.com/a/42147995) for clarification. As well the `spring.jpa.properties.hibernate.format_sql` is for formatting the printed SQL queries. In the article, you said that was for displaying them.

**Comment by john-amiscaray** [comment]
@davidmbochi It's looking all good now in terms of the contents of the article. There is one small thing we forgot, however: your article is missing a hero image. Please add one.

**Comment by davidmbochi** [comment]
> @davidmbochi It's looking all good now in terms of the contents of the article. There is one small thing we forgot, however: your article is missing a hero image. Please add one.

Hello @john-amiscaray,
I have added the hero image

**Comment by john-amiscaray** [comment]
> > @davidmbochi It's looking all good now in terms of the contents of the article. There is one small thing we forgot, however: your article is missing a hero image. Please add one.
> 
> Hello @john-amiscaray, I have added the hero image

@davidmbochi The image must be as close to 600X400 pixels as possible. Please resize it if possible or use a new image.

**Comment by davidmbochi** [comment]
@john-amiscaray 
The image should work now

**Comment by john-amiscaray** [comment]
@davidmbochi nice work. Should be ready for the final review now.

**Comment by davidmbochi** [comment]
> @davidmbochi nice work. Should be ready for the final review now.

Thank you @john-amiscaray 🙂

**Comment by hectorkambow** [comment]
jumping on this one

**Comment by hectorkambow** [comment]
Overall very nice work Gents 🚀  

@davidmbochi 
Please be sure you update your forked repo before you submit another PR 👍 (to get the latest changes made to the main repo).

**Pull request merged**
